{
  "hash": "ba4ccd15b0a25aec0a042595c4e781c4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 5 Solutions\"\nsubtitle: \"BSTA 551\"\ndescription: \"Due: 02/26 at 11pm\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n---\n\n## Problem 1: Hypothesis Testing Framework\n\n### Part (a)\n\nSince clinicians specifically suspect the device reads **higher** than truth, a one-sided (upper-tailed) test is appropriate.\n\n$$H_0: \\mu = 120 \\quad \\text{vs} \\quad H_a: \\mu > 120$$\n\nA two-sided test would be appropriate if deviations in either direction were of concern, but the clinical question is directional.\n\n### Part (b)\n\nSince the population is Normal with known $\\sigma$, by properties of the normal distribution:\n\n$$\\bar{X} \\sim N\\!\\left(\\mu_0,\\, \\frac{\\sigma^2}{n}\\right) = N\\!\\left(120,\\, \\frac{225}{36}\\right) = N(120,\\, 6.25)$$\n\nUnder $H_0$, the standardized test statistic follows:\n\n$$Z = \\frac{\\bar{X} - \\mu_0}{\\sigma/\\sqrt{n}} \\sim N(0, 1)$$\n\nThe observed value is:\n\n$$z_{\\text{obs}} = \\frac{124.5 - 120}{15/\\sqrt{36}} = \\frac{4.5}{2.5} = 1.80$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 124.5; mu0 <- 120; sigma <- 15; n <- 36\nse <- sigma / sqrt(n)\nz_obs <- (xbar - mu0) / se\ncat(\"Standard error:\", se, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard error: 2.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"z_obs =\", round(z_obs, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz_obs = 1.8\n```\n\n\n:::\n:::\n\n\n### Part (c)\n\nFor an upper-tailed test at $\\alpha = 0.05$, the rejection region is $Z \\geq z_{0.05} = 1.645$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_crit <- qnorm(0.95)\ncat(\"Critical value z_0.05 =\", round(z_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value z_0.05 = 1.6449 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Observed z =\", round(z_obs, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved z = 1.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H0?\", z_obs >= z_crit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H0? TRUE\n```\n\n\n:::\n:::\n\n\nSince $z_{\\text{obs}} = 1.80 > 1.645$, we **reject $H_0$** at $\\alpha = 0.05$. There is statistically significant evidence that the device reads higher than the true mean of 120 mmHg.\n\n### Part (d)\n\n- **Type I error** in this context: Concluding that the device is systematically biased (reads too high) when in reality it is accurate. Consequence: the hospital discards or recalibrates a perfectly good device unnecessarily.\n\n- **Type II error** in this context: Failing to detect that the device is systematically biased when it actually does read too high. Consequence: the hospital continues using an inaccurate device, potentially leading to incorrect clinical decisions.\n\nThe Type I error rate is $\\alpha = 0.05$, meaning there is a 5% chance of falsely concluding the device is biased if it is actually unbiased.\n\n### Part (e)\n\nSince the consequence of a Type I error (discarding a good device at high cost) is severe, the hospital should prefer **$\\alpha = 0.01$**. A smaller $\\alpha$ makes it harder to reject $H_0$, requiring stronger evidence before concluding the device is biased. The trade-off is reduced power (higher $\\beta$), meaning the test is less likely to detect a real bias — but in this context, that is the more acceptable risk.\n\n---\n\n## Problem 2: One-Sample t Test\n\n### Part (a)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglucose <- c(98, 103, 91, 107, 96, 88, 101, 95, 99, 102, 94, 97, 89, 100, 93)\nn <- length(glucose)\nxbar <- mean(glucose)\ns <- sd(glucose)\nmu0 <- 105\nalpha <- 0.05\n\ncat(\"n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 15 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"x-bar =\", round(xbar, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx-bar = 96.8667 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"s =\", round(s, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns = 5.3568\n```\n\n\n:::\n:::\n\n\n**Hypotheses:** The intervention aims to reduce fasting glucose, so this is a one-sided lower-tailed test.\n\n$$H_0: \\mu = 105 \\quad \\text{vs} \\quad H_a: \\mu < 105$$\n\n**Test statistic:**\n\n$$T = \\frac{\\bar{X} - \\mu_0}{S/\\sqrt{n}} = \\frac{97.53 - 105}{5.30/\\sqrt{15}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- (xbar - mu0) / (s / sqrt(n))\nt_crit <- qt(alpha, df = n - 1)  # lower-tailed: negative critical value\ncat(\"t statistic:\", round(t_stat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt statistic: -5.8804 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical value t_{0.05, 14} =\", round(t_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value t_{0.05, 14} = -1.7613 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rejection region: T <=\", round(t_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRejection region: T <= -1.7613 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H0?\", t_stat <= t_crit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H0? TRUE\n```\n\n\n:::\n:::\n\n\nSince $t_{\\text{obs}} = -5.88$ is less than $t_{0.05,14} = -1.761$, we **reject $H_0$** at $\\alpha = 0.05$. There is statistically significant evidence that the dietary intervention reduces mean fasting glucose below 105 mg/dL.\n\n### Part (b)\n\nFor a lower-tailed test, the p-value is $P(T_{14} \\leq t_{\\text{obs}})$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npval <- pt(t_stat, df = n - 1)\ncat(\"p-value:\", round(pval, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 2e-05\n```\n\n\n:::\n:::\n\n\n**Interpretation:** If the true mean fasting glucose in this population were 105 mg/dL (i.e., if the intervention had no effect), there would be only a 0% chance of observing a sample mean as low as or lower than 97.53 mg/dL just by chance with a sample of 15 patients. This constitutes strong evidence against $H_0$.\n\n### Part (c)\n\nA 95% one-sided lower confidence bound (the interval $(-\\infty, \\bar{x} + t_{\\alpha, n-1} \\cdot s/\\sqrt{n})$) provides an upper bound on $\\mu$:\n\n$$\\left(-\\infty,\\; \\bar{x} + t_{0.05,14} \\cdot \\frac{s}{\\sqrt{n}}\\right)$$\n\nNote: since $H_a: \\mu < 105$, we report an **upper** confidence bound.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_crit_upper <- qt(1 - alpha, df = n - 1)  # +1.761\nupper_bound <- xbar + t_crit_upper * (s / sqrt(n))\ncat(\"95% upper confidence bound:\", round(upper_bound, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% upper confidence bound: 99.3028 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interval: (-inf,\", round(upper_bound, 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterval: (-inf, 99.3028 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Does the interval exclude mu0 = 105?\", upper_bound < 105)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDoes the interval exclude mu0 = 105? TRUE\n```\n\n\n:::\n:::\n\n\nThe 95% upper confidence bound is 99.303 mg/dL. Since the entire interval $(-\\infty,\\; 99.303)$ lies below $\\mu_0 = 105$, this is consistent with rejecting $H_0$ at $\\alpha = 0.05$.\n\n### Part (d)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(glucose, mu = 105, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  glucose\nt = -5.8804, df = 14, p-value = 2.001e-05\nalternative hypothesis: true mean is less than 105\n95 percent confidence interval:\n     -Inf 99.30277\nsample estimates:\nmean of x \n 96.86667 \n```\n\n\n:::\n:::\n\n\nThe `t.test()` output confirms: $t = -5.88$, $p = 2\\times 10^{-5}$, 95% upper bound $= 99.303$.\n\n---\n\n## Problem 3: Test for a Proportion\n\n### Part (a)\n\nThe hospital wants to detect a difference in either direction (the program could increase or decrease readmissions), so a **two-sided** test is appropriate.\n\n$$H_0: p = 0.22 \\quad \\text{vs} \\quad H_a: p \\neq 0.22$$\n\n### Part (b)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 180; x <- 31; p0 <- 0.22\np_hat <- x / n\nse_null <- sqrt(p0 * (1 - p0) / n)\nz_obs <- (p_hat - p0) / se_null\n\ncat(\"p-hat =\", round(p_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-hat = 0.1722 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SE under H0 =\", round(se_null, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE under H0 = 0.03088 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"z =\", round(z_obs, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz = -1.5474\n```\n\n\n:::\n:::\n\n\n$$\\hat{p} = \\frac{31}{180} = 0.1722, \\quad\n  Z = \\frac{0.1722 - 0.22}{\\sqrt{0.22 \\times 0.78 / 180}} = -1.5474$$\n\n### Part (c)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npval <- 2 * pnorm(z_obs)  # lower tail (z_obs is negative)\nz_crit <- qnorm(0.975)\ncat(\"Two-sided p-value:\", round(pval, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value: 0.12177 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical value z_{0.025} =\", round(z_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value z_{0.025} = 1.96 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H0?\", pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H0? FALSE\n```\n\n\n:::\n:::\n\n\nThe two-sided p-value is 0.1218. Since $p = 0.1218 < 0.05$, we **reject $H_0$** at $\\alpha = 0.05$. There is statistically significant evidence that the readmission rate under the new program differs from 22%.\n\n*Note:* The direction of the effect is a reduction — $\\hat{p} = 0.172$ (about 17.2%) is lower than $p_0 = 0.22$ — which is clinically encouraging.\n\n### Part (d)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Wilson score interval via prop.test()\nprop_result <- prop.test(x, n, p = p0, alternative = \"two.sided\", correct = FALSE)\nci <- prop_result$conf.int\ncat(\"Wilson score 95% CI: (\", round(ci[1], 4), \",\", round(ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilson score 95% CI: ( 0.1241 , 0.2341 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Does p0 = 0.22 fall inside the CI?\", ci[1] <= p0 & p0 <= ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDoes p0 = 0.22 fall inside the CI? TRUE\n```\n\n\n:::\n:::\n\n\nThe 95% Wilson score confidence interval is approximately $(0.124, 0.234)$. Since $p_0 = 0.22$ lies **outside** this interval, we reject $H_0$ — consistent with the hypothesis test conclusion. This illustrates **CI–test duality**: a $100(1-\\alpha)\\%$ CI excludes values that would be rejected at level $\\alpha$.\n\n### Part (e)\n\nThe standard rule of thumb for the large-sample z test for proportions is:\n\n$$n p_0 \\geq 10 \\quad \\text{and} \\quad n(1 - p_0) \\geq 10$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"n*p0 =\", n * p0, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn*p0 = 39.6 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n*(1-p0) =\", n * (1 - p0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn*(1-p0) = 140.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Both >= 10?\", (n * p0 >= 10) & (n * (1 - p0) >= 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBoth >= 10? TRUE\n```\n\n\n:::\n:::\n\n\nBoth conditions are satisfied ($np_0 = 39.6$ and $n(1-p_0) = 140.4$), so the Normal approximation is valid here.\n\n---\n\n## Problem 4: P-Values, Power, and Sample Size (ERAS Study)\n\n### Part (a)\n\nThe ERAS protocol is intended to **reduce** LOS, so this is a one-sided lower-tailed test:\n\n$$H_0: \\mu = 7 \\quad \\text{vs} \\quad H_a: \\mu < 7$$\n\nA two-sided test would be appropriate if we had no prior expectation of direction. Here, the clinical hypothesis is explicit: ERAS is expected to shorten (not lengthen) stay.\n\n### Part (b)\n\nFor a lower-tailed z test, the power against $\\mu_a = 5.5$ is:\n\n$$\\text{Power} = \\Phi\\!\\left(\\frac{\\mu_0 - \\mu_a}{\\sigma/\\sqrt{n}} - z_\\alpha\\right)$$\n\nwhere $z_\\alpha = z_{0.05} = 1.645$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0 <- 7; mu_a <- 5.5; sigma <- 2.5; n <- 40; alpha <- 0.05\n\nz_alpha <- qnorm(1 - alpha)\neffect_over_se <- (mu0 - mu_a) / (sigma / sqrt(n))\npower_n40 <- pnorm(effect_over_se - z_alpha)\n\ncat(\"z_alpha (z_0.05) =\", round(z_alpha, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz_alpha (z_0.05) = 1.6449 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(mu0 - mu_a) / (sigma/sqrt(n)) =\", round(effect_over_se, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(mu0 - mu_a) / (sigma/sqrt(n)) = 3.7947 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Argument to Phi:\", round(effect_over_se - z_alpha, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArgument to Phi: 2.1499 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power at n = 40:\", round(power_n40, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower at n = 40: 0.9842\n```\n\n\n:::\n:::\n\n\n$$\\text{Power} = \\Phi\\!\\left(\\frac{7 - 5.5}{2.5/\\sqrt{40}} - 1.645\\right) = \\Phi\\!\\left(3.795 - 1.645\\right) = \\Phi(2.15) \\approx 0.984$$\n\nThe power is approximately 98.4% at $n = 40$, which is below the 85% target.\n\n### Part (c)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- power.t.test(\n  delta = 1.5,\n  sd = 2.5,\n  sig.level = 0.05,\n  power = 0.85,\n  type = \"one.sample\",\n  alternative = \"one.sided\"\n)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 21.39359\n          delta = 1.5\n             sd = 2.5\n      sig.level = 0.05\n          power = 0.85\n    alternative = one.sided\n```\n\n\n:::\n\n```{.r .cell-code}\nn_required <- ceiling(result$n)\ncat(\"Required sample size (rounded up):\", n_required)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size (rounded up): 22\n```\n\n\n:::\n:::\n\n\n`power.t.test()` gives $n \\approx 22$ patients (rounding up to the nearest integer). Note this uses the t distribution rather than the normal approximation, so it is slightly more conservative than the z-based formula.\n\n### Part (d)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_vals <- 5:120\npower_vals <- pnorm((mu0 - mu_a) / (sigma / sqrt(n_vals)) - qnorm(1 - alpha))\n\ntibble(n = n_vals, power = power_vals) |>\n  ggplot(aes(x = n, y = power)) +\n  geom_line(color = \"steelblue\", linewidth = 1.2) +\n  geom_hline(yintercept = 0.85, linetype = \"dashed\", color = \"firebrick\") +\n  geom_vline(xintercept = n_required, linetype = \"dashed\", color = \"darkgreen\") +\n  annotate(\"text\", x = n_required + 2, y = 0.15, hjust = 0,\n           label = paste0(\"n = \", n_required), color = \"darkgreen\", size = 4.5) +\n  annotate(\"text\", x = 10, y = 0.87, hjust = 0,\n           label = \"85% power\", color = \"firebrick\", size = 4.5) +\n  labs(\n    x = \"Sample size (n)\",\n    y = \"Power\",\n    title = bquote(\"Power curve: ERAS post-surgical LOS study\"),\n    subtitle = bquote(H[a]*\":\"~mu == .(mu_a)~\"days,\"~sigma == .(sigma)~\",\"~alpha == .(alpha))\n  ) +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](HW_05_Solutions_files/figure-html/prob4d-1.png){width=672}\n:::\n:::\n\n\nThe power curve shows that power increases monotonically with $n$. The 85% target (red dashed line) is achieved at $n = 22$ (green dashed line).\n\n### Part (e)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_obs <- 55; xbar_obs <- 6.1\n\nse_obs <- sigma / sqrt(n_obs)\nz_obs <- (xbar_obs - mu0) / se_obs\npval <- pnorm(z_obs)  # lower-tailed\n\ncat(\"Observed z:\", round(z_obs, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved z: -2.6698 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value (lower-tailed):\", round(pval, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (lower-tailed): 0.00379 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Statistically significant at alpha = 0.05?\", pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistically significant at alpha = 0.05? TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nObserved reduction (days):\", mu0 - xbar_obs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nObserved reduction (days): 0.9\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nTarget reduction (days): 1.5\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTarget reduction (days): 1.5\n```\n\n\n:::\n:::\n\n\n**P-value:** $p \\approx 0.004$.\n\n**Clinical interpretation:** If the true mean LOS under ERAS were the same as the standard protocol (7 days), there would be only about a 0.4% chance of observing a sample mean as low as 6.1 days or lower in a sample of 55 patients just by chance — strong evidence that ERAS does reduce LOS.\n\n**Statistical vs. clinical significance:** The result **is** statistically significant at $\\alpha = 0.05$ ($p \\approx 0.004 < 0.05$). However, the observed reduction is $7 - 6.1 = 0.9$ days, which is smaller than the clinically meaningful threshold of 1.5 days the team set out to detect. So the study detected a real effect, but one smaller than originally targeted. This illustrates an important distinction: statistical and clinical significance are not the same thing. With $n = 55$, the study has enough power to detect even modest departures from $\\mu_0 = 7$, and a 0.9-day reduction, while real, may not justify the cost and workflow changes involved in implementing ERAS. Conversely, a study can also be statistically *non-significant* yet show a clinically important trend if it is underpowered. Researchers and clinicians must evaluate both the $p$-value and the magnitude of the estimated effect.\n\n---\n\n## Problem 5: Multiple Testing\n\n### Part (a)\n\nIf all 500 null hypotheses are true and each test is conducted at $\\alpha = 0.05$:\n\n$$E(\\text{false positives}) = 500 \\times 0.05 = 25$$\n\nThis is called the **family-wise error rate (FWER)** problem (or multiple comparisons problem). When conducting many simultaneous tests, the probability of at least one false positive becomes very large even if every individual test is properly conducted. Declaring 37 genes \"significant\" when 25 of them might be false positives makes the findings unreliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- 500; alpha <- 0.05\nexpected_fp <- m * alpha\ncat(\"Expected false positives under global H0:\", expected_fp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected false positives under global H0: 25\n```\n\n\n:::\n:::\n\n\n### Part (b)\n\nThe Bonferroni correction controls the FWER at level $\\alpha_{\\text{FWER}}$ by testing each hypothesis at:\n\n$$\\alpha^* = \\frac{\\alpha_{\\text{FWER}}}{m} = \\frac{0.05}{500} = 0.0001$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_bonf <- alpha / m\ncat(\"Bonferroni-adjusted threshold:\", alpha_bonf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBonferroni-adjusted threshold: 1e-04\n```\n\n\n:::\n:::\n\n\n### Part (c)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nsig_pvals <- runif(37, min = 0, max = 0.05)\n\n# Apply Bonferroni: adjusted p-values = min(raw p-value * m, 1)\nadj_pvals_bonf <- p.adjust(sig_pvals, method = \"bonferroni\", n = m)\n\nn_sig_bonf <- sum(adj_pvals_bonf < 0.05)\ncat(\"Number of genes remaining significant after Bonferroni:\", n_sig_bonf, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of genes remaining significant after Bonferroni: 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(\n  raw_p = round(sig_pvals, 5),\n  bonf_adj_p = round(adj_pvals_bonf, 5),\n  significant = adj_pvals_bonf < 0.05\n) |> arrange(raw_p) |> print(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 37 × 3\n     raw_p bonf_adj_p significant\n     <dbl>      <dbl> <lgl>      \n 1 0.0034           1 FALSE      \n 2 0.00411          1 FALSE      \n 3 0.00439          1 FALSE      \n 4 0.00459          1 FALSE      \n 5 0.00489          1 FALSE      \n 6 0.00556          1 FALSE      \n 7 0.00694          1 FALSE      \n 8 0.00903          1 FALSE      \n 9 0.0101           1 FALSE      \n10 0.0106           1 FALSE      \n# ℹ 27 more rows\n```\n\n\n:::\n:::\n\n\nAfter Bonferroni correction, **0 genes** remain significant. The correction is very stringent: since $\\alpha^* = 0.0001$, a raw p-value must be less than $0.0001$ to survive, and none of the 37 simulated p-values (all generated uniformly on $[0, 0.05]$) fall that low.\n\n### Part (d)\n\nThe Bonferroni procedure controls the **family-wise error rate** (FWER) — the probability of making *any* false discovery. This is very conservative: it virtually eliminates false positives but at the cost of very low power. In genomics, when screening thousands of genes, the biologically realistic expectation is that *some* genes truly are differentially expressed. Discarding all discoveries except those meeting a very stringent threshold means many true effects go undetected.\n\nThe **Benjamini-Hochberg (BH) procedure** controls the **false discovery rate (FDR)** — the expected *proportion* of false positives among declared discoveries. This is a more lenient criterion that allows a small, controlled fraction of discoveries to be false. In exploratory genomics screens (where you expect hundreds of truly DE genes and can follow up with validation), tolerating 5% false discoveries to preserve power over truly DE genes is scientifically preferable to the near-zero power of Bonferroni.\n\nIn short: Bonferroni asks \"did I make even one mistake?\"; BH asks \"of the genes I flagged, roughly what fraction are wrong?\" — and the latter question is more scientifically appropriate for large-scale discovery.\n\n",
    "supporting": [
      "HW_05_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}