{
  "hash": "9f3122e7284d43f40bf92dbf8ce6216a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 7 Solutions\"\nsubtitle: \"BSTA 551\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n---\n\n## Problem 1: Two-Sample t-Tests for Means\n\n### Part (a) — Welch–Satterthwaite degrees of freedom\n\nSummary statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- 22; xbar1 <- 412.8; s1 <- 68.4  # COPD\nn2 <- 25; xbar2 <- 356.2; s2 <- 41.7  # Controls\n\n# Welch-Satterthwaite\nv1 <- s1^2 / n1\nv2 <- s2^2 / n2\n\nnu_hat <- (v1 + v2)^2 / (v1^2 / (n1 - 1) + v2^2 / (n2 - 1))\ncat(sprintf(\"v1 = s1^2/n1 = %.4f\\n\", v1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nv1 = s1^2/n1 = 212.6618\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"v2 = s2^2/n2 = %.4f\\n\", v2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nv2 = s2^2/n2 = 69.5556\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Numerator:   (v1 + v2)^2 = %.4f\\n\", (v1 + v2)^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumerator:   (v1 + v2)^2 = 79646.6711\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Denominator: %.4f\\n\", v1^2/(n1-1) + v2^2/(n2-1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDenominator: 2355.1563\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"nu_hat = %.2f  -->  round down to %d\\n\", nu_hat, floor(nu_hat)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnu_hat = 33.82  -->  round down to 33\n```\n\n\n:::\n:::\n\n\n$$\\hat{\\nu} = \\frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\dfrac{(s_1^2/n_1)^2}{n_1-1} + \\dfrac{(s_2^2/n_2)^2}{n_2-1}}$$\n\nThe Welch–Satterthwaite approximation gives $\\hat{\\nu} \\approx 33.8$, rounded down to $33$ degrees of freedom.\n\n---\n\n### Part (b) — Welch t-test (one-sided)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSE_diff <- sqrt(s1^2/n1 + s2^2/n2)\nt_obs   <- (xbar1 - xbar2) / SE_diff\np_one   <- pt(t_obs, df = nu_hat, lower.tail = FALSE)\n\ncat(sprintf(\"SE(xbar1 - xbar2) = %.4f\\n\", SE_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE(xbar1 - xbar2) = 16.7993\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"t_obs = %.4f\\n\", t_obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_obs = 3.3692\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"df    = %.2f\\n\", nu_hat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf    = 33.82\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"p-value (one-sided, upper) = %.5f\\n\", p_one))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (one-sided, upper) = 0.00095\n```\n\n\n:::\n:::\n\n\n**Test statistic:** $T_W = \\dfrac{412.8 - 356.2}{\\sqrt{68.4^2/22 + 41.7^2/25}} = 3.369$\n\n**Degrees of freedom:** $\\hat{\\nu} \\approx 33.8$\n\n**$p$-value:** $\\ensuremath{9.5\\times 10^{-4}}$\n\n**Conclusion:** At $\\alpha = 0.05$ we reject $H_0$ ($p < 0.05$). There is statistically significant evidence that mean plasma fibrinogen is higher in COPD patients than in healthy controls.\n\n---\n\n### Part (c) — 95% two-sided CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_crit <- qt(0.975, df = nu_hat)\nci_lo  <- (xbar1 - xbar2) - t_crit * SE_diff\nci_hi  <- (xbar1 - xbar2) + t_crit * SE_diff\n\ncat(sprintf(\"t_crit (df = %.1f) = %.4f\\n\", nu_hat, t_crit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_crit (df = 33.8) = 2.0326\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI: (%.2f, %.2f) mg/dL\\n\", ci_lo, ci_hi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: (22.45, 90.75) mg/dL\n```\n\n\n:::\n:::\n\n\n**Interpretation:** We are 95% confident that the true mean plasma fibrinogen is between 22.5 and 90.7 mg/dL higher in COPD patients than in healthy controls. Because the entire interval is positive and excludes zero, the data provide strong evidence of a meaningful difference.\n\n---\n\n### Part (d) — F-test for equality of variances\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_obs  <- s1^2 / s2^2\ndf1    <- n1 - 1\ndf2    <- n2 - 1\n\n# Two-sided p-value: 2 * min(lower, upper) tail\np_F <- 2 * min(pf(F_obs, df1, df2), pf(F_obs, df1, df2, lower.tail = FALSE))\n\ncat(sprintf(\"F = s1^2/s2^2 = %.4f^2 / %.4f^2 = %.4f\\n\", s1, s2, F_obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF = s1^2/s2^2 = 68.4000^2 / 41.7000^2 = 2.6905\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"df1 = %d, df2 = %d\\n\", df1, df2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf1 = 21, df2 = 24\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Two-sided p-value = %.5f\\n\", p_F))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value = 0.02115\n```\n\n\n:::\n:::\n\n\n**Hypotheses:** $H_0: \\sigma_1^2 = \\sigma_2^2$ vs. $H_a: \\sigma_1^2 \\neq \\sigma_2^2$\n\n**Test statistic:** $F_0 = s_1^2 / s_2^2 = 4678.6 / 1738.9 = 2.691$ on $(21, 24)$ df\n\n**$p$-value:** $0.0211$\n\nThe $F$-test is highly significant, providing strong evidence that the population variances are *unequal*. **The Welch $t$-test is therefore the more appropriate choice** because it does not assume equal variances. The pooled $t$-test would be invalid here.\n\n---\n\n### Part (e) — Pooled t-test for comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSp2 <- ((n1-1)*s1^2 + (n2-1)*s2^2) / (n1 + n2 - 2)\nSp  <- sqrt(Sp2)\nSE_pool <- Sp * sqrt(1/n1 + 1/n2)\nt_pool  <- (xbar1 - xbar2) / SE_pool\ndf_pool <- n1 + n2 - 2\np_pool  <- pt(t_pool, df = df_pool, lower.tail = FALSE)\nt_crit_pool <- qt(0.975, df = df_pool)\nci_pool <- c((xbar1 - xbar2) - t_crit_pool * SE_pool,\n             (xbar1 - xbar2) + t_crit_pool * SE_pool)\n\ncat(sprintf(\"Sp^2 = %.2f  -->  Sp = %.2f\\n\", Sp2, Sp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSp^2 = 3110.74  -->  Sp = 55.77\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"SE_pool = %.4f\\n\", SE_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE_pool = 16.3042\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"t_pool = %.4f, df = %d\\n\", t_pool, df_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_pool = 3.4715, df = 45\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"p-value (one-sided) = %.5f\\n\", p_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (one-sided) = 0.00058\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% Pooled CI: (%.2f, %.2f)\\n\", ci_pool[1], ci_pool[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Pooled CI: (23.76, 89.44)\n```\n\n\n:::\n:::\n\n\n**Comparison:**\n\n| Method | $t$ | df | 95% CI | $p$-value |\n|--------|-----|-----|--------|-----------|\n| Welch | 3.369 | 33.8 | (22.5, 90.7) | \\ensuremath{9.5\\times 10^{-4}} |\n| Pooled | 3.472 | 45 | (23.8, 89.4) | \\ensuremath{5.8\\times 10^{-4}} |\n\nThe two procedures give similar conclusions here because both $n_1$ and $n_2$ are moderate. However, the pooled SE is inflated relative to the Welch SE because the larger variance (COPD, $s_1 = 68.4$) is averaged with the smaller (Controls, $s_2 = 41.7$). When sample sizes are **unequal and the larger variance is in the smaller group**, the pooled test can be anti-conservative (actual Type I error exceeds nominal $\\alpha$). The Welch test does not rely on equal-variance assumptions and is generally preferred.\n\n---\n\n## Problem 2: Two-Sample Inference for Proportions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnA <- 105; xA <- 89   # Regimen A\nnB <- 105; xB <- 76   # Regimen B\n\nphatA <- xA / nA\nphatB <- xB / nB\ndiff_hat <- phatA - phatB\n\ncat(sprintf(\"phat_A = %d/%d = %.4f\\n\", xA, nA, phatA))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphat_A = 89/105 = 0.8476\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"phat_B = %d/%d = %.4f\\n\", xB, nB, phatB))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphat_B = 76/105 = 0.7238\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"phat_A - phat_B = %.4f\\n\", diff_hat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphat_A - phat_B = 0.1238\n```\n\n\n:::\n:::\n\n\n### Part (a) — Verify large-sample conditions\n\nThe four conditions for $\\hat{p}_1 - \\hat{p}_2 \\approx N(p_1-p_2, \\text{SE}^2)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncond <- tibble(\n  Regimen = c(\"A\", \"A\", \"B\", \"B\"),\n  Condition = c(\"n*phat\", \"n*(1-phat)\", \"n*phat\", \"n*(1-phat)\"),\n  Value = c(nA*phatA, nA*(1-phatA), nB*phatB, nB*(1-phatB))\n)\ncond\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 3\n  Regimen Condition  Value\n  <chr>   <chr>      <dbl>\n1 A       n*phat        89\n2 A       n*(1-phat)    16\n3 B       n*phat        76\n4 B       n*(1-phat)    29\n```\n\n\n:::\n:::\n\n\nAll four values exceed 5 (in fact all exceed 10), so the normal approximation is appropriate.\n\n---\n\n### Part (b) — 95% CI (unpooled SE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSE_unpooled <- sqrt(phatA*(1-phatA)/nA + phatB*(1-phatB)/nB)\nz_crit      <- qnorm(0.975)\nci_lo_p     <- diff_hat - z_crit * SE_unpooled\nci_hi_p     <- diff_hat + z_crit * SE_unpooled\n\ncat(sprintf(\"SE (unpooled) = %.5f\\n\", SE_unpooled))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE (unpooled) = 0.05598\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI: (%.4f, %.4f)\\n\", ci_lo_p, ci_hi_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: (0.0141, 0.2335)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI: (%.1f%%, %.1f%%)\\n\", 100*ci_lo_p, 100*ci_hi_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: (1.4%, 23.4%)\n```\n\n\n:::\n:::\n\n\n**Interpretation:** We are 95% confident that the true success rate for Regimen A is between 1.4% and 23.4% higher than for Regimen B. Since the interval contains 0, the data do **not** provide statistically significant evidence of a difference at the 5% level (though the point estimate favors A).\n\n---\n\n### Part (c) — Two-sided z-test (pooled SE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphat_pool <- (xA + xB) / (nA + nB)\nSE_pool_p <- sqrt(phat_pool*(1-phat_pool)*(1/nA + 1/nB))\nZ_obs     <- diff_hat / SE_pool_p\np_two     <- 2 * pnorm(abs(Z_obs), lower.tail = FALSE)\n\ncat(sprintf(\"phat_pool = (%d+%d)/(%d+%d) = %.4f\\n\", xA, xB, nA, nB, phat_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphat_pool = (89+76)/(105+105) = 0.7857\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"SE (pooled) = %.5f\\n\", SE_pool_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE (pooled) = 0.05663\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Z = %.4f\\n\", Z_obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZ = 2.1863\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"p-value (two-sided) = %.5f\\n\", p_two))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (two-sided) = 0.02880\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verify\nprop.test(c(xA, xB), c(nA, nB), correct = FALSE) |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 9\n  estimate1 estimate2 statistic p.value parameter conf.low conf.high method     \n      <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      \n1     0.848     0.724      4.78  0.0288         1   0.0141     0.234 2-sample t~\n# i 1 more variable: alternative <chr>\n```\n\n\n:::\n:::\n\n\n**Test statistic:** $Z = 2.186$, **$p$-value** = 0.0288\n\nAt $\\alpha = 0.05$ we fail to reject $H_0$. There is insufficient evidence to conclude that the success rates differ between the two regimens.\n\n---\n\n### Part (d) — Pooled vs. unpooled SE: conceptual explanation\n\nWhen we test $H_0: p_A = p_B$, we assume under $H_0$ that there is a **single common success probability** $p$. The pooled estimate $\\hat{p}_{\\text{pool}} = (x_A + x_B)/(n_A + n_B)$ is the most efficient estimate of this common $p$ under $H_0$, so plugging it into the SE is consistent with the null hypothesis and yields a valid test.\n\nFor the CI we make **no such assumption** — the CI must be valid whether or not $p_A = p_B$. Using the pooled estimate in the CI would distort coverage when $p_A \\neq p_B$ (which is the interesting case we are trying to characterize). The unpooled SE is therefore correct for CI construction.\n\n---\n\n### Part (e) — Relative risk and delta-method CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRR_hat  <- phatA / phatB\nlog_RR  <- log(RR_hat)\n\n# Var(log(phat_A/phat_B)) = Var(log phat_A) + Var(log phat_B)\n# By delta method: Var(log phat) = (1-p)/(n*p)\nvar_log_A <- (1 - phatA) / (nA * phatA)\nvar_log_B <- (1 - phatB) / (nB * phatB)\nse_log_RR <- sqrt(var_log_A + var_log_B)\n\nci_log  <- log_RR + c(-1,1) * z_crit * se_log_RR\nci_RR   <- exp(ci_log)\n\ncat(sprintf(\"RR = phat_A / phat_B = %.4f / %.4f = %.4f\\n\",\n            phatA, phatB, RR_hat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRR = phat_A / phat_B = 0.8476 / 0.7238 = 1.1711\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"log(RR) = %.4f,  SE(log RR) = %.5f\\n\", log_RR, se_log_RR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog(RR) = 0.1579,  SE(log RR) = 0.07312\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI for log(RR): (%.4f, %.4f)\\n\", ci_log[1], ci_log[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for log(RR): (0.0146, 0.3012)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI for RR:      (%.4f, %.4f)\\n\", ci_RR[1],  ci_RR[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for RR:      (1.0147, 1.3515)\n```\n\n\n:::\n:::\n\n\n**Point estimate:** $\\widehat{RR} = 1.171$. Regimen A has an estimated 17.1% higher success rate than Regimen B.\n\n**95% CI for RR:** (1.015, 1.351). Since this interval includes 1.0, the relative risk is not significantly different from 1 at the 5% level, consistent with the z-test conclusion.\n\n---\n\n## Problem 3: Paired Data Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbefore <- c(3.8, 5.2, 4.1, 6.7, 3.3, 4.9, 5.8, 7.1, 3.6, 4.4,\n            6.0, 5.5, 4.7, 3.9, 5.1)\nafter  <- c(2.9, 4.4, 3.2, 5.8, 2.8, 4.1, 4.9, 6.0, 2.7, 3.5,\n            5.0, 4.6, 3.8, 3.1, 4.3)\nd      <- before - after\nn_pair <- length(d)\n```\n:::\n\n\n### Part (a) — Why paired analysis is appropriate\n\nThe same 15 participants are measured **twice** (before and after the intervention). The two measurements on the same individual are positively correlated — people who start with high HOMA-IR tend to end with high HOMA-IR even after the intervention, reflecting between-subject variation in baseline insulin sensitivity.\n\nIf the Welch two-sample test were incorrectly applied, it would treat the 30 observations as independent, ignoring the within-person correlation. This inflates the variance estimate ($\\hat{\\sigma}_D^2 = \\sigma_1^2 + \\sigma_2^2 - 2\\rho\\sigma_1\\sigma_2 < \\sigma_1^2 + \\sigma_2^2$ when $\\rho > 0$), producing wider CIs and larger $p$-values — i.e., **reduced statistical power** to detect a real treatment effect.\n\n---\n\n### Part (b) — Summary statistics of differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDbar  <- mean(d)\nSD_d  <- sd(d)\nr_cor <- cor(before, after)\n\ncat(sprintf(\"n (pairs)     = %d\\n\",   n_pair))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn (pairs)     = 15\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"D_bar         = %.4f\\n\", Dbar))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nD_bar         = 0.8667\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"S_D           = %.4f\\n\", SD_d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nS_D           = 0.1291\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"cor(before, after) = %.4f\\n\", r_cor))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncor(before, after) = 0.9954\n```\n\n\n:::\n:::\n\n\n$\\bar{D} = 0.8667$, $S_D = 0.1291$, $r = 0.9954$.\n\n---\n\n### Part (c) — Paired t-test (one-sided)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_pair <- Dbar / (SD_d / sqrt(n_pair))\np_pair <- pt(t_pair, df = n_pair - 1, lower.tail = FALSE)\nt_crit_pair <- qt(0.975, df = n_pair - 1)\n\ncat(sprintf(\"T = %.4f\\n\", t_pair))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT = 26.0000\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"df = %d\\n\", n_pair - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndf = 14\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"p-value (one-sided) = %.6f\\n\", p_pair))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (one-sided) = 0.000000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Confirm with t.test\nt.test(before, after, paired = TRUE, alternative = \"greater\") |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 8\n  estimate statistic  p.value parameter conf.low conf.high method    alternative\n     <dbl>     <dbl>    <dbl>     <dbl>    <dbl>     <dbl> <chr>     <chr>      \n1    0.867        26 1.50e-13        14    0.808       Inf Paired t~ greater    \n```\n\n\n:::\n:::\n\n\n**Test statistic:** $T = \\bar{D}/(S_D/\\sqrt{n}) = 0.8667 / (0.1291/$\\sqrt{15}$) = 26$\n\n**$p$-value:** $0$\n\n**Conclusion:** We reject $H_0: \\mu_D = 0$ at $\\alpha = 0.05$ ($p \\ll 0.001$). There is strong evidence that the dietary intervention reduces HOMA-IR.\n\n---\n\n### Part (d) — 95% CI for $\\mu_D$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_pair_lo <- Dbar - t_crit_pair * SD_d / sqrt(n_pair)\nci_pair_hi <- Dbar + t_crit_pair * SD_d / sqrt(n_pair)\n\ncat(sprintf(\"95%% CI for mu_D: (%.4f, %.4f)\\n\", ci_pair_lo, ci_pair_hi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mu_D: (0.7952, 0.9382)\n```\n\n\n:::\n:::\n\n\n**Interpretation:** We are 95% confident that the dietary intervention reduces HOMA-IR by between 0.8 and 0.94 units on average. The entire interval is positive and away from zero, confirming a clinically meaningful reduction.\n\n---\n\n### Part (e) — Incorrect Welch two-sample t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwelch_wrong <- t.test(before, after, paired = FALSE, \n                       alternative = \"greater\") |> tidy()\nwelch_paired <- t.test(before, after, paired = TRUE) |> tidy()\n\ncat(\"=== Incorrect: Welch two-sample ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Incorrect: Welch two-sample ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"SE      = %.4f\\n\", welch_wrong$std.error))\ncat(sprintf(\"p-value = %.6f (one-sided approx)\\n\", welch_wrong$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = 0.019516 (one-sided approx)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI  = (%.4f, %.4f)\\n\", welch_wrong$conf.low, welch_wrong$conf.high))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI  = (0.1859, Inf)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n=== Correct: Paired t-test ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Correct: Paired t-test ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"SE      = %.4f\\n\", welch_paired$std.error))\ncat(sprintf(\"p-value = %.6f (two-sided)\\n\", welch_paired$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = 0.000000 (two-sided)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI  = (%.4f, %.4f)\\n\", welch_paired$conf.low, welch_paired$conf.high))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI  = (0.7952, 0.9382)\n```\n\n\n:::\n:::\n\n\n**Variance formula explanation:**\n\nUnder the correct paired model:\n$$\\text{Var}(D_i) = \\sigma_1^2 + \\sigma_2^2 - 2\\rho\\,\\sigma_1\\,\\sigma_2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns1_obs <- sd(before)\ns2_obs <- sd(after)\n\nvar_d_formula <- s1_obs^2 + s2_obs^2 - 2 * r_cor * s1_obs * s2_obs\nvar_d_direct  <- SD_d^2\n\ncat(sprintf(\"s_before = %.4f,  s_after = %.4f,  r = %.4f\\n\",\n            s1_obs, s2_obs, r_cor))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns_before = 1.1325,  s_after = 1.0579,  r = 0.9954\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Var(D) via formula = %.4f\\n\", var_d_formula))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVar(D) via formula = 0.0167\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Var(D) direct      = %.4f  (should match)\\n\", var_d_direct))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVar(D) direct      = 0.0167  (should match)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Var(D) if rho = 0  = %.4f  (what unpaired assumes)\\n\",\n            s1_obs^2 + s2_obs^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVar(D) if rho = 0  = 2.4018  (what unpaired assumes)\n```\n\n\n:::\n:::\n\n\nWhen $\\rho > 0$, $\\sigma_D^2$ is smaller than $\\sigma_1^2 + \\sigma_2^2$. The incorrect Welch test uses $S_1^2/n + S_2^2/n$ as its SE, which overestimates the variance, yielding a **wider CI and larger $p$-value** — in this case failing to detect the significant treatment effect more clearly.\n\n---\n\n### Part (f) — Spaghetti plot and histogram\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npair_df <- tibble(\n  Patient = factor(seq_len(n_pair)),\n  Before  = before,\n  After   = after,\n  D       = d\n)\n\np1 <- pair_df |>\n  pivot_longer(c(Before, After), names_to = \"Time\", values_to = \"HOMA_IR\") |>\n  mutate(Time = factor(Time, levels = c(\"Before\", \"After\"))) |>\n  ggplot(aes(x = Time, y = HOMA_IR, group = Patient)) +\n  geom_line(color = \"grey65\", linewidth = 0.6) +\n  geom_point(aes(color = Time), size = 3) +\n  scale_color_manual(values = c(\"Before\" = \"#e74c3c\", \"After\" = \"#006a4e\")) +\n  labs(\n    title  = \"Individual HOMA-IR Profiles\",\n    x      = NULL,\n    y      = \"HOMA-IR\",\n    color  = NULL\n  ) +\n  theme(legend.position = \"bottom\")\n\np2 <- pair_df |>\n  ggplot(aes(x = D)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 8,\n                 fill = \"#3498db\", color = \"white\", alpha = 0.75) +\n  geom_density(color = \"#2c3e50\", linewidth = 1.1) +\n  geom_vline(xintercept = 0,    linetype = \"dashed\",\n             color = \"grey40\",  linewidth = 1.0) +\n  geom_vline(xintercept = Dbar, color = \"#e74c3c\", linewidth = 1.4) +\n  annotate(\"text\", x = Dbar + 0.03, y = 1.05,\n           label = bquote(bar(D) == .(round(Dbar, 2))),\n           color = \"#e74c3c\", size = 5, hjust = 0) +\n  labs(\n    title = expression(\"Distribution of Differences  \" * D[i] == \"Before\" - \"After\"),\n    x     = \"D (HOMA-IR units)\",\n    y     = \"Density\"\n  )\n\np1 + p2 +\n  plot_annotation(\n    title    = \"Dietary Intervention: HOMA-IR Before vs. After (n = 15 pairs)\",\n    subtitle = \"Left: each line connects the same patient's two measurements  |  Right: distribution of within-patient differences\"\n  )\n```\n\n::: {.cell-output-display}\n![](HW_07_Solutions_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n---\n\n## Problem 4: Bootstrap and Permutation Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nplatelets_shock  <- round(rgamma(35, shape = 2.0, rate = 0.016), 1)\nplatelets_sepsis <- round(rgamma(40, shape = 3.5, rate = 0.022), 1)\n```\n:::\n\n\n### Part (a) — Exploratory summaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Group = c(rep(\"Septic Shock\", 35), rep(\"Non-septic Sepsis\", 40)),\n  Platelets = c(platelets_shock, platelets_sepsis)\n) |>\n  group_by(Group) |>\n  summarise(\n    n      = n(),\n    Mean   = round(mean(Platelets), 1),\n    Median = round(median(Platelets), 1),\n    SD     = round(sd(Platelets), 1),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 5\n  Group                 n  Mean Median    SD\n  <chr>             <int> <dbl>  <dbl> <dbl>\n1 Non-septic Sepsis    40  173.   145  111. \n2 Septic Shock         35  130.   112.  91.6\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(\n  Group     = c(rep(\"Septic Shock\", 35), rep(\"Non-septic Sepsis\", 40)),\n  Platelets = c(platelets_shock, platelets_sepsis)\n) |>\n  ggplot(aes(x = Platelets, fill = Group)) +\n  geom_density(aes(color = Group), linewidth = 1.1, alpha = 0.35) +\n  geom_rug(aes(color = Group), linewidth = 0.6, alpha = 0.7) +\n  scale_fill_manual(values  = c(\"Septic Shock\" = \"#e74c3c\", \"Non-septic Sepsis\" = \"#006a4e\")) +\n  scale_color_manual(values = c(\"Septic Shock\" = \"#e74c3c\", \"Non-septic Sepsis\" = \"#006a4e\")) +\n  labs(\n    title    = expression(\"Platelet Count Distribution by Sepsis Severity  (× 10\"^3 * \"/µL)\"),\n    subtitle = \"Right-skewed distributions; rug marks show individual observations\",\n    x        = expression(\"Platelet Count (× 10\"^3 * \"/µL)\"),\n    y        = \"Density\",\n    fill     = NULL, color = NULL\n  ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](HW_07_Solutions_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nBoth distributions are right-skewed, as expected from gamma-distributed platelet counts. The septic shock group shows a lower mean and median compared to the non-septic sepsis group, and also greater spread (larger SD).\n\n---\n\n### Part (b) — Bootstrap CIs for difference in means\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB        <- 5000\nn1_plt   <- length(platelets_shock)\nn2_plt   <- length(platelets_sepsis)\nobs_diff <- mean(platelets_shock) - mean(platelets_sepsis)\n\nboot_means <- replicate(B, {\n  mean(sample(platelets_shock,  n1_plt, replace = TRUE)) -\n  mean(sample(platelets_sepsis, n2_plt, replace = TRUE))\n})\n\nci_pct   <- quantile(boot_means, c(0.025, 0.975))\nci_basic <- 2 * obs_diff - quantile(boot_means, c(0.975, 0.025))\nboot_se  <- sd(boot_means)\n\ncat(sprintf(\"Observed difference (Shock - Sepsis): %.2f\\n\", obs_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved difference (Shock - Sepsis): -42.71\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap SE:                         %.4f\\n\", boot_se))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE:                         22.5641\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap Percentile 95%% CI: (%.2f, %.2f)\\n\", ci_pct[1],   ci_pct[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap Percentile 95% CI: (-87.97, 0.57)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap Basic      95%% CI: (%.2f, %.2f)\\n\", ci_basic[1], ci_basic[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap Basic      95% CI: (-85.99, 2.55)\n```\n\n\n:::\n:::\n\n\nThe two bootstrap intervals are similar; the percentile CI is (-87.97, 0.57) and the basic CI is (-85.99, 2.55).\n\n---\n\n### Part (c) — Bootstrap CI for difference in medians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nobs_med_diff <- median(platelets_shock) - median(platelets_sepsis)\n\nboot_meds <- replicate(B, {\n  median(sample(platelets_shock,  n1_plt, replace = TRUE)) -\n  median(sample(platelets_sepsis, n2_plt, replace = TRUE))\n})\n\nci_med_pct <- quantile(boot_meds, c(0.025, 0.975))\n\ncat(sprintf(\"Observed median difference (Shock - Sepsis): %.2f\\n\", obs_med_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved median difference (Shock - Sepsis): -32.90\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap Percentile 95%% CI (medians): (%.2f, %.2f)\\n\",\n            ci_med_pct[1], ci_med_pct[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap Percentile 95% CI (medians): (-104.35, 11.05)\n```\n\n\n:::\n:::\n\n\nThe percentile CI for the difference in medians is (-104.35, 11.05). For right-skewed data, the median is often a more robust measure of location than the mean, and the bootstrap provides a valid CI without requiring distributional assumptions.\n\n---\n\n### Part (d) — Welch t-test comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwelch_plt <- t.test(platelets_shock, platelets_sepsis) |> tidy()\ncat(sprintf(\"Welch t-test:  diff = %.2f,  95%% CI = (%.2f, %.2f),  p = %.4f\\n\",\n            welch_plt$estimate, welch_plt$conf.low, welch_plt$conf.high,\n            welch_plt$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWelch t-test:  diff = -42.71,  95% CI = (-89.27, 3.86),  p = 0.0716\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap SE CI: diff = %.2f,  boot SE = %.4f\\n\", obs_diff, boot_se))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE CI: diff = -42.71,  boot SE = 22.5641\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Bootstrap Percentile 95%% CI: (%.2f, %.2f)\\n\", ci_pct[1], ci_pct[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap Percentile 95% CI: (-87.97, 0.57)\n```\n\n\n:::\n:::\n\n\nThe Welch $t$ CI and bootstrap percentile CI are similar, suggesting the CLT approximation is reasonably good for these moderate sample sizes despite some skewness. If the distributions were more severely skewed or $n$ were smaller, the bootstrap percentile CI would be preferred because it does not rely on the approximate normality of $\\bar{X}_1 - \\bar{X}_2$.\n\n---\n\n### Part (e) — Two-sample permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nall_obs <- c(platelets_shock, platelets_sepsis)\nT_obs   <- mean(platelets_shock) - mean(platelets_sepsis)\n\nperm_stats <- replicate(B, {\n  perm <- sample(all_obs)\n  mean(perm[1:n1_plt]) - mean(perm[(n1_plt+1):(n1_plt+n2_plt)])\n})\n\np_perm <- mean(abs(perm_stats) >= abs(T_obs))\n\ncat(sprintf(\"Observed test statistic: %.4f\\n\", T_obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved test statistic: -42.7086\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Permutation p-value (two-sided): %.4f\\n\", p_perm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation p-value (two-sided): 0.0684\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Welch t-test p-value:            %.4f\\n\", welch_plt$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWelch t-test p-value:            0.0716\n```\n\n\n:::\n:::\n\n\n**Observed statistic:** $\\hat{\\Delta} = -42.71$, **permutation $p$-value:** $0.0684$\n\nThe permutation $p$-value and Welch $t$-test $p$-value agree closely. The **permutation test** is exactly valid under $H_0: F_1 = F_2$ (the two populations have the *same distribution*) — it tests whether the group labels could have been permuted by chance. The Welch $t$-test is asymptotically valid under the weaker $H_0: \\mu_1 = \\mu_2$.\n\n---\n\n### Part (f) — Permutation null distribution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Pre-compute histogram bins so density heights are consistent across fill groups. This part is not necessary for the solution because it's tricky to get right. As long as vertical are there that's good enough.\n\n\nh <- hist(perm_stats, breaks = 60, plot = FALSE)\n\nbin_df <- tibble(\n  xmin    = h$breaks[-length(h$breaks)],\n  xmax    = h$breaks[-1],\n  density = h$density,\n  xmid    = h$mids,\n  in_tail = abs(xmid) >= abs(T_obs)\n)\n\np_val_label <- sprintf(\"p = %.3f\", p_perm)\n\nggplot(bin_df) +\n  geom_rect(aes(xmin = xmin, xmax = xmax,\n                ymin = 0,    ymax = density,\n                fill = in_tail),\n            color = \"white\", linewidth = 0.2) +\n  scale_fill_manual(values = c(\"FALSE\" = \"#aecde8\", \"TRUE\" = \"#e74c3c\"),\n                    guide = \"none\") +\n  geom_vline(xintercept =  T_obs, color = \"#2c3e50\", linewidth = 1.5) +\n  geom_vline(xintercept = -T_obs, color = \"#2c3e50\", linewidth = 1.5,\n             linetype = \"dashed\") +\n  annotate(\"text\", x = T_obs + 2, y = max(h$density) * 0.92,\n           label = bquote(hat(Delta)[obs] == .(round(T_obs, 1))),\n           color = \"#2c3e50\", size = 5, hjust = 0) +\n  annotate(\"text\", x = min(h$breaks) + 2, y = max(h$density) * 0.80,\n           label = p_val_label, color = \"#e74c3c\",\n           size = 5.5, hjust = 0) +\n  labs(\n    title    = \"Permutation Null Distribution: Difference in Mean Platelet Count\",\n    subtitle = \"Red bars = permuted statistics at least as extreme as observed (both tails)\",\n    x        = expression(bar(x)[shock]^\"*\" - bar(x)[sepsis]^\"*\" ~\n                          \"(× 10\"^3 * \"/µL)\"),\n    y        = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](HW_07_Solutions_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n",
    "supporting": [
      "HW_07_Solutions_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}