{
  "hash": "3cb6bb1e3c0576ffff0955dd70df2121",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 6: Confidence Intervals\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-01-26\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 6\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 6: Confidence Intervals\n\n## Review: Where We Left Off\n\n**Key concepts from Lessons 1-5:**\n\n-   **Point estimation:** $\\hat{\\theta}$ estimates unknown parameter $\\theta$\n-   **Bias and MSE:** Properties for evaluating estimators\n-   **MVUE:** Minimum variance unbiased estimators\n-   **MLE:** Maximum likelihood estimation\n-   **Sufficient statistics:** Data reduction without information loss\n\n. . .\n\n**Today's Goals:**\n\n-   Move from point estimates to **interval estimates**\n-   Understand the concept of **confidence level**\n-   Derive confidence intervals using **pivotal quantities**\n-   Explore the relationship between **precision and confidence**\n\n## From Point Estimates to Intervals\n\nA point estimate like $\\bar{x} = 11.28$ tells us nothing about **precision** or **reliability**.\n\n. . .\n\n**Consider:** A clinical trial testing a new blood pressure medication\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Blood pressure reductions (mmHg) from 25 patients\nbp_reductions <- c(12.3, 8.7, 15.2, 10.1, 7.4, 14.8, 11.2, 9.5, 13.1, 16.2,\n                   8.1, 12.5, 10.8, 14.3, 11.7, 9.2, 15.0, 13.4, 7.9, 12.1,\n                   10.5, 8.3, 14.1, 11.5, 13.8)\n\ncat(\"Point estimate of mean BP reduction:\", round(mean(bp_reductions), 2), \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint estimate of mean BP reduction: 11.67 mmHg\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-note\n## The Key Question\nHow close is $\\bar{x} = 11.28$ mmHg to the true population mean $\\mu$? Could we get a different answer with different patients?\n:::\n\n## The Confidence Interval Approach\n\nInstead of a single number, we report an **interval of plausible values**.\n\n. . .\n\n**Definition:** A **confidence interval (CI)** is a range of values that, with a specified level of confidence, contains the true parameter value.\n\n. . .\n\n::: callout-important\n## Two Key Properties of CIs\n\n1.  **Confidence level:** How reliable is the interval? (e.g., 95%)\n2.  **Width:** How precise is our estimate? (narrower = more precise)\n:::\n\n. . .\n\n**The tradeoff:** Higher confidence → Wider interval → Less precision\n\n# Deriving the CI for $\\mu$ (Known $\\sigma$) {background-color=\"#3498db\"}\n\n## Setup: The Idealized Scenario\n\n**Assumptions:**\n\n1.  $X_1, X_2, \\ldots, X_n$ is a random sample from a **normal population**\n2.  The population standard deviation $\\sigma$ is **known**\n\n. . .\n\nWhile $\\sigma$ known is unrealistic, this case:\n\n-   Illustrates the fundamental concepts\n-   Provides the foundation for more realistic scenarios\n-   Is approximately valid when $n$ is very large\n\n## Starting Point: The Sampling Distribution\n\nFrom the Central Limit Theorem and properties of normal distributions:\n\n$$\\bar{X} \\sim N\\left(\\mu, \\frac{\\sigma^2}{n}\\right)$$\n\n. . .\n\n**Standardizing:**\n\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\sim N(0, 1)$$\n\n. . .\n\nThis $Z$ has a **known distribution** (standard normal) that does **not depend on $\\mu$**.\n\n## The Pivotal Quantity\n\n::: callout-important\n## Definition (Devore 8.1)\n\nA **pivotal quantity** is a random variable $h(X_1, \\ldots, X_n; \\theta)$ such that:\n\n1.  It is a function of both the data and the unknown parameter $\\theta$\n2.  Its probability distribution does **not** depend on $\\theta$ or any other unknown parameters\n:::\n\n. . .\n\n**Our pivotal quantity:**\n\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$$\n\n-   ✓ Depends on data ($\\bar{X}$) and unknown parameter ($\\mu$)\n-   ✓ Distribution is $N(0, 1)$ — doesn't depend on $\\mu$\n\n## Building the Interval: Step 1\n\nFor the standard normal distribution, we know:\n\n$$P(-1.96 < Z < 1.96) = 0.95$$\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(z = seq(-4, 4, 0.01)) |>\n  mutate(density = dnorm(z),\n         fill_region = ifelse(abs(z) <= 1.96, \"Middle 95%\", \"Tails\")) |>\n  ggplot(aes(x = z, y = density, fill = fill_region)) +\n  geom_area(alpha = 0.7) +\n  geom_vline(xintercept = c(-1.96, 1.96), linetype = \"dashed\", color = \"red\") +\n  scale_fill_manual(values = c(\"Middle 95%\" = \"steelblue\", \"Tails\" = \"gray80\")) +\n  labs(title = \"Standard Normal Distribution\", \n       subtitle = \"P(-1.96 < Z < 1.96) = 0.95\",\n       x = \"Z\", y = \"Density\", fill = \"\") +\n  annotate(\"text\", x = 0, y = 0.15, label = \"0.95\", size = 6, color = \"white\") +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Building the Interval: Step 2\n\nSubstitute our pivotal quantity:\n\n$$P\\left(-1.96 < \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < 1.96\\right) = 0.95$$\n\n. . .\n\n**Isolate $\\mu$:** Multiply all parts by $\\sigma/\\sqrt{n}$:\n\n$$P\\left(-1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\bar{X} - \\mu < 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right) = 0.95$$\n\n. . .\n\n**Rearrange** (subtract $\\bar{X}$, multiply by $-1$):\n\n$$P\\left(\\bar{X} - 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{X} + 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right) = 0.95$$\n\n## The Random Interval\n\n::: callout-important\n## Key Insight\n\nThe interval $\\left(\\bar{X} - 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}, \\bar{X} + 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right)$ is **random** because $\\bar{X}$ is random.\n:::\n\n. . .\n\n**Before sampling:** With probability 0.95, this random interval will contain $\\mu$.\n\n**After sampling:** We observe $\\bar{x}$ and compute the interval. The interval is now fixed — it either contains $\\mu$ or it doesn't.\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## The 95% Confidence Interval\n\n::: callout-important\n## Definition (Devore 8.1)\n\nA **95% confidence interval** for $\\mu$ (with known $\\sigma$) is:\n\n$$\\left(\\bar{x} - 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}, \\bar{x} + 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}\\right)$$\n\nor equivalently: $\\bar{x} \\pm 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n:::\n\n. . .\n\n**Components:**\n\n-   $\\bar{x}$ = point estimate (center of the interval)\n-   $1.96 \\cdot \\sigma/\\sqrt{n}$ = **margin of error**\n-   $\\sigma/\\sqrt{n}$ = standard error of $\\bar{X}$\n\n## Example: Titanium Alloy Tensile Strength (Devore 8.1-8.2)\n\n**Problem:** An engineer wants to estimate the true mean tensile strength of a titanium alloy weld. Previous tests suggest $\\sigma = 55$ MPa. A sample of $n = 31$ welds gives $\\bar{x} = 1064$ MPa.\n\n. . .\n\n**Calculate the 95% CI:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 55\nn <- 31\nxbar <- 1064\nz_crit <- 1.96\n\nmargin_error <- z_crit * sigma / sqrt(n)\nlower <- xbar - margin_error\nupper <- xbar + margin_error\n\ncat(\"95% CI: (\", round(lower, 1), \",\", round(upper, 1), \") MPa\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 1044.6 , 1083.4 ) MPa\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Margin of Error:\", round(margin_error, 1), \"MPa\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargin of Error: 19.4 MPa\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** We are 95% confident that the true mean tensile strength is between 1044.6 and 1083.4 MPa.\n\n## Medical Example: Blood Pressure Medication\n\n**Scenario:** A clinical trial measures systolic BP reduction (mmHg) for a new medication. Assume $\\sigma = 5$ mmHg (from prior studies). With $n = 25$ patients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\nbp_reductions <- c(12.3, 8.7, 15.2, 10.1, 7.4, 14.8, 11.2, 9.5, 13.1, 16.2,\n                   8.1, 12.5, 10.8, 14.3, 11.7, 9.2, 15.0, 13.4, 7.9, 12.1,\n                   10.5, 8.3, 14.1, 11.5, 13.8)\nsigma <- 5\nn <- length(bp_reductions)\nxbar <- mean(bp_reductions)\n\n# 95% CI\nmargin_error <- 1.96 * sigma / sqrt(n)\nci_lower <- xbar - margin_error\nci_upper <- xbar + margin_error\n\ncat(\"Sample mean:\", round(xbar, 2), \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 11.67 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: (\", round(ci_lower, 2), \",\", round(ci_upper, 2), \") mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 9.71 , 13.63 ) mmHg\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Clinical interpretation:** We're 95% confident the medication reduces systolic BP by between 9.32 and 13.24 mmHg on average.\n\n# Interpreting Confidence Level {background-color=\"#3498db\"}\n\n## What Does \"95% Confident\" Mean?\n\n::: callout-warning\n## Common Misconception\n\n**WRONG:** \"There is a 95% probability that $\\mu$ lies in the interval (9.32, 13.24).\"\n:::\n\n. . .\n\n**Why is this wrong?**\n\n-   $\\mu$ is a **fixed** (though unknown) constant\n-   The interval (9.32, 13.24) is **fixed** after we compute it\n-   There's no probability involved — $\\mu$ either is or isn't in this specific interval\n\n## The Correct Interpretation\n\n::: callout-important\n## Frequentist Interpretation\n\nIf we were to repeat this sampling procedure many times:\n\n-   Each time computing a 95% CI from a new random sample\n-   **95% of those intervals would contain the true $\\mu$**\n:::\n\n. . .\n\n**In other words:** The method works 95% of the time, not this specific interval.\n\n. . .\n\nThink of it as confidence in the **procedure**, not in the specific interval.\n\n## Simulation: Understanding Confidence Level\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(2024)\nmu_true <- 11  # True mean BP reduction\nsigma <- 5\nn <- 25\nn_samples <- 100\n\n# Generate 100 confidence intervals\nci_sim <- tibble(sample_id = 1:n_samples) |>\n  mutate(\n    data = map(sample_id, ~rnorm(n, mu_true, sigma)),\n    xbar = map_dbl(data, mean),\n    lower = xbar - 1.96 * sigma / sqrt(n),\n    upper = xbar + 1.96 * sigma / sqrt(n),\n    contains_mu = lower < mu_true & upper > mu_true\n  )\n\ncoverage <- mean(ci_sim$contains_mu)\n\n# Plot\nci_sim |>\n  slice_head(n = 50) |>\n  ggplot(aes(y = sample_id)) +\n  geom_segment(aes(x = lower, xend = upper, yend = sample_id, color = contains_mu),\n               linewidth = 0.8) +\n  geom_point(aes(x = xbar, color = contains_mu), size = 1.5) +\n  geom_vline(xintercept = mu_true, color = \"red\", linewidth = 1.2, linetype = \"dashed\") +\n  scale_color_manual(values = c(\"FALSE\" = \"orange\", \"TRUE\" = \"steelblue\"),\n                     labels = c(\"Misses μ\", \"Contains μ\")) +\n  labs(title = paste0(\"50 of \", n_samples, \" Simulated 95% CIs\"),\n       subtitle = paste0(\"Coverage: \", round(100*coverage, 1), \"% contain true μ = \", mu_true),\n       x = \"BP Reduction (mmHg)\", y = \"Sample Number\", color = \"\") +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Key Insight from Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Out of\", n_samples, \"intervals:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOut of 100 intervals:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"-\", sum(ci_sim$contains_mu), \"contain the true μ\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- 98 contain the true μ\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"-\", sum(!ci_sim$contains_mu), \"miss the true μ\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- 2 miss the true μ\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nEmpirical coverage:\", round(100*coverage, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEmpirical coverage: 98 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expected coverage: 95%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected coverage: 95%\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-tip\n## Practical Interpretation\n\nWhen we report a 95% CI, we're using a **reliable method**. About 1 in 20 times, we'll be unlucky and our interval won't contain the true value — but we won't know which times those are!\n:::\n\n# Other Confidence Levels {background-color=\"#3498db\"}\n\n## General Confidence Interval Formula\n\nTo construct a $100(1-\\alpha)\\%$ CI, we use $z_{\\alpha/2}$ — the critical value that captures upper tail area $\\alpha/2$.\n\n. . .\n\n::: callout-important\n## General CI for $\\mu$ (Known $\\sigma$)\n\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\nwhere $P(Z > z_{\\alpha/2}) = \\alpha/2$ for $Z \\sim N(0,1)$.\n:::\n\n. . .\n\n| Confidence Level | $\\alpha$ | $\\alpha/2$ | $z_{\\alpha/2}$ |\n|------------------|----------|------------|----------------|\n| 90%              | 0.10     | 0.05       | 1.645          |\n| 95%              | 0.05     | 0.025      | 1.960          |\n| 99%              | 0.01     | 0.005      | 2.576          |\n\n## Visualizing Different Confidence Levels\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nz_values <- tibble(\n  conf_level = c(\"90%\", \"95%\", \"99%\"),\n  z_crit = c(1.645, 1.96, 2.576)\n)\n\ntibble(z = seq(-4, 4, 0.01)) |>\n  mutate(density = dnorm(z)) |>\n  ggplot(aes(x = z, y = density)) +\n  geom_area(fill = \"gray90\") +\n  geom_area(data = . %>% filter(abs(z) <= 2.576), fill = \"lightblue\", alpha = 0.5) +\n  geom_area(data = . %>% filter(abs(z) <= 1.96), fill = \"steelblue\", alpha = 0.7) +\n  geom_area(data = . %>% filter(abs(z) <= 1.645), fill = \"darkblue\", alpha = 0.8) +\n  geom_vline(xintercept = c(-2.576, 2.576), linetype = \"dotted\", color = \"lightblue\") +\n  geom_vline(xintercept = c(-1.96, 1.96), linetype = \"dashed\", color = \"steelblue\") +\n  geom_vline(xintercept = c(-1.645, 1.645), linetype = \"solid\", color = \"darkblue\") +\n  annotate(\"text\", x = 0, y = 0.35, label = \"90%\", color = \"white\", size = 5) +\n  annotate(\"text\", x = 1.8, y = 0.08, label = \"95%\", color = \"steelblue\", size = 4) +\n  annotate(\"text\", x = 2.3, y = 0.02, label = \"99%\", color = \"lightblue\", size = 4) +\n  labs(title = \"Critical Values for Different Confidence Levels\",\n       x = \"Z\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Example: Comparing Confidence Levels (Devore 8.3)\n\n**Scenario:** A new online homework system is tested. Past experience: $\\sigma = 13$ points. A sample of $n = 40$ students has mean final exam score $\\bar{x} = 70.7$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 13\nn <- 40\nxbar <- 70.7\n\n# Calculate CIs at different confidence levels\nci_results <- tibble(\n  conf_level = c(\"90%\", \"95%\", \"99%\"),\n  z_crit = c(1.645, 1.96, 2.576)\n) |>\n  mutate(\n    margin_error = z_crit * sigma / sqrt(n),\n    lower = xbar - margin_error,\n    upper = xbar + margin_error,\n    width = upper - lower\n  )\n\nci_results |>\n  mutate(across(where(is.numeric), ~round(., 2))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|conf_level | z_crit| margin_error| lower| upper| width|\n|:----------|------:|------------:|-----:|-----:|-----:|\n|90%        |   1.65|         3.38| 67.32| 74.08|  6.76|\n|95%        |   1.96|         4.03| 66.67| 74.73|  8.06|\n|99%        |   2.58|         5.29| 65.41| 75.99| 10.59|\n\n\n:::\n:::\n\n\n## The Confidence-Precision Tradeoff\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nci_results |>\n  ggplot(aes(y = conf_level)) +\n  geom_segment(aes(x = lower, xend = upper, yend = conf_level), \n               linewidth = 2, color = \"steelblue\") +\n  geom_point(aes(x = xbar), size = 4, color = \"red\") +\n  geom_vline(xintercept = 65, linetype = \"dashed\", color = \"darkgray\") +\n  annotate(\"text\", x = 65, y = 3.3, label = \"Old mean = 65\", size = 4) +\n  labs(title = \"Effect of Confidence Level on Interval Width\",\n       subtitle = \"Higher confidence → Wider interval\",\n       x = \"Final Exam Score\", y = \"Confidence Level\") +\n  theme(axis.text.y = element_text(size = 14))\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n. . .\n\n**Note:** At 90% confidence, we can say the new mean exceeds 65 (the old mean). At higher confidence levels, this conclusion is less certain.\n\n# Confidence Level, Precision, and Sample Size {background-color=\"#3498db\"}\n\n## The Width of a Confidence Interval\n\nThe width of a $100(1-\\alpha)\\%$ CI is:\n\n$$w = 2 \\cdot z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\n. . .\n\n**Width depends on:**\n\n| Factor | Effect on Width |\n|--------|-----------------|\n| $\\uparrow$ Confidence level | Width increases (larger $z_{\\alpha/2}$) |\n| $\\uparrow$ Sample size $n$ | Width decreases (larger $\\sqrt{n}$) |\n| $\\uparrow$ Population SD $\\sigma$ | Width increases |\n\n## Sample Size Determination\n\n**The question:** How large a sample do we need to achieve a desired width $w$ at a specified confidence level?\n\n. . .\n\nFrom $w = 2 \\cdot z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$, solving for $n$:\n\n::: callout-important\n## Sample Size Formula (Devore 8.6)\n\n$$n = \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{w/2}\\right)^2 = \\left(\\frac{2 \\cdot z_{\\alpha/2} \\cdot \\sigma}{w}\\right)^2$$\n\nwhere $w/2$ is the desired **margin of error**.\n:::\n\n## Example: Response Time Study (Devore 8.4)\n\n**Problem:** A new operating system is installed. Response time is normally distributed with $\\sigma = 25$ ms. What sample size ensures a 95% CI with width at most 10 ms?\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 25\nw <- 10  # desired width\nz_crit <- 1.96\n\nn_required <- (2 * z_crit * sigma / w)^2\ncat(\"Required sample size:\", ceiling(n_required), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 97 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Check:**\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 97\nactual_width <- 2 * z_crit * sigma / sqrt(n)\ncat(\"Actual width with n =\", n, \":\", round(actual_width, 2), \"ms\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nActual width with n = 97 : 9.95 ms\n```\n\n\n:::\n:::\n\n\n## Medical Example: Planning a Clinical Trial\n\n**Scenario:** Planning a trial for a hypertension drug. Prior studies suggest $\\sigma = 8$ mmHg for BP reduction. You want to estimate the true mean reduction to within 2 mmHg with 99% confidence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 8\nmargin_error <- 2  # desired margin of error\nz_crit <- 2.576  # for 99% CI\n\nn_required <- (z_crit * sigma / margin_error)^2\ncat(\"For 99% CI with margin of error ±2 mmHg:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFor 99% CI with margin of error ±2 mmHg:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required sample size:\", ceiling(n_required), \"patients\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 107 patients\n```\n\n\n:::\n:::\n\n\n. . .\n\n**What if we use 95% confidence instead?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_crit_95 <- 1.96\nn_required_95 <- (z_crit_95 * sigma / margin_error)^2\ncat(\"\\nFor 95% CI with same margin of error:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFor 95% CI with same margin of error:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required sample size:\", ceiling(n_required_95), \"patients\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 62 patients\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Savings:\", ceiling(n_required) - ceiling(n_required_95), \"patients\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSavings: 45 patients\n```\n\n\n:::\n:::\n\n\n## Sample Size vs. Precision\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Show how sample size affects width\nsample_sizes <- seq(10, 200, 5)\nsigma <- 25\n\nwidth_data <- tibble(n = sample_sizes) |>\n  mutate(\n    width_90 = 2 * 1.645 * sigma / sqrt(n),\n    width_95 = 2 * 1.96 * sigma / sqrt(n),\n    width_99 = 2 * 2.576 * sigma / sqrt(n)\n  ) |>\n  pivot_longer(starts_with(\"width\"), names_to = \"conf_level\", values_to = \"width\") |>\n  mutate(conf_level = case_when(\n    conf_level == \"width_90\" ~ \"90%\",\n    conf_level == \"width_95\" ~ \"95%\",\n    conf_level == \"width_99\" ~ \"99%\"\n  ))\n\nggplot(width_data, aes(x = n, y = width, color = conf_level)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 10, linetype = \"dashed\", color = \"gray50\") +\n  annotate(\"text\", x = 180, y = 11, label = \"Target width = 10\", size = 4) +\n  scale_color_manual(values = c(\"90%\" = \"darkblue\", \"95%\" = \"steelblue\", \"99%\" = \"lightblue\")) +\n  labs(title = \"CI Width vs. Sample Size\",\n       subtitle = \"σ = 25, showing diminishing returns\",\n       x = \"Sample Size (n)\", y = \"CI Width\", color = \"Confidence\\nLevel\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n# One-Sided Confidence Intervals {background-color=\"#3498db\"}\n\n## Confidence Bounds\n\nSometimes we only need a **lower bound** or **upper bound** for the parameter.\n\n. . .\n\n**Examples:**\n\n-   A surgeon wants only a **lower bound** for average remission time after cancer surgery\n-   A manufacturer wants only an **upper bound** for average defect rate\n-   An engineer wants only a **lower bound** for mean tensile strength\n\n## Derivation of One-Sided Bounds\n\nFor a **95% lower confidence bound:**\n\n$$P(Z < 1.645) = 0.95$$\n\n$$P\\left(\\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < 1.645\\right) = 0.95$$\n\n. . .\n\nRearranging:\n\n$$P\\left(\\bar{X} - 1.645 \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu\\right) = 0.95$$\n\n::: callout-important\n## One-Sided Confidence Bounds\n\n-   **95% Lower Bound:** $\\bar{x} - 1.645 \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu$\n-   **95% Upper Bound:** $\\mu < \\bar{x} + 1.645 \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n:::\n\n## Example: Tensile Strength Lower Bound (Devore 8.7)\n\n**Problem:** For the titanium alloy weld data ($\\bar{x} = 1064$ MPa, $\\sigma = 55$ MPa, $n = 31$), compute a 95% lower confidence bound.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 1064\nsigma <- 55\nn <- 31\nz_crit <- 1.645  # for one-sided 95%\n\nlower_bound <- xbar - z_crit * sigma / sqrt(n)\ncat(\"95% Lower Confidence Bound:\", round(lower_bound, 2), \"MPa\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Lower Confidence Bound: 1047.75 MPa\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** We are 95% confident that the true mean tensile strength is **at least** 1047.75 MPa.\n\n. . .\n\nCompare with two-sided 95% CI: (1044.6, 1083.4) — the lower bound is **higher** than the two-sided lower limit!\n\n## Comparing One-Sided and Two-Sided Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Visual comparison - draw each interval type separately\nggplot() +\n  # Two-sided CI (no arrow)\n  geom_segment(aes(x = 1044.6, xend = 1083.4, y = \"Two-sided 95% CI\", yend = \"Two-sided 95% CI\"),\n               linewidth = 3, color = \"steelblue\") +\n  # One-sided lower bound (arrow pointing right to infinity)\n  geom_segment(aes(x = 1047.75, xend = 1110, y = \"One-sided 95% LB\", yend = \"One-sided 95% LB\"),\n               linewidth = 3, color = \"steelblue\",\n               arrow = arrow(length = unit(0.3, \"cm\"), ends = \"last\")) +\n  # One-sided upper bound (arrow pointing left to negative infinity)\n  geom_segment(aes(x = 1020, xend = 1080.25, y = \"One-sided 95% UB\", yend = \"One-sided 95% UB\"),\n               linewidth = 3, color = \"steelblue\",\n               arrow = arrow(length = unit(0.3, \"cm\"), ends = \"first\")) +\n  # Point estimates\n\n  geom_point(aes(x = 1064, y = \"Two-sided 95% CI\"), size = 4, color = \"red\") +\n  geom_point(aes(x = 1064, y = \"One-sided 95% LB\"), size = 4, color = \"red\") +\n  geom_point(aes(x = 1064, y = \"One-sided 95% UB\"), size = 4, color = \"red\") +\n  labs(title = \"Comparison of Two-Sided CI vs One-Sided Bounds\",\n       subtitle = \"Arrows indicate interval extends to ±∞\",\n       x = \"Tensile Strength (MPa)\", y = \"\") +\n  xlim(1020, 1110) +\n  theme(axis.text.y = element_text(size = 12))\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n# Simulation: Properties of CIs {background-color=\"#3498db\"}\n\n## Understanding CI Coverage Through Simulation\n\nLet's simulate many samples and examine how often CIs capture the true parameter.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\nmu_true <- 100\nsigma <- 15\nn_values <- c(10, 25, 50, 100)\nn_sims <- 1000\n\n# Function to compute CI and check coverage\nsimulate_coverage <- function(n, mu, sigma, n_sims) {\n  tibble(sim = 1:n_sims) |>\n    mutate(\n      xbar = map_dbl(sim, ~mean(rnorm(n, mu, sigma))),\n      lower = xbar - 1.96 * sigma / sqrt(n),\n      upper = xbar + 1.96 * sigma / sqrt(n),\n      contains_mu = lower < mu & upper > mu\n    )\n}\n\ncoverage_results <- tibble(n = n_values) |>\n  mutate(\n    results = map(n, ~simulate_coverage(.x, mu_true, sigma, n_sims)),\n    coverage = map_dbl(results, ~mean(.x$contains_mu)),\n    avg_width = map_dbl(results, ~mean(.x$upper - .x$lower))\n  )\n\ncoverage_results |>\n  select(n, coverage, avg_width) |>\n  mutate(coverage = paste0(round(100*coverage, 1), \"%\"),\n         avg_width = round(avg_width, 2)) |>\n  knitr::kable(col.names = c(\"Sample Size\", \"Coverage\", \"Average Width\"))\n```\n\n::: {.cell-output-display}\n\n\n| Sample Size|Coverage | Average Width|\n|-----------:|:--------|-------------:|\n|          10|93.8%    |         18.59|\n|          25|95%      |         11.76|\n|          50|95.3%    |          8.32|\n|         100|95.3%    |          5.88|\n\n\n:::\n:::\n\n\n## Visualizing Coverage by Sample Size\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncoverage_results |>\n  unnest(results) |>\n  filter(sim <= 50) |>\n  ggplot(aes(y = sim)) +\n  geom_segment(aes(x = lower, xend = upper, yend = sim, color = contains_mu),\n               linewidth = 0.6) +\n  geom_vline(xintercept = mu_true, color = \"red\", linewidth = 1, linetype = \"dashed\") +\n  facet_wrap(~paste(\"n =\", n), nrow = 1, scales = \"free_x\") +\n  scale_color_manual(values = c(\"FALSE\" = \"orange\", \"TRUE\" = \"steelblue\"),\n                     labels = c(\"Misses μ\", \"Contains μ\")) +\n  labs(title = \"95% CIs for Different Sample Sizes (first 50 simulations)\",\n       subtitle = paste0(\"True μ = \", mu_true, \" (red dashed line)\"),\n       x = \"Value\", y = \"Simulation\", color = \"\") +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Key Observations\n\n::: callout-tip\n## What the Simulation Shows\n\n1.  **Coverage is approximately 95%** regardless of sample size (when assumptions hold)\n2.  **Width decreases with sample size** — larger samples give more precise estimates\n3.  **Width decreases proportional to $1/\\sqrt{n}$** — need to quadruple $n$ to halve the width\n4.  **Intervals are centered at $\\bar{x}$**, which varies from sample to sample\n:::\n\n# Summary {background-color=\"#2c3e50\"}\n\n## Lesson 6: Key Takeaways\n\n**1. Confidence Intervals provide interval estimates**\n\n-   More informative than point estimates alone\n-   Communicate both estimate and precision\n\n. . .\n\n**2. The pivotal quantity method**\n\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\sim N(0,1)$$\n\n-   Allows derivation of CI formula\n-   Foundation for more complex scenarios\n\n. . .\n\n**3. The $100(1-\\alpha)\\%$ CI for $\\mu$ (known $\\sigma$):**\n\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\n## Key Formulas\n\n| Quantity | Formula |\n|----------|---------|\n| 95% CI | $\\bar{x} \\pm 1.96 \\cdot \\frac{\\sigma}{\\sqrt{n}}$ |\n| General CI | $\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$ |\n| CI Width | $w = 2 \\cdot z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$ |\n| Sample Size | $n = \\left(\\frac{2z_{\\alpha/2}\\sigma}{w}\\right)^2$ |\n| Lower Bound | $\\bar{x} - z_\\alpha \\cdot \\frac{\\sigma}{\\sqrt{n}}$ |\n| Upper Bound | $\\bar{x} + z_\\alpha \\cdot \\frac{\\sigma}{\\sqrt{n}}$ |\n\n## Looking Ahead\n\n**Next Lesson (7):** Confidence intervals when $\\sigma$ is unknown\n\n-   The $t$-distribution\n-   One-sample $t$ confidence interval\n-   Large-sample intervals\n-   Intervals for population proportions\n\n. . .\n\n**Key transition:** From the idealized case (known $\\sigma$) to the realistic case (unknown $\\sigma$)\n\n## References\n\n::: nonincremental\n-   Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Chapter 8.1\n-   Chihara and Hesterberg. *Mathematical Statistics with Resampling and R* (Wiley). Chapter 7\n:::\n\n# Homework Problems {background-color=\"#8B0000\"}\n\n## Exercises from Devore, Berk, Carlton Section 8.1\n\n**Problem 1.** Consider a normal population distribution with the value of $\\sigma$ known.\n\na.  What is the confidence level for the interval $\\bar{x} \\pm 2.81\\sigma/\\sqrt{n}$?\nb.  What is the confidence level for the interval $\\bar{x} \\pm 1.44\\sigma/\\sqrt{n}$?\nc.  What value of $z_{\\alpha/2}$ in the CI formula results in a confidence level of 99.7%?\nd.  Answer the question posed in part (c) for a confidence level of 75%.\n\n## Exercises from Devore, Berk, Carlton Section 8.1 (continued)\n\n**Problem 2.** Each of the following is a confidence interval for $\\mu$ = true average resonance frequency (Hz) for all tennis rackets of a certain type:\n\n(114.4, 115.6) and (114.1, 115.9)\n\na.  What is the value of the sample mean resonance frequency?\nb.  Both intervals were calculated from the same sample data. The confidence level for one of these intervals is 90% and for the other is 99%. Which of the intervals has the 90% confidence level, and why?\n\n## Exercises from Devore, Berk, Carlton Section 8.1 (continued)\n\n**Problem 3.** Suppose that a random sample of 50 bottles of a particular brand of cough syrup is selected and the alcohol content of each bottle is determined. Let $\\mu$ denote the average alcohol content for the population of all bottles of the brand under study. Suppose that the resulting 95% confidence interval is (7.8, 9.4).\n\na.  Would a 90% confidence interval calculated from this same sample have been narrower or wider than the given interval? Explain your reasoning.\nb.  Consider the following statement: There is a 95% chance that $\\mu$ is between 7.8 and 9.4. Is this statement correct? Why or why not?\nc.  Consider the following statement: We can be highly confident that 95% of all bottles of this type of cough syrup have an alcohol content that is between 7.8 and 9.4. Is this statement correct? Why or why not?\n\n## Exercises from Devore, Berk, Carlton Section 8.1 (continued)\n\n**Problem 4.** A random sample of $n = 15$ heat pumps of a certain type yielded the following observations on lifetime (in years):\n\n2.0, 1.3, 6.0, 1.9, 5.1, 0.4, 1.0, 5.3, 15.7, 0.7, 4.8, 0.9, 12.2, 5.3, 0.6\n\na.  Assume that the lifetime distribution is exponential and use an argument parallel to that of Example 8.5 in the textbook to obtain a 95% CI for expected (true average) lifetime.\nb.  How should the interval of part (a) be altered to achieve a confidence level of 99%?\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n",
    "supporting": [
      "07_Confidence_Intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}