{
  "hash": "ad132bdf8be4b702287c018e7607ceb7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 2 Solutions\"\nsubtitle: \"BSTA 551\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n## Problem 1: Fisher Information and CRLB\n\nA clinical trial is testing a new treatment for hypertension. The time (in days) until a patient achieves target blood pressure is modeled as an Exponential distribution with rate parameter $\\lambda$ (where $E(X) = 1/\\lambda$).\n\nIn a pilot study, the following times (in days) were observed for $n = 8$ patients:\n$$X = \\{12, 8, 15, 6, 10, 14, 9, 11\\}$$\n\n### Part (a)\n\n**Calculate the Fisher Information $I(\\lambda)$ for a single observation from an Exponential($\\lambda$) distribution. Show your derivation using the definition $I(\\lambda) = E[-\\ell''(\\lambda)]$.**\n\nFor $X \\sim \\text{Exponential}(\\lambda)$, the pdf is $f(x; \\lambda) = \\lambda e^{-\\lambda x}$ for $x > 0$.\n\n**Log-likelihood for a single observation:**\n$$\\ell(\\lambda) = \\ln f(x; \\lambda) = \\ln \\lambda - \\lambda x$$\n\n**First derivative:**\n$$\\ell'(\\lambda) = \\frac{1}{\\lambda} - x$$\n\n**Second derivative:**\n$$\\ell''(\\lambda) = -\\frac{1}{\\lambda^2}$$\n\n**Fisher Information:**\n$$I(\\lambda) = E[-\\ell''(\\lambda)] = E\\left[\\frac{1}{\\lambda^2}\\right] = \\boxed{\\frac{1}{\\lambda^2}}$$\n\nNote: Since the second derivative does not depend on $X$, the expectation is straightforward.\n\n### Part (b)\n\n**State the Cramér-Rao Lower Bound (CRLB) for unbiased estimators of $\\lambda$ based on a sample of size $n$.**\n\nFor $n$ observations, the Fisher Information is:\n$$I_n(\\lambda) = n \\cdot I(\\lambda) = \\frac{n}{\\lambda^2}$$\n\nThe **Cramér-Rao Lower Bound** for unbiased estimators of $\\lambda$ is:\n$$\\boxed{\\text{CRLB} = \\frac{1}{I_n(\\lambda)} = \\frac{\\lambda^2}{n}}$$\n\n### Part (c)\n\n**The MLE of $\\lambda$ is $\\hat{\\lambda} = 1/\\bar{X}$. This estimator is biased. Find an unbiased estimator of $\\lambda$ and compute its variance. Does this unbiased estimator achieve the CRLB?**\n\n**Method of Moments Approach:**\n\nFor the Exponential($\\lambda$) distribution, $E(X) = 1/\\lambda$. By the Method of Moments, we set the population mean equal to the sample mean:\n$$\\frac{1}{\\lambda} = \\bar{X}$$\n\nSolving for $\\lambda$:\n$$\\tilde{\\lambda}_{MME} = \\frac{1}{\\bar{X}}$$\n\nNote that the MME and MLE are identical in this case. However, while $\\bar{X}$ is an unbiased estimator of $1/\\lambda$, the estimator $1/\\bar{X}$ is **not** unbiased for $\\lambda$ due to Jensen's inequality (since $g(x) = 1/x$ is convex).\n\n**Finding the bias:**\n\nFor Exponential($\\lambda$), we have $\\sum_{i=1}^n X_i \\sim \\text{Gamma}(n, \\lambda)$.\n\nUsing properties of the Gamma distribution, for $Y \\sim \\text{Gamma}(n, \\lambda)$:\n$$E\\left(\\frac{1}{Y}\\right) = \\frac{\\lambda}{n-1} \\quad \\text{for } n > 1$$\n\nTherefore:\n$$E\\left(\\frac{1}{\\bar{X}}\\right) = E\\left(\\frac{n}{\\sum X_i}\\right) = \\frac{n\\lambda}{n-1}$$\n\nSo the MLE/MME is biased with $E(\\hat{\\lambda}) = \\frac{n}{n-1}\\lambda > \\lambda$.\n\n**Unbiased estimator:**\n\nTo correct the bias, multiply by $\\frac{n-1}{n}$:\n$$\\boxed{\\hat{\\lambda}_U = \\frac{n-1}{n} \\cdot \\frac{1}{\\bar{X}} = \\frac{n-1}{\\sum_{i=1}^n X_i}}$$\n\n**Variance of the unbiased estimator:**\n\nFor $Y \\sim \\text{Gamma}(n, \\lambda)$, we have:\n$$\\text{Var}\\left(\\frac{1}{Y}\\right) = \\frac{\\lambda^2}{(n-1)^2(n-2)} \\quad \\text{for } n > 2$$\n\nTherefore:\n$$\\text{Var}(\\hat{\\lambda}_U) = (n-1)^2 \\cdot \\text{Var}\\left(\\frac{1}{\\sum X_i}\\right) = (n-1)^2 \\cdot \\frac{\\lambda^2}{(n-1)^2(n-2)} = \\boxed{\\frac{\\lambda^2}{n-2}}$$\n\n**Comparison with CRLB:**\n$$\\text{Var}(\\hat{\\lambda}_U) = \\frac{\\lambda^2}{n-2} > \\frac{\\lambda^2}{n} = \\text{CRLB}$$\n\nThe unbiased estimator does **NOT** achieve the CRLB.\n\n### Part (d)\n\n**Using R, compute the MLE $\\hat{\\lambda}$ from the pilot study data. Also compute the CRLB at this estimated value. Interpret what this bound tells us about estimation precision.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pilot study data\nbp_times <- c(12, 8, 15, 6, 10, 14, 9, 11)\nn <- length(bp_times)\n\n# MLE\nlambda_mle <- 1 / mean(bp_times)\n\n# Unbiased estimator\nlambda_unbiased <- (n - 1) / sum(bp_times)\n\n# CRLB at the MLE estimate\ncrlb <- lambda_mle^2 / n\n\ncat(\"Sample size: n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: n = 8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample mean:\", mean(bp_times), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 10.625 days\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MLE of λ:\", round(lambda_mle, 4), \"per day\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE of λ: 0.0941 per day\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unbiased estimate of λ:\", round(lambda_unbiased, 4), \"per day\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnbiased estimate of λ: 0.0824 per day\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"CRLB at MLE:\", round(crlb, 6), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCRLB at MLE: 0.001107 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard error bound:\", round(sqrt(crlb), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard error bound: 0.0333 \n```\n\n\n:::\n:::\n\n\n**Interpretation:** The CRLB tells us that no unbiased estimator of $\\lambda$ can have variance smaller than 0.001107. This means the standard error of any unbiased estimator must be at least 0.0333. Our estimate of $\\lambda \\approx$ 0.0941 per day (corresponding to a mean time of 10.6 days) has inherent uncertainty—we can expect our estimates to vary by roughly ±0.067 across repeated samples of this size.\n\n\n## Problem 2: Method of Moments (Shifted Exponential Distribution)\n\nThe time (in hours) from hospital admission to discharge for patients undergoing a minor outpatient procedure can be modeled with a shifted (two-parameter) Exponential distribution. This accounts for a minimum required observation time $\\theta$ plus additional random waiting time. The pdf is:\n$$f(x; \\lambda, \\theta) = \\lambda e^{-\\lambda(x - \\theta)}, \\quad x \\geq \\theta, \\quad \\lambda > 0, \\quad \\theta > 0$$\n\nFor this distribution:\n$$E(X) = \\theta + \\frac{1}{\\lambda}, \\quad \\text{Var}(X) = \\frac{1}{\\lambda^2}$$\n\n### Part (a)\n\n**Derive the Method of Moments estimators $\\tilde{\\lambda}$ and $\\tilde{\\theta}$ in terms of the sample mean $\\bar{X}$ and sample standard deviation $S$.**\n\n**Step 1:** From the variance equation, solve for $\\lambda$:\n$$\\text{Var}(X) = \\frac{1}{\\lambda^2}$$\n\nSetting the population variance equal to the sample variance $S^2$:\n$$S^2 = \\frac{1}{\\lambda^2} \\implies \\lambda = \\frac{1}{S}$$\n\n**Step 2:** Substitute into the mean equation to find $\\theta$:\n$$E(X) = \\theta + \\frac{1}{\\lambda}$$\n\nSetting the population mean equal to the sample mean $\\bar{X}$:\n$$\\bar{X} = \\theta + \\frac{1}{\\lambda} = \\theta + S$$\n$$\\theta = \\bar{X} - S$$\n\n**Method of Moments Estimators:**\n$$\\boxed{\\tilde{\\lambda} = \\frac{1}{S}}$$\n$$\\boxed{\\tilde{\\theta} = \\bar{X} - S}$$\n\n### Part (b)\n\n**Using R, calculate the MME estimates $\\tilde{\\lambda}$ and $\\tilde{\\theta}$. Verify that your estimate of $\\theta$ is less than the minimum observed value.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Discharge times (hours)\ndischarge_times <- c(3.2, 4.1, 2.8, 5.3, 3.5, 4.8, 3.1, 6.2, 4.4, 3.9)\nn <- length(discharge_times)\n\n# Sample statistics\nxbar <- mean(discharge_times)\ns <- sd(discharge_times)\n\n# Method of Moments estimates\nlambda_mme <- 1 / s\ntheta_mme <- xbar - s\n\ncat(\"Sample size: n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: n = 10 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample mean:\", round(xbar, 4), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 4.13 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:\", round(s, 4), \"hours\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD: 1.0709 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MME estimates:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMME estimates:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  λ̃ =\", round(lambda_mme, 4), \"per hour\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  λ̃ = 0.9338 per hour\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  θ̃ =\", round(theta_mme, 4), \"hours\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  θ̃ = 3.0591 hours\n```\n\n\n:::\n\n```{.r .cell-code}\n# Validity check\nmin_obs <- min(discharge_times)\ncat(\"Validity check:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValidity check:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Minimum observed value:\", min_obs, \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Minimum observed value: 2.8 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  θ̃ =\", round(theta_mme, 4), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  θ̃ = 3.0591 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Is θ̃ < min(X)?\", theta_mme < min_obs, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Is θ̃ < min(X)? FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\n# Interpretation\ncat(\"Interpretation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Estimated minimum observation time:\", round(theta_mme, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Estimated minimum observation time: 3.06 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Estimated mean additional wait time:\", round(1/lambda_mme, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Estimated mean additional wait time: 1.07 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Estimated total mean discharge time:\", round(theta_mme + 1/lambda_mme, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Estimated total mean discharge time: 4.13 hours\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The MME estimates suggest that patients require a minimum of approximately 3.06 hours of observation, with an additional expected random waiting time of 1.07 hours before discharge. The validity check confirms that $\\tilde{\\theta} =$ 3.06 is less than the smallest observed discharge time (2.8 hours), which is necessary for the model to be consistent with the data.\n\n\n## Problem 3: Maximum Likelihood Estimation (Devore 7.25)\n\nLet $X_1, X_2, \\ldots, X_n$ be a random sample from a distribution with pdf:\n$$f(x; \\theta) = (\\theta + 1)x^\\theta, \\quad 0 \\le x \\le 1, \\quad \\theta > -1$$\n\n### Part (a)\n\n**Derive the maximum likelihood estimator $\\hat{\\theta}$ of $\\theta$.**\n\n**Likelihood:**\n$$L(\\theta) = \\prod_{i=1}^n (\\theta + 1) x_i^\\theta = (\\theta + 1)^n \\prod_{i=1}^n x_i^\\theta = (\\theta + 1)^n \\left(\\prod_{i=1}^n x_i\\right)^\\theta$$\n\n**Log-likelihood:**\n$$\\ell(\\theta) = n \\ln(\\theta + 1) + \\theta \\sum_{i=1}^n \\ln(x_i)$$\n\n**First derivative:**\n$$\\ell'(\\theta) = \\frac{n}{\\theta + 1} + \\sum_{i=1}^n \\ln(x_i)$$\n\n**Setting $\\ell'(\\theta) = 0$:**\n$$\\frac{n}{\\theta + 1} = -\\sum_{i=1}^n \\ln(x_i)$$\n$$\\theta + 1 = \\frac{n}{-\\sum_{i=1}^n \\ln(x_i)} = \\frac{-n}{\\sum_{i=1}^n \\ln(x_i)}$$\n$$\\theta = \\frac{-n}{\\sum_{i=1}^n \\ln(x_i)} - 1$$\n\n**MLE:**\n$$\\boxed{\\hat{\\theta} = \\frac{-n}{\\sum_{i=1}^n \\ln(x_i)} - 1 = -1 - \\frac{1}{\\overline{\\ln(X)}}}$$\n\nwhere $\\overline{\\ln(X)} = \\frac{1}{n}\\sum_{i=1}^n \\ln(x_i)$.\n\n**Verification (second derivative test):**\n$$\\ell''(\\theta) = -\\frac{n}{(\\theta + 1)^2} < 0$$\n\nThis confirms we have a maximum.\n\n### Part (b)\n\n**For a sample of size $n = 5$ with observations $x_1 = 0.92, x_2 = 0.79, x_3 = 0.85, x_4 = 0.95, x_5 = 0.88$, compute the MLE $\\hat{\\theta}$.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0.92, 0.79, 0.85, 0.95, 0.88)\nn <- length(x)\n\n# MLE calculation\nsum_ln_x <- sum(log(x))\ntheta_mle <- -n / sum_ln_x - 1\n\ncat(\"Observations:\", x, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations: 0.92 0.79 0.85 0.95 0.88 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sum of ln(x_i):\", round(sum_ln_x, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum of ln(x_i): -0.6607 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MLE θ̂ =\", round(theta_mle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE θ̂ = 6.5672 \n```\n\n\n:::\n:::\n\n\n### Part (c)\n\n**Use the invariance property of MLEs to find the MLE of $\\tau(\\theta) = \\frac{\\theta + 1}{\\theta + 2}$, which represents $E(X)$ for this distribution.**\n\nBy the **invariance property of MLEs**, the MLE of $\\tau(\\theta) = g(\\theta)$ is $\\hat{\\tau} = g(\\hat{\\theta})$.\n\nTherefore:\n$$\\hat{\\tau} = \\frac{\\hat{\\theta} + 1}{\\hat{\\theta} + 2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntau_mle <- (theta_mle + 1) / (theta_mle + 2)\ncat(\"MLE of τ(θ) = (θ+1)/(θ+2):\", round(tau_mle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE of τ(θ) = (θ+1)/(θ+2): 0.8833 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample mean (for comparison):\", round(mean(x), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean (for comparison): 0.878 \n```\n\n\n:::\n:::\n\n\nNote: The MLE of $E(X)$ (0.8833) is close to but not exactly equal to the sample mean (0.878). This is expected since the MLE uses the full likelihood structure of the distribution.\n\n\n## Problem 4: Sufficient Statistics (Medical Application)\n\nA researcher is studying the number of adverse events reported per patient in a drug trial. The number of adverse events $X$ follows a Poisson($\\mu$) distribution.\n\n### Part (a)\n\n**For a random sample $X_1, \\ldots, X_n$ from Poisson($\\mu$), use the Neyman Factorization Theorem to show that $T = \\sum_{i=1}^n X_i$ is a sufficient statistic for $\\mu$.**\n\nFor $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} \\text{Poisson}(\\mu)$, the joint pmf is:\n\n$$f(x_1, \\ldots, x_n; \\mu) = \\prod_{i=1}^n \\frac{e^{-\\mu} \\mu^{x_i}}{x_i!} = \\frac{e^{-n\\mu} \\mu^{\\sum_{i=1}^n x_i}}{\\prod_{i=1}^n x_i!}$$\n\nWe can factor this as:\n$$f(x_1, \\ldots, x_n; \\mu) = \\underbrace{e^{-n\\mu} \\mu^{\\sum x_i}}_{g(T; \\mu)} \\cdot \\underbrace{\\frac{1}{\\prod_{i=1}^n x_i!}}_{h(x_1, \\ldots, x_n)}$$\n\nwhere $T = \\sum_{i=1}^n X_i$.\n\n- $g(T; \\mu) = e^{-n\\mu} \\mu^T$ depends on the data **only through** $T$ and involves $\\mu$\n- $h(x_1, \\ldots, x_n) = 1/\\prod x_i!$ depends only on the data, **not on** $\\mu$\n\nBy the **Neyman Factorization Theorem**, $T = \\sum_{i=1}^n X_i$ is **sufficient for $\\mu$**. $\\square$\n\n### Part (b)\n\n**Show that the MLE $\\hat{\\mu} = \\bar{X}$ is a function of the sufficient statistic $T$.**\n\nThe MLE is:\n$$\\hat{\\mu} = \\bar{X} = \\frac{1}{n}\\sum_{i=1}^n X_i = \\frac{T}{n}$$\n\nSince $\\hat{\\mu} = T/n$, the MLE can be written purely as a function of the sufficient statistic $T$. $\\checkmark$\n\n### Part (c)\n\n**Using R simulation, generate 1000 samples from Poisson($\\mu = 1.5$) with $n = 50$ and compare the bias, variance and MSE of $\\hat{\\mu}$ and $\\tilde{\\mu}$.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nn <- 50\nmu_true <- 1.5\nn_sims <- 1000\n\n# Simulation\nsim_results <- tibble(sim = 1:n_sims) |>\n  mutate(\n    data = map(sim, \\(s) rpois(n, mu_true)),\n    mu_hat = map_dbl(data, mean),                    # MLE (based on sufficient stat)\n    mu_tilde = map_dbl(data, \\(x) mean(x > 0))       # Proportion with events\n  )\n\n# Compute summaries\nsummary_stats <- sim_results |>\n  summarize(\n    Estimator = c(\"μ̂ = X̄ (MLE)\", \"μ̃ = proportion(X > 0)\"),\n    True_Value = c(mu_true, 1 - exp(-mu_true)),  # Note: E(μ̃) = P(X > 0) = 1 - e^(-μ)\n    Mean = c(mean(mu_hat), mean(mu_tilde)),\n    Bias = c(mean(mu_hat) - mu_true, mean(mu_tilde) - mu_true),\n    Variance = c(var(mu_hat), var(mu_tilde)),\n    MSE = c(mean((mu_hat - mu_true)^2), mean((mu_tilde - mu_true)^2))\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Returning more (or less) than 1 row per `summarise()` group was deprecated in\ndplyr 1.1.0.\ni Please use `reframe()` instead.\ni When switching from `summarise()` to `reframe()`, remember that `reframe()`\n  always returns an ungrouped data frame and adjust accordingly.\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 6\n  Estimator             True_Value  Mean     Bias Variance    MSE\n  <chr>                      <dbl> <dbl>    <dbl>    <dbl>  <dbl>\n1 μ̂ = X̄ (MLE)                1.5   1.50   0.00384  0.0309  0.0309\n2 μ̃ = proportion(X > 0)      0.777 0.778 -0.722    0.00367 0.525 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualization\nsim_results |>\n  pivot_longer(cols = c(mu_hat, mu_tilde), \n               names_to = \"Estimator\", values_to = \"Estimate\") |>\n  mutate(Estimator = case_when(\n    Estimator == \"mu_hat\" ~ \"μ̂ = X̄ (MLE)\",\n    Estimator == \"mu_tilde\" ~ \"μ̃ = proportion(X > 0)\"\n  )) |>\n  ggplot(aes(x = Estimate, fill = Estimator)) +\n  geom_histogram(alpha = 0.6, bins = 30, position = \"identity\") +\n  geom_vline(xintercept = mu_true, linetype = \"dashed\", color = \"red\", linewidth = 1) +\n  labs(title = \"Sampling Distributions of Two Estimators for μ\",\n       subtitle = paste(\"True μ =\", mu_true, \"| n =\", n, \"| Simulations =\", n_sims),\n       x = \"Estimate\", y = \"Frequency\") +\n  scale_fill_brewer(palette = \"Set1\") +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](HW_02_Solutions1_files/figure-pdf/prob4-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Interpretation:** \n\n- The MLE $\\hat{\\mu} = \\bar{X}$ is essentially unbiased with bias ≈ 0 and estimates $\\mu$ directly.\n- The proportion estimator $\\tilde{\\mu}$ is heavily biased because it estimates $P(X > 0) = 1 - e^{-\\mu} \\approx$ 0.777, not $\\mu$ itself.\n- Even though $\\tilde{\\mu}$ has smaller variance, its large bias results in much larger MSE.\n- The MLE, which is based on the sufficient statistic $T = \\sum X_i$, is clearly superior for estimating $\\mu$.\n\n\n## Problem 5: MLE for Normal Variance (Devore 7.31 Modified)\n\nMeasurement errors in a laboratory instrument are assumed to follow a Normal distribution with known mean $\\mu = 0$ and unknown variance $\\sigma^2$. A sample of $n$ measurements yields observations $X_1, \\ldots, X_n$.\n\n### Part (a)\n\n**Derive the MLE of $\\sigma^2$.**\n\nFor $X_i \\stackrel{iid}{\\sim} N(0, \\sigma^2)$, the pdf is:\n$$f(x; \\sigma^2) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-x^2/(2\\sigma^2)}$$\n\n**Likelihood:**\n$$L(\\sigma^2) = \\prod_{i=1}^n \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-x_i^2/(2\\sigma^2)} = (2\\pi\\sigma^2)^{-n/2} \\exp\\left(-\\frac{\\sum_{i=1}^n x_i^2}{2\\sigma^2}\\right)$$\n\n**Log-likelihood:**\n$$\\ell(\\sigma^2) = -\\frac{n}{2}\\ln(2\\pi) - \\frac{n}{2}\\ln(\\sigma^2) - \\frac{\\sum_{i=1}^n x_i^2}{2\\sigma^2}$$\n\n**Derivative with respect to $\\sigma^2$:**\n$$\\frac{\\partial \\ell}{\\partial \\sigma^2} = -\\frac{n}{2\\sigma^2} + \\frac{\\sum_{i=1}^n x_i^2}{2(\\sigma^2)^2}$$\n\n**Setting equal to zero:**\n$$\\frac{n}{2\\sigma^2} = \\frac{\\sum_{i=1}^n x_i^2}{2(\\sigma^2)^2}$$\n$$n\\sigma^2 = \\sum_{i=1}^n x_i^2$$\n\n**MLE:**\n$$\\boxed{\\hat{\\sigma}^2 = \\frac{1}{n}\\sum_{i=1}^n X_i^2}$$\n\n### Part (b)\n\n**Is this MLE unbiased? If not, find the bias.**\n\nSince $X_i \\sim N(0, \\sigma^2)$, we have:\n$$E(X_i^2) = \\text{Var}(X_i) + [E(X_i)]^2 = \\sigma^2 + 0 = \\sigma^2$$\n\nTherefore:\n$$E(\\hat{\\sigma}^2) = E\\left(\\frac{1}{n}\\sum_{i=1}^n X_i^2\\right) = \\frac{1}{n} \\cdot n \\cdot \\sigma^2 = \\sigma^2$$\n\nThe MLE **is unbiased**:\n$$\\boxed{\\text{Bias}(\\hat{\\sigma}^2) = E(\\hat{\\sigma}^2) - \\sigma^2 = 0}$$\n\n### Part (c)\n\n**A technician takes $n = 15$ measurements and records: $\\sum_{i=1}^{15} X_i^2 = 4.8$**\n\n**Calculate the MLE of $\\sigma^2$ and provide an unbiased estimate.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 15\nsum_x_squared <- 4.8\n\n# MLE (which is also unbiased in this case)\nsigma2_mle <- sum_x_squared / n\n\ncat(\"n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 15 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sum of X_i² =\", sum_x_squared, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum of X_i² = 4.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MLE of σ²:\", round(sigma2_mle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE of σ²: 0.32 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unbiased estimate of σ²:\", round(sigma2_mle, 4), \"(same as MLE)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnbiased estimate of σ²: 0.32 (same as MLE)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Estimated σ:\", round(sqrt(sigma2_mle), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated σ: 0.5657 \n```\n\n\n:::\n:::\n\n\n**Note:** In this special case where $\\mu = 0$ is known, the MLE $\\hat{\\sigma}^2 = \\frac{1}{n}\\sum X_i^2$ is already unbiased. This is different from the usual case where $\\mu$ is unknown, in which case the MLE $\\frac{1}{n}\\sum(X_i - \\bar{X})^2$ is biased and we use $\\frac{1}{n-1}\\sum(X_i - \\bar{X})^2$ for an unbiased estimate.\n",
    "supporting": [
      "HW_02_Solutions1_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}