---
title: "DRAFT Schedule"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

Last year, did material in 17 classes. Can I make that more efficient??

| class | Lesson | Topic | TB | Things covered |
|----|----|----|----|----|
| 1 |  | Welcome |  | Hello and stuff |
|  | 1 | Introduction to Probability | 1.1, 2.1, 2.2, 2.4 | randomness, probability, single coin toss + simulation, def of prob, outcomes, events, sample space |
| 2 | 2 | Language of Probability and Simulations | 2.2, 2.4, | union, intersections, complements, mutually exclusive, prob axioms, prob properties, de morgans laws, partitions |
| 3 |  | Introduction to Simulations | 2.5 |  |
| 4 | 3 | Rules of probability | 3.5, 2.7, 3.4, 3.3 | multiplication rule, law of total probability, bayes rule, conditional prob, independence, fun link: <https://pudding.cool/2018/04/birthday-paradox/> |
| 5 |  | Equally Likely Outcomes (some counting) | 3.6 |  |
| 6 | pre-24 | Optional class: Calculus Review |  |  |
| 7 | 7 | Random Variables | 2.3, 4.1 |  |
|  | 8 | pmfs | 4.2 |  |
| 8 |  | pdfs | 4.3 |  |
|  |  | CDFs | 4.4 |  |
| 9 | 9 | Tranformations of distributions, joint distributions | 4.6, 4.7 |  |
| 10 |  | Independence and Conditioning (Joint Distributions) | 4.8, 4.9 |  |
| 11 | 10 | Expected Values | 5.1 |  |
|  | 11 | Expected Values of *sums* | 5.5 |  |
|  |  | conditional expect value | 5.6 |  |
| 12 | 12 | Variance | 5.2, 5.3 |  |
| 13 | 14-20 | Some Important Discrete RVs | 6 |  |
| 14 | 31-35 | Some Important Continuous RVs | 7 |  |
| 15 | 37 | Central limit theorem | 8.1 |  |
|  | 43 | Moment generating functions |  |  |
| 16 |  | MGF part 2?? |  |  |
| 17 |  |  |  |  |

: {.striped .hover tbl-colwidths="\[ 6, 6, 15, 6, 40\]"}
