---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

|  |  |  |  |  |  |  |  |  |  |  |
|-------|:-----:|:------|:------|:------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| Week | Date | Exit tix | Lesson | Topics | [TB](https://librarysearch.ohsu.edu/permalink/01ALLIANCE_OHSU/okd4j/alma99900609916301858) | Key Info | Slides HTML | Slides PDF | Slides Notes | Muddy Points |
| 1 | `{r} w1d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/UT6bq9k6Gr)]{style="color:#f8f5f0;"} | 0 | Welcome |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Intro/00_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Intro/00_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 1 | Introduction to Statistical Inference; Statistics | 6.1, 6.2 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Intro_Inference/01_Intro_Inference.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Intro_Inference/01_Intro_Inference.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 2 | Point estimation; Bias, variance, and MSE of estimators | 7.1 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Point_Estimation/02_Point_Estimation.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Point_Estimation/02_Point_Estimation.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/mu5tEQ3dyT)]{style="color:#f8f5f0;"} | 2 | ctd. |  |  |  |  |  |  |
|  |  |  | 3 | Unbiased estimators, MVUE, Likelihood Theory | 7.1, 7.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_MVUE_Likelihood/03_MVUE.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_MVUE_Likelihood/03_MVUE.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw0 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  | [[**HW 0 due 11pm**](/homework/HW_00.qmd)]{style="color:#006a4e;"} |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/E9rSVzzdsT)]{style="color:#f8f5f0;"} | 3 | ctd. |  |  |  |  |  |  |
|  |  |  | 4 | Method of Moments and MLE | 7.2 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/04_MME_MLE/04_MME_MLE.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/04_MME_MLE/04_MME_MLE.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w2d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/9WVvN6QQc2)]{style="color:#f8f5f0;"} | 5 | Sufficient Statistics | 7.3 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/05_Sufficiency/05_Sufficient_Statistics.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/05_Sufficiency/05_Sufficient_Statistics.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw1 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  | [[**HW 1 due 11pm**](/homework/HW_01.qmd)]{style="color:#006a4e;"} |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 3 | `r w3d1 %>% format("%m/%d")` |  | No class |  |  |  |  |  |  |  |
|  | `r w3d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/7R1UpfENta)]{style="color:#f8f5f0;"} | 6 | Review Point Estimation | 7 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/06_Review_Point_Estimation/06_Review_Point_Estimation.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/06_Review_Point_Estimation/06_Review_Point_Estimation.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 7 | Interval estimation | 8.1 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/07_Confidence_Intervals/07_Confidence_Intervals.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/07_Confidence_Intervals/07_Confidence_Intervals.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw2 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  | [[**HW 2 due 11 pm**](/homework/HW_02.qmd)]{style="color:#006a4e;"} |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 4 | `r w4d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/bPtdPWu2ap)]{style="color:#f8f5f0;"} | 8 | Interval estimation: single sample, one-sample t, population proportions | 8.1-8.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/08_CI_One_Sample/08_CI_One_Sample.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/08_CI_One_Sample/08_CI_One_Sample.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w4d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/bNudGf5LiE)]{style="color:#f8f5f0;"} | 9 | Bootstrap Introduction | 8.1-8.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/09_Bootstrap_Introduction/09_Bootstrap_Introduction.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/09_Bootstrap_Introduction/09_Bootstrap_Introduction.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 10 | Bootstrap confidence intervals | 8.5 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/10_Bootstrap_CI/10_Bootstrap_CI.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/10_Bootstrap_CI/10_Bootstrap_CI.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw3 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  | [[**HW 3 due 11 pm**](/homework/HW_03.qmd)]{style="color:#006a4e;"} |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 5 | `r w5d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWC-f_NLwhR1PupeCDJVbs-lUOVhSQ01GMkZJOTI4VUs4WUNPNlk4UDJCVS4u)]{style="color:#f8f5f0;"} | 11 | More Confidence Intervals + Review | 8 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/11_Review_Confidence_Intervals/11_Review_Confidence_Intervals.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/11_Review_Confidence_Intervals/11_Review_Confidence_Intervals.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | **`r mid_open %>% format("%m/%d")`** |  |  | [**Midterm assigned 02/02 (take-home)**](/homework/Midterm_Exam.qmd) |  |  |  |  |  |  |
|  | `r w5d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/Smia0wzbL8)]{style="color:#f8f5f0;"} | 12 | Hypotheses and Test Procedures; Type I and Type II Errors | 9.1 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/12_Hypothesis_Testing_Introduction/12_Hypothesis_Testing_Introduction.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/12_Hypothesis_Testing_Introduction/12_Hypothesis_Testing_Introduction.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 13 | Tests About a Population Mean (z and t tests); Tests About a Population Proportion | 9.2-9.3 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/13_Tests_Mean_Proportion/13_Tests_Mean_Proportion.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/13_Tests_Mean_Proportion/13_Tests_Mean_Proportion.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  | [[**HW 4 due 11 pm**](/homework/HW_04.qmd)]{style="color:#006a4e;"} |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 6 | `r w6d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/xBEJYE3WP8)]{style="color:#f8f5f0;"} | 14 | P-Values; Power and Sample Size Determination | 9.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/14_PValues_Power_SampleSize/14_PValues_Power_SampleSize.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/14_PValues_Power_SampleSize/14_PValues_Power_SampleSize.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w6d2 %>% format("%m/%d")` |  | No class |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 7 | `r w7d1 %>% format("%m/%d")` |  | No class |  |  |  |  |  |  |  |
|  | **`r mid_close %>% format("%m/%d")`** |  |  | **Midterm due 11pm** |  |  |  |  |  |  |
|  | `r w7d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/XYtQRvQGw6)]{style="color:#f8f5f0;"} | 14 | ctd. |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 8 | `r w8d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/EVHrjNq6fB)]{style="color:#f8f5f0;"} | 15 | Neyman-Pearson Lemma; Likelihood Ratio Tests | 9.5 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/15_NeymanPearson_LRT/15_NeymanPearson_LRT.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/15_NeymanPearson_LRT/15_NeymanPearson_LRT.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w8d2 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/U57EQVtUFn)]{style="color:#f8f5f0;"} | 16 | Further Aspects of Hypothesis Testing; Relationship between Testing and Interval Estimation | 9.6 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/16_FurtherHypothesisTesting/16_FurtherHypothesisTesting.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/16_FurtherHypothesisTesting/16_FurtherHypothesisTesting.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  |  | 17 | Bootstrap Hypothesis Testingfor One Sample | C&H 8 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/17_BootstrapHypothesisTesting/17_BootstrapHypothesisTesting.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/17_BootstrapHypothesisTesting/17_BootstrapHypothesisTesting.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | **`r hw5 %>% format("%m/%d")`** |  |  | [**HW 5 due 11 pm**](/homework/HW_05.qmd) |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 9 | `r w9d1 %>% format("%m/%d")` | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/r/rmVdBxjtAi)]{style="color:#f8f5f0;"} | 18 | Two-Sample Confidence Intervals and Tests | 9.5-9.6 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/18_TwoSampleTests/18_TwoSampleTests.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/18_TwoSampleTests/18_TwoSampleTests.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w9d2 %>% format("%m/%d")` | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | 19 | Analysis of Paired Data | 10.3 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/19_PairedData/19_PairedData.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/19_PairedData/19_PairedData.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | **`r hw6 %>% format("%m/%d")`** |  |  | [**HW 6 due 11 pm**](/homework/HW_06.qmd) |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 10 | `r w10d1 %>% format("%m/%d")` | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | 20 | Bootstrap and Permutation Methods for Two Samples | 10.6, C&H 3,5 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w10d2 %>% format("%m/%d")` | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | 21 | Nonparametric Inference |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | **`r hw7 %>% format("%m/%d")`** |  |  | [**HW 7 due 11 pm**](/homework/HW_07.qmd) |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 11 | `r w11d1 %>% format("%m/%d")` |  |  | Finals week (no class) |  |  |  |  |  |  |
|  | **`r final_close %>% format("%m/%d")`** |  |  | **Final Exam due 11 pm** |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 6,40,12, 6, 6, 6, 6, 6,\]"}
