---
title: "BSTA 551 Syllabus"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    page-layout: full
  pdf: default
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #639976;
  background-color: #fff;
  padding: 0px;
}

.description{
  font-size: 20px;
  color: #fff;
  background-color: #639976;
  padding: 10px;
}
```

## Key Course Info

-   **If an assignment on Sakai is closed** or you are submitting late work, please email me AND the TA your work
-   The class instruction will end on March 11, 2026. **All coursework is expected to be completed by Wednesday of finals week March 18, 2026 at 11:59pm.**

## Description

Welcome to BSTA 551! In this course we will study the theoretical foundaton of statistical inference which includes estimation and hypothesis testing. This is the official course description:

This course introduces theoretical foundation in Biostatistics. Topics will include distributions of random variables (location-scale families and exponential families), data reduction (sufficiency and completeness of statistics), methods of estimation (method of moment estimators and maximum likelihood estimators), convergence, finite and large sample properties of estimators, interval estimation, hypothesis testing, asymptotic tests (likelihood-ratio tests, score tests, and Wald tests), and statistical simulations to evaluate statistical methods.

### Course Learning Objectives

At the end of this course, students should be able to...

1.  Explain the major concepts and theorems in statistical inference.
2.  Connect theoretical concepts to statistical analyses.
3.  Conduct simulations to study and evaluate statistical methods.

## Instructors

[Here is the instructor page.](instructors.qmd)

## Meeting Times

Mondays          10:00 AM -- 12:00 PM PST (see Sakai for room)

Wednesdays    10:00 AM -- 12:00 PM PST

### Known Exceptions

-   Monday, January 19: No class (holiday)
-   Wednesday, February 10: No class
-   Monday, February 16: No class (holiday)
-   March 16 and 18: Finals week, no in person teaching, possibly virtual office hours as needed

```{r}
#| echo: false
g=3
```

## Materials

### Textbook

#### Modern Mathematical Statistics with Applications, 3rd ed.

-   **Author:** JL Devore, KN Berk, MA Carlton

-   [Textbook available online through library](https://librarysearch.ohsu.edu/permalink/01ALLIANCE_OHSU/okd4j/alma99900609916301858)

-   Citation: Devore JL, Berk KN, Carlton MA. Modern Mathematical Statistics with Applications. Third edition. Springer; 2021. doi:10.1007/978-3-030-55156-8

-   Focus on chapters 6-10

#### Supplemental Readings (Optional)

-   *Statistical Inference*, Casella and Berger, 2nd ed. (This was the previous textbook BSTA 551-552 Math Stat., very theoretical) [ebook OHSU library link](https://librarysearch.ohsu.edu/permalink/01ALLIANCE_OHSU/19jn9i0/alma99900537344401858)

-   *An Introduction to R* ([free pdf available](http://cran.r-project.org/manuals.html))

-   *Statistical Inference via Data Science, A ModernDive into R and the Tidyverse*, Ismay, Kim, Valdivia, 2nd ed. [free ebook online](https://moderndive.com/v2/index.html)

### Online Resources

#### Sakai

While most course materials will be delivered online through this website, assignments will be turned in through [Sakai](https://sakai.ohsu.edu/), OHSU's course management system. I will include a link on this website to the Sakai assignment page. 

#### PennState STAT 415 Website

Dr. Wakim linked to Penn State's probability course materials for 550. They also have the subsequent inference course on the website as well. They have all their [course notes posted on this page](https://online.stat.psu.edu/stat415/) if you wish to have an alternative reference.

#### University of South Carolina STAT 713 Website

This is a more thoeretical version (similar to previous math/stats courses taught at OHSU) of statistical inference taught by Professor Tebbs at U of SC. Their notes [which are linked on the course website](https://people.stat.sc.edu/Tebbs/stat713/index.htm) are very well written. If you want more theoretical context for what we are learning in this course this is a good source. Note, it uses Casella & Berger's textbook *Statistical Inference* as a reference.

#### R: Statistical Computing Software

R/Rstudio will be used to complete some homework assignments. Please see [Dr. Wakim's BSTA 550 syllabus](http://localhost:6712/syllabus.html) section on R if you need any references or refreshers on how to use.

## Assessment

### Breakdown

#### Grading & Requirements

#### Homework grading

#### Viewing Grades in Sakai

Points you receive for graded activities will be posted to the Sakai Gradebook. Click on the Gradebook link on the left navigation to view your points.

## Course & Instructor Evaluations

### Ongoing Course Feedback

### Final Course Feedback

At the conclusion of the course, you will be asked to complete a formal online review of the course and the instructor. Your feedback on this University evaluation is critical to improving future student learning in this course as well as providing metrics relevant to the instructor's career advancement (or lack of). Since our class is on the smaller side, everyone's participation is needed for feedback to be released.

## Schedule

[Please refer to the Schedule page.](/schedule.qmd) I will make changes to this schedule if we need more or less time on a concept. You do not need to read the corresponding chapters in the textbook for each class.

### Assignments

Written problem sets, approximately weekly, usually assigned Wednesday and due the following Wednesday.

Homework problems requiring a written solution are assigned approximately one week in advance of their due date. Homework assignments will be posted in the Sakai submissions box.

## Course Policies and Resources

### Late Work Policy

I encourage you to make your best effort to submit all assignments on time, but I understand circumstances arise that are beyond our control. Please see this [Swansea University's page on extenuating circumstances](https://myuni.swansea.ac.uk/academic-life/extenuating-circumstances/#how-can-the-university-support-me-and-what-should-i-do=is-expanded&what-are-extenuating-circumstances=is-expanded&what-isnt-an-extenuating-circumstance=is-expanded&what-supporting-evidence-is-required=is-expanded&who-should-i-contact-to-make-an-extenuating-circumstances-application=is-expanded&who-will-make-a-decision-on-my-application=is-expanded) for some examples. Not all circumstances are covered here, so please reach out if you have questions. 

-   The class will end on March 18, 2026. **All coursework is expected to be completed by March 20, 2026 at 11pm.** If you have *extenuating circumstances*, and need additional time to complete class assignments, please contact me. Together, we will come up with a plan for completion and to sort out registrar logistics. If you need an Incomplete, generally this requires request two weeks before the end of class.

-   If you have extenuating circumstances that may jeopardize your ability to do work for several weeks, please contact me. We will come up with a plan to keep you on track in the course and prevent any delay in your education.

-   For homework, you will have TWO no-questions-asked, 3-day extensions: one for the first assignment part and one for either the solutions or presentation. Please use this wisely! You just need to send me a quick email saying "I am using my no-questions-asked extension for Homework \_\_ assignment/solutions/presentation."

-   For homework, I ask you to email me directly about any late submissions. You can explain your circumstances and may ask us for an extension. I am very likely to grant an extension, but **I want to emphasize how important it will be to stay on track with your homework**! Your group is depending on you, and delaying homework may only add stress on the next homework!

-   If you have a emergency involving your self, family, pet, friend, classmate, or anything/one deemed important to you, **please do not worry about immediately contacting me**. We can work something out after your emergency. If I contact you during an emergency, it is only because I am worried, and you do NOT need to respond until you are able. 

### Regrade Policy

If you think a question was incorrectly graded, first compare your answer to the answer key. If you believe a re-grade would be appropriate, write an email to me containing the question and a short explanation as to why the question(s) was/were incorrectly graded. Deadline: One week after assignments were returned to class (late requests will not be considered).

### Attendance Policy

You are expected to attend class, participate in-class polls, and complete the exit ticket. For students who miss class or need a review, I will make video and audio recordings of lectures available. There are no guarantees against technical or other challenges for the recording availability or quality.

**You will need to attend all classes.** There are 19 classes total, so you are welcome to watch the recordings or come in-person. While I want attendance to be a flexible thing, I need to set certain requirements around in-person attendance to align with the school's policy. Attendance is measured through exit tickets that will be due 7 days after each class.

This is meant to keep you on track within the course and prevent a pile up of material. Make sure to complete the exit ticket at the end of class to demonstrate attendance.

### Plagiarism and Attribution

Please note that this section is directly sourced from Dr. Nicky Wakim's Course Policies for BSTA 550 which has itself has been motivated by [Dr. Steven Bedrick's Course Policies and Grading site](https://dmice.ohsu.edu/bedricks/courses/bmi525/policies.html) for BMI 525. (Note that this is a good example of informal attribution of someone else's work.)

In this class, it is easy to use ChatGPT or other AI tools to solve your homework for you. Many problems follow a basic structure that is especially easy for ChatGPT to solve. In this class, you may use ChatGPT to help with your homework. You may even ask for direct answers. However, there are a few things I do not want you to do:

-   **Do not copy ChatGPT's answer directly into your homework.** Your homework is graded for full credit if you turn it in, in any state, so turning in ChatGPT's answers is unacceptable. I rather see half-written answers that show what you're thinking than see a correct answer from ChatGPT.

-   **Do not stop once ChatGPT answered a question.** If it gives an explanation, interact with it! Make sure you understand the thought process of ChatGPT. Try writing out the process to help cement it in your head. Check the answer with what we learn in class.

-   **Do not use ChatGPT on our exams!** Hence, you need to really understand how to solve these problems even if you use ChatGPT on the homework.

At the end of the day, ChatGPT is a resource that will be available to you in a job and outside of school. Thus, we should use it as a tool in school as well! Let me know if ChatGPT helped you understand something! I would love to incorporate it into future classes!

::: callout-important
You can think of this class as assembling a toolbox. When a handyperson starts working for the first time, they need to buy their tools. For their first few jobs, they might need help finding their tools or remembering which tool is best used for what action. Eventually, they get to know their tools well, and using them appropriately becomes second nature.

**For now, ChatGPT can help us find and use our tools, but we need to work towards using them as second nature!**
:::

## Course Expectations

### Instructor Expectations

[*Commitment to your learning and your success\
*]{.underline}I believe that everyone has the ability to be successful in this course and I have put a lot of effort into designing the course in a way that maximizes your learning to ensure your success. Please talk to me before or after class or stop by my office if there is anything you want to discuss or about which you are unclear. I want to be supportive of your learning and growth.

[*Inclusive & supportive learning community*]{.underline}\
I believe that learning happens best when we all learn together, as a community. This means creating a space characterized by generous listening, civility, humility, patience, and hospitality. I will attempt to promote a safe climate where we examine content from multiple perspectives. I will strive to create and maintain a classroom atmosphere in which you feel free to both listen to others and express your views and ask questions to increase your learning.

[*Openness to feedback*]{.underline}\
I appreciate straightforward feedback from you regarding how well the class is meeting your needs. Let me know if material is not clear or when its relevance to the student learning outcomes for the course is not apparent. In particular, let me know if you identify bias or stereotyping in my teaching materials as I will seek to continuously improve. Please also let me know if there's an aspect of the class you find particularly interesting, helpful, or enjoyable!

[*Responsiveness\
*]{.underline}I will monitor email as well as the discussion board daily and try respond to all messages within 24 hours Monday-Friday.

[*Clear guidelines and prompt feedback on assignments*]{.underline}\
I will provide clear instructions for all assignments, and a grading rubric when applicable. The TAs and I will provide detailed feedback on your submissions and will update grades promptly in Sakai.

### Student Expectations and Resources

[*Attend class*]{.underline}**\
**You are expected to attend at least 12 scheduled class meetings in-person. Attendance is taken through exit tickets. If you have issues accessing the poll on a specific day, please let me know. 

[*Participate**\
***]{.underline}I encourage you to participate actively in class and in Slack discussions. I will expect all students, and all instructors, to be respectful of each other's contributions, whether I agree with them or not. Professional interactions are expected.

[*Build rapport*]{.underline}\
If you find that you have any trouble keeping up with assignments or other aspects of the course, make sure you let me know as early as possible. As you will find, building rapport and effective relationships are key to becoming an effective professional. Make sure that you are proactive in informing me when difficulties arise during the quarter so that I can help you find a solution in regards to coursework.

[*Complete assignments*]{.underline}\
All assignments for this course will be submitted electronically through Sakai unless otherwise instructed. I encourage you to make your best effort to submit all assignments on time, but I understand that sometimes circumstances arise that are beyond our control. If you need an extension, please contact me in congruence with the Late Policy.

[*Seek help if you need it*]{.underline}**\
**I believe it is important to support the physical and emotional well‐being of my students. If you are experiencing physical and/or mental health issues, I encourage you to use the resources on campus such as those listed below. If you have a health issue that is affecting your performance or participation in the course, and/or if you need help connecting with these resources, please contact me.

-   Student Health and Wellness Center (SHW), [Website](https://www.ohsu.edu/education/student-health-and-wellness), 503-494-8665 (OHSU Students only)

-   Student Health and Counseling (SHAC), [Website](https://www.pdx.edu/health-counseling/), 503-725-2800

[*Inform your instructor of any accommodations needed*]{.underline}\
You should speak with or email me before or during the first week of classes regarding any special needs. Students seeking academic accommodations should register with the appropriate service under the School policies below.

Some religious holidays may occur on regularly scheduled class days. Because available class hours are so limited in number, we will have to hold class on all such days. Class video recordings will be available and you are encouraged to engage with the material outside of the regular class time. Please email me about your absence. I will excuse the absece from your grade. You are also encouraged to come to office hours with questions from the session.

[*Commit to integrity*]{.underline}**\
**As a student in this course (and at PSU or OHSU) you are expected to maintain high degrees of professionalism, commitment to active learning and participation in this class and also integrity in your behavior in and out of the classroom.

Cheating and other forms of academic misconduct will not be tolerated in this course and will be dealt with firmly. Student academic misconduct refers to behavior that includes plagiarism, cheating on assignments, fabrication of data, falsification of records or official documents, intentional misuse of equipment or materials (including library materials), or aiding and abetting the perpetration of such acts. Preparation of exams, assigned on an individual basis, must represent each student's own individual effort. When used, resource materials should be cited in conventional reference format.

## Course Communications

**Sakai/Slack announcements\
**For important/urgent matters, I will communicate with you using announcements via Sakai that will be delivered to your OHSU Email account as well as displayed in the Sakai course site Announcements section. I will copy these announcements in Slack if they do not involve changes to the schedule. Unfortunately, there are certain announcements that OHSU requires I initiate behind the firewall.

**General course questions\
**It is normal to have many questions about things that relate to the course, such as clarification about assignments, course materials, or assessments. Please post these on our Slack Workspace. Please use the channels that I created for questions. You are encouraged to give answers and help each other. I will monitor these threads, so I will endorse or correct responses as needed. Please give me 24 hours to respond to questions within Monday-Friday. Work-life balance is important for me as well, so I will try to respond as quickly as I can within my healthy limits. 

**E-mail**\
E-mail should be used only for messages that are private in nature. Please send private messages to my OHSU email address (wakim\@ohsu.edu). **Messages sent through Sakai Inbox will not be answered.** Do not send messages asking general information about the class; please post those on Slack instead.

## Further Student Resources

### Academic Success Center

OHSU houses an Academic Success Center for all students. Their mission is to create a center for learning support where ALL learners can discover the resources and community that they need for finding academic success at OHSU. They provide many services to students, including: learning skills support, writing support, English for speakers of other languages (ESOL) support, and individual and group content tutoring. [Check out the SharePoint site for the Academic Success Center.](https://ohsuitg.sharepoint.com/sites/AcademicSuccessCenter)

### Student Wellness

I am committed to supporting the physical and emotional well-being of my students. Both PSU and OHSU have designated centers for student health. For OHSU, students can visit the [Behavioral Health site](https://www.ohsu.edu/education/behavioral-health), where you can find more information including the number to make an appointment. **All student visits are free.** OHSU students also have access to PSU's [Counseling Services](https://www.pdx.edu/health-counseling/counseling) through the school's Student Health & Counseling. Information on additional student resources for OHSU students are available on the OHSU [Health and Wellness Resource page](https://ohsu-psu-sph.org/health_and_wellness/). 

### Support for Food Insecurity

Students across the country experience food insecurity at high rates. OHSU and PSU both provide a list of resources to help combat food insecurity. Of note, the Committee to Improve Student Food Security (CISFS) at PSU provides a [Free Food Market](https://www.pdx.edu/student-access-center/free-food-market) on the second Monday of each month. OHSU also provides [SNAP Enrollment Assistance](https://o2.ohsu.edu/student-central/health-wellness/student-food-resources/snap.cfm). The [Supplemental Nutrition Assistance Program (SNAP)](https://oregonhunger.org/snap-for-students/) allocates money towards food for individuals below a certain income level. If you make less than \$2,430 monthly, you may wish to enroll.

### Support for Students with Children

Students who have children can use the PSU resource: [Resource Center for Students with Children](https://www.pdx.edu/students-with-children/). Resources are mostly focused on students with younger children. There are several great resources available, including: family-friendly study spaces, new baby starter packs, free kids clothing, and further information on financial resources for childcare.

# Additional information

Please go to the Syllabus tab in Sakai for the following information:

-   School Policies and Resources

-   OHSU Competencies

-   Institutional Policies and Resources

I do not include them here because I do not have the bandwidth to make sure all links and resources are up-to-date.
