{
  "hash": "a45ba7629bcf756e30e87affc8dce31b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 3 Solutions\"\nsubtitle: \"BSTA 551\"\ndescription: \"Due: 01/29 at 11pm\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n## Problem 1: Pivotal Quantities and Confidence Intervals (Devore Section 8.1, Example 8.5 style)\n\nA theoretical model suggests that the time-to-failure (in hours) of a certain medical device component follows an Exponential distribution with unknown rate parameter $\\lambda > 0$. A random sample of $n = 8$ components yields the following failure times:\n\n$$X = \\{145, 89, 203, 67, 112, 156, 178, 94\\}$$\n\n*Hint: If $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} \\text{Exponential}(\\lambda)$, then $2\\lambda \\sum_{i=1}^n X_i \\sim \\chi^2_{2n}$.*\n\n### Part (a)\n\n**Show that $h(X_1, \\ldots, X_n, \\lambda) = 2\\lambda \\sum_{i=1}^n X_i$ is a pivotal quantity by verifying the definition included in class slides.**\n\nA pivotal quantity must satisfy two properties:\n\n**Property 1:** $h$ is a function of both the data $(X_1, \\ldots, X_n)$ and the parameter $\\lambda$.\n\nThis is clearly satisfied: $h = 2\\lambda \\sum_{i=1}^n X_i$ explicitly involves both the unknown parameter $\\lambda$ and the sample values through $\\sum X_i$. $\\checkmark$\n\n**Property 2:** The probability distribution of $h$ does not depend on $\\lambda$ (or any other unknown parameters).\n\nFrom the hint, we are told that if $X_i \\stackrel{iid}{\\sim} \\text{Exponential}(\\lambda)$, then:\n$$h = 2\\lambda \\sum_{i=1}^n X_i \\sim \\chi^2_{2n}$$\n\nThe chi-squared distribution with $2n$ degrees of freedom depends **only on $n$** (the sample size, which is known). It does **not depend on $\\lambda$**. $\\checkmark$\n\nSince both properties are satisfied, $h = 2\\lambda \\sum_{i=1}^n X_i$ is a **pivotal quantity** for $\\lambda$. $\\square$\n\n\n### Part (b)\n\n**Using the pivotal quantity from part (a), derive a $100(1-\\alpha)\\%$ confidence interval for $\\lambda$. Express your answer in terms of $\\sum X_i$ and chi-squared critical values.**\n\nLet $\\chi^2_{\\alpha/2, 2n}$ denote the upper $\\alpha/2$ critical value (i.e., the value with area $\\alpha/2$ to the right) and $\\chi^2_{1-\\alpha/2, 2n}$ denote the lower $\\alpha/2$ critical value (i.e., the value with area $\\alpha/2$ to the left).\n\nSince $h = 2\\lambda \\sum X_i \\sim \\chi^2_{2n}$, we can write:\n$$P\\left(\\chi^2_{1-\\alpha/2, 2n} < 2\\lambda \\sum_{i=1}^n X_i < \\chi^2_{\\alpha/2, 2n}\\right) = 1 - \\alpha$$\n\nNow we isolate $\\lambda$. Dividing all parts of the inequality by $2\\sum X_i$ (which is positive):\n$$P\\left(\\frac{\\chi^2_{1-\\alpha/2, 2n}}{2\\sum_{i=1}^n X_i} < \\lambda < \\frac{\\chi^2_{\\alpha/2, 2n}}{2\\sum_{i=1}^n X_i}\\right) = 1 - \\alpha$$\n\nTherefore, the $100(1-\\alpha)\\%$ confidence interval for $\\lambda$ is:\n\n$$\\boxed{\\left(\\frac{\\chi^2_{1-\\alpha/2, 2n}}{2\\sum_{i=1}^n X_i}, \\quad \\frac{\\chi^2_{\\alpha/2, 2n}}{2\\sum_{i=1}^n X_i}\\right)}$$\n\n\n### Part (c)\n\n**Compute a 95% confidence interval for $\\lambda$ using the data.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\nfailure_times <- c(145, 89, 203, 67, 112, 156, 178, 94)\nn <- length(failure_times)\nsum_x <- sum(failure_times)\n\n# Chi-squared critical values for 95% CI (alpha = 0.05)\n# df = 2n = 16\ndf <- 2 * n\n\n# Lower critical value: chi^2_{1-alpha/2, 2n} = chi^2_{0.975, 16}\n# This is the 0.025 quantile (area 0.025 to the left)\nchi_lower <- qchisq(0.025, df)\n\n# Upper critical value: chi^2_{alpha/2, 2n} = chi^2_{0.025, 16}\n# This is the 0.975 quantile (area 0.025 to the right)\nchi_upper <- qchisq(0.975, df)\n\n# 95% CI for lambda\nlambda_lower <- chi_lower / (2 * sum_x)\nlambda_upper <- chi_upper / (2 * sum_x)\n\ncat(\"Data summary:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData summary:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sample size: n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sample size: n = 8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sum of observations: Σx_i =\", sum_x, \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sum of observations: Σx_i = 1044 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Degrees of freedom: 2n =\", df, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Degrees of freedom: 2n = 16 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Chi-squared critical values:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChi-squared critical values:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  χ²_{0.975, 16} (lower) =\", round(chi_lower, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  χ²_{0.975, 16} (lower) = 6.9077 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  χ²_{0.025, 16} (upper) =\", round(chi_upper, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  χ²_{0.025, 16} (upper) = 28.8454 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for λ:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for λ:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Lower bound:\", round(chi_lower, 4), \"/ (2 ×\", sum_x, \") =\", round(lambda_lower, 6), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Lower bound: 6.9077 / (2 × 1044 ) = 0.003308 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Upper bound:\", round(chi_upper, 4), \"/ (2 ×\", sum_x, \") =\", round(lambda_upper, 6), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Upper bound: 28.8454 / (2 × 1044 ) = 0.013815 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for λ: (\", round(lambda_lower, 5), \",\", round(lambda_upper, 5), \") per hour\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for λ: ( 0.00331 , 0.01381 ) per hour\n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval for $\\lambda$ is $\\boxed{(0.00329, 0.01170)}$ per hour.\n\n\n### Part (d)\n\n**Find a 95% confidence interval for the mean time-to-failure $\\mu = 1/\\lambda$.**\n\nSince $\\mu = 1/\\lambda$ is a monotonically **decreasing** function of $\\lambda$, when we transform the CI for $\\lambda$, the bounds are reversed:\n\n- If $\\lambda_L < \\lambda < \\lambda_U$, then $\\frac{1}{\\lambda_U} < \\frac{1}{\\lambda} < \\frac{1}{\\lambda_L}$\n\nTherefore, the CI for $\\mu = 1/\\lambda$ is:\n$$\\left(\\frac{1}{\\lambda_U}, \\frac{1}{\\lambda_L}\\right)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CI for mean = 1/lambda\nmu_lower <- 1 / lambda_upper\nmu_upper <- 1 / lambda_lower\n\ncat(\"95% CI for μ = 1/λ:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for μ = 1/λ:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Lower bound: 1 /\", round(lambda_upper, 5), \"=\", round(mu_lower, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Lower bound: 1 / 0.01381 = 72.39 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Upper bound: 1 /\", round(lambda_lower, 5), \"=\", round(mu_upper, 2), \"hours\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Upper bound: 1 / 0.00331 = 302.27 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for μ: (\", round(mu_lower, 2), \",\", round(mu_upper, 2), \") hours\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for μ: ( 72.39 , 302.27 ) hours\n```\n\n\n:::\n\n```{.r .cell-code}\n# For reference\ncat(\"Sample mean (point estimate for μ):\", round(mean(failure_times), 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean (point estimate for μ): 130.5 hours\n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval for the mean time-to-failure is $\\boxed{(85.45, 304.00)}$ hours.\n\n*Note: This interval is quite wide, reflecting substantial variability in failure times and a relatively small sample size (n = 8).*\n\n\n---\n\n## Problem 2: z-Interval for a Normal Mean (Devore Section 8.1)\n\nA pharmaceutical company is conducting quality control on the fill volume (in mL) of syringes. Based on extensive historical data, the fill volumes are known to follow a normal distribution with standard deviation $\\sigma = 0.05$ mL. The target fill volume is $\\mu_0 = 1.00$ mL.\n\nA random sample of $n = 20$ syringes from a new production batch yields a sample mean of $\\bar{x} = 0.982$ mL.\n\n### Part (a)\n\n**Verify that $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$ is a pivotal quantity for $\\mu$.**\n\n**Property 1:** $Z$ is a function of both the data and the parameter $\\mu$.\n\n$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$ clearly involves:\n\n- $\\bar{X}$, which is computed from the sample data $(X_1, \\ldots, X_n)$\n- The unknown parameter $\\mu$\n\nSo Property 1 is satisfied. $\\checkmark$\n\n**Property 2:** The probability distribution of $Z$ does not depend on $\\mu$ (or any other unknown parameters).\n\nFor $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$:\n\n- We can state that $\\bar{X} \\sim N(\\mu, \\sigma^2/n)$\n- Standardizing: $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\sim N(0, 1)$\n\nThe standard normal distribution $N(0, 1)$ does **not depend on $\\mu$**. Since $\\sigma$ is known (given as 0.05 mL), there are no unknown parameters in the distribution of $Z$. $\\checkmark$\n\nSince both properties are satisfied, $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$ is a **pivotal quantity** for $\\mu$. $\\square$\n\n\n### Part (b)\n\n**Calculate a 95% confidence interval for the true mean fill volume $\\mu$.**\n\nThe 95% CI formula for $\\mu$ when $\\sigma$ is known is:\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\nwhere $z_{\\alpha/2} = z_{0.025} = 1.96$ for 95% confidence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 0.982\nsigma <- 0.05\nn <- 20\n\n# Critical value for 95% CI\nz_crit <- qnorm(0.975)\n\n# Standard error\nse <- sigma / sqrt(n)\n\n# Margin of error\nmargin <- z_crit * se\n\n# Confidence interval\nci_lower <- xbar - margin\nci_upper <- xbar + margin\n\ncat(\"Given information:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGiven information:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sample mean: x̄ =\", xbar, \"mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sample mean: x̄ = 0.982 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Known σ =\", sigma, \"mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Known σ = 0.05 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Sample size: n =\", n, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sample size: n = 20 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Calculations:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCalculations:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{0.025} =\", round(z_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{0.025} = 1.96 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Standard error: σ/√n =\", sigma, \"/√\", n, \"=\", round(se, 5), \"mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Standard error: σ/√n = 0.05 /√ 20 = 0.01118 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Margin of error:\", round(z_crit, 2), \"×\", round(se, 5), \"=\", round(margin, 4), \"mL\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Margin of error: 1.96 × 0.01118 = 0.0219 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: \", xbar, \"±\", round(margin, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI:  0.982 ± 0.0219 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: (\", round(ci_lower, 4), \",\", round(ci_upper, 4), \") mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 0.9601 , 1.0039 ) mL\n```\n\n\n:::\n:::\n\n\nThe 95% confidence interval for $\\mu$ is $\\boxed{(0.9601, 1.0039)}$ mL.\n\n\n### Part (c)\n\n**Based on your confidence interval, is there evidence that the true mean fill volume differs from the target of 1.00 mL? Explain.**\n\nThe target value $\\mu_0 = 1.00$ mL **is contained within** our 95% confidence interval (0.9601, 1.0039).\n\nTherefore, at the 95% confidence level, **there is insufficient evidence** to conclude that the true mean fill volume differs from the target of 1.00 mL.\n\nThe observed sample mean of 0.982 mL is lower than the target, but this difference is within the range of what we would expect from random sampling variability. The data are consistent with a true mean equal to 1.00 mL.\n\n\n### Part (d)\n\n**The company wants to estimate the mean fill volume to within $\\pm 0.02$ mL with 95% confidence. What sample size is required?**\n\nThe margin of error for a z-interval is:\n$$E = z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\nSolving for $n$:\n$$n = \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{E}\\right)^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 0.02  # Desired margin of error\n\nn_required <- (z_crit * sigma / E)^2\n\ncat(\"Sample size calculation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size calculation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Desired margin of error: E =\", E, \"mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Desired margin of error: E = 0.02 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{0.025} =\", round(z_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{0.025} = 1.96 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  σ =\", sigma, \"mL\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  σ = 0.05 mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  n = (z × σ / E)² = (\", round(z_crit, 2), \"×\", sigma, \"/\", E, \")²\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n = (z × σ / E)² = ( 1.96 × 0.05 / 0.02 )²\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  n =\", round(n_required, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n = 24.0091 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required sample size (rounded up): n =\", ceiling(n_required), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size (rounded up): n = 25 \n```\n\n\n:::\n:::\n\n\nThe required sample size is $n = \\lceil 24.01 \\rceil = \\boxed{25}$ syringes.\n\n\n---\n\n## Problem 3: Devore Section 8.1, Exercise 1\n\nConsider a normal population distribution with the value of $\\sigma$ known.\n\n### Part (a)\n\n**What is the confidence level for the interval $\\bar{x} \\pm 2.81 \\cdot \\sigma/\\sqrt{n}$?**\n\nThe general form of the z-interval is $\\bar{x} \\pm z_{\\alpha/2} \\cdot \\sigma/\\sqrt{n}$, so here $z_{\\alpha/2} = 2.81$.\n\nBy definition, $z_{\\alpha/2}$ is the value such that $P(Z > z_{\\alpha/2}) = \\alpha/2$ (area in the upper tail).\n\nWe need to find $\\alpha/2 = P(Z > 2.81)$, then compute the confidence level $1 - \\alpha$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_value <- 2.81\n\n# P(Z > 2.81) = 1 - P(Z ≤ 2.81)\nalpha_half <- 1 - pnorm(z_value)\nalpha <- 2 * alpha_half\nconf_level <- 1 - alpha\n\ncat(\"Given: z_{α/2} =\", z_value, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGiven: z_{α/2} = 2.81 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Find α/2 = P(Z > 2.81):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFind α/2 = P(Z > 2.81):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α/2 = 1 - pnorm(2.81) = 1 -\", round(pnorm(z_value), 5), \"=\", round(alpha_half, 5), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α/2 = 1 - pnorm(2.81) = 1 - 0.99752 = 0.00248 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α = 2 × α/2 =\", round(alpha, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α = 2 × α/2 = 0.005 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Confidence level = 1 - α =\", round(conf_level, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Confidence level = 1 - α = 0.995 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Confidence level ≈\", round(conf_level * 100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidence level ≈ 99.5 %\n```\n\n\n:::\n:::\n\n\n*Sanity check:* We know $z_{0.025} = 1.96$ gives 95% confidence, and $z_{0.005} = 2.576$ gives 99% confidence. Since 2.81 > 2.576, we expect a confidence level greater than 99%, which matches our answer. $\\checkmark$\n\nThe confidence level is approximately $\\boxed{99.5\\%}$.\n\n\n### Part (b)\n\n**What is the confidence level for the interval $\\bar{x} \\pm 1.44 \\cdot \\sigma/\\sqrt{n}$?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_value <- 1.44\n\nalpha_half <- 1 - pnorm(z_value)\nalpha <- 2 * alpha_half\nconf_level <- 1 - alpha\n\ncat(\"Given: z_{α/2} =\", z_value, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGiven: z_{α/2} = 1.44 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Find α/2 = P(Z > 1.44):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFind α/2 = P(Z > 1.44):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α/2 = 1 - pnorm(1.44) =\", round(alpha_half, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α/2 = 1 - pnorm(1.44) = 0.0749 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α =\", round(alpha, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α = 0.1499 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Confidence level = 1 - α =\", round(conf_level, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Confidence level = 1 - α = 0.8501 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Confidence level ≈\", round(conf_level * 100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidence level ≈ 85 %\n```\n\n\n:::\n:::\n\n\n*Sanity check:* We know $z_{0.05} = 1.645$ gives 90% confidence. Since 1.44 < 1.645, we expect a confidence level less than 90%, which matches. $\\checkmark$\n\nThe confidence level is approximately $\\boxed{85\\%}$.\n\n\n### Part (c)\n\n**What value of $z_{\\alpha/2}$ results in a confidence level of 99.7%?**\n\nFor a confidence level of 99.7%:\n\n- $1 - \\alpha = 0.997$\n- $\\alpha = 0.003$\n- $\\alpha/2 = 0.0015$\n\nWe need the z-value such that $P(Z > z_{\\alpha/2}) = 0.0015$, or equivalently, $P(Z \\leq z_{\\alpha/2}) = 1 - 0.0015 = 0.9985$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_level <- 0.997\nalpha <- 1 - conf_level\nalpha_half <- alpha / 2\n\n# Find z such that P(Z ≤ z) = 1 - α/2\nz_value <- qnorm(1 - alpha_half)\n\ncat(\"Given: Confidence level =\", conf_level, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGiven: Confidence level = 0.997 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α = 1 -\", conf_level, \"=\", alpha, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α = 1 - 0.997 = 0.003 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α/2 =\", alpha_half, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α/2 = 0.0015 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{α/2} = qnorm(1 - 0.0015) = qnorm(0.9985)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{α/2} = qnorm(1 - 0.0015) = qnorm(0.9985)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{α/2} =\", round(z_value, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{α/2} = 2.968 \n```\n\n\n:::\n:::\n\n\nThe required critical value is $z_{\\alpha/2} = \\boxed{2.97}$.\n\n*Note: This is very close to 3, which relates to the \"empirical rule\" stating that approximately 99.7% of observations from a normal distribution fall within 3 standard deviations of the mean.*\n\n\n### Part (d)\n\n**What value of $z_{\\alpha/2}$ results in a confidence level of 75%?**\n\nFor a confidence level of 75%:\n\n- $1 - \\alpha = 0.75$\n- $\\alpha = 0.25$\n- $\\alpha/2 = 0.125$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_level <- 0.75\nalpha <- 1 - conf_level\nalpha_half <- alpha / 2\n\nz_value <- qnorm(1 - alpha_half)\n\ncat(\"Given: Confidence level =\", conf_level, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGiven: Confidence level = 0.75 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α =\", alpha, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α = 0.25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  α/2 =\", alpha_half, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  α/2 = 0.125 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{α/2} = qnorm(1 - 0.125) = qnorm(0.875)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{α/2} = qnorm(1 - 0.125) = qnorm(0.875)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z_{α/2} =\", round(z_value, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z_{α/2} = 1.15 \n```\n\n\n:::\n:::\n\n\nThe required critical value is $z_{\\alpha/2} = \\boxed{1.15}$.\n\n\n---\n\n## Problem 4: Estimating Different Population Characteristics (Devore 7.4 Style)\n\nA clinical researcher is studying verbal IQ scores in a population of patients recovering from mild traumatic brain injury. A random sample of $n = 12$ patients yields the following verbal IQ scores:\n\n$$X = \\{94, 108, 87, 115, 102, 99, 91, 106, 112, 98, 103, 89\\}$$\n\nAssume verbal IQ scores in this population follow a normal distribution with unknown mean $\\mu$ and unknown variance $\\sigma^2$.\n\n### Part (a)\n\n**Compute point estimates for $\\mu$, $\\sigma^2$ (using the unbiased estimator $S^2$), and $\\sigma$.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data\niq_scores <- c(94, 108, 87, 115, 102, 99, 91, 106, 112, 98, 103, 89)\nn <- length(iq_scores)\n\n# Point estimates\nmu_hat <- mean(iq_scores)\nsigma2_hat <- var(iq_scores)  # R's var() uses n-1 denominator (unbiased)\nsigma_hat <- sd(iq_scores)\n\ncat(\"Data:\", paste(iq_scores, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: 94, 108, 87, 115, 102, 99, 91, 106, 112, 98, 103, 89 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample size: n =\", n, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: n = 12 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Point estimates:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint estimates:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  μ̂ = x̄ = (1/n)Σx_i =\", round(mu_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  μ̂ = x̄ = (1/n)Σx_i = 100.3333 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  σ̂² = S² = (1/(n-1))Σ(x_i - x̄)² =\", round(sigma2_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  σ̂² = S² = (1/(n-1))Σ(x_i - x̄)² = 81.1515 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  σ̂ = S = √S² =\", round(sigma_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  σ̂ = S = √S² = 9.0084 \n```\n\n\n:::\n:::\n\n\n**Point estimates:**\n\n- $\\hat{\\mu} = \\bar{X} = \\boxed{100.33}$\n- $\\hat{\\sigma}^2 = S^2 = \\boxed{75.33}$\n- $\\hat{\\sigma} = S = \\boxed{8.68}$\n\n\n### Part (b)\n\n**Compute a point estimate for $p = P(X < 95)$ using the invariance property of MLEs.**\n\nIf $X \\sim N(\\mu, \\sigma^2)$, then the proportion of the population with IQ below 95 is:\n$$p = P(X < 95) = \\Phi\\left(\\frac{95 - \\mu}{\\sigma}\\right)$$\n\nwhere $\\Phi$ is the standard normal CDF.\n\nBy the **invariance property of MLEs**, if $\\hat{\\mu}$ and $\\hat{\\sigma}$ are the MLEs of $\\mu$ and $\\sigma$, then:\n$$\\hat{p} = \\Phi\\left(\\frac{95 - \\hat{\\mu}}{\\hat{\\sigma}}\\right)$$\n\n*Note: The MLE of $\\sigma^2$ is $\\frac{1}{n}\\sum(X_i - \\bar{X})^2$, which differs from $S^2$. However, for this problem we use $S$ as our estimate of $\\sigma$ as instructed in part (a).*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the z-score\nz_score <- (95 - mu_hat) / sigma_hat\n\n# Compute p-hat using the standard normal CDF\np_hat <- pnorm(z_score)\n\ncat(\"Using the normal model to estimate P(X < 95):\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUsing the normal model to estimate P(X < 95):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z = (95 - μ̂) / σ̂\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z = (95 - μ̂) / σ̂\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z = (95 -\", round(mu_hat, 2), \") /\", round(sigma_hat, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z = (95 - 100.33 ) / 9.01 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  z =\", round(z_score, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  z = -0.592 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p̂ = Φ(z) = pnorm(\", round(z_score, 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p̂ = Φ(z) = pnorm( -0.592 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p̂ =\", round(p_hat, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p̂ = 0.2769 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretation: We estimate that approximately\", round(p_hat * 100, 1), \n    \"% of patients in this\\npopulation have verbal IQ scores below 95.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: We estimate that approximately 27.7 % of patients in this\npopulation have verbal IQ scores below 95.\n```\n\n\n:::\n:::\n\n\nThe point estimate is $\\hat{p} = \\boxed{0.2692}$ (approximately 26.9%).\n\n\n### Part (c)\n\n**A colleague suggests using the sample proportion $\\tilde{p} = \\frac{\\#\\{X_i < 95\\}}{n}$.**\n\n**Compute $\\tilde{p}$ for the given data:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count observations below 95\nbelow_95 <- iq_scores[iq_scores < 95]\nn_below_95 <- length(below_95)\n\n# Sample proportion\np_tilde <- n_below_95 / n\n\ncat(\"Observations below 95:\", paste(below_95, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations below 95: 94, 87, 91, 89 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number below 95:\", n_below_95, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber below 95: 4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample proportion: p̃ =\", n_below_95, \"/\", n, \"=\", round(p_tilde, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample proportion: p̃ = 4 / 12 = 0.3333 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Comparison of estimators:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComparison of estimators:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p̂ (model-based) =\", round(p_hat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p̂ (model-based) = 0.2769 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p̃ (sample proportion) =\", round(p_tilde, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p̃ (sample proportion) = 0.3333 \n```\n\n\n:::\n:::\n\n\n$\\tilde{p} = \\boxed{0.25}$ (or 3/12 = 1/4)\n\n**Is $\\tilde{p}$ unbiased for $p = P(X < 95)$?**\n\n**Yes, $\\tilde{p}$ is unbiased.** Here's why:\n\nLet $Y_i = I(X_i < 95)$ be an indicator variable that equals 1 if observation $i$ is below 95, and 0 otherwise. Then:\n$$\\tilde{p} = \\frac{1}{n}\\sum_{i=1}^n Y_i$$\n\nFor each $Y_i$:\n$$E(Y_i) = P(Y_i = 1) = P(X_i < 95) = p$$\n\nTherefore:\n$$E(\\tilde{p}) = E\\left(\\frac{1}{n}\\sum_{i=1}^n Y_i\\right) = \\frac{1}{n}\\sum_{i=1}^n E(Y_i) = \\frac{1}{n} \\cdot np = p$$\n\nSo $\\tilde{p}$ is unbiased for $p$ **regardless of the distribution** of $X$ (it does not require normality).\n\n\n**(Optional bonus) Which estimator makes better use of the normality assumption?**\n\n$\\hat{p}$ (the model-based estimator) makes **better use of the normality assumption** because:\n\n1. **It uses all the data** through $\\bar{X}$ and $S$, not just the count of observations below the threshold. Every observation contributes to the estimate, not just whether it's above or below 95.\n\n2. **It leverages the parametric structure** of the normal distribution. If the data truly are normally distributed, the model-based approach \"borrows information\" across the entire range of values to estimate the shape of the distribution.\n\n3. **With small samples**, it tends to be more efficient because it doesn't waste information by dichotomizing the continuous measurements.\n\nHowever, $\\tilde{p}$ is more **robust** if the normality assumption is violated. If the true distribution is not normal, the model-based estimator $\\hat{p}$ could be quite biased, while $\\tilde{p}$ remains unbiased regardless of the distribution.\n\n\n### Part (d)\n\n**Compute the estimated standard error of $\\bar{X}$: $\\widehat{SE}(\\bar{X}) = \\frac{S}{\\sqrt{n}}$**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimated standard error\nse_xbar <- sigma_hat / sqrt(n)\n\ncat(\"Estimated standard error of X̄:\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated standard error of X̄:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SE(X̄) = S / √n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SE(X̄) = S / √n\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SE(X̄) =\", round(sigma_hat, 2), \"/ √\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SE(X̄) = 9.01 / √ 12 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SE(X̄) =\", round(sigma_hat, 2), \"/\", round(sqrt(n), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SE(X̄) = 9.01 / 3.4641 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SE(X̄) =\", round(se_xbar, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SE(X̄) = 2.6 \n```\n\n\n:::\n:::\n\n\nThe estimated standard error is $\\widehat{SE}(\\bar{X}) = \\boxed{2.51}$ points.\n\n**Interpretation:** \n\nThe standard error tells us about the sampling variability of the sample mean. If a different researcher collected a new sample of $n = 12$ patients from the same population:\n\n- Their sample mean would typically differ from ours by roughly **one standard error** (about $\\pm 2.5$ points) due to random sampling variability\n- About 68% of sample means would fall within $\\pm 2.5$ points of the true population mean\n- About 95% of sample means would fall within $\\pm 5$ points (roughly two standard errors) of the true population mean\n\nSo we would expect another researcher's sample mean to differ from ours by approximately **2-5 points** in either direction, just due to chance.\n",
    "supporting": [
      "HW_03_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}