---
title: "Homework 4"
subtitle: "BSTA 550"
description: "Due: `r library(here); source(here('class_dates.R')); hw4 %>% format('%m/%d')` at 11pm"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)

library(here)
source(here("class_dates.R"))
```

## Directions

**Please turn in this homework on Sakai.** Please submit your homework in pdf or html format. 

You can type your work on your computer or submit a photo of your written work or any other method that can be turned into a pdf. The Adobe Scan phone app is an easy way to scan photos and compile into a PDF. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

*You must show all of your work to receive credit.*

## Questions

1. **Mystery constant.** Suppose $X$ is a discrete random variable with a probability mass function $p_X(x) = c(4- x)$ for $x$ in $\{-1, 2, 3\}$ and $p_X(x) = 0$ otherwise.

    a. What is the value of c so that $p_X(x)$ is a mass?
    b. Make a plot of the probability mass function and write the piecewise pmf
    c. What is the CDF of $X$? Write the piecewise CDF.
    d. Make a plot of the CDF.

2. **Wastebasket basketball.** Chris tries to throw a ball of paper in the wastebasket behind his back (without looking). He estimates that his chance of success each time, regardless of the outcome of the other attempts, is $1/3$. Let $X$ be the number of attempts required. If he is not successful within the first 5 attempts, then he quits, and he lets $X = 6$ in such a case.

    a. Draw the mass of $X$ and define the piecewise pmf.
    b. Draw the CDF of $X$ and define the piecewise CDF.
    c. Simulate 10,000 trials of this experiment in R and plot the approximate probability distribution.
  
  
3. Suppose a density $f_X(x)$ increases linearly from $(16, 0)$ to
$\left(24, \dfrac{1}{4}\right)$.

    a. Find the CDF of $X$.
    b. What is the value of $a$ so that $P(X > a) = 0.75$?

4. For the following pdf $$f_X(x) = \begin{cases} kx^9(1-x)^2 & \text{if } 0 \leq x \leq 1 \\ 0 & \text{otherwise} \end{cases}$$
    
    a. What is the constant $k$ that makes the following function a valid density?
    b. What is the cumulative distribution function (cdf) $F_X(x)$?

