---
title: "Homework 2"
subtitle: "BSTA 550"
description: "Due: `r library(here); source(here('class_dates.R')); hw2 %>% format('%m/%d')` at 11pm"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)

library(here)
source(here("class_dates.R"))
```

## Directions

Please turn in this homework on Sakai. 

Please submit your homework in pdf format. You can type your work on your computer or submit a photo of your written work or any other method that can be turned into a pdf. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

*You must show all of your work to receive credit.*

Extra problems do not need to be turned in!!

## Questions

1.  Suppose the following are the percentage of US adults with the following conditions:

    -   $A$: Hypertension 33%

    -   $B$: Diabetes 9%

    -   $C$: Metabolic syndrome 24%

    -   $A$ or $B$: 39%

    -   $A$ or $C$: 45%

    -   $B$ or $C$: 28%

    -   $A$ or $B$ or $C$: 48%

    a.  Make a Venn diagram of the 3 conditions labeling the percentage (or probability) for *ALL* of the 8 "sections". *Hint: Start from the last condition and work your way up!*
    b.  For each of the following (1. - 7. below), ($i$) write out the event using unions, intersections, and/or complements of the events $A$, $B$, and $C$ (this is NOT finding the probability, that's in $ii$); ($ii$) find the probability of the event; and ($iii$) write a sentence explaining what the probability is of in terms of the context of the problem.
        1.  $\mathbb{P}$(event at least one of the 3)

        2.  $\mathbb{P}$(event none)

        3.  $\mathbb{P}$(event $A$ only)

        4.  $\mathbb{P}$(event exactly one)

        5.  $\mathbb{P}$(event $A$ and $B$)

        6.  $\mathbb{P}$(event $A$ and $B$ but not $C$)

        7.  $\mathbb{P}$(event all 3)

2.  **Guessing on an exam.** While taking a probability exam, you come to three questions that you have no clue how to answer. You would have known the answers if you had taken the time to study the night before instead of going to a party, but you did not make a good life choice, and you vow to never party on a school night again if you fail this exam. Each question on the exam is multiple choice with the correct answer being either a, b, c, d, or e. (Your guesses are independent.) What is the probability that:

    a.  you randomly guess the right answer to all three questions?

    b.  you randomly guess the right answer to none of the three questions?

    c.  you randomly guess the right answer to exactly one of the three questions?

    d.  you randomly guess the right answer to exactly two of the three questions?

    e.  Do the probabilities in parts a–d sum to 1?

3.  Recall from class, that we defined events $A,B,$ and $C$ to mutually independent if both (1) and (2) below hold. This point of this exercise is to show that $(1)\nRightarrow (2),$ and $(2)\nRightarrow (1).$ $$\begin{array}{cc}
        (1) & \mathbb{P}(A\cap B\cap C)=\mathbb{P}(A)\mathbb{P(}B)\mathbb{P(}C) \\ 
        (2) & \mathbb{P}(A\cap B)=\mathbb{P}(A)\mathbb{P(}B) \\ 
        & \mathbb{P}(A\cap C)=\mathbb{P}(A)\mathbb{P(}C) \\ 
        & \mathbb{P}(B\cap C)=\mathbb{P}(B)\mathbb{P(}C)%
        \end{array}%$$

    a.  Suppose two different fair dice are rolled. Let events $A,B,$ and $C$ be defined in the following way: $$\begin{array}{cl}
        A: & \text{Roll a total of 7} \\ 
        B: & \text{First die is a 6} \\ 
        C: & \text{Second die is a 2}%
        \end{array}%$$

        Show that condition $(2)$ holds, but that condition $(1)$ does not.

    b.  Suppose two different fair dice are rolled. Let events $A,B,$ and $C$ be defined in the following way: $$\begin{array}{cl}
        A: & \text{Roll a 1 or 2 on the first die} \\ 
        B: & \text{Roll a 3, 4, or 5 on the second die} \\ 
        C: & \text{Roll a total of 4, 11, or 12}%
        \end{array}%$$

        Show that condition $(1)$ holds, but that condition $(2)$ does not.

4.  **Parity of spinning.** A spinner has the left side (numbers 1, 2, 3, 4, and 5) colored red and the right side colored white (numbers 6, 7, 8, and 9), with all numbers equally likely.

    a.  What is the probability the spinner lands on an odd number?

    b.  Given that the spinner landed on an odd number, what is the chance the spinner landed on a white number?

    c.  Given that the spinner landed on a white number, what is the chance it landed on an odd number?

5.  **Weather.** The weather on any given day can either be sunny, cloudy, or partially cloudy. Each day is also classified as dry or rainy. The probability of a sunny day is 0.48, and the probability of a cloudy day is 0.39. The probability of having a sunny and dry day is 0.48. The probability of a cloudy and dry day is 0.14. The probability of a partially cloudy and dry day is 0.09.

    a.  Find the probability of a dry day.

    b.  Find the probability of a rainy day.

    c.  Find the probability of a sunny day given that it is a dry day.

    d.  Find the probability of a dry day given that it is a sunny day.

    e.  Find the probability of a cloudy day given that it is a rainy day.

    f.  Find the probability that it is a rainy day given that it is a cloudy day

### Extra problems

1.  Judith has a penny, nickel, dime, and quarter in her pocket. So does Joe. They both reach into their pockets and choose a coin (all four coins are equally likely to be selected). Let X be the larger value (in cents) of the coins selected by Judith and Joe. For reference, the penny is 1 cent, nickel is 5 cents, dime is 10 cents, and quarter is 25 cents.

    a.  How many possible combinations is there for the pair of Judith's and Joe's selected coins? (Hint: we know to whom each coin belongs) 

    b.  Define the sample space for X in this experiment. 

    c.  Find the probability for each possible value of X. 

    d.  Find the probability of the event that Judith's coin is worth more than Joe's. 
