{
  "hash": "6a021808488a8efb01ebc89a09751792",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 18: Two-Sample Confidence Intervals and Tests for Means\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-03-02\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 18 - Two-Sample Inference for Means\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 18: Two-Sample Inference for Means {background-color=\"#2c3e50\"}\n\n## Review: Where We Left Off\n\n**Lessons 15–17: Hypothesis Testing**\n\n- Neyman-Pearson Lemma: MP tests via likelihood ratio\n- Likelihood Ratio Tests (LRT) for composite hypotheses\n- Bootstrap hypothesis tests: shift data to satisfy $H_0$, approximate null distribution\n- Permutation tests (preview)\n\n. . .\n\n**Today's Goals:**\n\n1. Extend one-sample inference to **two independent samples**\n2. Derive and apply the two-sample **z-test and CI** (variances known)\n3. Derive and apply the **Welch t-test** (variances unknown, unequal)\n4. Understand the **pooled t-test** (variances assumed equal) and when it is appropriate\n5. Connect CIs and tests via the duality theorem\n6. Apply all methods to medical research examples\n\n## Roadmap\n\n| Setting | Variances | Test Statistic | Reference |\n|---------|-----------|---------------|-----------|\n| Two independent samples | $\\sigma_1^2, \\sigma_2^2$ known | $Z$ | DBC 9.5 |\n| Two independent samples | $\\sigma_1^2 = \\sigma_2^2$ unknown | Pooled $T$ | DBC 9.5 |\n| Two independent samples | $\\sigma_1^2 \\neq \\sigma_2^2$ unknown | Welch $T$ | DBC 9.5 |\n\n. . .\n\n::: callout-note\n## Motivating Example\nA clinical trial randomizes $n_1 = 45$ patients to a new antihypertensive drug and $n_2 = 43$ to placebo. After 12 weeks, we measure the reduction in systolic blood pressure (mmHg). **Does the drug produce a larger mean reduction than placebo?**\n\nWe need two-sample methods because the groups are **independent**.\n:::\n\n# Two-Sample Setup and Point Estimation {background-color=\"#3498db\"}\n\n## The Two-Sample Model\n\n**Setup:** Two independent random samples from possibly different populations:\n\n$$X_{11}, X_{12}, \\ldots, X_{1n_1} \\stackrel{iid}{\\sim} F_1 \\quad \\text{with mean } \\mu_1, \\text{ variance } \\sigma_1^2$$\n\n$$X_{21}, X_{22}, \\ldots, X_{2n_2} \\stackrel{iid}{\\sim} F_2 \\quad \\text{with mean } \\mu_2, \\text{ variance } \\sigma_2^2$$\n\nThe two samples are **independent of each other**.\n\n. . .\n\n**Parameter of interest:** $\\Delta = \\mu_1 - \\mu_2$\n\n**Point estimator:** $\\hat{\\Delta} = \\bar{X}_1 - \\bar{X}_2$\n\n. . .\n\n**Properties of $\\hat{\\Delta}$:**\n\n- $E[\\bar{X}_1 - \\bar{X}_2] = \\mu_1 - \\mu_2$ $\\Rightarrow$ **unbiased**\n- $\\text{Var}(\\bar{X}_1 - \\bar{X}_2) = \\dfrac{\\sigma_1^2}{n_1} + \\dfrac{\\sigma_2^2}{n_2}$ (by independence)\n- SE$(\\bar{X}_1 - \\bar{X}_2) = \\sqrt{\\dfrac{\\sigma_1^2}{n_1} + \\dfrac{\\sigma_2^2}{n_2}}$\n\n## Sampling Distribution of $\\bar{X}_1 - \\bar{X}_2$\n\n**Case 1: Both populations normal** (any sample size):\n$$\\bar{X}_1 - \\bar{X}_2 \\sim N\\!\\left(\\mu_1 - \\mu_2,\\; \\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}\\right)$$\n\n**Case 2: Non-normal populations, large samples** (CLT):\n$$\\bar{X}_1 - \\bar{X}_2 \\;\\dot{\\sim}\\; N\\!\\left(\\mu_1 - \\mu_2,\\; \\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}\\right)$$\n\n. . .\n\nIn either case, the standardized statistic is approximately $N(0,1)$:\n\n$$Z = \\frac{(\\bar{X}_1 - \\bar{X}_2) - (\\mu_1 - \\mu_2)}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}} \\;\\sim\\; N(0,1)$$\n\nThis is a **pivotal quantity** when $\\sigma_1^2$ and $\\sigma_2^2$ are known.\n\n# Case 1: Variances Known (z-procedures) {background-color=\"#e74c3c\"}\n\n## Two-Sample z-Interval (DBC 9.5)\n\nWhen $\\sigma_1^2$ and $\\sigma_2^2$ are **known**, the pivot $Z$ gives a $100(1-\\alpha)\\%$ CI for $\\mu_1 - \\mu_2$:\n\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm z_{\\alpha/2} \\sqrt{\\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}}$$\n\n. . .\n\n**Two-sample z-test** of $H_0: \\mu_1 - \\mu_2 = \\Delta_0$:\n\n$$Z = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}}$$\n\nReject $H_0$ at level $\\alpha$:\n\n| Alternative | Rejection Region |\n|-------------|-----------------|\n| $\\mu_1 - \\mu_2 > \\Delta_0$ | $Z > z_\\alpha$ |\n| $\\mu_1 - \\mu_2 < \\Delta_0$ | $Z < -z_\\alpha$ |\n| $\\mu_1 - \\mu_2 \\neq \\Delta_0$ | $|Z| > z_{\\alpha/2}$ |\n\n## Medical Example: Two-Sample z-Test\n\n**Study:** A pilot study compares mean serum cortisol (μg/dL) between ICU patients with sepsis ($n_1 = 30$, known $\\sigma_1 = 6$) and non-septic ICU controls ($n_2 = 35$, known $\\sigma_2 = 5$). Observed: $\\bar{x}_1 = 28.4$, $\\bar{x}_2 = 22.1$. Test $H_0: \\mu_1 = \\mu_2$ vs. $H_a: \\mu_1 > \\mu_2$ at $\\alpha = 0.05$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Summary statistics\nxbar1 <- 28.4; xbar2 <- 22.1\nsigma1 <- 6;   sigma2 <- 5\nn1 <- 30;      n2 <- 35\nalpha <- 0.05\n\n# Test statistic and p-value (one-sided)\nse_diff <- sqrt(sigma1^2/n1 + sigma2^2/n2)\nz_obs   <- (xbar1 - xbar2) / se_diff\np_value <- pnorm(z_obs, lower.tail = FALSE)\n\n# 95% CI (two-sided)\nz_crit <- qnorm(1 - alpha/2)\nci_lo  <- (xbar1 - xbar2) - z_crit * se_diff\nci_hi  <- (xbar1 - xbar2) + z_crit * se_diff\n\ncat(\"SE of difference:\", round(se_diff, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE of difference: 1.384 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"Z statistic:\", round(z_obs, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZ statistic: 4.553 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"One-sided p-value:\", round(p_value, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOne-sided p-value: 0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"95% CI for mu1 - mu2: (\", round(ci_lo, 2), \",\", round(ci_hi, 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mu1 - mu2: ( 3.59 , 9.01 )\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Conclusion:** $Z = 4.55$, $p < 0.001$. Strong evidence that septic ICU patients have higher mean cortisol.\n\n# Case 2: Variances Unknown {background-color=\"#27ae60\"}\n\n## The Challenge: Unknown Variances\n\nIn practice, $\\sigma_1^2$ and $\\sigma_2^2$ are **rarely known**. We estimate them from the data:\n\n$$S_1^2 = \\frac{1}{n_1-1}\\sum_{j=1}^{n_1}(X_{1j}-\\bar{X}_1)^2, \\quad S_2^2 = \\frac{1}{n_2-1}\\sum_{j=1}^{n_2}(X_{2j}-\\bar{X}_2)^2$$\n\nThe standardized statistic\n$$T = \\frac{(\\bar{X}_1 - \\bar{X}_2) - (\\mu_1-\\mu_2)}{\\sqrt{S_1^2/n_1 + S_2^2/n_2}}$$\n\ndoes **not** follow an exact $t$ distribution (Behrens-Fisher problem).\n\n. . .\n\n**Two approaches:**\n\n1. **Welch (Satterthwaite) approximation**: $T$ is approximately $t_\\nu$ with estimated df $\\hat\\nu$\n2. **Pooled t-test**: assume $\\sigma_1^2 = \\sigma_2^2$, use exact $t_{n_1+n_2-2}$ distribution\n\n## Welch's t-Test (DBC 9.5) — Recommended Default\n\n**Welch's t-statistic:**\n$$T_W = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{\\sqrt{S_1^2/n_1 + S_2^2/n_2}}$$\n\nUnder $H_0$, $T_W \\approx t_{\\hat\\nu}$ where the **Welch-Satterthwaite degrees of freedom** are:\n\n$$\\hat\\nu = \\frac{(S_1^2/n_1 + S_2^2/n_2)^2}{\\dfrac{(S_1^2/n_1)^2}{n_1-1} + \\dfrac{(S_2^2/n_2)^2}{n_2-1}}$$\n\n. . .\n\n**Welch 95% CI for $\\mu_1 - \\mu_2$:**\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm t_{\\alpha/2,\\,\\hat\\nu}\\,\\sqrt{\\frac{S_1^2}{n_1} + \\frac{S_2^2}{n_2}}$$\n\n::: callout-important\n## Why Welch?\nThe Welch test is **robust** to unequal variances and performs well even when $\\sigma_1^2 = \\sigma_2^2$. It is the default in R's `t.test()` and is recommended by most statisticians.\n:::\n\n## The Pooled t-Test (DBC 9.5)\n\nWhen $\\sigma_1^2 = \\sigma_2^2 = \\sigma^2$ (equal variances), we pool information:\n\n$$S_p^2 = \\frac{(n_1-1)S_1^2 + (n_2-1)S_2^2}{n_1 + n_2 - 2} \\quad \\text{(pooled variance estimator)}$$\n\n**Pooled t-statistic:**\n$$T_P = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{S_p\\sqrt{1/n_1 + 1/n_2}} \\sim t_{n_1+n_2-2} \\quad \\text{(exact, under normality + equal } \\sigma^2\\text{)}$$\n\n. . .\n\n**Pooled 95% CI:**\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm t_{\\alpha/2,\\,n_1+n_2-2}\\;S_p\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}$$\n\n::: callout-warning\n## When to Use Pooled t\nOnly use the pooled t when there is **strong prior reason** to believe $\\sigma_1^2 = \\sigma_2^2$ (e.g., same measurement in similar populations). Do not use an F-test on the same data to justify pooling — this inflates Type I error.\n:::\n\n## Welch vs. Pooled: Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\n# Simulate 10,000 two-sample experiments under H0\n# Compare Type I error when sigma1 != sigma2\nsim_ttest <- function(n1, n2, sigma1, sigma2, B = 10000) {\n  map_dfr(1:B, function(i) {\n    x1 <- rnorm(n1, mean = 0, sd = sigma1)\n    x2 <- rnorm(n2, mean = 0, sd = sigma2)\n    p_welch  <- t.test(x1, x2, var.equal = FALSE)$p.value\n    p_pooled <- t.test(x1, x2, var.equal = TRUE)$p.value\n    tibble(p_welch = p_welch, p_pooled = p_pooled)\n  })\n}\n\nscenarios <- list(\n  list(n1=20, n2=20, s1=2, s2=2, label=\"Equal n, Equal σ\"),\n  list(n1=20, n2=20, s1=1, s2=3, label=\"Equal n, σ1=1, σ2=3\"),\n  list(n1=10, n2=30, s1=1, s2=3, label=\"Small n₁, σ1=1, σ2=3 (n∝σ²)\"),\n  list(n1=30, n2=10, s1=1, s2=3, label=\"Large n₁, σ1=1, σ2=3 (n anti-∝σ²)\")\n)\n\nresults <- map_dfr(scenarios, function(sc) {\n  sim_ttest(sc$n1, sc$n2, sc$s1, sc$s2, B = 3000) |>\n    summarise(Welch = mean(p_welch < 0.05),\n              Pooled = mean(p_pooled < 0.05)) |>\n    mutate(Scenario = sc$label)\n})\n\nresults |>\n  pivot_longer(c(Welch, Pooled), names_to = \"Test\", values_to = \"TypeI_Error\") |>\n  ggplot(aes(x = reorder(Scenario, -TypeI_Error), y = TypeI_Error, fill = Test)) +\n  geom_col(position = \"dodge\", width = 0.6) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", color = \"black\", linewidth = 1) +\n  scale_fill_manual(values = c(\"Welch\" = \"#006a4e\", \"Pooled\" = \"#e74c3c\")) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.14),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(\n    title = \"Type I Error Rate: Welch vs. Pooled t-test  (nominal α = 5%)\",\n    subtitle = \"Dashed line = 5% target. Pooled test is anti-conservative when variances are unequal.\",\n    x = NULL, y = \"Type I Error Rate\", fill = \"Method\"\n  ) +\n  coord_flip() +\n  theme(legend.position = \"bottom\", axis.text.y = element_text(size = 13))\n```\n\n::: {.cell-output-display}\n![](18_TwoSample_Mean_files/figure-revealjs/unnamed-chunk-2-1.png){width=1344}\n:::\n:::\n\n\n## Medical Example: Welch t-Test in R\n\n**RCT:** A randomized trial compares 12-week reduction in LDL cholesterol (mg/dL) between a statin drug ($n_1 = 45$) and placebo ($n_2 = 43$).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(42)\n# Simulate individual-level data\nldl_drug    <- rnorm(45, mean = 32, sd = 18)   # larger mean reduction\nldl_placebo <- rnorm(43, mean = 8,  sd = 12)   # smaller reduction\n\n# Welch t-test (default in R)\ntest_result <- t.test(ldl_drug, ldl_placebo, \n                      alternative = \"greater\",\n                      conf.level  = 0.95)\ntidy(test_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic    p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>      <dbl>     <dbl>    <dbl>     <dbl>\n1     21.3      30.8      9.52      5.97    5.39e-8      65.6     15.3       Inf\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(\n  reduction = c(ldl_drug, ldl_placebo),\n  group     = rep(c(\"Statin\", \"Placebo\"), c(45, 43))\n) |>\n  ggplot(aes(x = group, y = reduction, fill = group)) +\n  geom_boxplot(alpha = 0.7, width = 0.4) +\n  geom_jitter(width = 0.1, alpha = 0.4, size = 1.5) +\n  scale_fill_manual(values = c(\"Statin\" = \"#006a4e\", \"Placebo\" = \"#3498db\")) +\n  labs(title = \"LDL Cholesterol Reduction by Treatment Group\",\n       subtitle = \"Welch two-sample t-test\",\n       x = NULL, y = \"LDL Reduction (mg/dL)\", fill = NULL) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](18_TwoSample_Mean_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Interpreting the Welch Output\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Two-sided CI for the difference (mu_drug - mu_placebo)\nci_result <- t.test(ldl_drug, ldl_placebo, \n                    alternative = \"two.sided\",\n                    conf.level  = 0.95)\ncat(\"Welch df:\", round(ci_result$parameter, 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWelch df: 65.6 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"Mean difference:\", round(diff(rev(ci_result$estimate)), 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean difference: 21.25 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"95% CI: (\", round(ci_result$conf.int[1], 2), \",\",\n                  round(ci_result$conf.int[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 14.14 , 28.37 )\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"p-value:\", format.pval(ci_result$p.value, digits = 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 1.08e-07 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** We estimate the statin reduces LDL by approximately 21.3 mg/dL more than placebo on average (95% CI: 14.1 to 28.4 mg/dL). This is highly statistically significant ($p < 0.001$, Welch t-test).\n\n::: callout-note\n## Report Both\nAlways report both the **CI** (magnitude of effect) and the **p-value** (strength of evidence). Neither alone tells the full story.\n:::\n\n## Example: Pooled t-Test When Appropriate\n\n**Devore Example (DBC 9.5):** Two independent groups of adult male patients measured for systolic blood pressure:\n- Group 1 (standard care): $n_1 = 12$, $\\bar{x}_1 = 140.2$, $s_1 = 14.3$ mmHg\n- Group 2 (intensive care): $n_2 = 10$, $\\bar{x}_2 = 128.7$, $s_2 = 13.8$ mmHg\n\nStrong prior reason to assume equal population SDs (same measurement, similar populations). Test $H_0: \\mu_1 = \\mu_2$ vs. $H_a: \\mu_1 \\neq \\mu_2$ at $\\alpha = 0.05$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nn1 <- 12; xbar1 <- 140.2; s1 <- 14.3\nn2 <- 10; xbar2 <- 128.7; s2 <- 13.8\n\n# Pooled variance\nsp2 <- ((n1-1)*s1^2 + (n2-1)*s2^2) / (n1 + n2 - 2)\nsp  <- sqrt(sp2)\n\n# Test statistic\nt_obs <- (xbar1 - xbar2) / (sp * sqrt(1/n1 + 1/n2))\ndf    <- n1 + n2 - 2\n\n# Two-sided p-value and 95% CI\np_val <- 2 * pt(abs(t_obs), df = df, lower.tail = FALSE)\nt_crit <- qt(0.975, df = df)\nmargin <- t_crit * sp * sqrt(1/n1 + 1/n2)\n\ncat(sprintf(\"Pooled SD = %.2f,  df = %d\\n\", sp, df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPooled SD = 14.08,  df = 20\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"T_obs = %.3f,  p-value = %.4f\\n\", t_obs, p_val))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT_obs = 1.908,  p-value = 0.0709\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"95%% CI: (%.2f, %.2f)\\n\", xbar1 - xbar2 - margin,\n                                        xbar1 - xbar2 + margin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: (-1.07, 24.07)\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Conclusion:** $t = 1.908$, $df = 20$, $p = 0.0709$. At $\\alpha = 0.05$, we reject $H_0$; evidence that systolic BP differs between care groups.\n\n## Visualizing t-Distributions: Welch vs. Pooled\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# From the LDL example above\nn1_ldl <- 45; n2_ldl <- 43\ns1_ldl <- sd(ldl_drug); s2_ldl <- sd(ldl_placebo)\n\n# Welch df\nnu_hat <- (s1_ldl^2/n1_ldl + s2_ldl^2/n2_ldl)^2 /\n          ((s1_ldl^2/n1_ldl)^2/(n1_ldl-1) + (s2_ldl^2/n2_ldl)^2/(n2_ldl-1))\ndf_pooled_ldl <- n1_ldl + n2_ldl - 2\n\nt_obs_ldl <- (mean(ldl_drug) - mean(ldl_placebo)) /\n             sqrt(s1_ldl^2/n1_ldl + s2_ldl^2/n2_ldl)\n\nt_grid <- seq(-6, 6, length.out = 500)\ndf_plot <- bind_rows(\n  tibble(t = t_grid, \n         density = dt(t_grid, df = round(nu_hat)),\n         Distribution = sprintf(\"Welch (df=%.0f)\", nu_hat)),\n  tibble(t = t_grid,\n         density = dt(t_grid, df = df_pooled_ldl),\n         Distribution = sprintf(\"Pooled (df=%d)\", df_pooled_ldl))\n)\n\nggplot(df_plot, aes(x = t, y = density, color = Distribution)) +\n  geom_line(linewidth = 1.4) +\n  geom_vline(xintercept = t_obs_ldl, linetype = \"dashed\", color = \"#e74c3c\",\n             linewidth = 1.2) +\n  annotate(\"text\", x = t_obs_ldl + 0.3, y = 0.35,\n           label = bquote(T[obs] == .(round(t_obs_ldl, 2))),\n           color = \"#e74c3c\", size = 5, hjust = 0) +\n  scale_color_manual(values = c(\"#006a4e\", \"#3498db\")) +\n  labs(title = \"LDL Example: Welch vs. Pooled t-Distributions\",\n       subtitle = \"With similar sample sizes and variances, the two distributions are nearly identical\",\n       x = \"t\", y = \"Density\", color = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](18_TwoSample_Mean_files/figure-revealjs/unnamed-chunk-7-1.png){width=1344}\n:::\n:::\n\n\n# Sample Size and Power {background-color=\"#9b59b6\"}\n\n## Sample Size for Two-Sample t-Test\n\nFor a two-sided test at level $\\alpha$ with power $1 - \\beta$ to detect $|\\mu_1 - \\mu_2| = \\delta$ (assuming $\\sigma_1 = \\sigma_2 = \\sigma$ and $n_1 = n_2 = n$):\n\n$$n \\approx \\frac{2\\sigma^2(z_{\\alpha/2} + z_\\beta)^2}{\\delta^2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Clinical question: How many patients per arm to detect a 10 mmHg difference\n# in SBP with 90% power at alpha = 0.05 (two-sided)?\nsigma <- 15   # assumed common SD (mmHg)\ndelta <- 10   # target difference to detect\nalpha <- 0.05\npower <- 0.90\n\nz_a2 <- qnorm(1 - alpha/2)\nz_b  <- qnorm(power)\n\nn_per_arm <- ceiling(2 * sigma^2 * (z_a2 + z_b)^2 / delta^2)\ncat(\"Approximate n per arm:\", n_per_arm, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nApproximate n per arm: 48 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# Cross-check with power.t.test\npower.t.test(delta = delta, sd = sigma, sig.level = alpha, \n             power = power, type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 48.26431\n          delta = 10\n             sd = 15\n      sig.level = 0.05\n          power = 0.9\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n## Summary: Which Two-Sample t-Test?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-5ddf05d5255e0553fb0e\" style=\"width:1152px;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5ddf05d5255e0553fb0e\">{\"x\":{\"diagram\":\"\\ndigraph decision {\\n  graph [rankdir=TB, fontname=Helvetica]\\n  node [shape=box, style=\\\"rounded,filled\\\", fontsize=14]\\n\\n  A [label=\\\"Two independent\\\\nsamples\\\", fillcolor=\\\"#3498db\\\", fontcolor=white]\\n  B [label=\\\"Normal populations\\\\nor n large?\\\", shape=diamond, fillcolor=\\\"#f39c12\\\", fontcolor=white]\\n  C [label=\\\"σ₁² = σ₂²\\\\nassumed known?\\\", shape=diamond, fillcolor=\\\"#f39c12\\\", fontcolor=white]\\n  D [label=\\\"z-test & z-interval\\\", fillcolor=\\\"#006a4e\\\", fontcolor=white]\\n  E [label=\\\"Strong prior evidence\\\\nσ₁² = σ₂²?\\\", shape=diamond, fillcolor=\\\"#f39c12\\\", fontcolor=white]\\n  F [label=\\\"Pooled t-test\\\\n(df = n₁+n₂−2)\\\", fillcolor=\\\"#006a4e\\\", fontcolor=white]\\n  G [label=\\\"Welch t-test\\\\n(Satterthwaite df)\\\", fillcolor=\\\"#006a4e\\\", fontcolor=white]\\n  N [label=\\\"Bootstrap or\\\\nnon-parametric\\\\nmethods\\\", fillcolor=\\\"#9b59b6\\\", fontcolor=white]\\n\\n  A -> B\\n  B -> C [label=\\\"Yes\\\"]\\n  B -> N [label=\\\"No (small n)\\\"]\\n  C -> D [label=\\\"Yes\\\"]\\n  C -> E [label=\\\"No\\\"]\\n  E -> F [label=\\\"Yes\\\"]\\n  E -> G [label=\\\"No (default)\\\"]\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n# Key Takeaways {background-color=\"#2c3e50\"}\n\n## Key Takeaways\n\n::: callout-important\n## Today's Main Points (DBC 9.5)\n\n1. **Point estimator:** $\\bar{X}_1 - \\bar{X}_2$ is unbiased for $\\mu_1 - \\mu_2$ with variance $\\sigma_1^2/n_1 + \\sigma_2^2/n_2$\n\n2. **z-procedures:** Use when $\\sigma_1^2, \\sigma_2^2$ known (or large samples approximation)\n\n3. **Welch t-test** (recommended default): approximates the sampling distribution of the standardized difference with $t_{\\hat\\nu}$; the Welch-Satterthwaite df $\\hat\\nu$ accounts for unequal variances\n\n4. **Pooled t-test:** Exact $t_{n_1+n_2-2}$ distribution under normality + $\\sigma_1^2 = \\sigma_2^2$; requires strong prior justification for equal variances\n\n5. **CI-test duality:** The 95% CI for $\\Delta = \\mu_1 - \\mu_2$ contains all values of $\\Delta_0$ for which the two-sided test would fail to reject at $\\alpha = 0.05$\n\n6. **Always report** the estimated difference, its CI, and the p-value together\n:::\n\n## Looking Ahead\n\n**Next class: Two-Sample Inference for Proportions; Inferences About Two Variances**\n\n- $z$-test and CI for $p_1 - p_2$: comparing event rates between groups\n- F-test for equality of variances\n- Inferences about $\\sigma_1^2/\\sigma_2^2$\n\n. . .\n\n**Later: Paired Data (Lesson 20) and Bootstrap/Permutation for Two Samples (Lesson 21)**\n\n## Homework 7 {.smaller}\n\n**Due:** March 5, 2026 at 11pm\n\n**Problem 1** (DBC 9.5 style): Two hospital units are compared on patient length of stay (days). Unit A ($n_1 = 20$, $\\bar{x}_1 = 7.4$, $s_1 = 2.8$) vs. Unit B ($n_2 = 25$, $\\bar{x}_2 = 6.1$, $s_2 = 3.5$).\n(a) Compute the Welch t-statistic and approximate df.\n(b) Construct a 95% Welch CI for $\\mu_1 - \\mu_2$.\n(c) Test $H_0: \\mu_1 = \\mu_2$ vs. $H_a: \\mu_1 > \\mu_2$ at $\\alpha = 0.05$. State your conclusion.\n(d) Verify your answers using `t.test()` in R.\n\n**Problem 2** (DBC 9.5, pooled): Two formulations of an analgesic are tested for time to pain relief (minutes). Assume equal population SDs. Formulation A: $n_1 = 15$, $\\bar{x}_1 = 48.3$, $s_1 = 8.1$. Formulation B: $n_2 = 15$, $\\bar{x}_2 = 52.6$, $s_2 = 7.9$.\n(a) Compute $S_p^2$ and the pooled t-statistic.\n(b) Construct a 90% pooled CI for $\\mu_A - \\mu_B$.\n(c) What sample size per group would be needed to detect a 5-minute difference with 80% power at $\\alpha = 0.05$?\n\n**Problem 3** (DBC 9.5): Using the cortisol example from class (sepsis vs. non-septic ICU patients), suppose $\\sigma_1$ and $\\sigma_2$ are actually unknown. Re-analyze using:\n(a) Welch t-test. (b) Pooled t-test. (c) Compare results and discuss when conclusions might differ.\n\n## References\n\n::: nonincremental\n- Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Section 9.5.\n- Welch, B. L. (1947). The generalization of 'Student's' problem when several different population variances are involved. *Biometrika*, 34(1–2), 28–35.\n:::\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n",
    "supporting": [
      "18_TwoSample_Mean_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}