{
  "hash": "4679845d9266f37212013e94013379a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 15: Neyman-Pearson Lemma; Likelihood Ratio Tests\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-02-18\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 15 - Neyman-Pearson Lemma; Likelihood Ratio Tests\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 15: Neyman-Pearson Lemma; Likelihood Ratio Tests {background-color=\"#2c3e50\"}\n\n## Review: Where We Left Off\n\n**Lesson 14: P-Values; Power and Sample Size Determination**\n\n-   P-values are Uniform(0,1) under $H_0$ by the probability integral transformation\n-   Power depends on the noncentrality parameter $\\delta = (\\mu' - \\mu_0)/(\\sigma/\\sqrt{n})$\n-   Sample size determination via `power.t.test()` for planning clinical trials\n-   Multiple testing adjustments: Bonferroni (FWER) and Benjamini-Hochberg (FDR)\n\n. . .\n\n**Today's Goals:**\n\n1. Understand the concept of a **most powerful** test for simple hypotheses\n2. State and prove the **Neyman-Pearson Lemma** \n3. Define **power functions** and **uniformly most powerful (UMP)** tests\n4. Develop the **likelihood ratio test (LRT)** for composite hypotheses\n5. Connect the LRT to familiar tests (z test, t test)\n6. Apply the large-sample chi-squared approximation for LRTs\n\n## Roadmap for Today\n\n| Topic | Key Idea | Textbook |\n|-------|----------|----------|\n| Simple hypotheses | Both $H_0$ and $H_a$ fully specify the distribution | Devore 9.5 |\n| Neyman-Pearson Lemma | The likelihood ratio test is most powerful for simple $H_0$ vs simple $H_a$ | Devore 9.5 |\n| Power function | $\\pi(\\theta') = P_{\\theta'}(\\text{Reject } H_0)$ as a function of $\\theta$ | Devore 9.5 |\n| UMP tests | Most powerful for every value in the alternative | Devore 9.5 |\n| Likelihood ratio tests | General principle for composite hypotheses | Devore 9.5 |\n| LRT $\\to$ t test | The one-sample t test is a LRT | Devore 9.5 |\n| Large-sample LRT | $-2\\ln(\\Lambda) \\xrightarrow{d} \\chi^2_m$ | Devore 9.5 |\n\n. . .\n\n::: callout-note\n## Why This Matters\nThe Neyman-Pearson Lemma provides the **theoretical foundation** for optimal hypothesis testing. It tells us *why* the tests we have been using (z tests, t tests) are the best possible tests in their respective settings. The likelihood ratio principle then gives us a **general recipe** for constructing tests in new situations.\n:::\n\n# Simple Hypotheses and Optimal Tests (Devore 9.5) {background-color=\"#3498db\"}\n\n## Simple vs. Composite Hypotheses\n\nRecall from Lesson 12:\n\n::: callout-important\n## Definition (Simple and Composite Hypotheses)\nA hypothesis is **simple** if it completely specifies the distribution of the sample $X_1, \\ldots, X_n$. Otherwise, it is **composite**.\n:::\n\n. . .\n\n**Examples:**\n\n- $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} \\text{Exp}(\\lambda)$:\n  - $H: \\lambda = 5$ is **simple** (distribution fully determined)\n  - $H: \\lambda < 5$ is **composite** (many possible distributions)\n\n. . .\n\n- $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ **known**:\n  - $H: \\mu = 100$ is **simple**\n  - $H: \\mu \\neq 100$ is **composite**\n\n. . .\n\n- $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ **unknown**:\n  - $H: \\mu = 100$ is **composite** (because $\\sigma$ is unspecified --- it is a *nuisance parameter*)\n\n## The Optimality Question\n\nWe have developed many test procedures: z tests, t tests, score tests, exact binomial tests...\n\n. . .\n\n**But are these the *best* tests?**\n\n. . .\n\nFor a test of $H_0: \\theta = \\theta_0$ vs $H_a: \\theta = \\theta_a$, both simple, there are infinitely many possible rejection regions $R$. Each one gives:\n\n- A **Type I error rate**: $\\alpha = P_{\\theta_0}((X_1, \\ldots, X_n) \\in R)$\n- A **Type II error rate**: $\\beta = P_{\\theta_a}((X_1, \\ldots, X_n) \\notin R)$\n\n. . .\n\n**Goal:** Among all tests with $\\alpha \\leq \\alpha^*$ (controlling Type I error), find the test that **minimizes $\\beta$** (equivalently, **maximizes power**).\n\n. . .\n\n::: callout-tip\n## Medical Research Motivation\nIn a clinical trial comparing a new drug to a standard, we want the test that gives us the **best chance of detecting a real treatment effect** (high power) while maintaining the required significance level. The Neyman-Pearson Lemma tells us exactly how to construct such a test.\n:::\n\n## The Likelihood Ratio as a Test Statistic\n\n**Intuition:** Given data $x_1, \\ldots, x_n$, which hypothesis makes the data more likely?\n\n. . .\n\nConsider the ratio:\n\n$$\\Lambda^* = \\frac{f(x_1, \\ldots, x_n; \\theta_a)}{f(x_1, \\ldots, x_n; \\theta_0)} = \\frac{L(\\theta_a)}{L(\\theta_0)}$$\n\n. . .\n\n- If $\\Lambda^* \\gg 1$: data much more consistent with $H_a$ $\\Rightarrow$ evidence against $H_0$\n- If $\\Lambda^* \\approx 1$: data equally consistent with both $\\Rightarrow$ no strong evidence\n- If $\\Lambda^* \\ll 1$: data more consistent with $H_0$ $\\Rightarrow$ no evidence against $H_0$\n\n. . .\n\n**Natural test:** Reject $H_0$ when $\\Lambda^* \\geq k$ for some constant $k > 0$.\n\n. . .\n\n::: callout-note\n## Convention Note\nDevore defines the NP ratio as $L(\\theta_a)/L(\\theta_0)$ (reject when large). Chihara defines it as $L(\\theta_0)/L(\\theta_a)$ (reject when small). Both formulations are equivalent --- just inverted. We will primarily follow Devore's convention in the statement of the lemma.\n:::\n\n# The Neyman-Pearson Lemma {background-color=\"#e74c3c\"}\n\n## Statement of the Neyman-Pearson Lemma\n\n::: callout-important\n## The Neyman-Pearson Lemma (Devore 9.5)\nFor testing a simple null hypothesis $H_0: \\theta = \\theta_0$ versus a simple alternative $H_a: \\theta = \\theta_a$, let $k$ be a fixed positive number and form the rejection region\n\n$$R^* = \\left\\{(x_1, \\ldots, x_n): \\frac{f(x_1, \\ldots, x_n; \\theta_a)}{f(x_1, \\ldots, x_n; \\theta_0)} \\geq k \\right\\}$$\n\nLet $\\alpha^* = P((X_1, \\ldots, X_n) \\in R^* \\text{ when } \\theta = \\theta_0)$ and let $\\beta^*$ denote the Type II error probability.\n\nThen for **any other** test procedure with Type I error probability $\\alpha \\leq \\alpha^*$, the Type II error probability must satisfy $\\beta \\geq \\beta^*$.\n:::\n\n. . .\n\n**In plain language:** The test based on the likelihood ratio\n\n- Has the **smallest** $\\beta$ (Type II error) among all tests with $\\alpha \\leq \\alpha^*$\n- Equivalently, has the **largest power** at $\\theta_a$ among all level-$\\alpha^*$ tests\n- Is called the **most powerful (MP)** test at level $\\alpha^*$\n\n## Proof of the Neyman-Pearson Lemma\n\nLet $R$ be the rejection region of **any** test, so that:\n\n$$\\alpha = \\sum_R f(x_1, \\ldots, x_n; \\theta_0), \\quad \\beta = 1 - \\sum_R f(x_1, \\ldots, x_n; \\theta_a)$$\n\n. . .\n\nFor any constant $k > 0$, consider the linear combination $k\\alpha + \\beta$:\n\n$$k\\alpha + \\beta = k \\sum_R f(\\mathbf{x}; \\theta_0) + 1 - \\sum_R f(\\mathbf{x}; \\theta_a) = 1 + \\sum_R \\left[k \\cdot f(\\mathbf{x}; \\theta_0) - f(\\mathbf{x}; \\theta_a)\\right]$$\n\n. . .\n\n**Key insight:** The expression $k \\cdot f(\\mathbf{x}; \\theta_0) - f(\\mathbf{x}; \\theta_a)$ can be positive or negative. To **minimize** $k\\alpha + \\beta$, choose $R$ to include exactly the points where this expression is negative:\n\n$$R^* = \\left\\{\\mathbf{x}: k \\cdot f(\\mathbf{x}; \\theta_0) - f(\\mathbf{x}; \\theta_a) \\leq 0\\right\\} = \\left\\{\\mathbf{x}: \\frac{f(\\mathbf{x}; \\theta_a)}{f(\\mathbf{x}; \\theta_0)} \\geq k\\right\\}$$\n\n. . .\n\nThis is exactly the Neyman-Pearson rejection region! So $R^*$ minimizes $k\\alpha + \\beta$.\n\n## Proof (continued)\n\nWe've shown: $k\\alpha^* + \\beta^* \\leq k\\alpha + \\beta$ for **all** rejection regions $R$.\n\n. . .\n\nNow, for any test with $\\alpha \\leq \\alpha^*$:\n\n$$k\\alpha^* + \\beta^* \\leq k\\alpha + \\beta$$\n\n$$\\beta^* \\leq \\beta + k(\\alpha - \\alpha^*) \\leq \\beta + k \\cdot 0 = \\beta$$\n\n. . .\n\nsince $\\alpha - \\alpha^* \\leq 0$ and $k > 0$.\n\n. . .\n\nTherefore $\\beta^* \\leq \\beta$ for all tests with $\\alpha \\leq \\alpha^*$. $\\blacksquare$\n\n. . .\n\n::: callout-note\n## What Does This Mean?\nThe proof works by showing that the NP rejection region simultaneously minimizes **both** $\\alpha$ and $\\beta$ in a trade-off sense. You cannot do better on one without doing worse on the other. The NP test is on the **efficient frontier** of the $(\\alpha, \\beta)$ trade-off.\n:::\n\n## Example: Adverse Events in a Drug Trial (Normal, Known $\\sigma$)\n\nA pharmaceutical company monitors a biomarker level in patients. Under the current treatment, biomarker levels follow $N(\\mu, 1)$. An elevated biomarker signals a potential adverse event.\n\nTest $H_0: \\mu = 5$ vs $H_a: \\mu = 6$ based on $n$ patients (known $\\sigma = 1$).\n\n. . .\n\n**Applying the Neyman-Pearson Lemma:**\n\n$$\\frac{L(\\mu_a = 6)}{L(\\mu_0 = 5)} = \\frac{\\prod_{i=1}^n \\frac{1}{\\sqrt{2\\pi}} e^{-(x_i - 6)^2/2}}{\\prod_{i=1}^n \\frac{1}{\\sqrt{2\\pi}} e^{-(x_i - 5)^2/2}} = e^{\\sum (x_i - 6)^2/2 \\cdot (-1) + \\sum(x_i - 5)^2/2}$$\n\n. . .\n\nSimplifying the exponent:\n\n$$= e^{(6 - 5)\\sum x_i - n(6^2 - 5^2)/2} = e^{\\sum x_i - 11n/2}$$\n\n## Example: Normal (continued)\n\nThe rejection region $\\Lambda^* \\geq k$ becomes:\n\n$$e^{\\sum x_i - 11n/2} \\geq k$$\n\n. . .\n\nTaking logarithms (since $\\mu_a - \\mu_0 = 1 > 0$, the exponential is increasing in $\\sum x_i$):\n\n$$\\sum x_i \\geq k' \\quad \\iff \\quad \\bar{x} \\geq k'' \\quad \\iff \\quad \\frac{\\bar{x} - 5}{1/\\sqrt{n}} \\geq c$$\n\n. . .\n\nSetting $c = z_\\alpha$, this is exactly the **one-sample z test**!\n\n. . .\n\n::: callout-important\n## Key Result (Devore Example 9.24)\nFor $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ known, testing $H_0: \\mu = \\mu_0$ vs $H_a: \\mu = \\mu_a$ where $\\mu_a > \\mu_0$:\n\nThe Neyman-Pearson Lemma shows that the **one-sample z test** (reject when $z \\geq z_\\alpha$) is the **most powerful** test at level $\\alpha$. Our familiar z test is optimal!\n:::\n\n## Example: Poisson Adverse Event Counts (Devore Example 9.23)\n\nIn post-market drug surveillance, the number of adverse events per reporting period is monitored. Suppose $X_1, \\ldots, X_5 \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$ represent adverse event counts over 5 periods. \n\nTest $H_0: \\lambda = 1$ (baseline rate) vs $H_a: \\lambda = 2$ (elevated rate).\n\n. . .\n\n**The Poisson likelihood is:** $f(x_1, \\ldots, x_5; \\lambda) = e^{-5\\lambda} \\lambda^{\\sum x_i} / \\prod x_i!$\n\n. . .\n\n**The likelihood ratio:**\n\n$$\\frac{L(\\lambda = 2)}{L(\\lambda = 1)} = \\frac{e^{-10} \\cdot 2^{\\sum x_i}}{e^{-5} \\cdot 1^{\\sum x_i}} = e^{-5} \\cdot 2^{\\sum x_i} \\geq k$$\n\n. . .\n\nTaking logarithms: $\\sum x_i \\geq c$ where $c = \\ln(k \\cdot e^5)/\\ln(2)$.\n\n## Example: Poisson (continued)\n\n**Finding the critical value:** Under $H_0$, $Y = \\sum X_i \\sim \\text{Poisson}(5)$.\n\n. . .\n\nIf we use $c = 10$: $\\alpha^* = P(Y \\geq 10 \\mid Y \\sim \\text{Poisson}(5)) = 1 - 0.968 = 0.032$\n\nIf we use $c = 9$: $\\alpha^* = P(Y \\geq 9 \\mid Y \\sim \\text{Poisson}(5)) = 1 - 0.932 = 0.068$\n\n. . .\n\nFor $\\alpha \\leq 0.05$, we use $c = 10$, giving $\\alpha^* = 0.032$.\n\n. . .\n\n**Type II error:** Under $H_a$, $Y \\sim \\text{Poisson}(10)$.\n\n$$\\beta^* = P(Y < 10 \\mid Y \\sim \\text{Poisson}(10)) = 0.458$$\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Verify with R\ncat(\"alpha* =\", 1 - ppois(9, lambda = 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalpha* = 0.03182806 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"beta*  =\", ppois(9, lambda = 10), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta*  = 0.4579297 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"Power  =\", 1 - ppois(9, lambda = 10), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower  = 0.5420703 \n```\n\n\n:::\n:::\n\n\n## Example: Poisson (continued)\n\n**The Neyman-Pearson guarantee:** Any other test with $\\alpha \\leq 0.032$ must have $\\beta \\geq 0.458$.\n\n. . .\n\nThe power is only $1 - 0.458 = 0.542$. Why so low?\n\n. . .\n\n**Because $n = 5$ is too small** to discriminate between $\\lambda = 1$ and $\\lambda = 2$.\n\nFor $n = 10$: best test with $\\alpha \\leq 0.05$ uses $c = 16$, giving $\\alpha^* = 0.049$ and $\\beta^* = 0.157$ (power = 0.843).\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Compare rejection regions for n=5 and n=10\ntibble(y = 0:30) |>\n  mutate(\n    `n = 5, Poisson(5)` = dpois(y, 5),\n    `n = 5, Poisson(10)` = dpois(y, 10),\n    `n = 10, Poisson(10)` = dpois(y, 10),\n    `n = 10, Poisson(20)` = dpois(y, 20)\n  ) |>\n  pivot_longer(-y, names_to = \"distribution\", values_to = \"prob\") |>\n  separate(distribution, into = c(\"sample_size\", \"dist\"), sep = \", \") |>\n  ggplot(aes(x = y, y = prob, fill = dist)) +\n  geom_col(position = \"identity\", alpha = 0.5, width = 0.8) +\n  geom_vline(data = tibble(sample_size = c(\"n = 5\", \"n = 10\"), \n                            cutoff = c(10, 16)),\n             aes(xintercept = cutoff - 0.5), linetype = \"dashed\", \n             color = \"red\", linewidth = 1) +\n  facet_wrap(~sample_size, scales = \"free\") +\n  scale_fill_manual(values = c(\"steelblue\", \"coral\", \"steelblue\", \"coral\")) +\n  labs(x = expression(y == sum(x[i])), y = \"Probability\",\n       title = \"Neyman-Pearson Test: Poisson Adverse Event Monitoring\",\n       subtitle = \"Red dashed line = rejection boundary; larger n gives better separation\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-2-1.png){width=1344}\n:::\n:::\n\n\n## Medical Example: Exponential Survival Times (C&H Example 8.18)\n\nIn an oncology trial, patient survival times follow $\\text{Exp}(\\lambda)$. We want to test whether the hazard rate has increased from a historical baseline.\n\nTest $H_0: \\lambda = 8$ vs $H_a: \\lambda = 10$ based on $n = 9$ patients.\n\n. . .\n\n**Likelihood ratio:**\n\n$$\\frac{L(\\lambda = 8)}{L(\\lambda = 10)} = \\frac{8^9 e^{-8\\sum x_i}}{10^9 e^{-10\\sum x_i}} = (0.8)^9 e^{2\\sum x_i}$$\n\n. . .\n\n(Note: Chihara uses $L(\\theta_0)/L(\\theta_a)$, rejecting for small values.)\n\nReject $H_0$ when this ratio is small, i.e., when $\\sum x_i < c_2$.\n\n. . .\n\nUnder $H_0$: $\\sum_{i=1}^9 X_i \\sim \\text{Gamma}(9, 8)$. For $\\alpha = 0.05$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc2 <- qgamma(0.05, shape = 9, rate = 8)\ncat(\"Critical value c2 =\", round(c2, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value c2 = 0.5869 \n```\n\n\n:::\n:::\n\n\nBy the Neyman-Pearson Lemma, this is the **best possible** test at this significance level.\n\n# Power Functions and UMP Tests {background-color=\"#27ae60\"}\n\n## The Power Function\n\n::: callout-important\n## Definition (Power Function, Devore 9.5)\nLet $\\Omega_0$ and $\\Omega_a$ be two disjoint sets of possible values of $\\theta$. For testing $H_0: \\theta \\in \\Omega_0$ vs $H_a: \\theta \\in \\Omega_a$ with rejection region $R$, the **power function** is:\n\n$$\\pi(\\theta') = P_{\\theta'}((X_1, \\ldots, X_n) \\in R)$$\n\nthe probability of rejecting $H_0$ as a function of $\\theta$.\n:::\n\n. . .\n\n**Connection to error probabilities:**\n\n$$\\pi(\\theta') = \\begin{cases} P(\\text{Type I error}) = \\alpha(\\theta') & \\text{when } \\theta' \\in \\Omega_0 \\\\[4pt] 1 - P(\\text{Type II error}) = 1 - \\beta(\\theta') & \\text{when } \\theta' \\in \\Omega_a \\end{cases}$$\n\n. . .\n\n**Ideal power function** (unachievable in practice):\n\n$$\\pi(\\theta') = \\begin{cases} 0 & \\text{when } \\theta' \\in \\Omega_0 \\\\ 1 & \\text{when } \\theta' \\in \\Omega_a \\end{cases}$$\n\n## Visualizing the Power Function\n\n**Example (Devore 9.25 adapted):** Blood pressure reduction (mmHg) with a new antihypertensive follows $N(\\mu, 81)$. Test $H_0: \\mu \\leq 75$ vs $H_a: \\mu < 75$ with $n = 100$, $\\alpha = 0.10$.\n\nRejection region: $z \\leq -z_{0.10} = -1.28$, i.e., $\\bar{x} \\leq 73.848$.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Power function for the z test\nsigma <- 9\nn <- 100\nse <- sigma / sqrt(n)\nx_crit <- 75 - 1.28 * se  # 73.848\n\nmu_prime <- seq(68, 78, length.out = 500)\npower_actual <- pnorm((x_crit - mu_prime) / se)\n\npower_df <- tibble(mu = mu_prime, power = power_actual)\n\nggplot(power_df, aes(x = mu, y = power)) +\n  geom_line(linewidth = 1.3, color = \"steelblue\") +\n  # Ideal power function\n  geom_segment(aes(x = 68, xend = 75, y = 1, yend = 1), \n               linetype = \"dashed\", color = \"coral\", linewidth = 1) +\n  geom_segment(aes(x = 75, xend = 78, y = 0, yend = 0), \n               linetype = \"dashed\", color = \"coral\", linewidth = 1) +\n  geom_vline(xintercept = 75, linetype = \"dotted\", color = \"gray50\") +\n  geom_hline(yintercept = 0.10, linetype = \"dotted\", color = \"gray50\") +\n  annotate(\"text\", x = 76.5, y = 0.6, label = \"Ideal\", color = \"coral\", size = 6) +\n  annotate(\"text\", x = 70, y = 0.6, label = \"Actual\", color = \"steelblue\", size = 6) +\n  annotate(\"text\", x = 77, y = 0.12, \n           label = expression(alpha == 0.10), size = 5, color = \"gray30\") +\n  annotate(\"text\", x = 75.3, y = 0.5, \n           label = expression(mu[0] == 75), size = 5, color = \"gray30\") +\n  scale_y_continuous(breaks = seq(0, 1, 0.1)) +\n  labs(x = expression(mu * \"' (true mean)\"), y = expression(pi(mu * \"'\")),\n       title = \"Power Function for the Lower-Tailed z Test\",\n       subtitle = bquote(\"Testing\" ~ H[0]*\":\" ~ mu <= 75 ~ \"vs\" ~ H[a]*\":\" ~ mu < 75 ~ \"with n = 100,\" ~ sigma == 9*\",\" ~ alpha == 0.10))\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-4-1.png){width=1344}\n:::\n:::\n\n\n## Properties of the Power Function\n\nFrom the figure, we observe several important properties:\n\n. . .\n\n1. **At the boundary** ($\\mu = 75$): $\\pi(75) = \\alpha = 0.10$ by design\n\n. . .\n\n2. **In $\\Omega_0$** ($\\mu > 75$): $\\pi(\\mu') < 0.10$ --- power is below $\\alpha$ (good!)\n\n. . .\n\n3. **Near the boundary** ($\\mu$ slightly below 75): power is barely above $\\alpha$ --- small departures are hard to detect\n\n. . .\n\n4. **Far from $H_0$** ($\\mu \\ll 75$): $\\pi(\\mu') \\to 1$ --- large departures are easily detected\n\n. . .\n\n5. **As $n$ increases:** the actual power function approaches the ideal step function\n\n. . .\n\n::: callout-tip\n## Clinical Implication\nIn designing a clinical trial, we need to choose $n$ large enough so that the power function is acceptably close to 1 at the **minimum clinically important difference**. This connects directly to the sample size calculations from Lesson 14.\n:::\n\n## Uniformly Most Powerful (UMP) Tests\n\nThe NP Lemma handles simple vs simple. What about composite alternatives?\n\n. . .\n\n::: callout-important\n## Definition (Uniformly Most Powerful Test)\nA test is **uniformly most powerful (UMP)** at level $\\alpha$ if it maximizes $\\pi(\\theta')$ for **every** $\\theta' \\in \\Omega_a$, subject to $\\pi(\\theta') \\leq \\alpha$ for all $\\theta' \\in \\Omega_0$.\n:::\n\n. . .\n\n**When do UMP tests exist?** If the NP rejection region **does not depend on the specific alternative** $\\theta_a$, then the same test is most powerful for *every* $\\theta_a \\in \\Omega_a$.\n\n## UMP Example: Poisson (Devore Example 9.26)\n\nReturning to the Poisson adverse event example with $n = 5$:\n\nTest $H_0: \\lambda \\leq 1$ vs $H_a: \\lambda > 1$.\n\n. . .\n\nFor **any** specific $\\lambda_a > 1$, the NP test of $H_0: \\lambda = 1$ vs $H_a: \\lambda = \\lambda_a$ rejects when $\\sum x_i \\geq c$.\n\n. . .\n\n**Key observation:** The rejection region $\\sum x_i \\geq 10$ is the **same** regardless of which $\\lambda_a > 1$ we choose! (The critical value $c$ is determined by $H_0$ alone.)\n\n. . .\n\nTherefore, this test is **UMP** at level $\\alpha^* = 0.032$.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Power function for the UMP Poisson test\nlambda_prime <- seq(0, 5, length.out = 300)\npower_poisson <- 1 - ppois(9, lambda = 5 * lambda_prime)\n\nggplot(tibble(lambda = lambda_prime, power = power_poisson), \n       aes(x = lambda, y = power)) +\n  geom_line(linewidth = 1.3, color = \"steelblue\") +\n  geom_vline(xintercept = 1, linetype = \"dotted\", color = \"gray50\") +\n  geom_hline(yintercept = 0.032, linetype = \"dashed\", color = \"coral\") +\n  annotate(\"text\", x = 0.5, y = 0.08, \n           label = expression(alpha * \"* = 0.032\"), color = \"coral\", size = 5) +\n  annotate(\"text\", x = 1.15, y = 0.5, \n           label = expression(lambda[0] == 1), color = \"gray40\", size = 5) +\n  labs(x = expression(lambda * \"' (true Poisson rate)\"), \n       y = expression(pi(lambda * \"'\")),\n       title = bquote(\"Power Function of the UMP Test for\" ~ H[0]*\":\" ~ lambda <= 1),\n       subtitle = bquote(\"Reject when\" ~ sum(X[i], i==1, 5) >= 10 ~ \"; maximizes power for every\" ~ lambda > 1))\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-5-1.png){width=1344}\n:::\n:::\n\n\n## When UMP Tests Don't Exist\n\n::: callout-warning\n## Important Limitation\nUMP tests are **fairly rare**, especially in the commonly encountered situation of testing a two-sided alternative.\n:::\n\n. . .\n\n**Example:** Testing $H_0: \\mu = \\mu_0$ vs $H_a: \\mu \\neq \\mu_0$ with $X_i \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$, $\\sigma$ known.\n\n- For $\\mu_a > \\mu_0$: NP test rejects when $\\bar{x}$ is **large** (upper tail)\n- For $\\mu_a < \\mu_0$: NP test rejects when $\\bar{x}$ is **small** (lower tail)\n- These are **different rejection regions** --- no single test is best for all $\\mu_a \\neq \\mu_0$\n\n. . .\n\n**Resolution:** Restrict attention to **unbiased tests** (tests where $\\pi(\\theta') \\geq \\alpha$ for all $\\theta' \\in \\Omega_a$). Under this restriction:\n\n- The two-sided z test is **UMP unbiased** when $\\sigma$ is known\n- The one-sample t test is **UMP unbiased** when $\\sigma$ is unknown\n\n## Unbiased Tests\n\n::: callout-note\n## Definition (Unbiased Test)\nA test is **unbiased** if the power under any alternative is at least as large as the power under any null value:\n\n$$\\inf_{\\theta' \\in \\Omega_a} \\pi(\\theta') \\geq \\sup_{\\theta' \\in \\Omega_0} \\pi(\\theta')$$\n\nEquivalently: we are at least as likely to reject $H_0$ when it is false as when it is true.\n:::\n\n. . .\n\n**Why is this desirable?** A biased test would reject $H_0$ *less* often for some alternatives than it does when $H_0$ is true --- that would defeat the purpose of the test!\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Biased vs unbiased test illustration\nmu_seq <- seq(-4, 4, length.out = 500)\nn_ex <- 16; sigma_ex <- 4; se_ex <- sigma_ex / sqrt(n_ex)\n\n# Unbiased (symmetric) rejection region\npower_unbiased <- pnorm((-1.96 * se_ex - mu_seq) / se_ex) + \n                  1 - pnorm((1.96 * se_ex - mu_seq) / se_ex)\n\n# Biased (asymmetric) rejection region: reject if x_bar > 2.17 or x_bar < -1.81\npower_biased <- pnorm((-1.81 * se_ex - mu_seq) / se_ex) + \n                1 - pnorm((2.17 * se_ex - mu_seq) / se_ex)\n\ntibble(mu = mu_seq, Unbiased = power_unbiased, Biased = power_biased) |>\n  pivot_longer(-mu, names_to = \"Test\", values_to = \"Power\") |>\n  ggplot(aes(x = mu, y = Power, color = Test)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", color = \"gray50\") +\n  scale_color_manual(values = c(\"coral\", \"steelblue\")) +\n  annotate(\"text\", x = 3.5, y = 0.08, label = expression(alpha == 0.05), \n           color = \"gray50\", size = 5) +\n  labs(x = expression(mu * \"'\"), y = expression(pi(mu * \"'\")),\n       title = \"Unbiased vs Biased Tests for H0: \\u03bc = 0 vs Ha: \\u03bc \\u2260 0\",\n       subtitle = \"The biased test has power < alpha for some alternatives near mu = 0\") +\n  theme(legend.position = c(0.85, 0.5))\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-6-1.png){width=1344}\n:::\n:::\n\n\n# Likelihood Ratio Tests (Devore 9.5) {background-color=\"#8e44ad\"}\n\n## From Simple to Composite Hypotheses\n\nThe NP Lemma handles simple vs simple hypotheses. But in practice, we need tests for:\n\n$$H_0: \\theta \\in \\Omega_0 \\quad \\text{vs} \\quad H_a: \\theta \\in \\Omega_a$$\n\nwhere one or both hypotheses may be composite.\n\n. . .\n\n**The likelihood ratio principle** provides a **general recipe** for constructing test statistics in virtually any testing situation.\n\n. . .\n\n::: callout-important\n## The Likelihood Ratio Test (LRT) Procedure\n\n1. Find $\\hat{\\theta}_{mle}$, the MLE of $\\theta$ over the **full** parameter space $\\Omega = \\Omega_0 \\cup \\Omega_a$\n2. Find $\\hat{\\theta}_0$, the **restricted MLE** of $\\theta$ over $\\Omega_0$ only\n3. Form the **likelihood ratio statistic**:\n\n$$\\Lambda = \\frac{L(\\hat{\\theta}_0)}{L(\\hat{\\theta}_{mle})}$$\n\n4. Reject $H_0$ when $\\Lambda \\leq k$ (i.e., when the restricted MLE fits much worse than the unrestricted MLE)\n:::\n\n## Understanding the LRT Statistic\n\n$$\\Lambda = \\frac{L(\\hat{\\theta}_0)}{L(\\hat{\\theta}_{mle})} = \\frac{\\max_{\\theta \\in \\Omega_0} L(\\theta)}{\\max_{\\theta \\in \\Omega} L(\\theta)}$$\n\n. . .\n\n**Key properties:**\n\n- Always $0 \\leq \\Lambda \\leq 1$ (because $\\Omega_0 \\subseteq \\Omega$, so the restricted maximum $\\leq$ unrestricted maximum)\n- $\\Lambda \\approx 1$: the data are about equally consistent with $H_0$ and the overall best fit\n- $\\Lambda \\approx 0$: the data are **much** more consistent with $H_a$ than with $H_0$\n\n. . .\n\n**Connection to NP Lemma:** When both hypotheses are simple ($\\Omega_0 = \\{\\theta_0\\}$ and $\\Omega_a = \\{\\theta_a\\}$):\n\n$$\\Lambda = \\frac{L(\\theta_0)}{\\max\\{L(\\theta_0), L(\\theta_a)\\}} = \\begin{cases} L(\\theta_0)/L(\\theta_a) & \\text{if } L(\\theta_a) \\geq L(\\theta_0) \\\\[2pt] 1 & \\text{otherwise} \\end{cases}$$\n\nThis is the reciprocal of the NP statistic (when $H_a$ is more likely), so rejecting for small $\\Lambda$ is equivalent to rejecting for large $\\Lambda^*$.\n\n## LRT Example 1: Normal Mean, Known Variance (Devore Example 9.27 style)\n\nSystolic blood pressure readings follow $N(\\mu, 100)$ (known $\\sigma = 10$). A clinical trial tests whether a new treatment changes the population mean from a target value.\n\n$$H_0: \\mu = \\mu_0 \\quad \\text{vs} \\quad H_a: \\mu \\neq \\mu_0$$\n\n. . .\n\n**Step 1: Unrestricted MLE.** Over $\\Omega = \\mathbb{R}$: $\\hat{\\mu}_{mle} = \\bar{x}$\n\n. . .\n\n**Step 2: Restricted MLE.** Over $\\Omega_0 = \\{\\mu_0\\}$: $\\hat{\\mu}_0 = \\mu_0$\n\n. . .\n\n**Step 3: Likelihood ratio.**\n\n$$\\Lambda = \\frac{L(\\mu_0)}{L(\\bar{x})} = \\frac{\\prod \\frac{1}{\\sqrt{2\\pi}\\sigma} e^{-(x_i - \\mu_0)^2/(2\\sigma^2)}}{\\prod \\frac{1}{\\sqrt{2\\pi}\\sigma} e^{-(x_i - \\bar{x})^2/(2\\sigma^2)}} = e^{-\\frac{1}{2\\sigma^2}\\left[\\sum(x_i - \\mu_0)^2 - \\sum(x_i - \\bar{x})^2\\right]}$$\n\n. . .\n\nSince $\\sum(x_i - \\mu_0)^2 = \\sum(x_i - \\bar{x})^2 + n(\\bar{x} - \\mu_0)^2$:\n\n$$\\Lambda = e^{-n(\\bar{x} - \\mu_0)^2 / (2\\sigma^2)}$$\n\n## LRT $\\Rightarrow$ z Test\n\nReject when $\\Lambda \\leq k$:\n\n$$e^{-n(\\bar{x} - \\mu_0)^2/(2\\sigma^2)} \\leq k$$\n\n. . .\n\nTaking $-\\ln$ of both sides:\n\n$$\\frac{n(\\bar{x} - \\mu_0)^2}{2\\sigma^2} \\geq -\\ln(k) = c'$$\n\n. . .\n\n$$\\left|\\frac{\\bar{x} - \\mu_0}{\\sigma/\\sqrt{n}}\\right| \\geq c$$\n\n. . .\n\nThis is the **two-sided z test**! Setting $c = z_{\\alpha/2}$ gives the test at level $\\alpha$.\n\n. . .\n\n::: callout-important\n## Key Result\nThe **likelihood ratio test** for $H_0: \\mu = \\mu_0$ vs $H_a: \\mu \\neq \\mu_0$ when $\\sigma$ is known is exactly the **two-sided z test**. The LRT principle automatically \"discovers\" the z test.\n:::\n\n## LRT Example 2: Normal Mean, Unknown Variance (Devore Example 9.27)\n\nNow suppose $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ **unknown**.\n\n$$H_0: \\mu = \\mu_0 \\quad \\text{vs} \\quad H_a: \\mu \\neq \\mu_0$$\n\n. . .\n\n**Step 1: Unrestricted MLE** over $\\Omega = \\{(\\mu, \\sigma^2): \\mu \\in \\mathbb{R}, \\sigma^2 > 0\\}$:\n\n$$\\hat{\\mu}_{mle} = \\bar{x}, \\quad \\hat{\\sigma}^2_{mle} = \\frac{1}{n}\\sum(x_i - \\bar{x})^2$$\n\n. . .\n\n**Step 2: Restricted MLE** over $\\Omega_0 = \\{(\\mu_0, \\sigma^2): \\sigma^2 > 0\\}$:\n\n$$\\hat{\\mu}_0 = \\mu_0, \\quad \\hat{\\sigma}^2_0 = \\frac{1}{n}\\sum(x_i - \\mu_0)^2$$\n\n. . .\n\nNote: under $H_0$, we still estimate $\\sigma^2$ by MLE, but with $\\mu$ fixed at $\\mu_0$.\n\n## LRT $\\Rightarrow$ t Test (Devore Example 9.27)\n\n**Step 3: Likelihood ratio.** After substitution and simplification:\n\n$$\\Lambda = \\left[\\frac{\\hat{\\sigma}^2_{mle}}{\\hat{\\sigma}^2_0}\\right]^{n/2} = \\left[\\frac{\\sum(x_i - \\bar{x})^2}{\\sum(x_i - \\mu_0)^2}\\right]^{n/2}$$\n\n. . .\n\nSince $\\sum(x_i - \\mu_0)^2 = \\sum(x_i - \\bar{x})^2 + n(\\bar{x} - \\mu_0)^2$:\n\n$$\\Lambda = \\left[\\frac{1}{1 + \\frac{n(\\bar{x} - \\mu_0)^2}{\\sum(x_i - \\bar{x})^2}}\\right]^{n/2} = \\left[\\frac{1}{1 + t^2/(n-1)}\\right]^{n/2}$$\n\nwhere $t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}$ is the **t statistic**.\n\n. . .\n\n**Reject** when $\\Lambda$ is small $\\iff$ $t^2/(n-1)$ is large $\\iff$ $|t| \\geq c$.\n\nSetting $c = t_{\\alpha/2, n-1}$ gives the **one-sample t test**.\n\n. . .\n\n::: callout-important\n## Key Result\nThe **likelihood ratio test** for $H_0: \\mu = \\mu_0$ vs $H_a: \\mu \\neq \\mu_0$ when $\\sigma$ is unknown is exactly the **one-sample t test**. Many classical tests can be derived from the LRT principle.\n:::\n\n## LRT and the t Test: Simulation Illustration\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Demonstrate that the LRT statistic is a monotone function of |t|\nset.seed(551)\nn_sim <- 25\nmu_0 <- 120  # target systolic BP\n# Simulated clinical trial data: true mu = 125\nx_data <- rnorm(n_sim, mean = 125, sd = 15)\n\nx_bar <- mean(x_data)\ns <- sd(x_data)\nt_stat <- (x_bar - mu_0) / (s / sqrt(n_sim))\n\n# Compute Lambda for a range of hypothetical t values\nt_range <- seq(-5, 5, length.out = 500)\nlambda_vals <- (1 / (1 + t_range^2 / (n_sim - 1)))^(n_sim / 2)\n\np1 <- ggplot(tibble(t = t_range, Lambda = lambda_vals), aes(x = t, y = Lambda)) +\n  geom_line(linewidth = 1.2, color = \"steelblue\") +\n  geom_vline(xintercept = c(-qt(0.025, n_sim - 1), qt(0.025, n_sim - 1)),\n             linetype = \"dashed\", color = \"coral\") +\n  geom_point(data = tibble(t = t_stat, \n                            Lambda = (1 / (1 + t_stat^2 / (n_sim - 1)))^(n_sim / 2)),\n             size = 4, color = \"darkred\") +\n  annotate(\"text\", x = t_stat - 0.3, y = 0.6, \n           label = paste0(\"Observed t = \", round(t_stat, 2)), \n           color = \"darkred\", size = 5, hjust = 1) +\n  labs(x = \"t statistic\", y = expression(Lambda),\n       title = expression(Lambda == (1 + t^2/(n-1))^{-n/2}),\n       subtitle = expression(\"Smaller \" * Lambda * \" = stronger evidence against \" * H[0]))\n\n# Show the relationship between -2ln(Lambda) and t^2\nneg2lnL <- -n_sim * log(1 + t_range^2 / (n_sim - 1))\np2 <- ggplot(tibble(t2 = t_range^2, neg2lnL = -neg2lnL), \n             aes(x = t2, y = neg2lnL)) +\n  geom_line(linewidth = 1.2, color = \"purple\") +\n  geom_vline(xintercept = qt(0.975, n_sim - 1)^2, \n             linetype = \"dashed\", color = \"coral\") +\n  labs(x = expression(t^2), y = expression(-2 * ln(Lambda)),\n       title = expression(-2 * ln(Lambda) ~ \"vs\" ~ t^2),\n       subtitle = \"Monotone increasing: small Lambda = large |t|\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-7-1.png){width=1344}\n:::\n:::\n\n\n## Medical Application: Drug Efficacy Trial\n\nA Phase III clinical trial tests whether a new cholesterol-lowering drug changes mean LDL from baseline $\\mu_0 = 130$ mg/dL. Data from $n = 30$ patients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 30\nmu_0 <- 130\nldl_data <- rnorm(n, mean = 122, sd = 18)\n\nx_bar <- mean(ldl_data)\ns_val <- sd(ldl_data)\nt_obs <- (x_bar - mu_0) / (s_val / sqrt(n))\n\ncat(\"Sample mean:\", round(x_bar, 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 123.23 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:  \", round(s_val, 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD:   22.59 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t statistic:\", round(t_obs, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt statistic: -1.64 \n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LRT statistic\nLambda <- (1 / (1 + t_obs^2 / (n - 1)))^(n / 2)\nneg2lnLambda <- -2 * log(Lambda)\n\ncat(\"Lambda:       \", round(Lambda, 6), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLambda:        0.26424 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"-2 ln(Lambda):\", round(neg2lnLambda, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-2 ln(Lambda): 2.662 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t^2:         \", round(t_obs^2, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt^2:          2.691 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value (t):  \", round(2 * pt(-abs(t_obs), df = n - 1), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP-value (t):   0.1117 \n```\n\n\n:::\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify with t.test\nt.test(ldl_data, mu = mu_0) |> tidy() |> \n  select(estimate, statistic, p.value, conf.low, conf.high) |>\n  mutate(across(everything(), ~round(., 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  estimate statistic p.value conf.low conf.high\n     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1     123.     -1.64   0.112     115.      132.\n```\n\n\n:::\n:::\n\n\n# Large-Sample LRT Approximation {background-color=\"#f39c12\"}\n\n## Wilks' Theorem: The Chi-Squared Approximation\n\nIn many situations, the LRT rejection region $\\Lambda \\leq k$ cannot be expressed in terms of a simple, familiar statistic. A powerful large-sample result resolves this.\n\n. . .\n\n::: callout-important\n## Theorem (Wilks' Theorem, Devore 9.5)\nIf the sample size $n$ is sufficiently large, then under $H_0$:\n\n$$-2\\ln(\\Lambda) \\xrightarrow{d} \\chi^2_m$$\n\nwhere $m$ is the difference between the number of free parameters in $\\Omega$ and the number of free parameters in $\\Omega_0$.\n:::\n\n. . .\n\n**How to use it:** Since $0 \\leq \\Lambda \\leq 1$, we have $-2\\ln(\\Lambda) \\geq 0$. Reject $H_0$ when:\n\n$$-2\\ln(\\Lambda) \\geq \\chi^2_{\\alpha, m}$$\n\n. . .\n\n**The degrees of freedom $m$:**\n\n- $m = \\dim(\\Omega) - \\dim(\\Omega_0)$ = (number of parameters estimated under $H_a$) minus (number estimated under $H_0$)\n- Represents the number of \"constraints\" imposed by $H_0$\n\n## Computing Degrees of Freedom: Examples\n\n| Setting | $\\Omega$ | $\\Omega_0$ | $m$ |\n|---------|----------|------------|-----|\n| $N(\\mu, \\sigma^2)$, $\\sigma$ known, $H_0: \\mu = \\mu_0$ | 1 ($\\mu$) | 0 | 1 |\n| $N(\\mu, \\sigma^2)$, $\\sigma$ unknown, $H_0: \\mu = \\mu_0$ | 2 ($\\mu, \\sigma^2$) | 1 ($\\sigma^2$) | 1 |\n| Bivariate normal, $H_0: \\mu_1 = \\mu_2$ and $\\sigma_1 = \\sigma_2$ | 5 ($\\mu_1, \\mu_2, \\sigma_1, \\sigma_2, \\rho$) | 3 ($\\mu, \\sigma, \\rho$) | 2 |\n| Multinomial with $k$ categories, $H_0: p_i = p_{i,0}$ | $k - 1$ | 0 | $k - 1$ |\n\n. . .\n\n::: callout-tip\n## Practical Rule\nCount the number of parameters that are \"free\" (need to be estimated) under each hypothesis. The difference is $m$.\n:::\n\n## Large-Sample LRT Example: Double Exponential (Devore 9.5)\n\nThe Laplace (double exponential) distribution with pdf $f(x; \\theta) = \\frac{1}{2}e^{-|x - \\theta|}$ is sometimes used to model measurement errors. Test $H_0: \\theta = 0$ vs $H_a: \\theta \\neq 0$.\n\n. . .\n\n**Under $\\Omega$:** The MLE of $\\theta$ is the **sample median** $\\tilde{x}$ (minimizes $\\sum |x_i - \\theta|$).\n\n**Under $\\Omega_0$:** $\\theta = 0$ (no estimation needed).\n\n. . .\n\n$$\\Lambda = \\frac{(1/2)^n e^{-\\sum|x_i|}}{(1/2)^n e^{-\\sum|x_i - \\tilde{x}|}} = e^{-(\\sum|x_i| - \\sum|x_i - \\tilde{x}|)}$$\n\n. . .\n\n$$-2\\ln(\\Lambda) = 2\\left(\\sum|x_i| - \\sum|x_i - \\tilde{x}|\\right)$$\n\n. . .\n\n**Degrees of freedom:** $m = 1 - 0 = 1$, so $-2\\ln(\\Lambda) \\stackrel{\\cdot}{\\sim} \\chi^2_1$ under $H_0$.\n\nReject $H_0$ when $-2\\ln(\\Lambda) \\geq \\chi^2_{\\alpha, 1}$.\n\n## Simulation: Verifying the Chi-Squared Approximation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Simulate LRT for normal mean (known variance) and check chi-squared approximation\nset.seed(551)\nn_obs <- 30\nn_rep <- 10000\nmu_0 <- 0\nsigma_known <- 1\n\n# Simulate under H_0\nneg2lnL_sims <- replicate(n_rep, {\n  x <- rnorm(n_obs, mean = mu_0, sd = sigma_known)\n  x_bar <- mean(x)\n  # -2ln(Lambda) = n * (x_bar - mu_0)^2 / sigma^2 for known variance case\n  n_obs * (x_bar - mu_0)^2 / sigma_known^2\n})\n\n# Compare to chi-squared(1)\nchi2_theoretical <- seq(0.01, 12, length.out = 500)\n\np1 <- ggplot(tibble(stat = neg2lnL_sims), aes(x = stat)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 60, \n                 fill = \"steelblue\", alpha = 0.6) +\n  geom_line(data = tibble(x = chi2_theoretical, y = dchisq(chi2_theoretical, df = 1)),\n            aes(x = x, y = y), color = \"coral\", linewidth = 1.2) +\n  labs(x = expression(-2 * ln(Lambda)), y = \"Density\",\n       title = expression(\"Simulated \" * -2 * ln(Lambda) * \" vs \" * chi[1]^2 * \n                         \" (n = 30, known \" * sigma * \")\"),\n       subtitle = expression(\"Red curve: \" * chi^2 * \"(1) density\"))\n\n# Q-Q plot\np2 <- ggplot(tibble(stat = neg2lnL_sims), aes(sample = stat)) +\n  stat_qq(distribution = qchisq, dparams = list(df = 1), \n          color = \"steelblue\", alpha = 0.3, size = 0.8) +\n  stat_qq_line(distribution = qchisq, dparams = list(df = 1), \n               color = \"coral\", linewidth = 1) +\n  labs(x = expression(\"Theoretical \" * chi[1]^2 * \" quantiles\"),\n       y = expression(\"Sample quantiles of \" * -2 * ln(Lambda)),\n       title = \"Q-Q Plot: Chi-Squared Approximation\",\n       subtitle = \"Close alignment confirms Wilks' theorem\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-11-1.png){width=1344}\n:::\n:::\n\n\n## How Good is the Approximation for Small $n$?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Check chi-squared approximation quality for different n\n# Normal mean, unknown variance -> -2ln(Lambda) = n*ln(1 + t^2/(n-1))\nset.seed(551)\nn_rep <- 50000\nsample_sizes <- c(5, 10, 30, 100)\n\nsim_results <- map_dfr(sample_sizes, function(n_val) {\n  stats <- replicate(n_rep, {\n    x <- rnorm(n_val, mean = 0, sd = 1)\n    t_stat <- mean(x) / (sd(x) / sqrt(n_val))\n    n_val * log(1 + t_stat^2 / (n_val - 1))\n  })\n  tibble(n = n_val, n_label = paste0(\"n = \", n_val), stat = stats)\n})\n\n# Overlay: simulated density vs chi-squared(1) reference\nchi2_ref <- tibble(\n  x = seq(0.01, 10, length.out = 500),\n  y = dchisq(x, df = 1)\n)\n\np_facet <- sim_results |>\n  mutate(n_label = factor(n_label, levels = paste0(\"n = \", sample_sizes))) |>\n  ggplot(aes(x = stat)) +\n  geom_density(aes(color = \"Simulated\"), linewidth = 1.1, key_glyph = \"path\") +\n  geom_line(data = chi2_ref |> crossing(n_label = factor(paste0(\"n = \", sample_sizes), \n            levels = paste0(\"n = \", sample_sizes))),\n            aes(x = x, y = y, color = \"Chi-squared(1)\"), linewidth = 1.1,\n            linetype = \"dashed\", key_glyph = \"path\") +\n  facet_wrap(~n_label) +\n  scale_color_manual(values = c(\"Simulated\" = \"steelblue\", \"Chi-squared(1)\" = \"coral\")) +\n  coord_cartesian(xlim = c(0, 8), ylim = c(0, 1.5)) +\n  labs(x = expression(-2 * ln(Lambda)), y = \"Density\",\n       title = expression(\"Quality of \" * chi^2 * \"(1) Approximation for the t Test LRT\"),\n       subtitle = \"Solid blue = simulated; dashed red = reference. Heavy tails for small n.\",\n       color = NULL) +\n  theme(legend.position = \"bottom\")\n\np_facet\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-12-1.png){width=1344}\n:::\n:::\n\n\n## How Good is the Approximation for Small $n$?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Also show Q-Q plots against chi-squared(1) for each n\np_qq <- sim_results |>\n  mutate(n_label = factor(n_label, levels = paste0(\"n = \", sample_sizes))) |>\n  group_by(n_label) |>\n  slice_sample(n = 2000) |>\n  ungroup() |>\n  ggplot(aes(sample = stat)) +\n  stat_qq(distribution = qchisq, dparams = list(df = 1),\n          color = \"steelblue\", alpha = 0.15, size = 0.7) +\n  geom_abline(slope = 1, intercept = 0, color = \"coral\", \n              linewidth = 1, linetype = \"dashed\") +\n  facet_wrap(~n_label) +\n  coord_cartesian(xlim = c(0, 8), ylim = c(0, 12)) +\n  labs(x = expression(\"Theoretical \" * chi[1]^2 * \" quantiles\"),\n       y = \"Sample quantiles\",\n       title = \"Q-Q Plots Against Chi-squared(1)\",\n       subtitle = \"Departure from diagonal shows approximation error for small n\")\n\np_qq\n```\n\n::: {.cell-output-display}\n![](15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-13-1.png){width=1344}\n:::\n:::\n\n\n# Connecting the Pieces {background-color=\"#2c3e50\"}\n\n## The Big Picture: Hypothesis Testing Framework\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(DiagrammeR)\n\ngrViz(\"\ndigraph testing_framework {\n  graph [rankdir=TB, bgcolor=transparent, fontsize=20]\n  node [shape=box, style=filled, fontsize=16, fontname='Helvetica']\n  \n  # Top level\n  A [label='Hypothesis Testing Problem\\\\nH₀: θ ∈ Ω₀ vs Hₐ: θ ∈ Ωₐ', \n     fillcolor='#3498db', fontcolor=white, width=4]\n  \n  # Decision node\n  B [label='Are both hypotheses simple?', \n     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]\n  \n  # Simple path\n  C [label='Neyman-Pearson Lemma\\\\nLikelihood ratio: L(θₐ)/L(θ₀) ≥ k\\\\nMost Powerful Test', \n     fillcolor='#27ae60', fontcolor=white, width=3.5]\n  \n  # Composite path\n  D [label='Likelihood Ratio Test (LRT)\\\\nΛ = L(θ̂₀) / L(θ̂ₘₗₑ) ≤ k', \n     fillcolor='#8e44ad', fontcolor=white, width=3.5]\n  \n  # UMP\n  E [label='Same rejection region\\\\nfor all θₐ ∈ Ωₐ?', \n     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]\n  F [label='UMP Test\\\\n(one-sided alternatives;\\\\nKarlin-Rubin Theorem)', \n     fillcolor='#27ae60', fontcolor=white, width=3]\n  G [label='No UMP exists\\\\n(two-sided alternatives)\\\\nUse UMP Unbiased or LRT', \n     fillcolor='#e74c3c', fontcolor=white, width=3.5]\n  \n  # LRT outcomes\n  H [label='Exact distribution\\\\nknown?', \n     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]\n  I [label='Use exact test\\\\n(z test, t test, F test)', \n     fillcolor='#27ae60', fontcolor=white, width=3]\n  J [label='Large-sample approx.\\\\n-2ln(Λ) ~ χ²ₘ', \n     fillcolor='#16a085', fontcolor=white, width=3]\n  \n  A -> B\n  B -> C [label='  Yes', fontsize=14]\n  B -> D [label='  No', fontsize=14]\n  C -> E\n  E -> F [label='  Yes', fontsize=14]\n  E -> G [label='  No', fontsize=14]\n  D -> H\n  H -> I [label='  Yes', fontsize=14]\n  H -> J [label='  No', fontsize=14]\n}\n\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-0dd68904c5b7b7947ef7\" style=\"width:1536px;height:768px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0dd68904c5b7b7947ef7\">{\"x\":{\"diagram\":\"\\ndigraph testing_framework {\\n  graph [rankdir=TB, bgcolor=transparent, fontsize=20]\\n  node [shape=box, style=filled, fontsize=16, fontname=\\\"Helvetica\\\"]\\n  \\n  # Top level\\n  A [label=\\\"Hypothesis Testing Problem\\\\nH₀: θ ∈ Ω₀ vs Hₐ: θ ∈ Ωₐ\\\", \\n     fillcolor=\\\"#3498db\\\", fontcolor=white, width=4]\\n  \\n  # Decision node\\n  B [label=\\\"Are both hypotheses simple?\\\", \\n     fillcolor=\\\"#f39c12\\\", fontcolor=white, shape=diamond, width=3]\\n  \\n  # Simple path\\n  C [label=\\\"Neyman-Pearson Lemma\\\\nLikelihood ratio: L(θₐ)/L(θ₀) ≥ k\\\\nMost Powerful Test\\\", \\n     fillcolor=\\\"#27ae60\\\", fontcolor=white, width=3.5]\\n  \\n  # Composite path\\n  D [label=\\\"Likelihood Ratio Test (LRT)\\\\nΛ = L(θ̂₀) / L(θ̂ₘₗₑ) ≤ k\\\", \\n     fillcolor=\\\"#8e44ad\\\", fontcolor=white, width=3.5]\\n  \\n  # UMP\\n  E [label=\\\"Same rejection region\\\\nfor all θₐ ∈ Ωₐ?\\\", \\n     fillcolor=\\\"#f39c12\\\", fontcolor=white, shape=diamond, width=3]\\n  F [label=\\\"UMP Test\\\\n(one-sided alternatives;\\\\nKarlin-Rubin Theorem)\\\", \\n     fillcolor=\\\"#27ae60\\\", fontcolor=white, width=3]\\n  G [label=\\\"No UMP exists\\\\n(two-sided alternatives)\\\\nUse UMP Unbiased or LRT\\\", \\n     fillcolor=\\\"#e74c3c\\\", fontcolor=white, width=3.5]\\n  \\n  # LRT outcomes\\n  H [label=\\\"Exact distribution\\\\nknown?\\\", \\n     fillcolor=\\\"#f39c12\\\", fontcolor=white, shape=diamond, width=3]\\n  I [label=\\\"Use exact test\\\\n(z test, t test, F test)\\\", \\n     fillcolor=\\\"#27ae60\\\", fontcolor=white, width=3]\\n  J [label=\\\"Large-sample approx.\\\\n-2ln(Λ) ~ χ²ₘ\\\", \\n     fillcolor=\\\"#16a085\\\", fontcolor=white, width=3]\\n  \\n  A -> B\\n  B -> C [label=\\\"  Yes\\\", fontsize=14]\\n  B -> D [label=\\\"  No\\\", fontsize=14]\\n  C -> E\\n  E -> F [label=\\\"  Yes\\\", fontsize=14]\\n  E -> G [label=\\\"  No\\\", fontsize=14]\\n  D -> H\\n  H -> I [label=\\\"  Yes\\\", fontsize=14]\\n  H -> J [label=\\\"  No\\\", fontsize=14]\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## Summary: Classical Tests as LRTs\n\n| Test | Hypotheses | LRT Produces | Exact or Approx? |\n|------|-----------|-------------|-------------------|\n| One-sample z | $H_0: \\mu = \\mu_0$, $\\sigma$ known | $z = \\frac{\\bar{x} - \\mu_0}{\\sigma/\\sqrt{n}}$ | Exact |\n| One-sample t | $H_0: \\mu = \\mu_0$, $\\sigma$ unknown | $t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}$ | Exact |\n| Pooled two-sample t | $H_0: \\mu_1 = \\mu_2$, equal $\\sigma$ | Pooled $t$ statistic | Exact |\n| Chi-squared goodness-of-fit | $H_0: p_i = p_{i,0}$ | $\\sum (O_i - E_i)^2/E_i$ | Large-sample |\n| F test (ANOVA) | $H_0: \\mu_1 = \\cdots = \\mu_k$ | $F$ ratio | Exact (normal) |\n\n. . .\n\n::: callout-tip\n## Key Insight\nThe LRT principle is a **unifying framework**. Many of the \"named\" tests from introductory statistics --- z tests, t tests, F tests, chi-squared tests --- can all be derived as likelihood ratio tests. The LRT gives us a principled way to construct new tests for situations not covered by standard formulas.\n:::\n\n## Comparison of Approaches: When to Use What\n\n**Neyman-Pearson Lemma:**\n\n- Applies to **simple vs simple** hypotheses\n- Guarantees **optimality** (most powerful test)\n- Useful for proving that known tests are optimal\n\n. . .\n\n**UMP Tests:**\n\n- Extend NP to **one-sided composite** alternatives\n- Exist mainly for one-parameter exponential families with one-sided alternatives\n- Do **not** exist for two-sided alternatives in general\n\n. . .\n\n**Likelihood Ratio Tests:**\n\n- Apply to **any** testing problem (simple or composite, one or multiple parameters)\n- **General-purpose recipe** that always yields a reasonable test\n- Often coincide with optimal tests when those exist\n- Large-sample $\\chi^2$ approximation makes them practical even when exact distributions are unknown\n\n# Key Takeaways and Looking Ahead {background-color=\"#2c3e50\"}\n\n## Key Takeaways\n\n::: callout-important\n## Today's Main Points\n\n1. **Simple hypotheses** completely specify the distribution; composite hypotheses do not\n2. **Neyman-Pearson Lemma:** the likelihood ratio test $L(\\theta_a)/L(\\theta_0) \\geq k$ is the most powerful test for simple $H_0$ vs simple $H_a$\n3. **Power function** $\\pi(\\theta') = P_{\\theta'}(\\text{Reject } H_0)$ characterizes test performance across all parameter values\n4. **UMP tests** maximize power for *every* alternative; they exist for one-sided tests in exponential families\n5. **Likelihood ratio test** $\\Lambda = L(\\hat{\\theta}_0)/L(\\hat{\\theta}_{mle})$ provides a general recipe for composite hypotheses\n6. **LRT $\\Rightarrow$ classical tests:** the z test and t test are both LRTs\n7. **Wilks' theorem:** $-2\\ln(\\Lambda) \\xrightarrow{d} \\chi^2_m$ provides a large-sample approximation\n:::\n\n. . .\n\n**Common mistakes to avoid:**\n\n- Confusing the NP ratio $L(\\theta_a)/L(\\theta_0)$ (reject when large) with the LRT ratio $L(\\hat{\\theta}_0)/L(\\hat{\\theta}_{mle})$ (reject when small)\n- Assuming UMP tests always exist (they don't for two-sided alternatives)\n- Using the $\\chi^2$ approximation when $n$ is too small\n- Forgetting that the LRT degrees of freedom $m$ count *free* parameters, not total parameters\n\n## Looking Ahead\n\n**Next class (Lesson 16):** Further Aspects of Hypothesis Testing; Bootstrap Hypothesis Testing (Devore 9.6, C&H Chapter 8)\n\n- Statistical vs practical significance\n- Relationship between confidence intervals and hypothesis tests\n- Bootstrap hypothesis testing\n- Permutation tests\n\n## References\n\n::: nonincremental\n-   Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Section 9.5\n-   Chihara and Hesterberg. *Mathematical Statistics with Resampling and R* (Wiley). Section 8.4\n-   Neyman, J. & Pearson, E. S. (1933). On the problem of the most efficient tests of statistical hypotheses. *Philosophical Transactions of the Royal Society A*, 231, 289--337.\n-   Wilks, S. S. (1938). The large-sample distribution of the likelihood ratio for testing composite hypotheses. *The Annals of Mathematical Statistics*, 9(1), 60--62.\n:::\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n\n",
    "supporting": [
      "15_NeymanPearson_LRT_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}