{
  "hash": "f23ee24cab48488778b0a80e7c5c99b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 22: Gauss-Markov Theorem and OLS Theory\"\nsubtitle: \"BSTA 551: Statistical Inference: Bridging Estimation Theory to Linear Regression\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-03-09\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 22 - Gauss-Markov Theorem and OLS Theory\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 22: Gauss-Markov and OLS Theory {background-color=\"#2c3e50\"}\n\n## Where We've Been, and Where We're Going\n\n**Lessons 1–6: Point Estimation Theory**\n\n- Bias, variance, MSE\n- MVUE: minimum variance among **all** unbiased estimators\n- Cramér-Rao Lower Bound, Fisher Information\n- Rao-Blackwell, Lehmann-Scheffé\n\n. . .\n\n**Lessons 7–21:** Confidence intervals, hypothesis testing, bootstrap, nonparametric methods\n\n. . .\n\n**Today:** How does all of that theory connect to **linear regression**, the crux of applied statistics?\n\n::: callout-note\n## Why This Matters\nYour applied courses (regression, GLMs, mixed models) rely fundamentally on the optimality theory we have built. Today we make that connection explicit.\n:::\n\n## Today's Goals\n\n1. Define the **simple linear regression (SLR) model** and the Gauss-Markov assumptions\n2. Derive the **OLS estimators** from the principle of least squares\n3. Prove OLS estimators are **linear** and **unbiased**\n4. Derive their **exact variances**\n5. State and prove the **Gauss-Markov Theorem**: OLS is BLUE\n6. Connect BLUE → **MVUE** under the additional assumption of normality\n7. Simulate to see the theorem in action with a **medical research example**\n\n## Textbook References\n\n| Topic | DBC | Notes |\n|-------|-----|-------|\n| SLR model and OLS derivation | §12.1 | Normal equations, $\\hat\\beta_0$, $\\hat\\beta_1$ |\n| Unbiasedness, $\\text{Var}(\\hat\\beta_1)$ | §12.2 | Properties under GM assumptions |\n| Gauss-Markov Theorem (BLUE) | §12.2 | Stated in DBC, proof here |\n| OLS = MLE under normality | §12.2 | Connects to inference (t-tests) |\n| Weighted least squares | §12.9 | When homoscedasticity fails |\n\n. . .\n\n::: callout-tip\n## Notation\nDBC uses $\\beta_0, \\beta_1$ for the **true** parameters and $\\hat\\beta_0, \\hat\\beta_1$ for the **OLS estimates**.\nWe will use this convention throughout.\n:::\n\n# Part 1: The Simple Linear Regression Model {background-color=\"#8e44ad\"}\n\n## Motivating Example: Gestational Age and Birth Weight\n\nA neonatologist wants to predict **birth weight** (grams) from **gestational age** (weeks) in premature infants.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\nn <- 60\ngest_age   <- runif(n, min = 26, max = 36)\nbirth_wt   <- -3200 + 170 * gest_age + rnorm(n, 0, 120)\n\npreterm <- tibble(gestational_age = gest_age, birth_weight = birth_wt)\n\nggplot(preterm, aes(x = gestational_age, y = birth_weight)) +\n  geom_point(color = \"#2c3e50\", alpha = 0.7, size = 2.5) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#e74c3c\", linewidth = 1.3) +\n  labs(\n    title = \"Birth Weight vs. Gestational Age in Premature Infants\",\n    x = \"Gestational Age (weeks)\",\n    y = \"Birth Weight (grams)\"\n  ) +\n  theme(plot.title = element_text(size = 16))\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n**Question:** What is the \"best\" line through these data, and in what sense is it best?\n\n## The Simple Linear Regression Model\n\n::: callout-important\n## Model (DBC §12.1)\n\n$$Y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i, \\quad i = 1, \\ldots, n$$\n\nwhere:\n\n- $Y_i$ = response (random variable) for the $i$-th observation\n- $x_i$ = predictor value (fixed, non-random), in a **fixed-design** setup\n- $\\beta_0$ = true intercept (unknown parameter)\n- $\\beta_1$ = true slope (unknown parameter)\n- $\\varepsilon_i$ = random error term\n:::\n\n. . .\n\n**Notice:** The $x_i$'s are **not random**; we treat them as known constants.\n\nThis is different from our earlier iid setup! The $Y_i$'s are **independent but not identically distributed**: each has a different mean $\\beta_0 + \\beta_1 x_i$.\n\n## The Gauss-Markov Theorem: Our Destination\n\nBefore examining the assumptions, let's state the theorem we are building toward.\n\n::: callout-important\n## Gauss-Markov Theorem (preview)\n\nUnder four conditions on the error terms $\\varepsilon_i$, the OLS estimators $\\hat\\beta_0$ and $\\hat\\beta_1$ are the **Best Linear Unbiased Estimators** (BLUE) of $\\beta_0$ and $\\beta_1$.\n\nThat is, among all estimators that are (1) linear functions of $Y_1, \\ldots, Y_n$ and (2) unbiased, OLS has the **smallest variance**.\n\n$$\\text{Var}(\\hat\\beta_1^{\\text{OLS}}) \\leq \\text{Var}(\\tilde\\beta_1) \\quad \\text{for every linear unbiased } \\tilde\\beta_1$$\n:::\n\n. . .\n\n**Why does this matter?** This is the regression analog of everything we built in Lessons 1–6: MVUE, CRLB, sufficiency. The four conditions (the **Gauss-Markov assumptions**) are exactly what makes OLS optimal. Understanding them tells you when OLS is trustworthy, and what to do when it is not.\n\n## The Gauss-Markov Assumptions\n\n::: callout-important\n## Gauss-Markov (GM) Assumptions\n\n1. **Linearity:** $E[Y_i] = \\beta_0 + \\beta_1 x_i$ (the mean follows a line)\n2. **Independence:** $\\varepsilon_1, \\ldots, \\varepsilon_n$ are independent\n3. **Zero mean:** $E[\\varepsilon_i] = 0$ for all $i$\n4. **Homoscedasticity:** $\\text{Var}(\\varepsilon_i) = \\sigma^2$ for all $i$ (same variance; **no normality required!**)\n:::\n\n. . .\n\n**Key point:** The Gauss-Markov theorem does **not** require normality.\n\nUnder these four assumptions alone, OLS is BLUE.\n\nUnder the additional assumption $\\varepsilon_i \\stackrel{iid}{\\sim} N(0, \\sigma^2)$, OLS is even stronger: it equals the MLE and is the MVUE, not just BLUE.\n\n## Checking the GM Assumptions in Our Example\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfit <- lm(birth_weight ~ gestational_age, data = preterm)\naug <- augment(fit)\n\np1 <- ggplot(aug, aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.6, color = \"#2c3e50\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Residuals vs. Fitted\",\n    x = expression(hat(Y)[i]),\n    y = expression(hat(epsilon)[i])\n  )\n\np2 <- ggplot(aug, aes(sample = .resid)) +\n  stat_qq(color = \"#2c3e50\", alpha = 0.7) +\n  stat_qq_line(color = \"red\", linetype = \"dashed\") +\n  labs(title = \"Normal Q-Q Plot of Residuals\",\n       x = \"Theoretical Quantiles\", y = \"Sample Quantiles\")\n\np1 + p2 +\n  plot_annotation(title = \"Regression Diagnostics: Birth Weight vs. Gestational Age\")\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nResiduals look scattered around zero with roughly constant spread; the GM assumptions appear reasonable here.\n\n# Part 2: The OLS Estimators: Derivation {background-color=\"#2980b9\"}\n\n## The Principle of Least Squares\n\n**Question:** Given data $(x_1, Y_1), \\ldots, (x_n, Y_n)$, how do we choose $\\hat\\beta_0$ and $\\hat\\beta_1$?\n\n. . .\n\n::: callout-important\n## Principle of Least Squares (DBC §12.1)\n\nChoose $\\hat\\beta_0$ and $\\hat\\beta_1$ to minimize the **residual sum of squares**:\n\n$$\\text{RSS}(\\beta_0, \\beta_1) = \\sum_{i=1}^n \\left(Y_i - \\beta_0 - \\beta_1 x_i\\right)^2$$\n:::\n\n. . .\n\nThis minimizes the total squared vertical distance from each data point to the line.\n\n**Why squares?** Calculus works cleanly; squared deviations penalize large errors more than small ones; connects to maximum likelihood under normality (see later).\n\n## Deriving the OLS Estimates: Normal Equations\n\nTake partial derivatives and set to zero:\n\n$$\\frac{\\partial \\text{RSS}}{\\partial \\beta_0} = -2\\sum_{i=1}^n (Y_i - \\beta_0 - \\beta_1 x_i) = 0$$\n\n$$\\frac{\\partial \\text{RSS}}{\\partial \\beta_1} = -2\\sum_{i=1}^n x_i(Y_i - \\beta_0 - \\beta_1 x_i) = 0$$\n\n. . .\n\nThese simplify to the **normal equations** (DBC §12.1):\n\n$$n\\hat\\beta_0 + \\hat\\beta_1 \\sum x_i = \\sum Y_i$$\n\n$$\\hat\\beta_0 \\sum x_i + \\hat\\beta_1 \\sum x_i^2 = \\sum x_i Y_i$$\n\n## Solving the Normal Equations\n\n**From the first equation:** $\\hat\\beta_0 = \\bar{Y} - \\hat\\beta_1 \\bar{x}$\n\n**Substituting into the second and simplifying:**\n\n$$\\hat\\beta_1 = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})(Y_i - \\bar{Y})}{\\sum_{i=1}^n (x_i - \\bar{x})^2} = \\frac{S_{xy}}{S_{xx}}$$\n\n. . .\n\n::: callout-important\n## OLS Estimators (DBC §12.1)\n\n$$\\hat\\beta_1 = \\frac{S_{xy}}{S_{xx}} = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})(Y_i - \\bar{Y})}{\\sum_{i=1}^n (x_i - \\bar{x})^2}$$\n\n$$\\hat\\beta_0 = \\bar{Y} - \\hat\\beta_1 \\bar{x}$$\n\nwhere $S_{xx} = \\sum(x_i - \\bar x)^2$ and $S_{xy} = \\sum(x_i - \\bar x)(Y_i - \\bar Y)$.\n:::\n\n## Computing OLS in Our Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manual computation of OLS estimators\nx <- preterm$gestational_age\nY <- preterm$birth_weight\n\nx_bar <- mean(x)\nY_bar <- mean(Y)\n\nSxx <- sum((x - x_bar)^2)\nSxy <- sum((x - x_bar) * (Y - Y_bar))\n\nbeta1_hat <- Sxy / Sxx\nbeta0_hat <- Y_bar - beta1_hat * x_bar\n\ncat(\"Manual OLS:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nManual OLS:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  beta0_hat =\", round(beta0_hat, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  beta0_hat = -3181.73 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  beta1_hat =\", round(beta1_hat, 2), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  beta1_hat = 169.88 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Confirm with lm()\nfit <- lm(birth_weight ~ gestational_age, data = preterm)\ntidy(fit) |> select(term, estimate) |> print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term            estimate\n  <chr>              <dbl>\n1 (Intercept)       -3182.\n2 gestational_age     170.\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** Each additional week of gestational age is associated with approximately 169.9 grams of additional birth weight, on average.\n\n## The RSS Surface: A Geometric View\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Create a grid of (beta0, beta1) values and compute RSS at each\nb0_seq <- seq(beta0_hat - 800, beta0_hat + 800, length.out = 60)\nb1_seq <- seq(beta1_hat - 60,  beta1_hat + 60,  length.out = 60)\n\nrss_grid <- expand_grid(b0 = b0_seq, b1 = b1_seq) |>\n  mutate(\n    rss = map2_dbl(b0, b1, \\(b0, b1) sum((Y - b0 - b1 * x)^2))\n  )\n\nggplot(rss_grid, aes(x = b0, y = b1, z = rss)) +\n  geom_contour_filled(bins = 18, alpha = 0.85) +\n  geom_point(\n    aes(x = beta0_hat, y = beta1_hat),\n    inherit.aes = FALSE,\n    color = \"red\", size = 4, shape = 8, stroke = 2\n  ) +\n  labs(\n    title = expression(\"RSS Surface: \" * hat(beta)[0] * \" and \" * hat(beta)[1] * \" minimize RSS\"),\n    x = expression(beta[0]),\n    y = expression(beta[1]),\n    fill = \"RSS\"\n  ) +\n  scale_fill_viridis_d(option = \"plasma\") +\n  annotate(\"text\", x = beta0_hat + 300, y = beta1_hat + 20,\n           label = \"OLS minimum\", color = \"red\", size = 5)\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\nThe OLS solution is at the **unique global minimum** of the convex RSS surface.\n\n# Part 3: Properties of OLS Estimators {background-color=\"#16a085\"}\n\n## Step 1: OLS Estimators Are Linear in $Y$\n\n**Key rewrite:** The slope estimator can be written as a linear combination of the $Y_i$'s:\n\n$$\\hat\\beta_1 = \\frac{S_{xy}}{S_{xx}} = \\frac{\\sum(x_i - \\bar x)(Y_i - \\bar Y)}{S_{xx}} = \\sum_{i=1}^n c_i Y_i$$\n\nwhere $c_i = \\dfrac{x_i - \\bar x}{S_{xx}}$ are **fixed constants** (they depend only on the $x_i$'s, not on the $Y_i$'s).\n\n. . .\n\nSimilarly, $\\hat\\beta_0 = \\bar{Y} - \\hat\\beta_1 \\bar{x} = \\sum_{i=1}^n d_i Y_i$ where $d_i = \\frac{1}{n} - c_i \\bar x$.\n\n. . .\n\n::: callout-note\n## Definition: Linear Estimator\nAn estimator $\\tilde\\beta$ is **linear** if it can be written as $\\tilde\\beta = \\sum_{i=1}^n a_i Y_i$ for some constants $a_i$ that depend only on the $x_i$'s.\n\nOLS estimators satisfy this definition; they are **linear estimators**.\n:::\n\n## Step 2: OLS Estimators Are Unbiased\n\nBoth $\\hat\\beta_0$ and $\\hat\\beta_1$ are **unbiased estimators** of $\\beta_0$ and $\\beta_1$, respectively, under the GM assumptions.\n\n**For $\\hat\\beta_1$:** Since $\\hat\\beta_1 = \\sum c_i Y_i$ and $E[Y_i] = \\beta_0 + \\beta_1 x_i$:\n\n$$E[\\hat\\beta_1] = E\\left[\\sum c_i Y_i\\right] = \\sum c_i E[Y_i] = \\sum c_i (\\beta_0 + \\beta_1 x_i)$$\n\n$$= \\beta_0 \\underbrace{\\sum c_i}_{=0} + \\beta_1 \\underbrace{\\sum c_i x_i}_{=1} = \\beta_1 \\checkmark$$\n\n. . .\n\nThe two facts that make this work, for $c_i = (x_i - \\bar x)/S_{xx}$:\n\n$$\\sum_{i=1}^n c_i = \\frac{\\sum(x_i - \\bar x)}{S_{xx}} = \\frac{0}{S_{xx}} = 0$$\n\nbecause deviations from the mean always sum to zero.\n\n$$\\sum_{i=1}^n c_i x_i = \\frac{\\sum(x_i - \\bar x)x_i}{S_{xx}} = \\frac{\\sum(x_i - \\bar x)(x_i - \\bar x) + \\bar x \\sum(x_i - \\bar x)}{S_{xx}} = \\frac{S_{xx} + 0}{S_{xx}} = 1$$\n\nbecause $\\sum(x_i - \\bar x)x_i = \\sum(x_i - \\bar x)^2 = S_{xx}$.\n\n. . .\n\n**For $\\hat\\beta_0$:** $E[\\hat\\beta_0] = E[\\bar Y] - \\hat\\beta_1 \\bar x = (\\beta_0 + \\beta_1 \\bar x) - \\beta_1 \\bar x = \\beta_0 \\checkmark$\n\n## Step 3: Exact Variances of OLS Estimators\n\nUnder the GM assumptions ($\\varepsilon_i$ independent with $\\text{Var}(\\varepsilon_i) = \\sigma^2$):\n\n$$\\text{Var}(\\hat\\beta_1) = \\text{Var}\\left(\\sum c_i Y_i\\right) = \\sum c_i^2 \\text{Var}(Y_i) = \\sigma^2 \\sum c_i^2 = \\frac{\\sigma^2}{S_{xx}}$$\n\nsince $\\sum c_i^2 = \\sum \\dfrac{(x_i - \\bar x)^2}{S_{xx}^2} = \\dfrac{S_{xx}}{S_{xx}^2} = \\dfrac{1}{S_{xx}}$.\n\n. . .\n\n::: callout-important\n## Variance Formulas (DBC §12.2)\n\n$$\\text{Var}(\\hat\\beta_1) = \\frac{\\sigma^2}{S_{xx}}$$\n\n$$\\text{Var}(\\hat\\beta_0) = \\sigma^2 \\left(\\frac{1}{n} + \\frac{\\bar x^2}{S_{xx}}\\right)$$\n\n$$\\text{Cov}(\\hat\\beta_0, \\hat\\beta_1) = -\\frac{\\sigma^2 \\bar x}{S_{xx}}$$\n:::\n\n## Intuition: What Drives Variance of $\\hat\\beta_1$?\n\n$$\\text{Var}(\\hat\\beta_1) = \\frac{\\sigma^2}{S_{xx}} = \\frac{\\sigma^2}{\\sum(x_i - \\bar x)^2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(42)\nn_pts <- 30\nsigma2 <- 100^2\nbeta0_true <- -3200; beta1_true <- 170\n\n# Low spread in x\nx_low  <- seq(30, 32, length.out = n_pts)\n# High spread in x\nx_high <- seq(26, 36, length.out = n_pts)\n\nSxx_low  <- sum((x_low  - mean(x_low))^2)\nSxx_high <- sum((x_high - mean(x_high))^2)\n\nsimulate_slope <- function(x_vals, n_sim = 2000) {\n  replicate(n_sim, {\n    Y <- beta0_true + beta1_true * x_vals + rnorm(length(x_vals), 0, sqrt(sigma2))\n    coef(lm(Y ~ x_vals))[2]\n  })\n}\n\nslopes_low  <- simulate_slope(x_low)\nslopes_high <- simulate_slope(x_high)\n\ntibble(\n  slope = c(slopes_low, slopes_high),\n  Design = rep(c(\"Sxx small\", \"Sxx large\"),\n               each = 2000)\n) |>\n  ggplot(aes(x = slope, fill = Design)) +\n  geom_histogram(bins = 45, alpha = 0.65, position = \"identity\") +\n  geom_vline(xintercept = beta1_true, color = \"black\", linetype = \"dashed\",\n             linewidth = 1.2) +\n  scale_fill_manual(values = c(\"Sxx small\" = \"tomato\",\n                               \"Sxx large\" = \"steelblue\")) +\n  labs(\n    title = expression(\"Variance of \" * hat(beta)[1] * \" depends on spread of x values\"),\n    subtitle = bquote(Var(hat(beta)[1]) == sigma^2 / S[xx]),\n    x = expression(hat(beta)[1]),\n    y = \"Count\",\n    fill = \"Design\"\n  ) +\n  annotate(\"text\", x = beta1_true + 3, y = 250, label = expression(beta[1] == 170),\n           size = 5) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n**Lesson for study design:** Spread your predictor values out to get a more precise slope estimate!\n\n# Part 4: The Gauss-Markov Theorem {background-color=\"#c0392b\"}\n\n## Statement of the Gauss-Markov Theorem\n\n::: callout-important\n## Gauss-Markov Theorem (DBC §12.2)\n\nUnder the four Gauss-Markov assumptions (linearity, independence, zero-mean errors, homoscedasticity), the OLS estimators $\\hat\\beta_0$ and $\\hat\\beta_1$ are the **Best Linear Unbiased Estimators** (BLUE) of $\\beta_0$ and $\\beta_1$.\n\nThat is, among all estimators of the form $\\tilde\\beta_1 = \\sum a_i Y_i$ that satisfy $E[\\tilde\\beta_1] = \\beta_1$:\n\n$$\\text{Var}(\\hat\\beta_1) \\leq \\text{Var}(\\tilde\\beta_1)$$\n\nwith equality iff $\\tilde\\beta_1 = \\hat\\beta_1$.\n:::\n\n. . .\n\n**Unpacking \"BLUE\":**\n\n- **B**est = smallest variance among the class considered\n- **L**inear = estimator is a linear function of the $Y_i$'s\n- **U**nbiased = $E[\\tilde\\beta] = \\beta$ for all $\\beta_0, \\beta_1, \\sigma^2$\n- **E**stimator = a function of the observed data\n\n## Proof: Gauss-Markov for $\\hat\\beta_1$ {.smaller}\n\n**Setup:** Let $\\tilde\\beta_1 = \\sum a_i Y_i$ be any linear unbiased estimator of $\\beta_1$, where the $a_i$'s are constants.\n\n**Unbiasedness constraint:**\n\n$$E[\\tilde\\beta_1] = \\sum a_i E[Y_i] = \\sum a_i(\\beta_0 + \\beta_1 x_i) = \\beta_0 \\sum a_i + \\beta_1 \\sum a_i x_i = \\beta_1$$\n\nThis must hold for all $\\beta_0$ and $\\beta_1$, so: $\\quad \\sum a_i = 0 \\quad$ and $\\quad \\sum a_i x_i = 1$.\n\n. . .\n\n**Write $a_i = c_i + e_i$** where $c_i = (x_i - \\bar x)/S_{xx}$ are the OLS weights and $e_i = a_i - c_i$.\n\nThe constraints $\\sum a_i = 0$ and $\\sum a_i x_i = 1$ imply $\\sum e_i = 0$ and $\\sum e_i x_i = 0$.\n\n. . .\n\n**Variance of $\\tilde\\beta_1$:**\n\n$$\\text{Var}(\\tilde\\beta_1) = \\sigma^2 \\sum a_i^2 = \\sigma^2 \\sum (c_i + e_i)^2 = \\sigma^2\\left(\\sum c_i^2 + 2\\sum c_i e_i + \\sum e_i^2\\right)$$\n\nSince $\\sum c_i e_i = \\frac{1}{S_{xx}}\\sum(x_i - \\bar x)e_i = \\frac{1}{S_{xx}}\\left(\\sum x_i e_i - \\bar x \\sum e_i\\right) = 0$, we get:\n\n$$\\text{Var}(\\tilde\\beta_1) = \\underbrace{\\frac{\\sigma^2}{S_{xx}}}_{\\text{Var}(\\hat\\beta_1)} + \\underbrace{\\sigma^2 \\sum e_i^2}_{\\geq 0} \\geq \\text{Var}(\\hat\\beta_1) \\quad \\checkmark$$\n\n## The BLUE Hierarchy: Connecting to MVUE\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-82f080207f5d5dadffcf\" style=\"width:960px;height:576px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-82f080207f5d5dadffcf\">{\"x\":{\"diagram\":\"\\ndigraph BLUE_MVUE {\\n  graph [rankdir = TB, bgcolor = transparent, splines = ortho]\\n  node [shape = box, style = filled, fontsize = 14, width = 3.5]\\n\\n  All   [label = \\\"All Unbiased Estimators\\\\n(includes nonlinear functions of Y)\\\", \\n          fillcolor = \\\"#F5B7B1\\\"]\\n  Lin   [label = \\\"Linear Unbiased Estimators\\\\n(tildeβ = Σ aᵢYᵢ, E[tildeβ] = β)\\\", \\n          fillcolor = \\\"#FAD7A0\\\"]\\n  OLS   [label = \\\"OLS: Best Linear Unbiased (BLUE)\\\\nGauss-Markov: smallest Var among linear UEs\\\", \\n          fillcolor = \\\"#ABEBC6\\\"]\\n  MVUE  [label = \\\"MVUE (under normality)\\\\nOLS = MLE = BLUE = MVUE\\\", \\n          fillcolor = \\\"#AED6F1\\\"]\\n\\n  All  -> Lin  [label = \\\"restrict to\\\\nlinear estimators\\\"]\\n  Lin  -> OLS  [label = \\\"Gauss-Markov\\\\nTheorem\\\"]\\n  OLS  -> MVUE [label = \\\"Add normality:\\\\nε ~ N(0,σ²)\\\", style = dashed]\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n. . .\n\n- **Gauss-Markov (no normality needed):** OLS is BLUE — smallest variance among all linear unbiased estimators\n- **Add normality:** two independent arguments both conclude OLS is MVUE — see next slide\n\n## From BLUE to MVUE: Two Routes Under Normality\n\nAdding $\\varepsilon_i \\stackrel{iid}{\\sim} N(0,\\sigma^2)$ unlocks two separate arguments, each concluding OLS is the MVUE.\n\n. . .\n\n::: callout-important\n## Route 1: Lehmann-Scheffé\n\nUnder the normal SLR model, $(\\hat\\beta_0, \\hat\\beta_1, S^2)$ is a **complete sufficient statistic** for $(\\beta_0, \\beta_1, \\sigma^2)$.\n\n$\\hat\\beta_1$ is an **unbiased function** of that complete sufficient statistic.\n\nTherefore, by the Lehmann-Scheffé theorem, $\\hat\\beta_1$ is the **unique MVUE** of $\\beta_1$.\n\nThe CRLB plays no role in this argument — it follows from completeness and sufficiency alone.\n:::\n\n. . .\n\n::: callout-important\n## Route 2: CRLB / Efficiency\n\nThe normal SLR model belongs to the **exponential family**. For exponential family models, the MLE achieves the Cramér-Rao Lower Bound **exactly** (not just asymptotically).\n\nSince OLS = MLE under normality (shown in Part 5), and $\\text{Var}(\\hat\\beta_1) = \\sigma^2/S_{xx}$ equals the CRLB:\n\n$$\\text{Var}(\\hat\\beta_1) = \\frac{\\sigma^2}{S_{xx}} = \\text{CRLB for } \\beta_1$$\n\nAn unbiased estimator that achieves the CRLB is, by definition, the MVUE.\n:::\n\n. . .\n\nThese are parallel routes to the same destination. Lehmann-Scheffé works via the structure of the sufficient statistic; the CRLB route works via the information bound. Both require normality.\n\n## What BLUE Does Not Say\n\n::: callout-warning\n## Common Misconceptions\n\n**BLUE does not mean:**\n\n- OLS has the smallest variance among **all** estimators (biased or not): weighted least squares (WLS) or ridge regression can have smaller MSE\n- OLS is optimal when GM assumptions are **violated**: heteroscedasticity calls for WLS; dependence calls for generalized least squares (GLS)\n- The model is **correct**: OLS is BLUE for the stated model, regardless of whether the model fits the data well\n\n**BLUE does mean:**\n\n- Within the class of **linear, unbiased** estimators, OLS cannot be beaten\n- This is a remarkable, assumption-lean result: no distributional assumption on $\\varepsilon_i$ beyond mean 0 and constant variance\n:::\n\n# Part 5: OLS = MLE Under Normality {background-color=\"#2c3e50\"}\n\n## The Normal Simple Linear Regression Model\n\nAdd one assumption to the GM setup:\n\n$$\\varepsilon_i \\stackrel{iid}{\\sim} N(0, \\sigma^2)$$\n\nThis implies:\n$$Y_i \\stackrel{\\text{indep}}{\\sim} N(\\beta_0 + \\beta_1 x_i, \\; \\sigma^2)$$\n\n. . .\n\nThe joint likelihood is:\n\n$$L(\\beta_0, \\beta_1, \\sigma^2) = \\prod_{i=1}^n \\frac{1}{\\sqrt{2\\pi\\sigma^2}} \\exp\\!\\left\\{-\\frac{(Y_i - \\beta_0 - \\beta_1 x_i)^2}{2\\sigma^2}\\right\\}$$\n\n$$= \\left(\\frac{1}{2\\pi\\sigma^2}\\right)^{n/2} \\exp\\!\\left\\{-\\frac{1}{2\\sigma^2}\\sum_{i=1}^n (Y_i - \\beta_0 - \\beta_1 x_i)^2\\right\\}$$\n\n## Maximizing the Likelihood\n\nThe log-likelihood is:\n\n$$\\ell(\\beta_0, \\beta_1, \\sigma^2) = -\\frac{n}{2}\\log(2\\pi\\sigma^2) - \\frac{1}{2\\sigma^2}\\sum_{i=1}^n (Y_i - \\beta_0 - \\beta_1 x_i)^2$$\n\n. . .\n\n**Key observation:** For fixed $\\sigma^2$, maximizing $\\ell$ with respect to $\\beta_0$ and $\\beta_1$ is **equivalent to minimizing**:\n\n$$\\sum_{i=1}^n (Y_i - \\beta_0 - \\beta_1 x_i)^2 = \\text{RSS}$$\n\n. . .\n\n::: callout-important\n## OLS = MLE Under Normality\n\nThe OLS estimators $\\hat\\beta_0^{\\text{OLS}}$ and $\\hat\\beta_1^{\\text{OLS}}$ are **identical** to the MLE estimators $\\hat\\beta_0^{\\text{MLE}}$ and $\\hat\\beta_1^{\\text{MLE}}$.\n:::\n\nThis is why we can use $t$-tests and $F$-tests in normal linear regression; the distributional framework that enables inference comes from normality + OLS = MLE.\n\n## From BLUE to MVUE: The Full Chain {.smaller}\n\nUnder the normal SLR model ($\\varepsilon_i \\stackrel{iid}{\\sim} N(0,\\sigma^2)$):\n\n| Property | Justification |\n|----------|---------------|\n| $\\hat\\beta_1$ is linear | By construction: $\\hat\\beta_1 = \\sum c_i Y_i$ |\n| $\\hat\\beta_1$ is unbiased | Shown above (only needs GM assumptions) |\n| $\\hat\\beta_1$ is BLUE | Gauss-Markov Theorem (only needs GM assumptions) |\n| $\\hat\\beta_1$ is sufficient | $(\\hat\\beta_0, \\hat\\beta_1, S^2)$ is sufficient for $(\\beta_0, \\beta_1, \\sigma^2)$ under normality |\n| $\\hat\\beta_1$ is the MLE | OLS = MLE under normality (shown above) |\n| $\\hat\\beta_1$ is the MVUE | Lehmann-Scheffé: complete sufficient statistic + unbiased |\n| $\\hat\\beta_1$ achieves CRLB | MLE achieves CRLB asymptotically; exactly for exponential family |\n\n. . .\n\n::: callout-note\n## The Big Picture\nThis is precisely the situation we studied with scalar parameters: the MLE of an exponential family parameter based on the sufficient statistic is unbiased, complete, and achieves the CRLB. The normal SLR model is an exponential family model, and OLS produces the sufficient statistics.\n:::\n\n## Connecting to the CRLB\n\nUnder normal SLR, the Fisher information matrix for $(\\beta_0, \\beta_1)$ gives:\n\n$$\\text{CRLB for } \\beta_1 = \\frac{\\sigma^2}{S_{xx}} = \\text{Var}(\\hat\\beta_1^{\\text{OLS}})$$\n\n$$\\text{CRLB for } \\beta_0 = \\sigma^2\\!\\left(\\frac{1}{n} + \\frac{\\bar x^2}{S_{xx}}\\right) = \\text{Var}(\\hat\\beta_0^{\\text{OLS}})$$\n\n. . .\n\nOLS estimators **achieve the Cramér-Rao Lower Bound**; they are **efficient** unbiased estimators.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify: compare theoretical variance to simulation variance\nsigma <- 120\nSxx_val <- Sxx\n\ncat(\"Theoretical Var(beta1_hat) =\", round(sigma^2 / Sxx_val, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTheoretical Var(beta1_hat) = 25.1581 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Simulated  Var(beta1_hat) =\", round(var(slopes_high), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimulated  Var(beta1_hat) = 36.8917 \n```\n\n\n:::\n:::\n\n\n# Part 6: R Simulation: Verifying Gauss-Markov {background-color=\"#27ae60\"}\n\n## Comparing OLS to Alternative Linear Estimators\n\nThe GM theorem says OLS beats every other linear unbiased estimator. Let's verify with a simulation.\n\n**Setting:** Same premature infant model: $Y_i = -3200 + 170 x_i + \\varepsilon_i$, $\\varepsilon_i \\sim N(0, 120^2)$\n\n**Competitors:**\n\n1. **OLS:** $\\hat\\beta_1 = S_{xy}/S_{xx}$ (the Gauss-Markov champion)\n2. **Naïve two-point slope:** Use only the first and last observation: $\\tilde\\beta_1^{(2)} = (Y_n - Y_1)/(x_n - x_1)$\n3. **Trimmed OLS:** Drop middle third of observations, apply OLS to rest\n4. **Unweighted mean of slopes:** Average of all pairwise slopes (all pairs $i < j$)\n\nAll four are linear in $Y$ and unbiased, but only OLS is BLUE.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\nn_sim <- 5000\nx_fixed <- sort(preterm$gestational_age)\nn <- length(x_fixed)\nbeta0_true <- -3200; beta1_true <- 170; sigma <- 120\n\nsimulate_estimators <- function(x_vals, n_sim, beta0, beta1, sigma) {\n  replicate(n_sim, {\n    Y <- beta0 + beta1 * x_vals + rnorm(length(x_vals), 0, sigma)\n    n  <- length(x_vals)\n    \n    # OLS slope\n    ols <- coef(lm(Y ~ x_vals))[2]\n    \n    # Two-point slope: first and last observation\n    two_pt <- (Y[n] - Y[1]) / (x_vals[n] - x_vals[1])\n    \n    # Trimmed OLS: drop middle third\n    keep <- c(1:floor(n/3), ceiling(2*n/3):n)\n    trimmed <- coef(lm(Y[keep] ~ x_vals[keep]))[2]\n    \n    # Mean of all pairwise slopes\n    pairs_i <- rep(1:(n-1), times = (n-1):1)\n    pairs_j <- unlist(lapply(2:n, \\(j) j:n))\n    pairwise_slopes <- (Y[pairs_j] - Y[pairs_i]) / (x_vals[pairs_j] - x_vals[pairs_i])\n    pairwise_mean <- mean(pairwise_slopes)\n    \n    c(ols = as.numeric(ols), two_pt = two_pt, trimmed = as.numeric(trimmed), pairwise = pairwise_mean)\n  }) |> t() |> as_tibble()\n}\n\nsim_results <- simulate_estimators(x_fixed, n_sim, beta0_true, beta1_true, sigma)\n```\n:::\n\n\n## Simulation Results: OLS Wins\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsim_results |>\n  pivot_longer(everything(),\n               names_to = \"Estimator\",\n               values_to = \"slope_hat\") |>\n  mutate(Estimator = recode(Estimator,\n    ols       = \"OLS (BLUE)\",\n    two_pt    = \"Naive Two-point\",\n    trimmed   = \"Trimmed OLS\",\n    pairwise  = \"Mean pairwise slopes\"\n  )) |>\n  ggplot(aes(x = slope_hat, fill = Estimator)) +\n  geom_density(alpha = 0.55, color = \"white\") +\n  geom_vline(xintercept = beta1_true, linetype = \"dashed\",\n             color = \"black\", linewidth = 1.2) +\n  scale_fill_manual(values = c(\"#e74c3c\", \"#3498db\", \"#2ecc71\", \"#f39c12\")) +\n  facet_wrap(~Estimator, ncol = 2, scales = \"free_y\") +\n  labs(\n    title = expression(\"Sampling Distributions of Four Linear Unbiased Estimators of \" * beta[1]),\n    subtitle = bquote(\"True \" * beta[1] == 170 * \" (dashed line); OLS has smallest variance\"),\n    x = expression(hat(beta)[1]),\n    y = \"Density\"\n  ) +\n  theme(legend.position = \"none\", strip.text = element_text(size = 13))\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Summarizing the Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsim_summary <- sim_results |>\n  summarise(across(everything(), list(Mean = mean, Variance = var, SD = sd))) |>\n  pivot_longer(everything()) |>\n  separate(name, into = c(\"Estimator\", \"Statistic\"), sep = \"_(?=[^_]+$)\") |>\n  mutate(value = round(value, 4)) |>\n  pivot_wider(names_from = Statistic, values_from = value) |>\n  mutate(\n    Estimator = recode(Estimator,\n      ols      = \"OLS (BLUE)\",\n      two_pt   = \"Two-point\",\n      trimmed  = \"Trimmed OLS\",\n      pairwise = \"Mean pairwise\"\n    ),\n    `Relative Efficiency` = round(min(Variance) / Variance, 3)\n  )\n\nsim_summary |>\n  arrange(Variance) |>\n  knitr::kable(digits = 4,\n               caption = \"Comparison of Linear Unbiased Estimators (5,000 simulations)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Linear Unbiased Estimators (5,000 simulations)\n\n|Estimator     |     Mean|  Variance|      SD| Relative Efficiency|\n|:-------------|--------:|---------:|-------:|-------------------:|\n|OLS (BLUE)    | 169.9583|   25.4524|  5.0450|               1.000|\n|Trimmed OLS   | 169.9690|   27.3717|  5.2318|               0.930|\n|Two-point     | 169.8514|  312.1433| 17.6676|               0.082|\n|Mean pairwise | 169.8039| 1062.4175| 32.5947|               0.024|\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation of relative efficiency:** The ratio of OLS variance to each competitor's variance; OLS (efficiency = 1.0) is the benchmark.\n\n# Part 7: Estimation of $\\sigma^2$ and Inference {background-color=\"#8e44ad\"}\n\n## Estimating the Error Variance $\\sigma^2$\n\nThe GM assumptions include an unknown error variance $\\sigma^2$. We need to estimate it for inference.\n\n**Residuals:** $\\hat\\varepsilon_i = Y_i - \\hat\\beta_0 - \\hat\\beta_1 x_i = Y_i - \\hat{Y}_i$\n\n. . .\n\n::: callout-important\n## Unbiased Estimator of $\\sigma^2$ (DBC §12.2)\n\n$$\\hat\\sigma^2 = S^2 = \\frac{\\text{RSS}}{n-2} = \\frac{\\sum_{i=1}^n (Y_i - \\hat\\beta_0 - \\hat\\beta_1 x_i)^2}{n-2}$$\n\n$E[S^2] = \\sigma^2$. Why $n - 2$? We lose 2 degrees of freedom because we estimate 2 parameters.\n:::\n\n. . .\n\nUnder normality: $\\dfrac{(n-2)S^2}{\\sigma^2} \\sim \\chi^2_{n-2}$, independent of $\\hat\\beta_0$ and $\\hat\\beta_1$.\n\nThis is the direct analog of how $S^2$ worked in one-sample inference: the distribution changes because the number of estimated parameters changes.\n\n## Standard Errors and t-Based Inference\n\nReplacing $\\sigma^2$ with $S^2$ gives estimated standard errors:\n\n$$\\widehat{\\text{SE}}(\\hat\\beta_1) = \\frac{S}{\\sqrt{S_{xx}}} \\qquad \\widehat{\\text{SE}}(\\hat\\beta_0) = S\\sqrt{\\frac{1}{n} + \\frac{\\bar x^2}{S_{xx}}}$$\n\n. . .\n\nUnder normality, the pivot statistics follow $t$ distributions:\n\n$$T_1 = \\frac{\\hat\\beta_1 - \\beta_1}{S/\\sqrt{S_{xx}}} \\sim t_{n-2} \\qquad T_0 = \\frac{\\hat\\beta_0 - \\beta_0}{S\\sqrt{1/n + \\bar x^2/S_{xx}}} \\sim t_{n-2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standard errors in our example\nfit_summary <- summary(fit)\ncat(\"sigma_hat (S) =\", round(fit_summary$sigma, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsigma_hat (S) = 136.42 \n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(fit) |> select(term, estimate, std.error, statistic, p.value) |> \n  mutate(p.value = scales::pvalue_format(0.0001)(p.value), across(where(is.numeric), \\(x) round(x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term            estimate std.error statistic p.value\n  <chr>              <dbl>     <dbl>     <dbl> <chr>  \n1 (Intercept)       -3182.    177.       -17.9 <0.0001\n2 gestational_age     170.      5.70      29.8 <0.0001\n```\n\n\n:::\n:::\n\n\n## Prediction and the Fitted Line\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nnew_ages <- tibble(gestational_age = seq(26, 36, by = 0.5))\npred_ci   <- predict(fit, newdata = new_ages, interval = \"confidence\") |> as_tibble()\npred_pi   <- predict(fit, newdata = new_ages, interval = \"prediction\") |> as_tibble()\n\nplot_data <- bind_cols(new_ages, pred_ci) |>\n  rename(conf_lwr = lwr, conf_upr = upr) |>\n  mutate(pred_lwr = pred_pi$lwr, pred_upr = pred_pi$upr)\n\nggplot() +\n  geom_ribbon(data = plot_data,\n              aes(x = gestational_age, ymin = pred_lwr, ymax = pred_upr, fill = \"95% PI\"),\n              alpha = 0.15) +\n  geom_ribbon(data = plot_data,\n              aes(x = gestational_age, ymin = conf_lwr, ymax = conf_upr, fill = \"95% CI for mean\"),\n              alpha = 0.35) +\n  geom_line(data = plot_data, aes(x = gestational_age, y = fit), color = \"#c0392b\", linewidth = 1.3) +\n  geom_point(data = preterm, aes(x = gestational_age, y = birth_weight),\n             color = \"#2c3e50\", alpha = 0.65, size = 2) +\n  scale_fill_manual(values = c(\"95% CI for mean\" = \"steelblue\", \"95% PI\" = \"orange\"),\n                    name = \"Interval\") +\n  labs(\n    title = \"Birth Weight vs. Gestational Age: Fitted Line with Uncertainty Bands\",\n    subtitle = expression(\"CI for \" * E*\"[Y | x], PI for an individual future Y\"),\n    x = \"Gestational Age (weeks)\", y = \"Birth Weight (grams)\"\n  ) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n# Part 8: When Gauss-Markov Fails {background-color=\"#e67e22\"}\n\n## Violation: Heteroscedasticity\n\nIf $\\text{Var}(\\varepsilon_i) = \\sigma_i^2$ (not constant), OLS is still **unbiased** but is no longer BLUE.\n\n**Example:** In a study of drug dosage and response, variance in response may increase with dose.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(42)\nx_dose <- seq(1, 10, length.out = 80)\ny_response <- 2 + 1.5 * x_dose + rnorm(80, 0, sd = 0.4 * x_dose)\nhetero_data <- tibble(dose = x_dose, response = y_response)\n\nggplot(hetero_data, aes(x = dose, y = response)) +\n  geom_point(alpha = 0.6, color = \"#2c3e50\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#e74c3c\") +\n  labs(\n    title = expression(\"Heteroscedasticity: \" * Var(epsilon[i]) * \" grows with dose\"),\n    x = \"Drug Dose (mg/kg)\", y = \"Biomarker Response\"\n  )\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n**Fix: Weighted Least Squares (WLS)** minimizes $\\sum w_i (Y_i - \\beta_0 - \\beta_1 x_i)^2$ where $w_i \\propto 1/\\sigma_i^2$, down-weighting observations with higher variance.\n\nWeighted least squares is BLUE when weights are correctly specified. This is DBC §12.9.\n\n## Summary: The Hierarchy of OLS Optimality\n\n| Assumption Set | OLS Property |\n|----------------|-------------|\n| GM 1–4 (linearity, independence, $E[\\varepsilon_i]=0$, homoscedasticity) | **BLUE**: best among linear unbiased estimators |\n| GM 1–4 + normality ($\\varepsilon_i \\sim N(0,\\sigma^2)$) | **MVUE**: best among **all** unbiased estimators |\n| GM 1–4 + normality | **MLE**: OLS and MLE coincide |\n| GM 1–4 + normality | **Achieves CRLB**: efficient |\n| Homoscedasticity violated | OLS unbiased, but not BLUE; use weighted least squares (WLS) |\n| Independence violated | OLS unbiased, but not BLUE; use generalized least squares (GLS) |\n\n. . .\n\n::: callout-tip\n## The Takeaway for Applied Regression\nWhen you check regression diagnostics (residual plots, Q-Q plots, leverage), you are **verifying the GM assumptions** that justify the optimality of OLS. If they fail, you need a different estimator.\n:::\n\n# Part 9: Extended Example from DBC {background-color=\"#2c3e50\"}\n\n## DBC Example 12.7: Tensile Strength and Percentage Cotton\n\nFrom DBC §12.1–12.2: Tensile strength (psi) of synthetic fiber as a function of percentage of cotton in the fiber.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# DBC Table 12.1: cotton content and tensile strength\ncotton <- tibble(\n  pct_cotton   = c(15, 15, 15, 15, 20, 20, 20, 20, 25, 25,\n                   25, 25, 30, 30, 30, 30, 35, 35, 35, 35),\n  tensile_str  = c(7, 7, 15, 11, 12, 17, 12, 18, 14, 18,\n                   18, 19, 19, 25, 22, 19, 7, 10, 11, 15)\n)\n\n# Fit OLS\nfit_cotton <- lm(tensile_str ~ pct_cotton, data = cotton)\n\n# Manual OLS components\nx_c  <- cotton$pct_cotton\nY_c  <- cotton$tensile_str\nSxx_c <- sum((x_c - mean(x_c))^2)\nSxy_c <- sum((x_c - mean(x_c)) * (Y_c - mean(Y_c)))\n\ncat(\"Sxx =\", Sxx_c, \"  Sxy =\", Sxy_c, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSxx = 1000   Sxy = 160 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"beta1_hat =\", round(Sxy_c / Sxx_c, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta1_hat = 0.16 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"beta0_hat =\", round(mean(Y_c) - (Sxy_c/Sxx_c) * mean(x_c), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta0_hat = 10.8 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"Theoretical Var(beta1_hat) / sigma^2 =\", round(1 / Sxx_c, 6), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTheoretical Var(beta1_hat) / sigma^2 = 0.001 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(fit_cotton) |> select(term, estimate, std.error, statistic, p.value) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)    10.8      4.20      2.57   0.0191\n2 pct_cotton      0.16     0.162     0.991  0.335 \n```\n\n\n:::\n:::\n\n\n## DBC Example 12.7: Plot\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(cotton, aes(x = pct_cotton, y = tensile_str)) +\n  geom_point(size = 3, color = \"#2c3e50\", alpha = 0.8) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#c0392b\", linewidth = 1.2) +\n  labs(\n    title = \"DBC Example 12.7: Tensile Strength vs. Cotton Content\",\n    subtitle = bquote(hat(beta)[1] == .(round(Sxy_c / Sxx_c, 3)) ~\n                        \" psi per % cotton (OLS = BLUE = MLE)\"),\n    x = \"Percentage Cotton\",\n    y = \"Tensile Strength (psi)\"\n  )\n```\n\n::: {.cell-output-display}\n![](22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nThe positive slope $\\hat\\beta_1 \\approx$ 0.16 is the **BLUE** of the true slope. Under normality, it also achieves the CRLB and is the MVUE.\n\n# Summary {background-color=\"#006a4e\"}\n\n## What We Proved Today\n\n::: callout-important\n## Key Results\n\n1. **OLS estimators** $\\hat\\beta_0 = \\bar Y - \\hat\\beta_1 \\bar x$ and $\\hat\\beta_1 = S_{xy}/S_{xx}$ minimize the RSS\n\n2. OLS estimators are **linear** in $Y_i$ and **unbiased** under GM assumptions 1–3\n\n3. Under all four GM assumptions: $\\text{Var}(\\hat\\beta_1) = \\sigma^2/S_{xx}$, $\\text{Var}(\\hat\\beta_0) = \\sigma^2(1/n + \\bar x^2/S_{xx})$\n\n4. **Gauss-Markov Theorem:** OLS is **BLUE** (no normality required)\n\n5. Under normality: OLS = MLE, and OLS is the **MVUE** (not just BLUE)\n\n6. OLS achieves the **Cramér-Rao Lower Bound**; it is an **efficient** estimator under normality\n:::\n\n## Connections to the Course Themes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-79f351a847cf4e646453\" style=\"width:960px;height:864px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-79f351a847cf4e646453\">{\"x\":{\"diagram\":\"\\ndigraph course_connections {\\n  graph [rankdir = LR, bgcolor = transparent, splines = curved, nodesep = 0.8, ranksep = 2.2]\\n  node [shape = box, style = filled, fontsize = 42, width = 6.4, height = 2.0]\\n\\n  MVUE  [label = \\\"MVUE Theory\\\\n(Lessons 3, 6)\\\", fillcolor = \\\"#AED6F1\\\"]\\n  CRLB  [label = \\\"CRLB / Fisher Info\\\\n(Lessons 3, 6)\\\", fillcolor = \\\"#F5B7B1\\\"]\\n  MLE   [label = \\\"MLE\\\\n(Lesson 4)\\\", fillcolor = \\\"#FAD7A0\\\"]\\n  Suff  [label = \\\"Sufficient Stats\\\\n(Lesson 5)\\\", fillcolor = \\\"#D7BDE2\\\"]\\n  GM    [label = \\\"Gauss-Markov:\\\\nOLS is BLUE\\\", fillcolor = \\\"#ABEBC6\\\"]\\n  Reg   [label = \\\"Applied Regression\\\", fillcolor = \\\"#D5D8DC\\\"]\\n\\n  MVUE -> GM  [label = \\\"BLUE = MVUE for\\\\nlinear models\\\", fontsize = 24]\\n  CRLB -> GM  [label = \\\"OLS achieves CRLB\\\\nunder normality\\\", fontsize = 24]\\n  MLE  -> GM  [label = \\\"OLS = MLE\\\\nunder normality\\\", fontsize = 24]\\n  Suff -> GM  [label = \\\"(β̂₀, β̂₁, S²) sufficient\\\\nunder normality\\\", fontsize = 24]\\n  GM   -> Reg [label = \\\"t-tests, F-tests,\\\\nprediction intervals\\\", fontsize = 24]\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## Looking Ahead\n\n- **Applied Regression:** Everything builds on today's theory\n  - Multiple regression extends to $\\hat{\\boldsymbol\\beta} = (\\mathbf{X}^\\top\\mathbf{X})^{-1}\\mathbf{X}^\\top\\mathbf{Y}$; the same BLUE result holds via matrix algebra\n  - Generalized Linear Models (GLMs): when $\\varepsilon_i$ are non-normal → MLE replaces OLS\n  - Mixed models: when independence fails → GLS / REML\n\n- **Weighted Least Squares:** BLUE when heteroscedasticity is known (DBC §12.9)\n\n. . .\n\n::: callout-note\n## Matrix Formulation Preview\nIn multiple regression: $\\mathbf{Y} = \\mathbf{X}\\boldsymbol\\beta + \\boldsymbol\\varepsilon$\n\nOLS estimate: $\\hat{\\boldsymbol\\beta} = (\\mathbf{X}^\\top\\mathbf{X})^{-1}\\mathbf{X}^\\top\\mathbf{Y}$\n\nThis is still linear in $\\mathbf{Y}$, still unbiased under GM conditions, and still BLUE by the matrix version of the Gauss-Markov theorem.\n:::\n\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n\n",
    "supporting": [
      "22_GaussMarkov_OLS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}