<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a14e345711173c227b21482e2eb4cc70.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Jessica Minnier">
  <meta name="dcterms.date" content="2026-03-11">
  <title>Theory of Statistical Inference – Lesson 21: Nonparametric Inference</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #383a42;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #383a42; } /* Normal */
    code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
    code span.an { color: #50a14f; } /* Annotation */
    code span.at { color: #a626a4; } /* Attribute */
    code span.bn { color: #986801; } /* BaseN */
    code span.bu { color: #a626a4; } /* BuiltIn */
    code span.cf { color: #a626a4; } /* ControlFlow */
    code span.ch { color: #50a14f; } /* Char */
    code span.cn { color: #986801; } /* Constant */
    code span.co { color: #a0a1a7; font-style: italic; } /* Comment */
    code span.cv { color: #e45649; font-style: italic; } /* CommentVar */
    code span.do { color: #e45649; } /* Documentation */
    code span.dt { color: #a626a4; } /* DataType */
    code span.dv { color: #986801; } /* DecVal */
    code span.er { color: #f44747; text-decoration: underline; } /* Error */
    code span.ex { color: #4078f2; font-weight: bold; } /* Extension */
    code span.fl { color: #986801; } /* Float */
    code span.fu { color: #4078f2; } /* Function */
    code span.im { color: #50a14f; } /* Import */
    code span.in { color: #c45b00; } /* Information */
    code span.kw { color: #a626a4; } /* Keyword */
    code span.op { color: #a626a4; } /* Operator */
    code span.ot { color: #27ae60; } /* Other */
    code span.pp { color: #a626a4; } /* Preprocessor */
    code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
    code span.sc { color: #0184bc; } /* SpecialChar */
    code span.ss { color: #da4453; } /* SpecialString */
    code span.st { color: #50a14f; } /* String */
    code span.va { color: #e45649; } /* Variable */
    code span.vs { color: #da4453; } /* VerbatimString */
    code span.wa { color: #da4453; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-2e74a31c1bd85ff20c819e764b562f47.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="../../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
  <script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
  <script src="../../site_libs/viz-1.8.2/viz.js"></script>
  <link href="../../site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
  <script src="../../site_libs/grViz-binding-1.0.11/grViz.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#006a4e" class="quarto-title-block center">
  <h1 class="title">Lesson 21: Nonparametric Inference</h1>
  <p class="subtitle">BSTA 551: Statistical Inference</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jessica Minnier 
</div>
</div>
</div>

  <p class="date">2026-03-11</p>
</section>
<section>
<section id="lesson-21-nonparametric-inference" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Lesson 21: Nonparametric Inference</h1>

</section>
<section id="review-lessons-1820" class="slide level2 scrollable">
<h2>Review: Lessons 18–20</h2>
<ul>
<li><strong>Lesson 18:</strong> Parametric two-sample tests — Welch <span class="math inline">\(t\)</span>, pooled <span class="math inline">\(t\)</span>, <span class="math inline">\(z\)</span>-test for proportions, <span class="math inline">\(F\)</span>-test</li>
<li><strong>Lesson 19:</strong> Paired <span class="math inline">\(t\)</span>-test — reduces to one-sample inference on <span class="math inline">\(D_i = X_{1i} - X_{2i}\)</span></li>
<li><strong>Lesson 20:</strong> Bootstrap CIs (resample separately) and permutation tests (relabel pooled data)</li>
</ul>
<div class="fragment">
<p><strong>Today’s Goals:</strong></p>
<ol type="1">
<li>Understand what “nonparametric” means and when it is preferred over parametric tests</li>
<li>Derive and apply the <strong>sign test</strong> for paired data (DBC 14.1)</li>
<li>Derive and apply the <strong>Wilcoxon signed-rank test</strong> for paired data (DBC 14.2)</li>
<li>Derive and apply the <strong>Wilcoxon rank-sum test</strong> for two independent samples (DBC 14.3)</li>
<li>Understand <strong>asymptotic relative efficiency (ARE)</strong> and the power trade-offs it quantifies</li>
<li>Apply all three tests to medical examples and compare conclusions</li>
</ol>
</div>
</section>
<section id="what-does-nonparametric-mean" class="slide level2">
<h2>What Does “Nonparametric” Mean?</h2>
<p>A <strong>parametric</strong> test specifies a distributional family (e.g., <span class="math inline">\(D_i \sim N(\mu, \sigma^2)\)</span>) and makes inference about the <strong>parameters</strong> of that family. Validity depends on the assumed family being correct.</p>
<div class="fragment">
<p>A <strong>nonparametric</strong> test makes inference about features of the distribution (median, location, equality of distributions) <strong>without specifying a parametric family</strong>. Validity holds over a broad class of distributions.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>What “Nonparametric” Is NOT</strong></p>
</div>
<div class="callout-content">
<p>Nonparametric <span class="math inline">\(\neq\)</span> assumption-free. These tests still require:</p>
<ul>
<li><strong>Independence</strong> of observations (or independence of pairs)</li>
<li><strong>Continuity</strong> of the underlying distribution (for rank-based tests — ties deflate test power)</li>
<li><strong>Symmetry</strong> of <span class="math inline">\(D_i\)</span> about 0 (for the Wilcoxon signed-rank test)</li>
</ul>
<p>The key relaxation is normality — not all assumptions.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Why does it matter in biomedical research?</strong></p>
<ul>
<li><strong>Biomarkers</strong> (CRP, troponin, ALT) are right-skewed with occasional extreme values</li>
<li><strong>Ordinal scales</strong> (pain VAS, Likert, disability scores) — arithmetic means may be misleading</li>
<li><strong>Small <span class="math inline">\(n\)</span></strong> — CLT convergence too slow to trust normality-based tests</li>
</ul>
</div>
</section>
<section id="roadmap-for-today" class="slide level2">
<h2>Roadmap for Today</h2>
<table class="caption-top">
<colgroup>
<col style="width: 10%">
<col style="width: 27%">
<col style="width: 14%">
<col style="width: 27%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Data Structure</th>
<th><span class="math inline">\(H_0\)</span></th>
<th>Key Assumption</th>
<th>Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sign test</td>
<td>Paired / one-sample</td>
<td>Median <span class="math inline">\(D = 0\)</span></td>
<td>None beyond independence</td>
<td>DBC 14.1</td>
</tr>
<tr class="even">
<td>Wilcoxon signed-rank</td>
<td>Paired / one-sample</td>
<td>Median <span class="math inline">\(D = 0\)</span></td>
<td>Symmetric, continuous <span class="math inline">\(D_i\)</span></td>
<td>DBC 14.2</td>
</tr>
<tr class="odd">
<td>Wilcoxon rank-sum</td>
<td>Two independent samples</td>
<td><span class="math inline">\(F_1 = F_2\)</span></td>
<td>Continuous distributions</td>
<td>DBC 14.3</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Information used by each test:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Test</th>
<th style="text-align: center;">Uses direction of <span class="math inline">\(D_i\)</span>?</th>
<th style="text-align: center;">Uses magnitude of <span class="math inline">\(D_i\)</span>?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sign test</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✗</td>
</tr>
<tr class="even">
<td>Wilcoxon signed-rank</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓ (via ranks)</td>
</tr>
<tr class="odd">
<td>Paired <span class="math inline">\(t\)</span>-test</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓ (exact values)</td>
</tr>
</tbody>
</table>
<p>Each test makes a different assumption about the data in exchange for the information it extracts.</p>
</div>
</section></section>
<section>
<section id="the-sign-test-dbc-14.1" class="title-slide slide level1 center" data-background-color="#3498db">
<h1>The Sign Test (DBC 14.1)</h1>

</section>
<section id="sign-test-setup-and-motivation" class="slide level2">
<h2>Sign Test: Setup and Motivation</h2>
<p><strong>Setting:</strong> Paired differences <span class="math inline">\(D_i = X_{1i} - X_{2i}\)</span>, <span class="math inline">\(i = 1, \ldots, n\)</span>.</p>
<p><strong>Goal:</strong> Test whether the <strong>population median</strong> of the <span class="math inline">\(D_i\)</span> equals zero, without assuming any particular shape.</p>
<p><strong>Key insight:</strong> If the true median of <span class="math inline">\(D_i\)</span> is zero, then <span class="math inline">\(P(D_i &gt; 0) = P(D_i &lt; 0) = 1/2\)</span> (for continuous distributions).</p>
<div class="fragment">
<p><strong>Test statistic:</strong> Count the positive differences.</p>
<p><span class="math display">\[S^+ = \#\{i : D_i &gt; 0\}\]</span></p>
<p>Ties (<span class="math inline">\(D_i = 0\)</span>): excluded. Let <span class="math inline">\(n^* = \#\{i : D_i \neq 0\}\)</span>.</p>
<p><strong>Null distribution:</strong> Under <span class="math inline">\(H_0: P(D_i &gt; 0) = 1/2\)</span>,</p>
<p><span class="math display">\[\boxed{S^+ \sim \text{Binomial}(n^*, 1/2)}\]</span></p>
<p>This follows because each non-zero <span class="math inline">\(D_i\)</span> is independently positive or negative with equal probability under <span class="math inline">\(H_0\)</span>.</p>
</div>
</section>
<section id="sign-test-null-distribution-derivation" class="slide level2">
<h2>Sign Test: Null Distribution Derivation</h2>
<p>Why exactly <span class="math inline">\(\text{Binomial}(n^*, 1/2)\)</span>?</p>
<p>Define <span class="math inline">\(Z_i = \mathbf{1}(D_i &gt; 0)\)</span> for each <span class="math inline">\(i\)</span> with <span class="math inline">\(D_i \neq 0\)</span>. Under <span class="math inline">\(H_0\)</span>:</p>
<ul>
<li><span class="math inline">\(P(Z_i = 1) = P(D_i &gt; 0) = 1/2\)</span> (median is 0, distribution continuous)</li>
<li><span class="math inline">\(P(Z_i = 0) = P(D_i &lt; 0) = 1/2\)</span></li>
<li><span class="math inline">\(Z_1, \ldots, Z_{n^*}\)</span> are <strong>independent</strong> (pairs are independent)</li>
</ul>
<p>Therefore <span class="math inline">\(Z_i \stackrel{iid}{\sim} \text{Bernoulli}(1/2)\)</span> and</p>
<p><span class="math display">\[S^+ = \sum_{i=1}^{n^*} Z_i \sim \text{Binomial}(n^*, 1/2)\]</span></p>
<div class="fragment">
<p>This is exact — no asymptotic approximation needed. The binomial distribution is completely tractable.</p>
<p><strong>Large-sample approximation:</strong> For large <span class="math inline">\(n^*\)</span>, by the CLT:</p>
<p><span class="math display">\[Z_S = \frac{S^+ - n^*/2}{\sqrt{n^*/4}} \;\dot{\sim}\; N(0,1)\]</span></p>
<p>Use the <strong>continuity correction</strong>: replace <span class="math inline">\(S^+\)</span> with <span class="math inline">\(S^+ \pm 0.5\)</span> to improve approximation to the discrete binomial.</p>
</div>
</section>
<section id="sign-test-p-values" class="slide level2">
<h2>Sign Test: P-values</h2>
<table class="caption-top">
<colgroup>
<col style="width: 52%">
<col style="width: 36%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Alternative</th>
<th>Exact p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\tilde{\mu}_D &gt; 0\)</span></td>
<td><span class="math inline">\(P(S^+ \geq s^+)\)</span></td>
<td>More positives than expected</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\tilde{\mu}_D &lt; 0\)</span></td>
<td><span class="math inline">\(P(S^+ \leq s^+)\)</span></td>
<td>Fewer positives than expected</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\tilde{\mu}_D \neq 0\)</span></td>
<td><span class="math inline">\(2\min\bigl(P(S^+ \geq s^+),\; P(S^+ \leq s^+)\bigr)\)</span></td>
<td>Either tail</td>
</tr>
</tbody>
</table>
<p>All probabilities from <span class="math inline">\(\text{Bin}(n^*, 1/2)\)</span> — exact, no normality required.</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Confidence Interval for the Median (Sign Test)</strong></p>
</div>
<div class="callout-content">
<p>An exact CI for the <strong>population median</strong> is based on order statistics. The <span class="math inline">\(100(1-\alpha)\%\)</span> CI for the median is <span class="math inline">\((D_{(j)}, D_{(n^*-j+1)})\)</span> where <span class="math inline">\(j\)</span> is chosen so <span class="math inline">\(P(\text{Bin}(n^*, 1/2) \leq j - 1) \leq \alpha/2\)</span>.</p>
<p>In R: <code>wilcox.test(d, conf.int = TRUE)</code> gives the Wilcoxon CI (preferred when symmetry holds). For the sign-based CI: use <code>SignifReg::sign.ci()</code> or compute directly from the binomial.</p>
</div>
</div>
</div>
</div>
</section>
<section id="sign-test-medical-example-pain-and-physical-therapy" class="slide level2">
<h2>Sign Test: Medical Example (Pain and Physical Therapy)</h2>
<p><strong>Study:</strong> 15 patients rate pain on a 0–10 VAS scale <strong>before</strong> and <strong>after</strong> a 4-week physical therapy program.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0\)</span>: median change <span class="math inline">\(= 0\)</span> vs.&nbsp;<span class="math inline">\(H_a\)</span>: median change <span class="math inline">\(&lt; 0\)</span> (pain <strong>decreases</strong>; <span class="math inline">\(D_i = \text{after} - \text{before}\)</span>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>pain_before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">6</span>)</span>
<span id="cb1-2"><a></a>pain_after  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">3</span>)</span>
<span id="cb1-3"><a></a>d_pain      <span class="ot">&lt;-</span> pain_after <span class="sc">-</span> pain_before</span>
<span id="cb1-4"><a></a></span>
<span id="cb1-5"><a></a><span class="fu">cat</span>(<span class="st">"D = after - before:</span><span class="sc">\n</span><span class="st">"</span>, d_pain, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>D = after - before:
 -3 -1 -3 -2 -3 -4 -2 -2 -3 -3 -2 -3 -3 -3 -3 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>n_star  <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_pain <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb3-2"><a></a>s_plus  <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_pain <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb3-3"><a></a></span>
<span id="cb3-4"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Non-zero differences: n* = %d</span><span class="sc">\n</span><span class="st">"</span>, n_star))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-zero differences: n* = 15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Positive differences: S+ = %d</span><span class="sc">\n</span><span class="st">"</span>, s_plus))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Positive differences: S+ = 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Negative differences: %d</span><span class="sc">\n\n</span><span class="st">"</span>, <span class="fu">sum</span>(d_pain <span class="sc">&lt;</span> <span class="dv">0</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Negative differences: 15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="co"># One-sided p-value: H_a is median &lt; 0 → few positives supports H_a</span></span>
<span id="cb9-2"><a></a>p_sign_one <span class="ot">&lt;-</span> <span class="fu">pbinom</span>(s_plus, <span class="at">size =</span> n_star, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb9-3"><a></a>p_sign_two <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">min</span>(<span class="fu">pbinom</span>(s_plus, n_star, <span class="fl">0.5</span>),</span>
<span id="cb9-4"><a></a>                      <span class="fu">pbinom</span>(s_plus <span class="sc">-</span> <span class="dv">1</span>, n_star, <span class="fl">0.5</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span>
<span id="cb9-5"><a></a></span>
<span id="cb9-6"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"One-sided p-value = %.5f</span><span class="sc">\n</span><span class="st">"</span>, p_sign_one))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>One-sided p-value = 0.00003</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Two-sided p-value = %.5f</span><span class="sc">\n</span><span class="st">"</span>, p_sign_two))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two-sided p-value = 0.00006</code></pre>
</div>
</div>
<div class="fragment">
<p><span class="math inline">\(S^+ = 0\)</span> out of <span class="math inline">\(n^* = 15\)</span> non-zero differences.</p>
<p>Under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(S^+ \sim \text{Bin}(14, 0.5)\)</span>, so <span class="math inline">\(E[S^+] = 7\)</span>.</p>
<p>Observing only <span class="math inline">\(S^+ = 0\)</span> positive differences is very unlikely if the median were zero.</p>
</div>
</section>
<section id="sign-test-visualizing-the-evidence" class="slide level2">
<h2>Sign Test: Visualizing the Evidence</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># Panel 1: Dot chart of differences</span></span>
<span id="cb13-2"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Patient =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>, <span class="at">D =</span> d_pain,</span>
<span id="cb13-3"><a></a>             <span class="at">Direction =</span> <span class="fu">ifelse</span>(d_pain <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Positive"</span>, <span class="fu">ifelse</span>(d_pain <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="st">"Negative"</span>, <span class="st">"Zero"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Patient, <span class="at">y =</span> D, <span class="at">color =</span> Direction)) <span class="sc">+</span></span>
<span id="cb13-5"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> Patient, <span class="at">yend =</span> <span class="dv">0</span>), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Positive"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>,</span>
<span id="cb13-9"><a></a>                                 <span class="st">"Negative"</span> <span class="ot">=</span> <span class="st">"#006a4e"</span>,</span>
<span id="cb13-10"><a></a>                                 <span class="st">"Zero"</span>     <span class="ot">=</span> <span class="st">"grey60"</span>)) <span class="sc">+</span></span>
<span id="cb13-11"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Signed Differences (Pain After \u2212 Before)"</span>,</span>
<span id="cb13-12"><a></a>       <span class="at">x =</span> <span class="st">"Patient"</span>, <span class="at">y =</span> <span class="st">"D = After \u2212 Before"</span>, <span class="at">color =</span> <span class="st">"Direction"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb13-14"><a></a></span>
<span id="cb13-15"><a></a><span class="co"># Panel 2: Binomial null distribution</span></span>
<span id="cb13-16"><a></a>binom_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb13-17"><a></a>  <span class="at">k    =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">14</span>,</span>
<span id="cb13-18"><a></a>  <span class="at">prob =</span> <span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">14</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">prob =</span> <span class="fl">0.5</span>),</span>
<span id="cb13-19"><a></a>  <span class="at">tail =</span> k <span class="sc">&lt;=</span> s_plus</span>
<span id="cb13-20"><a></a>)</span>
<span id="cb13-21"><a></a>p2 <span class="ot">&lt;-</span> binom_df <span class="sc">|&gt;</span></span>
<span id="cb13-22"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> prob, <span class="at">fill =</span> tail)) <span class="sc">+</span></span>
<span id="cb13-23"><a></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-24"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> s_plus, <span class="at">color =</span> <span class="st">"#e74c3c"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb13-25"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"#3498db"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"grey70"</span>),</span>
<span id="cb13-26"><a></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"p-value region"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"Not in tail"</span>)) <span class="sc">+</span></span>
<span id="cb13-27"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> s_plus <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="fl">0.17</span>,</span>
<span id="cb13-28"><a></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"S+ = "</span>, s_plus), <span class="at">color =</span> <span class="st">"#e74c3c"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb13-29"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Null Distribution: "</span> <span class="sc">*</span> S<span class="sc">^</span><span class="st">"+"</span> <span class="sc">*</span> <span class="st">" ~ Bin(14, 0.5)"</span>),</span>
<span id="cb13-30"><a></a>       <span class="at">x =</span> <span class="fu">expression</span>(S<span class="sc">^</span><span class="st">"+"</span>), <span class="at">y =</span> <span class="st">"P(X = k)"</span>, <span class="at">fill =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb13-31"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb13-32"><a></a></span>
<span id="cb13-33"><a></a>p1 <span class="sc">+</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="21_NonparametricInference_files/figure-revealjs/unnamed-chunk-2-1.png" width="1344" class="r-stretch"></section>
<section id="sign-test-strengths-and-limitations" class="slide level2">
<h2>Sign Test: Strengths and Limitations</h2>
<p><strong>Strengths:</strong></p>
<ul>
<li><strong>No distributional assumptions</strong> beyond independence — valid for any continuous or ordinal <span class="math inline">\(D_i\)</span></li>
<li>Works when differences are measured on an <strong>ordinal scale</strong> (e.g., pain VAS, Likert), where arithmetic means are questionable</li>
<li>The simplest nonparametric test to derive, compute, and explain</li>
</ul>
<p><strong>Limitations:</strong></p>
<ul>
<li>Only uses the <strong>sign</strong> (direction) of each difference — discards all magnitude information</li>
<li><strong>Lowest power</strong> among the three paired tests when differences are continuous and symmetric</li>
<li>Wide confidence intervals for the median, especially at small <span class="math inline">\(n\)</span></li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>When to Prefer the Sign Test</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Data are <strong>ordinal</strong>: arithmetic differences aren’t on an interval scale</li>
<li>Differences are <strong>highly asymmetric</strong> with extreme outliers: sign is reliable, magnitude is not</li>
<li>You need the most <strong>assumption-free</strong> result and are willing to sacrifice power</li>
<li>Only the <strong>direction</strong> of each difference is observable (e.g., preferences without magnitudes)</li>
</ul>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="wilcoxon-signed-rank-test-dbc-14.2" class="title-slide slide level1 center" data-background-color="#e74c3c">
<h1>Wilcoxon Signed-Rank Test (DBC 14.2)</h1>

</section>
<section id="wilcoxon-signed-rank-motivation" class="slide level2">
<h2>Wilcoxon Signed-Rank: Motivation</h2>
<p>The sign test throws away the <strong>size</strong> of each difference. Can we do better while still avoiding normality?</p>
<div class="fragment">
<p><strong>Key idea:</strong> Replace the raw differences with their <strong>ranks</strong> by absolute value.</p>
<ul>
<li>Ranks preserve the <em>relative ordering</em> of the magnitudes</li>
<li>They are less sensitive to extreme outliers than raw values</li>
<li>If the distribution is symmetric about 0, the ranks of positive and negative differences should look “balanced” under <span class="math inline">\(H_0\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Key assumption added over sign test:</strong> The distribution of <span class="math inline">\(D_i\)</span> is <strong>symmetric</strong> about its median.</p>
<ul>
<li>Under <span class="math inline">\(H_0\)</span>, symmetric about 0</li>
<li>Under <span class="math inline">\(H_a\)</span>, symmetric about <span class="math inline">\(\theta \neq 0\)</span> (a location shift)</li>
</ul>
<p>This rules out heavily skewed <span class="math inline">\(D_i\)</span> — but covers most bell-shaped and even uniform-like distributions.</p>
</div>
</section>
<section id="wilcoxon-signed-rank-algorithm" class="slide level2 scrollable">
<h2>Wilcoxon Signed-Rank: Algorithm</h2>
<p><strong>Setup:</strong> <span class="math inline">\(D_1, \ldots, D_n \stackrel{iid}{\sim}\)</span> a continuous, symmetric distribution. <span class="math inline">\(H_0\)</span>: median <span class="math inline">\(= 0\)</span>.</p>
<p><strong>Step-by-step:</strong></p>
<ol type="1">
<li class="fragment"><strong>Remove zeros</strong>: drop any <span class="math inline">\(D_i = 0\)</span>. Let $n^* = $ number remaining.</li>
<li class="fragment"><strong>Rank absolute values</strong>: rank <span class="math inline">\(|D_1|, \ldots, |D_{n^*}|\)</span> from smallest (rank 1) to largest (rank <span class="math inline">\(n^*\)</span>). Average ranks for ties.</li>
<li class="fragment"><strong>Compute <span class="math inline">\(W^+\)</span></strong>: sum of ranks for observations with <strong>positive</strong> <span class="math inline">\(D_i\)</span>: <span class="math display">\[W^+ = \sum_{\{i:\,D_i &gt; 0\}} R_i\]</span></li>
<li class="fragment"><strong>Also define</strong>: <span class="math inline">\(W^- = \sum_{\{i:\,D_i &lt; 0\}} R_i = \frac{n^*(n^*+1)}{2} - W^+\)</span></li>
</ol>
<div class="fragment">
<p>Under <span class="math inline">\(H_0\)</span> (symmetric about 0):</p>
<p><span class="math display">\[E[W^+] = \frac{n^*(n^*+1)}{4}, \qquad \text{Var}(W^+) = \frac{n^*(n^*+1)(2n^*+1)}{24}\]</span></p>
<p>Large <span class="math inline">\(n^*\)</span>: <span class="math inline">\(\quad Z = \dfrac{W^+ - E[W^+]}{\sqrt{\text{Var}(W^+)}} \;\dot{\sim}\; N(0,1)\)</span></p>
</div>
</section>
<section id="why-does-ew-fracnn14" class="slide level2">
<h2>Why Does <span class="math inline">\(E[W^+] = \frac{n^*(n^*+1)}{4}\)</span>?</h2>
<p>Under <span class="math inline">\(H_0\)</span> and symmetry, each rank <span class="math inline">\(R_i\)</span> is equally likely to be assigned to a positive or negative difference. Formally, let <span class="math inline">\(\phi_i = \mathbf{1}(D_i &gt; 0)\)</span>. Under <span class="math inline">\(H_0\)</span>:</p>
<ul>
<li><span class="math inline">\(\phi_i \stackrel{iid}{\sim} \text{Bernoulli}(1/2)\)</span>, independent of the ranks <span class="math inline">\(R_i\)</span></li>
<li><span class="math inline">\(W^+ = \sum_{i=1}^{n^*} \phi_i \cdot R_i\)</span></li>
</ul>
<p>Then:</p>
<p><span class="math display">\[E[W^+] = \sum_{i=1}^{n^*} E[\phi_i] \cdot R_i = \frac{1}{2} \sum_{i=1}^{n^*} R_i = \frac{1}{2} \cdot \frac{n^*(n^*+1)}{2} = \frac{n^*(n^*+1)}{4}\]</span></p>
<p>The variance follows from <span class="math inline">\(\text{Var}(\phi_i) = 1/4\)</span> and independence:</p>
<p><span class="math display">\[\text{Var}(W^+) = \sum_{i=1}^{n^*} R_i^2 \cdot \text{Var}(\phi_i) = \frac{1}{4} \sum_{i=1}^{n^*} i^2 = \frac{1}{4} \cdot \frac{n^*(n^*+1)(2n^*+1)}{6} = \frac{n^*(n^*+1)(2n^*+1)}{24}\]</span></p>
</section>
<section id="wilcoxon-signed-rank-continuity-correction-and-ties" class="slide level2">
<h2>Wilcoxon Signed-Rank: Continuity Correction and Ties</h2>
<p><strong>Continuity correction</strong> for the normal approximation:</p>
<p><span class="math display">\[Z = \frac{W^+ - E[W^+] \pm 0.5}{\sqrt{\text{Var}(W^+)}}\]</span></p>
<p>Use <span class="math inline">\(-0.5\)</span> when <span class="math inline">\(W^+ &gt; E[W^+]\)</span> (upper-tail test), <span class="math inline">\(+0.5\)</span> when <span class="math inline">\(W^+ &lt; E[W^+]\)</span> (lower-tail test). R does this automatically.</p>
<div class="fragment">
<p><strong>Correction for ties in ranking:</strong></p>
<p>When there are many ties among the <span class="math inline">\(|D_i|\)</span>, the variance formula understates the true variance. The corrected formula is:</p>
<p><span class="math display">\[\text{Var}_{\text{ties}}(W^+) = \frac{1}{24}\left[n^*(n^*+1)(2n^*+1) - \frac{1}{2}\sum_{j} t_j(t_j-1)(t_j+1)\right]\]</span></p>
<p>where <span class="math inline">\(t_j\)</span> is the size of the <span class="math inline">\(j\)</span>-th group of tied absolute differences.</p>
<ul>
<li>When there are no ties, this reduces to the standard formula</li>
<li>Many ties <span class="math inline">\(\Rightarrow\)</span> reduced variance <span class="math inline">\(\Rightarrow\)</span> more conservative test<br>
</li>
<li><code>wilcox.test()</code> in R applies this correction automatically when <code>exact = FALSE</code></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical Implication of Ties</strong></p>
</div>
<div class="callout-content">
<p>Integer-valued outcomes (VAS pain, Likert scales) have many ties. The <strong>exact</strong> distribution is affected but R handles it. For data with many ties, the <strong>sign test</strong> or a permutation test may be preferred since rank-based tests assume continuous distributions.</p>
</div>
</div>
</div>
</div>
</section>
<section id="wilcoxon-signed-rank-medical-example" class="slide level2">
<h2>Wilcoxon Signed-Rank: Medical Example</h2>
<p><strong>Study:</strong> 16 patients with Stage 1 hypertension. Systolic blood pressure (SBP, mmHg) measured before and 8 weeks after starting a new antihypertensive drug.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0\)</span>: median SBP change <span class="math inline">\(= 0\)</span> vs.&nbsp;<span class="math inline">\(H_a\)</span>: median SBP change <span class="math inline">\(&lt; 0\)</span> (drug lowers BP; <span class="math inline">\(D_i = \text{after} - \text{before}\)</span>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>sbp_before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">158</span>, <span class="dv">142</span>, <span class="dv">168</span>, <span class="dv">135</span>, <span class="dv">172</span>, <span class="dv">145</span>, <span class="dv">163</span>, <span class="dv">138</span>, <span class="dv">155</span>, <span class="dv">149</span>, <span class="dv">167</span>, <span class="dv">141</span>, <span class="dv">160</span>, <span class="dv">153</span>, <span class="dv">144</span>, <span class="dv">170</span>)</span>
<span id="cb14-2"><a></a>sbp_after  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">145</span>, <span class="dv">148</span>, <span class="dv">152</span>, <span class="dv">131</span>, <span class="dv">158</span>, <span class="dv">139</span>, <span class="dv">170</span>, <span class="dv">135</span>, <span class="dv">142</span>, <span class="dv">143</span>, <span class="dv">151</span>, <span class="dv">150</span>, <span class="dv">148</span>, <span class="dv">140</span>, <span class="dv">149</span>, <span class="dv">155</span>)</span>
<span id="cb14-3"><a></a>d_sbp      <span class="ot">&lt;-</span> sbp_after <span class="sc">-</span> sbp_before</span>
<span id="cb14-4"><a></a></span>
<span id="cb14-5"><a></a><span class="fu">cat</span>(<span class="st">"D = after - before (mmHg):</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>D = after - before (mmHg):</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">cat</span>(d_sbp, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>-13 6 -16 -4 -14 -6 7 -3 -13 -6 -16 9 -12 -13 5 -15 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"n = %d pairs | Positive (BP increased): %d | Negative (BP decreased): %d | Zero: %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb18-2"><a></a>            <span class="fu">length</span>(d_sbp), <span class="fu">sum</span>(d_sbp <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">sum</span>(d_sbp <span class="sc">&lt;</span> <span class="dv">0</span>), <span class="fu">sum</span>(d_sbp <span class="sc">==</span> <span class="dv">0</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>n = 16 pairs | Positive (BP increased): 4 | Negative (BP decreased): 12 | Zero: 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Mean change: %.1f mmHg | Median change: %.1f mmHg</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-2"><a></a>            <span class="fu">mean</span>(d_sbp), <span class="fu">median</span>(d_sbp)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean change: -6.5 mmHg | Median change: -9.0 mmHg</code></pre>
</div>
</div>
<div class="fragment">
<p>Most patients improved (SBP decreased), but <strong>4 patients had higher SBP</strong> after treatment — the kind of individual variability that makes nonparametric inference useful.</p>
</div>
</section>
<section id="wilcoxon-signed-rank-step-by-step-calculation" class="slide level2">
<h2>Wilcoxon Signed-Rank: Step-by-Step Calculation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="co"># Step 1: Remove zeros (none here)</span></span>
<span id="cb22-2"><a></a>d_nz   <span class="ot">&lt;-</span> d_sbp[d_sbp <span class="sc">!=</span> <span class="dv">0</span>]</span>
<span id="cb22-3"><a></a>n_star <span class="ot">&lt;-</span> <span class="fu">length</span>(d_nz)</span>
<span id="cb22-4"><a></a></span>
<span id="cb22-5"><a></a><span class="co"># Step 2: Rank absolute values (ties averaged automatically)</span></span>
<span id="cb22-6"><a></a>abs_ranks <span class="ot">&lt;-</span> <span class="fu">rank</span>(<span class="fu">abs</span>(d_nz))</span>
<span id="cb22-7"><a></a></span>
<span id="cb22-8"><a></a><span class="co"># Step 3: Compute W+</span></span>
<span id="cb22-9"><a></a>W_plus  <span class="ot">&lt;-</span> <span class="fu">sum</span>(abs_ranks[d_nz <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb22-10"><a></a>W_minus <span class="ot">&lt;-</span> <span class="fu">sum</span>(abs_ranks[d_nz <span class="sc">&lt;</span> <span class="dv">0</span>])</span>
<span id="cb22-11"><a></a></span>
<span id="cb22-12"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"n* = %d</span><span class="sc">\n</span><span class="st">"</span>, n_star))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>n* = 16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"W+ = %.1f   (sum of ranks for %d positive differences)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb24-2"><a></a>            W_plus, <span class="fu">sum</span>(d_nz <span class="sc">&gt;</span> <span class="dv">0</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>W+ = 23.0   (sum of ranks for 4 positive differences)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"W- = %.1f   (sum of ranks for %d negative differences)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb26-2"><a></a>            W_minus, <span class="fu">sum</span>(d_nz <span class="sc">&lt;</span> <span class="dv">0</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>W- = 113.0   (sum of ranks for 12 negative differences)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Check: W+ + W- = %.1f  (should equal n*(n*+1)/2 = %.1f)</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb28-2"><a></a>            W_plus <span class="sc">+</span> W_minus, n_star<span class="sc">*</span>(n_star<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Check: W+ + W- = 136.0  (should equal n*(n*+1)/2 = 136.0)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="co"># Normal approximation</span></span>
<span id="cb30-2"><a></a>mu_W  <span class="ot">&lt;-</span> n_star <span class="sc">*</span> (n_star <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb30-3"><a></a>var_W <span class="ot">&lt;-</span> n_star <span class="sc">*</span> (n_star <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">*</span> (<span class="dv">2</span><span class="sc">*</span>n_star <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">24</span></span>
<span id="cb30-4"><a></a>sd_W  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_W)</span>
<span id="cb30-5"><a></a>z_W   <span class="ot">&lt;-</span> (W_plus <span class="sc">-</span> mu_W) <span class="sc">/</span> sd_W  <span class="co"># one-sided: small W+ supports Ha</span></span>
<span id="cb30-6"><a></a></span>
<span id="cb30-7"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"E[W+] = %.2f   Var(W+) = %.2f   SD(W+) = %.2f</span><span class="sc">\n</span><span class="st">"</span>, mu_W, var_W, sd_W))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>E[W+] = 68.00   Var(W+) = 374.00   SD(W+) = 19.34</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Z = (%.1f - %.2f) / %.2f = %.3f</span><span class="sc">\n</span><span class="st">"</span>, W_plus, mu_W, sd_W, z_W))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z = (23.0 - 68.00) / 19.34 = -2.327</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"One-sided p-value (normal approx): %.5f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">pnorm</span>(z_W)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>One-sided p-value (normal approx): 0.00999</code></pre>
</div>
</div>
</section>
<section id="wilcoxon-signed-rank-r-output-and-hodges-lehmann-estimate" class="slide level2">
<h2>Wilcoxon Signed-Rank: R Output and Hodges-Lehmann Estimate</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="co"># R uses exact distribution for small n, Hodges-Lehmann estimate</span></span>
<span id="cb36-2"><a></a>wsr_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(sbp_after, sbp_before,</span>
<span id="cb36-3"><a></a>                           <span class="at">paired      =</span> <span class="cn">TRUE</span>,</span>
<span id="cb36-4"><a></a>                           <span class="at">alternative =</span> <span class="st">"less"</span>,</span>
<span id="cb36-5"><a></a>                           <span class="at">conf.int    =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-6"><a></a>wsr_result <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-7"><a></a>  <span class="fu">select</span>(statistic, p.value, conf.low, conf.high, method, alternative) <span class="sc">|&gt;</span></span>
<span id="cb36-8"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  statistic p.value conf.low conf.high method                        alternative
      &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                         &lt;chr&gt;      
1        23  0.0106     -Inf     -3.00 Wilcoxon signed rank test wi… less       </code></pre>
</div>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Hodges-Lehmann Estimator</strong></p>
</div>
<div class="callout-content">
<p>The <strong>Hodges-Lehmann (HL) estimator</strong> of location shift associated with the signed-rank test is:</p>
<p><span class="math display">\[\hat{\theta}_{HL} = \text{median}\left\{\frac{D_i + D_j}{2} : 1 \leq i \leq j \leq n^*\right\}\]</span></p>
<p>the median of all <strong>Walsh averages</strong> (pairwise averages of differences, including self-averages).</p>
<ul>
<li>This is a natural point estimate when using the signed-rank test</li>
<li>The confidence interval from <code>wilcox.test(..., conf.int = TRUE)</code> is the <strong>Hodges-Lehmann CI</strong></li>
<li>More robust to outliers than the sample mean, but still uses magnitude information</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="visualizing-the-rankings-for-the-sbp-data" class="slide level2">
<h2>Visualizing the Rankings for the SBP Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>sbp_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb38-2"><a></a>  <span class="at">Patient =</span> <span class="fu">seq_along</span>(d_sbp),</span>
<span id="cb38-3"><a></a>  <span class="at">Diff    =</span> d_sbp,</span>
<span id="cb38-4"><a></a>  <span class="at">AbsDiff =</span> <span class="fu">abs</span>(d_sbp),</span>
<span id="cb38-5"><a></a>  <span class="at">Sign    =</span> <span class="fu">ifelse</span>(d_sbp <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Positive: BP increased (D &gt; 0)"</span>,</span>
<span id="cb38-6"><a></a>                              <span class="st">"Negative: BP decreased (D &lt; 0)"</span>),</span>
<span id="cb38-7"><a></a>  <span class="at">Rank    =</span> <span class="fu">rank</span>(<span class="fu">abs</span>(d_sbp))</span>
<span id="cb38-8"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb38-9"><a></a>  <span class="fu">filter</span>(Diff <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb38-10"><a></a></span>
<span id="cb38-11"><a></a>p_rank <span class="ot">&lt;-</span> sbp_df <span class="sc">|&gt;</span></span>
<span id="cb38-12"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(<span class="fu">factor</span>(Patient), AbsDiff),</span>
<span id="cb38-13"><a></a>             <span class="at">y =</span> AbsDiff,</span>
<span id="cb38-14"><a></a>             <span class="at">fill =</span> Sign)) <span class="sc">+</span></span>
<span id="cb38-15"><a></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.65</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb38-16"><a></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"R = %g"</span>, Rank), <span class="at">y =</span> AbsDiff <span class="sc">+</span> <span class="fl">0.4</span>),</span>
<span id="cb38-17"><a></a>            <span class="at">size =</span> <span class="fl">4.5</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb38-18"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb38-19"><a></a>    <span class="st">"Positive: BP increased (D &gt; 0)"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>,</span>
<span id="cb38-20"><a></a>    <span class="st">"Negative: BP decreased (D &lt; 0)"</span> <span class="ot">=</span> <span class="st">"#006a4e"</span></span>
<span id="cb38-21"><a></a>  )) <span class="sc">+</span></span>
<span id="cb38-22"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb38-23"><a></a>    <span class="at">title    =</span> <span class="st">"Wilcoxon Signed-Rank: Absolute SBP Changes with Ranks"</span>,</span>
<span id="cb38-24"><a></a>    <span class="at">subtitle =</span> <span class="fu">expression</span>(W<span class="sc">^</span><span class="st">"+"</span> <span class="sc">*</span> <span class="st">" = sum of ranks for red bars (BP increased); small "</span> <span class="sc">*</span></span>
<span id="cb38-25"><a></a>                          W<span class="sc">^</span><span class="st">"+"</span> <span class="sc">*</span> <span class="st">" relative to E["</span> <span class="sc">*</span> W<span class="sc">^</span><span class="st">"+"</span> <span class="sc">*</span> <span class="st">"] = 68 supports H"</span>[a]),</span>
<span id="cb38-26"><a></a>    <span class="at">x        =</span> <span class="st">"Patient (ordered by |D|)"</span>,</span>
<span id="cb38-27"><a></a>    <span class="at">y        =</span> <span class="st">"|SBP change| (mmHg)"</span>,</span>
<span id="cb38-28"><a></a>    <span class="at">fill     =</span> <span class="st">"Direction of change"</span></span>
<span id="cb38-29"><a></a>  ) <span class="sc">+</span></span>
<span id="cb38-30"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb38-31"><a></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>))</span>
<span id="cb38-32"><a></a></span>
<span id="cb38-33"><a></a>p_rank</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="21_NonparametricInference_files/figure-revealjs/unnamed-chunk-6-1.png" width="1440" class="r-stretch"><div class="fragment">
<p><span class="math inline">\(W^+ = 23 \ll E[W^+] = 68\)</span> — the positive-difference ranks are concentrated at low values, indicating the drug tends to reduce SBP.</p>
</div>
</section>
<section id="wilcoxon-signed-rank-visualizing-the-paired-data" class="slide level2">
<h2>Wilcoxon Signed-Rank: Visualizing the Paired Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>sbp_long <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb39-2"><a></a>  <span class="at">Patient   =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>, <span class="dv">2</span>),</span>
<span id="cb39-3"><a></a>  <span class="at">SBP       =</span> <span class="fu">c</span>(sbp_before, sbp_after),</span>
<span id="cb39-4"><a></a>  <span class="at">Timepoint =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>), <span class="at">each =</span> <span class="dv">16</span>),</span>
<span id="cb39-5"><a></a>  <span class="at">Direction =</span> <span class="fu">rep</span>(<span class="fu">ifelse</span>(d_sbp <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="st">"Decreased"</span>, <span class="st">"Increased"</span>), <span class="dv">2</span>)</span>
<span id="cb39-6"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb39-7"><a></a>  <span class="fu">mutate</span>(<span class="at">Timepoint =</span> <span class="fu">factor</span>(Timepoint, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>)))</span>
<span id="cb39-8"><a></a></span>
<span id="cb39-9"><a></a>p_paired <span class="ot">&lt;-</span> sbp_long <span class="sc">|&gt;</span></span>
<span id="cb39-10"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Timepoint, <span class="at">y =</span> SBP)) <span class="sc">+</span></span>
<span id="cb39-11"><a></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> Patient, <span class="at">color =</span> Direction),</span>
<span id="cb39-12"><a></a>            <span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb39-13"><a></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Direction), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb39-14"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Decreased"</span> <span class="ot">=</span> <span class="st">"#006a4e"</span>, <span class="st">"Increased"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>),</span>
<span id="cb39-15"><a></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"BP decreased"</span>, <span class="st">"BP increased"</span>)) <span class="sc">+</span></span>
<span id="cb39-16"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Systolic Blood Pressure Before and After Antihypertensive Treatment"</span>,</span>
<span id="cb39-17"><a></a>       <span class="at">subtitle =</span> <span class="st">"Each line = one patient. Green = improved (BP decreased); Red = worsened (BP increased)."</span>,</span>
<span id="cb39-18"><a></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"SBP (mmHg)"</span>, <span class="at">color =</span> <span class="st">"Change direction"</span>) <span class="sc">+</span></span>
<span id="cb39-19"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb39-20"><a></a></span>
<span id="cb39-21"><a></a>p_diff <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">D =</span> d_sbp, <span class="at">Patient =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>,</span>
<span id="cb39-22"><a></a>                 <span class="at">Direction =</span> <span class="fu">ifelse</span>(d_sbp <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Increased"</span>, <span class="st">"Decreased"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb39-23"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(<span class="fu">factor</span>(Patient), D), <span class="at">y =</span> D, <span class="at">fill =</span> Direction)) <span class="sc">+</span></span>
<span id="cb39-24"><a></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb39-25"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb39-26"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">median</span>(d_sbp), <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb39-27"><a></a>             <span class="at">color =</span> <span class="st">"#3498db"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb39-28"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fu">median</span>(d_sbp) <span class="sc">-</span> <span class="fl">1.5</span>, <span class="at">hjust =</span> <span class="dv">0</span>,</span>
<span id="cb39-29"><a></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"HL estimate = "</span>, <span class="fu">median</span>(d_sbp), <span class="st">" mmHg"</span>),</span>
<span id="cb39-30"><a></a>           <span class="at">color =</span> <span class="st">"#3498db"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb39-31"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Increased"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>, <span class="st">"Decreased"</span> <span class="ot">=</span> <span class="st">"#006a4e"</span>)) <span class="sc">+</span></span>
<span id="cb39-32"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Differences D = After \u2212 Before (mmHg)"</span>,</span>
<span id="cb39-33"><a></a>       <span class="at">x =</span> <span class="st">"Patient (ordered by D)"</span>, <span class="at">y =</span> <span class="st">"D (mmHg)"</span>, <span class="at">fill =</span> <span class="st">"Direction"</span>) <span class="sc">+</span></span>
<span id="cb39-34"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb39-35"><a></a></span>
<span id="cb39-36"><a></a>p_paired <span class="sc">+</span> p_diff</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="21_NonparametricInference_files/figure-revealjs/unnamed-chunk-7-1.png" width="1440" class="r-stretch"></section>
<section id="comparing-sign-test-wilcoxon-signed-rank-and-paired-t-on-sbp-data" class="slide level2">
<h2>Comparing Sign Test, Wilcoxon Signed-Rank, and Paired <em>t</em> on SBP Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">cat</span>(<span class="st">"=== SIGN TEST ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== SIGN TEST ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a>n_s  <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_sbp <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb42-2"><a></a>sp   <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_sbp <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb42-3"><a></a>p_sign <span class="ot">&lt;-</span> <span class="fu">pbinom</span>(sp, n_s, <span class="fl">0.5</span>)</span>
<span id="cb42-4"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"S+ = %d   n* = %d   one-sided p = %.5f</span><span class="sc">\n\n</span><span class="st">"</span>, sp, n_s, p_sign))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>S+ = 4   n* = 16   one-sided p = 0.03841</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">cat</span>(<span class="st">"=== WILCOXON SIGNED-RANK ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== WILCOXON SIGNED-RANK ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="fu">wilcox.test</span>(sbp_after, sbp_before, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb46-2"><a></a>            <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a></a>  <span class="fu">select</span>(statistic, p.value, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb46-5"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic p.value conf.low conf.high
      &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1        23  0.0106     -Inf     -3.00</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a><span class="fu">cat</span>(<span class="st">"=== PAIRED t-TEST ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== PAIRED t-TEST ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">t.test</span>(sbp_after, sbp_before, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-2"><a></a>       <span class="at">alternative =</span> <span class="st">"less"</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a></a>  <span class="fu">select</span>(statistic, parameter, p.value, conf.low) <span class="sc">|&gt;</span></span>
<span id="cb51-5"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic parameter p.value conf.low
      &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1     -2.91        15 0.00537     -Inf</code></pre>
</div>
</div>
<div class="fragment">
<p>All three agree: strong evidence the drug reduces SBP. The paired <span class="math inline">\(t\)</span>-test uses exact magnitudes; the Wilcoxon uses ranks; the sign test uses only directions.</p>
</div>
</section></section>
<section>
<section id="wilcoxon-rank-sum-test-dbc-14.3" class="title-slide slide level1 center" data-background-color="#27ae60">
<h1>Wilcoxon Rank-Sum Test (DBC 14.3)</h1>

</section>
<section id="rank-sum-test-two-independent-samples" class="slide level2 scrollable">
<h2>Rank-Sum Test: Two Independent Samples</h2>
<p><strong>Setting:</strong> <span class="math inline">\(X_{11}, \ldots, X_{1n_1} \stackrel{iid}{\sim} F_1\)</span> and <span class="math inline">\(X_{21}, \ldots, X_{2n_2} \stackrel{iid}{\sim} F_2\)</span>, independent samples.</p>
<p><strong><span class="math inline">\(H_0\)</span>:</strong> <span class="math inline">\(F_1 = F_2\)</span> — the two samples come from the <strong>same distribution</strong>.</p>
<p>Under a <strong>location-shift model</strong> (<span class="math inline">\(F_2(x) = F_1(x - \Delta)\)</span>), this is equivalent to <span class="math inline">\(H_0: \Delta = 0\)</span>.</p>
<div class="fragment">
<p><strong>Algorithm:</strong></p>
<ol type="1">
<li>Pool all <span class="math inline">\(N = n_1 + n_2\)</span> observations together; rank from 1 to <span class="math inline">\(N\)</span> (average ties)</li>
<li>Compute <span class="math inline">\(W = \displaystyle\sum_{\text{group 1}} R_i\)</span> = sum of ranks for group 1 observations</li>
<li>Under <span class="math inline">\(H_0\)</span>: <strong>every allocation of ranks to groups is equally likely</strong></li>
</ol>
<p><span class="math display">\[E[W] = \frac{n_1(N+1)}{2}, \qquad \text{Var}(W) = \frac{n_1 n_2(N+1)}{12}\]</span></p>
<p>For large samples: <span class="math inline">\(Z = \dfrac{W - E[W]}{\sqrt{\text{Var}(W)}} \;\dot{\sim}\; N(0,1)\)</span></p>
</div>
<div class="fragment">
<p>The exact null distribution of <span class="math inline">\(W\)</span> is computed by R for small <span class="math inline">\(n_1, n_2\)</span> (<code>wilcox.test</code> with <code>exact = TRUE</code>).</p>
</div>
</section>
<section id="rank-sum-test-why-this-null-distribution" class="slide level2">
<h2>Rank-Sum Test: Why This Null Distribution?</h2>
<p>Under <span class="math inline">\(H_0: F_1 = F_2\)</span>, the <span class="math inline">\(N\)</span> pooled observations are exchangeable. The group labels (group 1 or group 2) are equally likely to be assigned to any set of <span class="math inline">\(n_1\)</span> positions out of <span class="math inline">\(N\)</span>.</p>
<p>There are <span class="math inline">\(\binom{N}{n_1}\)</span> equally-likely allocations.</p>
<p><span class="math inline">\(W\)</span> = sum of group-1 ranks ranges from <span class="math inline">\(\frac{n_1(n_1+1)}{2}\)</span> (smallest <span class="math inline">\(n_1\)</span> ranks) to <span class="math inline">\(\frac{n_1(2n_2+n_1+1)}{2}\)</span> (largest <span class="math inline">\(n_1\)</span> ranks).</p>
<div class="fragment">
<p><strong>Expected value:</strong></p>
<p><span class="math display">\[E[W] = n_1 \cdot E[\text{rank of a single obs.}] = n_1 \cdot \frac{N+1}{2}\]</span></p>
<p>since under <span class="math inline">\(H_0\)</span>, each rank from 1 to <span class="math inline">\(N\)</span> is equally likely for any observation.</p>
<p><strong>Variance:</strong></p>
<p><span class="math display">\[\text{Var}(W) = \frac{n_1 n_2 (N+1)}{12}\]</span></p>
<p>derived from the variance of sampling without replacement from <span class="math inline">\(\{1, \ldots, N\}\)</span>.</p>
</div>
</section>
<section id="the-mannwhitney-u-statistic" class="slide level2">
<h2>The Mann–Whitney <span class="math inline">\(U\)</span> Statistic</h2>
<p>The <strong>Mann-Whitney <span class="math inline">\(U\)</span></strong> is equivalent to <span class="math inline">\(W\)</span> and has a useful probabilistic interpretation:</p>
<p><span class="math display">\[U = W - \frac{n_1(n_1+1)}{2}\]</span></p>
<p><strong><span class="math inline">\(U\)</span> counts the number of concordant pairs:</strong></p>
<p><span class="math display">\[U = \#\{(i,j) : X_{1i} &gt; X_{2j}\}\]</span></p>
<p>out of all <span class="math inline">\(n_1 \times n_2\)</span> pairs. Under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(E[U] = n_1 n_2 / 2\)</span>.</p>
<div class="fragment">
<p><span class="math inline">\(U / (n_1 n_2)\)</span> is a consistent estimator of <span class="math inline">\(P(X_1 &gt; X_2)\)</span>:</p>
<ul>
<li><span class="math inline">\(P(X_1 &gt; X_2) = 1/2\)</span> under <span class="math inline">\(H_0\)</span></li>
<li><span class="math inline">\(P(X_1 &gt; X_2) &gt; 1/2\)</span> when group 1 tends to be larger</li>
<li>This is the <strong>area under the ROC curve (AUC)</strong> — a key measure in diagnostic medicine</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mann-Whitney U and the ROC Curve</strong></p>
</div>
<div class="callout-content">
<p>If you use group membership as a “predictor” and a continuous biomarker as the “score,” the Mann-Whitney <span class="math inline">\(U\)</span> statistic normalized by <span class="math inline">\(n_1 n_2\)</span> equals the AUC of the ROC curve. This connects nonparametric testing directly to classification performance.</p>
</div>
</div>
</div>
</div>
</section>
<section id="rank-sum-test-ties-correction" class="slide level2">
<h2>Rank-Sum Test: Ties Correction</h2>
<p>When there are ties among the pooled observations, the variance is corrected:</p>
<p><span class="math display">\[\text{Var}_{\text{ties}}(W) = \frac{n_1 n_2}{12} \left[ N + 1 - \frac{\sum_j t_j(t_j^2-1)}{N(N-1)} \right]\]</span></p>
<p>where <span class="math inline">\(t_j\)</span> = size of the <span class="math inline">\(j\)</span>-th tied group in the combined sample.</p>
<ul>
<li>Ties reduce the variance (less information in the ranks)</li>
<li>The correction makes the <span class="math inline">\(Z\)</span>-statistic slightly larger in absolute value</li>
<li>R applies this automatically in <code>wilcox.test()</code></li>
</ul>
<div class="fragment">
<p><strong>Hodges-Lehmann Estimator for Two Samples:</strong></p>
<p><span class="math display">\[\hat{\Delta}_{HL} = \text{median}\{X_{1i} - X_{2j} : i = 1,\ldots,n_1;\ j = 1,\ldots,n_2\}\]</span></p>
<p>The median of all <span class="math inline">\(n_1 \times n_2\)</span> pairwise differences. This is the natural point estimate of the location shift <span class="math inline">\(\Delta\)</span> under the rank-sum framework.</p>
</div>
</section>
<section id="rank-sum-test-medical-example-serum-crp" class="slide level2">
<h2>Rank-Sum Test: Medical Example (Serum CRP)</h2>
<p><strong>Study:</strong> Compare serum CRP (mg/L), a right-skewed inflammatory biomarker, between patients <strong>with</strong> and <strong>without</strong> post-operative infections.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb53-2"><a></a>crp_infect  <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">18</span>, <span class="at">shape =</span> <span class="fl">2.0</span>, <span class="at">rate =</span> <span class="fl">0.08</span>)  <span class="co"># mean ~25 mg/L</span></span>
<span id="cb53-3"><a></a>crp_control <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">20</span>, <span class="at">shape =</span> <span class="fl">1.2</span>, <span class="at">rate =</span> <span class="fl">0.12</span>)  <span class="co"># mean ~10 mg/L</span></span>
<span id="cb53-4"><a></a></span>
<span id="cb53-5"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Infection:  n = %d   mean = %.1f   median = %.1f   sd = %.1f   range = [%.1f, %.1f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb53-6"><a></a>            <span class="fu">length</span>(crp_infect),  <span class="fu">mean</span>(crp_infect),</span>
<span id="cb53-7"><a></a>            <span class="fu">median</span>(crp_infect),  <span class="fu">sd</span>(crp_infect),</span>
<span id="cb53-8"><a></a>            <span class="fu">min</span>(crp_infect), <span class="fu">max</span>(crp_infect)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Infection:  n = 18   mean = 19.9   median = 22.5   sd = 10.1   range = [3.5, 33.8]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Control:    n = %d   mean = %.1f   median = %.1f   sd = %.1f   range = [%.1f, %.1f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb55-2"><a></a>            <span class="fu">length</span>(crp_control), <span class="fu">mean</span>(crp_control),</span>
<span id="cb55-3"><a></a>            <span class="fu">median</span>(crp_control), <span class="fu">sd</span>(crp_control),</span>
<span id="cb55-4"><a></a>            <span class="fu">min</span>(crp_control), <span class="fu">max</span>(crp_control)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Control:    n = 20   mean = 11.7   median = 6.4   sd = 10.3   range = [1.7, 36.3]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>N  <span class="ot">&lt;-</span> <span class="fu">length</span>(crp_infect) <span class="sc">+</span> <span class="fu">length</span>(crp_control)</span>
<span id="cb57-2"><a></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(crp_infect)</span>
<span id="cb57-3"><a></a>n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(crp_control)</span>
<span id="cb57-4"><a></a></span>
<span id="cb57-5"><a></a>W_obs  <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">rank</span>(<span class="fu">c</span>(crp_infect, crp_control))[<span class="dv">1</span><span class="sc">:</span>n1])</span>
<span id="cb57-6"><a></a>E_W    <span class="ot">&lt;-</span> n1 <span class="sc">*</span> (N <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb57-7"><a></a>Var_W  <span class="ot">&lt;-</span> n1 <span class="sc">*</span> n2 <span class="sc">*</span> (N <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb57-8"><a></a>Z_W    <span class="ot">&lt;-</span> (W_obs <span class="sc">-</span> E_W) <span class="sc">/</span> <span class="fu">sqrt</span>(Var_W)</span>
<span id="cb57-9"><a></a></span>
<span id="cb57-10"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"N = %d   n1 = %d   n2 = %d</span><span class="sc">\n</span><span class="st">"</span>, N, n1, n2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>N = 38   n1 = 18   n2 = 20</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"W = %.1f   E[W] = %.1f   SD(W) = %.2f</span><span class="sc">\n</span><span class="st">"</span>, W_obs, E_W, <span class="fu">sqrt</span>(Var_W)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>W = 440.0   E[W] = 351.0   SD(W) = 34.21</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Z = %.3f   one-sided p (approx) = %.5f</span><span class="sc">\n\n</span><span class="st">"</span>, Z_W, <span class="fu">pnorm</span>(Z_W, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z = 2.602   one-sided p (approx) = 0.00463</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a><span class="fu">cat</span>(<span class="st">"--- wilcox.test (exact + Hodges-Lehmann CI) ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- wilcox.test (exact + Hodges-Lehmann CI) ---</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a></a><span class="fu">wilcox.test</span>(crp_infect, crp_control,</span>
<span id="cb65-2"><a></a>            <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb65-3"><a></a>  <span class="fu">select</span>(statistic, p.value, conf.low, conf.high, method) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic p.value conf.low conf.high method                      
      &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                       
1       269 0.00427     2.68       Inf Wilcoxon rank sum exact test</code></pre>
</div>
</div>
</section>
<section id="rank-sum-test-comparison-with-welch-t" class="slide level2">
<h2>Rank-Sum Test: Comparison with Welch <em>t</em></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a></a><span class="fu">cat</span>(<span class="st">"--- Welch t-test ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Welch t-test ---</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a></a><span class="fu">t.test</span>(crp_infect, crp_control, <span class="at">alternative =</span> <span class="st">"greater"</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a></a>  <span class="fu">select</span>(statistic, parameter, p.value, conf.low, method) <span class="sc">|&gt;</span></span>
<span id="cb69-4"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic parameter p.value conf.low method                 
      &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                  
1      2.49      35.7 0.00876     2.67 Welch Two Sample t-test</code></pre>
</div>
</div>
<div class="fragment">
<p>Both tests reject <span class="math inline">\(H_0\)</span>, but note:</p>
<ul>
<li>CRP is strongly <strong>right-skewed</strong> with outliers → <span class="math inline">\(t\)</span>-test p-value is less reliable</li>
<li>Wilcoxon rank-sum p-value is based on a <strong>distribution-free</strong> null</li>
<li>Hodges-Lehmann estimate of location shift: <code>conf.low</code> from <code>wilcox.test</code></li>
<li>With small <span class="math inline">\(n\)</span> and skewed biomarkers, the rank-sum test is the <strong>preferred primary analysis</strong></li>
</ul>
</div>
</section>
<section id="visualizing-the-crp-data" class="slide level2">
<h2>Visualizing the CRP Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a></a>p_vio <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb71-2"><a></a>  <span class="at">CRP   =</span> <span class="fu">c</span>(crp_infect, crp_control),</span>
<span id="cb71-3"><a></a>  <span class="at">Group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Infection"</span>, <span class="st">"Control"</span>),</span>
<span id="cb71-4"><a></a>              <span class="fu">c</span>(<span class="fu">length</span>(crp_infect), <span class="fu">length</span>(crp_control)))</span>
<span id="cb71-5"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb71-6"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Group, <span class="at">y =</span> CRP, <span class="at">fill =</span> Group)) <span class="sc">+</span></span>
<span id="cb71-7"><a></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">trim =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb71-8"><a></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.18</span>, <span class="at">fill =</span> <span class="st">"white"</span>,</span>
<span id="cb71-9"><a></a>               <span class="at">outlier.shape =</span> <span class="dv">1</span>, <span class="at">outlier.size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb71-10"><a></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> median, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb71-11"><a></a>               <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb71-12"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Infection"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>,</span>
<span id="cb71-13"><a></a>                                <span class="st">"Control"</span>   <span class="ot">=</span> <span class="st">"#006a4e"</span>)) <span class="sc">+</span></span>
<span id="cb71-14"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb71-15"><a></a>    <span class="at">title    =</span> <span class="st">"Serum CRP by Post-Operative Infection Status"</span>,</span>
<span id="cb71-16"><a></a>    <span class="at">subtitle =</span> <span class="st">"Right-skewed biomarker: Wilcoxon rank-sum preferred. Diamond = median."</span>,</span>
<span id="cb71-17"><a></a>    <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"CRP (mg/L)"</span></span>
<span id="cb71-18"><a></a>  ) <span class="sc">+</span></span>
<span id="cb71-19"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb71-20"><a></a></span>
<span id="cb71-21"><a></a><span class="co"># Show ranks</span></span>
<span id="cb71-22"><a></a>all_crp   <span class="ot">&lt;-</span> <span class="fu">c</span>(crp_infect, crp_control)</span>
<span id="cb71-23"><a></a>all_group <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Infection"</span>, <span class="st">"Control"</span>), <span class="fu">c</span>(n1, n2))</span>
<span id="cb71-24"><a></a>p_ranks <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">CRP =</span> all_crp, <span class="at">Group =</span> all_group,</span>
<span id="cb71-25"><a></a>                   <span class="at">Rank =</span> <span class="fu">rank</span>(all_crp)) <span class="sc">|&gt;</span></span>
<span id="cb71-26"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Rank, <span class="at">y =</span> CRP, <span class="at">color =</span> Group)) <span class="sc">+</span></span>
<span id="cb71-27"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb71-28"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Infection"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>, <span class="st">"Control"</span> <span class="ot">=</span> <span class="st">"#006a4e"</span>)) <span class="sc">+</span></span>
<span id="cb71-29"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb71-30"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"CRP Values vs. Pooled Ranks"</span>,</span>
<span id="cb71-31"><a></a>       <span class="at">subtitle =</span> <span class="st">"Infection group tends to hold the higher ranks (rightward)"</span>,</span>
<span id="cb71-32"><a></a>       <span class="at">x =</span> <span class="st">"Pooled rank"</span>, <span class="at">y =</span> <span class="st">"CRP (mg/L)"</span>, <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb71-33"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb71-34"><a></a></span>
<span id="cb71-35"><a></a>p_vio <span class="sc">+</span> p_ranks</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="21_NonparametricInference_files/figure-revealjs/unnamed-chunk-12-1.png" width="1440" class="r-stretch"></section></section>
<section>
<section id="asymptotic-relative-efficiency" class="title-slide slide level1 center" data-background-color="#9b59b6">
<h1>Asymptotic Relative Efficiency</h1>

</section>
<section id="what-is-asymptotic-relative-efficiency" class="slide level2">
<h2>What Is Asymptotic Relative Efficiency?</h2>
<p><strong>Definition:</strong> The ARE of test <span class="math inline">\(T_1\)</span> relative to test <span class="math inline">\(T_2\)</span> is:</p>
<p><span class="math display">\[\text{ARE}(T_1, T_2) = \lim_{n \to \infty} \frac{n_2^*}{n_1^*}\]</span></p>
<p>where <span class="math inline">\(n_i^*\)</span> = sample size needed by test <span class="math inline">\(T_i\)</span> to achieve the <strong>same power</strong> at the same significance level <span class="math inline">\(\alpha\)</span> and the same effect size.</p>
<div class="fragment">
<p><strong>Interpretation:</strong></p>
<ul>
<li><span class="math inline">\(\text{ARE}(T_1, T_2) = 0.95\)</span>: <span class="math inline">\(T_1\)</span> needs <span class="math inline">\(n_2 / 0.95 \approx 1.05 n_2\)</span> observations — 5% more</li>
<li><span class="math inline">\(\text{ARE}(T_1, T_2) = 1.50\)</span>: <span class="math inline">\(T_1\)</span> needs only <span class="math inline">\(n_2 / 1.50 \approx 0.67 n_2\)</span> — 33% fewer!</li>
<li><span class="math inline">\(\text{ARE}(T_1, T_2) = 0.50\)</span>: <span class="math inline">\(T_1\)</span> needs twice as many observations</li>
</ul>
</div>
<div class="fragment">
<p>ARE is computed under a specific distributional family (the <strong>Pitman local alternatives</strong> framework) and tells us about asymptotic power, not finite-sample behavior — but it is a reliable guide in practice.</p>
</div>
</section>
<section id="are-pitman-efficiency-results" class="slide level2">
<h2>ARE: Pitman Efficiency Results</h2>
<p>The Pitman ARE for location-shift alternatives <span class="math inline">\(H_a: \theta = \theta_n = c/\sqrt{n}\)</span> (DBC 14.5, DBC p.&nbsp;681):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Distribution of <span class="math inline">\(D_i\)</span></th>
<th style="text-align: center;">ARE(sign / <span class="math inline">\(t\)</span>)</th>
<th style="text-align: center;">ARE(signed-rank / <span class="math inline">\(t\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normal</td>
<td style="text-align: center;"><span class="math inline">\(2/\pi \approx 0.637\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3/\pi \approx 0.955\)</span></td>
</tr>
<tr class="even">
<td>Logistic</td>
<td style="text-align: center;"><span class="math inline">\(\pi^2/12 \approx 0.822\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\pi^2/9 \approx 1.097\)</span></td>
</tr>
<tr class="odd">
<td>Double exponential (Laplace)</td>
<td style="text-align: center;"><span class="math inline">\(2.000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3/2 = 1.500\)</span></td>
</tr>
<tr class="even">
<td>Uniform</td>
<td style="text-align: center;"><span class="math inline">\(1/3 \approx 0.333\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.000\)</span></td>
</tr>
<tr class="odd">
<td>Cauchy (very heavy tails)</td>
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(t_\nu\)</span> (<span class="math inline">\(\nu\)</span> small)</td>
<td style="text-align: center;"><span class="math inline">\(&gt; 1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(&gt; 1\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Remarkable Result for the Signed-Rank Test</strong></p>
</div>
<div class="callout-content">
<ul>
<li>At <strong>normality</strong>: ARE(signed-rank, <span class="math inline">\(t\)</span>) = <span class="math inline">\(3/\pi \approx 0.955\)</span> — only <strong>4.5% efficiency loss</strong></li>
<li>The signed-rank test is <strong>never catastrophically bad</strong> — for all symmetric distributions, ARE <span class="math inline">\(\geq 0.864\)</span> (Hodges-Lehmann lower bound)</li>
<li>For heavy-tailed or non-normal distributions, the signed-rank test can be <strong>substantially more powerful</strong></li>
</ul>
<p>This makes it an excellent “default” for small <span class="math inline">\(n\)</span> when normality is uncertain.</p>
</div>
</div>
</div>
</div>
</section>
<section id="where-do-the-are-formulas-come-from" class="slide level2">
<h2>Where Do the ARE Formulas Come From?</h2>
<p>For the <strong>signed-rank test</strong> vs.&nbsp;the <span class="math inline">\(t\)</span>-test under the normal distribution:</p>
<p>The ARE can be computed using the <strong>Pitman formula</strong>:</p>
<p><span class="math display">\[\text{ARE}(W^+, t) = \frac{\left[E\left\{f(D)\right\}\right]^2 \cdot \text{Var}(D)}{\left[\frac{1}{2}f(0)\right]^2}\]</span></p>
<p>where <span class="math inline">\(f\)</span> is the density of <span class="math inline">\(D_i\)</span>.</p>
<p>For <span class="math inline">\(D_i \sim N(0, \sigma^2)\)</span>:</p>
<ul>
<li><span class="math inline">\(f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-x^2/(2\sigma^2)}\)</span>, so <span class="math inline">\(f(0) = \frac{1}{\sigma\sqrt{2\pi}}\)</span></li>
<li><span class="math inline">\(E\{f(D)\} = \int_{-\infty}^{\infty} f(x)^2 \, dx = \frac{1}{2\sigma\sqrt{\pi}}\)</span></li>
</ul>
<p>This gives <span class="math inline">\(\text{ARE} = \frac{3}{\pi} \approx 0.955\)</span>.</p>
<p>The analogous result for the sign test is <span class="math inline">\(\text{ARE}(\text{sign}, t) = 4\sigma^2 f(0)^2 = 2/\pi\)</span> under normality.</p>
</section>
<section id="are-power-simulation-across-distributions" class="slide level2">
<h2>ARE: Power Simulation Across Distributions</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb72-2"><a></a>B_are <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb72-3"><a></a></span>
<span id="cb72-4"><a></a>sim_power <span class="ot">&lt;-</span> <span class="cf">function</span>(n, effect, dist_fn) {</span>
<span id="cb72-5"><a></a>  <span class="fu">replicate</span>(B_are, {</span>
<span id="cb72-6"><a></a>    d <span class="ot">&lt;-</span> <span class="fu">dist_fn</span>(n) <span class="sc">+</span> effect</span>
<span id="cb72-7"><a></a>    nt <span class="ot">&lt;-</span> <span class="fu">sum</span>(d <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb72-8"><a></a>    sp <span class="ot">&lt;-</span> <span class="fu">sum</span>(d <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb72-9"><a></a>    <span class="fu">c</span>(</span>
<span id="cb72-10"><a></a>      <span class="at">t_test   =</span> <span class="fu">t.test</span>(d)<span class="sc">$</span>p.value,</span>
<span id="cb72-11"><a></a>      <span class="at">sign_p   =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">min</span>(<span class="fu">pbinom</span>(sp, nt, <span class="fl">0.5</span>),</span>
<span id="cb72-12"><a></a>                         <span class="fu">pbinom</span>(sp <span class="sc">-</span> <span class="dv">1</span>, nt, <span class="fl">0.5</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)),</span>
<span id="cb72-13"><a></a>      <span class="at">wilcoxon =</span> <span class="fu">wilcox.test</span>(d, <span class="at">exact =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>p.value</span>
<span id="cb72-14"><a></a>    )</span>
<span id="cb72-15"><a></a>  }) <span class="sc">|&gt;</span> <span class="fu">t</span>() <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb72-16"><a></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), \(x) <span class="fu">mean</span>(x <span class="sc">&lt;</span> <span class="fl">0.05</span>)))</span>
<span id="cb72-17"><a></a>}</span>
<span id="cb72-18"><a></a></span>
<span id="cb72-19"><a></a>dists <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb72-20"><a></a>  <span class="fu">list</span>(<span class="at">fn =</span> <span class="cf">function</span>(n) <span class="fu">rnorm</span>(n),                    <span class="at">label =</span> <span class="st">"Normal"</span>),</span>
<span id="cb72-21"><a></a>  <span class="fu">list</span>(<span class="at">fn =</span> <span class="cf">function</span>(n) <span class="fu">rt</span>(n, <span class="at">df =</span> <span class="dv">3</span>),               <span class="at">label =</span> <span class="fu">expression</span>(t[<span class="dv">3</span>] <span class="sc">~</span> <span class="st">"(heavy tails)"</span>)),</span>
<span id="cb72-22"><a></a>  <span class="fu">list</span>(<span class="at">fn =</span> <span class="cf">function</span>(n) <span class="fu">rexp</span>(n) <span class="sc">-</span> <span class="fu">log</span>(<span class="dv">2</span>),            <span class="at">label =</span> <span class="st">"Exponential</span><span class="sc">\n</span><span class="st">(shifted, skewed)"</span>),</span>
<span id="cb72-23"><a></a>  <span class="fu">list</span>(<span class="at">fn =</span> <span class="cf">function</span>(n) <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb72-24"><a></a>         (<span class="fu">runif</span>(n) <span class="sc">&lt;</span> <span class="fl">0.2</span>) <span class="sc">*</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">4</span>, <span class="at">sd =</span> <span class="dv">2</span>), <span class="at">label =</span> <span class="st">"Contaminated Normal</span><span class="sc">\n</span><span class="st">(outlier-prone)"</span>)</span>
<span id="cb72-25"><a></a>)</span>
<span id="cb72-26"><a></a></span>
<span id="cb72-27"><a></a>results_are <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(dists, <span class="cf">function</span>(dd) {</span>
<span id="cb72-28"><a></a>  <span class="fu">map_dfr</span>(<span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">50</span>), <span class="cf">function</span>(n) {</span>
<span id="cb72-29"><a></a>    <span class="fu">sim_power</span>(n, <span class="at">effect =</span> <span class="fl">0.5</span>, <span class="at">dist_fn =</span> dd<span class="sc">$</span>fn) <span class="sc">|&gt;</span></span>
<span id="cb72-30"><a></a>      <span class="fu">mutate</span>(<span class="at">n =</span> n, <span class="at">Distribution =</span> <span class="fu">as.character</span>(dd<span class="sc">$</span>label))</span>
<span id="cb72-31"><a></a>  })</span>
<span id="cb72-32"><a></a>})</span>
<span id="cb72-33"><a></a></span>
<span id="cb72-34"><a></a>results_are <span class="sc">|&gt;</span></span>
<span id="cb72-35"><a></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(t_test, sign_p, wilcoxon),</span>
<span id="cb72-36"><a></a>               <span class="at">names_to =</span> <span class="st">"Test"</span>, <span class="at">values_to =</span> <span class="st">"Power"</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-37"><a></a>  <span class="fu">mutate</span>(<span class="at">Test =</span> <span class="fu">recode</span>(Test,</span>
<span id="cb72-38"><a></a>                       <span class="at">t_test   =</span> <span class="st">"Paired t-test"</span>,</span>
<span id="cb72-39"><a></a>                       <span class="at">sign_p   =</span> <span class="st">"Sign test"</span>,</span>
<span id="cb72-40"><a></a>                       <span class="at">wilcoxon =</span> <span class="st">"Wilcoxon signed-rank"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb72-41"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> Power, <span class="at">color =</span> Test, <span class="at">linetype =</span> Test)) <span class="sc">+</span></span>
<span id="cb72-42"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb72-43"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb72-44"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.05</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb72-45"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Paired t-test"</span>        <span class="ot">=</span> <span class="st">"#006a4e"</span>,</span>
<span id="cb72-46"><a></a>                                 <span class="st">"Sign test"</span>            <span class="ot">=</span> <span class="st">"#e74c3c"</span>,</span>
<span id="cb72-47"><a></a>                                 <span class="st">"Wilcoxon signed-rank"</span> <span class="ot">=</span> <span class="st">"#3498db"</span>)) <span class="sc">+</span></span>
<span id="cb72-48"><a></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Paired t-test"</span>        <span class="ot">=</span> <span class="st">"solid"</span>,</span>
<span id="cb72-49"><a></a>                                    <span class="st">"Sign test"</span>            <span class="ot">=</span> <span class="st">"dashed"</span>,</span>
<span id="cb72-50"><a></a>                                    <span class="st">"Wilcoxon signed-rank"</span> <span class="ot">=</span> <span class="st">"solid"</span>)) <span class="sc">+</span></span>
<span id="cb72-51"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb72-52"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Distribution, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb72-53"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb72-54"><a></a>    <span class="at">title    =</span> <span class="st">"Power vs. Sample Size: Sign Test, Wilcoxon Signed-Rank, Paired t-test"</span>,</span>
<span id="cb72-55"><a></a>    <span class="at">subtitle =</span> <span class="st">"Effect size = 0.5. Signed-rank matches t-test at normality; both tests excel for heavy tails; sign test strongest for very skewed data"</span>,</span>
<span id="cb72-56"><a></a>    <span class="at">x =</span> <span class="st">"Sample size n (pairs)"</span>, <span class="at">y =</span> <span class="st">"Power"</span>,</span>
<span id="cb72-57"><a></a>    <span class="at">color =</span> <span class="cn">NULL</span>, <span class="at">linetype =</span> <span class="cn">NULL</span></span>
<span id="cb72-58"><a></a>  ) <span class="sc">+</span></span>
<span id="cb72-59"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb72-60"><a></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="21_NonparametricInference_files/figure-revealjs/unnamed-chunk-13-1.png" width="1536" class="r-stretch"></section>
<section id="are-interpreting-the-simulation" class="slide level2">
<h2>ARE: Interpreting the Simulation</h2>
<p>The simulation confirms the Pitman ARE theory:</p>
<ul>
<li><strong>Normal distribution</strong>: Signed-rank ≈ <span class="math inline">\(t\)</span>-test power (ARE <span class="math inline">\(\approx 0.955\)</span>). Sign test noticeably weaker (ARE <span class="math inline">\(\approx 0.637\)</span>).</li>
<li><strong><span class="math inline">\(t_3\)</span> distribution (heavy tails)</strong>: Both nonparametric tests <strong>outperform</strong> the <span class="math inline">\(t\)</span>-test. Signed-rank especially strong.</li>
<li><strong>Exponential (skewed)</strong>: Signed-rank invalid in principle (asymmetric <span class="math inline">\(D_i\)</span>), but often still competitive in practice. Sign test surprisingly strong.</li>
<li><strong>Contaminated normal</strong>: Even modest outlier contamination makes nonparametric tests superior.</li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical Takeaway for Biomedical Research</strong></p>
</div>
<div class="callout-content">
<p>Many biomarkers (CRP, troponin, liver enzymes) follow right-skewed, heavy-tailed distributions.</p>
<p>For such data with small <span class="math inline">\(n\)</span>:</p>
<ul>
<li><strong>Sign test</strong>: if ordinal data or very extreme outliers</li>
<li><strong>Wilcoxon signed-rank</strong>: best default for continuous paired data with uncertain normality</li>
<li><strong>Wilcoxon rank-sum</strong>: best default for independent two-group comparisons</li>
</ul>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="comparing-all-three-tests" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Comparing All Three Tests</h1>

</section>
<section id="decision-flowchart-which-test" class="slide level2">
<h2>Decision Flowchart: Which Test?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a></a><span class="fu">grViz</span>(<span class="st">"</span></span>
<span id="cb73-2"><a></a><span class="st">digraph test_selection {</span></span>
<span id="cb73-3"><a></a></span>
<span id="cb73-4"><a></a><span class="st">  graph [layout = dot, rankdir = TB, fontname = 'Helvetica', nodesep = 0.6]</span></span>
<span id="cb73-5"><a></a></span>
<span id="cb73-6"><a></a><span class="st">  node [shape = diamond, style = filled, fillcolor = '#f0f0f0',</span></span>
<span id="cb73-7"><a></a><span class="st">        fontsize = 14, margin = '0.2,0.1', fontname = 'Helvetica']</span></span>
<span id="cb73-8"><a></a><span class="st">  Q1 [label = 'Paired data or</span><span class="sc">\\</span><span class="st">none-sample?']</span></span>
<span id="cb73-9"><a></a><span class="st">  Q2 [label = 'Data ordinal or</span><span class="sc">\\</span><span class="st">nhighly asymmetric?']</span></span>
<span id="cb73-10"><a></a><span class="st">  Q3 [label = 'n large or</span><span class="sc">\\</span><span class="st">nnormality plausible?']</span></span>
<span id="cb73-11"><a></a><span class="st">  Q4 [label = 'n large or</span><span class="sc">\\</span><span class="st">nnormality plausible?']</span></span>
<span id="cb73-12"><a></a></span>
<span id="cb73-13"><a></a><span class="st">  node [shape = box, style = filled, fontsize = 14,</span></span>
<span id="cb73-14"><a></a><span class="st">        margin = '0.2,0.1', fontname = 'Helvetica']</span></span>
<span id="cb73-15"><a></a><span class="st">  T1 [label = 'Sign Test</span><span class="sc">\\</span><span class="st">n(Binomial)', fillcolor = '#3498db', fontcolor = white]</span></span>
<span id="cb73-16"><a></a><span class="st">  T2 [label = 'Wilcoxon</span><span class="sc">\\</span><span class="st">nSigned-Rank', fillcolor = '#e74c3c', fontcolor = white]</span></span>
<span id="cb73-17"><a></a><span class="st">  T3 [label = 'Paired t-test', fillcolor = '#006a4e', fontcolor = white]</span></span>
<span id="cb73-18"><a></a><span class="st">  T4 [label = 'Wilcoxon</span><span class="sc">\\</span><span class="st">nRank-Sum', fillcolor = '#27ae60', fontcolor = white]</span></span>
<span id="cb73-19"><a></a><span class="st">  T5 [label = 'Welch t-test</span><span class="sc">\\</span><span class="st">n(two independent)', fillcolor = '#9b59b6', fontcolor = white]</span></span>
<span id="cb73-20"><a></a></span>
<span id="cb73-21"><a></a><span class="st">  Q1 -&gt; Q2 [label = 'Yes']</span></span>
<span id="cb73-22"><a></a><span class="st">  Q1 -&gt; Q4 [label = 'No (two independent)']</span></span>
<span id="cb73-23"><a></a><span class="st">  Q2 -&gt; T1 [label = 'Yes / Ordinal']</span></span>
<span id="cb73-24"><a></a><span class="st">  Q2 -&gt; Q3 [label = 'No (continuous, symmetric)']</span></span>
<span id="cb73-25"><a></a><span class="st">  Q3 -&gt; T3 [label = 'Yes']</span></span>
<span id="cb73-26"><a></a><span class="st">  Q3 -&gt; T2 [label = 'No (small n, non-normal)']</span></span>
<span id="cb73-27"><a></a><span class="st">  Q4 -&gt; T5 [label = 'Yes']</span></span>
<span id="cb73-28"><a></a><span class="st">  Q4 -&gt; T4 [label = 'No (small n, non-normal)']</span></span>
<span id="cb73-29"><a></a><span class="st">}</span></span>
<span id="cb73-30"><a></a><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-6cea04e595ad2bdc0c4d" style="width:1344px;height:672px;"></div>
<script type="application/json" data-for="htmlwidget-6cea04e595ad2bdc0c4d">{"x":{"diagram":"\ndigraph test_selection {\n\n  graph [layout = dot, rankdir = TB, fontname = \"Helvetica\", nodesep = 0.6]\n\n  node [shape = diamond, style = filled, fillcolor = \"#f0f0f0\",\n        fontsize = 14, margin = \"0.2,0.1\", fontname = \"Helvetica\"]\n  Q1 [label = \"Paired data or\\none-sample?\"]\n  Q2 [label = \"Data ordinal or\\nhighly asymmetric?\"]\n  Q3 [label = \"n large or\\nnormality plausible?\"]\n  Q4 [label = \"n large or\\nnormality plausible?\"]\n\n  node [shape = box, style = filled, fontsize = 14,\n        margin = \"0.2,0.1\", fontname = \"Helvetica\"]\n  T1 [label = \"Sign Test\\n(Binomial)\", fillcolor = \"#3498db\", fontcolor = white]\n  T2 [label = \"Wilcoxon\\nSigned-Rank\", fillcolor = \"#e74c3c\", fontcolor = white]\n  T3 [label = \"Paired t-test\", fillcolor = \"#006a4e\", fontcolor = white]\n  T4 [label = \"Wilcoxon\\nRank-Sum\", fillcolor = \"#27ae60\", fontcolor = white]\n  T5 [label = \"Welch t-test\\n(two independent)\", fillcolor = \"#9b59b6\", fontcolor = white]\n\n  Q1 -> Q2 [label = \"Yes\"]\n  Q1 -> Q4 [label = \"No (two independent)\"]\n  Q2 -> T1 [label = \"Yes / Ordinal\"]\n  Q2 -> Q3 [label = \"No (continuous, symmetric)\"]\n  Q3 -> T3 [label = \"Yes\"]\n  Q3 -> T2 [label = \"No (small n, non-normal)\"]\n  Q4 -> T5 [label = \"Yes\"]\n  Q4 -> T4 [label = \"No (small n, non-normal)\"]\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="side-by-side-on-the-pain-score-data-sign-test-example" class="slide level2">
<h2>Side-by-Side on the Pain Score Data (Sign Test Example)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a><span class="fu">cat</span>(<span class="st">"=== SIGN TEST ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== SIGN TEST ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a></a>n_s <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_pain <span class="sc">!=</span> <span class="dv">0</span>); sp <span class="ot">&lt;-</span> <span class="fu">sum</span>(d_pain <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb76-2"><a></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"S+ = %d   n* = %d   one-sided p = %.5f</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb76-3"><a></a>            sp, n_s, <span class="fu">pbinom</span>(sp, n_s, <span class="fl">0.5</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>S+ = 0   n* = 15   one-sided p = 0.00003</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a></a><span class="fu">cat</span>(<span class="st">"=== WILCOXON SIGNED-RANK ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== WILCOXON SIGNED-RANK ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a></a><span class="fu">wilcox.test</span>(pain_after, pain_before, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb80-2"><a></a>            <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb80-3"><a></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb80-4"><a></a>  <span class="fu">select</span>(statistic, p.value, conf.low, conf.high, method) <span class="sc">|&gt;</span></span>
<span id="cb80-5"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic  p.value conf.low conf.high method                                  
      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                                   
1         0 0.000259     -Inf     -2.50 Wilcoxon signed rank test with continui…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a></a><span class="fu">cat</span>(<span class="st">"=== PAIRED t-TEST ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== PAIRED t-TEST ===</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a></a><span class="fu">t.test</span>(pain_after, pain_before, <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb85-2"><a></a>       <span class="at">alternative =</span> <span class="st">"less"</span>) <span class="sc">|&gt;</span></span>
<span id="cb85-3"><a></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span></span>
<span id="cb85-4"><a></a>  <span class="fu">select</span>(statistic, parameter, p.value, conf.low, method) <span class="sc">|&gt;</span></span>
<span id="cb85-5"><a></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic parameter  p.value conf.low method       
      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        
1     -14.3        14 4.91e-10     -Inf Paired t-test</code></pre>
</div>
</div>
<div class="fragment">
<p>All three strongly reject <span class="math inline">\(H_0\)</span>. The differences in <span class="math inline">\(p\)</span>-values reflect what information each test uses.</p>
</div>
</section>
<section id="summary-table-when-to-use-each-test" class="slide level2">
<h2>Summary Table: When to Use Each Test</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 40%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Use When</th>
<th>Caution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sign test</strong></td>
<td>Ordinal data; only sign matters; extreme asymmetry of <span class="math inline">\(D_i\)</span></td>
<td>Wastes magnitude information; lowest power</td>
</tr>
<tr class="even">
<td><strong>Wilcoxon signed-rank</strong></td>
<td>Continuous paired data; small <span class="math inline">\(n\)</span>; uncertain normality</td>
<td>Requires <strong>symmetric</strong> <span class="math inline">\(D_i\)</span>; not for ordinal-only data</td>
</tr>
<tr class="odd">
<td><strong>Wilcoxon rank-sum</strong></td>
<td>Two independent continuous groups; small <span class="math inline">\(n\)</span>; skewed</td>
<td>Requires <strong>continuous</strong> distributions; exact p-value affected by ties</td>
</tr>
<tr class="even">
<td><strong>Paired <span class="math inline">\(t\)</span>-test</strong></td>
<td>Paired; approximately normal <span class="math inline">\(D_i\)</span> or <span class="math inline">\(n \geq 30\)</span></td>
<td>Sensitive to heavy tails and outliers for small <span class="math inline">\(n\)</span></td>
</tr>
<tr class="odd">
<td><strong>Welch <span class="math inline">\(t\)</span>-test</strong></td>
<td>Two independent groups; approximately normal or <span class="math inline">\(n_i \geq 30\)</span></td>
<td>Heavy tails inflate Type I error for small <span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Default Recommendation for Biomedical Research</strong></p>
</div>
<div class="callout-content">
<p>For <strong>paired</strong> continuous <span class="math inline">\(D_i\)</span> with <span class="math inline">\(n &lt; 30\)</span> and uncertain normality: use <strong>Wilcoxon signed-rank</strong>. For <strong>two independent</strong> groups with small <span class="math inline">\(n\)</span> and skewed biomarkers: use <strong>Wilcoxon rank-sum</strong>.</p>
<p>If assumptions are met, the parametric test gains only ~5% efficiency — a small price for robustness.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="key-takeaways" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Key Takeaways</h1>

</section>
<section id="key-takeaways-dbc-14.114.3" class="slide level2 scrollable">
<h2>Key Takeaways (DBC 14.1–14.3)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nonparametric Inference: Main Points</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><p><strong>Sign test:</strong> <span class="math inline">\(S^+ \sim \text{Bin}(n^*, 1/2)\)</span> under <span class="math inline">\(H_0\)</span>; uses only direction of <span class="math inline">\(D_i\)</span>; valid for ordinal data; no symmetry assumption; lowest power of the three</p></li>
<li><p><strong>Wilcoxon signed-rank:</strong> ranks <span class="math inline">\(|D_i|\)</span>, sums ranks of positive differences; requires symmetric (not necessarily normal) continuous <span class="math inline">\(D_i\)</span>; ARE vs.&nbsp;<span class="math inline">\(t\)</span>-test <span class="math inline">\(= 3/\pi \approx 0.955\)</span> at normality — minimal efficiency loss, with gains for non-normal data; Hodges-Lehmann estimator is the associated point estimate</p></li>
<li><p><strong>Wilcoxon rank-sum (Mann–Whitney <span class="math inline">\(U\)</span>):</strong> pools and ranks all <span class="math inline">\(N\)</span> observations; sums group-1 ranks; tests <span class="math inline">\(H_0: F_1 = F_2\)</span>; <span class="math inline">\(U/(n_1 n_2)\)</span> estimates <span class="math inline">\(P(X_1 &gt; X_2)\)</span> = AUC; Hodges-Lehmann estimate = median of all <span class="math inline">\(n_1 \times n_2\)</span> pairwise differences</p></li>
<li><p><strong>ARE quantifies the asymptotic power trade-off:</strong> signed-rank ARE <span class="math inline">\(\geq 0.864\)</span> vs.&nbsp;<span class="math inline">\(t\)</span>-test for all symmetric distributions (Hodges-Lehmann lower bound) — never much worse at normality, potentially much better for heavy tails</p></li>
<li><p><strong>Nonparametric <span class="math inline">\(\neq\)</span> assumption-free:</strong> signed-rank requires <strong>symmetric</strong> <span class="math inline">\(D_i\)</span>; rank-sum requires <strong>continuous</strong> distributions; both require <strong>independent</strong> observations; ties require variance corrections</p></li>
<li><p><strong>Variance corrections for ties:</strong> both tests have modified variance formulas; R applies them automatically; heavy ties (e.g., ordinal data) reduce precision of rank-based tests — consider the sign test or permutation tests</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p><strong>Next class (Lesson 22): Course Review</strong></p>
<ul>
<li>Complete roadmap: from point estimation to nonparametric inference</li>
<li>Key theorems, formulas, and connections</li>
<li>Method selection guide</li>
<li>R function reference and practice problems</li>
</ul>
</section>
<section id="homework-problems" class="slide level2 scrollable">
<h2>Homework Problems</h2>
<p><strong>From Devore, Berk, and Carlton (Chapter 14):</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Problems</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>(DBC 14.1 / Sign Test)</strong> A clinical trial measured resting heart rate (bpm) in 12 patients before and after beta-blocker therapy. The differences (after − before) were: <span class="math inline">\(−8, −14, +3, −6, −11, −5, +2, −9, −7, −4, −12, −6\)</span>.
<ul>
<li><ol type="a">
<li>Carry out the sign test with <span class="math inline">\(H_a\)</span>: median <span class="math inline">\(&lt; 0\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>. Compute the exact p-value.</li>
</ol></li>
<li><ol start="2" type="a">
<li>What is <span class="math inline">\(S^+\)</span> and what is its null distribution? Why is this distribution exact?</li>
</ol></li>
</ul></li>
<li><strong>(DBC 14.2 / Wilcoxon Signed-Rank)</strong> Using the heart rate data from Problem 1:
<ul>
<li><ol type="a">
<li>Compute ranks of the absolute differences, noting any ties.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Compute <span class="math inline">\(W^+\)</span>, <span class="math inline">\(E[W^+]\)</span>, and <span class="math inline">\(\text{Var}(W^+)\)</span>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Compute the large-sample <span class="math inline">\(Z\)</span> statistic and p-value. Apply the continuity correction.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Verify with <code>wilcox.test()</code> in R. Why might the exact and asymptotic p-values differ?</li>
</ol></li>
</ul></li>
<li><strong>(DBC 14.3 / Rank-Sum)</strong> Serum albumin levels (g/dL) were measured in critically ill patients with (Group 1, <span class="math inline">\(n_1 = 10\)</span>) and without (Group 2, <span class="math inline">\(n_2 = 12\)</span>) acute kidney injury. Use R to:
<ul>
<li><ol type="a">
<li>Conduct the Wilcoxon rank-sum test (<span class="math inline">\(H_a\)</span>: Group 1 median <span class="math inline">\(&lt;\)</span> Group 2 median).</li>
</ol></li>
<li><ol start="2" type="a">
<li>Report the Hodges-Lehmann estimate and 95% CI for the location shift.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Compare conclusions to a Welch <span class="math inline">\(t\)</span>-test. Which test is more appropriate here, and why?</li>
</ol></li>
</ul></li>
<li><strong>(ARE / Conceptual)</strong> Suppose you have <span class="math inline">\(n = 25\)</span> paired differences known to follow a logistic distribution.
<ul>
<li><ol type="a">
<li>The ARE of the Wilcoxon signed-rank test relative to the paired <span class="math inline">\(t\)</span>-test is <span class="math inline">\(\pi^2/9 \approx 1.097\)</span>. Interpret this: how many pairs would the <span class="math inline">\(t\)</span>-test need to match the signed-rank test’s power?</li>
</ol></li>
<li><ol start="2" type="a">
<li>Give an intuitive explanation for why the rank-based test outperforms the <span class="math inline">\(t\)</span>-test for logistic data.</li>
</ol></li>
</ul></li>
</ol>
</div>
</div>
</div>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<ul>
<li>Devore, Berk, and Carlton. <em>Modern Mathematical Statistics with Applications</em> (Springer). Sections 14.1, 14.2, 14.3, 14.5.</li>
<li>Chihara, L. M. and Hesterberg, T. C. <em>Mathematical Statistics with Resampling and R</em> (Wiley). Chapter 3.</li>
<li>Hodges, J. L. and Lehmann, E. L. (1963). Estimates of location based on rank tests. <em>Annals of Mathematical Statistics</em>, 34(2), 598–611.</li>
<li>Wilcoxon, F. (1945). Individual comparisons by ranking methods. <em>Biometrics Bulletin</em>, 1(6), 80–83.</li>
<li>Mann, H. B. and Whitney, D. R. (1947). On a test of whether one of two random variables is stochastically larger than the other. <em>Annals of Mathematical Statistics</em>, 18(1), 50–60.</li>
</ul>
</section>
<section id="questions" class="slide level2 center" data-background-color="#3498db">
<h2>Questions?</h2>
<p>Thank you!</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lesson 21 - Nonparametric Inference</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1955,

        height: 1100,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>