<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a14e345711173c227b21482e2eb4cc70.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Jessica Minnier">
  <meta name="dcterms.date" content="2026-02-18">
  <title>Theory of Statistical Inference – Lesson 15: Neyman-Pearson Lemma; Likelihood Ratio Tests</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #383a42;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #383a42; } /* Normal */
    code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
    code span.an { color: #50a14f; } /* Annotation */
    code span.at { color: #a626a4; } /* Attribute */
    code span.bn { color: #986801; } /* BaseN */
    code span.bu { color: #a626a4; } /* BuiltIn */
    code span.cf { color: #a626a4; } /* ControlFlow */
    code span.ch { color: #50a14f; } /* Char */
    code span.cn { color: #986801; } /* Constant */
    code span.co { color: #a0a1a7; font-style: italic; } /* Comment */
    code span.cv { color: #e45649; font-style: italic; } /* CommentVar */
    code span.do { color: #e45649; } /* Documentation */
    code span.dt { color: #a626a4; } /* DataType */
    code span.dv { color: #986801; } /* DecVal */
    code span.er { color: #f44747; text-decoration: underline; } /* Error */
    code span.ex { color: #4078f2; font-weight: bold; } /* Extension */
    code span.fl { color: #986801; } /* Float */
    code span.fu { color: #4078f2; } /* Function */
    code span.im { color: #50a14f; } /* Import */
    code span.in { color: #c45b00; } /* Information */
    code span.kw { color: #a626a4; } /* Keyword */
    code span.op { color: #a626a4; } /* Operator */
    code span.ot { color: #27ae60; } /* Other */
    code span.pp { color: #a626a4; } /* Preprocessor */
    code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
    code span.sc { color: #0184bc; } /* SpecialChar */
    code span.ss { color: #da4453; } /* SpecialString */
    code span.st { color: #50a14f; } /* String */
    code span.va { color: #e45649; } /* Variable */
    code span.vs { color: #da4453; } /* VerbatimString */
    code span.wa { color: #da4453; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-2e74a31c1bd85ff20c819e764b562f47.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="../../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
  <script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
  <script src="../../site_libs/viz-1.8.2/viz.js"></script>
  <link href="../../site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
  <script src="../../site_libs/grViz-binding-1.0.11/grViz.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#006a4e" class="quarto-title-block center">
  <h1 class="title">Lesson 15: Neyman-Pearson Lemma; Likelihood Ratio Tests</h1>
  <p class="subtitle">BSTA 551: Statistical Inference</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jessica Minnier 
</div>
</div>
</div>

  <p class="date">2026-02-18</p>
</section>
<section>
<section id="lesson-15-neyman-pearson-lemma-likelihood-ratio-tests" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Lesson 15: Neyman-Pearson Lemma; Likelihood Ratio Tests</h1>

</section>
<section id="review-where-we-left-off" class="slide level2 scrollable">
<h2>Review: Where We Left Off</h2>
<p><strong>Lesson 14: P-Values; Power and Sample Size Determination</strong></p>
<ul>
<li>P-values are Uniform(0,1) under <span class="math inline">\(H_0\)</span> by the probability integral transformation</li>
<li>Power depends on the noncentrality parameter <span class="math inline">\(\delta = (\mu' - \mu_0)/(\sigma/\sqrt{n})\)</span></li>
<li>Sample size determination via <code>power.t.test()</code> for planning clinical trials</li>
<li>Multiple testing adjustments: Bonferroni (FWER) and Benjamini-Hochberg (FDR)</li>
</ul>
<div class="fragment">
<p><strong>Today’s Goals:</strong></p>
<ol type="1">
<li>Understand the concept of a <strong>most powerful</strong> test for simple hypotheses</li>
<li>State and prove the <strong>Neyman-Pearson Lemma</strong></li>
<li>Define <strong>power functions</strong> and <strong>uniformly most powerful (UMP)</strong> tests</li>
<li>Develop the <strong>likelihood ratio test (LRT)</strong> for composite hypotheses</li>
<li>Connect the LRT to familiar tests (z test, t test)</li>
<li>Apply the large-sample chi-squared approximation for LRTs</li>
</ol>
</div>
</section>
<section id="roadmap-for-today" class="slide level2">
<h2>Roadmap for Today</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Key Idea</th>
<th>Textbook</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple hypotheses</td>
<td>Both <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_a\)</span> fully specify the distribution</td>
<td>Devore 9.5</td>
</tr>
<tr class="even">
<td>Neyman-Pearson Lemma</td>
<td>The likelihood ratio test is most powerful for simple <span class="math inline">\(H_0\)</span> vs simple <span class="math inline">\(H_a\)</span></td>
<td>Devore 9.5</td>
</tr>
<tr class="odd">
<td>Power function</td>
<td><span class="math inline">\(\pi(\theta') = P_{\theta'}(\text{Reject } H_0)\)</span> as a function of <span class="math inline">\(\theta\)</span></td>
<td>Devore 9.5</td>
</tr>
<tr class="even">
<td>UMP tests</td>
<td>Most powerful for every value in the alternative</td>
<td>Devore 9.5</td>
</tr>
<tr class="odd">
<td>Likelihood ratio tests</td>
<td>General principle for composite hypotheses</td>
<td>Devore 9.5</td>
</tr>
<tr class="even">
<td>LRT <span class="math inline">\(\to\)</span> t test</td>
<td>The one-sample t test is a LRT</td>
<td>Devore 9.5</td>
</tr>
<tr class="odd">
<td>Large-sample LRT</td>
<td><span class="math inline">\(-2\ln(\Lambda) \xrightarrow{d} \chi^2_m\)</span></td>
<td>Devore 9.5</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why This Matters</strong></p>
</div>
<div class="callout-content">
<p>The Neyman-Pearson Lemma provides the <strong>theoretical foundation</strong> for optimal hypothesis testing. It tells us <em>why</em> the tests we have been using (z tests, t tests) are the best possible tests in their respective settings. The likelihood ratio principle then gives us a <strong>general recipe</strong> for constructing tests in new situations.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="simple-hypotheses-and-optimal-tests-devore-9.5" class="title-slide slide level1 center" data-background-color="#3498db">
<h1>Simple Hypotheses and Optimal Tests (Devore 9.5)</h1>

</section>
<section id="simple-vs.-composite-hypotheses" class="slide level2">
<h2>Simple vs.&nbsp;Composite Hypotheses</h2>
<p>Recall from Lesson 12:</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Definition (Simple and Composite Hypotheses)</strong></p>
</div>
<div class="callout-content">
<p>A hypothesis is <strong>simple</strong> if it completely specifies the distribution of the sample <span class="math inline">\(X_1, \ldots, X_n\)</span>. Otherwise, it is <strong>composite</strong>.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Examples:</strong></p>
<ul>
<li><span class="math inline">\(X_1, \ldots, X_n \stackrel{iid}{\sim} \text{Exp}(\lambda)\)</span>:
<ul>
<li><span class="math inline">\(H: \lambda = 5\)</span> is <strong>simple</strong> (distribution fully determined)</li>
<li><span class="math inline">\(H: \lambda &lt; 5\)</span> is <strong>composite</strong> (many possible distributions)</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\(X_1, \ldots, X_n \stackrel{iid}{\sim} N(\mu, \sigma^2)\)</span> with <span class="math inline">\(\sigma\)</span> <strong>known</strong>:
<ul>
<li><span class="math inline">\(H: \mu = 100\)</span> is <strong>simple</strong></li>
<li><span class="math inline">\(H: \mu \neq 100\)</span> is <strong>composite</strong></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\(X_1, \ldots, X_n \stackrel{iid}{\sim} N(\mu, \sigma^2)\)</span> with <span class="math inline">\(\sigma\)</span> <strong>unknown</strong>:
<ul>
<li><span class="math inline">\(H: \mu = 100\)</span> is <strong>composite</strong> (because <span class="math inline">\(\sigma\)</span> is unspecified — it is a <em>nuisance parameter</em>)</li>
</ul></li>
</ul>
</div>
</section>
<section id="the-optimality-question" class="slide level2">
<h2>The Optimality Question</h2>
<p>We have developed many test procedures: z tests, t tests, score tests, exact binomial tests…</p>
<div class="fragment">
<p><strong>But are these the <em>best</em> tests?</strong></p>
</div>
<div class="fragment">
<p>For a test of <span class="math inline">\(H_0: \theta = \theta_0\)</span> vs <span class="math inline">\(H_a: \theta = \theta_a\)</span>, both simple, there are infinitely many possible rejection regions <span class="math inline">\(R\)</span>. Each one gives:</p>
<ul>
<li>A <strong>Type I error rate</strong>: <span class="math inline">\(\alpha = P_{\theta_0}((X_1, \ldots, X_n) \in R)\)</span></li>
<li>A <strong>Type II error rate</strong>: <span class="math inline">\(\beta = P_{\theta_a}((X_1, \ldots, X_n) \notin R)\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Goal:</strong> Among all tests with <span class="math inline">\(\alpha \leq \alpha^*\)</span> (controlling Type I error), find the test that <strong>minimizes <span class="math inline">\(\beta\)</span></strong> (equivalently, <strong>maximizes power</strong>).</p>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Medical Research Motivation</strong></p>
</div>
<div class="callout-content">
<p>In a clinical trial comparing a new drug to a standard, we want the test that gives us the <strong>best chance of detecting a real treatment effect</strong> (high power) while maintaining the required significance level. The Neyman-Pearson Lemma tells us exactly how to construct such a test.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-likelihood-ratio-as-a-test-statistic" class="slide level2">
<h2>The Likelihood Ratio as a Test Statistic</h2>
<p><strong>Intuition:</strong> Given data <span class="math inline">\(x_1, \ldots, x_n\)</span>, which hypothesis makes the data more likely?</p>
<div class="fragment">
<p>Consider the ratio:</p>
<p><span class="math display">\[\Lambda^* = \frac{f(x_1, \ldots, x_n; \theta_a)}{f(x_1, \ldots, x_n; \theta_0)} = \frac{L(\theta_a)}{L(\theta_0)}\]</span></p>
</div>
<div class="fragment">
<ul>
<li>If <span class="math inline">\(\Lambda^* \gg 1\)</span>: data much more consistent with <span class="math inline">\(H_a\)</span> <span class="math inline">\(\Rightarrow\)</span> evidence against <span class="math inline">\(H_0\)</span></li>
<li>If <span class="math inline">\(\Lambda^* \approx 1\)</span>: data equally consistent with both <span class="math inline">\(\Rightarrow\)</span> no strong evidence</li>
<li>If <span class="math inline">\(\Lambda^* \ll 1\)</span>: data more consistent with <span class="math inline">\(H_0\)</span> <span class="math inline">\(\Rightarrow\)</span> no evidence against <span class="math inline">\(H_0\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Natural test:</strong> Reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(\Lambda^* \geq k\)</span> for some constant <span class="math inline">\(k &gt; 0\)</span>.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Convention Note</strong></p>
</div>
<div class="callout-content">
<p>Devore defines the NP ratio as <span class="math inline">\(L(\theta_a)/L(\theta_0)\)</span> (reject when large). Chihara defines it as <span class="math inline">\(L(\theta_0)/L(\theta_a)\)</span> (reject when small). Both formulations are equivalent — just inverted. We will primarily follow Devore’s convention in the statement of the lemma.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="the-neyman-pearson-lemma" class="title-slide slide level1 center" data-background-color="#e74c3c">
<h1>The Neyman-Pearson Lemma</h1>

</section>
<section id="statement-of-the-neyman-pearson-lemma" class="slide level2">
<h2>Statement of the Neyman-Pearson Lemma</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Neyman-Pearson Lemma (Devore 9.5)</strong></p>
</div>
<div class="callout-content">
<p>For testing a simple null hypothesis <span class="math inline">\(H_0: \theta = \theta_0\)</span> versus a simple alternative <span class="math inline">\(H_a: \theta = \theta_a\)</span>, let <span class="math inline">\(k\)</span> be a fixed positive number and form the rejection region</p>
<p><span class="math display">\[R^* = \left\{(x_1, \ldots, x_n): \frac{f(x_1, \ldots, x_n; \theta_a)}{f(x_1, \ldots, x_n; \theta_0)} \geq k \right\}\]</span></p>
<p>Let <span class="math inline">\(\alpha^* = P((X_1, \ldots, X_n) \in R^* \text{ when } \theta = \theta_0)\)</span> and let <span class="math inline">\(\beta^*\)</span> denote the Type II error probability.</p>
<p>Then for <strong>any other</strong> test procedure with Type I error probability <span class="math inline">\(\alpha \leq \alpha^*\)</span>, the Type II error probability must satisfy <span class="math inline">\(\beta \geq \beta^*\)</span>.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>In plain language:</strong> The test based on the likelihood ratio</p>
<ul>
<li>Has the <strong>smallest</strong> <span class="math inline">\(\beta\)</span> (Type II error) among all tests with <span class="math inline">\(\alpha \leq \alpha^*\)</span></li>
<li>Equivalently, has the <strong>largest power</strong> at <span class="math inline">\(\theta_a\)</span> among all level-<span class="math inline">\(\alpha^*\)</span> tests</li>
<li>Is called the <strong>most powerful (MP)</strong> test at level <span class="math inline">\(\alpha^*\)</span></li>
</ul>
</div>
</section>
<section id="proof-of-the-neyman-pearson-lemma" class="slide level2">
<h2>Proof of the Neyman-Pearson Lemma</h2>
<p>Let <span class="math inline">\(R\)</span> be the rejection region of <strong>any</strong> test, so that:</p>
<p><span class="math display">\[\alpha = \sum_R f(x_1, \ldots, x_n; \theta_0), \quad \beta = 1 - \sum_R f(x_1, \ldots, x_n; \theta_a)\]</span></p>
<div class="fragment">
<p>For any constant <span class="math inline">\(k &gt; 0\)</span>, consider the linear combination <span class="math inline">\(k\alpha + \beta\)</span>:</p>
<p><span class="math display">\[k\alpha + \beta = k \sum_R f(\mathbf{x}; \theta_0) + 1 - \sum_R f(\mathbf{x}; \theta_a) = 1 + \sum_R \left[k \cdot f(\mathbf{x}; \theta_0) - f(\mathbf{x}; \theta_a)\right]\]</span></p>
</div>
<div class="fragment">
<p><strong>Key insight:</strong> The expression <span class="math inline">\(k \cdot f(\mathbf{x}; \theta_0) - f(\mathbf{x}; \theta_a)\)</span> can be positive or negative. To <strong>minimize</strong> <span class="math inline">\(k\alpha + \beta\)</span>, choose <span class="math inline">\(R\)</span> to include exactly the points where this expression is negative:</p>
<p><span class="math display">\[R^* = \left\{\mathbf{x}: k \cdot f(\mathbf{x}; \theta_0) - f(\mathbf{x}; \theta_a) \leq 0\right\} = \left\{\mathbf{x}: \frac{f(\mathbf{x}; \theta_a)}{f(\mathbf{x}; \theta_0)} \geq k\right\}\]</span></p>
</div>
<div class="fragment">
<p>This is exactly the Neyman-Pearson rejection region! So <span class="math inline">\(R^*\)</span> minimizes <span class="math inline">\(k\alpha + \beta\)</span>.</p>
</div>
</section>
<section id="proof-continued" class="slide level2">
<h2>Proof (continued)</h2>
<p>We’ve shown: <span class="math inline">\(k\alpha^* + \beta^* \leq k\alpha + \beta\)</span> for <strong>all</strong> rejection regions <span class="math inline">\(R\)</span>.</p>
<div class="fragment">
<p>Now, for any test with <span class="math inline">\(\alpha \leq \alpha^*\)</span>:</p>
<p><span class="math display">\[k\alpha^* + \beta^* \leq k\alpha + \beta\]</span></p>
<p><span class="math display">\[\beta^* \leq \beta + k(\alpha - \alpha^*) \leq \beta + k \cdot 0 = \beta\]</span></p>
</div>
<div class="fragment">
<p>since <span class="math inline">\(\alpha - \alpha^* \leq 0\)</span> and <span class="math inline">\(k &gt; 0\)</span>.</p>
</div>
<div class="fragment">
<p>Therefore <span class="math inline">\(\beta^* \leq \beta\)</span> for all tests with <span class="math inline">\(\alpha \leq \alpha^*\)</span>. <span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>What Does This Mean?</strong></p>
</div>
<div class="callout-content">
<p>The proof works by showing that the NP rejection region simultaneously minimizes <strong>both</strong> <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> in a trade-off sense. You cannot do better on one without doing worse on the other. The NP test is on the <strong>efficient frontier</strong> of the <span class="math inline">\((\alpha, \beta)\)</span> trade-off.</p>
</div>
</div>
</div>
</div>
</section>
<section id="example-adverse-events-in-a-drug-trial-normal-known-sigma" class="slide level2">
<h2>Example: Adverse Events in a Drug Trial (Normal, Known <span class="math inline">\(\sigma\)</span>)</h2>
<p>A pharmaceutical company monitors a biomarker level in patients. Under the current treatment, biomarker levels follow <span class="math inline">\(N(\mu, 1)\)</span>. An elevated biomarker signals a potential adverse event.</p>
<p>Test <span class="math inline">\(H_0: \mu = 5\)</span> vs <span class="math inline">\(H_a: \mu = 6\)</span> based on <span class="math inline">\(n\)</span> patients (known <span class="math inline">\(\sigma = 1\)</span>).</p>
<div class="fragment">
<p><strong>Applying the Neyman-Pearson Lemma:</strong></p>
<p><span class="math display">\[\frac{L(\mu_a = 6)}{L(\mu_0 = 5)} = \frac{\prod_{i=1}^n \frac{1}{\sqrt{2\pi}} e^{-(x_i - 6)^2/2}}{\prod_{i=1}^n \frac{1}{\sqrt{2\pi}} e^{-(x_i - 5)^2/2}} = e^{\sum (x_i - 6)^2/2 \cdot (-1) + \sum(x_i - 5)^2/2}\]</span></p>
</div>
<div class="fragment">
<p>Simplifying the exponent:</p>
<p><span class="math display">\[= e^{(6 - 5)\sum x_i - n(6^2 - 5^2)/2} = e^{\sum x_i - 11n/2}\]</span></p>
</div>
</section>
<section id="example-normal-continued" class="slide level2">
<h2>Example: Normal (continued)</h2>
<p>The rejection region <span class="math inline">\(\Lambda^* \geq k\)</span> becomes:</p>
<p><span class="math display">\[e^{\sum x_i - 11n/2} \geq k\]</span></p>
<div class="fragment">
<p>Taking logarithms (since <span class="math inline">\(\mu_a - \mu_0 = 1 &gt; 0\)</span>, the exponential is increasing in <span class="math inline">\(\sum x_i\)</span>):</p>
<p><span class="math display">\[\sum x_i \geq k' \quad \iff \quad \bar{x} \geq k'' \quad \iff \quad \frac{\bar{x} - 5}{1/\sqrt{n}} \geq c\]</span></p>
</div>
<div class="fragment">
<p>Setting <span class="math inline">\(c = z_\alpha\)</span>, this is exactly the <strong>one-sample z test</strong>!</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Result (Devore Example 9.24)</strong></p>
</div>
<div class="callout-content">
<p>For <span class="math inline">\(X_1, \ldots, X_n \stackrel{iid}{\sim} N(\mu, \sigma^2)\)</span> with <span class="math inline">\(\sigma\)</span> known, testing <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs <span class="math inline">\(H_a: \mu = \mu_a\)</span> where <span class="math inline">\(\mu_a &gt; \mu_0\)</span>:</p>
<p>The Neyman-Pearson Lemma shows that the <strong>one-sample z test</strong> (reject when <span class="math inline">\(z \geq z_\alpha\)</span>) is the <strong>most powerful</strong> test at level <span class="math inline">\(\alpha\)</span>. Our familiar z test is optimal!</p>
</div>
</div>
</div>
</div>
</section>
<section id="example-poisson-adverse-event-counts-devore-example-9.23" class="slide level2">
<h2>Example: Poisson Adverse Event Counts (Devore Example 9.23)</h2>
<p>In post-market drug surveillance, the number of adverse events per reporting period is monitored. Suppose <span class="math inline">\(X_1, \ldots, X_5 \stackrel{iid}{\sim} \text{Poisson}(\lambda)\)</span> represent adverse event counts over 5 periods.</p>
<p>Test <span class="math inline">\(H_0: \lambda = 1\)</span> (baseline rate) vs <span class="math inline">\(H_a: \lambda = 2\)</span> (elevated rate).</p>
<div class="fragment">
<p><strong>The Poisson likelihood is:</strong> <span class="math inline">\(f(x_1, \ldots, x_5; \lambda) = e^{-5\lambda} \lambda^{\sum x_i} / \prod x_i!\)</span></p>
</div>
<div class="fragment">
<p><strong>The likelihood ratio:</strong></p>
<p><span class="math display">\[\frac{L(\lambda = 2)}{L(\lambda = 1)} = \frac{e^{-10} \cdot 2^{\sum x_i}}{e^{-5} \cdot 1^{\sum x_i}} = e^{-5} \cdot 2^{\sum x_i} \geq k\]</span></p>
</div>
<div class="fragment">
<p>Taking logarithms: <span class="math inline">\(\sum x_i \geq c\)</span> where <span class="math inline">\(c = \ln(k \cdot e^5)/\ln(2)\)</span>.</p>
</div>
</section>
<section id="example-poisson-continued" class="slide level2">
<h2>Example: Poisson (continued)</h2>
<p><strong>Finding the critical value:</strong> Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(Y = \sum X_i \sim \text{Poisson}(5)\)</span>.</p>
<div class="fragment">
<p>If we use <span class="math inline">\(c = 10\)</span>: <span class="math inline">\(\alpha^* = P(Y \geq 10 \mid Y \sim \text{Poisson}(5)) = 1 - 0.968 = 0.032\)</span></p>
<p>If we use <span class="math inline">\(c = 9\)</span>: <span class="math inline">\(\alpha^* = P(Y \geq 9 \mid Y \sim \text{Poisson}(5)) = 1 - 0.932 = 0.068\)</span></p>
</div>
<div class="fragment">
<p>For <span class="math inline">\(\alpha \leq 0.05\)</span>, we use <span class="math inline">\(c = 10\)</span>, giving <span class="math inline">\(\alpha^* = 0.032\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Type II error:</strong> Under <span class="math inline">\(H_a\)</span>, <span class="math inline">\(Y \sim \text{Poisson}(10)\)</span>.</p>
<p><span class="math display">\[\beta^* = P(Y &lt; 10 \mid Y \sim \text{Poisson}(10)) = 0.458\]</span></p>
</div>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># Verify with R</span></span>
<span id="cb1-2"><a></a><span class="fu">cat</span>(<span class="st">"alpha* ="</span>, <span class="dv">1</span> <span class="sc">-</span> <span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>alpha* = 0.03182806 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">cat</span>(<span class="st">"beta*  ="</span>, <span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">10</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>beta*  = 0.4579297 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">cat</span>(<span class="st">"Power  ="</span>, <span class="dv">1</span> <span class="sc">-</span> <span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">10</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Power  = 0.5420703 </code></pre>
</div>
</div>
</div>
</section>
<section id="example-poisson-continued-1" class="slide level2">
<h2>Example: Poisson (continued)</h2>
<p><strong>The Neyman-Pearson guarantee:</strong> Any other test with <span class="math inline">\(\alpha \leq 0.032\)</span> must have <span class="math inline">\(\beta \geq 0.458\)</span>.</p>
<div class="fragment">
<p>The power is only <span class="math inline">\(1 - 0.458 = 0.542\)</span>. Why so low?</p>
</div>
<div class="fragment">
<p><strong>Because <span class="math inline">\(n = 5\)</span> is too small</strong> to discriminate between <span class="math inline">\(\lambda = 1\)</span> and <span class="math inline">\(\lambda = 2\)</span>.</p>
<p>For <span class="math inline">\(n = 10\)</span>: best test with <span class="math inline">\(\alpha \leq 0.05\)</span> uses <span class="math inline">\(c = 16\)</span>, giving <span class="math inline">\(\alpha^* = 0.049\)</span> and <span class="math inline">\(\beta^* = 0.157\)</span> (power = 0.843).</p>
</div>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># Compare rejection regions for n=5 and n=10</span></span>
<span id="cb7-2"><a></a><span class="fu">tibble</span>(<span class="at">y =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">30</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-4"><a></a>    <span class="st">`</span><span class="at">n = 5, Poisson(5)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">dpois</span>(y, <span class="dv">5</span>),</span>
<span id="cb7-5"><a></a>    <span class="st">`</span><span class="at">n = 5, Poisson(10)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">dpois</span>(y, <span class="dv">10</span>),</span>
<span id="cb7-6"><a></a>    <span class="st">`</span><span class="at">n = 10, Poisson(10)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">dpois</span>(y, <span class="dv">10</span>),</span>
<span id="cb7-7"><a></a>    <span class="st">`</span><span class="at">n = 10, Poisson(20)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">dpois</span>(y, <span class="dv">20</span>)</span>
<span id="cb7-8"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>y, <span class="at">names_to =</span> <span class="st">"distribution"</span>, <span class="at">values_to =</span> <span class="st">"prob"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-10"><a></a>  <span class="fu">separate</span>(distribution, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"sample_size"</span>, <span class="st">"dist"</span>), <span class="at">sep =</span> <span class="st">", "</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-11"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> y, <span class="at">y =</span> prob, <span class="at">fill =</span> dist)) <span class="sc">+</span></span>
<span id="cb7-12"><a></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">width =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb7-13"><a></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">sample_size =</span> <span class="fu">c</span>(<span class="st">"n = 5"</span>, <span class="st">"n = 10"</span>), </span>
<span id="cb7-14"><a></a>                            <span class="at">cutoff =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">16</span>)),</span>
<span id="cb7-15"><a></a>             <span class="fu">aes</span>(<span class="at">xintercept =</span> cutoff <span class="sc">-</span> <span class="fl">0.5</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb7-16"><a></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-17"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sample_size, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"coral"</span>, <span class="st">"steelblue"</span>, <span class="st">"coral"</span>)) <span class="sc">+</span></span>
<span id="cb7-19"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(y <span class="sc">==</span> <span class="fu">sum</span>(x[i])), <span class="at">y =</span> <span class="st">"Probability"</span>,</span>
<span id="cb7-20"><a></a>       <span class="at">title =</span> <span class="st">"Neyman-Pearson Test: Poisson Adverse Event Monitoring"</span>,</span>
<span id="cb7-21"><a></a>       <span class="at">subtitle =</span> <span class="st">"Red dashed line = rejection boundary; larger n gives better separation"</span>) <span class="sc">+</span></span>
<span id="cb7-22"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-2-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="medical-example-exponential-survival-times-ch-example-8.18" class="slide level2">
<h2>Medical Example: Exponential Survival Times (C&amp;H Example 8.18)</h2>
<p>In an oncology trial, patient survival times follow <span class="math inline">\(\text{Exp}(\lambda)\)</span>. We want to test whether the hazard rate has increased from a historical baseline.</p>
<p>Test <span class="math inline">\(H_0: \lambda = 8\)</span> vs <span class="math inline">\(H_a: \lambda = 10\)</span> based on <span class="math inline">\(n = 9\)</span> patients.</p>
<div class="fragment">
<p><strong>Likelihood ratio:</strong></p>
<p><span class="math display">\[\frac{L(\lambda = 8)}{L(\lambda = 10)} = \frac{8^9 e^{-8\sum x_i}}{10^9 e^{-10\sum x_i}} = (0.8)^9 e^{2\sum x_i}\]</span></p>
</div>
<div class="fragment">
<p>(Note: Chihara uses <span class="math inline">\(L(\theta_0)/L(\theta_a)\)</span>, rejecting for small values.)</p>
<p>Reject <span class="math inline">\(H_0\)</span> when this ratio is small, i.e., when <span class="math inline">\(\sum x_i &lt; c_2\)</span>.</p>
</div>
<div class="fragment">
<p>Under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\sum_{i=1}^9 X_i \sim \text{Gamma}(9, 8)\)</span>. For <span class="math inline">\(\alpha = 0.05\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>c2 <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="fl">0.05</span>, <span class="at">shape =</span> <span class="dv">9</span>, <span class="at">rate =</span> <span class="dv">8</span>)</span>
<span id="cb8-2"><a></a><span class="fu">cat</span>(<span class="st">"Critical value c2 ="</span>, <span class="fu">round</span>(c2, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical value c2 = 0.5869 </code></pre>
</div>
</div>
<p>By the Neyman-Pearson Lemma, this is the <strong>best possible</strong> test at this significance level.</p>
</div>
</section></section>
<section>
<section id="power-functions-and-ump-tests" class="title-slide slide level1 center" data-background-color="#27ae60">
<h1>Power Functions and UMP Tests</h1>

</section>
<section id="the-power-function" class="slide level2">
<h2>The Power Function</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Definition (Power Function, Devore 9.5)</strong></p>
</div>
<div class="callout-content">
<p>Let <span class="math inline">\(\Omega_0\)</span> and <span class="math inline">\(\Omega_a\)</span> be two disjoint sets of possible values of <span class="math inline">\(\theta\)</span>. For testing <span class="math inline">\(H_0: \theta \in \Omega_0\)</span> vs <span class="math inline">\(H_a: \theta \in \Omega_a\)</span> with rejection region <span class="math inline">\(R\)</span>, the <strong>power function</strong> is:</p>
<p><span class="math display">\[\pi(\theta') = P_{\theta'}((X_1, \ldots, X_n) \in R)\]</span></p>
<p>the probability of rejecting <span class="math inline">\(H_0\)</span> as a function of <span class="math inline">\(\theta\)</span>.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Connection to error probabilities:</strong></p>
<p><span class="math display">\[\pi(\theta') = \begin{cases} P(\text{Type I error}) = \alpha(\theta') &amp; \text{when } \theta' \in \Omega_0 \\[4pt] 1 - P(\text{Type II error}) = 1 - \beta(\theta') &amp; \text{when } \theta' \in \Omega_a \end{cases}\]</span></p>
</div>
<div class="fragment">
<p><strong>Ideal power function</strong> (unachievable in practice):</p>
<p><span class="math display">\[\pi(\theta') = \begin{cases} 0 &amp; \text{when } \theta' \in \Omega_0 \\ 1 &amp; \text{when } \theta' \in \Omega_a \end{cases}\]</span></p>
</div>
</section>
<section id="visualizing-the-power-function" class="slide level2">
<h2>Visualizing the Power Function</h2>
<p><strong>Example (Devore 9.25 adapted):</strong> Blood pressure reduction (mmHg) with a new antihypertensive follows <span class="math inline">\(N(\mu, 81)\)</span>. Test <span class="math inline">\(H_0: \mu \leq 75\)</span> vs <span class="math inline">\(H_a: \mu &lt; 75\)</span> with <span class="math inline">\(n = 100\)</span>, <span class="math inline">\(\alpha = 0.10\)</span>.</p>
<p>Rejection region: <span class="math inline">\(z \leq -z_{0.10} = -1.28\)</span>, i.e., <span class="math inline">\(\bar{x} \leq 73.848\)</span>.</p>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="co"># Power function for the z test</span></span>
<span id="cb10-2"><a></a>sigma <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb10-3"><a></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb10-4"><a></a>se <span class="ot">&lt;-</span> sigma <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb10-5"><a></a>x_crit <span class="ot">&lt;-</span> <span class="dv">75</span> <span class="sc">-</span> <span class="fl">1.28</span> <span class="sc">*</span> se  <span class="co"># 73.848</span></span>
<span id="cb10-6"><a></a></span>
<span id="cb10-7"><a></a>mu_prime <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">68</span>, <span class="dv">78</span>, <span class="at">length.out =</span> <span class="dv">500</span>)</span>
<span id="cb10-8"><a></a>power_actual <span class="ot">&lt;-</span> <span class="fu">pnorm</span>((x_crit <span class="sc">-</span> mu_prime) <span class="sc">/</span> se)</span>
<span id="cb10-9"><a></a></span>
<span id="cb10-10"><a></a>power_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">mu =</span> mu_prime, <span class="at">power =</span> power_actual)</span>
<span id="cb10-11"><a></a></span>
<span id="cb10-12"><a></a><span class="fu">ggplot</span>(power_df, <span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> power)) <span class="sc">+</span></span>
<span id="cb10-13"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb10-14"><a></a>  <span class="co"># Ideal power function</span></span>
<span id="cb10-15"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">68</span>, <span class="at">xend =</span> <span class="dv">75</span>, <span class="at">y =</span> <span class="dv">1</span>, <span class="at">yend =</span> <span class="dv">1</span>), </span>
<span id="cb10-16"><a></a>               <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-17"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">75</span>, <span class="at">xend =</span> <span class="dv">78</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> <span class="dv">0</span>), </span>
<span id="cb10-18"><a></a>               <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-19"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">75</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb10-20"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.10</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb10-21"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">76.5</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">label =</span> <span class="st">"Ideal"</span>, <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">size =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb10-22"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">70</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">label =</span> <span class="st">"Actual"</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb10-23"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">77</span>, <span class="at">y =</span> <span class="fl">0.12</span>, </span>
<span id="cb10-24"><a></a>           <span class="at">label =</span> <span class="fu">expression</span>(alpha <span class="sc">==</span> <span class="fl">0.10</span>), <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"gray30"</span>) <span class="sc">+</span></span>
<span id="cb10-25"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">75.3</span>, <span class="at">y =</span> <span class="fl">0.5</span>, </span>
<span id="cb10-26"><a></a>           <span class="at">label =</span> <span class="fu">expression</span>(mu[<span class="dv">0</span>] <span class="sc">==</span> <span class="dv">75</span>), <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"gray30"</span>) <span class="sc">+</span></span>
<span id="cb10-27"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb10-28"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu <span class="sc">*</span> <span class="st">"' (true mean)"</span>), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">pi</span>(mu <span class="sc">*</span> <span class="st">"'"</span>)),</span>
<span id="cb10-29"><a></a>       <span class="at">title =</span> <span class="st">"Power Function for the Lower-Tailed z Test"</span>,</span>
<span id="cb10-30"><a></a>       <span class="at">subtitle =</span> <span class="fu">bquote</span>(<span class="st">"Testing"</span> <span class="sc">~</span> H[<span class="dv">0</span>]<span class="sc">*</span><span class="st">":"</span> <span class="sc">~</span> mu <span class="sc">&lt;=</span> <span class="dv">75</span> <span class="sc">~</span> <span class="st">"vs"</span> <span class="sc">~</span> H[a]<span class="sc">*</span><span class="st">":"</span> <span class="sc">~</span> mu <span class="sc">&lt;</span> <span class="dv">75</span> <span class="sc">~</span> <span class="st">"with n = 100,"</span> <span class="sc">~</span> sigma <span class="sc">==</span> <span class="dv">9</span><span class="sc">*</span><span class="st">","</span> <span class="sc">~</span> alpha <span class="sc">==</span> <span class="fl">0.10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-4-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="properties-of-the-power-function" class="slide level2 scrollable">
<h2>Properties of the Power Function</h2>
<p>From the figure, we observe several important properties:</p>
<div class="fragment">
<ol type="1">
<li><strong>At the boundary</strong> (<span class="math inline">\(\mu = 75\)</span>): <span class="math inline">\(\pi(75) = \alpha = 0.10\)</span> by design</li>
</ol>
</div>
<div class="fragment">
<ol start="2" type="1">
<li><strong>In <span class="math inline">\(\Omega_0\)</span></strong> (<span class="math inline">\(\mu &gt; 75\)</span>): <span class="math inline">\(\pi(\mu') &lt; 0.10\)</span> — power is below <span class="math inline">\(\alpha\)</span> (good!)</li>
</ol>
</div>
<div class="fragment">
<ol start="3" type="1">
<li><strong>Near the boundary</strong> (<span class="math inline">\(\mu\)</span> slightly below 75): power is barely above <span class="math inline">\(\alpha\)</span> — small departures are hard to detect</li>
</ol>
</div>
<div class="fragment">
<ol start="4" type="1">
<li><strong>Far from <span class="math inline">\(H_0\)</span></strong> (<span class="math inline">\(\mu \ll 75\)</span>): <span class="math inline">\(\pi(\mu') \to 1\)</span> — large departures are easily detected</li>
</ol>
</div>
<div class="fragment">
<ol start="5" type="1">
<li><strong>As <span class="math inline">\(n\)</span> increases:</strong> the actual power function approaches the ideal step function</li>
</ol>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Clinical Implication</strong></p>
</div>
<div class="callout-content">
<p>In designing a clinical trial, we need to choose <span class="math inline">\(n\)</span> large enough so that the power function is acceptably close to 1 at the <strong>minimum clinically important difference</strong>. This connects directly to the sample size calculations from Lesson 14.</p>
</div>
</div>
</div>
</div>
</section>
<section id="uniformly-most-powerful-ump-tests" class="slide level2">
<h2>Uniformly Most Powerful (UMP) Tests</h2>
<p>The NP Lemma handles simple vs simple. What about composite alternatives?</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Definition (Uniformly Most Powerful Test)</strong></p>
</div>
<div class="callout-content">
<p>A test is <strong>uniformly most powerful (UMP)</strong> at level <span class="math inline">\(\alpha\)</span> if it maximizes <span class="math inline">\(\pi(\theta')\)</span> for <strong>every</strong> <span class="math inline">\(\theta' \in \Omega_a\)</span>, subject to <span class="math inline">\(\pi(\theta') \leq \alpha\)</span> for all <span class="math inline">\(\theta' \in \Omega_0\)</span>.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>When do UMP tests exist?</strong> If the NP rejection region <strong>does not depend on the specific alternative</strong> <span class="math inline">\(\theta_a\)</span>, then the same test is most powerful for <em>every</em> <span class="math inline">\(\theta_a \in \Omega_a\)</span>.</p>
</div>
</section>
<section id="ump-example-poisson-devore-example-9.26" class="slide level2">
<h2>UMP Example: Poisson (Devore Example 9.26)</h2>
<p>Returning to the Poisson adverse event example with <span class="math inline">\(n = 5\)</span>:</p>
<p>Test <span class="math inline">\(H_0: \lambda \leq 1\)</span> vs <span class="math inline">\(H_a: \lambda &gt; 1\)</span>.</p>
<div class="fragment">
<p>For <strong>any</strong> specific <span class="math inline">\(\lambda_a &gt; 1\)</span>, the NP test of <span class="math inline">\(H_0: \lambda = 1\)</span> vs <span class="math inline">\(H_a: \lambda = \lambda_a\)</span> rejects when <span class="math inline">\(\sum x_i \geq c\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Key observation:</strong> The rejection region <span class="math inline">\(\sum x_i \geq 10\)</span> is the <strong>same</strong> regardless of which <span class="math inline">\(\lambda_a &gt; 1\)</span> we choose! (The critical value <span class="math inline">\(c\)</span> is determined by <span class="math inline">\(H_0\)</span> alone.)</p>
</div>
<div class="fragment">
<p>Therefore, this test is <strong>UMP</strong> at level <span class="math inline">\(\alpha^* = 0.032\)</span>.</p>
</div>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># Power function for the UMP Poisson test</span></span>
<span id="cb11-2"><a></a>lambda_prime <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">300</span>)</span>
<span id="cb11-3"><a></a>power_poisson <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">5</span> <span class="sc">*</span> lambda_prime)</span>
<span id="cb11-4"><a></a></span>
<span id="cb11-5"><a></a><span class="fu">ggplot</span>(<span class="fu">tibble</span>(<span class="at">lambda =</span> lambda_prime, <span class="at">power =</span> power_poisson), </span>
<span id="cb11-6"><a></a>       <span class="fu">aes</span>(<span class="at">x =</span> lambda, <span class="at">y =</span> power)) <span class="sc">+</span></span>
<span id="cb11-7"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb11-9"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.032</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="fl">0.08</span>, </span>
<span id="cb11-11"><a></a>           <span class="at">label =</span> <span class="fu">expression</span>(alpha <span class="sc">*</span> <span class="st">"* = 0.032"</span>), <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb11-12"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">1.15</span>, <span class="at">y =</span> <span class="fl">0.5</span>, </span>
<span id="cb11-13"><a></a>           <span class="at">label =</span> <span class="fu">expression</span>(lambda[<span class="dv">0</span>] <span class="sc">==</span> <span class="dv">1</span>), <span class="at">color =</span> <span class="st">"gray40"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(lambda <span class="sc">*</span> <span class="st">"' (true Poisson rate)"</span>), </span>
<span id="cb11-15"><a></a>       <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">pi</span>(lambda <span class="sc">*</span> <span class="st">"'"</span>)),</span>
<span id="cb11-16"><a></a>       <span class="at">title =</span> <span class="fu">bquote</span>(<span class="st">"Power Function of the UMP Test for"</span> <span class="sc">~</span> H[<span class="dv">0</span>]<span class="sc">*</span><span class="st">":"</span> <span class="sc">~</span> lambda <span class="sc">&lt;=</span> <span class="dv">1</span>),</span>
<span id="cb11-17"><a></a>       <span class="at">subtitle =</span> <span class="fu">bquote</span>(<span class="st">"Reject when"</span> <span class="sc">~</span> <span class="fu">sum</span>(X[i], i<span class="sc">==</span><span class="dv">1</span>, <span class="dv">5</span>) <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"; maximizes power for every"</span> <span class="sc">~</span> lambda <span class="sc">&gt;</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-5-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="when-ump-tests-dont-exist" class="slide level2">
<h2>When UMP Tests Don’t Exist</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important Limitation</strong></p>
</div>
<div class="callout-content">
<p>UMP tests are <strong>fairly rare</strong>, especially in the commonly encountered situation of testing a two-sided alternative.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Example:</strong> Testing <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs <span class="math inline">\(H_a: \mu \neq \mu_0\)</span> with <span class="math inline">\(X_i \stackrel{iid}{\sim} N(\mu, \sigma^2)\)</span>, <span class="math inline">\(\sigma\)</span> known.</p>
<ul>
<li>For <span class="math inline">\(\mu_a &gt; \mu_0\)</span>: NP test rejects when <span class="math inline">\(\bar{x}\)</span> is <strong>large</strong> (upper tail)</li>
<li>For <span class="math inline">\(\mu_a &lt; \mu_0\)</span>: NP test rejects when <span class="math inline">\(\bar{x}\)</span> is <strong>small</strong> (lower tail)</li>
<li>These are <strong>different rejection regions</strong> — no single test is best for all <span class="math inline">\(\mu_a \neq \mu_0\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Resolution:</strong> Restrict attention to <strong>unbiased tests</strong> (tests where <span class="math inline">\(\pi(\theta') \geq \alpha\)</span> for all <span class="math inline">\(\theta' \in \Omega_a\)</span>). Under this restriction:</p>
<ul>
<li>The two-sided z test is <strong>UMP unbiased</strong> when <span class="math inline">\(\sigma\)</span> is known</li>
<li>The one-sample t test is <strong>UMP unbiased</strong> when <span class="math inline">\(\sigma\)</span> is unknown</li>
</ul>
</div>
</section>
<section id="unbiased-tests" class="slide level2">
<h2>Unbiased Tests</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Definition (Unbiased Test)</strong></p>
</div>
<div class="callout-content">
<p>A test is <strong>unbiased</strong> if the power under any alternative is at least as large as the power under any null value:</p>
<p><span class="math display">\[\inf_{\theta' \in \Omega_a} \pi(\theta') \geq \sup_{\theta' \in \Omega_0} \pi(\theta')\]</span></p>
<p>Equivalently: we are at least as likely to reject <span class="math inline">\(H_0\)</span> when it is false as when it is true.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Why is this desirable?</strong> A biased test would reject <span class="math inline">\(H_0\)</span> <em>less</em> often for some alternatives than it does when <span class="math inline">\(H_0\)</span> is true — that would defeat the purpose of the test!</p>
</div>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="co"># Biased vs unbiased test illustration</span></span>
<span id="cb12-2"><a></a>mu_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">500</span>)</span>
<span id="cb12-3"><a></a>n_ex <span class="ot">&lt;-</span> <span class="dv">16</span>; sigma_ex <span class="ot">&lt;-</span> <span class="dv">4</span>; se_ex <span class="ot">&lt;-</span> sigma_ex <span class="sc">/</span> <span class="fu">sqrt</span>(n_ex)</span>
<span id="cb12-4"><a></a></span>
<span id="cb12-5"><a></a><span class="co"># Unbiased (symmetric) rejection region</span></span>
<span id="cb12-6"><a></a>power_unbiased <span class="ot">&lt;-</span> <span class="fu">pnorm</span>((<span class="sc">-</span><span class="fl">1.96</span> <span class="sc">*</span> se_ex <span class="sc">-</span> mu_seq) <span class="sc">/</span> se_ex) <span class="sc">+</span> </span>
<span id="cb12-7"><a></a>                  <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>((<span class="fl">1.96</span> <span class="sc">*</span> se_ex <span class="sc">-</span> mu_seq) <span class="sc">/</span> se_ex)</span>
<span id="cb12-8"><a></a></span>
<span id="cb12-9"><a></a><span class="co"># Biased (asymmetric) rejection region: reject if x_bar &gt; 2.17 or x_bar &lt; -1.81</span></span>
<span id="cb12-10"><a></a>power_biased <span class="ot">&lt;-</span> <span class="fu">pnorm</span>((<span class="sc">-</span><span class="fl">1.81</span> <span class="sc">*</span> se_ex <span class="sc">-</span> mu_seq) <span class="sc">/</span> se_ex) <span class="sc">+</span> </span>
<span id="cb12-11"><a></a>                <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>((<span class="fl">2.17</span> <span class="sc">*</span> se_ex <span class="sc">-</span> mu_seq) <span class="sc">/</span> se_ex)</span>
<span id="cb12-12"><a></a></span>
<span id="cb12-13"><a></a><span class="fu">tibble</span>(<span class="at">mu =</span> mu_seq, <span class="at">Unbiased =</span> power_unbiased, <span class="at">Biased =</span> power_biased) <span class="sc">|&gt;</span></span>
<span id="cb12-14"><a></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>mu, <span class="at">names_to =</span> <span class="st">"Test"</span>, <span class="at">values_to =</span> <span class="st">"Power"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-15"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> Power, <span class="at">color =</span> Test)) <span class="sc">+</span></span>
<span id="cb12-16"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.05</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb12-18"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"coral"</span>, <span class="st">"steelblue"</span>)) <span class="sc">+</span></span>
<span id="cb12-19"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">3.5</span>, <span class="at">y =</span> <span class="fl">0.08</span>, <span class="at">label =</span> <span class="fu">expression</span>(alpha <span class="sc">==</span> <span class="fl">0.05</span>), </span>
<span id="cb12-20"><a></a>           <span class="at">color =</span> <span class="st">"gray50"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb12-21"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu <span class="sc">*</span> <span class="st">"'"</span>), <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">pi</span>(mu <span class="sc">*</span> <span class="st">"'"</span>)),</span>
<span id="cb12-22"><a></a>       <span class="at">title =</span> <span class="st">"Unbiased vs Biased Tests for H0: \u03bc = 0 vs Ha: \u03bc \u2260 0"</span>,</span>
<span id="cb12-23"><a></a>       <span class="at">subtitle =</span> <span class="st">"The biased test has power &lt; alpha for some alternatives near mu = 0"</span>) <span class="sc">+</span></span>
<span id="cb12-24"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.85</span>, <span class="fl">0.5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-6-1.png" width="1344"></p>
</figure>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="likelihood-ratio-tests-devore-9.5" class="title-slide slide level1 center" data-background-color="#8e44ad">
<h1>Likelihood Ratio Tests (Devore 9.5)</h1>

</section>
<section id="from-simple-to-composite-hypotheses" class="slide level2 scrollable">
<h2>From Simple to Composite Hypotheses</h2>
<p>The NP Lemma handles simple vs simple hypotheses. But in practice, we need tests for:</p>
<p><span class="math display">\[H_0: \theta \in \Omega_0 \quad \text{vs} \quad H_a: \theta \in \Omega_a\]</span></p>
<p>where one or both hypotheses may be composite.</p>
<div class="fragment">
<p><strong>The likelihood ratio principle</strong> provides a <strong>general recipe</strong> for constructing test statistics in virtually any testing situation.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Likelihood Ratio Test (LRT) Procedure</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Find <span class="math inline">\(\hat{\theta}_{mle}\)</span>, the MLE of <span class="math inline">\(\theta\)</span> over the <strong>full</strong> parameter space <span class="math inline">\(\Omega = \Omega_0 \cup \Omega_a\)</span></li>
<li>Find <span class="math inline">\(\hat{\theta}_0\)</span>, the <strong>restricted MLE</strong> of <span class="math inline">\(\theta\)</span> over <span class="math inline">\(\Omega_0\)</span> only</li>
<li>Form the <strong>likelihood ratio statistic</strong>:</li>
</ol>
<p><span class="math display">\[\Lambda = \frac{L(\hat{\theta}_0)}{L(\hat{\theta}_{mle})}\]</span></p>
<ol start="4" type="1">
<li>Reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(\Lambda \leq k\)</span> (i.e., when the restricted MLE fits much worse than the unrestricted MLE)</li>
</ol>
</div>
</div>
</div>
</div>
</section>
<section id="understanding-the-lrt-statistic" class="slide level2">
<h2>Understanding the LRT Statistic</h2>
<p><span class="math display">\[\Lambda = \frac{L(\hat{\theta}_0)}{L(\hat{\theta}_{mle})} = \frac{\max_{\theta \in \Omega_0} L(\theta)}{\max_{\theta \in \Omega} L(\theta)}\]</span></p>
<div class="fragment">
<p><strong>Key properties:</strong></p>
<ul>
<li>Always <span class="math inline">\(0 \leq \Lambda \leq 1\)</span> (because <span class="math inline">\(\Omega_0 \subseteq \Omega\)</span>, so the restricted maximum <span class="math inline">\(\leq\)</span> unrestricted maximum)</li>
<li><span class="math inline">\(\Lambda \approx 1\)</span>: the data are about equally consistent with <span class="math inline">\(H_0\)</span> and the overall best fit</li>
<li><span class="math inline">\(\Lambda \approx 0\)</span>: the data are <strong>much</strong> more consistent with <span class="math inline">\(H_a\)</span> than with <span class="math inline">\(H_0\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Connection to NP Lemma:</strong> When both hypotheses are simple (<span class="math inline">\(\Omega_0 = \{\theta_0\}\)</span> and <span class="math inline">\(\Omega_a = \{\theta_a\}\)</span>):</p>
<p><span class="math display">\[\Lambda = \frac{L(\theta_0)}{\max\{L(\theta_0), L(\theta_a)\}} = \begin{cases} L(\theta_0)/L(\theta_a) &amp; \text{if } L(\theta_a) \geq L(\theta_0) \\[2pt] 1 &amp; \text{otherwise} \end{cases}\]</span></p>
<p>This is the reciprocal of the NP statistic (when <span class="math inline">\(H_a\)</span> is more likely), so rejecting for small <span class="math inline">\(\Lambda\)</span> is equivalent to rejecting for large <span class="math inline">\(\Lambda^*\)</span>.</p>
</div>
</section>
<section id="lrt-example-1-normal-mean-known-variance-devore-example-9.27-style" class="slide level2">
<h2>LRT Example 1: Normal Mean, Known Variance (Devore Example 9.27 style)</h2>
<p>Systolic blood pressure readings follow <span class="math inline">\(N(\mu, 100)\)</span> (known <span class="math inline">\(\sigma = 10\)</span>). A clinical trial tests whether a new treatment changes the population mean from a target value.</p>
<p><span class="math display">\[H_0: \mu = \mu_0 \quad \text{vs} \quad H_a: \mu \neq \mu_0\]</span></p>
<div class="fragment">
<p><strong>Step 1: Unrestricted MLE.</strong> Over <span class="math inline">\(\Omega = \mathbb{R}\)</span>: <span class="math inline">\(\hat{\mu}_{mle} = \bar{x}\)</span></p>
</div>
<div class="fragment">
<p><strong>Step 2: Restricted MLE.</strong> Over <span class="math inline">\(\Omega_0 = \{\mu_0\}\)</span>: <span class="math inline">\(\hat{\mu}_0 = \mu_0\)</span></p>
</div>
<div class="fragment">
<p><strong>Step 3: Likelihood ratio.</strong></p>
<p><span class="math display">\[\Lambda = \frac{L(\mu_0)}{L(\bar{x})} = \frac{\prod \frac{1}{\sqrt{2\pi}\sigma} e^{-(x_i - \mu_0)^2/(2\sigma^2)}}{\prod \frac{1}{\sqrt{2\pi}\sigma} e^{-(x_i - \bar{x})^2/(2\sigma^2)}} = e^{-\frac{1}{2\sigma^2}\left[\sum(x_i - \mu_0)^2 - \sum(x_i - \bar{x})^2\right]}\]</span></p>
</div>
<div class="fragment">
<p>Since <span class="math inline">\(\sum(x_i - \mu_0)^2 = \sum(x_i - \bar{x})^2 + n(\bar{x} - \mu_0)^2\)</span>:</p>
<p><span class="math display">\[\Lambda = e^{-n(\bar{x} - \mu_0)^2 / (2\sigma^2)}\]</span></p>
</div>
</section>
<section id="lrt-rightarrow-z-test" class="slide level2">
<h2>LRT <span class="math inline">\(\Rightarrow\)</span> z Test</h2>
<p>Reject when <span class="math inline">\(\Lambda \leq k\)</span>:</p>
<p><span class="math display">\[e^{-n(\bar{x} - \mu_0)^2/(2\sigma^2)} \leq k\]</span></p>
<div class="fragment">
<p>Taking <span class="math inline">\(-\ln\)</span> of both sides:</p>
<p><span class="math display">\[\frac{n(\bar{x} - \mu_0)^2}{2\sigma^2} \geq -\ln(k) = c'\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[\left|\frac{\bar{x} - \mu_0}{\sigma/\sqrt{n}}\right| \geq c\]</span></p>
</div>
<div class="fragment">
<p>This is the <strong>two-sided z test</strong>! Setting <span class="math inline">\(c = z_{\alpha/2}\)</span> gives the test at level <span class="math inline">\(\alpha\)</span>.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Result</strong></p>
</div>
<div class="callout-content">
<p>The <strong>likelihood ratio test</strong> for <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs <span class="math inline">\(H_a: \mu \neq \mu_0\)</span> when <span class="math inline">\(\sigma\)</span> is known is exactly the <strong>two-sided z test</strong>. The LRT principle automatically “discovers” the z test.</p>
</div>
</div>
</div>
</div>
</section>
<section id="lrt-example-2-normal-mean-unknown-variance-devore-example-9.27" class="slide level2">
<h2>LRT Example 2: Normal Mean, Unknown Variance (Devore Example 9.27)</h2>
<p>Now suppose <span class="math inline">\(X_1, \ldots, X_n \stackrel{iid}{\sim} N(\mu, \sigma^2)\)</span> with <span class="math inline">\(\sigma\)</span> <strong>unknown</strong>.</p>
<p><span class="math display">\[H_0: \mu = \mu_0 \quad \text{vs} \quad H_a: \mu \neq \mu_0\]</span></p>
<div class="fragment">
<p><strong>Step 1: Unrestricted MLE</strong> over <span class="math inline">\(\Omega = \{(\mu, \sigma^2): \mu \in \mathbb{R}, \sigma^2 &gt; 0\}\)</span>:</p>
<p><span class="math display">\[\hat{\mu}_{mle} = \bar{x}, \quad \hat{\sigma}^2_{mle} = \frac{1}{n}\sum(x_i - \bar{x})^2\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 2: Restricted MLE</strong> over <span class="math inline">\(\Omega_0 = \{(\mu_0, \sigma^2): \sigma^2 &gt; 0\}\)</span>:</p>
<p><span class="math display">\[\hat{\mu}_0 = \mu_0, \quad \hat{\sigma}^2_0 = \frac{1}{n}\sum(x_i - \mu_0)^2\]</span></p>
</div>
<div class="fragment">
<p>Note: under <span class="math inline">\(H_0\)</span>, we still estimate <span class="math inline">\(\sigma^2\)</span> by MLE, but with <span class="math inline">\(\mu\)</span> fixed at <span class="math inline">\(\mu_0\)</span>.</p>
</div>
</section>
<section id="lrt-rightarrow-t-test-devore-example-9.27" class="slide level2">
<h2>LRT <span class="math inline">\(\Rightarrow\)</span> t Test (Devore Example 9.27)</h2>
<p><strong>Step 3: Likelihood ratio.</strong> After substitution and simplification:</p>
<p><span class="math display">\[\Lambda = \left[\frac{\hat{\sigma}^2_{mle}}{\hat{\sigma}^2_0}\right]^{n/2} = \left[\frac{\sum(x_i - \bar{x})^2}{\sum(x_i - \mu_0)^2}\right]^{n/2}\]</span></p>
<div class="fragment">
<p>Since <span class="math inline">\(\sum(x_i - \mu_0)^2 = \sum(x_i - \bar{x})^2 + n(\bar{x} - \mu_0)^2\)</span>:</p>
<p><span class="math display">\[\Lambda = \left[\frac{1}{1 + \frac{n(\bar{x} - \mu_0)^2}{\sum(x_i - \bar{x})^2}}\right]^{n/2} = \left[\frac{1}{1 + t^2/(n-1)}\right]^{n/2}\]</span></p>
<p>where <span class="math inline">\(t = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}\)</span> is the <strong>t statistic</strong>.</p>
</div>
<div class="fragment">
<p><strong>Reject</strong> when <span class="math inline">\(\Lambda\)</span> is small <span class="math inline">\(\iff\)</span> <span class="math inline">\(t^2/(n-1)\)</span> is large <span class="math inline">\(\iff\)</span> <span class="math inline">\(|t| \geq c\)</span>.</p>
<p>Setting <span class="math inline">\(c = t_{\alpha/2, n-1}\)</span> gives the <strong>one-sample t test</strong>.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Result</strong></p>
</div>
<div class="callout-content">
<p>The <strong>likelihood ratio test</strong> for <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs <span class="math inline">\(H_a: \mu \neq \mu_0\)</span> when <span class="math inline">\(\sigma\)</span> is unknown is exactly the <strong>one-sample t test</strong>. Many classical tests can be derived from the LRT principle.</p>
</div>
</div>
</div>
</div>
</section>
<section id="lrt-and-the-t-test-simulation-illustration" class="slide level2">
<h2>LRT and the t Test: Simulation Illustration</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># Demonstrate that the LRT statistic is a monotone function of |t|</span></span>
<span id="cb13-2"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb13-3"><a></a>n_sim <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb13-4"><a></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">120</span>  <span class="co"># target systolic BP</span></span>
<span id="cb13-5"><a></a><span class="co"># Simulated clinical trial data: true mu = 125</span></span>
<span id="cb13-6"><a></a>x_data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> <span class="dv">125</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span>
<span id="cb13-7"><a></a></span>
<span id="cb13-8"><a></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_data)</span>
<span id="cb13-9"><a></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(x_data)</span>
<span id="cb13-10"><a></a>t_stat <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> mu_0) <span class="sc">/</span> (s <span class="sc">/</span> <span class="fu">sqrt</span>(n_sim))</span>
<span id="cb13-11"><a></a></span>
<span id="cb13-12"><a></a><span class="co"># Compute Lambda for a range of hypothetical t values</span></span>
<span id="cb13-13"><a></a>t_range <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">500</span>)</span>
<span id="cb13-14"><a></a>lambda_vals <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> t_range<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n_sim <span class="sc">-</span> <span class="dv">1</span>)))<span class="sc">^</span>(n_sim <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb13-15"><a></a></span>
<span id="cb13-16"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">tibble</span>(<span class="at">t =</span> t_range, <span class="at">Lambda =</span> lambda_vals), <span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Lambda)) <span class="sc">+</span></span>
<span id="cb13-17"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb13-18"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fu">qt</span>(<span class="fl">0.025</span>, n_sim <span class="sc">-</span> <span class="dv">1</span>), <span class="fu">qt</span>(<span class="fl">0.025</span>, n_sim <span class="sc">-</span> <span class="dv">1</span>)),</span>
<span id="cb13-19"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb13-20"><a></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">t =</span> t_stat, </span>
<span id="cb13-21"><a></a>                            <span class="at">Lambda =</span> (<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> t_stat<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n_sim <span class="sc">-</span> <span class="dv">1</span>)))<span class="sc">^</span>(n_sim <span class="sc">/</span> <span class="dv">2</span>)),</span>
<span id="cb13-22"><a></a>             <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb13-23"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> t_stat <span class="sc">-</span> <span class="fl">0.3</span>, <span class="at">y =</span> <span class="fl">0.6</span>, </span>
<span id="cb13-24"><a></a>           <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Observed t = "</span>, <span class="fu">round</span>(t_stat, <span class="dv">2</span>)), </span>
<span id="cb13-25"><a></a>           <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">hjust =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-26"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"t statistic"</span>, <span class="at">y =</span> <span class="fu">expression</span>(Lambda),</span>
<span id="cb13-27"><a></a>       <span class="at">title =</span> <span class="fu">expression</span>(Lambda <span class="sc">==</span> (<span class="dv">1</span> <span class="sc">+</span> t<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n<span class="dv">-1</span>))<span class="sc">^</span>{<span class="sc">-</span>n<span class="sc">/</span><span class="dv">2</span>}),</span>
<span id="cb13-28"><a></a>       <span class="at">subtitle =</span> <span class="fu">expression</span>(<span class="st">"Smaller "</span> <span class="sc">*</span> Lambda <span class="sc">*</span> <span class="st">" = stronger evidence against "</span> <span class="sc">*</span> H[<span class="dv">0</span>]))</span>
<span id="cb13-29"><a></a></span>
<span id="cb13-30"><a></a><span class="co"># Show the relationship between -2ln(Lambda) and t^2</span></span>
<span id="cb13-31"><a></a>neg2lnL <span class="ot">&lt;-</span> <span class="sc">-</span>n_sim <span class="sc">*</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> t_range<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n_sim <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb13-32"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">tibble</span>(<span class="at">t2 =</span> t_range<span class="sc">^</span><span class="dv">2</span>, <span class="at">neg2lnL =</span> <span class="sc">-</span>neg2lnL), </span>
<span id="cb13-33"><a></a>             <span class="fu">aes</span>(<span class="at">x =</span> t2, <span class="at">y =</span> neg2lnL)) <span class="sc">+</span></span>
<span id="cb13-34"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb13-35"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, n_sim <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">^</span><span class="dv">2</span>, </span>
<span id="cb13-36"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb13-37"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(t<span class="sc">^</span><span class="dv">2</span>), <span class="at">y =</span> <span class="fu">expression</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda)),</span>
<span id="cb13-38"><a></a>       <span class="at">title =</span> <span class="fu">expression</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda) <span class="sc">~</span> <span class="st">"vs"</span> <span class="sc">~</span> t<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb13-39"><a></a>       <span class="at">subtitle =</span> <span class="st">"Monotone increasing: small Lambda = large |t|"</span>)</span>
<span id="cb13-40"><a></a></span>
<span id="cb13-41"><a></a>p1 <span class="sc">+</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-7-1.png" width="1344" class="r-stretch"></section>
<section id="medical-application-drug-efficacy-trial" class="slide level2">
<h2>Medical Application: Drug Efficacy Trial</h2>
<p>A Phase III clinical trial tests whether a new cholesterol-lowering drug changes mean LDL from baseline <span class="math inline">\(\mu_0 = 130\)</span> mg/dL. Data from <span class="math inline">\(n = 30\)</span> patients:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb14-2"><a></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb14-3"><a></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">130</span></span>
<span id="cb14-4"><a></a>ldl_data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">122</span>, <span class="at">sd =</span> <span class="dv">18</span>)</span>
<span id="cb14-5"><a></a></span>
<span id="cb14-6"><a></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(ldl_data)</span>
<span id="cb14-7"><a></a>s_val <span class="ot">&lt;-</span> <span class="fu">sd</span>(ldl_data)</span>
<span id="cb14-8"><a></a>t_obs <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> mu_0) <span class="sc">/</span> (s_val <span class="sc">/</span> <span class="fu">sqrt</span>(n))</span>
<span id="cb14-9"><a></a></span>
<span id="cb14-10"><a></a><span class="fu">cat</span>(<span class="st">"Sample mean:"</span>, <span class="fu">round</span>(x_bar, <span class="dv">2</span>), <span class="st">"mg/dL</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 123.23 mg/dL</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">cat</span>(<span class="st">"Sample SD:  "</span>, <span class="fu">round</span>(s_val, <span class="dv">2</span>), <span class="st">"mg/dL</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample SD:   22.59 mg/dL</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">cat</span>(<span class="st">"t statistic:"</span>, <span class="fu">round</span>(t_obs, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>t statistic: -1.64 </code></pre>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># LRT statistic</span></span>
<span id="cb20-2"><a></a>Lambda <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> t_obs<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n <span class="sc">-</span> <span class="dv">1</span>)))<span class="sc">^</span>(n <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb20-3"><a></a>neg2lnLambda <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">log</span>(Lambda)</span>
<span id="cb20-4"><a></a></span>
<span id="cb20-5"><a></a><span class="fu">cat</span>(<span class="st">"Lambda:       "</span>, <span class="fu">round</span>(Lambda, <span class="dv">6</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lambda:        0.26424 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">cat</span>(<span class="st">"-2 ln(Lambda):"</span>, <span class="fu">round</span>(neg2lnLambda, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>-2 ln(Lambda): 2.662 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">cat</span>(<span class="st">"t^2:         "</span>, <span class="fu">round</span>(t_obs<span class="sc">^</span><span class="dv">2</span>, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>t^2:          2.691 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">cat</span>(<span class="st">"P-value (t):  "</span>, <span class="fu">round</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_obs), <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value (t):   0.1117 </code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="co"># Verify with t.test</span></span>
<span id="cb28-2"><a></a><span class="fu">t.test</span>(ldl_data, <span class="at">mu =</span> mu_0) <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a></a>  <span class="fu">select</span>(estimate, statistic, p.value, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">round</span>(., <span class="dv">4</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  estimate statistic p.value conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     123.     -1.64   0.112     115.      132.</code></pre>
</div>
</div>
</div>
</section></section>
<section>
<section id="large-sample-lrt-approximation" class="title-slide slide level1 center" data-background-color="#f39c12">
<h1>Large-Sample LRT Approximation</h1>

</section>
<section id="wilks-theorem-the-chi-squared-approximation" class="slide level2">
<h2>Wilks’ Theorem: The Chi-Squared Approximation</h2>
<p>In many situations, the LRT rejection region <span class="math inline">\(\Lambda \leq k\)</span> cannot be expressed in terms of a simple, familiar statistic. A powerful large-sample result resolves this.</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem (Wilks’ Theorem, Devore 9.5)</strong></p>
</div>
<div class="callout-content">
<p>If the sample size <span class="math inline">\(n\)</span> is sufficiently large, then under <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math display">\[-2\ln(\Lambda) \xrightarrow{d} \chi^2_m\]</span></p>
<p>where <span class="math inline">\(m\)</span> is the difference between the number of free parameters in <span class="math inline">\(\Omega\)</span> and the number of free parameters in <span class="math inline">\(\Omega_0\)</span>.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>How to use it:</strong> Since <span class="math inline">\(0 \leq \Lambda \leq 1\)</span>, we have <span class="math inline">\(-2\ln(\Lambda) \geq 0\)</span>. Reject <span class="math inline">\(H_0\)</span> when:</p>
<p><span class="math display">\[-2\ln(\Lambda) \geq \chi^2_{\alpha, m}\]</span></p>
</div>
<div class="fragment">
<p><strong>The degrees of freedom <span class="math inline">\(m\)</span>:</strong></p>
<ul>
<li><span class="math inline">\(m = \dim(\Omega) - \dim(\Omega_0)\)</span> = (number of parameters estimated under <span class="math inline">\(H_a\)</span>) minus (number estimated under <span class="math inline">\(H_0\)</span>)</li>
<li>Represents the number of “constraints” imposed by <span class="math inline">\(H_0\)</span></li>
</ul>
</div>
</section>
<section id="computing-degrees-of-freedom-examples" class="slide level2">
<h2>Computing Degrees of Freedom: Examples</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 27%">
<col style="width: 33%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th><span class="math inline">\(\Omega\)</span></th>
<th><span class="math inline">\(\Omega_0\)</span></th>
<th><span class="math inline">\(m\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(N(\mu, \sigma^2)\)</span>, <span class="math inline">\(\sigma\)</span> known, <span class="math inline">\(H_0: \mu = \mu_0\)</span></td>
<td>1 (<span class="math inline">\(\mu\)</span>)</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(N(\mu, \sigma^2)\)</span>, <span class="math inline">\(\sigma\)</span> unknown, <span class="math inline">\(H_0: \mu = \mu_0\)</span></td>
<td>2 (<span class="math inline">\(\mu, \sigma^2\)</span>)</td>
<td>1 (<span class="math inline">\(\sigma^2\)</span>)</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Bivariate normal, <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> and <span class="math inline">\(\sigma_1 = \sigma_2\)</span></td>
<td>5 (<span class="math inline">\(\mu_1, \mu_2, \sigma_1, \sigma_2, \rho\)</span>)</td>
<td>3 (<span class="math inline">\(\mu, \sigma, \rho\)</span>)</td>
<td>2</td>
</tr>
<tr class="even">
<td>Multinomial with <span class="math inline">\(k\)</span> categories, <span class="math inline">\(H_0: p_i = p_{i,0}\)</span></td>
<td><span class="math inline">\(k - 1\)</span></td>
<td>0</td>
<td><span class="math inline">\(k - 1\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical Rule</strong></p>
</div>
<div class="callout-content">
<p>Count the number of parameters that are “free” (need to be estimated) under each hypothesis. The difference is <span class="math inline">\(m\)</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="large-sample-lrt-example-double-exponential-devore-9.5" class="slide level2">
<h2>Large-Sample LRT Example: Double Exponential (Devore 9.5)</h2>
<p>The Laplace (double exponential) distribution with pdf <span class="math inline">\(f(x; \theta) = \frac{1}{2}e^{-|x - \theta|}\)</span> is sometimes used to model measurement errors. Test <span class="math inline">\(H_0: \theta = 0\)</span> vs <span class="math inline">\(H_a: \theta \neq 0\)</span>.</p>
<div class="fragment">
<p><strong>Under <span class="math inline">\(\Omega\)</span>:</strong> The MLE of <span class="math inline">\(\theta\)</span> is the <strong>sample median</strong> <span class="math inline">\(\tilde{x}\)</span> (minimizes <span class="math inline">\(\sum |x_i - \theta|\)</span>).</p>
<p><strong>Under <span class="math inline">\(\Omega_0\)</span>:</strong> <span class="math inline">\(\theta = 0\)</span> (no estimation needed).</p>
</div>
<div class="fragment">
<p><span class="math display">\[\Lambda = \frac{(1/2)^n e^{-\sum|x_i|}}{(1/2)^n e^{-\sum|x_i - \tilde{x}|}} = e^{-(\sum|x_i| - \sum|x_i - \tilde{x}|)}\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[-2\ln(\Lambda) = 2\left(\sum|x_i| - \sum|x_i - \tilde{x}|\right)\]</span></p>
</div>
<div class="fragment">
<p><strong>Degrees of freedom:</strong> <span class="math inline">\(m = 1 - 0 = 1\)</span>, so <span class="math inline">\(-2\ln(\Lambda) \stackrel{\cdot}{\sim} \chi^2_1\)</span> under <span class="math inline">\(H_0\)</span>.</p>
<p>Reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(-2\ln(\Lambda) \geq \chi^2_{\alpha, 1}\)</span>.</p>
</div>
</section>
<section id="simulation-verifying-the-chi-squared-approximation" class="slide level2">
<h2>Simulation: Verifying the Chi-Squared Approximation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="co"># Simulate LRT for normal mean (known variance) and check chi-squared approximation</span></span>
<span id="cb30-2"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb30-3"><a></a>n_obs <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb30-4"><a></a>n_rep <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb30-5"><a></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb30-6"><a></a>sigma_known <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb30-7"><a></a></span>
<span id="cb30-8"><a></a><span class="co"># Simulate under H_0</span></span>
<span id="cb30-9"><a></a>neg2lnL_sims <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_rep, {</span>
<span id="cb30-10"><a></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_obs, <span class="at">mean =</span> mu_0, <span class="at">sd =</span> sigma_known)</span>
<span id="cb30-11"><a></a>  x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb30-12"><a></a>  <span class="co"># -2ln(Lambda) = n * (x_bar - mu_0)^2 / sigma^2 for known variance case</span></span>
<span id="cb30-13"><a></a>  n_obs <span class="sc">*</span> (x_bar <span class="sc">-</span> mu_0)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> sigma_known<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb30-14"><a></a>})</span>
<span id="cb30-15"><a></a></span>
<span id="cb30-16"><a></a><span class="co"># Compare to chi-squared(1)</span></span>
<span id="cb30-17"><a></a>chi2_theoretical <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="dv">12</span>, <span class="at">length.out =</span> <span class="dv">500</span>)</span>
<span id="cb30-18"><a></a></span>
<span id="cb30-19"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">tibble</span>(<span class="at">stat =</span> neg2lnL_sims), <span class="fu">aes</span>(<span class="at">x =</span> stat)) <span class="sc">+</span></span>
<span id="cb30-20"><a></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">bins =</span> <span class="dv">60</span>, </span>
<span id="cb30-21"><a></a>                 <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb30-22"><a></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">x =</span> chi2_theoretical, <span class="at">y =</span> <span class="fu">dchisq</span>(chi2_theoretical, <span class="at">df =</span> <span class="dv">1</span>)),</span>
<span id="cb30-23"><a></a>            <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y), <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb30-24"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda)), <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb30-25"><a></a>       <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Simulated "</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda) <span class="sc">*</span> <span class="st">" vs "</span> <span class="sc">*</span> chi[<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> </span>
<span id="cb30-26"><a></a>                         <span class="st">" (n = 30, known "</span> <span class="sc">*</span> sigma <span class="sc">*</span> <span class="st">")"</span>),</span>
<span id="cb30-27"><a></a>       <span class="at">subtitle =</span> <span class="fu">expression</span>(<span class="st">"Red curve: "</span> <span class="sc">*</span> chi<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">"(1) density"</span>))</span>
<span id="cb30-28"><a></a></span>
<span id="cb30-29"><a></a><span class="co"># Q-Q plot</span></span>
<span id="cb30-30"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">tibble</span>(<span class="at">stat =</span> neg2lnL_sims), <span class="fu">aes</span>(<span class="at">sample =</span> stat)) <span class="sc">+</span></span>
<span id="cb30-31"><a></a>  <span class="fu">stat_qq</span>(<span class="at">distribution =</span> qchisq, <span class="at">dparams =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">1</span>), </span>
<span id="cb30-32"><a></a>          <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb30-33"><a></a>  <span class="fu">stat_qq_line</span>(<span class="at">distribution =</span> qchisq, <span class="at">dparams =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">1</span>), </span>
<span id="cb30-34"><a></a>               <span class="at">color =</span> <span class="st">"coral"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-35"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="st">"Theoretical "</span> <span class="sc">*</span> chi[<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">" quantiles"</span>),</span>
<span id="cb30-36"><a></a>       <span class="at">y =</span> <span class="fu">expression</span>(<span class="st">"Sample quantiles of "</span> <span class="sc">*</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda)),</span>
<span id="cb30-37"><a></a>       <span class="at">title =</span> <span class="st">"Q-Q Plot: Chi-Squared Approximation"</span>,</span>
<span id="cb30-38"><a></a>       <span class="at">subtitle =</span> <span class="st">"Close alignment confirms Wilks' theorem"</span>)</span>
<span id="cb30-39"><a></a></span>
<span id="cb30-40"><a></a>p1 <span class="sc">+</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-11-1.png" width="1344" class="r-stretch"></section>
<section id="how-good-is-the-approximation-for-small-n" class="slide level2">
<h2>How Good is the Approximation for Small <span class="math inline">\(n\)</span>?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="co"># Check chi-squared approximation quality for different n</span></span>
<span id="cb31-2"><a></a><span class="co"># Normal mean, unknown variance -&gt; -2ln(Lambda) = n*ln(1 + t^2/(n-1))</span></span>
<span id="cb31-3"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb31-4"><a></a>n_rep <span class="ot">&lt;-</span> <span class="dv">50000</span></span>
<span id="cb31-5"><a></a>sample_sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">30</span>, <span class="dv">100</span>)</span>
<span id="cb31-6"><a></a></span>
<span id="cb31-7"><a></a>sim_results <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(sample_sizes, <span class="cf">function</span>(n_val) {</span>
<span id="cb31-8"><a></a>  stats <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_rep, {</span>
<span id="cb31-9"><a></a>    x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_val, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb31-10"><a></a>    t_stat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">/</span> (<span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(n_val))</span>
<span id="cb31-11"><a></a>    n_val <span class="sc">*</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> t_stat<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n_val <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb31-12"><a></a>  })</span>
<span id="cb31-13"><a></a>  <span class="fu">tibble</span>(<span class="at">n =</span> n_val, <span class="at">n_label =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, n_val), <span class="at">stat =</span> stats)</span>
<span id="cb31-14"><a></a>})</span>
<span id="cb31-15"><a></a></span>
<span id="cb31-16"><a></a><span class="co"># Overlay: simulated density vs chi-squared(1) reference</span></span>
<span id="cb31-17"><a></a>chi2_ref <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb31-18"><a></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">500</span>),</span>
<span id="cb31-19"><a></a>  <span class="at">y =</span> <span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">1</span>)</span>
<span id="cb31-20"><a></a>)</span>
<span id="cb31-21"><a></a></span>
<span id="cb31-22"><a></a>p_facet <span class="ot">&lt;-</span> sim_results <span class="sc">|&gt;</span></span>
<span id="cb31-23"><a></a>  <span class="fu">mutate</span>(<span class="at">n_label =</span> <span class="fu">factor</span>(n_label, <span class="at">levels =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, sample_sizes))) <span class="sc">|&gt;</span></span>
<span id="cb31-24"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> stat)) <span class="sc">+</span></span>
<span id="cb31-25"><a></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"Simulated"</span>), <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">key_glyph =</span> <span class="st">"path"</span>) <span class="sc">+</span></span>
<span id="cb31-26"><a></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> chi2_ref <span class="sc">|&gt;</span> <span class="fu">crossing</span>(<span class="at">n_label =</span> <span class="fu">factor</span>(<span class="fu">paste0</span>(<span class="st">"n = "</span>, sample_sizes), </span>
<span id="cb31-27"><a></a>            <span class="at">levels =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, sample_sizes))),</span>
<span id="cb31-28"><a></a>            <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">color =</span> <span class="st">"Chi-squared(1)"</span>), <span class="at">linewidth =</span> <span class="fl">1.1</span>,</span>
<span id="cb31-29"><a></a>            <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">key_glyph =</span> <span class="st">"path"</span>) <span class="sc">+</span></span>
<span id="cb31-30"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>n_label) <span class="sc">+</span></span>
<span id="cb31-31"><a></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Simulated"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>, <span class="st">"Chi-squared(1)"</span> <span class="ot">=</span> <span class="st">"coral"</span>)) <span class="sc">+</span></span>
<span id="cb31-32"><a></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">8</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span></span>
<span id="cb31-33"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">ln</span>(Lambda)), <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb31-34"><a></a>       <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Quality of "</span> <span class="sc">*</span> chi<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">"(1) Approximation for the t Test LRT"</span>),</span>
<span id="cb31-35"><a></a>       <span class="at">subtitle =</span> <span class="st">"Solid blue = simulated; dashed red = reference. Heavy tails for small n."</span>,</span>
<span id="cb31-36"><a></a>       <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb31-37"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb31-38"><a></a></span>
<span id="cb31-39"><a></a>p_facet</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-12-1.png" width="1344" class="r-stretch"></section>
<section id="how-good-is-the-approximation-for-small-n-1" class="slide level2">
<h2>How Good is the Approximation for Small <span class="math inline">\(n\)</span>?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="co"># Also show Q-Q plots against chi-squared(1) for each n</span></span>
<span id="cb32-2"><a></a>p_qq <span class="ot">&lt;-</span> sim_results <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a></a>  <span class="fu">mutate</span>(<span class="at">n_label =</span> <span class="fu">factor</span>(n_label, <span class="at">levels =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, sample_sizes))) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a></a>  <span class="fu">group_by</span>(n_label) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">2000</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-6"><a></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-7"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> stat)) <span class="sc">+</span></span>
<span id="cb32-8"><a></a>  <span class="fu">stat_qq</span>(<span class="at">distribution =</span> qchisq, <span class="at">dparams =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">1</span>),</span>
<span id="cb32-9"><a></a>          <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"coral"</span>, </span>
<span id="cb32-11"><a></a>              <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>n_label) <span class="sc">+</span></span>
<span id="cb32-13"><a></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">8</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">12</span>)) <span class="sc">+</span></span>
<span id="cb32-14"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="st">"Theoretical "</span> <span class="sc">*</span> chi[<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">" quantiles"</span>),</span>
<span id="cb32-15"><a></a>       <span class="at">y =</span> <span class="st">"Sample quantiles"</span>,</span>
<span id="cb32-16"><a></a>       <span class="at">title =</span> <span class="st">"Q-Q Plots Against Chi-squared(1)"</span>,</span>
<span id="cb32-17"><a></a>       <span class="at">subtitle =</span> <span class="st">"Departure from diagonal shows approximation error for small n"</span>)</span>
<span id="cb32-18"><a></a></span>
<span id="cb32-19"><a></a>p_qq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="15_NeymanPearson_LRT_files/figure-revealjs/unnamed-chunk-13-1.png" width="1344" class="r-stretch"></section></section>
<section>
<section id="connecting-the-pieces" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Connecting the Pieces</h1>

</section>
<section id="the-big-picture-hypothesis-testing-framework" class="slide level2">
<h2>The Big Picture: Hypothesis Testing Framework</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">library</span>(DiagrammeR)</span>
<span id="cb33-2"><a></a></span>
<span id="cb33-3"><a></a><span class="fu">grViz</span>(<span class="st">"</span></span>
<span id="cb33-4"><a></a><span class="st">digraph testing_framework {</span></span>
<span id="cb33-5"><a></a><span class="st">  graph [rankdir=TB, bgcolor=transparent, fontsize=20]</span></span>
<span id="cb33-6"><a></a><span class="st">  node [shape=box, style=filled, fontsize=16, fontname='Helvetica']</span></span>
<span id="cb33-7"><a></a><span class="st">  </span></span>
<span id="cb33-8"><a></a><span class="st">  # Top level</span></span>
<span id="cb33-9"><a></a><span class="st">  A [label='Hypothesis Testing Problem</span><span class="sc">\\</span><span class="st">nH₀: θ ∈ Ω₀ vs Hₐ: θ ∈ Ωₐ', </span></span>
<span id="cb33-10"><a></a><span class="st">     fillcolor='#3498db', fontcolor=white, width=4]</span></span>
<span id="cb33-11"><a></a><span class="st">  </span></span>
<span id="cb33-12"><a></a><span class="st">  # Decision node</span></span>
<span id="cb33-13"><a></a><span class="st">  B [label='Are both hypotheses simple?', </span></span>
<span id="cb33-14"><a></a><span class="st">     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]</span></span>
<span id="cb33-15"><a></a><span class="st">  </span></span>
<span id="cb33-16"><a></a><span class="st">  # Simple path</span></span>
<span id="cb33-17"><a></a><span class="st">  C [label='Neyman-Pearson Lemma</span><span class="sc">\\</span><span class="st">nLikelihood ratio: L(θₐ)/L(θ₀) ≥ k</span><span class="sc">\\</span><span class="st">nMost Powerful Test', </span></span>
<span id="cb33-18"><a></a><span class="st">     fillcolor='#27ae60', fontcolor=white, width=3.5]</span></span>
<span id="cb33-19"><a></a><span class="st">  </span></span>
<span id="cb33-20"><a></a><span class="st">  # Composite path</span></span>
<span id="cb33-21"><a></a><span class="st">  D [label='Likelihood Ratio Test (LRT)</span><span class="sc">\\</span><span class="st">nΛ = L(θ̂₀) / L(θ̂ₘₗₑ) ≤ k', </span></span>
<span id="cb33-22"><a></a><span class="st">     fillcolor='#8e44ad', fontcolor=white, width=3.5]</span></span>
<span id="cb33-23"><a></a><span class="st">  </span></span>
<span id="cb33-24"><a></a><span class="st">  # UMP</span></span>
<span id="cb33-25"><a></a><span class="st">  E [label='Same rejection region</span><span class="sc">\\</span><span class="st">nfor all θₐ ∈ Ωₐ?', </span></span>
<span id="cb33-26"><a></a><span class="st">     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]</span></span>
<span id="cb33-27"><a></a><span class="st">  F [label='UMP Test</span><span class="sc">\\</span><span class="st">n(one-sided alternatives;</span><span class="sc">\\</span><span class="st">nKarlin-Rubin Theorem)', </span></span>
<span id="cb33-28"><a></a><span class="st">     fillcolor='#27ae60', fontcolor=white, width=3]</span></span>
<span id="cb33-29"><a></a><span class="st">  G [label='No UMP exists</span><span class="sc">\\</span><span class="st">n(two-sided alternatives)</span><span class="sc">\\</span><span class="st">nUse UMP Unbiased or LRT', </span></span>
<span id="cb33-30"><a></a><span class="st">     fillcolor='#e74c3c', fontcolor=white, width=3.5]</span></span>
<span id="cb33-31"><a></a><span class="st">  </span></span>
<span id="cb33-32"><a></a><span class="st">  # LRT outcomes</span></span>
<span id="cb33-33"><a></a><span class="st">  H [label='Exact distribution</span><span class="sc">\\</span><span class="st">nknown?', </span></span>
<span id="cb33-34"><a></a><span class="st">     fillcolor='#f39c12', fontcolor=white, shape=diamond, width=3]</span></span>
<span id="cb33-35"><a></a><span class="st">  I [label='Use exact test</span><span class="sc">\\</span><span class="st">n(z test, t test, F test)', </span></span>
<span id="cb33-36"><a></a><span class="st">     fillcolor='#27ae60', fontcolor=white, width=3]</span></span>
<span id="cb33-37"><a></a><span class="st">  J [label='Large-sample approx.</span><span class="sc">\\</span><span class="st">n-2ln(Λ) ~ χ²ₘ', </span></span>
<span id="cb33-38"><a></a><span class="st">     fillcolor='#16a085', fontcolor=white, width=3]</span></span>
<span id="cb33-39"><a></a><span class="st">  </span></span>
<span id="cb33-40"><a></a><span class="st">  A -&gt; B</span></span>
<span id="cb33-41"><a></a><span class="st">  B -&gt; C [label='  Yes', fontsize=14]</span></span>
<span id="cb33-42"><a></a><span class="st">  B -&gt; D [label='  No', fontsize=14]</span></span>
<span id="cb33-43"><a></a><span class="st">  C -&gt; E</span></span>
<span id="cb33-44"><a></a><span class="st">  E -&gt; F [label='  Yes', fontsize=14]</span></span>
<span id="cb33-45"><a></a><span class="st">  E -&gt; G [label='  No', fontsize=14]</span></span>
<span id="cb33-46"><a></a><span class="st">  D -&gt; H</span></span>
<span id="cb33-47"><a></a><span class="st">  H -&gt; I [label='  Yes', fontsize=14]</span></span>
<span id="cb33-48"><a></a><span class="st">  H -&gt; J [label='  No', fontsize=14]</span></span>
<span id="cb33-49"><a></a><span class="st">}</span></span>
<span id="cb33-50"><a></a><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-0dd68904c5b7b7947ef7" style="width:1536px;height:768px;"></div>
<script type="application/json" data-for="htmlwidget-0dd68904c5b7b7947ef7">{"x":{"diagram":"\ndigraph testing_framework {\n  graph [rankdir=TB, bgcolor=transparent, fontsize=20]\n  node [shape=box, style=filled, fontsize=16, fontname=\"Helvetica\"]\n  \n  # Top level\n  A [label=\"Hypothesis Testing Problem\\nH₀: θ ∈ Ω₀ vs Hₐ: θ ∈ Ωₐ\", \n     fillcolor=\"#3498db\", fontcolor=white, width=4]\n  \n  # Decision node\n  B [label=\"Are both hypotheses simple?\", \n     fillcolor=\"#f39c12\", fontcolor=white, shape=diamond, width=3]\n  \n  # Simple path\n  C [label=\"Neyman-Pearson Lemma\\nLikelihood ratio: L(θₐ)/L(θ₀) ≥ k\\nMost Powerful Test\", \n     fillcolor=\"#27ae60\", fontcolor=white, width=3.5]\n  \n  # Composite path\n  D [label=\"Likelihood Ratio Test (LRT)\\nΛ = L(θ̂₀) / L(θ̂ₘₗₑ) ≤ k\", \n     fillcolor=\"#8e44ad\", fontcolor=white, width=3.5]\n  \n  # UMP\n  E [label=\"Same rejection region\\nfor all θₐ ∈ Ωₐ?\", \n     fillcolor=\"#f39c12\", fontcolor=white, shape=diamond, width=3]\n  F [label=\"UMP Test\\n(one-sided alternatives;\\nKarlin-Rubin Theorem)\", \n     fillcolor=\"#27ae60\", fontcolor=white, width=3]\n  G [label=\"No UMP exists\\n(two-sided alternatives)\\nUse UMP Unbiased or LRT\", \n     fillcolor=\"#e74c3c\", fontcolor=white, width=3.5]\n  \n  # LRT outcomes\n  H [label=\"Exact distribution\\nknown?\", \n     fillcolor=\"#f39c12\", fontcolor=white, shape=diamond, width=3]\n  I [label=\"Use exact test\\n(z test, t test, F test)\", \n     fillcolor=\"#27ae60\", fontcolor=white, width=3]\n  J [label=\"Large-sample approx.\\n-2ln(Λ) ~ χ²ₘ\", \n     fillcolor=\"#16a085\", fontcolor=white, width=3]\n  \n  A -> B\n  B -> C [label=\"  Yes\", fontsize=14]\n  B -> D [label=\"  No\", fontsize=14]\n  C -> E\n  E -> F [label=\"  Yes\", fontsize=14]\n  E -> G [label=\"  No\", fontsize=14]\n  D -> H\n  H -> I [label=\"  Yes\", fontsize=14]\n  H -> J [label=\"  No\", fontsize=14]\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="summary-classical-tests-as-lrts" class="slide level2">
<h2>Summary: Classical Tests as LRTs</h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 26%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Hypotheses</th>
<th>LRT Produces</th>
<th>Exact or Approx?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-sample z</td>
<td><span class="math inline">\(H_0: \mu = \mu_0\)</span>, <span class="math inline">\(\sigma\)</span> known</td>
<td><span class="math inline">\(z = \frac{\bar{x} - \mu_0}{\sigma/\sqrt{n}}\)</span></td>
<td>Exact</td>
</tr>
<tr class="even">
<td>One-sample t</td>
<td><span class="math inline">\(H_0: \mu = \mu_0\)</span>, <span class="math inline">\(\sigma\)</span> unknown</td>
<td><span class="math inline">\(t = \frac{\bar{x} - \mu_0}{s/\sqrt{n}}\)</span></td>
<td>Exact</td>
</tr>
<tr class="odd">
<td>Pooled two-sample t</td>
<td><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>, equal <span class="math inline">\(\sigma\)</span></td>
<td>Pooled <span class="math inline">\(t\)</span> statistic</td>
<td>Exact</td>
</tr>
<tr class="even">
<td>Chi-squared goodness-of-fit</td>
<td><span class="math inline">\(H_0: p_i = p_{i,0}\)</span></td>
<td><span class="math inline">\(\sum (O_i - E_i)^2/E_i\)</span></td>
<td>Large-sample</td>
</tr>
<tr class="odd">
<td>F test (ANOVA)</td>
<td><span class="math inline">\(H_0: \mu_1 = \cdots = \mu_k\)</span></td>
<td><span class="math inline">\(F\)</span> ratio</td>
<td>Exact (normal)</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Insight</strong></p>
</div>
<div class="callout-content">
<p>The LRT principle is a <strong>unifying framework</strong>. Many of the “named” tests from introductory statistics — z tests, t tests, F tests, chi-squared tests — can all be derived as likelihood ratio tests. The LRT gives us a principled way to construct new tests for situations not covered by standard formulas.</p>
</div>
</div>
</div>
</div>
</section>
<section id="comparison-of-approaches-when-to-use-what" class="slide level2">
<h2>Comparison of Approaches: When to Use What</h2>
<p><strong>Neyman-Pearson Lemma:</strong></p>
<ul>
<li>Applies to <strong>simple vs simple</strong> hypotheses</li>
<li>Guarantees <strong>optimality</strong> (most powerful test)</li>
<li>Useful for proving that known tests are optimal</li>
</ul>
<div class="fragment">
<p><strong>UMP Tests:</strong></p>
<ul>
<li>Extend NP to <strong>one-sided composite</strong> alternatives</li>
<li>Exist mainly for one-parameter exponential families with one-sided alternatives</li>
<li>Do <strong>not</strong> exist for two-sided alternatives in general</li>
</ul>
</div>
<div class="fragment">
<p><strong>Likelihood Ratio Tests:</strong></p>
<ul>
<li>Apply to <strong>any</strong> testing problem (simple or composite, one or multiple parameters)</li>
<li><strong>General-purpose recipe</strong> that always yields a reasonable test</li>
<li>Often coincide with optimal tests when those exist</li>
<li>Large-sample <span class="math inline">\(\chi^2\)</span> approximation makes them practical even when exact distributions are unknown</li>
</ul>
</div>
</section></section>
<section>
<section id="key-takeaways-and-looking-ahead" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Key Takeaways and Looking Ahead</h1>

</section>
<section id="key-takeaways" class="slide level2 scrollable">
<h2>Key Takeaways</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Today’s Main Points</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Simple hypotheses</strong> completely specify the distribution; composite hypotheses do not</li>
<li><strong>Neyman-Pearson Lemma:</strong> the likelihood ratio test <span class="math inline">\(L(\theta_a)/L(\theta_0) \geq k\)</span> is the most powerful test for simple <span class="math inline">\(H_0\)</span> vs simple <span class="math inline">\(H_a\)</span></li>
<li><strong>Power function</strong> <span class="math inline">\(\pi(\theta') = P_{\theta'}(\text{Reject } H_0)\)</span> characterizes test performance across all parameter values</li>
<li><strong>UMP tests</strong> maximize power for <em>every</em> alternative; they exist for one-sided tests in exponential families</li>
<li><strong>Likelihood ratio test</strong> <span class="math inline">\(\Lambda = L(\hat{\theta}_0)/L(\hat{\theta}_{mle})\)</span> provides a general recipe for composite hypotheses</li>
<li><strong>LRT <span class="math inline">\(\Rightarrow\)</span> classical tests:</strong> the z test and t test are both LRTs</li>
<li><strong>Wilks’ theorem:</strong> <span class="math inline">\(-2\ln(\Lambda) \xrightarrow{d} \chi^2_m\)</span> provides a large-sample approximation</li>
</ol>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Common mistakes to avoid:</strong></p>
<ul>
<li>Confusing the NP ratio <span class="math inline">\(L(\theta_a)/L(\theta_0)\)</span> (reject when large) with the LRT ratio <span class="math inline">\(L(\hat{\theta}_0)/L(\hat{\theta}_{mle})\)</span> (reject when small)</li>
<li>Assuming UMP tests always exist (they don’t for two-sided alternatives)</li>
<li>Using the <span class="math inline">\(\chi^2\)</span> approximation when <span class="math inline">\(n\)</span> is too small</li>
<li>Forgetting that the LRT degrees of freedom <span class="math inline">\(m\)</span> count <em>free</em> parameters, not total parameters</li>
</ul>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p><strong>Next class (Lesson 16):</strong> Further Aspects of Hypothesis Testing; Bootstrap Hypothesis Testing (Devore 9.6, C&amp;H Chapter 8)</p>
<ul>
<li>Statistical vs practical significance</li>
<li>Relationship between confidence intervals and hypothesis tests</li>
<li>Bootstrap hypothesis testing</li>
<li>Permutation tests</li>
</ul>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<ul>
<li>Devore, Berk, and Carlton. <em>Modern Mathematical Statistics with Applications</em> (Springer). Section 9.5</li>
<li>Chihara and Hesterberg. <em>Mathematical Statistics with Resampling and R</em> (Wiley). Section 8.4</li>
<li>Neyman, J. &amp; Pearson, E. S. (1933). On the problem of the most efficient tests of statistical hypotheses. <em>Philosophical Transactions of the Royal Society A</em>, 231, 289–337.</li>
<li>Wilks, S. S. (1938). The large-sample distribution of the likelihood ratio for testing composite hypotheses. <em>The Annals of Mathematical Statistics</em>, 9(1), 60–62.</li>
</ul>
</section>
<section id="questions" class="slide level2 center" data-background-color="#3498db">
<h2>Questions?</h2>
<p>Thank you!</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lesson 15 - Neyman-Pearson Lemma; Likelihood Ratio Tests</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1955,

        height: 1100,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>