{
  "hash": "a461a6a1fa0b34e64c3b9804f0866fae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 6 Solutions\"\nsubtitle: \"BSTA 551\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n---\n\n## Problem 1: Neyman-Pearson Lemma (Lesson 15)\n\nAdverse events in a clinical trial are monitored over successive reporting windows. The number of adverse events per window follows $X_i \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$. A safety board tests:\n\n$$H_0: \\lambda = 2 \\quad \\text{vs} \\quad H_a: \\lambda = 4 \\quad (n = 6 \\text{ windows})$$\n\n**(a)** Compute $\\Lambda^* = L(\\lambda=4)/L(\\lambda=2)$ and show the NP rejection region simplifies to $\\sum X_i \\geq c$.\n\n**(b)** Find critical value $c$ with $\\alpha^* \\leq 0.05$ using `ppois()`.\n\n**(c)** Compute the power at $\\lambda = 4$.\n\n**(d)** Explain why the same rejection region is UMP for $H_0: \\lambda \\leq 2$ vs $H_a: \\lambda > 2$.\n\n---\n\n### Part (a) — NP likelihood ratio\n\nThe joint PMF is $L(\\lambda) = e^{-6\\lambda}\\lambda^{\\sum x_i}/\\prod x_i!$. The NP ratio is:\n\n$$\\Lambda^* = \\frac{L(4)}{L(2)} = \\frac{e^{-24} \\cdot 4^{\\sum x_i}}{e^{-12} \\cdot 2^{\\sum x_i}} = e^{-12} \\cdot 2^{\\sum x_i}$$\n\nThe rejection region $\\Lambda^* \\geq k$ becomes:\n\n$$e^{-12} \\cdot 2^{\\sum x_i} \\geq k \\implies \\sum x_i \\cdot \\ln 2 \\geq \\ln k + 12 \\implies \\sum_{i=1}^6 X_i \\geq c$$\n\nfor some constant $c = (\\ln k + 12)/\\ln 2$. Since $2^{\\sum x_i}$ is strictly increasing in $\\sum x_i$, the inequality direction is preserved. $\\square$\n\n### Part (b) — Critical value\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Under H0: sum(X_i) ~ Poisson(6 * 2) = Poisson(12)\n# Find smallest c such that P(Y >= c | Y ~ Pois(12)) <= 0.05\nc_vals <- 12:25\nalpha_vals <- 1 - ppois(c_vals - 1, lambda = 12)\n\ntibble(c = c_vals, alpha = round(alpha_vals, 4)) |>\n  filter(alpha <= 0.06) |>   # show candidates near 0.05\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|  c|  alpha|\n|--:|------:|\n| 19| 0.0374|\n| 20| 0.0213|\n| 21| 0.0116|\n| 22| 0.0061|\n| 23| 0.0030|\n| 24| 0.0015|\n| 25| 0.0007|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc_crit   <- min(c_vals[alpha_vals <= 0.05])\nalpha_st <- 1 - ppois(c_crit - 1, lambda = 12)\ncat(\"Critical value c:\", c_crit, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value c: 19 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Achieved alpha*: \", round(alpha_st, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAchieved alpha*:  0.0374 \n```\n\n\n:::\n:::\n\n\nThe smallest $c$ with $P(Y \\geq c) \\leq 0.05$ is $c = 19$, giving an achieved $\\alpha^* = 0.0374$.\n\n### Part (c) — Power at $\\lambda = 4$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Under Ha: sum(X_i) ~ Poisson(6 * 4) = Poisson(24)\nbeta_st <- ppois(c_crit - 1, lambda = 24)\npower   <- 1 - beta_st\ncat(\"Type II error beta*:\", round(beta_st, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType II error beta*: 0.1283 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power (1 - beta*):  \", round(power, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower (1 - beta*):   0.8717 \n```\n\n\n:::\n:::\n\n\nThe power of the NP test at $\\lambda = 4$ is $1 - \\beta^* = 0.8717$. By the NP Lemma, no other level-$0.0374$ test can achieve higher power at $\\lambda = 4$.\n\n### Part (d) — UMP argument\n\nFor any fixed alternative $\\lambda_a > 2$, the NP likelihood ratio is:\n\n$$\\Lambda^*(\\lambda_a) = \\frac{e^{-6\\lambda_a}\\lambda_a^{\\sum x_i}}{e^{-12} \\cdot 2^{\\sum x_i}} = e^{-6(\\lambda_a - 2)} \\left(\\frac{\\lambda_a}{2}\\right)^{\\sum x_i}$$\n\nSince $\\lambda_a > 2$, the base $\\lambda_a/2 > 1$, so $\\Lambda^* \\geq k \\iff \\sum x_i \\geq c(\\lambda_a)$. But the constant $c$ that controls the Type I error at level $\\alpha^*$ is determined solely by $H_0$ (via the $\\text{Poisson}(12)$ null distribution) — it does **not** depend on which $\\lambda_a > 2$ we choose. Therefore the same rejection region $\\{\\sum X_i \\geq 19\\}$ is most powerful against every $\\lambda_a > 2$, making it **UMP** for the composite alternative $H_a: \\lambda > 2$.\n\n---\n\n## Problem 2: Likelihood Ratio Test and Wilks' Theorem (Lesson 15)\n\nHospital infection data: $X = \\{5, 2, 4, 6, 3, 5, 4, 7, 3, 4\\}$, $n = 10$, $\\lambda_0 = 3.5$.\n\nTest $H_0: \\lambda = 3.5$ vs $H_a: \\lambda \\neq 3.5$.\n\n**(a)** Find the log-likelihood and MLE $\\hat\\lambda$.\n\n**(b)** Compute $-2\\ln(\\Lambda)$.\n\n**(c)** Compute the Wilks p-value and compare to `poisson.test()`.\n\n**(d)** Explain the degrees of freedom.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_inf <- c(5, 2, 4, 6, 3, 5, 4, 7, 3, 4)\nn_inf <- length(x_inf)\nlambda0_inf <- 3.5\n```\n:::\n\n\n### Part (a) — Log-likelihood and MLE\n\nFor $X_i \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$, the log-likelihood is:\n\n$$\\ell(\\lambda) = -n\\lambda + \\left(\\sum_{i=1}^n x_i\\right)\\ln\\lambda - \\sum_{i=1}^n \\ln(x_i!)$$\n\nSetting $\\ell'(\\lambda) = -n + \\bar{x}/\\lambda \\cdot n= 0$ gives $\\hat\\lambda = \\bar{x}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar_inf <- mean(x_inf)\ncat(\"Sum:\", sum(x_inf), \"  n:\", n_inf, \"  MLE lambda-hat:\", xbar_inf, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum: 43   n: 10   MLE lambda-hat: 4.3 \n```\n\n\n:::\n:::\n\n\n$\\hat\\lambda = \\bar{x} = 4.3$ infections per 100 patient-days.\n\n### Part (b) — LRT statistic\n\n$$-2\\ln(\\Lambda) = 2\\left[n\\hat\\lambda - n\\lambda_0 + n\\bar{x}\\ln\\!\\left(\\frac{\\lambda_0}{\\hat\\lambda}\\right)\\right]$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneg2lnL <- 2 * (n_inf * xbar_inf - n_inf * lambda0_inf +\n                n_inf * xbar_inf * log(lambda0_inf / xbar_inf))\ncat(\"-2 ln(Lambda):\", round(neg2lnL, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-2 ln(Lambda): -1.7033 \n```\n\n\n:::\n:::\n\n\n$-2\\ln(\\Lambda) = -1.7033$.\n\n### Part (c) — Wilks p-value and exact comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_wilks <- pchisq(neg2lnL, df = 1, lower.tail = FALSE)\np_exact <- poisson.test(sum(x_inf), T = n_inf, r = lambda0_inf)$p.value\n\ncat(\"Wilks (chi-sq) p-value:\", round(p_wilks, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilks (chi-sq) p-value: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Exact Poisson p-value: \", round(p_exact, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExact Poisson p-value:  0.1755 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Conclusion at alpha=0.05:\",\n    ifelse(p_wilks < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConclusion at alpha=0.05: Fail to reject H0 \n```\n\n\n:::\n:::\n\n\nThe Wilks p-value is 1 and the exact p-value is 0.1755. Both fail to reject $H_0$ at $\\alpha = 0.05`. The approximation is somewhat rough for $n = 10$.\n\n### Part (d) — Degrees of freedom\n\nThe full parameter space $\\Omega$ has 1 free parameter ($\\lambda$). The null $\\Omega_0 = \\{3.5\\}$ constrains $\\lambda$ to a single point, leaving 0 free parameters. Wilks' theorem gives $m = \\dim(\\Omega) - \\dim(\\Omega_0) = 1 - 0 = \\mathbf{1}$ degree of freedom.\n\n---\n\n## Problem 3: Statistical vs. Practical Significance (Lesson 16)\n\nA large RCT ($n = 3{,}200$ per arm) evaluates a new lipid-lowering drug. $\\bar{x}_{\\text{control}} = 142.1$ mg/dL, $\\bar{x}_{\\text{treat}} = 140.3$ mg/dL, $\\sigma = 28.15$ mg/dL (assumed known).\n\n**(a)** z-statistic, p-value, and 95% CI. **(b)** Cohen's $d$ and clinical significance. **(c)** Conceptual explanation.\n\n---\n\n### Part (a) — z-statistic, p-value, and 95% CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar_c <- 142.1; xbar_t <- 140.3; sigma <- 28.15; n <- 3200\n\nse_diff <- sigma * sqrt(2 / n)\nz_obs   <- (xbar_t - xbar_c) / se_diff\np_val   <- 2 * pnorm(-abs(z_obs))\nz_crit  <- qnorm(0.975)\nci_lo   <- (xbar_t - xbar_c) - z_crit * se_diff\nci_hi   <- (xbar_t - xbar_c) + z_crit * se_diff\n\ncat(\"SE:\", round(se_diff, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE: 0.7038 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"z:\", round(z_obs, 4), \"  p-value:\", round(p_val, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz: -2.5577   p-value: 0.01054 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: [\", round(ci_lo, 3), \",\", round(ci_hi, 3), \"] mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [ -3.179 , -0.421 ] mg/dL\n```\n\n\n:::\n:::\n\n\nThe result is **statistically significant** ($p = 0.01054 < 0.05$). The 95% CI is $(-3.18,\\ -0.42)$ mg/dL.\n\n### Part (b) — Cohen's $d$ and clinical significance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_cohen <- abs(xbar_t - xbar_c) / sigma\ncat(\"Cohen's d:\", round(d_cohen, 4), \"-- classified as: negligible (< 0.2)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d: 0.0639 -- classified as: negligible (< 0.2)\n```\n\n\n:::\n:::\n\n\nCohen's $d = 0.064$ is classified as **negligible**. The entire 95% CI $(-3.18,\\ -0.42)$ mg/dL lies far above the clinical threshold of $-10$ mg/dL. Even the lower bound of the CI ($-3.18$ mg/dL) falls well short of a meaningful reduction. There is **no evidence of a clinically meaningful effect**.\n\n### Part (c) — Conceptual\n\nWith $n = 3{,}200$ per arm, even negligible differences produce tiny standard errors, making any non-zero effect statistically detectable. Statistical significance measures *detectability* given the sample size, not whether the effect is large enough to matter clinically. Reporting the CI rather than just the p-value reveals that the plausible effect range is 0.8–2.8 mg/dL — far below the 10 mg/dL threshold that justifies prescribing this drug.\n\n---\n\n## Problem 4: CI-Test Duality — Theory and Computation (Lesson 16)\n\n$$\\left(\\frac{\\chi^2_{\\alpha/2,\\; 2T}}{2n},\\; \\frac{\\chi^2_{1-\\alpha/2,\\; 2T+2}}{2n}\\right) \\quad \\text{where } T = \\sum_{i=1}^n X_i$$\n\nUsing infection data from Problem 2: $n = 10$, $\\sum x_i = 43$, $\\lambda_0 = 3.5$.\n\n**(a)** State and apply the duality theorem. **(b)** Compute CI and check two null values. **(c)** One-sided lower bound.\n\n---\n\n### Part (a) — Duality theorem\n\n**CI-Test Duality Theorem (Devore 9.6):** Let $C(\\mathbf{X})$ be a $100(1-\\alpha)\\%$ CI obtained by inverting a level-$\\alpha$ test. Then:\n$$\\theta_0 \\notin C(\\mathbf{X}) \\iff \\text{reject } H_0: \\theta = \\theta_0 \\text{ at level } \\alpha$$\n$$\\theta_0 \\in C(\\mathbf{X}) \\iff \\text{fail to reject } H_0: \\theta = \\theta_0 \\text{ at level } \\alpha$$\n\nThe Poisson CI is constructed precisely by inverting the exact Poisson test: it consists of all $\\lambda_0$ values for which the exact test fails to reject at level $\\alpha$. Therefore, by the theorem, $\\lambda_0 \\in C$ if and only if the test of $H_0: \\lambda = \\lambda_0$ fails to reject — the CI and the test are exactly dual.\n\n### Part (b) — Compute CI and verify duality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT_inf  <- sum(x_inf)   # = 43\nalpha_i <- 0.05\n\nci_lo_p <- qchisq(alpha_i/2,     df = 2 * T_inf)     / (2 * n_inf)\nci_hi_p <- qchisq(1 - alpha_i/2, df = 2 * T_inf + 2) / (2 * n_inf)\ncat(\"95% Poisson CI: [\", round(ci_lo_p, 4), \",\", round(ci_hi_p, 4), \"]\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Poisson CI: [ 3.1119 , 5.7921 ]\n```\n\n\n:::\n\n```{.r .cell-code}\n# (ii) Test H0: lambda = 3.5\nt35 <- poisson.test(T_inf, T = n_inf, r = 3.5)\ncat(\"H0: lambda = 3.5   p =\", round(t35$p.value, 4),\n    \" Decision:\", ifelse(t35$p.value < 0.05, \"Reject\", \"FTR\"),\n    \" | 3.5 in CI?\", ci_lo_p <= 3.5 & 3.5 <= ci_hi_p, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH0: lambda = 3.5   p = 0.1755  Decision: FTR  | 3.5 in CI? TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\n# (iii) Test H0: lambda = 4.5\nt45 <- poisson.test(T_inf, T = n_inf, r = 4.5)\ncat(\"H0: lambda = 4.5   p =\", round(t45$p.value, 4),\n    \" Decision:\", ifelse(t45$p.value < 0.05, \"Reject\", \"FTR\"),\n    \" | 4.5 in CI?\", ci_lo_p <= 4.5 & 4.5 <= ci_hi_p, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH0: lambda = 4.5   p = 0.8232  Decision: FTR  | 4.5 in CI? TRUE \n```\n\n\n:::\n:::\n\n\nFor $\\lambda_0 = 3.5$: the test fails to reject $H_0$ and $3.5$ is inside the CI — **consistent** ✓\n\nFor $\\lambda_0 = 4.5$: the test fails to reject $H_0$ and $4.5$ is inside the CI — **consistent** ✓\n\n### Part (c) — One-sided lower bound\n\nBy one-sided duality, the 95% lower bound dual to $H_0: \\lambda \\leq \\lambda_0$ vs $H_a: \\lambda > \\lambda_0$ is:\n\n$$\\underline{\\lambda} = \\frac{\\chi^2_{\\alpha,\\; 2T}}{2n}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb <- qchisq(alpha_i, df = 2 * T_inf) / (2 * n_inf)\nt_gt <- poisson.test(T_inf, T = n_inf, r = 3.5, alternative = \"greater\")\ncat(\"95% lower bound:\", round(lb, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower bound: 3.2812 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Lower bound > 3.5?\", lb > 3.5, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLower bound > 3.5? FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"One-sided p-value (Ha: lambda > 3.5):\", round(t_gt$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOne-sided p-value (Ha: lambda > 3.5): 0.105 \n```\n\n\n:::\n:::\n\n\nThe lower bound is $\\underline{\\lambda} = 3.2812$. Since 3.2812 ≤ 3.5, we fail to reject $H_0: \\lambda \\leq 3.5$ at the 5% level — the hospital's rate is significantly above the benchmark.\n\n---\n\n## Problem 5: Constructing CIs and the p-Value Function (Lesson 16)\n\n$$X = \\{1.8,\\ 2.6,\\ 3.1,\\ 2.2,\\ 4.7,\\ 2.9,\\ 3.8,\\ 2.4,\\ 1.6,\\ 3.5,\\ 4.1,\\ 2.7\\}, \\quad \\mu_0 = 3.0$$\n\n**(a)** 95% t-CI and duality-based rejection decision. **(b)** 95% CI for $\\sigma^2$ and $\\sigma$. **(c)** p-value function plot.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug <- c(1.8, 2.6, 3.1, 2.2, 4.7, 2.9, 3.8, 2.4, 1.6, 3.5, 4.1, 2.7)\nn_d  <- length(drug)\nxbar_d <- mean(drug); s_d <- sd(drug); se_d <- s_d / sqrt(n_d); df_d <- n_d - 1\n```\n:::\n\n\n### Part (a) — 95% t-CI and duality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_crit <- qt(0.975, df = df_d)\nci_lo_d <- xbar_d - t_crit * se_d\nci_hi_d <- xbar_d + t_crit * se_d\ncat(\"xbar:\", round(xbar_d, 4), \"  s:\", round(s_d, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nxbar: 2.95   s: 0.9357 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% t-CI: [\", round(ci_lo_d, 4), \",\", round(ci_hi_d, 4), \"] mg/L\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% t-CI: [ 2.3555 , 3.5445 ] mg/L\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"mu0 = 3.0 inside CI?\", ci_lo_d <= 3.0 & 3.0 <= ci_hi_d, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmu0 = 3.0 inside CI? TRUE \n```\n\n\n:::\n:::\n\n\n$\\mu_0 = 3.0$ falls **inside** the 95% CI $[2.356, 3.544]$. By the CI-Test Duality Theorem, we therefore **fail to reject** $H_0: \\mu = 3.0$ at $\\alpha = 0.05$ — no test statistic needed.\n\n### Part (b) — 95% CI for $\\sigma^2$ and $\\sigma$\n\nStarting from $(n-1)S^2/\\sigma^2 \\sim \\chi^2_{n-1}$, inverting the acceptance region gives:\n\n$$\\frac{(n-1)s^2}{\\chi^2_{\\alpha/2,\\, n-1}} \\leq \\sigma^2 \\leq \\frac{(n-1)s^2}{\\chi^2_{1-\\alpha/2,\\, n-1}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_up  <- qchisq(0.975, df = df_d)   # upper quantile -> smaller lower bound\nchi_lo  <- qchisq(0.025, df = df_d)   # lower quantile -> larger upper bound\ns2_d    <- var(drug)\n\nci_var_lo <- df_d * s2_d / chi_up\nci_var_hi <- df_d * s2_d / chi_lo\n\ncat(\"Sample variance:\", round(s2_d, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample variance: 0.8755 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for sigma^2: [\", round(ci_var_lo, 4), \",\", round(ci_var_hi, 4), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for sigma^2: [ 0.4393 , 2.5238 ]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for sigma:   [\", round(sqrt(ci_var_lo), 4), \",\",\n    round(sqrt(ci_var_hi), 4), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for sigma:   [ 0.6628 , 1.5886 ]\n```\n\n\n:::\n:::\n\n\n### Part (c) — p-value function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0_grid <- seq(1.5, 4.5, by = 0.05)\npval_fn  <- map_dbl(mu0_grid, ~2 * pt(-abs((xbar_d - .x) / se_d), df = df_d))\n\nggplot(tibble(mu0 = mu0_grid, pval = pval_fn), aes(x = mu0, y = pval)) +\n  annotate(\"rect\", xmin = ci_lo_d, xmax = ci_hi_d, ymin = -Inf, ymax = Inf,\n           fill = \"#006a4e\", alpha = 0.12) +\n  geom_vline(xintercept = c(ci_lo_d, ci_hi_d),\n             color = \"#006a4e\", linewidth = 1, linetype = \"dotted\") +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\",\n             color = \"#e74c3c\", linewidth = 1) +\n  geom_line(color = \"#2c3e50\", linewidth = 1.5) +\n  geom_point(aes(x = xbar_d, y = 1), size = 3.5, color = \"#006a4e\") +\n  annotate(\"text\", x = xbar_d, y = 0.90,\n           label = sprintf(\"95%% CI [%.2f, %.2f]\", ci_lo_d, ci_hi_d),\n           color = \"#006a4e\", size = 4.5) +\n  annotate(\"text\", x = 4.1, y = 0.09,\n           label = expression(alpha == 0.05), color = \"#e74c3c\", size = 4.5) +\n  labs(title = expression(\"p-value function: p(\" * mu[0] * \")\"),\n       subtitle = \"Green region = 95% CI (fail-to-reject region). Dot = MLE where p = 1.\",\n       x = expression(mu[0] * \" (null value, mg/L)\"),\n       y = \"Two-sided p-value\")\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-html/unnamed-chunk-15-1.png){width=1056}\n:::\n:::\n\n\nThe green shaded region where $p(\\mu_0) \\geq 0.05$ spans exactly $[2.356, 3.544]$ mg/L, matching the 95% t-CI from part (a) precisely — confirming the CI-test duality theorem visually.\n\n---\n\n## Problem 6: Bootstrap Hypothesis Testing (Lesson 17)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nferritin <- c(28.4, 45.2, 19.8, 67.3, 31.5, 88.1, 22.6, 54.9,\n              41.2, 76.8, 33.7, 29.4, 58.3, 44.1, 92.5, 37.6,\n              25.8, 61.4)\nmu_0 <- 40; n_f <- length(ferritin)\nxbar_f <- mean(ferritin); s_f <- sd(ferritin); se_f <- s_f / sqrt(n_f)\n```\n:::\n\n\n**(a)** Histogram, normality assessment, $T_{\\text{obs}}$, and t-test p-value.\n\n**(b)** Correct bootstrap test ($B = 5{,}000$, `set.seed(551)`).\n\n**(c)** Naive bootstrap and explanation of invalidity.\n\n**(d)** Side-by-side histograms of both bootstrap distributions.\n\n---\n\n### Part (a) — Histogram and t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(x = ferritin), aes(x = x)) +\n  geom_histogram(bins = 8, fill = \"#3498db\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = mu_0, linetype = \"dashed\",\n             color = \"#e74c3c\", linewidth = 1.2) +\n  annotate(\"text\", x = mu_0 + 3, y = 3.7,\n           label = expression(mu[0] == 40), color = \"#e74c3c\", size = 5) +\n  labs(title = \"Serum ferritin in CKD patients\",\n       subtitle = \"Dashed line = population norm (40 ng/mL)\",\n       x = \"Serum ferritin (ng/mL)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-html/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT_obs_f <- (xbar_f - mu_0) / se_f\np_ttest <- t.test(ferritin, mu = mu_0)$p.value\ncat(\"Mean:\", round(xbar_f, 3), \"  SD:\", round(s_f, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean: 47.7   SD: 22.281 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"T_obs:\", round(T_obs_f, 4), \"  t-test p:\", round(p_ttest, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT_obs: 1.4662   t-test p: 0.1608 \n```\n\n\n:::\n:::\n\n\nThe distribution is **right-skewed** with values up to 92.5 ng/mL. With $n = 18$ and noticeable skewness, the normality assumption is questionable — a bootstrap test is more appropriate. The t-test fails to reject $H_0$ ($p = 0.1608$).\n\n### Part (b) — Correct bootstrap test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551); B_f <- 5000\n\nferritin_sh <- ferritin - xbar_f + mu_0      # shift to H0\n\nT_boot_f <- replicate(B_f, {\n  bs <- sample(ferritin_sh, n_f, replace = TRUE)\n  (mean(bs) - mu_0) / (sd(bs) / sqrt(n_f))\n})\n\np_boot_f <- mean(abs(T_boot_f) >= abs(T_obs_f))\ncat(\"Bootstrap p-value:\", round(p_boot_f, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap p-value: 0.175 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-test p-value:   \", round(p_ttest,  4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-test p-value:    0.1608 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Decision:\", ifelse(p_boot_f < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDecision: Fail to reject H0 \n```\n\n\n:::\n:::\n\n\nBoth methods fail to reject $H_0$. The p-values are close ($0.175$ vs $0.1608$), consistent with Lesson 17's simulation showing that t-test and bootstrap converge as $n$ increases toward 30.\n\n### Part (c) — Naive (incorrect) bootstrap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nT_naive_f <- replicate(B_f, mean(sample(ferritin, n_f, replace = TRUE)))\np_naive_f <- mean(abs(T_naive_f - xbar_f) >= abs(xbar_f - mu_0))\ncat(\"Naive p-value:\", round(p_naive_f, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaive p-value: 0.1396 \n```\n\n\n:::\n:::\n\n\nThe naive approach is invalid because resampling from the original data produces a distribution centered at $\\bar{x} = 47.7$ ng/mL rather than at the null value $\\mu_0 = 40$ ng/mL. A valid null distribution must represent how the test statistic behaves *when $H_0$ is true*; the naive distribution instead approximates sampling variability of $\\hat\\mu$ around the unknown true mean. Comparing $|\\bar{x}^{*b} - \\bar{x}|$ to $|\\bar{x} - \\mu_0|$ measures something conceptually different from what the test requires.\n\n### Part (d) — Side-by-side histograms\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_nv <- ggplot(tibble(T = T_naive_f), aes(x = T)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"#e74c3c\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = xbar_f, color = \"black\", linewidth = 1.2) +\n  geom_vline(xintercept = mu_0, color = \"#3498db\",\n             linewidth = 1.2, linetype = \"dashed\") +\n  annotate(\"rect\",\n           xmin = xbar_f + abs(xbar_f - mu_0), xmax = Inf, ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"rect\",\n           xmin = -Inf, xmax = xbar_f - abs(xbar_f - mu_0), ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"text\", x = xbar_f + 0.8, y = 0.22,\n           label = \"bar(x)\", parse = TRUE, size = 5) +\n  annotate(\"text\", x = mu_0 - 0.8, y = 0.22,\n           label = \"mu[0]\", parse = TRUE, size = 5, color = \"#3498db\", hjust = 1) +\n  labs(title = expression(bold(\"WRONG\") * \": Naive (original data)\"),\n       subtitle = sprintf(\"Centered at x-bar=%.1f, not mu0=%.1f  |  p = %.4f\",\n                          xbar_f, mu_0, p_naive_f),\n       x = expression(bar(x)^\"*\"), y = \"Density\")\n\np_cr <- ggplot(tibble(T = T_boot_f), aes(x = T)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"#27ae60\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = c(-abs(T_obs_f), abs(T_obs_f)),\n             color = \"#e74c3c\", linewidth = 1.2) +\n  annotate(\"rect\", xmin =  abs(T_obs_f), xmax =  Inf, ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"rect\", xmin = -Inf, xmax = -abs(T_obs_f), ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"text\", x = abs(T_obs_f) + 0.2, y = 0.32,\n           label = bquote(T[obs] == .(round(T_obs_f, 2))),\n           color = \"#e74c3c\", size = 4.5) +\n  labs(title = expression(bold(\"CORRECT\") * \": Bootstrap from shifted data\"),\n       subtitle = sprintf(\"Centered at mu0=%.1f  |  Bootstrap p=%.4f, t-test p=%.4f\",\n                          mu_0, p_boot_f, p_ttest),\n       x = \"t-statistic\", y = \"Density\")\n\np_nv + p_cr\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-html/unnamed-chunk-21-1.png){width=1344}\n:::\n:::\n\n\nThe left panel shows the naive distribution centered at $\\bar{x}$ (not the null value), making it an invalid null reference distribution. The right panel shows the correct bootstrap null distribution centered at $\\mu_0$, with the observed statistic and p-value region clearly marked.\n",
    "supporting": [
      "HW_06_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}