{
  "hash": "137976d093af52e03764f78940dd6f0f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 6 Solutions\"\nsubtitle: \"BSTA 551\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n---\n\n## Problem 1: Statistical vs. Practical Significance (Lesson 16)\n\nA large randomized controlled trial ($n = 3{,}200$ patients per arm) evaluates a new lipid-lowering drug. The primary outcome is LDL cholesterol (mg/dL) measured after 6 months. Results:\n\n- Control arm: $\\bar{x}_{\\text{control}} = 142.1$ mg/dL, $s_{\\text{control}} = 28.4$ mg/dL\n- Treatment arm: $\\bar{x}_{\\text{treat}} = 140.3$ mg/dL, $s_{\\text{treat}} = 27.9$ mg/dL\n\nFor simplicity, assume equal and known $\\sigma = 28.15$ mg/dL (pooled) and use a two-sample z-test.\n\n**(a)** Compute the observed z-statistic and two-sided p-value for $H_0: \\mu_{\\text{treat}} = \\mu_{\\text{control}}$ vs $H_a: \\mu_{\\text{treat}} \\neq \\mu_{\\text{control}}$. Is the result statistically significant at $\\alpha = 0.05$?\n\n**(b)** Compute a 95% confidence interval for the difference in means $\\mu_{\\text{treat}} - \\mu_{\\text{control}}$.\n\n**(c)** Compute Cohen's $d = |\\bar{x}_{\\text{treat}} - \\bar{x}_{\\text{control}}| / \\sigma$. Using the table from class slides, how would you characterize the magnitude of this effect?\n\n**(d)** Clinical guidelines consider an LDL reduction of $\\geq 10$ mg/dL to be clinically meaningful. Based on your confidence interval from part (b), does this trial provide evidence of a clinically meaningful reduction? Explain clearly, referencing both the interval and the clinical threshold.\n\n**(e)** In 2–3 sentences, explain how a study can produce a statistically significant result that is not clinically significant, and why this distinction matters for medical decision-making.\n\n---\n\n### Part (a) — z-statistic and p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar_c <- 142.1; xbar_t <- 140.3\nsigma   <- 28.15\nn       <- 3200\n\nse_diff <- sigma * sqrt(2 / n)\nz_obs   <- (xbar_t - xbar_c) / se_diff\np_val   <- 2 * pnorm(-abs(z_obs))\n\ncat(\"SE of difference:\", round(se_diff, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE of difference: 0.7038 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"z-statistic:     \", round(z_obs, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz-statistic:      -2.5577 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Two-sided p-value:\", round(p_val, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value: 0.01054 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Significant at alpha = 0.05?\", p_val < 0.05, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSignificant at alpha = 0.05? TRUE \n```\n\n\n:::\n:::\n\n\nThe difference is $\\bar{x}_{\\text{treat}} - \\bar{x}_{\\text{control}} = 140.3 - 142.1 = -1.8$ mg/dL. With $\\text{SE} = \\sigma\\sqrt{2/n} = 0.7038$, the z-statistic is $z = -2.5577$ and the two-sided p-value is $p = 0.01054$, which is less than 0.05. The result is **statistically significant**.\n\n### Part (b) — 95% CI for difference in means\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_crit <- qnorm(0.975)\nci_lo  <- (xbar_t - xbar_c) - z_crit * se_diff\nci_hi  <- (xbar_t - xbar_c) + z_crit * se_diff\ncat(\"95% CI: [\", round(ci_lo, 3), \",\", round(ci_hi, 3), \"] mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [ -3.179 , -0.421 ] mg/dL\n```\n\n\n:::\n:::\n\n\nThe 95% CI for $\\mu_{\\text{treat}} - \\mu_{\\text{control}}$ is $(-3.18, -0.42)$ mg/dL.\n\n### Part (c) — Cohen's $d$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_cohen <- abs(xbar_t - xbar_c) / sigma\ncat(\"Cohen's d:\", round(d_cohen, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d: 0.0639 \n```\n\n\n:::\n:::\n\n\nCohen's $d = 1.8 / 28.15 \\approx 0.064$, which is well below 0.2. This is classified as a **negligible** effect by the standard Cohen's $d$ table.\n\n### Part (d) — Clinical significance\n\nThe entire 95% CI $(-3.18,\\ -0.42)$ mg/dL lies far above the clinical threshold of $-10$ mg/dL (a 10 mg/dL reduction). The upper end of the CI is positive, meaning the data are compatible with essentially no reduction or even a slight increase. There is **no evidence of a clinically meaningful LDL reduction**: the entire plausible range of effects falls well within the negligible range, far from the ≥10 mg/dL threshold.\n\n### Part (e) — Conceptual\n\nWith very large sample sizes, even negligible true effects produce extremely small standard errors, making the test statistic large enough to exceed any fixed critical value. Statistical significance measures whether an effect is *detectable* given the sample size — not whether it is *large enough to matter*. A drug that reduces LDL by 1.8 mg/dL in 3,200 patients per arm would likely not be approved or prescribed, since the cost, inconvenience, and potential side effects cannot be justified by a sub-clinical benefit. Reporting only the p-value obscures this; the CI makes the practical picture transparent.\n\n---\n\n## Problem 2: CI-Test Duality — Theory and Verification (Lesson 16)\n\nLet $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$. The exact two-sided $100(1-\\alpha)\\%$ confidence interval for $\\lambda$ based on $T = \\sum_{i=1}^n X_i$ is:\n\n$$\\left(\\frac{\\chi^2_{\\alpha/2,\\; 2T}}{2n},\\; \\frac{\\chi^2_{1-\\alpha/2,\\; 2T+2}}{2n}\\right)$$\n\n**(a)** State the CI-Test Duality Theorem precisely (as given in Devore 9.6 / Lesson 16). Then use it to argue that the Poisson interval above corresponds to a level-$\\alpha$ test of $H_0: \\lambda = \\lambda_0$ vs $H_a: \\lambda \\neq \\lambda_0$.\n\n**(b)** A radiation monitoring station records gamma-ray events per 10-minute period. In $n = 8$ periods, the observed counts are $X = \\{3, 7, 5, 4, 6, 8, 4, 5\\}$.\n\n  (i) Compute the 95% Poisson CI using `qchisq()`.\n  (ii) Test $H_0: \\lambda = 4$ at $\\alpha = 0.05$ using `poisson.test()`.\n  (iii) Test $H_0: \\lambda = 6$ at $\\alpha = 0.05$.\n  (iv) Verify that each test decision is consistent with CI membership (duality check).\n\n**(c)** State the 95% lower confidence bound dual to $H_0: \\lambda \\leq \\lambda_0$ vs $H_a: \\lambda > \\lambda_0$. Is there evidence that $\\lambda > 4$?\n\n---\n\n### Part (a) — Duality, theory\n\n**CI-Test Duality Theorem (Devore 9.6):** Let $C(\\mathbf{X})$ be a $100(1-\\alpha)\\%$ confidence interval for $\\theta$ obtained by inverting a level-$\\alpha$ test. Then:\n$$\\theta_0 \\notin C(\\mathbf{X}) \\iff \\text{reject } H_0: \\theta = \\theta_0 \\text{ at level } \\alpha$$\n$$\\theta_0 \\in C(\\mathbf{X}) \\iff \\text{fail to reject } H_0: \\theta = \\theta_0 \\text{ at level } \\alpha$$\n\nThe Poisson CI is constructed by inverting the exact Poisson test — it is the set of all $\\lambda_0$ values for which the exact test fails to reject at level $\\alpha$. By the duality theorem, $\\lambda_0 \\in C(\\mathbf{X})$ if and only if we fail to reject $H_0: \\lambda = \\lambda_0$ at level $\\alpha$; the CI and the test convey identical information about which null values are consistent with the data.\n\n### Part (b) — Duality, computation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_counts  <- c(3, 7, 5, 4, 6, 8, 4, 5)\nn_periods <- length(x_counts)\nT_sum     <- sum(x_counts)\nalpha_p   <- 0.05\n\ncat(\"n =\", n_periods, \", sum =\", T_sum, \", xbar =\", mean(x_counts), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 8 , sum = 42 , xbar = 5.25 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (i) 95% Poisson CI via chi-squared formula\nci_lo_pois <- qchisq(alpha_p / 2,     df = 2 * T_sum)       / (2 * n_periods)\nci_hi_pois <- qchisq(1 - alpha_p / 2, df = 2 * T_sum + 2)   / (2 * n_periods)\ncat(\"95% Poisson CI for lambda: [\", round(ci_lo_pois, 4), \",\",\n    round(ci_hi_pois, 4), \"]\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Poisson CI for lambda: [ 3.7837 , 7.0965 ]\n```\n\n\n:::\n\n```{.r .cell-code}\n# (ii) Test H0: lambda = 4\ntest_4 <- poisson.test(T_sum, T = n_periods, r = 4, alternative = \"two.sided\")\ncat(\"H0: lambda = 4\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH0: lambda = 4\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p-value:\", round(test_4$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p-value: 0.0918 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Decision:\", ifelse(test_4$p.value < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Decision: Fail to reject H0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  lambda0 = 4 in CI?\", ci_lo_pois <= 4 & 4 <= ci_hi_pois, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lambda0 = 4 in CI? TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\n# (iii) Test H0: lambda = 6\ntest_6 <- poisson.test(T_sum, T = n_periods, r = 6, alternative = \"two.sided\")\ncat(\"H0: lambda = 6\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nH0: lambda = 6\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  p-value:\", round(test_6$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p-value: 0.4271 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Decision:\", ifelse(test_6$p.value < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Decision: Fail to reject H0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  lambda0 = 6 in CI?\", ci_lo_pois <= 6 & 6 <= ci_hi_pois, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lambda0 = 6 in CI? TRUE \n```\n\n\n:::\n:::\n\n\n**(iv) Duality check:**\n\n- $\\lambda_0 = 4$: test fails to reject $H_0$ ($p = 0.0918$); $\\lambda_0 = 4$ is inside the CI. **Consistent** ✓\n- $\\lambda_0 = 6$: test fails to reject $H_0$ ($p = 0.4271$); $\\lambda_0 = 6$ is inside the CI. **Consistent** ✓\n\n### Part (c) — One-sided duality\n\nBy the one-sided duality theorem, the dual lower bound for $H_0: \\lambda \\leq \\lambda_0$ vs $H_a: \\lambda > \\lambda_0$ is:\n$$\\underline{\\lambda} = \\frac{\\chi^2_{\\alpha,\\; 2T}}{2n}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlb_one  <- qchisq(alpha_p, df = 2 * T_sum) / (2 * n_periods)\ntest_gt <- poisson.test(T_sum, T = n_periods, r = 4, alternative = \"greater\")\ncat(\"95% lower confidence bound:\", round(lb_one, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower confidence bound: 3.9923 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Lower bound > 4?\", lb_one > 4, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLower bound > 4? FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"One-sided p-value (Ha: lambda > 4):\", round(test_gt$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOne-sided p-value (Ha: lambda > 4): 0.0512 \n```\n\n\n:::\n:::\n\n\nThe lower bound is $\\underline{\\lambda} = 3.9923$. Since 3.9923 ≤ 4, we fail to reject $H_0: \\lambda \\leq 4$ at the 5% level.\n\n---\n\n## Problem 3: Constructing CIs by Inverting Tests (Lesson 16)\n\nA medical device manufacturer tests the precision of a glucose sensor. FDA requirements are $\\sigma < 8$ mg/dL (i.e., $\\sigma^2 < 64$). A quality control study with $n = 20$ measurements yields $s^2 = 42.3\\ (\\text{mg/dL})^2$.\n\n**(a)** Starting from $(n-1)S^2/\\sigma^2 \\sim \\chi^2_{n-1}$, derive the two-sided $100(1-\\alpha)\\%$ CI for $\\sigma^2$ by inverting the acceptance region. Show each algebraic step.\n\n**(b)** Compute the 95% CI for $\\sigma^2$ and $\\sigma$.\n\n**(c)** To test $H_0: \\sigma^2 \\geq 64$ vs $H_a: \\sigma^2 < 64$ at $\\alpha = 0.05$, compute the 95% upper confidence bound for $\\sigma^2$ and state your conclusion.\n\n**(d)** Verify by computing the chi-squared test p-value directly. Does the decision match?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nlos_data <- rexp(30, rate = 0.18)\n```\n:::\n\n\n---\n\n### Part (a) — Derivation\n\nThe pivot is $Q = (n-1)S^2/\\sigma^2 \\sim \\chi^2_{n-1}$. The acceptance region for testing $H_0: \\sigma^2 = \\sigma_0^2$ is:\n\n$$\\chi^2_{1-\\alpha/2,\\, n-1} \\leq \\frac{(n-1)s^2}{\\sigma_0^2} \\leq \\chi^2_{\\alpha/2,\\, n-1}$$\n\nInverting — solve for $\\sigma_0^2$. Divide through (noting that dividing by a positive $\\sigma_0^2$ preserves the direction, then inverting the chi-squared bounds flips the inequalities):\n\n$$\\frac{(n-1)s^2}{\\chi^2_{\\alpha/2,\\, n-1}} \\leq \\sigma_0^2 \\leq \\frac{(n-1)s^2}{\\chi^2_{1-\\alpha/2,\\, n-1}}$$\n\nThis is the $100(1-\\alpha)\\%$ two-sided CI for $\\sigma^2$. Note that $\\chi^2_{\\alpha/2} < \\chi^2_{1-\\alpha/2}$, so the larger denominator in the lower bound gives a smaller value, as required. $\\square$\n\n### Part (b) — Numeric CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dev  <- 20; s2_dev <- 42.3; df_dev <- n_dev - 1; alpha_d <- 0.05\n\nchi_upper <- qchisq(1 - alpha_d/2, df = df_dev)  # larger quantile -> smaller lower bound\nchi_lower <- qchisq(    alpha_d/2, df = df_dev)  # smaller quantile -> larger upper bound\n\nci_v_lo <- df_dev * s2_dev / chi_upper\nci_v_hi <- df_dev * s2_dev / chi_lower\n\ncat(\"chi^2 quantiles:\", round(chi_lower, 3), \"(lower),\", round(chi_upper, 3), \"(upper)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi^2 quantiles: 8.907 (lower), 32.852 (upper)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for sigma^2: [\", round(ci_v_lo, 3), \",\", round(ci_v_hi, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for sigma^2: [ 24.464 , 90.237 ]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI for sigma:   [\", round(sqrt(ci_v_lo), 3), \",\", round(sqrt(ci_v_hi), 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for sigma:   [ 4.946 , 9.499 ]\n```\n\n\n:::\n:::\n\n\n### Part (c) — One-sided upper bound\n\nFor $H_0: \\sigma^2 \\geq 64$ vs $H_a: \\sigma^2 < 64$ (lower-tailed), the dual 95% upper confidence bound is:\n\n$$\\bar{\\sigma}^2 = \\frac{(n-1)s^2}{\\chi^2_{\\alpha,\\, n-1}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_one  <- qchisq(alpha_d, df = df_dev)   # lower-tail alpha quantile\nub_var   <- df_dev * s2_dev / chi_one\nsigma0_sq <- 64\n\ncat(\"95% upper confidence bound for sigma^2:\", round(ub_var, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% upper confidence bound for sigma^2: 79.44 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Upper bound < 64?\", ub_var < sigma0_sq, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUpper bound < 64? FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Conclusion:\", ifelse(ub_var < sigma0_sq,\n    \"Reject H0: sigma^2 >= 64. Sensor meets FDA standard.\",\n    \"Fail to reject H0.\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConclusion: Fail to reject H0. \n```\n\n\n:::\n:::\n\n\nThe 95% upper bound is 79.44. Since 79.44 ≥ 64, we fail to reject $H_0$ and conclude the sensor does not meet the precision requirement.\n\n### Part (d) — Direct chi-squared test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_obs <- df_dev * s2_dev / sigma0_sq\np_chi   <- pchisq(chi_obs, df = df_dev, lower.tail = TRUE)  # lower-tailed\n\ncat(\"chi^2_obs:\", round(chi_obs, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi^2_obs: 12.5578 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value (lower tail):\", round(p_chi, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value (lower tail): 0.1396 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reject H0?\", p_chi < alpha_d, \"-- consistent with part (c)?\",\n    (p_chi < alpha_d) == (ub_var < sigma0_sq), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReject H0? FALSE -- consistent with part (c)? TRUE \n```\n\n\n:::\n:::\n\n\nThe direct test confirms the CI-based conclusion: $p = 0.1396$ ≥ 0.05, so we fail to reject $H_0$ — **consistent with the upper bound in (c)**. ✓\n\n\n---\n\n## Problem 4: Multiple Testing and Simultaneous CIs (Lesson 16)\n\nA Phase III clinical trial evaluates a new heart failure treatment on $m = 6$ pre-specified endpoints. You are given estimated treatment effects $\\hat{\\delta}_j$ and standard errors $\\widehat{SE}_j$:\n\n| Endpoint | $\\hat{\\delta}_j$ | $\\widehat{SE}_j$ |\n|----------|-----------|-----------|\n| 6-min walk distance (meters) | 28.4 | 9.1 |\n| NT-proBNP (pg/mL, log-scale) | -0.31 | 0.09 |\n| Quality of life score (0–100) | 5.2 | 2.1 |\n| Systolic BP (mmHg) | -4.8 | 2.3 |\n| Heart rate (bpm) | -3.1 | 1.6 |\n| Ejection fraction (%) | 2.9 | 1.8 |\n\nAssume $\\hat{\\delta}_j / \\widehat{SE}_j \\approx Z_j \\sim N(0,1)$ under $H_{0j}$.\n\n**(a)** For each endpoint, compute the unadjusted z-test p-value, 95% CI, and rejection decision at $\\alpha = 0.05$.\n\n**(b)** Apply Bonferroni correction to control the familywise error rate at 5%. Which endpoints remain significant?\n\n**(c)** Construct Bonferroni-adjusted 95% simultaneous CIs. Using the duality theorem, explain why wider intervals achieve simultaneous coverage.\n\n**(d)** Under the global null with 6 independent tests at $\\alpha = 0.05$, compute the exact probability of at least one false rejection and the Bonferroni upper bound.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nendpoints <- c(\"6-min walk (m)\", \"NT-proBNP (log)\", \"QoL score\",\n               \"Systolic BP (mmHg)\", \"Heart rate (bpm)\", \"EF (%)\")\ndelta_hat <- c(28.4, -0.31, 5.2, -4.8, -3.1, 2.9)\nse_hat    <- c(9.1,   0.09, 2.1,  2.3,  1.6,  1.8)\nm         <- length(endpoints)\nalpha_mf  <- 0.05\n```\n:::\n\n\n### Part (a) — Unadjusted tests and CIs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_stats   <- delta_hat / se_hat\np_unadj   <- 2 * pnorm(-abs(z_stats))\nz_95      <- qnorm(0.975)\n\nci_lo_ind <- delta_hat - z_95 * se_hat\nci_hi_ind <- delta_hat + z_95 * se_hat\n\ntibble(\n  Endpoint        = endpoints,\n  `delta-hat`     = round(delta_hat, 2),\n  SE              = round(se_hat, 2),\n  `z-stat`        = round(z_stats, 3),\n  `p-value`       = round(p_unadj, 4),\n  `Reject (5%)`   = ifelse(p_unadj < alpha_mf, \"Yes\", \"No\"),\n  `95% CI`        = sprintf(\"[%.2f, %.2f]\", ci_lo_ind, ci_hi_ind)\n) |> knitr::kable(align = \"lrrrrlc\")\n```\n\n::: {.cell-output-display}\n\n\n|Endpoint           | delta-hat|   SE| z-stat| p-value|Reject (5%) |     95% CI     |\n|:------------------|---------:|----:|------:|-------:|:-----------|:--------------:|\n|6-min walk (m)     |     28.40| 9.10|  3.121|  0.0018|Yes         | [10.56, 46.24] |\n|NT-proBNP (log)    |     -0.31| 0.09| -3.444|  0.0006|Yes         | [-0.49, -0.13] |\n|QoL score          |      5.20| 2.10|  2.476|  0.0133|Yes         |  [1.08, 9.32]  |\n|Systolic BP (mmHg) |     -4.80| 2.30| -2.087|  0.0369|Yes         | [-9.31, -0.29] |\n|Heart rate (bpm)   |     -3.10| 1.60| -1.938|  0.0527|No          | [-6.24, 0.04]  |\n|EF (%)             |      2.90| 1.80|  1.611|  0.1072|No          | [-0.63, 6.43]  |\n\n\n:::\n:::\n\n\n### Part (b) — Bonferroni correction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_bon <- alpha_mf / m\nz_bon     <- qnorm(1 - alpha_bon / 2)\n\ncat(\"Bonferroni alpha*:\", round(alpha_bon, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBonferroni alpha*: 0.00833 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical z value: \", round(z_bon, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical z value:  2.6383 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Endpoints significant after Bonferroni:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEndpoints significant after Bonferroni:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(paste(endpoints[p_unadj < alpha_bon], collapse = \"\\n\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6-min walk (m)\nNT-proBNP (log) \n```\n\n\n:::\n:::\n\n\nAt the Bonferroni-corrected level $\\alpha^* = 0.00833$ (z-critical $= 2.6383$), 2 endpoint(s) remain significant: **6-min walk (m), NT-proBNP (log)**.\n\n### Part (c) — Bonferroni simultaneous CIs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci_lo_bon <- delta_hat - z_bon * se_hat\nci_hi_bon <- delta_hat + z_bon * se_hat\n\ntibble(\n  Endpoint           = endpoints,\n  `Indiv. 95% CI`    = sprintf(\"[%.2f, %.2f]\", ci_lo_ind, ci_hi_ind),\n  `Bonf. Simult. CI` = sprintf(\"[%.2f, %.2f]\", ci_lo_bon, ci_hi_bon)\n) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Endpoint           |Indiv. 95% CI  |Bonf. Simult. CI |\n|:------------------|:--------------|:----------------|\n|6-min walk (m)     |[10.56, 46.24] |[4.39, 52.41]    |\n|NT-proBNP (log)    |[-0.49, -0.13] |[-0.55, -0.07]   |\n|QoL score          |[1.08, 9.32]   |[-0.34, 10.74]   |\n|Systolic BP (mmHg) |[-9.31, -0.29] |[-10.87, 1.27]   |\n|Heart rate (bpm)   |[-6.24, 0.04]  |[-7.32, 1.12]    |\n|EF (%)             |[-0.63, 6.43]  |[-1.85, 7.65]    |\n\n\n:::\n:::\n\n\nThe Bonferroni simultaneous CIs are wider than the individual 95% CIs. **By duality**, a $100(1-\\alpha)\\%$ CI is the set of $\\theta_0$ values that a level-$\\alpha$ test fails to reject. To ensure that *all $m$* CIs simultaneously cover their true parameters with probability $\\geq 1-\\alpha$, each individual test must run at level $\\alpha^* = \\alpha/m$. A more stringent test level means a wider acceptance region, which inverts to a wider CI — simultaneous coverage is achieved by widening each interval proportionally.\n\n### Part (d) — Familywise error rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfwer_exact <- 1 - (1 - alpha_mf)^m\nfwer_bon   <- m * alpha_mf\n\ncat(\"FWER exact (independence):\", round(fwer_exact, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFWER exact (independence): 0.2649 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bonferroni upper bound:   \", round(fwer_bon, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBonferroni upper bound:    0.3 \n```\n\n\n:::\n:::\n\n\nUnder the global null and independence:\n$$P(\\text{at least one false rejection}) = 1 - (1-0.05)^6 = 0.2649$$\n\nThe Bonferroni bound is $m\\alpha = 6 \\times 0.05 = 0.30$, which is conservative (a union bound) and slightly exceeds the exact value.\n\n---\n\n## Problem 5: Bootstrap Hypothesis Testing (Lesson 17)\n\nSerum ferritin (ng/mL) is a biomarker for iron stores. A study of $n = 18$ CKD patients gives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nferritin <- c(28.4, 45.2, 19.8, 67.3, 31.5, 88.1, 22.6, 54.9,\n              41.2, 76.8, 33.7, 29.4, 58.3, 44.1, 92.5, 37.6,\n              25.8, 61.4)\n```\n:::\n\n\nThe population norm is $\\mu_0 = 40$ ng/mL. Test $H_0: \\mu = 40$ vs $H_a: \\mu \\neq 40$ at $\\alpha = 0.05$.\n\n**(a)** Make a histogram and describe the distribution's shape. Is normality reasonable?\n\n**(b)** Compute $T_{\\text{obs}} = (\\bar{x} - \\mu_0)/(s/\\sqrt{n})$ and the parametric t-test p-value. State your conclusion.\n\n**(c)** Implement the **correct** bootstrap test with $B = 5{,}000$ (`set.seed(551)`): (i) shift data to $H_0$, (ii) compute bootstrap t-statistics, (iii) compute p-value as $\\hat{p} = B^{-1}\\sum\\mathbf{1}(|T^{*b}| \\geq |T_{\\text{obs}}|)$, (iv) compare to the t-test.\n\n**(d)** Implement the **naive (incorrect)** bootstrap (resample from original, compare $|\\bar{x}^{*b} - \\bar{x}|$ to $|\\bar{x} - \\mu_0|$). Compute the naive p-value and explain in 2–3 sentences why this approach is invalid.\n\n**(e)** Plot histograms of both bootstrap distributions side by side, marking the observed statistic and p-value region on each.\n\n**(f)** Would you expect the bootstrap percentile CI (from resampling the original data) to be approximately dual to the correct bootstrap test from (c)? Explain, referencing the pivot-matching discussion in Lesson 17.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_0 <- 40\nn_f  <- length(ferritin)\nxbar_f <- mean(ferritin); s_f <- sd(ferritin); se_f <- s_f / sqrt(n_f)\n```\n:::\n\n\n### Part (a) — Histogram and shape\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tibble(x = ferritin), aes(x = x)) +\n  geom_histogram(bins = 8, fill = \"#3498db\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = mu_0, linetype = \"dashed\", color = \"#e74c3c\", linewidth = 1.2) +\n  annotate(\"text\", x = mu_0 + 3, y = 3.7, label = expression(mu[0] == 40),\n           color = \"#e74c3c\", size = 5) +\n  labs(title = \"Serum ferritin in CKD patients\",\n       subtitle = \"Dashed line = population norm (40 ng/mL)\",\n       x = \"Serum ferritin (ng/mL)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe distribution is **right-skewed** with a long upper tail (values up to 92.5 ng/mL while many observations cluster below 45 ng/mL). With $n = 18$ and noticeable skewness, the normality assumption is questionable — a bootstrap test is a sensible choice here.\n\n### Part (b) — Parametric t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT_obs_f  <- (xbar_f - mu_0) / se_f\np_ttest  <- t.test(ferritin, mu = mu_0)$p.value\n\ncat(\"Sample mean:\", round(xbar_f, 3), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 47.7 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:  \", round(s_f, 3),   \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD:   22.281 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"T_obs:      \", round(T_obs_f, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT_obs:       1.4662 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-test p:   \", round(p_ttest, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-test p:    0.1608 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Decision:   \", ifelse(p_ttest < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDecision:    Fail to reject H0 \n```\n\n\n:::\n:::\n\n\n### Part (c) — Correct bootstrap test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551); B_f <- 5000\n\nferritin_sh <- ferritin - xbar_f + mu_0   # (i) shift to H0\n\nT_boot_f <- replicate(B_f, {              # (ii) bootstrap t-statistics\n  bs <- sample(ferritin_sh, n_f, replace = TRUE)\n  (mean(bs) - mu_0) / (sd(bs) / sqrt(n_f))\n})\n\np_boot_f <- mean(abs(T_boot_f) >= abs(T_obs_f))   # (iii) p-value\n\n# (iv) comparison\ncat(\"Bootstrap p-value:\", round(p_boot_f, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap p-value: 0.175 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t-test p-value:   \", round(p_ttest,  4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-test p-value:    0.1608 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap decision:\", ifelse(p_boot_f < 0.05, \"Reject H0\", \"Fail to reject H0\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap decision: Fail to reject H0 \n```\n\n\n:::\n:::\n\n\nBoth methods fail to reject $H_0$, and the p-values are close — consistent with Lesson 17's simulation showing that differences between bootstrap and t-test shrink as $n$ increases.\n\n### Part (d) — Naive (incorrect) bootstrap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nT_naive_f <- replicate(B_f, mean(sample(ferritin, n_f, replace = TRUE)))\np_naive_f <- mean(abs(T_naive_f - xbar_f) >= abs(xbar_f - mu_0))\ncat(\"Naive p-value:\", round(p_naive_f, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNaive p-value: 0.1396 \n```\n\n\n:::\n:::\n\n\nThe naive p-value is 0.1396. This approach is invalid because resampling from the original data produces a distribution centered at $\\bar{x} = 47.7$ ng/mL — not at the null value $\\mu_0 = 40$ ng/mL. A valid null distribution must represent how extreme the observed statistic would be *if $H_0$ were true*. Comparing variability around $\\bar{x}$ answers a different question (how variable is our estimator?) rather than the question of interest (how unusual is our result under $H_0$?).\n\n### Part (e) — Side-by-side plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_nv <- ggplot(tibble(T = T_naive_f), aes(x = T)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"#e74c3c\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = xbar_f, color = \"black\", linewidth = 1.2) +\n  geom_vline(xintercept = mu_0,   color = \"#3498db\", linewidth = 1.2, linetype = \"dashed\") +\n  annotate(\"rect\",\n           xmin = xbar_f + abs(xbar_f - mu_0), xmax = Inf, ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"rect\",\n           xmin = -Inf, xmax = xbar_f - abs(xbar_f - mu_0), ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"text\", x = xbar_f + 0.8, y = 0.22,\n           label = \"bar(x)\", parse = TRUE, size = 5) +\n  annotate(\"text\", x = mu_0 - 0.8, y = 0.22,\n           label = \"mu[0]\", parse = TRUE, size = 5, color = \"#3498db\", hjust = 1) +\n  labs(title = expression(bold(\"WRONG\") * \": Naive bootstrap (original data)\"),\n       subtitle = sprintf(\"Centered at x-bar = %.1f, not mu0 = %.1f  |  p = %.4f\",\n                          xbar_f, mu_0, p_naive_f),\n       x = expression(bar(x)^\"*\"), y = \"Density\")\n\np_cr <- ggplot(tibble(T = T_boot_f), aes(x = T)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"#27ae60\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = c(-abs(T_obs_f), abs(T_obs_f)),\n             color = \"#e74c3c\", linewidth = 1.2) +\n  annotate(\"rect\", xmin =  abs(T_obs_f), xmax =  Inf, ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"rect\", xmin = -Inf, xmax = -abs(T_obs_f), ymin = 0, ymax = Inf,\n           fill = \"#e74c3c\", alpha = 0.2) +\n  annotate(\"text\", x = abs(T_obs_f) + 0.2, y = 0.32,\n           label = bquote(T[obs] == .(round(T_obs_f, 2))),\n           color = \"#e74c3c\", size = 4.5) +\n  labs(title = expression(bold(\"CORRECT\") * \": Bootstrap from shifted data\"),\n       subtitle = sprintf(\"Centered at mu0 = %.1f  |  Bootstrap p = %.4f, t-test p = %.4f\",\n                          mu_0, p_boot_f, p_ttest),\n       x = \"t-statistic\", y = \"Density\")\n\np_nv + p_cr\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Part (f) — Conceptual: CI-test duality\n\nA bootstrap **percentile CI** (resampling from original data, using $\\bar{X}^*$ as pivot) and the **bootstrap t-test** in (c) (using standardised $T^* = (\\bar{X}^* - \\mu_0)/(S^*/\\sqrt{n})$ as pivot) use **different pivots**. As demonstrated in Lesson 17, duality is approximate only when both the CI and the test invert the *same* pivot. With the percentile CI (raw-mean pivot) vs. the standardised t-test, there will be systematic disagreements near the CI boundary — particularly evident with small, skewed samples like this one. To achieve approximate duality, one would need to use the raw mean difference $\\bar{x}^* - \\mu_0$ as the test statistic (matching the percentile CI's pivot), or use a bootstrap t-CI (percentile CI of the t-statistic) paired with the t-based bootstrap test.\n\n---\n\n## Problem 6: Devore 9.6 (Modified)\n\nThe plasma concentration (mg/L) of a drug is measured for $n = 12$ patients:\n\n$$X = \\{1.8,\\ 2.6,\\ 3.1,\\ 2.2,\\ 4.7,\\ 2.9,\\ 3.8,\\ 2.4,\\ 1.6,\\ 3.5,\\ 4.1,\\ 2.7\\}$$\n\nThe regulatory target mean concentration is $\\mu_0 = 3.0$ mg/L.\n\n**(a)** Compute $\\bar{x}$, $s$, and the 95% two-sided t-interval for $\\mu$.\n\n**(b)** Use the duality theorem to determine whether you would reject $H_0: \\mu = 3.0$ at $\\alpha = 0.05$ without computing a formal test statistic.\n\n**(c)** Test $H_0: \\mu = 2.5$ vs $H_a: \\mu > 2.5$ at $\\alpha = 0.05$. Compute the t-statistic, p-value, and the dual one-sided 95% lower confidence bound. Do they agree?\n\n**(d)** Sweep $\\mu_0$ over $[1.5, 4.5]$ in steps of 0.05. For each value compute the two-sided t-test p-value. Plot the p-value function and verify that the 95% CI corresponds exactly to the region where $p(\\mu_0) \\geq 0.05$.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_conc <- c(1.8, 2.6, 3.1, 2.2, 4.7, 2.9, 3.8, 2.4, 1.6, 3.5, 4.1, 2.7)\nn_dc      <- length(drug_conc)\nxbar_dc   <- mean(drug_conc)\ns_dc      <- sd(drug_conc)\nse_dc     <- s_dc / sqrt(n_dc)\ndf_dc     <- n_dc - 1\n```\n:::\n\n\n### Part (a) — Summary statistics and 95% t-interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_crit_dc <- qt(0.975, df = df_dc)\nci_lo_dc  <- xbar_dc - t_crit_dc * se_dc\nci_hi_dc  <- xbar_dc + t_crit_dc * se_dc\n\ncat(\"n:\", n_dc, \"  xbar:\", round(xbar_dc, 4), \"  s:\", round(s_dc, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn: 12   xbar: 2.95   s: 0.9357 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% t-CI: [\", round(ci_lo_dc, 4), \",\", round(ci_hi_dc, 4), \"] mg/L\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% t-CI: [ 2.3555 , 3.5445 ] mg/L\n```\n\n\n:::\n:::\n\n\n$\\bar{x} = 2.95$, $s = 0.936$, 95% CI: $[2.356, 3.544]$ mg/L.\n\n### Part (b) — Duality conclusion for $\\mu_0 = 3.0$\n\n$\\mu_0 = 3.0$ falls **inside** the 95% CI $[2.356, 3.544]$. By the CI-Test Duality Theorem, we therefore **fail to reject** $H_0: \\mu = 3.0$ at $\\alpha = 0.05$ — no test statistic needed.\n\n### Part (c) — One-sided test and dual bound\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0_one   <- 2.5\nT_obs_one <- (xbar_dc - mu0_one) / se_dc\np_one     <- pt(T_obs_one, df = df_dc, lower.tail = FALSE)  # Ha: mu > 2.5\n\nt_one     <- qt(0.95, df = df_dc)   # one-sided critical value\nlb_dc     <- xbar_dc - t_one * se_dc\n\ncat(\"T_obs:\", round(T_obs_one, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT_obs: 1.666 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"One-sided p-value:\", round(p_one, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOne-sided p-value: 0.0619 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% lower confidence bound:\", round(lb_dc, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower confidence bound: 2.4649 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Lower bound > 2.5?\", lb_dc > mu0_one, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLower bound > 2.5? FALSE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Duality consistent?\", (p_one < 0.05) == (lb_dc > mu0_one), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDuality consistent? TRUE \n```\n\n\n:::\n:::\n\n\n$T_{\\text{obs}} = 1.666$, $p = 0.0619$. We **fail to reject** $H_0$ at $\\alpha = 0.05$. The dual 95% lower bound is $\\underline{\\mu} = 2.4649$ mg/L; since 2.4649 ≤ 2.5, the bound is consistent with failure to reject. **Duality confirmed** ✓\n\n### Part (d) — p-value function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0_grid <- seq(1.5, 4.5, by = 0.05)\npval_fn  <- map_dbl(mu0_grid, function(mu0) {\n  t_stat <- (xbar_dc - mu0) / se_dc\n  2 * pt(-abs(t_stat), df = df_dc)\n})\n\nggplot(tibble(mu0 = mu0_grid, pval = pval_fn), aes(x = mu0, y = pval)) +\n  annotate(\"rect\", xmin = ci_lo_dc, xmax = ci_hi_dc, ymin = -Inf, ymax = Inf,\n           fill = \"#006a4e\", alpha = 0.12) +\n  geom_vline(xintercept = c(ci_lo_dc, ci_hi_dc),\n             color = \"#006a4e\", linewidth = 1, linetype = \"dotted\") +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", color = \"#e74c3c\", linewidth = 1) +\n  geom_line(color = \"#2c3e50\", linewidth = 1.5) +\n  geom_point(aes(x = xbar_dc, y = 1), size = 3.5, color = \"#006a4e\") +\n  annotate(\"text\", x = xbar_dc, y = 0.90,\n           label = sprintf(\"95%% CI [%.2f, %.2f]\", ci_lo_dc, ci_hi_dc),\n           color = \"#006a4e\", size = 4.5) +\n  annotate(\"text\", x = 4.1, y = 0.09,\n           label = expression(alpha == 0.05), color = \"#e74c3c\", size = 4.5) +\n  labs(\n    title = expression(\"p-value function: p(\" * mu[0] * \")\"),\n    subtitle = \"Green region = 95% CI (fail-to-reject region). Dot = MLE (p = 1).\",\n    x = expression(mu[0] * \" (null value, mg/L)\"),\n    y = \"Two-sided p-value\"\n  )\n```\n\n::: {.cell-output-display}\n![](HW_06_Solutions_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe green shaded region (where $p(\\mu_0) \\geq 0.05$) spans exactly $[2.356, 3.544]$ mg/L — matching the 95% t-CI from part (a) precisely. The CI is exactly the set of null values we would fail to reject at $\\alpha = 0.05$, confirming the duality theorem visually.\n",
    "supporting": [
      "HW_06_Solutions_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}