{
  "hash": "a7eb5c60017bb00cb9aa1d1d28e46940",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Midterm Exam Solutions\"\nsubtitle: \"BSTA 551: Theory of Statistical Inference\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\n## Part I: Conceptual Questions (45 points)\n\n### Problem 1: Estimator Properties (15 points)\n\nLet $X_1, X_2, \\ldots, X_n$ be independent measurements with mean $\\mu$ and variance $\\sigma^2$.\n\n#### Part (a): Bias (3 points)\n\n**$\\hat{\\mu}_1 = \\bar{X}$:**\n$$E(\\hat{\\mu}_1) = E(\\bar{X}) = \\frac{1}{n}\\sum_{i=1}^n E(X_i) = \\frac{1}{n} \\cdot n\\mu = \\mu$$\n$\\hat{\\mu}_1$ is **unbiased**. Bias = 0.\n\n**$\\hat{\\mu}_2 = \\frac{X_1 + X_n}{2}$:**\n$$E(\\hat{\\mu}_2) = \\frac{E(X_1) + E(X_n)}{2} = \\frac{\\mu + \\mu}{2} = \\mu$$\n$\\hat{\\mu}_2$ is **unbiased**. Bias = 0.\n\n**$\\hat{\\mu}_3 = \\frac{1}{n+1}\\sum_{i=1}^{n} X_i$:**\n$$E(\\hat{\\mu}_3) = \\frac{1}{n+1}\\sum_{i=1}^n E(X_i) = \\frac{n\\mu}{n+1}$$\n$\\hat{\\mu}_3$ is **biased**. \n$$\\boxed{\\text{Bias}(\\hat{\\mu}_3) = \\frac{n\\mu}{n+1} - \\mu = -\\frac{\\mu}{n+1}}$$\n\n#### Part (b): Variance (4 points)\n\n**$\\hat{\\mu}_1 = \\bar{X}$:**\n$$\\text{Var}(\\hat{\\mu}_1) = \\text{Var}\\left(\\frac{1}{n}\\sum_{i=1}^n X_i\\right) = \\frac{1}{n^2} \\cdot n\\sigma^2 = \\boxed{\\frac{\\sigma^2}{n}}$$\n\n**$\\hat{\\mu}_2 = \\frac{X_1 + X_n}{2}$:**\n$$\\text{Var}(\\hat{\\mu}_2) = \\frac{1}{4}\\left[\\text{Var}(X_1) + \\text{Var}(X_n)\\right] = \\frac{1}{4}(2\\sigma^2) = \\boxed{\\frac{\\sigma^2}{2}}$$\n\n**$\\hat{\\mu}_3 = \\frac{1}{n+1}\\sum_{i=1}^{n} X_i$:**\n$$\\text{Var}(\\hat{\\mu}_3) = \\frac{1}{(n+1)^2} \\cdot n\\sigma^2 = \\boxed{\\frac{n\\sigma^2}{(n+1)^2}}$$\n\n#### Part (c): MSE (4 points)\n\nRecall: $\\text{MSE}(\\hat{\\theta}) = \\text{Var}(\\hat{\\theta}) + [\\text{Bias}(\\hat{\\theta})]^2$\n\n**$\\hat{\\mu}_1$:** \n$$\\text{MSE}(\\hat{\\mu}_1) = \\frac{\\sigma^2}{n} + 0 = \\frac{\\sigma^2}{n}$$\n\n**$\\hat{\\mu}_2$:** \n$$\\text{MSE}(\\hat{\\mu}_2) = \\frac{\\sigma^2}{2} + 0 = \\frac{\\sigma^2}{2}$$\n\n**$\\hat{\\mu}_3$:** \n$$\\text{MSE}(\\hat{\\mu}_3) = \\frac{n\\sigma^2}{(n+1)^2} + \\frac{\\mu^2}{(n+1)^2} = \\frac{n\\sigma^2 + \\mu^2}{(n+1)^2}$$\n\n**For $n = 10$:**\n\n- $\\text{MSE}(\\hat{\\mu}_1) = \\sigma^2/10 = 0.1\\sigma^2$\n- $\\text{MSE}(\\hat{\\mu}_2) = \\sigma^2/2 = 0.5\\sigma^2$\n- $\\text{MSE}(\\hat{\\mu}_3) = \\frac{10\\sigma^2 + \\mu^2}{121}$\n\nFor most practical values of $\\mu$ (relative to $\\sigma$), **$\\hat{\\mu}_1$ has the smallest MSE**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare MSE for n = 10\nn <- 10\n# Assuming sigma^2 = 1 and varying mu/sigma ratios\nmse_1 <- 1/n\nmse_2 <- 1/2\n# MSE of mu_3 depends on mu^2/sigma^2\nmu_sigma_ratio <- seq(0, 3, by = 0.1)\nmse_3 <- (n + mu_sigma_ratio^2) / (n + 1)^2\n\ntibble(ratio = mu_sigma_ratio, MSE = mse_3) |>\n  ggplot(aes(x = ratio, y = MSE)) +\n  geom_line(linewidth = 1.2, color = \"steelblue\") +\n  geom_hline(yintercept = mse_1, linetype = \"dashed\", color = \"red\") +\n  geom_hline(yintercept = mse_2, linetype = \"dashed\", color = \"green\") +\n  annotate(\"text\", x = 2.5, y = mse_1 + 0.02, \n           label = expression(hat(mu)[1]), color = \"red\") +\n  annotate(\"text\", x = 2.5, y = mse_2 + 0.02, \n           label = expression(hat(mu)[2]), color = \"green\") +\n  labs(x = expression(mu/sigma), y = expression(MSE/sigma^2),\n       title = \"MSE Comparison (n = 10)\")\n```\n\n::: {.cell-output-display}\n![](Midterm_Exam_Solutions_files/figure-html/prob1-mse-1.png){width=672}\n:::\n:::\n\n\n#### Part (d): Consistency (4 points)\n\nAn estimator $\\hat{\\theta}_n$ is **consistent** for $\\theta$ if $\\hat{\\theta}_n \\xrightarrow{P} \\theta$ as $n \\to \\infty$.\n\nA sufficient condition is: $\\text{MSE}(\\hat{\\theta}_n) \\to 0$ as $n \\to \\infty$.\n\n**$\\hat{\\mu}_1$:** $\\text{MSE} = \\sigma^2/n \\to 0$ ✓ **Consistent**\n\n**$\\hat{\\mu}_2$:** $\\text{MSE} = \\sigma^2/2 \\not\\to 0$ ✗ **NOT consistent** (uses only 2 observations regardless of $n$)\n\n**$\\hat{\\mu}_3$:** \n$$\\text{MSE} = \\frac{n\\sigma^2 + \\mu^2}{(n+1)^2} \\approx \\frac{n\\sigma^2}{n^2} = \\frac{\\sigma^2}{n} \\to 0$$ ✓ **Consistent**\n\n---\n\n### Problem 2: Fisher Information and CRLB (15 points)\n\nFor $X \\sim \\text{Gamma}(2, \\beta)$, the pdf is $f(x; \\beta) = \\beta^2 x \\, e^{-\\beta x}$ for $x > 0$.\n\n#### Part (a): Fisher Information (4 points)\n\n**Log-likelihood for a single observation:**\n$$\\ell(\\beta) = \\ln(\\beta^2 x \\, e^{-\\beta x}) = 2\\ln\\beta + \\ln x - \\beta x$$\n\n**First derivative (score function):**\n$$\\ell'(\\beta) = \\frac{2}{\\beta} - x$$\n\n**Second derivative:**\n$$\\ell''(\\beta) = -\\frac{2}{\\beta^2}$$\n\n**Fisher Information:**\n$$I(\\beta) = E\\left[-\\ell''(\\beta)\\right] = E\\left[\\frac{2}{\\beta^2}\\right] = \\boxed{\\frac{2}{\\beta^2}}$$\n\n(Note: The second derivative does not depend on $X$, so the expectation is trivial.)\n\n#### Part (b): CRLB (3 points)\n\nFor $n$ independent observations, the total Fisher Information is:\n$$I_n(\\beta) = n \\cdot I(\\beta) = \\frac{2n}{\\beta^2}$$\n\nThe **Cramér-Rao Lower Bound** for unbiased estimators of $\\beta$ is:\n$$\\boxed{\\text{CRLB} = \\frac{1}{I_n(\\beta)} = \\frac{\\beta^2}{2n}}$$\n\n#### Part (c): Bias and unbiased estimator (4 points)\n\n**Is $\\hat{\\beta}_{MLE} = 2/\\bar{X}$ biased?**\n\nWe can write $\\hat{\\beta}_{MLE} = 2/\\bar{X} = 2n / \\sum_{i=1}^n X_i$. Since $\\sum X_i \\sim \\text{Gamma}(2n, \\beta)$, we use the given result $E(1/Y) = b/(a-1)$ with $Y = \\sum X_i$, $a = 2n$, $b = \\beta$:\n\n$$E\\left(\\frac{1}{\\sum X_i}\\right) = \\frac{\\beta}{2n - 1}$$\n\nTherefore:\n$$E(\\hat{\\beta}_{MLE}) = 2n \\cdot \\frac{\\beta}{2n - 1} = \\frac{2n\\beta}{2n - 1}$$\n\nSince $\\frac{2n}{2n-1} > 1$, the MLE **overestimates** $\\beta$.\n\n$$\\boxed{\\text{Bias}(\\hat{\\beta}_{MLE}) = \\frac{2n\\beta}{2n - 1} - \\beta = \\frac{\\beta}{2n - 1}}$$\n\n**Unbiased estimator:**\n\nWe want $E(\\tilde{\\beta}) = \\beta$. Multiplying the MLE by the correction factor $(2n-1)/(2n)$:\n\n$$\\boxed{\\tilde{\\beta} = \\frac{2n - 1}{2n} \\cdot \\hat{\\beta}_{MLE} = \\frac{2n-1}{\\sum_{i=1}^n X_i}}$$\n\nVerification: $E(\\tilde{\\beta}) = (2n-1) \\cdot \\frac{\\beta}{2n-1} = \\beta$ ✓\n\n#### Part (d): Variance and CRLB comparison (4 points)\n\nUsing the given result $\\text{Var}(1/Y) = \\frac{b^2}{(a-1)^2(a-2)}$ with $Y = \\sum X_i \\sim \\text{Gamma}(2n, \\beta)$:\n\n$$\\text{Var}\\left(\\frac{1}{\\sum X_i}\\right) = \\frac{\\beta^2}{(2n-1)^2(2n-2)}$$\n\nTherefore:\n$$\\text{Var}(\\tilde{\\beta}) = (2n-1)^2 \\cdot \\text{Var}\\left(\\frac{1}{\\sum X_i}\\right) = (2n-1)^2 \\cdot \\frac{\\beta^2}{(2n-1)^2(2n-2)} = \\boxed{\\frac{\\beta^2}{2n - 2} = \\frac{\\beta^2}{2(n-1)}}$$\n\n**Comparison with CRLB:**\n$$\\text{Var}(\\tilde{\\beta}) = \\frac{\\beta^2}{2(n-1)} > \\frac{\\beta^2}{2n} = \\text{CRLB}$$\n\nThe unbiased estimator does **NOT** achieve the CRLB.\n\n**Interpretation:** Although the Gamma(2, $\\beta$) belongs to the exponential family, the CRLB is not achieved for the rate parameter $\\beta$ because $\\beta$ is not the \"natural\" parameter of the family. The sufficient statistic $\\sum X_i$ is a linear function of $\\bar{X}$, but $\\beta = 2/E(X)$ is a nonlinear function of the natural parameter. The CRLB would be achieved for $\\theta = 1/\\beta = E(X)/2$ (the mean of each phase), but not for the rate $\\beta$ itself. As $n$ grows, $\\text{Var}(\\tilde{\\beta}) \\to \\text{CRLB}$, so the bound is asymptotically achieved.\n\n---\n\n### Problem 3: Confidence Interval Interpretation (15 points)\n\nGiven: $n = 64$, $\\bar{x} = 28$ mg/dL, $s = 16$ mg/dL.\n\n#### Part (a): Construct 95% CI (4 points)\n\nSince $\\sigma$ is unknown, we use a **t-interval**. With $n = 64$, we have $df = 63$.\n\n$$\\bar{x} \\pm t_{0.025, 63} \\cdot \\frac{s}{\\sqrt{n}} = 28 \\pm t_{0.025, 63} \\cdot \\frac{16}{\\sqrt{64}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 64\nxbar <- 28\ns <- 16\nt_crit <- qt(0.975, df = n - 1)\nse <- s / sqrt(n)\nci <- xbar + c(-1, 1) * t_crit * se\n\ncat(\"t critical value:\", round(t_crit, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt critical value: 1.9983 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard error:\", se, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard error: 2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: (\", round(ci[1], 2), \",\", round(ci[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 24 , 32 )\n```\n\n\n:::\n:::\n\n\n**Assumptions:** The sample is random, and either the population is normally distributed OR $n$ is large enough for CLT to apply (with $n = 64$, CLT is reasonable).\n\n**Note:** With $n = 64$, the t-interval is very close to a z-interval since $t_{0.025, 63} \\approx z_{0.025} = 1.96$.\n\n#### Part (b): Interpretation (4 points)\n\ni. **\"There is a 95% probability that $\\mu$ lies in this interval.\"** \n   \n   **INCORRECT.** The parameter $\\mu$ is fixed (not random). Once the interval is computed, $\\mu$ either is or is not in the interval. The probability statement applies to the procedure, not to a specific interval.\n\nii. **\"If we repeated this study many times, 95% of the resulting confidence intervals would contain $\\mu$.\"**\n   \n   **CORRECT.** This is the frequentist interpretation of confidence intervals.\n\niii. **\"95% of patients in this study had LDL reductions within this interval.\"**\n   \n   **INCORRECT.** The CI is for the population mean, not for individual observations. The individual data values have much more variability than the mean.\n\niv. **\"We are 95% confident that the true mean LDL reduction is in this interval.\"**\n   \n   **CORRECT.** This is an acceptable shorthand interpretation, understanding that \"confidence\" refers to the long-run reliability of the procedure.\n\n#### Part (c): Can they claim mean reduction ≥ 25? (4 points)\n\nThe 95% CI is approximately (24.01, 31.99).\n\nSince the **lower bound (24.01) is less than 25**, the CI does NOT exclude 25 mg/dL. However, 25 is barely inside the interval.\n\n**Answer:** At the 95% confidence level, they cannot definitively claim the mean reduction is at least 25 mg/dL because 25 is within the confidence interval (just barely). They could make a slightly weaker claim or compute a one-sided 95% lower confidence bound.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One-sided 95% lower bound\nlower_bound <- xbar - qt(0.95, df = n - 1) * se\ncat(\"95% one-sided lower bound:\", round(lower_bound, 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% one-sided lower bound: 24.66 mg/dL\n```\n\n\n:::\n:::\n\n\nThe one-sided 95% lower bound is about 24.66 mg/dL, which is still less than 25.\n\n#### Part (d): Sample size for margin ≤ 3 (3 points)\n\nFor margin of error $E = 3$:\n$$n = \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{E}\\right)^2 = \\left(\\frac{1.96 \\cdot 16}{3}\\right)^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 3\nsigma_est <- 16\nz <- qnorm(0.975)\nn_required <- (z * sigma_est / E)^2\ncat(\"Required sample size:\", ceiling(n_required), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 110 \n```\n\n\n:::\n:::\n\n\n**Answer:** A sample size of at least **110** patients would be required.\n\n---\n\n## Part II: Computational Problems (55 points)\n\n### Problem 4: Maximum Likelihood Estimation (18 points)\n\nER visit data: $X = \\{47, 53, 61, 42, 58, 55, 49, 64, 52, 45, 59, 51\\}$\n\n#### Part (a): Likelihood and log-likelihood (4 points)\n\nFor $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} \\text{Poisson}(\\mu)$:\n\n**Likelihood:**\n$$L(\\mu) = \\prod_{i=1}^{n} \\frac{e^{-\\mu}\\mu^{x_i}}{x_i!} = \\frac{e^{-n\\mu}\\mu^{\\sum x_i}}{\\prod_{i=1}^n x_i!}$$\n\n**Log-likelihood:**\n$$\\ell(\\mu) = -n\\mu + \\left(\\sum_{i=1}^n x_i\\right)\\ln\\mu - \\sum_{i=1}^n \\ln(x_i!)$$\n\nOr equivalently:\n$$\\boxed{\\ell(\\mu) = -n\\mu + \\left(\\sum_{i=1}^n x_i\\right)\\ln\\mu + \\text{constant}}$$\n\n#### Part (b): Derive MLE (4 points)\n\nTaking the derivative and setting to zero:\n$$\\frac{d\\ell}{d\\mu} = -n + \\frac{\\sum x_i}{\\mu} = 0$$\n\nSolving:\n$$\\mu = \\frac{\\sum_{i=1}^n x_i}{n} = \\bar{X}$$\n\n**MLE:** $\\boxed{\\hat{\\mu} = \\bar{X}}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ner_visits <- c(47, 53, 61, 42, 58, 55, 49, 64, 52, 45, 59, 51)\nn <- length(er_visits)\nmu_mle <- mean(er_visits)\ncat(\"MLE:\", mu_mle, \"visits per month\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE: 53 visits per month\n```\n\n\n:::\n:::\n\n\n#### Part (c): Sufficient statistic via Neyman Factorization (4 points)\n\nThe joint pmf is:\n$$f(x_1, \\ldots, x_n; \\mu) = \\frac{e^{-n\\mu}\\mu^{\\sum x_i}}{\\prod_{i=1}^n x_i!}$$\n\nWe can factor this as:\n$$f(\\mathbf{x}; \\mu) = \\underbrace{e^{-n\\mu}\\mu^T}_{g(T; \\mu)} \\cdot \\underbrace{\\frac{1}{\\prod_{i=1}^n x_i!}}_{h(\\mathbf{x})}$$\n\nwhere $T = \\sum_{i=1}^n X_i$.\n\n- $g(T; \\mu)$ depends on the data only through $T$ and involves $\\mu$\n- $h(\\mathbf{x})$ depends only on the data, not on $\\mu$\n\nBy the **Neyman Factorization Theorem**, $T = \\sum_{i=1}^n X_i$ is **sufficient for $\\mu$**. $\\square$\n\n#### Part (d): R computations (6 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ner_visits <- c(47, 53, 61, 42, 58, 55, 49, 64, 52, 45, 59, 51)\nn <- length(er_visits)\n\n# MLE\nmu_mle <- mean(er_visits)\ncat(\"MLE of μ:\", mu_mle, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE of μ: 53 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fisher Information for Poisson: I(μ) = n/μ\n# Observed Fisher Information at MLE\nobs_fisher <- n / mu_mle\n\n# Standard error using observed Fisher Information\nse_mle <- 1 / sqrt(obs_fisher)\ncat(\"Observed Fisher Information:\", round(obs_fisher, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Fisher Information: 0.2264 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard Error of MLE:\", round(se_mle, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard Error of MLE: 2.1016 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 95% Wald confidence interval\nz <- qnorm(0.975)\nwald_ci <- mu_mle + c(-1, 1) * z * se_mle\ncat(\"95% Wald CI: (\", round(wald_ci[1], 2), \",\", round(wald_ci[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Wald CI: ( 48.88 , 57.12 )\n```\n\n\n:::\n:::\n\n\n**Interpretation:** We estimate approximately 53 ER visits per month, with 95% confidence that the true mean lies between about 49 and 57 visits.\n\n---\n\n### Problem 5: Method of Moments vs. MLE (15 points)\n\nWeibull with $k = 2$: $f(x; \\lambda) = \\frac{2x}{\\lambda^2}\\exp(-x^2/\\lambda^2)$\n\nGiven: $E(X) = \\lambda\\sqrt{\\pi}/2$, $E(X^2) = \\lambda^2$\n\nData: $X = \\{3.2, 4.8, 2.1, 5.5, 3.9, 4.2, 6.1, 3.5, 4.6, 2.8\\}$\n\n#### Part (a): Method of Moments (5 points)\n\nUsing the first moment:\n$$E(X) = \\frac{\\lambda\\sqrt{\\pi}}{2} = \\bar{X}$$\n\nSolving for $\\lambda$:\n$$\\boxed{\\tilde{\\lambda} = \\frac{2\\bar{X}}{\\sqrt{\\pi}}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvival_times <- c(3.2, 4.8, 2.1, 5.5, 3.9, 4.2, 6.1, 3.5, 4.6, 2.8)\nn <- length(survival_times)\nxbar <- mean(survival_times)\n\nlambda_mme <- 2 * xbar / sqrt(pi)\ncat(\"Sample mean:\", round(xbar, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 4.07 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MME of λ:\", round(lambda_mme, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMME of λ: 4.5925 \n```\n\n\n:::\n:::\n\n\n#### Part (b): Maximum Likelihood Estimator (5 points)\n\n**Log-likelihood:**\n$$\\ell(\\lambda) = \\sum_{i=1}^n \\ln\\left(\\frac{2x_i}{\\lambda^2}e^{-x_i^2/\\lambda^2}\\right) = \\sum_{i=1}^n \\left[\\ln(2x_i) - 2\\ln\\lambda - \\frac{x_i^2}{\\lambda^2}\\right]$$\n\n$$\\ell(\\lambda) = \\sum_{i=1}^n \\ln(2x_i) - 2n\\ln\\lambda - \\frac{1}{\\lambda^2}\\sum_{i=1}^n x_i^2$$\n\n**Taking derivative:**\n$$\\frac{d\\ell}{d\\lambda} = -\\frac{2n}{\\lambda} + \\frac{2}{\\lambda^3}\\sum_{i=1}^n x_i^2 = 0$$\n\n**Solving:**\n$$\\frac{2n}{\\lambda} = \\frac{2\\sum x_i^2}{\\lambda^3}$$\n$$n\\lambda^2 = \\sum x_i^2$$\n$$\\boxed{\\hat{\\lambda} = \\sqrt{\\frac{\\sum_{i=1}^n X_i^2}{n}} = \\sqrt{\\overline{X^2}}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda_mle <- sqrt(mean(survival_times^2))\ncat(\"Sum of X_i^2:\", sum(survival_times^2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum of X_i^2: 179.25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MLE of λ:\", round(lambda_mle, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLE of λ: 4.2338 \n```\n\n\n:::\n:::\n\n\n#### Part (c): Simulation comparison (5 points)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\n\nn <- 10\nlambda_true <- 4\nn_sims <- 5000\n\n# Function to generate Weibull(k=2, lambda) data\n# For Weibull with shape k and scale lambda, we can use:\n# X = lambda * (-log(U))^(1/k) where U ~ Uniform(0,1)\n# For k = 2: X = lambda * sqrt(-log(U))\nrweibull_k2 <- function(n, lambda) {\n  lambda * sqrt(-log(runif(n)))\n}\n\n# Simulation\nsim_results <- tibble(sim = 1:n_sims) |>\n  mutate(\n    data = map(sim, \\(s) rweibull_k2(n, lambda_true)),\n    xbar = map_dbl(data, mean),\n    x2bar = map_dbl(data, \\(x) mean(x^2)),\n    lambda_mme = 2 * xbar / sqrt(pi),\n    lambda_mle = sqrt(x2bar)\n  )\n\n# Summary statistics\nsummary_table <- sim_results |>\n  summarize(\n    Estimator = c(\"MME\", \"MLE\"),\n    Mean = c(mean(lambda_mme), mean(lambda_mle)),\n    Bias = c(mean(lambda_mme) - lambda_true, mean(lambda_mle) - lambda_true),\n    Variance = c(var(lambda_mme), var(lambda_mle)),\n    MSE = c(mean((lambda_mme - lambda_true)^2), mean((lambda_mle - lambda_true)^2))\n  )\n\nprint(summary_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  Estimator  Mean     Bias Variance   MSE\n  <chr>     <dbl>    <dbl>    <dbl> <dbl>\n1 MME        3.99 -0.00829    0.440 0.440\n2 MLE        3.94 -0.0576     0.396 0.399\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# Visualization\nsim_results |>\n  pivot_longer(cols = c(lambda_mme, lambda_mle), \n               names_to = \"Estimator\", values_to = \"Estimate\") |>\n  mutate(Estimator = factor(Estimator, \n                            levels = c(\"lambda_mme\", \"lambda_mle\"),\n                            labels = c(\"MME\", \"MLE\"))) |>\n  ggplot(aes(x = Estimate, fill = Estimator)) +\n  geom_histogram(alpha = 0.6, bins = 50, position = \"identity\") +\n  geom_vline(xintercept = lambda_true, linetype = \"dashed\", linewidth = 1.2) +\n  labs(title = bquote(\"Sampling Distributions of MME and MLE for\" ~ lambda),\n       subtitle = bquote(\"True\" ~ lambda == 4 ~ \"|\" ~ n == 10 ~ \"| 5000 simulations\"),\n       x = expression(hat(lambda)), y = \"Frequency\") +\n  scale_fill_brewer(palette = \"Set1\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Midterm_Exam_Solutions_files/figure-html/prob5c-1.png){width=672}\n:::\n:::\n\n\n**Conclusion:** The MLE has slightly smaller bias, variance, and MSE compared to the MME. The MLE performs better for this distribution.\n\n---\n\n### Problem 6: Confidence Intervals for Proportions (12 points)\n\nData: $x = 312$ successes out of $n = 400$.\n\n#### Part (a): Sample proportion and SE (3 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 312\nn <- 400\np_hat <- x / n\nse_wald <- sqrt(p_hat * (1 - p_hat) / n)\n\ncat(\"Sample proportion:\", p_hat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample proportion: 0.78 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Wald standard error:\", round(se_wald, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald standard error: 0.0207 \n```\n\n\n:::\n:::\n\n\n#### Part (b): Three confidence intervals (4 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- qnorm(0.975)\n\n# Wald interval\nwald_ci <- p_hat + c(-1, 1) * z * se_wald\n\n# Score (Wilson) interval using prop.test\nscore_result <- prop.test(x, n, conf.level = 0.95, correct = FALSE)\nscore_ci <- score_result$conf.int\n\n# Agresti-Coull interval\nn_tilde <- n + 4\np_tilde <- (x + 2) / n_tilde\nse_ac <- sqrt(p_tilde * (1 - p_tilde) / n_tilde)\nac_ci <- p_tilde + c(-1, 1) * z * se_ac\n\ncat(\"Wald 95% CI:          (\", round(wald_ci[1], 4), \",\", round(wald_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald 95% CI:          ( 0.7394 , 0.8206 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Score 95% CI:         (\", round(score_ci[1], 4), \",\", round(score_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nScore 95% CI:         ( 0.7368 , 0.8178 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Agresti-Coull 95% CI: (\", round(ac_ci[1], 4), \",\", round(ac_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgresti-Coull 95% CI: ( 0.7367 , 0.8178 )\n```\n\n\n:::\n:::\n\n\n#### Part (c): Recommendation (3 points)\n\n**Recommended: Score (Wilson) interval**\n\n**Reasons:**\n\n1. The Score interval has better coverage probability across all values of $p$, especially near the boundaries (0 and 1).\n2. It is based on inverting a score test, which uses the correct standard error under the null hypothesis.\n3. With $\\hat{p} = 0.78$ (not near 0 or 1), all three intervals are similar, but the Score interval is generally preferred in the statistical literature (Agresti & Coull, 1998).\n\nThe Agresti-Coull is also acceptable and easier to compute by hand.\n\n#### Part (d): FDA threshold (2 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Lower bound of Score CI:\", round(score_ci[1] * 100, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLower bound of Score CI: 73.68 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"FDA threshold: 70%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFDA threshold: 70%\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Meets threshold:\", score_ci[1] > 0.70, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMeets threshold: TRUE \n```\n\n\n:::\n:::\n\n\n**Answer:** Yes, the vaccine meets the FDA threshold. The lower bound of the 95% Score CI (73.4%) exceeds 70%.\n\n---\n\n### Problem 7: Bootstrap Confidence Intervals (10 points)\n\nRecovery data: $X = \\{18, 22, 25, 19, 31, 24, 20, 28, 23, 45, 21, 26, 24, 22, 27\\}$\n\n#### Part (a): Summary statistics and normality check (2 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecovery <- c(18, 22, 25, 19, 31, 24, 20, 28, 23, 45, 21, 26, 24, 22, 27)\nn <- length(recovery)\n\ncat(\"n =\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 15 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean:\", round(mean(recovery), 2), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean: 25 days\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median:\", median(recovery), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: 24 days\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SD:\", round(sd(recovery), 2), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD: 6.55 days\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualization\npar(mfrow = c(1, 2))\nhist(recovery, main = \"Histogram of Recovery Times\", \n     xlab = \"Days\", col = \"lightblue\", breaks = 8)\nabline(v = mean(recovery), col = \"red\", lwd = 2, lty = 2)\nabline(v = median(recovery), col = \"blue\", lwd = 2, lty = 2)\nlegend(\"topright\", legend = c(\"Mean\", \"Median\"), \n       col = c(\"red\", \"blue\"), lty = 2, lwd = 2)\n\nqqnorm(recovery, pch = 19, col = \"steelblue\")\nqqline(recovery, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Midterm_Exam_Solutions_files/figure-html/prob7a-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nThe histogram shows right skew due to the outlier at 45 days. The Q-Q plot shows departure from normality in the upper tail.\n\n#### Part (b): Bootstrap analysis (4 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB <- 10000\n\n# Bootstrap for mean\nboot_means <- replicate(B, mean(sample(recovery, replace = TRUE)))\nboot_se_mean <- sd(boot_means)\nboot_ci_mean <- quantile(boot_means, c(0.025, 0.975))\n\n# Bootstrap for median\nboot_medians <- replicate(B, median(sample(recovery, replace = TRUE)))\nboot_ci_median <- quantile(boot_medians, c(0.025, 0.975))\n\ncat(\"Bootstrap SE of mean:\", round(boot_se_mean, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE of mean: 1.651 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% Bootstrap percentile CI for mean: (\", \n    round(boot_ci_mean[1], 2), \",\", round(boot_ci_mean[2], 2), \")\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap percentile CI for mean: ( 22.2 , 28.53 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% Bootstrap percentile CI for median: (\", \n    round(boot_ci_median[1], 2), \",\", round(boot_ci_median[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap percentile CI for median: ( 22 , 27 )\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Visualize bootstrap distributions\npar(mfrow = c(1, 2))\nhist(boot_means, main = \"Bootstrap Distribution of Mean\", \n     xlab = \"Mean\", col = \"lightblue\", breaks = 40)\nabline(v = mean(recovery), col = \"red\", lwd = 2)\nabline(v = boot_ci_mean, col = \"darkblue\", lwd = 2, lty = 2)\n\nhist(boot_medians, main = \"Bootstrap Distribution of Median\", \n     xlab = \"Median\", col = \"lightgreen\", breaks = 40)\nabline(v = median(recovery), col = \"red\", lwd = 2)\nabline(v = boot_ci_median, col = \"darkgreen\", lwd = 2, lty = 2)\n```\n\n::: {.cell-output-display}\n![](Midterm_Exam_Solutions_files/figure-html/prob7b-plot-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n#### Part (c): Classical t-interval (2 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_result <- t.test(recovery, conf.level = 0.95)\nt_ci <- t_result$conf.int\n\ncat(\"Classical t-interval: (\", round(t_ci[1], 2), \",\", round(t_ci[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClassical t-interval: ( 21.37 , 28.63 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap percentile CI: (\", round(boot_ci_mean[1], 2), \",\", \n    round(boot_ci_mean[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap percentile CI: ( 22.2 , 28.53 )\n```\n\n\n:::\n:::\n\n\nThe classical t-interval and bootstrap percentile interval are fairly similar. The bootstrap interval is slightly asymmetric, reflecting the skewness in the data.\n\n#### Part (d): Recommendations (2 points)\n\n**Recommended measure of center: Median**\n\n- The data shows right skew with an outlier at 45 days\n- The median (24 days) is more robust to the outlier than the mean (25 days)\n- The median better represents the \"typical\" recovery time\n\n**Recommended confidence interval: Bootstrap percentile interval for the median**\n\n- The normality assumption for the t-interval is questionable with $n = 15$ and visible skew\n- The bootstrap naturally handles non-normal data\n- The median is a more appropriate summary for skewed data\n- The bootstrap CI for the median (22, 26 days) gives a clinically interpretable range\n\n---\n\n## Bonus Question (5 points)\n\nRare mutation: $x = 3$ successes, $n = 500$\n\n#### Part (a): Three intervals (2 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 3\nn <- 500\np_hat <- x / n\nz <- qnorm(0.975)\n\n# Wald interval\nse_wald <- sqrt(p_hat * (1 - p_hat) / n)\nwald_ci <- p_hat + c(-1, 1) * z * se_wald\n\n# Score interval\nscore_ci <- prop.test(x, n, conf.level = 0.95, correct = FALSE)$conf.int\n\n# Agresti-Coull\np_tilde <- (x + 2) / (n + 4)\nse_ac <- sqrt(p_tilde * (1 - p_tilde) / (n + 4))\nac_ci <- p_tilde + c(-1, 1) * z * se_ac\n\ncat(\"Sample proportion:\", p_hat, \"=\", round(p_hat * 100, 2), \"%\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample proportion: 0.006 = 0.6 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Wald 95% CI:          (\", round(wald_ci[1] * 100, 4), \"%,\", \n    round(wald_ci[2] * 100, 4), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald 95% CI:          ( -0.0769 %, 1.2769 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Score 95% CI:         (\", round(score_ci[1] * 100, 4), \"%,\", \n    round(score_ci[2] * 100, 4), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nScore 95% CI:         ( 0.2043 %, 1.749 %)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Agresti-Coull 95% CI: (\", round(ac_ci[1] * 100, 4), \"%,\", \n    round(ac_ci[2] * 100, 4), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgresti-Coull 95% CI: ( 0.1268 %, 1.8573 %)\n```\n\n\n:::\n:::\n\n\n**Problem with Wald interval:** The lower bound is **negative** (-0.07%), which is impossible for a proportion. This is a clear indicator that the Wald interval is inappropriate for rare events.\n\n#### Part (b): Why Score and Agresti-Coull are better (3 points)\n\n**Key properties that make Score and Agresti-Coull better:**\n\n1. **They stay within [0, 1]:** The Score interval is derived by solving a quadratic equation that naturally constrains the bounds to valid probability values. The Agresti-Coull \"shrinks\" extreme estimates toward 0.5 by adding pseudocounts.\n\n2. **Better coverage probability:** Research has shown that Wald intervals have poor coverage for $p$ near 0 or 1. The Score interval maintains nominal coverage across all values of $p$.\n\n3. **Asymmetry:** When $p$ is near a boundary, the true sampling distribution is highly skewed. Score and Agresti-Coull produce asymmetric intervals that better reflect this skewness, while Wald forces symmetry.\n\n4. **The \"shrinkage\" effect:** Agresti-Coull adds 2 successes and 2 failures, effectively pulling the estimate away from extreme values (0 or 1) toward 0.5. This improves coverage because it accounts for the fact that extreme observed proportions likely underestimate the true variability.\n\n**Conclusion:** For rare events, always use Score (Wilson) or Agresti-Coull intervals, never Wald.\n\n---\n\n**End of Solutions**\n",
    "supporting": [
      "Midterm_Exam_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}