{
  "hash": "e6b3e918611bd4780485317697b496ce",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 7: Confidence Intervals\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-01-26\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 7 - Confidence Intervals\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 7: From Point Estimates to Intervals {background-color=\"#2c3e50\"}\n\n## Review: What We've Learned About Estimation\n\n**Point Estimation (Lessons 1-6):**\n\n-   Estimators: statistics that estimate parameters\n-   Properties: bias, variance, MSE, efficiency\n-   Construction: Method of Moments, Maximum Likelihood\n-   Quality: MVUE, sufficient statistics, Cramér-Rao bound\n\n. . .\n\n**The Limitation of Point Estimates:**\n\nA single number ($\\hat{\\theta} = 0.75$) tells us nothing about **precision** or **uncertainty**.\n\n## Today's Goals\n\n::: incremental\n1.  Understand why we need interval estimates\n2.  Derive confidence intervals using pivotal quantities\n3.  Construct and interpret z-intervals (known $\\sigma$)\n4.  Construct and interpret t-intervals (unknown $\\sigma$)\n5.  Understand confidence intervals for proportions\n6.  Apply these methods to medical research examples\n:::\n\n## Motivating Example: Clinical Trial\n\nA new antihypertensive drug is tested in $n = 36$ patients. The mean reduction in systolic blood pressure is $\\bar{x} = 12.3$ mmHg.\n\n. . .\n\n**Point estimate:** $\\hat{\\mu} = 12.3$ mmHg\n\n. . .\n\n**Questions we can't answer with just the point estimate:**\n\n-   How close is 12.3 to the true mean reduction?\n-   Is the true mean likely to be at least 10 mmHg?\n-   How much could $\\bar{X}$ vary in repeated trials?\n\n. . .\n\n::: callout-note\n## The Solution\nA **confidence interval** provides a range of plausible values for the parameter, along with a measure of confidence.\n:::\n\n# The Fundamental Idea {background-color=\"#27ae60\"}\n\n## From Point to Interval\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-1-1.png){width=1344}\n:::\n:::\n\n\n**Key insight:** The interval captures our uncertainty about the true parameter value.\n\n## What Is a Confidence Interval?\n\n::: callout-important\n## Definition: Confidence Interval\nA **confidence interval (CI)** for a parameter $\\theta$ is a random interval $(L, U)$ computed from sample data such that:\n$$P(L < \\theta < U) = 1 - \\alpha$$\nfor a specified confidence level $1 - \\alpha$.\n:::\n\n. . .\n\n**Important:**\n\n-   $L$ and $U$ are **random** (they depend on the sample)\n-   $\\theta$ is **fixed** (but unknown)\n-   The probability statement is about the **procedure**, not about $\\theta$\n\n## Correct Interpretation of Confidence Intervals\n\n::: callout-warning\n## Common Misconception\n\"There is a 95% probability that $\\mu$ lies in the interval (7.4, 17.2).\"\n\n**This is WRONG!** After computing the interval, $\\mu$ either is or is not in the interval. There's no probability involved.\n:::\n\n. . .\n\n::: callout-tip\n## Correct Interpretation\n\"If we repeated this procedure many times, 95% of the resulting intervals would contain the true $\\mu$.\"\n\nOr more simply: \"We are 95% confident that the true mean lies between 7.4 and 17.2.\"\n:::\n\n## Visualizing Confidence Level: Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate 100 confidence intervals\nset.seed(551)\ntrue_mu <- 10; sigma <- 4; n <- 25\n\nci_data <- tibble(sample_id = 1:100) |>\n  rowwise() |>\n  mutate(\n    xbar = mean(rnorm(n, true_mu, sigma)),\n    lower = xbar - 1.96 * sigma / sqrt(n),\n    upper = xbar + 1.96 * sigma / sqrt(n),\n    contains_mu = lower < true_mu & upper > true_mu\n  )\n\n# Count how many contain the true mean\nsum(ci_data$contains_mu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 94\n```\n\n\n:::\n:::\n\n\n## Visualizing Confidence Level: The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## The R Code for CI Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate 100 confidence intervals\nset.seed(551)\ntrue_mu <- 10; sigma <- 4; n <- 25\n\nci_data <- tibble(sample_id = 1:100) |>\n  rowwise() |>\n  mutate(\n    xbar = mean(rnorm(n, true_mu, sigma)),\n    lower = xbar - 1.96 * sigma / sqrt(n),\n    upper = xbar + 1.96 * sigma / sqrt(n),\n    contains_mu = lower < true_mu & upper > true_mu\n  )\n\n# Proportion containing true mu (should be ~95%)\nmean(ci_data$contains_mu)\n```\n:::\n\n\nThis is how the confidence level works: about 95% of intervals capture $\\mu$.\n\n# Pivotal Quantities {background-color=\"#e74c3c\"}\n\n## The Key to Constructing CIs\n\n::: callout-important\n## Definition: Pivotal Quantity\nA **pivotal quantity** is a function $h(X_1, \\ldots, X_n; \\theta)$ of the data and parameter such that:\n\n1.  It depends on both the sample and $\\theta$\n2.  Its **distribution does not depend on $\\theta$** (or any other unknown parameters)\n:::\n\n. . .\n\n**Why pivotal quantities matter:**\n\n-   We can find critical values that don't depend on unknowns\n-   We can \"solve for $\\theta$\" to get confidence limits\n\n## Example: The Standard Pivotal Quantity\n\nLet $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ known.\n\n. . .\n\nConsider:\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$$\n\n. . .\n\n**Check the properties:**\n\n1.  $Z$ depends on $\\bar{X}$ (data) and $\\mu$ (parameter) ✓\n2.  $Z \\sim N(0, 1)$ — the distribution doesn't depend on $\\mu$ ✓\n\n. . .\n\n$Z$ is a **pivotal quantity**!\n\n## From Pivotal Quantity to CI\n\nSince $Z \\sim N(0, 1)$, we know:\n$$P(-z_{\\alpha/2} < Z < z_{\\alpha/2}) = 1 - \\alpha$$\n\n. . .\n\nSubstitute $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$:\n$$P\\left(-z_{\\alpha/2} < \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < z_{\\alpha/2}\\right) = 1 - \\alpha$$\n\n. . .\n\n**Solve for $\\mu$:**\n$$P\\left(\\bar{X} - z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{X} + z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\\right) = 1 - \\alpha$$\n\n. . .\n\nThis gives us the **confidence interval formula**!\n\n# CI for Mean: $\\sigma$ Known {background-color=\"#3498db\"}\n\n## The Z-Interval\n\n::: callout-important\n## Z Confidence Interval for Normal Mean ($\\sigma$ Known)\nIf $X_1, \\ldots, X_n \\sim N(\\mu, \\sigma^2)$ with $\\sigma$ known, a $100(1-\\alpha)\\%$ CI for $\\mu$ is:\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\nwhere $z_{\\alpha/2}$ is the critical value with $P(Z > z_{\\alpha/2}) = \\alpha/2$.\n:::\n\n. . .\n\n**Common critical values:**\n\n| Confidence Level | $\\alpha$ | $\\alpha/2$ | $z_{\\alpha/2}$ |\n|------------------|----------|------------|----------------|\n| 90% | 0.10 | 0.05 | 1.645 |\n| 95% | 0.05 | 0.025 | 1.960 |\n| 99% | 0.01 | 0.005 | 2.576 |\n\n## Example: Tensile Strength (Devore Example 8.1)\n\nSynthetic fibers are tested for tensile strength. From past data, $\\sigma = 55$ MPa is known. A sample of $n = 31$ fibers has $\\bar{x} = 1064$ MPa.\n\n. . .\n\n**95% Confidence Interval:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 1064\nsigma <- 55\nn <- 31\nalpha <- 0.05\n\nz_crit <- qnorm(1 - alpha/2)\nmargin <- z_crit * sigma / sqrt(n)\n\nc(xbar - margin, xbar + margin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1044.639 1083.361\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** We are 95% confident that the true mean tensile strength is between 1044.6 and 1083.4 MPa.\n\n## Medical Example: Blood Glucose Levels\n\nA hospital monitors fasting blood glucose in diabetic patients. Historical data shows $\\sigma = 18$ mg/dL. A sample of $n = 40$ patients has $\\bar{x} = 142$ mg/dL.\n\n**Construct a 99% CI for the population mean glucose level:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 142\nsigma <- 18\nn <- 40\nalpha <- 0.01\n\nz_crit <- qnorm(1 - alpha/2)\ncat(\"z critical value:\", round(z_crit, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz critical value: 2.576 \n```\n\n\n:::\n\n```{.r .cell-code}\nmargin <- z_crit * sigma / sqrt(n)\ncat(\"Margin of error:\", round(margin, 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargin of error: 7.33 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"99% CI: (\", round(xbar - margin, 1), \",\", round(xbar + margin, 1), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n99% CI: ( 134.7 , 149.3 )\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Clinical interpretation:** We can be 99% confident that the true mean fasting glucose for this patient population is between 134.7 and 149.3 mg/dL.\n\n## Anatomy of a Confidence Interval\n\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Three factors affect the margin of error:**\n\n1. **Confidence level** ($z_{\\alpha/2}$): Higher confidence → wider interval\n2. **Population variability** ($\\sigma$): More variation → wider interval\n3. **Sample size** ($n$): Larger sample → narrower interval\n\n## Interactive: Effect of Confidence Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Same data, different confidence levels\nxbar <- 1064; sigma <- 55; n <- 31\n\nconfidence_levels <- c(0.90, 0.95, 0.99)\n\ntibble(conf_level = confidence_levels) |>\n  mutate(\n    z_crit = qnorm(1 - (1 - conf_level)/2),\n    margin = z_crit * sigma / sqrt(n),\n    lower = xbar - margin,\n    upper = xbar + margin,\n    width = upper - lower\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  conf_level z_crit margin lower upper width\n       <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl>\n1       0.9    1.64   16.2 1048. 1080.  32.5\n2       0.95   1.96   19.4 1045. 1083.  38.7\n3       0.99   2.58   25.4 1039. 1089.  50.9\n```\n\n\n:::\n:::\n\n\n**Takeaway:** Higher confidence requires wider intervals!\n\n## Sample Size Determination\n\n**Question:** How large should $n$ be to achieve a desired precision?\n\n. . .\n\nIf we want the margin of error to be at most $b$:\n$$z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}} \\leq b$$\n\n. . .\n\n**Solving for $n$:**\n$$n \\geq \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{b}\\right)^2$$\n\n## Sample Size Example: Clinical Trial Design\n\nA pharmaceutical company wants to estimate mean drug clearance time. From pilot data, $\\sigma \\approx 25$ minutes. They want a 95% CI with margin of error ≤ 5 minutes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 25\nb <- 5  # desired margin of error\nalpha <- 0.05\nz_crit <- qnorm(1 - alpha/2)\n\nn_required <- (z_crit * sigma / b)^2\ncat(\"Required sample size:\", ceiling(n_required))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 97\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Note:** Always round **up** to ensure the desired precision!\n\n## One-Sided Confidence Bounds\n\nSometimes we only care about one direction:\n\n-   **Lower bound:** We want to know the minimum plausible value\n-   **Upper bound:** We want to know the maximum plausible value\n\n. . .\n\n::: callout-tip\n## One-Sided Bounds\n**Lower Confidence Bound:** $\\bar{x} - z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu$\n\n**Upper Confidence Bound:** $\\mu < \\bar{x} + z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n\nNote: Use $z_\\alpha$ (not $z_{\\alpha/2}$) for one-sided bounds at confidence level $1 - \\alpha$.\n:::\n\n## Medical Example: Drug Half-Life\n\nA pharmacologist measures half-life of a new drug. With $n = 20$ subjects, $\\bar{x} = 4.2$ hours, and known $\\sigma = 0.8$ hours.\n\n**Find a 95% lower confidence bound:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 4.2\nsigma <- 0.8\nn <- 20\nalpha <- 0.05\n\nz_crit <- qnorm(1 - alpha)  # Note: z_alpha, not z_alpha/2\nlower_bound <- xbar - z_crit * sigma / sqrt(n)\n\ncat(\"95% lower confidence bound:\", round(lower_bound, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower confidence bound: 3.91 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretation: We are 95% confident that the true half-life\",\n    \"\\nis at least\", round(lower_bound, 2), \"hours\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: We are 95% confident that the true half-life \nis at least 3.91 hours\n```\n\n\n:::\n:::\n\n\n# CI for Mean: $\\sigma$ Unknown {background-color=\"#9b59b6\"}\n\n## The Realistic Case\n\nIn practice, we **rarely know** the population standard deviation $\\sigma$.\n\n. . .\n\n**Natural idea:** Replace $\\sigma$ with the sample standard deviation $s$.\n\n. . .\n\nBut what happens to our pivotal quantity?\n\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\sim N(0, 1)$$\n\nbecomes\n\n$$T = \\frac{\\bar{X} - \\mu}{S/\\sqrt{n}} \\sim \\; ???$$\n\n## The t Distribution\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe t distribution has **heavier tails** than the normal — accounting for extra uncertainty from estimating $\\sigma$.\n\n## Student's t Distribution\n\n::: callout-important\n## Gosset's Theorem\nIf $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$, then:\n$$T = \\frac{\\bar{X} - \\mu}{S/\\sqrt{n}} \\sim t_{n-1}$$\nwhere $t_{n-1}$ denotes the t distribution with $n-1$ **degrees of freedom**.\n:::\n\n. . .\n\n**Key properties of $t_\\nu$:**\n\n-   Symmetric around 0\n-   Heavier tails than $N(0, 1)$\n-   As $\\nu \\to \\infty$, $t_\\nu \\to N(0, 1)$\n\n## Why $(n-1)$ Degrees of Freedom?\n\nThe sample variance involves:\n$$S^2 = \\frac{1}{n-1}\\sum_{i=1}^n(X_i - \\bar{X})^2$$\n\n. . .\n\nSince $\\sum(X_i - \\bar{X}) = 0$, knowing any $n-1$ deviations determines the last one.\n\n. . .\n\n**Intuition:** We \"use up\" one degree of freedom by estimating $\\mu$ with $\\bar{X}$.\n\n## The One-Sample t Interval\n\n::: callout-important\n## t Confidence Interval for Normal Mean ($\\sigma$ Unknown)\nIf $X_1, \\ldots, X_n \\sim N(\\mu, \\sigma^2)$, a $100(1-\\alpha)\\%$ CI for $\\mu$ is:\n$$\\bar{x} \\pm t_{\\alpha/2, n-1} \\cdot \\frac{s}{\\sqrt{n}}$$\nwhere $t_{\\alpha/2, n-1}$ is the critical value with $P(T > t_{\\alpha/2, n-1}) = \\alpha/2$ for $T \\sim t_{n-1}$.\n:::\n\n. . .\n\nThe quantity $s/\\sqrt{n}$ is called the **standard error of the mean** (SEM or SE).\n\n## t Critical Values\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare z and t critical values for 95% CI\nz_crit <- qnorm(0.975)\n\ndf_values <- c(5, 10, 20, 30, 50, 100, Inf)\nt_crits <- qt(0.975, df = df_values)\n\ntibble(\n  df = c(\"5\", \"10\", \"20\", \"30\", \"50\", \"100\", \"∞ (z)\"),\n  t_critical = round(c(head(t_crits, -1), z_crit), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  df    t_critical\n  <chr>      <dbl>\n1 5           2.57\n2 10          2.23\n3 20          2.09\n4 30          2.04\n5 50          2.01\n6 100         1.98\n7 ∞ (z)       1.96\n```\n\n\n:::\n:::\n\n\n**Key insight:** For small samples, $t$ critical values are substantially larger than $z$ critical values.\n\n## Example: Porsche Odometer Readings (Devore Example 8.8)\n\nA sample of $n = 16$ used Porsche Boxsters has odometer readings (miles):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodometer <- c(80000, 30100, 97500, 58551, 73787, 51800, 69267, 44530,\n              42192, 104920, 41442, 27418, 43436, 77219, 5991, 14362)\n\nn <- length(odometer)\nxbar <- mean(odometer)\ns <- sd(odometer)\n\ncat(\"Sample size:\", n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: 16 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample mean:\", round(xbar, 1), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 53907.2 miles\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:\", round(s, 1), \"miles\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD: 28287.2 miles\n```\n\n\n:::\n:::\n\n\n## Example: Porsche (continued)\n\n**95% Confidence Interval:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nt_crit <- qt(1 - alpha/2, df = n - 1)\n\ncat(\"t critical value (df=15):\", round(t_crit, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt critical value (df=15): 2.131 \n```\n\n\n:::\n\n```{.r .cell-code}\nse <- s / sqrt(n)\nmargin <- t_crit * se\n\ncat(\"Standard error:\", round(se, 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard error: 7071.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Margin of error:\", round(margin, 1), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargin of error: 15073.2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: (\", round(xbar - margin, 1), \",\", round(xbar + margin, 1), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 38834 , 68980.4 )\n```\n\n\n:::\n:::\n\n\n## Checking the Normality Assumption\n\nThe t interval assumes normally distributed data. Always check!\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nhist(odometer, main = \"Histogram\", xlab = \"Odometer (miles)\", col = \"lightblue\")\nqqnorm(odometer, main = \"Normal Q-Q Plot\", pch = 19)\nqqline(odometer, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot looks reasonably linear — normality assumption is plausible.\n\n## Medical Example: Systolic Blood Pressure\n\nA clinical study measures systolic blood pressure in $n = 25$ patients after a new treatment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulated BP data (mmHg)\nbp <- c(118, 124, 131, 127, 122, 119, 128, 135, 121, 126,\n        130, 124, 129, 133, 120, 125, 127, 132, 123, 128,\n        126, 131, 122, 129, 125)\n\nn <- length(bp)\nxbar <- mean(bp)\ns <- sd(bp)\n\n# 95% CI\nt_crit <- qt(0.975, df = n - 1)\nse <- s / sqrt(n)\nci <- c(xbar - t_crit * se, xbar + t_crit * se)\n\ncat(\"Sample mean:\", round(xbar, 1), \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 126.2 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:\", round(s, 1), \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD: 4.5 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% CI: (\", round(ci[1], 1), \",\", round(ci[2], 1), \") mmHg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 124.3 , 128.1 ) mmHg\n```\n\n\n:::\n:::\n\n\n## Using t.test() in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The easy way to compute t confidence intervals\nt.test(bp, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  bp\nt = 140.51, df = 24, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 124.3463 128.0537\nsample estimates:\nmean of x \n    126.2 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Note:** R's `t.test()` also performs a hypothesis test (which we'll cover later).\n\n# Confidence Intervals for Proportions {background-color=\"#e67e22\"}\n\n## The Setup\n\n**Situation:** We observe $X$ successes in $n$ independent Bernoulli trials.\n\n-   $X \\sim \\text{Binomial}(n, p)$\n-   Point estimate: $\\hat{p} = X/n$\n\n. . .\n\n**Examples:**\n\n-   Proportion of patients responding to treatment\n-   Proportion of adverse events\n-   Disease prevalence in a population\n\n## The Wald Interval (Traditional)\n\nFor large $n$, $\\hat{P} = X/n$ is approximately normal:\n$$\\hat{P} \\approx N\\left(p, \\frac{p(1-p)}{n}\\right)$$\n\n. . .\n\n**The Wald (traditional) 95% CI:**\n$$\\hat{p} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\n. . .\n\n::: callout-warning\n## Problems with the Wald Interval\n-   Poor coverage probability for $p$ near 0 or 1\n-   Can produce bounds outside [0, 1]\n-   Not recommended for small samples\n:::\n\n## Coverage Problems with Wald\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_old2_long_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe Wald interval often has coverage **below** the nominal level!\n\n## The Score (Wilson) Interval\n\nA better approach: solve for $p$ in the pivotal quantity directly.\n\n::: callout-important\n## Score Confidence Interval for a Proportion\n$$\\frac{\\hat{p} + \\frac{z_{\\alpha/2}^2}{2n} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n} + \\frac{z_{\\alpha/2}^2}{4n^2}}}{1 + \\frac{z_{\\alpha/2}^2}{n}}$$\n:::\n\n. . .\n\n**Advantages:**\n\n-   Coverage probability much closer to nominal level\n-   Handles extreme proportions well\n-   Always produces bounds in [0, 1]\n\n## The Agresti-Coull Interval\n\nA simpler approximation that works well in practice:\n\n::: callout-tip\n## Agresti-Coull (\"Add Two Successes and Two Failures\")\nLet $\\tilde{n} = n + 4$ and $\\tilde{p} = \\frac{X + 2}{n + 4}$\n\nThen use:\n$$\\tilde{p} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\tilde{p}(1-\\tilde{p})}{\\tilde{n}}}$$\n:::\n\n. . .\n\n**Why it works:** Adding 2 successes and 2 failures \"shrinks\" extreme estimates toward 0.5.\n\n## Comparing Intervals: Clinical Trial Example\n\nIn a Phase II trial, 23 of 40 patients respond to treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 23; n <- 40; p_hat <- x/n\ncat(\"Sample proportion:\", p_hat, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample proportion: 0.575 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wald interval\nse_wald <- sqrt(p_hat * (1 - p_hat) / n)\nwald_ci <- p_hat + c(-1, 1) * 1.96 * se_wald\n\n# Agresti-Coull interval\nn_tilde <- n + 4\np_tilde <- (x + 2) / n_tilde\nse_ac <- sqrt(p_tilde * (1 - p_tilde) / n_tilde)\nac_ci <- p_tilde + c(-1, 1) * 1.96 * se_ac\n\ncat(\"Wald 95% CI:          (\", round(wald_ci[1], 3), \",\", round(wald_ci[2], 3), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald 95% CI:          ( 0.422 , 0.728 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Agresti-Coull 95% CI: (\", round(ac_ci[1], 3), \",\", round(ac_ci[2], 3), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgresti-Coull 95% CI: ( 0.422 , 0.715 )\n```\n\n\n:::\n:::\n\n\n## Using prop.test() for Score Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Score (Wilson) interval in R\nprop.test(x = 23, n = 40, conf.level = 0.95, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  23 out of 40, null probability 0.5\nX-squared = 0.9, df = 1, p-value = 0.3428\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.4219507 0.7149061\nsample estimates:\n    p \n0.575 \n```\n\n\n:::\n:::\n\n\n## Medical Example: Adverse Event Rate\n\nIn a safety study, 8 out of 200 patients experience a serious adverse event.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 8; n <- 200\n\n# Score interval\nresult <- prop.test(x, n, conf.level = 0.95, correct = FALSE)\ncat(\"Point estimate:\", x/n, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint estimate: 0.04 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% Score CI:\", round(result$conf.int, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Score CI: 0.0204 0.0769\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Clinical interpretation:** We are 95% confident that the true rate of serious adverse events is between 1.8% and 7.7%.\n\n## Sample Size for Proportions\n\nTo achieve a margin of error $b$ with confidence level $1 - \\alpha$:\n\n$$n = \\frac{z_{\\alpha/2}^2 \\cdot p(1-p)}{b^2}$$\n\n. . .\n\n**Problem:** We don't know $p$ before the study!\n\n. . .\n\n**Conservative approach:** Use $p = 0.5$ (maximizes $p(1-p)$):\n$$n = \\frac{z_{\\alpha/2}^2 \\cdot 0.25}{b^2}$$\n\n## Sample Size Example: Disease Prevalence\n\nAn epidemiologist wants to estimate disease prevalence with a margin of error ≤ 3% with 95% confidence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- 0.03  # margin of error\nz <- qnorm(0.975)\n\n# Conservative (p = 0.5)\nn_conservative <- z^2 * 0.25 / b^2\ncat(\"Conservative sample size:\", ceiling(n_conservative), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConservative sample size: 1068 \n```\n\n\n:::\n\n```{.r .cell-code}\n# If we believe p ≈ 0.10\nn_informed <- z^2 * 0.10 * 0.90 / b^2\ncat(\"Informed sample size (p ≈ 0.10):\", ceiling(n_informed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInformed sample size (p ≈ 0.10): 385\n```\n\n\n:::\n:::\n\n\n## Summary: CI Methods Comparison\n\n| Method | When to Use | Notes |\n|--------|-------------|-------|\n| Z-interval | Normal data, $\\sigma$ known | Rarely applicable |\n| t-interval | Normal data, $\\sigma$ unknown | Check normality |\n| Wald (proportion) | Large $n$, $p$ not extreme | Poor coverage |\n| Score/Wilson | General | Best for proportions |\n| Agresti-Coull | Quick calculation | Good approximation |\n\n# Interpreting CIs in Practice {background-color=\"#16a085\"}\n\n## What CIs Tell Us\n\n::: callout-tip\n## Valid Interpretations\n-   \"We are 95% confident that $\\mu$ lies between L and U\"\n-   \"The interval (L, U) is a plausible range for $\\mu$\"\n-   \"In repeated sampling, 95% of such intervals would contain $\\mu$\"\n:::\n\n. . .\n\n::: callout-warning\n## Invalid Interpretations\n-   \"There is a 95% probability that $\\mu$ is in (L, U)\" ✗\n-   \"95% of the data falls between L and U\" ✗\n-   \"The true mean varies between L and U\" ✗\n:::\n\n## Common Mistakes in Medical Literature\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Mistake                                                  |Correct Interpretation                            |\n|:--------------------------------------------------------|:-------------------------------------------------|\n|The probability that the true effect is in the CI is 95% |We are 95% confident the true effect is in the CI |\n|95% of patients have values in this range                |We are 95% confident the mean is in this range    |\n|If we repeat the study, results will be in the CI        |95% of future CIs would contain the true mean     |\n\n\n:::\n:::\n\n\n## Clinical Decision Making\n\n**Example:** A drug reduces blood pressure by an estimated 12 mmHg with 95% CI (8, 16).\n\n. . .\n\n**Questions we can answer:**\n\n-   Is the effect clinically meaningful? (If minimum important difference is 5 mmHg, yes!)\n-   Is zero a plausible value? (No — CI excludes 0)\n-   What's the worst-case scenario? (Lower bound suggests at least 8 mmHg effect)\n\n## Relationship to Hypothesis Testing\n\n::: callout-note\n## Preview of Coming Material\nA 95% CI contains all parameter values that would **not** be rejected by a two-sided test at $\\alpha = 0.05$.\n\n-   If CI excludes the null value → reject $H_0$\n-   If CI includes the null value → fail to reject $H_0$\n:::\n\n. . .\n\n**Example:** 95% CI for mean difference is (8, 16).\n\n-   Test $H_0: \\mu = 0$ → Reject (0 not in CI)\n-   Test $H_0: \\mu = 10$ → Fail to reject (10 in CI)\n\n# Summary and Looking Ahead {background-color=\"#2c3e50\"}\n\n## Lesson 7 Summary\n\n**Key Concepts:**\n\n1.  **Confidence Intervals** provide a range of plausible values with quantified uncertainty\n\n2.  **Pivotal Quantities** allow us to construct CIs without knowing unknown parameters\n\n3.  **Z-intervals** ($\\sigma$ known): $\\bar{x} \\pm z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$\n\n4.  **t-intervals** ($\\sigma$ unknown): $\\bar{x} \\pm t_{\\alpha/2, n-1}\\frac{s}{\\sqrt{n}}$\n\n5.  **Proportion intervals**: Score/Wilson preferred over Wald\n\n## Key Formulas\n\n| Parameter | CI Formula | Conditions |\n|-----------|------------|------------|\n| $\\mu$ ($\\sigma$ known) | $\\bar{x} \\pm z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$ | Normal data |\n| $\\mu$ ($\\sigma$ unknown) | $\\bar{x} \\pm t_{\\alpha/2, n-1}\\frac{s}{\\sqrt{n}}$ | Normal data |\n| $p$ (Wald) | $\\hat{p} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$ | Large $n$ |\n| $p$ (Agresti-Coull) | $\\tilde{p} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\tilde{p}(1-\\tilde{p})}{\\tilde{n}}}$ | General |\n\n## Lesson 7 Practice Problems\n\n1.  **(Devore 8.1)** Consider a normal population with $\\sigma$ known. \n    a. What is the confidence level for the interval $\\bar{x} \\pm 2.81\\sigma/\\sqrt{n}$?\n    b. What is the confidence level for the interval $\\bar{x} \\pm 1.44\\sigma/\\sqrt{n}$?\n\n2.  **(Devore 8.9)** A CI for true average breaking strength is (1142.4, 1257.6). \n    a. What assumptions must hold for this to be valid?\n    b. What sample size was used?\n\n3.  **(Devore 8.17)** Compute a 95% CI for mean tensile strength based on $n = 20$, $\\bar{x} = 13.71$, $s = 3.55$.\n\n4.  **(Devore 8.43)** In a survey, 859 of 1044 adults support mandatory GMO labeling. Construct a 95% CI for the true proportion.\n\n## Lesson 7 Practice Problems (continued)\n\n5.  **(Medical Application)** A clinical trial tests a new cholesterol medication. In $n = 48$ patients, the mean LDL reduction is $\\bar{x} = 35$ mg/dL with $s = 18$ mg/dL.\n    a. Construct a 95% CI for the mean LDL reduction.\n    b. Construct a 99% CI. How does it compare?\n    c. The company claims a mean reduction of at least 30 mg/dL. Is this claim supported?\n\n6.  **(Chihara 7.1)** Explain why the statement \"There is a 95% probability that $\\mu$ lies in the interval (29.5, 33.4)\" is incorrect.\n\n7.  **(Sample Size)** How many subjects are needed to estimate the proportion of patients responding to a treatment within $\\pm 5\\%$ with 95% confidence?\n\n## Looking Ahead\n\n**Next Session (Lesson 7 Part 2): Bootstrap Confidence Intervals**\n\n-   What if normality doesn't hold?\n-   Bootstrap percentile intervals\n-   Bootstrap t intervals\n-   When to use bootstrap vs. classical methods\n\n. . .\n\n**Coming Soon:**\n\n-   Hypothesis testing (Lessons 9-12)\n-   Two-sample inference (Lesson 13)\n-   Paired data analysis (Lesson 14)\n\n## References\n\n::: nonincremental\n-   Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Chapter 8.1-8.4\n-   Chihara and Hesterberg. *Mathematical Statistics with Resampling and R* (Wiley). Chapter 7.\n-   Agresti, A. and Coull, B. (1998). Approximate is better than \"exact\" for interval estimation of binomial proportions. *The American Statistician*, 52:119-126.\n:::\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n",
    "supporting": [
      "07_Confidence_Intervals_old2_long_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}