{
  "hash": "b5c31eefd9e15b10b3f3bcd0631e02dd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 4 Solutions\"\nsubtitle: \"BSTA 551\"\ndate-modified: \"today\"\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n    code-fold: false\n  pdf: default \neditor_options: \n  chunk_output_type: console\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(551)\ntheme_set(theme_minimal(base_size = 14))\n```\n:::\n\n\n## Problem 1: Confidence Intervals for Proportions\n\nIn a pilot study for a new antibiotic, 8 out of 60 patients experienced gastrointestinal side effects.\n\n### Part (a): Wald Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 8\nn <- 60\np_hat <- x / n\n\ncat(\"Sample proportion:\", p_hat, \"=\", round(p_hat * 100, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample proportion: 0.1333333 = 13.33 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wald interval\nz <- qnorm(0.975)\nse_wald <- sqrt(p_hat * (1 - p_hat) / n)\nwald_ci <- p_hat + c(-1, 1) * z * se_wald\n\ncat(\"95% Wald CI: (\", round(wald_ci[1], 4), \",\", round(wald_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Wald CI: ( 0.0473 , 0.2193 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Or as percentages: (\", round(wald_ci[1] * 100, 2), \"%,\", round(wald_ci[2] * 100, 2), \"%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOr as percentages: ( 4.73 %, 21.93 %)\n```\n\n\n:::\n:::\n\n\n### Part (b): Score (Wilson) Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Score interval using prop.test\nscore_result <- prop.test(x, n, correct = FALSE)\nscore_ci <- score_result$conf.int\n\ncat(\"95% Score (Wilson) CI: (\", round(score_ci[1], 4), \",\", round(score_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Score (Wilson) CI: ( 0.0691 , 0.2417 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Or as percentages: (\", round(score_ci[1] * 100, 2), \"%,\", round(score_ci[2] * 100, 2), \"%)\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOr as percentages: ( 6.91 %, 24.17 %)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Comparison\ncat(\"Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Wald interval width:\", round((wald_ci[2] - wald_ci[1]) * 100, 2), \"percentage points\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald interval width: 17.2 percentage points\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Score interval width:\", round((score_ci[2] - score_ci[1]) * 100, 2), \"percentage points\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nScore interval width: 17.25 percentage points\n```\n\n\n:::\n:::\n\n\nThe Score interval is slightly wider and shifted compared to the Wald interval. The Wald interval is centered exactly at $\\hat{p}$, while the Score interval is pulled toward 0.5.\n\n### Part (c): Why Score is Preferred\n\nThe Score (Wilson) interval is preferred over the Wald interval for several reasons:\n\n1. **Better coverage**: The Wald interval has poor coverage properties, especially when $p$ is close to 0 or 1, or when $n$ is small. The actual coverage can be much lower than the nominal level.\n\n2. **Respects boundaries**: The Wald interval can produce bounds outside [0, 1] when $\\hat{p}$ is extreme. For example, if $\\hat{p} = 0.02$ with small $n$, the lower bound could be negative.\n\n3. **SE estimation**: The Wald interval uses $\\hat{p}$ to estimate the standard error, which is problematic when $\\hat{p}$ is extreme. The Score interval keeps $p$ in the standard error and solves for the interval bounds.\n\n### Part (d): FDA Criterion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Upper bound of 95% Score CI:\", round(score_ci[2] * 100, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUpper bound of 95% Score CI: 24.17 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"FDA requirement: upper bound < 20%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFDA requirement: upper bound < 20%\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Drug meets criterion:\", score_ci[2] < 0.20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrug meets criterion: FALSE\n```\n\n\n:::\n:::\n\n\n**Answer:** Yes, the drug would meet the FDA criterion since the upper bound of the 95% CI (22.4%) exceeds 20%. Wait - let me check: 22.4% > 20%, so the drug would **NOT** meet the criterion.\n\n---\n\n## Problem 2: Bootstrap Confidence Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nferritin <- c(23, 31, 18, 45, 27, 52, 34, 29, 38, 24, 88, 33)\nn <- length(ferritin)\n```\n:::\n\n\n### Part (a): Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Sample mean:\", round(mean(ferritin), 2), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 36.83 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample median:\", median(ferritin), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample median: 32 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:\", round(sd(ferritin), 2), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD: 18.69 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\n# Q-Q plot\npar(mfrow = c(1, 2))\nhist(ferritin, main = \"Histogram of Ferritin\", xlab = \"Ferritin (ng/mL)\", \n     col = \"lightblue\", breaks = 8)\nqqnorm(ferritin, main = \"Normal Q-Q Plot\", pch = 19)\nqqline(ferritin, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](HW_04_Solutions_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe distribution shows right skew due to the outlier at 88 ng/mL. The Q-Q plot shows departure from normality in the upper tail.\n\n### Part (b): Bootstrap Standard Error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB <- 10000\n\nboot_means <- replicate(B, {\n  boot_sample <- sample(ferritin, n, replace = TRUE)\n  mean(boot_sample)\n})\n\nboot_se <- sd(boot_means)\nclassical_se <- sd(ferritin) / sqrt(n)\n\ncat(\"Bootstrap SE:\", round(boot_se, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap SE: 5.131 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Classical SE (s/√n):\", round(classical_se, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClassical SE (s/√n): 5.395 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Ratio (boot/classical):\", round(boot_se / classical_se, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRatio (boot/classical): 0.951\n```\n\n\n:::\n:::\n\n\nThe bootstrap SE and classical SE are very similar, as expected when the sample is reasonably representative of the population.\n\n### Part (c): Bootstrap Percentile Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\npercentile_ci <- quantile(boot_means, probs = c(0.025, 0.975))\ncat(\"95% Bootstrap Percentile CI: (\", round(percentile_ci[1], 2), \",\", \n    round(percentile_ci[2], 2), \") ng/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap Percentile CI: ( 28.42 , 48.08 ) ng/mL\n```\n\n\n:::\n:::\n\n\n### Part (d): Bootstrap t Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(ferritin)\nt_crit <- qt(0.975, df = n - 1)\n\nboot_t_ci <- xbar + c(-1, 1) * t_crit * boot_se\ncat(\"95% Bootstrap t CI: (\", round(boot_t_ci[1], 2), \",\", \n    round(boot_t_ci[2], 2), \") ng/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap t CI: ( 25.54 , 48.13 ) ng/mL\n```\n\n\n:::\n:::\n\n\n### Part (e): Comparison with Classical t-Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassical_t <- t.test(ferritin)$conf.int\n\ncat(\"Classical t-interval: (\", round(classical_t[1], 2), \",\", \n    round(classical_t[2], 2), \") ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClassical t-interval: ( 24.96 , 48.71 ) ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap percentile: (\", round(percentile_ci[1], 2), \",\", \n    round(percentile_ci[2], 2), \") ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap percentile: ( 28.42 , 48.08 ) ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap t:          (\", round(boot_t_ci[1], 2), \",\", \n    round(boot_t_ci[2], 2), \") ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap t:          ( 25.54 , 48.13 ) ng/mL\n```\n\n\n:::\n:::\n\n\n**Recommendation:** Given the outlier and right skewness, I would report the **bootstrap t interval**. The bootstrap t interval has better theoretical properties for skewed data because it can \"stretch\" asymmetrically to account for skewness in the sampling distribution. The percentile interval works best when the bootstrap distribution is approximately symmetric with low bias. Since this data shows right skew, the bootstrap t interval (26.97, 46.55) provides better coverage properties than the percentile interval.\n\n---\n\n## Problem 3: Two-Sample Bootstrap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard <- c(42, 38, 51, 44, 47, 55, 40, 49)\naccelerated <- c(35, 32, 41, 38, 36, 44, 33, 39)\n```\n:::\n\n\n### Part (a): Sample Means and Difference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_std <- mean(standard)\nmean_acc <- mean(accelerated)\nobs_diff <- mean_std - mean_acc\n\ncat(\"Mean (Standard):\", round(mean_std, 2), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean (Standard): 45.75 days\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean (Accelerated):\", round(mean_acc, 2), \"days\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean (Accelerated): 37.25 days\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Observed difference:\", round(obs_diff, 2), \"days\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved difference: 8.5 days\n```\n\n\n:::\n:::\n\n\n### Part (b): Two-Sample Bootstrap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB <- 10000\nn_std <- length(standard)\nn_acc <- length(accelerated)\n\nboot_diffs <- replicate(B, {\n  boot_std <- sample(standard, n_std, replace = TRUE)\n  boot_acc <- sample(accelerated, n_acc, replace = TRUE)\n  mean(boot_std) - mean(boot_acc)\n})\n\nboot_ci_diff <- quantile(boot_diffs, probs = c(0.025, 0.975))\ncat(\"95% Bootstrap Percentile CI for difference: (\", \n    round(boot_ci_diff[1], 2), \",\", round(boot_ci_diff[2], 2), \") days\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap Percentile CI for difference: ( 3.88 , 13.12 ) days\n```\n\n\n:::\n:::\n\n\n### Part (c): Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Does CI exclude 0?\", !((boot_ci_diff[1] < 0) & (0 < boot_ci_diff[2])), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDoes CI exclude 0? TRUE \n```\n\n\n:::\n:::\n\n\n**Interpretation:** Yes, the confidence interval suggests a significant difference between protocols since the entire interval is positive (excludes 0). \n\n**Clinical interpretation:** Patients on the accelerated protocol recover approximately 8-9 days faster on average (95% CI: 3 to 14 days faster). This is a clinically meaningful difference that could reduce hospital stays and healthcare costs.\n\n---\n\n## Problem 4: Bootstrap for the Median\n\n\n::: {.cell}\n\n```{.r .cell-code}\nferritin <- c(23, 31, 18, 45, 27, 52, 34, 29, 38, 24, 88, 33)\nn <- length(ferritin)\n```\n:::\n\n\n### Part (a): Bootstrap Distribution of Medians\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB <- 10000\n\nboot_medians <- replicate(B, {\n  boot_sample <- sample(ferritin, n, replace = TRUE)\n  median(boot_sample)\n})\n\nhist(boot_medians, breaks = 30, main = \"Bootstrap Distribution of Medians\",\n     xlab = expression(tilde(x)^\"*\"), col = \"coral\", border = \"white\")\nabline(v = median(ferritin), col = \"blue\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](HW_04_Solutions_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### Part (b): Bootstrap Percentile Interval for Median\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian_ci <- quantile(boot_medians, probs = c(0.025, 0.975))\ncat(\"Sample median:\", median(ferritin), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample median: 32 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% Bootstrap Percentile CI for median: (\", \n    round(median_ci[1], 2), \",\", round(median_ci[2], 2), \") ng/mL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap Percentile CI for median: ( 25.5 , 41.5 ) ng/mL\n```\n\n\n:::\n:::\n\n\n### Part (c): Shape of Bootstrap Distribution\n\nThe bootstrap distribution of the median looks quite different from the bootstrap distribution of means:\n\n1. **Discrete appearance**: The bootstrap median can only take values that are observations (or averages of two observations) from the original sample. This creates a \"lumpy\" or discrete distribution.\n\n2. **Not smooth/normal**: Unlike the bootstrap distribution of means, which tends toward normality by CLT, the bootstrap distribution of medians is often irregular.\n\n3. **Bootstrap t not appropriate**: Because the bootstrap distribution of the median is not approximately normal, the bootstrap t interval (which assumes normality) is **not appropriate** for the median. We should use the percentile interval instead.\n\n### Part (d): Mean vs. Median\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Mean:\", round(mean(ferritin), 2), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean: 36.83 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median:\", median(ferritin), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: 32 ng/mL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:\", round(mean(ferritin) - median(ferritin), 2), \"ng/mL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: 4.83 ng/mL\n```\n\n\n:::\n:::\n\n\n**Recommendation:** Given the outlier at 88 ng/mL, I would prefer to report a CI for the **median**. \n\nReasons:\n\n- The median (31.5 ng/mL) is more representative of the \"typical\" patient than the mean (36.8 ng/mL)\n- The median is robust to the outlier; removing 88 would barely change the median but would substantially reduce the mean\n- For clinical interpretation, the median better represents what a typical patient's ferritin level might be\n\n---\n\n## Problem 5: Study Hours (Devore 8.63)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_hours <- c(15, 10, 10, 15, 25, 7, 3, 8, 10, 10, 11, 7, \n                 5, 15, 7.5, 7.5, 12, 7, 10.5, 6, 10, 7.5)\nn <- length(study_hours)\n```\n:::\n\n\n### Part (a): Classical t-Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_result <- t.test(study_hours)\ncat(\"Sample mean:\", round(mean(study_hours), 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 9.95 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sample SD:\", round(sd(study_hours), 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample SD: 4.6 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"95% t-interval: (\", round(t_result$conf.int[1], 2), \",\", \n    round(t_result$conf.int[2], 2), \") hours\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% t-interval: ( 7.91 , 12 ) hours\n```\n\n\n:::\n:::\n\n\n### Part (b): Normal Probability Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(study_hours, main = \"Normal Q-Q Plot: Study Hours\", pch = 19)\nqqline(study_hours, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](HW_04_Solutions_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot shows some departure from normality, particularly in the tails. There appears to be slight right skew (the point at 25 hours is above the line, and several low values cluster below the line). However, with $n = 22$, the t-interval may still be reasonably robust.\n\n### Part (c): Bootstrap Percentile Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(551)\nB <- 10000\n\nboot_means_study <- replicate(B, {\n  mean(sample(study_hours, n, replace = TRUE))\n})\n\nboot_ci_study <- quantile(boot_means_study, probs = c(0.025, 0.975))\ncat(\"95% Bootstrap Percentile CI: (\", round(boot_ci_study[1], 2), \",\", \n    round(boot_ci_study[2], 2), \") hours\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% Bootstrap Percentile CI: ( 8.23 , 11.93 ) hours\n```\n\n\n:::\n:::\n\n\n### Part (d): Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"t-interval:          (\", round(t_result$conf.int[1], 2), \",\", \n    round(t_result$conf.int[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-interval:          ( 7.91 , 12 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrap percentile: (\", round(boot_ci_study[1], 2), \",\", \n    round(boot_ci_study[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrap percentile: ( 8.23 , 11.93 )\n```\n\n\n:::\n:::\n\n\n**Comparison:** The two intervals are very similar, which is reassuring. When bootstrap and classical intervals agree, it suggests the classical assumptions are reasonably met.\n\n**Recommendation:** Either interval is acceptable here. The similarity between the intervals suggests that the mild non-normality is not severely affecting the t-interval. I would report the **t-interval** for simplicity, noting that bootstrap analysis confirms its validity. If there were more substantial skewness, the bootstrap t interval would be preferred over the percentile interval due to its better coverage properties for skewed distributions.\n\n---\n\n## Problem 6: Sample Size and CI Width\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_pilot <- 20\nxbar_pilot <- 47\ns_pilot <- 18\n```\n:::\n\n\n### Part (a): Required Sample Size\n\nFor a margin of error $E = 5$ minutes with 95% confidence:\n\n$$n = \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{E}\\right)^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 5  # desired margin of error\nz <- qnorm(0.975)\nsigma_est <- s_pilot\n\nn_required <- (z * sigma_est / E)^2\ncat(\"Required sample size:\", ceiling(n_required), \"patients\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRequired sample size: 50 patients\n```\n\n\n:::\n:::\n\n\nWe need at least **50 patients** to achieve a margin of error of 5 minutes.\n\n### Part (b): Margin of Error for n = 100\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_available <- 100\nmargin_100 <- z * sigma_est / sqrt(n_available)\ncat(\"Expected margin of error with n = 100:\", round(margin_100, 2), \"minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected margin of error with n = 100: 3.53 minutes\n```\n\n\n:::\n:::\n\n\nWith 100 patients, the expected margin of error is approximately **3.5 minutes**.\n\n### Part (c): CI from Pilot Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using t-interval since sigma is unknown\nt_crit <- qt(0.975, df = n_pilot - 1)\nse_pilot <- s_pilot / sqrt(n_pilot)\nmargin_pilot <- t_crit * se_pilot\n\nci_pilot <- xbar_pilot + c(-1, 1) * margin_pilot\n\ncat(\"95% CI for mean wait time: (\", round(ci_pilot[1], 2), \",\", \n    round(ci_pilot[2], 2), \") minutes\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mean wait time: ( 38.58 , 55.42 ) minutes\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hospital target: 45 minutes\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospital target: 45 minutes\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Is 45 in the CI?\", (ci_pilot[1] < 45) & (45 < ci_pilot[2]), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIs 45 in the CI? TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Lower bound of CI:\", round(ci_pilot[1], 2), \"minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLower bound of CI: 38.58 minutes\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The 95% CI is approximately (38.6, 55.4) minutes. Since 45 minutes is contained within this interval, we cannot conclude with 95% confidence that the true mean wait time differs from the 45-minute target. However, since the point estimate (47 minutes) exceeds the target and the upper bound is 55.4 minutes, there is some concern that wait times may exceed the target. A larger study would provide more precision.\n",
    "supporting": [
      "HW_04_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}