<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a14e345711173c227b21482e2eb4cc70.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Jessica Minnier">
  <meta name="dcterms.date" content="2026-03-09">
  <title>Theory of Statistical Inference – Lesson 22: Gauss-Markov Theorem and OLS Theory</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #383a42;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #383a42; } /* Normal */
    code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
    code span.an { color: #50a14f; } /* Annotation */
    code span.at { color: #a626a4; } /* Attribute */
    code span.bn { color: #986801; } /* BaseN */
    code span.bu { color: #a626a4; } /* BuiltIn */
    code span.cf { color: #a626a4; } /* ControlFlow */
    code span.ch { color: #50a14f; } /* Char */
    code span.cn { color: #986801; } /* Constant */
    code span.co { color: #a0a1a7; font-style: italic; } /* Comment */
    code span.cv { color: #e45649; font-style: italic; } /* CommentVar */
    code span.do { color: #e45649; } /* Documentation */
    code span.dt { color: #a626a4; } /* DataType */
    code span.dv { color: #986801; } /* DecVal */
    code span.er { color: #f44747; text-decoration: underline; } /* Error */
    code span.ex { color: #4078f2; font-weight: bold; } /* Extension */
    code span.fl { color: #986801; } /* Float */
    code span.fu { color: #4078f2; } /* Function */
    code span.im { color: #50a14f; } /* Import */
    code span.in { color: #c45b00; } /* Information */
    code span.kw { color: #a626a4; } /* Keyword */
    code span.op { color: #a626a4; } /* Operator */
    code span.ot { color: #27ae60; } /* Other */
    code span.pp { color: #a626a4; } /* Preprocessor */
    code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
    code span.sc { color: #0184bc; } /* SpecialChar */
    code span.ss { color: #da4453; } /* SpecialString */
    code span.st { color: #50a14f; } /* String */
    code span.va { color: #e45649; } /* Variable */
    code span.vs { color: #da4453; } /* VerbatimString */
    code span.wa { color: #da4453; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-2e74a31c1bd85ff20c819e764b562f47.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="../../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
  <script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
  <script src="../../site_libs/viz-1.8.2/viz.js"></script>
  <link href="../../site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
  <script src="../../site_libs/grViz-binding-1.0.11/grViz.js"></script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#006a4e" class="quarto-title-block center">
  <h1 class="title">Lesson 22: Gauss-Markov Theorem and OLS Theory</h1>
  <p class="subtitle">BSTA 551: Statistical Inference: Bridging Estimation Theory to Linear Regression</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jessica Minnier 
</div>
</div>
</div>

  <p class="date">2026-03-09</p>
</section>
<section>
<section id="lesson-22-gauss-markov-and-ols-theory" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Lesson 22: Gauss-Markov and OLS Theory</h1>

</section>
<section id="where-weve-been-and-where-were-going" class="slide level2">
<h2>Where We’ve Been, and Where We’re Going</h2>
<p><strong>Lessons 1–6: Point Estimation Theory</strong></p>
<ul>
<li>Bias, variance, MSE</li>
<li>MVUE: minimum variance among <strong>all</strong> unbiased estimators</li>
<li>Cramér-Rao Lower Bound, Fisher Information</li>
<li>Rao-Blackwell, Lehmann-Scheffé</li>
</ul>
<div class="fragment">
<p><strong>Lessons 7–21:</strong> Confidence intervals, hypothesis testing, bootstrap, nonparametric methods</p>
</div>
<div class="fragment">
<p><strong>Today:</strong> How does all of that theory connect to <strong>linear regression</strong>, the crux of applied statistics?</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why This Matters</strong></p>
</div>
<div class="callout-content">
<p>Your applied courses (regression, GLMs, mixed models) rely fundamentally on the optimality theory we have built. Today we make that connection explicit.</p>
</div>
</div>
</div>
</div>
</section>
<section id="todays-goals" class="slide level2 scrollable">
<h2>Today’s Goals</h2>
<ol type="1">
<li>Define the <strong>simple linear regression (SLR) model</strong> and the Gauss-Markov assumptions</li>
<li>Derive the <strong>OLS estimators</strong> from the principle of least squares</li>
<li>Prove OLS estimators are <strong>linear</strong> and <strong>unbiased</strong></li>
<li>Derive their <strong>exact variances</strong></li>
<li>State and prove the <strong>Gauss-Markov Theorem</strong>: OLS is BLUE</li>
<li>Connect BLUE → <strong>MVUE</strong> under the additional assumption of normality</li>
<li>Simulate to see the theorem in action with a <strong>medical research example</strong></li>
</ol>
</section>
<section id="textbook-references" class="slide level2">
<h2>Textbook References</h2>
<table class="caption-top">
<colgroup>
<col style="width: 36%">
<col style="width: 26%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>DBC</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SLR model and OLS derivation</td>
<td>§12.1</td>
<td>Normal equations, <span class="math inline">\(\hat\beta_0\)</span>, <span class="math inline">\(\hat\beta_1\)</span></td>
</tr>
<tr class="even">
<td>Unbiasedness, <span class="math inline">\(\text{Var}(\hat\beta_1)\)</span></td>
<td>§12.2</td>
<td>Properties under GM assumptions</td>
</tr>
<tr class="odd">
<td>Gauss-Markov Theorem (BLUE)</td>
<td>§12.2</td>
<td>Stated in DBC, proof here</td>
</tr>
<tr class="even">
<td>OLS = MLE under normality</td>
<td>§12.2</td>
<td>Connects to inference (t-tests)</td>
</tr>
<tr class="odd">
<td>Weighted least squares</td>
<td>§12.9</td>
<td>When homoscedasticity fails</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Notation</strong></p>
</div>
<div class="callout-content">
<p>DBC uses <span class="math inline">\(\beta_0, \beta_1\)</span> for the <strong>true</strong> parameters and <span class="math inline">\(\hat\beta_0, \hat\beta_1\)</span> for the <strong>OLS estimates</strong>. We will use this convention throughout.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-1-the-simple-linear-regression-model" class="title-slide slide level1 center" data-background-color="#8e44ad">
<h1>Part 1: The Simple Linear Regression Model</h1>

</section>
<section id="motivating-example-gestational-age-and-birth-weight" class="slide level2">
<h2>Motivating Example: Gestational Age and Birth Weight</h2>
<p>A neonatologist wants to predict <strong>birth weight</strong> (grams) from <strong>gestational age</strong> (weeks) in premature infants.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb1-2"><a></a>n <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb1-3"><a></a>gest_age   <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">26</span>, <span class="at">max =</span> <span class="dv">36</span>)</span>
<span id="cb1-4"><a></a>birth_wt   <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3200</span> <span class="sc">+</span> <span class="dv">170</span> <span class="sc">*</span> gest_age <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">120</span>)</span>
<span id="cb1-5"><a></a></span>
<span id="cb1-6"><a></a>preterm <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">gestational_age =</span> gest_age, <span class="at">birth_weight =</span> birth_wt)</span>
<span id="cb1-7"><a></a></span>
<span id="cb1-8"><a></a><span class="fu">ggplot</span>(preterm, <span class="fu">aes</span>(<span class="at">x =</span> gestational_age, <span class="at">y =</span> birth_weight)) <span class="sc">+</span></span>
<span id="cb1-9"><a></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#e74c3c"</span>, <span class="at">linewidth =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb1-12"><a></a>    <span class="at">title =</span> <span class="st">"Birth Weight vs. Gestational Age in Premature Infants"</span>,</span>
<span id="cb1-13"><a></a>    <span class="at">x =</span> <span class="st">"Gestational Age (weeks)"</span>,</span>
<span id="cb1-14"><a></a>    <span class="at">y =</span> <span class="st">"Birth Weight (grams)"</span></span>
<span id="cb1-15"><a></a>  ) <span class="sc">+</span></span>
<span id="cb1-16"><a></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"><p><strong>Question:</strong> What is the “best” line through these data, and in what sense is it best?</p>
</section>
<section id="the-simple-linear-regression-model" class="slide level2">
<h2>The Simple Linear Regression Model</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Model (DBC §12.1)</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i, \quad i = 1, \ldots, n\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span> = response (random variable) for the <span class="math inline">\(i\)</span>-th observation</li>
<li><span class="math inline">\(x_i\)</span> = predictor value (fixed, non-random), in a <strong>fixed-design</strong> setup</li>
<li><span class="math inline">\(\beta_0\)</span> = true intercept (unknown parameter)</li>
<li><span class="math inline">\(\beta_1\)</span> = true slope (unknown parameter)</li>
<li><span class="math inline">\(\varepsilon_i\)</span> = random error term</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Notice:</strong> The <span class="math inline">\(x_i\)</span>’s are <strong>not random</strong>; we treat them as known constants.</p>
<p>This is different from our earlier iid setup! The <span class="math inline">\(Y_i\)</span>’s are <strong>independent but not identically distributed</strong>: each has a different mean <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span>.</p>
</div>
</section>
<section id="the-gauss-markov-theorem-our-destination" class="slide level2">
<h2>The Gauss-Markov Theorem: Our Destination</h2>
<p>Before examining the assumptions, let’s state the theorem we are building toward.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gauss-Markov Theorem (preview)</strong></p>
</div>
<div class="callout-content">
<p>Under four conditions on the error terms <span class="math inline">\(\varepsilon_i\)</span>, the OLS estimators <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> are the <strong>Best Linear Unbiased Estimators</strong> (BLUE) of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>That is, among all estimators that are (1) linear functions of <span class="math inline">\(Y_1, \ldots, Y_n\)</span> and (2) unbiased, OLS has the <strong>smallest variance</strong>.</p>
<p><span class="math display">\[\text{Var}(\hat\beta_1^{\text{OLS}}) \leq \text{Var}(\tilde\beta_1) \quad \text{for every linear unbiased } \tilde\beta_1\]</span></p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Why does this matter?</strong> This is the regression analog of everything we built in Lessons 1–6: MVUE, CRLB, sufficiency. The four conditions (the <strong>Gauss-Markov assumptions</strong>) are exactly what makes OLS optimal. Understanding them tells you when OLS is trustworthy, and what to do when it is not.</p>
</div>
</section>
<section id="the-gauss-markov-assumptions" class="slide level2 scrollable">
<h2>The Gauss-Markov Assumptions</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gauss-Markov (GM) Assumptions</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Linearity:</strong> <span class="math inline">\(E[Y_i] = \beta_0 + \beta_1 x_i\)</span> (the mean follows a line)</li>
<li><strong>Independence:</strong> <span class="math inline">\(\varepsilon_1, \ldots, \varepsilon_n\)</span> are independent</li>
<li><strong>Zero mean:</strong> <span class="math inline">\(E[\varepsilon_i] = 0\)</span> for all <span class="math inline">\(i\)</span></li>
<li><strong>Homoscedasticity:</strong> <span class="math inline">\(\text{Var}(\varepsilon_i) = \sigma^2\)</span> for all <span class="math inline">\(i\)</span> (same variance; <strong>no normality required!</strong>)</li>
</ol>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Key point:</strong> The Gauss-Markov theorem does <strong>not</strong> require normality.</p>
<p>Under these four assumptions alone, OLS is BLUE.</p>
<p>Under the additional assumption <span class="math inline">\(\varepsilon_i \stackrel{iid}{\sim} N(0, \sigma^2)\)</span>, OLS is even stronger: it equals the MLE and is the MVUE, not just BLUE.</p>
</div>
</section>
<section id="checking-the-gm-assumptions-in-our-example" class="slide level2">
<h2>Checking the GM Assumptions in Our Example</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(birth_weight <span class="sc">~</span> gestational_age, <span class="at">data =</span> preterm)</span>
<span id="cb2-2"><a></a>aug <span class="ot">&lt;-</span> <span class="fu">augment</span>(fit)</span>
<span id="cb2-3"><a></a></span>
<span id="cb2-4"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb2-5"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb2-8"><a></a>    <span class="at">title =</span> <span class="st">"Residuals vs. Fitted"</span>,</span>
<span id="cb2-9"><a></a>    <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(Y)[i]),</span>
<span id="cb2-10"><a></a>    <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(epsilon)[i])</span>
<span id="cb2-11"><a></a>  )</span>
<span id="cb2-12"><a></a></span>
<span id="cb2-13"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug, <span class="fu">aes</span>(<span class="at">sample =</span> .resid)) <span class="sc">+</span></span>
<span id="cb2-14"><a></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb2-15"><a></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb2-16"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Q-Q Plot of Residuals"</span>,</span>
<span id="cb2-17"><a></a>       <span class="at">x =</span> <span class="st">"Theoretical Quantiles"</span>, <span class="at">y =</span> <span class="st">"Sample Quantiles"</span>)</span>
<span id="cb2-18"><a></a></span>
<span id="cb2-19"><a></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span></span>
<span id="cb2-20"><a></a>  <span class="fu">plot_annotation</span>(<span class="at">title =</span> <span class="st">"Regression Diagnostics: Birth Weight vs. Gestational Age"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"><div class="fragment">
<p>Residuals look scattered around zero with roughly constant spread; the GM assumptions appear reasonable here.</p>
</div>
</section></section>
<section>
<section id="part-2-the-ols-estimators-derivation" class="title-slide slide level1 center" data-background-color="#2980b9">
<h1>Part 2: The OLS Estimators: Derivation</h1>

</section>
<section id="the-principle-of-least-squares" class="slide level2">
<h2>The Principle of Least Squares</h2>
<p><strong>Question:</strong> Given data <span class="math inline">\((x_1, Y_1), \ldots, (x_n, Y_n)\)</span>, how do we choose <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span>?</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Principle of Least Squares (DBC §12.1)</strong></p>
</div>
<div class="callout-content">
<p>Choose <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> to minimize the <strong>residual sum of squares</strong>:</p>
<p><span class="math display">\[\text{RSS}(\beta_0, \beta_1) = \sum_{i=1}^n \left(Y_i - \beta_0 - \beta_1 x_i\right)^2\]</span></p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>This minimizes the total squared vertical distance from each data point to the line.</p>
<p><strong>Why squares?</strong> Calculus works cleanly; squared deviations penalize large errors more than small ones; connects to maximum likelihood under normality (see later).</p>
</div>
</section>
<section id="deriving-the-ols-estimates-normal-equations" class="slide level2">
<h2>Deriving the OLS Estimates: Normal Equations</h2>
<p>Take partial derivatives and set to zero:</p>
<p><span class="math display">\[\frac{\partial \text{RSS}}{\partial \beta_0} = -2\sum_{i=1}^n (Y_i - \beta_0 - \beta_1 x_i) = 0\]</span></p>
<p><span class="math display">\[\frac{\partial \text{RSS}}{\partial \beta_1} = -2\sum_{i=1}^n x_i(Y_i - \beta_0 - \beta_1 x_i) = 0\]</span></p>
<div class="fragment">
<p>These simplify to the <strong>normal equations</strong> (DBC §12.1):</p>
<p><span class="math display">\[n\hat\beta_0 + \hat\beta_1 \sum x_i = \sum Y_i\]</span></p>
<p><span class="math display">\[\hat\beta_0 \sum x_i + \hat\beta_1 \sum x_i^2 = \sum x_i Y_i\]</span></p>
</div>
</section>
<section id="solving-the-normal-equations" class="slide level2">
<h2>Solving the Normal Equations</h2>
<p><strong>From the first equation:</strong> <span class="math inline">\(\hat\beta_0 = \bar{Y} - \hat\beta_1 \bar{x}\)</span></p>
<p><strong>Substituting into the second and simplifying:</strong></p>
<p><span class="math display">\[\hat\beta_1 = \frac{\sum_{i=1}^n (x_i - \bar{x})(Y_i - \bar{Y})}{\sum_{i=1}^n (x_i - \bar{x})^2} = \frac{S_{xy}}{S_{xx}}\]</span></p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>OLS Estimators (DBC §12.1)</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\hat\beta_1 = \frac{S_{xy}}{S_{xx}} = \frac{\sum_{i=1}^n (x_i - \bar{x})(Y_i - \bar{Y})}{\sum_{i=1}^n (x_i - \bar{x})^2}\]</span></p>
<p><span class="math display">\[\hat\beta_0 = \bar{Y} - \hat\beta_1 \bar{x}\]</span></p>
<p>where <span class="math inline">\(S_{xx} = \sum(x_i - \bar x)^2\)</span> and <span class="math inline">\(S_{xy} = \sum(x_i - \bar x)(Y_i - \bar Y)\)</span>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="computing-ols-in-our-example" class="slide level2">
<h2>Computing OLS in Our Example</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Manual computation of OLS estimators</span></span>
<span id="cb3-2"><a></a>x <span class="ot">&lt;-</span> preterm<span class="sc">$</span>gestational_age</span>
<span id="cb3-3"><a></a>Y <span class="ot">&lt;-</span> preterm<span class="sc">$</span>birth_weight</span>
<span id="cb3-4"><a></a></span>
<span id="cb3-5"><a></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-6"><a></a>Y_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(Y)</span>
<span id="cb3-7"><a></a></span>
<span id="cb3-8"><a></a>Sxx <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-9"><a></a>Sxy <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> x_bar) <span class="sc">*</span> (Y <span class="sc">-</span> Y_bar))</span>
<span id="cb3-10"><a></a></span>
<span id="cb3-11"><a></a>beta1_hat <span class="ot">&lt;-</span> Sxy <span class="sc">/</span> Sxx</span>
<span id="cb3-12"><a></a>beta0_hat <span class="ot">&lt;-</span> Y_bar <span class="sc">-</span> beta1_hat <span class="sc">*</span> x_bar</span>
<span id="cb3-13"><a></a></span>
<span id="cb3-14"><a></a><span class="fu">cat</span>(<span class="st">"Manual OLS:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Manual OLS:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">cat</span>(<span class="st">"  beta0_hat ="</span>, <span class="fu">round</span>(beta0_hat, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  beta0_hat = -3181.73 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">cat</span>(<span class="st">"  beta1_hat ="</span>, <span class="fu">round</span>(beta1_hat, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  beta1_hat = 169.88 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="co"># Confirm with lm()</span></span>
<span id="cb9-2"><a></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(birth_weight <span class="sc">~</span> gestational_age, <span class="at">data =</span> preterm)</span>
<span id="cb9-3"><a></a><span class="fu">tidy</span>(fit) <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  term            estimate
  &lt;chr&gt;              &lt;dbl&gt;
1 (Intercept)       -3182.
2 gestational_age     170.</code></pre>
</div>
</div>
<div class="fragment">
<p><strong>Interpretation:</strong> Each additional week of gestational age is associated with approximately 169.9 grams of additional birth weight, on average.</p>
</div>
</section>
<section id="the-rss-surface-a-geometric-view" class="slide level2">
<h2>The RSS Surface: A Geometric View</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># Create a grid of (beta0, beta1) values and compute RSS at each</span></span>
<span id="cb11-2"><a></a>b0_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(beta0_hat <span class="sc">-</span> <span class="dv">800</span>, beta0_hat <span class="sc">+</span> <span class="dv">800</span>, <span class="at">length.out =</span> <span class="dv">60</span>)</span>
<span id="cb11-3"><a></a>b1_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(beta1_hat <span class="sc">-</span> <span class="dv">60</span>,  beta1_hat <span class="sc">+</span> <span class="dv">60</span>,  <span class="at">length.out =</span> <span class="dv">60</span>)</span>
<span id="cb11-4"><a></a></span>
<span id="cb11-5"><a></a>rss_grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">b0 =</span> b0_seq, <span class="at">b1 =</span> b1_seq) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-7"><a></a>    <span class="at">rss =</span> <span class="fu">map2_dbl</span>(b0, b1, \(b0, b1) <span class="fu">sum</span>((Y <span class="sc">-</span> b0 <span class="sc">-</span> b1 <span class="sc">*</span> x)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb11-8"><a></a>  )</span>
<span id="cb11-9"><a></a></span>
<span id="cb11-10"><a></a><span class="fu">ggplot</span>(rss_grid, <span class="fu">aes</span>(<span class="at">x =</span> b0, <span class="at">y =</span> b1, <span class="at">z =</span> rss)) <span class="sc">+</span></span>
<span id="cb11-11"><a></a>  <span class="fu">geom_contour_filled</span>(<span class="at">bins =</span> <span class="dv">18</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb11-12"><a></a>  <span class="fu">geom_point</span>(</span>
<span id="cb11-13"><a></a>    <span class="fu">aes</span>(<span class="at">x =</span> beta0_hat, <span class="at">y =</span> beta1_hat),</span>
<span id="cb11-14"><a></a>    <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb11-15"><a></a>    <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">shape =</span> <span class="dv">8</span>, <span class="at">stroke =</span> <span class="dv">2</span></span>
<span id="cb11-16"><a></a>  ) <span class="sc">+</span></span>
<span id="cb11-17"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb11-18"><a></a>    <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"RSS Surface: "</span> <span class="sc">*</span> <span class="fu">hat</span>(beta)[<span class="dv">0</span>] <span class="sc">*</span> <span class="st">" and "</span> <span class="sc">*</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>] <span class="sc">*</span> <span class="st">" minimize RSS"</span>),</span>
<span id="cb11-19"><a></a>    <span class="at">x =</span> <span class="fu">expression</span>(beta[<span class="dv">0</span>]),</span>
<span id="cb11-20"><a></a>    <span class="at">y =</span> <span class="fu">expression</span>(beta[<span class="dv">1</span>]),</span>
<span id="cb11-21"><a></a>    <span class="at">fill =</span> <span class="st">"RSS"</span></span>
<span id="cb11-22"><a></a>  ) <span class="sc">+</span></span>
<span id="cb11-23"><a></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"plasma"</span>) <span class="sc">+</span></span>
<span id="cb11-24"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> beta0_hat <span class="sc">+</span> <span class="dv">300</span>, <span class="at">y =</span> beta1_hat <span class="sc">+</span> <span class="dv">20</span>,</span>
<span id="cb11-25"><a></a>           <span class="at">label =</span> <span class="st">"OLS minimum"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"><p>The OLS solution is at the <strong>unique global minimum</strong> of the convex RSS surface.</p>
</section></section>
<section>
<section id="part-3-properties-of-ols-estimators" class="title-slide slide level1 center" data-background-color="#16a085">
<h1>Part 3: Properties of OLS Estimators</h1>

</section>
<section id="step-1-ols-estimators-are-linear-in-y" class="slide level2">
<h2>Step 1: OLS Estimators Are Linear in <span class="math inline">\(Y\)</span></h2>
<p><strong>Key rewrite:</strong> The slope estimator can be written as a linear combination of the <span class="math inline">\(Y_i\)</span>’s:</p>
<p><span class="math display">\[\hat\beta_1 = \frac{S_{xy}}{S_{xx}} = \frac{\sum(x_i - \bar x)(Y_i - \bar Y)}{S_{xx}} = \sum_{i=1}^n c_i Y_i\]</span></p>
<p>where <span class="math inline">\(c_i = \dfrac{x_i - \bar x}{S_{xx}}\)</span> are <strong>fixed constants</strong> (they depend only on the <span class="math inline">\(x_i\)</span>’s, not on the <span class="math inline">\(Y_i\)</span>’s).</p>
<div class="fragment">
<p>Similarly, <span class="math inline">\(\hat\beta_0 = \bar{Y} - \hat\beta_1 \bar{x} = \sum_{i=1}^n d_i Y_i\)</span> where <span class="math inline">\(d_i = \frac{1}{n} - c_i \bar x\)</span>.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Definition: Linear Estimator</strong></p>
</div>
<div class="callout-content">
<p>An estimator <span class="math inline">\(\tilde\beta\)</span> is <strong>linear</strong> if it can be written as <span class="math inline">\(\tilde\beta = \sum_{i=1}^n a_i Y_i\)</span> for some constants <span class="math inline">\(a_i\)</span> that depend only on the <span class="math inline">\(x_i\)</span>’s.</p>
<p>OLS estimators satisfy this definition; they are <strong>linear estimators</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="step-2-ols-estimators-are-unbiased" class="slide level2">
<h2>Step 2: OLS Estimators Are Unbiased</h2>
<p>Both <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> are <strong>unbiased estimators</strong> of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, respectively, under the GM assumptions.</p>
<p><strong>For <span class="math inline">\(\hat\beta_1\)</span>:</strong> Since <span class="math inline">\(\hat\beta_1 = \sum c_i Y_i\)</span> and <span class="math inline">\(E[Y_i] = \beta_0 + \beta_1 x_i\)</span>:</p>
<p><span class="math display">\[E[\hat\beta_1] = E\left[\sum c_i Y_i\right] = \sum c_i E[Y_i] = \sum c_i (\beta_0 + \beta_1 x_i)\]</span></p>
<p><span class="math display">\[= \beta_0 \underbrace{\sum c_i}_{=0} + \beta_1 \underbrace{\sum c_i x_i}_{=1} = \beta_1 \checkmark\]</span></p>
<div class="fragment">
<p>The two facts that make this work, for <span class="math inline">\(c_i = (x_i - \bar x)/S_{xx}\)</span>:</p>
<p><span class="math display">\[\sum_{i=1}^n c_i = \frac{\sum(x_i - \bar x)}{S_{xx}} = \frac{0}{S_{xx}} = 0\]</span></p>
<p>because deviations from the mean always sum to zero.</p>
<p><span class="math display">\[\sum_{i=1}^n c_i x_i = \frac{\sum(x_i - \bar x)x_i}{S_{xx}} = \frac{\sum(x_i - \bar x)(x_i - \bar x) + \bar x \sum(x_i - \bar x)}{S_{xx}} = \frac{S_{xx} + 0}{S_{xx}} = 1\]</span></p>
<p>because <span class="math inline">\(\sum(x_i - \bar x)x_i = \sum(x_i - \bar x)^2 = S_{xx}\)</span>.</p>
</div>
<div class="fragment">
<p><strong>For <span class="math inline">\(\hat\beta_0\)</span>:</strong> <span class="math inline">\(E[\hat\beta_0] = E[\bar Y] - \hat\beta_1 \bar x = (\beta_0 + \beta_1 \bar x) - \beta_1 \bar x = \beta_0 \checkmark\)</span></p>
</div>
</section>
<section id="step-3-exact-variances-of-ols-estimators" class="slide level2">
<h2>Step 3: Exact Variances of OLS Estimators</h2>
<p>Under the GM assumptions (<span class="math inline">\(\varepsilon_i\)</span> independent with <span class="math inline">\(\text{Var}(\varepsilon_i) = \sigma^2\)</span>):</p>
<p><span class="math display">\[\text{Var}(\hat\beta_1) = \text{Var}\left(\sum c_i Y_i\right) = \sum c_i^2 \text{Var}(Y_i) = \sigma^2 \sum c_i^2 = \frac{\sigma^2}{S_{xx}}\]</span></p>
<p>since <span class="math inline">\(\sum c_i^2 = \sum \dfrac{(x_i - \bar x)^2}{S_{xx}^2} = \dfrac{S_{xx}}{S_{xx}^2} = \dfrac{1}{S_{xx}}\)</span>.</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Variance Formulas (DBC §12.2)</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\text{Var}(\hat\beta_1) = \frac{\sigma^2}{S_{xx}}\]</span></p>
<p><span class="math display">\[\text{Var}(\hat\beta_0) = \sigma^2 \left(\frac{1}{n} + \frac{\bar x^2}{S_{xx}}\right)\]</span></p>
<p><span class="math display">\[\text{Cov}(\hat\beta_0, \hat\beta_1) = -\frac{\sigma^2 \bar x}{S_{xx}}\]</span></p>
</div>
</div>
</div>
</div>
</section>
<section id="intuition-what-drives-variance-of-hatbeta_1" class="slide level2">
<h2>Intuition: What Drives Variance of <span class="math inline">\(\hat\beta_1\)</span>?</h2>
<p><span class="math display">\[\text{Var}(\hat\beta_1) = \frac{\sigma^2}{S_{xx}} = \frac{\sigma^2}{\sum(x_i - \bar x)^2}\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb12-2"><a></a>n_pts <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb12-3"><a></a>sigma2 <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb12-4"><a></a>beta0_true <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3200</span>; beta1_true <span class="ot">&lt;-</span> <span class="dv">170</span></span>
<span id="cb12-5"><a></a></span>
<span id="cb12-6"><a></a><span class="co"># Low spread in x</span></span>
<span id="cb12-7"><a></a>x_low  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">30</span>, <span class="dv">32</span>, <span class="at">length.out =</span> n_pts)</span>
<span id="cb12-8"><a></a><span class="co"># High spread in x</span></span>
<span id="cb12-9"><a></a>x_high <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">26</span>, <span class="dv">36</span>, <span class="at">length.out =</span> n_pts)</span>
<span id="cb12-10"><a></a></span>
<span id="cb12-11"><a></a>Sxx_low  <span class="ot">&lt;-</span> <span class="fu">sum</span>((x_low  <span class="sc">-</span> <span class="fu">mean</span>(x_low))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-12"><a></a>Sxx_high <span class="ot">&lt;-</span> <span class="fu">sum</span>((x_high <span class="sc">-</span> <span class="fu">mean</span>(x_high))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-13"><a></a></span>
<span id="cb12-14"><a></a>simulate_slope <span class="ot">&lt;-</span> <span class="cf">function</span>(x_vals, <span class="at">n_sim =</span> <span class="dv">2000</span>) {</span>
<span id="cb12-15"><a></a>  <span class="fu">replicate</span>(n_sim, {</span>
<span id="cb12-16"><a></a>    Y <span class="ot">&lt;-</span> beta0_true <span class="sc">+</span> beta1_true <span class="sc">*</span> x_vals <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(x_vals), <span class="dv">0</span>, <span class="fu">sqrt</span>(sigma2))</span>
<span id="cb12-17"><a></a>    <span class="fu">coef</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> x_vals))[<span class="dv">2</span>]</span>
<span id="cb12-18"><a></a>  })</span>
<span id="cb12-19"><a></a>}</span>
<span id="cb12-20"><a></a></span>
<span id="cb12-21"><a></a>slopes_low  <span class="ot">&lt;-</span> <span class="fu">simulate_slope</span>(x_low)</span>
<span id="cb12-22"><a></a>slopes_high <span class="ot">&lt;-</span> <span class="fu">simulate_slope</span>(x_high)</span>
<span id="cb12-23"><a></a></span>
<span id="cb12-24"><a></a><span class="fu">tibble</span>(</span>
<span id="cb12-25"><a></a>  <span class="at">slope =</span> <span class="fu">c</span>(slopes_low, slopes_high),</span>
<span id="cb12-26"><a></a>  <span class="at">Design =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Sxx small"</span>, <span class="st">"Sxx large"</span>),</span>
<span id="cb12-27"><a></a>               <span class="at">each =</span> <span class="dv">2000</span>)</span>
<span id="cb12-28"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb12-29"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> slope, <span class="at">fill =</span> Design)) <span class="sc">+</span></span>
<span id="cb12-30"><a></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">45</span>, <span class="at">alpha =</span> <span class="fl">0.65</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb12-31"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> beta1_true, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb12-32"><a></a>             <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb12-33"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Sxx small"</span> <span class="ot">=</span> <span class="st">"tomato"</span>,</span>
<span id="cb12-34"><a></a>                               <span class="st">"Sxx large"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>)) <span class="sc">+</span></span>
<span id="cb12-35"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb12-36"><a></a>    <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Variance of "</span> <span class="sc">*</span> <span class="fu">hat</span>(beta)[<span class="dv">1</span>] <span class="sc">*</span> <span class="st">" depends on spread of x values"</span>),</span>
<span id="cb12-37"><a></a>    <span class="at">subtitle =</span> <span class="fu">bquote</span>(<span class="fu">Var</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]) <span class="sc">==</span> sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> S[xx]),</span>
<span id="cb12-38"><a></a>    <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]),</span>
<span id="cb12-39"><a></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb12-40"><a></a>    <span class="at">fill =</span> <span class="st">"Design"</span></span>
<span id="cb12-41"><a></a>  ) <span class="sc">+</span></span>
<span id="cb12-42"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> beta1_true <span class="sc">+</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="dv">250</span>, <span class="at">label =</span> <span class="fu">expression</span>(beta[<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">170</span>),</span>
<span id="cb12-43"><a></a>           <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb12-44"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><p><strong>Lesson for study design:</strong> Spread your predictor values out to get a more precise slope estimate!</p>
</section></section>
<section>
<section id="part-4-the-gauss-markov-theorem" class="title-slide slide level1 center" data-background-color="#c0392b">
<h1>Part 4: The Gauss-Markov Theorem</h1>

</section>
<section id="statement-of-the-gauss-markov-theorem" class="slide level2">
<h2>Statement of the Gauss-Markov Theorem</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gauss-Markov Theorem (DBC §12.2)</strong></p>
</div>
<div class="callout-content">
<p>Under the four Gauss-Markov assumptions (linearity, independence, zero-mean errors, homoscedasticity), the OLS estimators <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> are the <strong>Best Linear Unbiased Estimators</strong> (BLUE) of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>That is, among all estimators of the form <span class="math inline">\(\tilde\beta_1 = \sum a_i Y_i\)</span> that satisfy <span class="math inline">\(E[\tilde\beta_1] = \beta_1\)</span>:</p>
<p><span class="math display">\[\text{Var}(\hat\beta_1) \leq \text{Var}(\tilde\beta_1)\]</span></p>
<p>with equality iff <span class="math inline">\(\tilde\beta_1 = \hat\beta_1\)</span>.</p>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Unpacking “BLUE”:</strong></p>
<ul>
<li><strong>B</strong>est = smallest variance among the class considered</li>
<li><strong>L</strong>inear = estimator is a linear function of the <span class="math inline">\(Y_i\)</span>’s</li>
<li><strong>U</strong>nbiased = <span class="math inline">\(E[\tilde\beta] = \beta\)</span> for all <span class="math inline">\(\beta_0, \beta_1, \sigma^2\)</span></li>
<li><strong>E</strong>stimator = a function of the observed data</li>
</ul>
</div>
</section>
<section id="proof-gauss-markov-for-hatbeta_1" class="slide level2 smaller">
<h2>Proof: Gauss-Markov for <span class="math inline">\(\hat\beta_1\)</span></h2>
<p><strong>Setup:</strong> Let <span class="math inline">\(\tilde\beta_1 = \sum a_i Y_i\)</span> be any linear unbiased estimator of <span class="math inline">\(\beta_1\)</span>, where the <span class="math inline">\(a_i\)</span>’s are constants.</p>
<p><strong>Unbiasedness constraint:</strong></p>
<p><span class="math display">\[E[\tilde\beta_1] = \sum a_i E[Y_i] = \sum a_i(\beta_0 + \beta_1 x_i) = \beta_0 \sum a_i + \beta_1 \sum a_i x_i = \beta_1\]</span></p>
<p>This must hold for all <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, so: <span class="math inline">\(\quad \sum a_i = 0 \quad\)</span> and <span class="math inline">\(\quad \sum a_i x_i = 1\)</span>.</p>
<div class="fragment">
<p><strong>Write <span class="math inline">\(a_i = c_i + e_i\)</span></strong> where <span class="math inline">\(c_i = (x_i - \bar x)/S_{xx}\)</span> are the OLS weights and <span class="math inline">\(e_i = a_i - c_i\)</span>.</p>
<p>The constraints <span class="math inline">\(\sum a_i = 0\)</span> and <span class="math inline">\(\sum a_i x_i = 1\)</span> imply <span class="math inline">\(\sum e_i = 0\)</span> and <span class="math inline">\(\sum e_i x_i = 0\)</span>.</p>
</div>
<div class="fragment">
<p><strong>Variance of <span class="math inline">\(\tilde\beta_1\)</span>:</strong></p>
<p><span class="math display">\[\text{Var}(\tilde\beta_1) = \sigma^2 \sum a_i^2 = \sigma^2 \sum (c_i + e_i)^2 = \sigma^2\left(\sum c_i^2 + 2\sum c_i e_i + \sum e_i^2\right)\]</span></p>
<p>Since <span class="math inline">\(\sum c_i e_i = \frac{1}{S_{xx}}\sum(x_i - \bar x)e_i = \frac{1}{S_{xx}}\left(\sum x_i e_i - \bar x \sum e_i\right) = 0\)</span>, we get:</p>
<p><span class="math display">\[\text{Var}(\tilde\beta_1) = \underbrace{\frac{\sigma^2}{S_{xx}}}_{\text{Var}(\hat\beta_1)} + \underbrace{\sigma^2 \sum e_i^2}_{\geq 0} \geq \text{Var}(\hat\beta_1) \quad \checkmark\]</span></p>
</div>
</section>
<section id="the-blue-hierarchy-connecting-to-mvue" class="slide level2">
<h2>The BLUE Hierarchy: Connecting to MVUE</h2>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-82f080207f5d5dadffcf" style="width:960px;height:576px;"></div>
<script type="application/json" data-for="htmlwidget-82f080207f5d5dadffcf">{"x":{"diagram":"\ndigraph BLUE_MVUE {\n  graph [rankdir = TB, bgcolor = transparent, splines = ortho]\n  node [shape = box, style = filled, fontsize = 14, width = 3.5]\n\n  All   [label = \"All Unbiased Estimators\\n(includes nonlinear functions of Y)\", \n          fillcolor = \"#F5B7B1\"]\n  Lin   [label = \"Linear Unbiased Estimators\\n(tildeβ = Σ aᵢYᵢ, E[tildeβ] = β)\", \n          fillcolor = \"#FAD7A0\"]\n  OLS   [label = \"OLS: Best Linear Unbiased (BLUE)\\nGauss-Markov: smallest Var among linear UEs\", \n          fillcolor = \"#ABEBC6\"]\n  MVUE  [label = \"MVUE (under normality)\\nOLS = MLE = BLUE = MVUE\", \n          fillcolor = \"#AED6F1\"]\n\n  All  -> Lin  [label = \"restrict to\\nlinear estimators\"]\n  Lin  -> OLS  [label = \"Gauss-Markov\\nTheorem\"]\n  OLS  -> MVUE [label = \"Add normality:\\nε ~ N(0,σ²)\", style = dashed]\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="fragment">
<ul>
<li><strong>Gauss-Markov (no normality needed):</strong> OLS is BLUE — smallest variance among all linear unbiased estimators</li>
<li><strong>Add normality:</strong> two independent arguments both conclude OLS is MVUE — see next slide</li>
</ul>
</div>
</section>
<section id="from-blue-to-mvue-two-routes-under-normality" class="slide level2">
<h2>From BLUE to MVUE: Two Routes Under Normality</h2>
<p>Adding <span class="math inline">\(\varepsilon_i \stackrel{iid}{\sim} N(0,\sigma^2)\)</span> unlocks two separate arguments, each concluding OLS is the MVUE.</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Route 1: Lehmann-Scheffé</strong></p>
</div>
<div class="callout-content">
<p>Under the normal SLR model, <span class="math inline">\((\hat\beta_0, \hat\beta_1, S^2)\)</span> is a <strong>complete sufficient statistic</strong> for <span class="math inline">\((\beta_0, \beta_1, \sigma^2)\)</span>.</p>
<p><span class="math inline">\(\hat\beta_1\)</span> is an <strong>unbiased function</strong> of that complete sufficient statistic.</p>
<p>Therefore, by the Lehmann-Scheffé theorem, <span class="math inline">\(\hat\beta_1\)</span> is the <strong>unique MVUE</strong> of <span class="math inline">\(\beta_1\)</span>.</p>
<p>The CRLB plays no role in this argument — it follows from completeness and sufficiency alone.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Route 2: CRLB / Efficiency</strong></p>
</div>
<div class="callout-content">
<p>The normal SLR model belongs to the <strong>exponential family</strong>. For exponential family models, the MLE achieves the Cramér-Rao Lower Bound <strong>exactly</strong> (not just asymptotically).</p>
<p>Since OLS = MLE under normality (shown in Part 5), and <span class="math inline">\(\text{Var}(\hat\beta_1) = \sigma^2/S_{xx}\)</span> equals the CRLB:</p>
<p><span class="math display">\[\text{Var}(\hat\beta_1) = \frac{\sigma^2}{S_{xx}} = \text{CRLB for } \beta_1\]</span></p>
<p>An unbiased estimator that achieves the CRLB is, by definition, the MVUE.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>These are parallel routes to the same destination. Lehmann-Scheffé works via the structure of the sufficient statistic; the CRLB route works via the information bound. Both require normality.</p>
</div>
</section>
<section id="what-blue-does-not-say" class="slide level2">
<h2>What BLUE Does Not Say</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Common Misconceptions</strong></p>
</div>
<div class="callout-content">
<p><strong>BLUE does not mean:</strong></p>
<ul>
<li>OLS has the smallest variance among <strong>all</strong> estimators (biased or not): weighted least squares (WLS) or ridge regression can have smaller MSE</li>
<li>OLS is optimal when GM assumptions are <strong>violated</strong>: heteroscedasticity calls for WLS; dependence calls for generalized least squares (GLS)</li>
<li>The model is <strong>correct</strong>: OLS is BLUE for the stated model, regardless of whether the model fits the data well</li>
</ul>
<p><strong>BLUE does mean:</strong></p>
<ul>
<li>Within the class of <strong>linear, unbiased</strong> estimators, OLS cannot be beaten</li>
<li>This is a remarkable, assumption-lean result: no distributional assumption on <span class="math inline">\(\varepsilon_i\)</span> beyond mean 0 and constant variance</li>
</ul>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-5-ols-mle-under-normality" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Part 5: OLS = MLE Under Normality</h1>

</section>
<section id="the-normal-simple-linear-regression-model" class="slide level2">
<h2>The Normal Simple Linear Regression Model</h2>
<p>Add one assumption to the GM setup:</p>
<p><span class="math display">\[\varepsilon_i \stackrel{iid}{\sim} N(0, \sigma^2)\]</span></p>
<p>This implies: <span class="math display">\[Y_i \stackrel{\text{indep}}{\sim} N(\beta_0 + \beta_1 x_i, \; \sigma^2)\]</span></p>
<div class="fragment">
<p>The joint likelihood is:</p>
<p><span class="math display">\[L(\beta_0, \beta_1, \sigma^2) = \prod_{i=1}^n \frac{1}{\sqrt{2\pi\sigma^2}} \exp\!\left\{-\frac{(Y_i - \beta_0 - \beta_1 x_i)^2}{2\sigma^2}\right\}\]</span></p>
<p><span class="math display">\[= \left(\frac{1}{2\pi\sigma^2}\right)^{n/2} \exp\!\left\{-\frac{1}{2\sigma^2}\sum_{i=1}^n (Y_i - \beta_0 - \beta_1 x_i)^2\right\}\]</span></p>
</div>
</section>
<section id="maximizing-the-likelihood" class="slide level2">
<h2>Maximizing the Likelihood</h2>
<p>The log-likelihood is:</p>
<p><span class="math display">\[\ell(\beta_0, \beta_1, \sigma^2) = -\frac{n}{2}\log(2\pi\sigma^2) - \frac{1}{2\sigma^2}\sum_{i=1}^n (Y_i - \beta_0 - \beta_1 x_i)^2\]</span></p>
<div class="fragment">
<p><strong>Key observation:</strong> For fixed <span class="math inline">\(\sigma^2\)</span>, maximizing <span class="math inline">\(\ell\)</span> with respect to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> is <strong>equivalent to minimizing</strong>:</p>
<p><span class="math display">\[\sum_{i=1}^n (Y_i - \beta_0 - \beta_1 x_i)^2 = \text{RSS}\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>OLS = MLE Under Normality</strong></p>
</div>
<div class="callout-content">
<p>The OLS estimators <span class="math inline">\(\hat\beta_0^{\text{OLS}}\)</span> and <span class="math inline">\(\hat\beta_1^{\text{OLS}}\)</span> are <strong>identical</strong> to the MLE estimators <span class="math inline">\(\hat\beta_0^{\text{MLE}}\)</span> and <span class="math inline">\(\hat\beta_1^{\text{MLE}}\)</span>.</p>
</div>
</div>
</div>
<p>This is why we can use <span class="math inline">\(t\)</span>-tests and <span class="math inline">\(F\)</span>-tests in normal linear regression; the distributional framework that enables inference comes from normality + OLS = MLE.</p>
</div>
</section>
<section id="from-blue-to-mvue-the-full-chain" class="slide level2 smaller">
<h2>From BLUE to MVUE: The Full Chain</h2>
<p>Under the normal SLR model (<span class="math inline">\(\varepsilon_i \stackrel{iid}{\sim} N(0,\sigma^2)\)</span>):</p>
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_1\)</span> is linear</td>
<td>By construction: <span class="math inline">\(\hat\beta_1 = \sum c_i Y_i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat\beta_1\)</span> is unbiased</td>
<td>Shown above (only needs GM assumptions)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_1\)</span> is BLUE</td>
<td>Gauss-Markov Theorem (only needs GM assumptions)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat\beta_1\)</span> is sufficient</td>
<td><span class="math inline">\((\hat\beta_0, \hat\beta_1, S^2)\)</span> is sufficient for <span class="math inline">\((\beta_0, \beta_1, \sigma^2)\)</span> under normality</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_1\)</span> is the MLE</td>
<td>OLS = MLE under normality (shown above)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat\beta_1\)</span> is the MVUE</td>
<td>Lehmann-Scheffé: complete sufficient statistic + unbiased</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_1\)</span> achieves CRLB</td>
<td>MLE achieves CRLB asymptotically; exactly for exponential family</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Big Picture</strong></p>
</div>
<div class="callout-content">
<p>This is precisely the situation we studied with scalar parameters: the MLE of an exponential family parameter based on the sufficient statistic is unbiased, complete, and achieves the CRLB. The normal SLR model is an exponential family model, and OLS produces the sufficient statistics.</p>
</div>
</div>
</div>
</div>
</section>
<section id="connecting-to-the-crlb" class="slide level2">
<h2>Connecting to the CRLB</h2>
<p>Under normal SLR, the Fisher information matrix for <span class="math inline">\((\beta_0, \beta_1)\)</span> gives:</p>
<p><span class="math display">\[\text{CRLB for } \beta_1 = \frac{\sigma^2}{S_{xx}} = \text{Var}(\hat\beta_1^{\text{OLS}})\]</span></p>
<p><span class="math display">\[\text{CRLB for } \beta_0 = \sigma^2\!\left(\frac{1}{n} + \frac{\bar x^2}{S_{xx}}\right) = \text{Var}(\hat\beta_0^{\text{OLS}})\]</span></p>
<div class="fragment">
<p>OLS estimators <strong>achieve the Cramér-Rao Lower Bound</strong>; they are <strong>efficient</strong> unbiased estimators.</p>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># Verify: compare theoretical variance to simulation variance</span></span>
<span id="cb13-2"><a></a>sigma <span class="ot">&lt;-</span> <span class="dv">120</span></span>
<span id="cb13-3"><a></a>Sxx_val <span class="ot">&lt;-</span> Sxx</span>
<span id="cb13-4"><a></a></span>
<span id="cb13-5"><a></a><span class="fu">cat</span>(<span class="st">"Theoretical Var(beta1_hat) ="</span>, <span class="fu">round</span>(sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> Sxx_val, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Theoretical Var(beta1_hat) = 25.1581 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">cat</span>(<span class="st">"Simulated  Var(beta1_hat) ="</span>, <span class="fu">round</span>(<span class="fu">var</span>(slopes_high), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simulated  Var(beta1_hat) = 36.8917 </code></pre>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-6-r-simulation-verifying-gauss-markov" class="title-slide slide level1 center" data-background-color="#27ae60">
<h1>Part 6: R Simulation: Verifying Gauss-Markov</h1>

</section>
<section id="comparing-ols-to-alternative-linear-estimators" class="slide level2 scrollable">
<h2>Comparing OLS to Alternative Linear Estimators</h2>
<p>The GM theorem says OLS beats every other linear unbiased estimator. Let’s verify with a simulation.</p>
<p><strong>Setting:</strong> Same premature infant model: <span class="math inline">\(Y_i = -3200 + 170 x_i + \varepsilon_i\)</span>, <span class="math inline">\(\varepsilon_i \sim N(0, 120^2)\)</span></p>
<p><strong>Competitors:</strong></p>
<ol type="1">
<li><strong>OLS:</strong> <span class="math inline">\(\hat\beta_1 = S_{xy}/S_{xx}\)</span> (the Gauss-Markov champion)</li>
<li><strong>Naïve two-point slope:</strong> Use only the first and last observation: <span class="math inline">\(\tilde\beta_1^{(2)} = (Y_n - Y_1)/(x_n - x_1)\)</span></li>
<li><strong>Trimmed OLS:</strong> Drop middle third of observations, apply OLS to rest</li>
<li><strong>Unweighted mean of slopes:</strong> Average of all pairwise slopes (all pairs <span class="math inline">\(i &lt; j\)</span>)</li>
</ol>
<p>All four are linear in <span class="math inline">\(Y\)</span> and unbiased, but only OLS is BLUE.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">set.seed</span>(<span class="dv">551</span>)</span>
<span id="cb17-2"><a></a>n_sim <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb17-3"><a></a>x_fixed <span class="ot">&lt;-</span> <span class="fu">sort</span>(preterm<span class="sc">$</span>gestational_age)</span>
<span id="cb17-4"><a></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x_fixed)</span>
<span id="cb17-5"><a></a>beta0_true <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3200</span>; beta1_true <span class="ot">&lt;-</span> <span class="dv">170</span>; sigma <span class="ot">&lt;-</span> <span class="dv">120</span></span>
<span id="cb17-6"><a></a></span>
<span id="cb17-7"><a></a>simulate_estimators <span class="ot">&lt;-</span> <span class="cf">function</span>(x_vals, n_sim, beta0, beta1, sigma) {</span>
<span id="cb17-8"><a></a>  <span class="fu">replicate</span>(n_sim, {</span>
<span id="cb17-9"><a></a>    Y <span class="ot">&lt;-</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x_vals <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(x_vals), <span class="dv">0</span>, sigma)</span>
<span id="cb17-10"><a></a>    n  <span class="ot">&lt;-</span> <span class="fu">length</span>(x_vals)</span>
<span id="cb17-11"><a></a>    </span>
<span id="cb17-12"><a></a>    <span class="co"># OLS slope</span></span>
<span id="cb17-13"><a></a>    ols <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> x_vals))[<span class="dv">2</span>]</span>
<span id="cb17-14"><a></a>    </span>
<span id="cb17-15"><a></a>    <span class="co"># Two-point slope: first and last observation</span></span>
<span id="cb17-16"><a></a>    two_pt <span class="ot">&lt;-</span> (Y[n] <span class="sc">-</span> Y[<span class="dv">1</span>]) <span class="sc">/</span> (x_vals[n] <span class="sc">-</span> x_vals[<span class="dv">1</span>])</span>
<span id="cb17-17"><a></a>    </span>
<span id="cb17-18"><a></a>    <span class="co"># Trimmed OLS: drop middle third</span></span>
<span id="cb17-19"><a></a>    keep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">floor</span>(n<span class="sc">/</span><span class="dv">3</span>), <span class="fu">ceiling</span>(<span class="dv">2</span><span class="sc">*</span>n<span class="sc">/</span><span class="dv">3</span>)<span class="sc">:</span>n)</span>
<span id="cb17-20"><a></a>    trimmed <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y[keep] <span class="sc">~</span> x_vals[keep]))[<span class="dv">2</span>]</span>
<span id="cb17-21"><a></a>    </span>
<span id="cb17-22"><a></a>    <span class="co"># Mean of all pairwise slopes</span></span>
<span id="cb17-23"><a></a>    pairs_i <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>(n<span class="dv">-1</span>), <span class="at">times =</span> (n<span class="dv">-1</span>)<span class="sc">:</span><span class="dv">1</span>)</span>
<span id="cb17-24"><a></a>    pairs_j <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">lapply</span>(<span class="dv">2</span><span class="sc">:</span>n, \(j) j<span class="sc">:</span>n))</span>
<span id="cb17-25"><a></a>    pairwise_slopes <span class="ot">&lt;-</span> (Y[pairs_j] <span class="sc">-</span> Y[pairs_i]) <span class="sc">/</span> (x_vals[pairs_j] <span class="sc">-</span> x_vals[pairs_i])</span>
<span id="cb17-26"><a></a>    pairwise_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(pairwise_slopes)</span>
<span id="cb17-27"><a></a>    </span>
<span id="cb17-28"><a></a>    <span class="fu">c</span>(<span class="at">ols =</span> <span class="fu">as.numeric</span>(ols), <span class="at">two_pt =</span> two_pt, <span class="at">trimmed =</span> <span class="fu">as.numeric</span>(trimmed), <span class="at">pairwise =</span> pairwise_mean)</span>
<span id="cb17-29"><a></a>  }) <span class="sc">|&gt;</span> <span class="fu">t</span>() <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb17-30"><a></a>}</span>
<span id="cb17-31"><a></a></span>
<span id="cb17-32"><a></a>sim_results <span class="ot">&lt;-</span> <span class="fu">simulate_estimators</span>(x_fixed, n_sim, beta0_true, beta1_true, sigma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="simulation-results-ols-wins" class="slide level2">
<h2>Simulation Results: OLS Wins</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>sim_results <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(),</span>
<span id="cb18-3"><a></a>               <span class="at">names_to =</span> <span class="st">"Estimator"</span>,</span>
<span id="cb18-4"><a></a>               <span class="at">values_to =</span> <span class="st">"slope_hat"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a></a>  <span class="fu">mutate</span>(<span class="at">Estimator =</span> <span class="fu">recode</span>(Estimator,</span>
<span id="cb18-6"><a></a>    <span class="at">ols       =</span> <span class="st">"OLS (BLUE)"</span>,</span>
<span id="cb18-7"><a></a>    <span class="at">two_pt    =</span> <span class="st">"Naive Two-point"</span>,</span>
<span id="cb18-8"><a></a>    <span class="at">trimmed   =</span> <span class="st">"Trimmed OLS"</span>,</span>
<span id="cb18-9"><a></a>    <span class="at">pairwise  =</span> <span class="st">"Mean pairwise slopes"</span></span>
<span id="cb18-10"><a></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb18-11"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> slope_hat, <span class="at">fill =</span> Estimator)) <span class="sc">+</span></span>
<span id="cb18-12"><a></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.55</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> beta1_true, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb18-14"><a></a>             <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#e74c3c"</span>, <span class="st">"#3498db"</span>, <span class="st">"#2ecc71"</span>, <span class="st">"#f39c12"</span>)) <span class="sc">+</span></span>
<span id="cb18-16"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Estimator, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb18-17"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb18-18"><a></a>    <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Sampling Distributions of Four Linear Unbiased Estimators of "</span> <span class="sc">*</span> beta[<span class="dv">1</span>]),</span>
<span id="cb18-19"><a></a>    <span class="at">subtitle =</span> <span class="fu">bquote</span>(<span class="st">"True "</span> <span class="sc">*</span> beta[<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">170</span> <span class="sc">*</span> <span class="st">" (dashed line); OLS has smallest variance"</span>),</span>
<span id="cb18-20"><a></a>    <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>]),</span>
<span id="cb18-21"><a></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb18-22"><a></a>  ) <span class="sc">+</span></span>
<span id="cb18-23"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="summarizing-the-simulation" class="slide level2">
<h2>Summarizing the Simulation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>sim_summary <span class="ot">&lt;-</span> sim_results <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="fu">list</span>(<span class="at">Mean =</span> mean, <span class="at">Variance =</span> var, <span class="at">SD =</span> sd))) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a></a>  <span class="fu">separate</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Estimator"</span>, <span class="st">"Statistic"</span>), <span class="at">sep =</span> <span class="st">"_(?=[^_]+$)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a></a>  <span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">round</span>(value, <span class="dv">4</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-6"><a></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Statistic, <span class="at">values_from =</span> value) <span class="sc">|&gt;</span></span>
<span id="cb19-7"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-8"><a></a>    <span class="at">Estimator =</span> <span class="fu">recode</span>(Estimator,</span>
<span id="cb19-9"><a></a>      <span class="at">ols      =</span> <span class="st">"OLS (BLUE)"</span>,</span>
<span id="cb19-10"><a></a>      <span class="at">two_pt   =</span> <span class="st">"Two-point"</span>,</span>
<span id="cb19-11"><a></a>      <span class="at">trimmed  =</span> <span class="st">"Trimmed OLS"</span>,</span>
<span id="cb19-12"><a></a>      <span class="at">pairwise =</span> <span class="st">"Mean pairwise"</span></span>
<span id="cb19-13"><a></a>    ),</span>
<span id="cb19-14"><a></a>    <span class="st">`</span><span class="at">Relative Efficiency</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">min</span>(Variance) <span class="sc">/</span> Variance, <span class="dv">3</span>)</span>
<span id="cb19-15"><a></a>  )</span>
<span id="cb19-16"><a></a></span>
<span id="cb19-17"><a></a>sim_summary <span class="sc">|&gt;</span></span>
<span id="cb19-18"><a></a>  <span class="fu">arrange</span>(Variance) <span class="sc">|&gt;</span></span>
<span id="cb19-19"><a></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb19-20"><a></a>               <span class="at">caption =</span> <span class="st">"Comparison of Linear Unbiased Estimators (5,000 simulations)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top">
<caption>Comparison of Linear Unbiased Estimators (5,000 simulations)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Estimator</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Variance</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Relative Efficiency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OLS (BLUE)</td>
<td style="text-align: right;">169.9583</td>
<td style="text-align: right;">25.4524</td>
<td style="text-align: right;">5.0450</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trimmed OLS</td>
<td style="text-align: right;">169.9690</td>
<td style="text-align: right;">27.3717</td>
<td style="text-align: right;">5.2318</td>
<td style="text-align: right;">0.930</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Two-point</td>
<td style="text-align: right;">169.8514</td>
<td style="text-align: right;">312.1433</td>
<td style="text-align: right;">17.6676</td>
<td style="text-align: right;">0.082</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean pairwise</td>
<td style="text-align: right;">169.8039</td>
<td style="text-align: right;">1062.4175</td>
<td style="text-align: right;">32.5947</td>
<td style="text-align: right;">0.024</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p><strong>Interpretation of relative efficiency:</strong> The ratio of OLS variance to each competitor’s variance; OLS (efficiency = 1.0) is the benchmark.</p>
</div>
</section></section>
<section>
<section id="part-7-estimation-of-sigma2-and-inference" class="title-slide slide level1 center" data-background-color="#8e44ad">
<h1>Part 7: Estimation of <span class="math inline">\(\sigma^2\)</span> and Inference</h1>

</section>
<section id="estimating-the-error-variance-sigma2" class="slide level2">
<h2>Estimating the Error Variance <span class="math inline">\(\sigma^2\)</span></h2>
<p>The GM assumptions include an unknown error variance <span class="math inline">\(\sigma^2\)</span>. We need to estimate it for inference.</p>
<p><strong>Residuals:</strong> <span class="math inline">\(\hat\varepsilon_i = Y_i - \hat\beta_0 - \hat\beta_1 x_i = Y_i - \hat{Y}_i\)</span></p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Unbiased Estimator of <span class="math inline">\(\sigma^2\)</span> (DBC §12.2)</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\hat\sigma^2 = S^2 = \frac{\text{RSS}}{n-2} = \frac{\sum_{i=1}^n (Y_i - \hat\beta_0 - \hat\beta_1 x_i)^2}{n-2}\]</span></p>
<p><span class="math inline">\(E[S^2] = \sigma^2\)</span>. Why <span class="math inline">\(n - 2\)</span>? We lose 2 degrees of freedom because we estimate 2 parameters.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>Under normality: <span class="math inline">\(\dfrac{(n-2)S^2}{\sigma^2} \sim \chi^2_{n-2}\)</span>, independent of <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span>.</p>
<p>This is the direct analog of how <span class="math inline">\(S^2\)</span> worked in one-sample inference: the distribution changes because the number of estimated parameters changes.</p>
</div>
</section>
<section id="standard-errors-and-t-based-inference" class="slide level2">
<h2>Standard Errors and t-Based Inference</h2>
<p>Replacing <span class="math inline">\(\sigma^2\)</span> with <span class="math inline">\(S^2\)</span> gives estimated standard errors:</p>
<p><span class="math display">\[\widehat{\text{SE}}(\hat\beta_1) = \frac{S}{\sqrt{S_{xx}}} \qquad \widehat{\text{SE}}(\hat\beta_0) = S\sqrt{\frac{1}{n} + \frac{\bar x^2}{S_{xx}}}\]</span></p>
<div class="fragment">
<p>Under normality, the pivot statistics follow <span class="math inline">\(t\)</span> distributions:</p>
<p><span class="math display">\[T_1 = \frac{\hat\beta_1 - \beta_1}{S/\sqrt{S_{xx}}} \sim t_{n-2} \qquad T_0 = \frac{\hat\beta_0 - \beta_0}{S\sqrt{1/n + \bar x^2/S_{xx}}} \sim t_{n-2}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># Standard errors in our example</span></span>
<span id="cb20-2"><a></a>fit_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit)</span>
<span id="cb20-3"><a></a><span class="fu">cat</span>(<span class="st">"sigma_hat (S) ="</span>, <span class="fu">round</span>(fit_summary<span class="sc">$</span>sigma, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma_hat (S) = 136.42 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">tidy</span>(fit) <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, statistic, p.value) <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a></a>  <span class="fu">mutate</span>(<span class="at">p.value =</span> scales<span class="sc">::</span><span class="fu">pvalue_format</span>(<span class="fl">0.0001</span>)(p.value), <span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">round</span>(x, <span class="dv">4</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term            estimate std.error statistic p.value
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
1 (Intercept)       -3182.    177.       -17.9 &lt;0.0001
2 gestational_age     170.      5.70      29.8 &lt;0.0001</code></pre>
</div>
</div>
</div>
</section>
<section id="prediction-and-the-fitted-line" class="slide level2">
<h2>Prediction and the Fitted Line</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>new_ages <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">gestational_age =</span> <span class="fu">seq</span>(<span class="dv">26</span>, <span class="dv">36</span>, <span class="at">by =</span> <span class="fl">0.5</span>))</span>
<span id="cb24-2"><a></a>pred_ci   <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> new_ages, <span class="at">interval =</span> <span class="st">"confidence"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb24-3"><a></a>pred_pi   <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> new_ages, <span class="at">interval =</span> <span class="st">"prediction"</span>) <span class="sc">|&gt;</span> <span class="fu">as_tibble</span>()</span>
<span id="cb24-4"><a></a></span>
<span id="cb24-5"><a></a>plot_data <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(new_ages, pred_ci) <span class="sc">|&gt;</span></span>
<span id="cb24-6"><a></a>  <span class="fu">rename</span>(<span class="at">conf_lwr =</span> lwr, <span class="at">conf_upr =</span> upr) <span class="sc">|&gt;</span></span>
<span id="cb24-7"><a></a>  <span class="fu">mutate</span>(<span class="at">pred_lwr =</span> pred_pi<span class="sc">$</span>lwr, <span class="at">pred_upr =</span> pred_pi<span class="sc">$</span>upr)</span>
<span id="cb24-8"><a></a></span>
<span id="cb24-9"><a></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb24-10"><a></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_data,</span>
<span id="cb24-11"><a></a>              <span class="fu">aes</span>(<span class="at">x =</span> gestational_age, <span class="at">ymin =</span> pred_lwr, <span class="at">ymax =</span> pred_upr, <span class="at">fill =</span> <span class="st">"95% PI"</span>),</span>
<span id="cb24-12"><a></a>              <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb24-13"><a></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_data,</span>
<span id="cb24-14"><a></a>              <span class="fu">aes</span>(<span class="at">x =</span> gestational_age, <span class="at">ymin =</span> conf_lwr, <span class="at">ymax =</span> conf_upr, <span class="at">fill =</span> <span class="st">"95% CI for mean"</span>),</span>
<span id="cb24-15"><a></a>              <span class="at">alpha =</span> <span class="fl">0.35</span>) <span class="sc">+</span></span>
<span id="cb24-16"><a></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> plot_data, <span class="fu">aes</span>(<span class="at">x =</span> gestational_age, <span class="at">y =</span> fit), <span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">linewidth =</span> <span class="fl">1.3</span>) <span class="sc">+</span></span>
<span id="cb24-17"><a></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> preterm, <span class="fu">aes</span>(<span class="at">x =</span> gestational_age, <span class="at">y =</span> birth_weight),</span>
<span id="cb24-18"><a></a>             <span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">alpha =</span> <span class="fl">0.65</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb24-19"><a></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"95% CI for mean"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>, <span class="st">"95% PI"</span> <span class="ot">=</span> <span class="st">"orange"</span>),</span>
<span id="cb24-20"><a></a>                    <span class="at">name =</span> <span class="st">"Interval"</span>) <span class="sc">+</span></span>
<span id="cb24-21"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb24-22"><a></a>    <span class="at">title =</span> <span class="st">"Birth Weight vs. Gestational Age: Fitted Line with Uncertainty Bands"</span>,</span>
<span id="cb24-23"><a></a>    <span class="at">subtitle =</span> <span class="fu">expression</span>(<span class="st">"CI for "</span> <span class="sc">*</span> E<span class="sc">*</span><span class="st">"[Y | x], PI for an individual future Y"</span>),</span>
<span id="cb24-24"><a></a>    <span class="at">x =</span> <span class="st">"Gestational Age (weeks)"</span>, <span class="at">y =</span> <span class="st">"Birth Weight (grams)"</span></span>
<span id="cb24-25"><a></a>  ) <span class="sc">+</span></span>
<span id="cb24-26"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section></section>
<section>
<section id="part-8-when-gauss-markov-fails" class="title-slide slide level1 center" data-background-color="#e67e22">
<h1>Part 8: When Gauss-Markov Fails</h1>

</section>
<section id="violation-heteroscedasticity" class="slide level2">
<h2>Violation: Heteroscedasticity</h2>
<p>If <span class="math inline">\(\text{Var}(\varepsilon_i) = \sigma_i^2\)</span> (not constant), OLS is still <strong>unbiased</strong> but is no longer BLUE.</p>
<p><strong>Example:</strong> In a study of drug dosage and response, variance in response may increase with dose.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb25-2"><a></a>x_dose <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">80</span>)</span>
<span id="cb25-3"><a></a>y_response <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> x_dose <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">80</span>, <span class="dv">0</span>, <span class="at">sd =</span> <span class="fl">0.4</span> <span class="sc">*</span> x_dose)</span>
<span id="cb25-4"><a></a>hetero_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">dose =</span> x_dose, <span class="at">response =</span> y_response)</span>
<span id="cb25-5"><a></a></span>
<span id="cb25-6"><a></a><span class="fu">ggplot</span>(hetero_data, <span class="fu">aes</span>(<span class="at">x =</span> dose, <span class="at">y =</span> response)) <span class="sc">+</span></span>
<span id="cb25-7"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#e74c3c"</span>) <span class="sc">+</span></span>
<span id="cb25-9"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb25-10"><a></a>    <span class="at">title =</span> <span class="fu">expression</span>(<span class="st">"Heteroscedasticity: "</span> <span class="sc">*</span> <span class="fu">Var</span>(epsilon[i]) <span class="sc">*</span> <span class="st">" grows with dose"</span>),</span>
<span id="cb25-11"><a></a>    <span class="at">x =</span> <span class="st">"Drug Dose (mg/kg)"</span>, <span class="at">y =</span> <span class="st">"Biomarker Response"</span></span>
<span id="cb25-12"><a></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"><div class="fragment">
<p><strong>Fix: Weighted Least Squares (WLS)</strong> minimizes <span class="math inline">\(\sum w_i (Y_i - \beta_0 - \beta_1 x_i)^2\)</span> where <span class="math inline">\(w_i \propto 1/\sigma_i^2\)</span>, down-weighting observations with higher variance.</p>
<p>Weighted least squares is BLUE when weights are correctly specified. This is DBC §12.9.</p>
</div>
</section>
<section id="summary-the-hierarchy-of-ols-optimality" class="slide level2">
<h2>Summary: The Hierarchy of OLS Optimality</h2>
<table class="caption-top">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption Set</th>
<th>OLS Property</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GM 1–4 (linearity, independence, <span class="math inline">\(E[\varepsilon_i]=0\)</span>, homoscedasticity)</td>
<td><strong>BLUE</strong>: best among linear unbiased estimators</td>
</tr>
<tr class="even">
<td>GM 1–4 + normality (<span class="math inline">\(\varepsilon_i \sim N(0,\sigma^2)\)</span>)</td>
<td><strong>MVUE</strong>: best among <strong>all</strong> unbiased estimators</td>
</tr>
<tr class="odd">
<td>GM 1–4 + normality</td>
<td><strong>MLE</strong>: OLS and MLE coincide</td>
</tr>
<tr class="even">
<td>GM 1–4 + normality</td>
<td><strong>Achieves CRLB</strong>: efficient</td>
</tr>
<tr class="odd">
<td>Homoscedasticity violated</td>
<td>OLS unbiased, but not BLUE; use weighted least squares (WLS)</td>
</tr>
<tr class="even">
<td>Independence violated</td>
<td>OLS unbiased, but not BLUE; use generalized least squares (GLS)</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Takeaway for Applied Regression</strong></p>
</div>
<div class="callout-content">
<p>When you check regression diagnostics (residual plots, Q-Q plots, leverage), you are <strong>verifying the GM assumptions</strong> that justify the optimality of OLS. If they fail, you need a different estimator.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-9-extended-example-from-dbc" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Part 9: Extended Example from DBC</h1>

</section>
<section id="dbc-example-12.7-tensile-strength-and-percentage-cotton" class="slide level2">
<h2>DBC Example 12.7: Tensile Strength and Percentage Cotton</h2>
<p>From DBC §12.1–12.2: Tensile strength (psi) of synthetic fiber as a function of percentage of cotton in the fiber.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="co"># DBC Table 12.1: cotton content and tensile strength</span></span>
<span id="cb26-2"><a></a>cotton <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb26-3"><a></a>  <span class="at">pct_cotton   =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">15</span>, <span class="dv">15</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">25</span>,</span>
<span id="cb26-4"><a></a>                   <span class="dv">25</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">35</span>, <span class="dv">35</span>, <span class="dv">35</span>, <span class="dv">35</span>),</span>
<span id="cb26-5"><a></a>  <span class="at">tensile_str  =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">15</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">17</span>, <span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">14</span>, <span class="dv">18</span>,</span>
<span id="cb26-6"><a></a>                   <span class="dv">18</span>, <span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">25</span>, <span class="dv">22</span>, <span class="dv">19</span>, <span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">15</span>)</span>
<span id="cb26-7"><a></a>)</span>
<span id="cb26-8"><a></a></span>
<span id="cb26-9"><a></a><span class="co"># Fit OLS</span></span>
<span id="cb26-10"><a></a>fit_cotton <span class="ot">&lt;-</span> <span class="fu">lm</span>(tensile_str <span class="sc">~</span> pct_cotton, <span class="at">data =</span> cotton)</span>
<span id="cb26-11"><a></a></span>
<span id="cb26-12"><a></a><span class="co"># Manual OLS components</span></span>
<span id="cb26-13"><a></a>x_c  <span class="ot">&lt;-</span> cotton<span class="sc">$</span>pct_cotton</span>
<span id="cb26-14"><a></a>Y_c  <span class="ot">&lt;-</span> cotton<span class="sc">$</span>tensile_str</span>
<span id="cb26-15"><a></a>Sxx_c <span class="ot">&lt;-</span> <span class="fu">sum</span>((x_c <span class="sc">-</span> <span class="fu">mean</span>(x_c))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-16"><a></a>Sxy_c <span class="ot">&lt;-</span> <span class="fu">sum</span>((x_c <span class="sc">-</span> <span class="fu">mean</span>(x_c)) <span class="sc">*</span> (Y_c <span class="sc">-</span> <span class="fu">mean</span>(Y_c)))</span>
<span id="cb26-17"><a></a></span>
<span id="cb26-18"><a></a><span class="fu">cat</span>(<span class="st">"Sxx ="</span>, Sxx_c, <span class="st">"  Sxy ="</span>, Sxy_c, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sxx = 1000   Sxy = 160 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">cat</span>(<span class="st">"beta1_hat ="</span>, <span class="fu">round</span>(Sxy_c <span class="sc">/</span> Sxx_c, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>beta1_hat = 0.16 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">cat</span>(<span class="st">"beta0_hat ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(Y_c) <span class="sc">-</span> (Sxy_c<span class="sc">/</span>Sxx_c) <span class="sc">*</span> <span class="fu">mean</span>(x_c), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>beta0_hat = 10.8 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">cat</span>(<span class="st">"Theoretical Var(beta1_hat) / sigma^2 ="</span>, <span class="fu">round</span>(<span class="dv">1</span> <span class="sc">/</span> Sxx_c, <span class="dv">6</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Theoretical Var(beta1_hat) / sigma^2 = 0.001 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">tidy</span>(fit_cotton) <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, statistic, p.value) <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">round</span>(x, <span class="dv">4</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)    10.8      4.20      2.57   0.0191
2 pct_cotton      0.16     0.162     0.991  0.335 </code></pre>
</div>
</div>
</section>
<section id="dbc-example-12.7-plot" class="slide level2">
<h2>DBC Example 12.7: Plot</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">ggplot</span>(cotton, <span class="fu">aes</span>(<span class="at">x =</span> pct_cotton, <span class="at">y =</span> tensile_str)) <span class="sc">+</span></span>
<span id="cb36-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb36-5"><a></a>    <span class="at">title =</span> <span class="st">"DBC Example 12.7: Tensile Strength vs. Cotton Content"</span>,</span>
<span id="cb36-6"><a></a>    <span class="at">subtitle =</span> <span class="fu">bquote</span>(<span class="fu">hat</span>(beta)[<span class="dv">1</span>] <span class="sc">==</span> .(<span class="fu">round</span>(Sxy_c <span class="sc">/</span> Sxx_c, <span class="dv">3</span>)) <span class="sc">~</span></span>
<span id="cb36-7"><a></a>                        <span class="st">" psi per % cotton (OLS = BLUE = MLE)"</span>),</span>
<span id="cb36-8"><a></a>    <span class="at">x =</span> <span class="st">"Percentage Cotton"</span>,</span>
<span id="cb36-9"><a></a>    <span class="at">y =</span> <span class="st">"Tensile Strength (psi)"</span></span>
<span id="cb36-10"><a></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="22_GaussMarkov_OLS_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"><div class="fragment">
<p>The positive slope <span class="math inline">\(\hat\beta_1 \approx\)</span> 0.16 is the <strong>BLUE</strong> of the true slope. Under normality, it also achieves the CRLB and is the MVUE.</p>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#006a4e">
<h1>Summary</h1>

</section>
<section id="what-we-proved-today" class="slide level2 scrollable">
<h2>What We Proved Today</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Results</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><p><strong>OLS estimators</strong> <span class="math inline">\(\hat\beta_0 = \bar Y - \hat\beta_1 \bar x\)</span> and <span class="math inline">\(\hat\beta_1 = S_{xy}/S_{xx}\)</span> minimize the RSS</p></li>
<li><p>OLS estimators are <strong>linear</strong> in <span class="math inline">\(Y_i\)</span> and <strong>unbiased</strong> under GM assumptions 1–3</p></li>
<li><p>Under all four GM assumptions: <span class="math inline">\(\text{Var}(\hat\beta_1) = \sigma^2/S_{xx}\)</span>, <span class="math inline">\(\text{Var}(\hat\beta_0) = \sigma^2(1/n + \bar x^2/S_{xx})\)</span></p></li>
<li><p><strong>Gauss-Markov Theorem:</strong> OLS is <strong>BLUE</strong> (no normality required)</p></li>
<li><p>Under normality: OLS = MLE, and OLS is the <strong>MVUE</strong> (not just BLUE)</p></li>
<li><p>OLS achieves the <strong>Cramér-Rao Lower Bound</strong>; it is an <strong>efficient</strong> estimator under normality</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="connections-to-the-course-themes" class="slide level2">
<h2>Connections to the Course Themes</h2>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-79f351a847cf4e646453" style="width:960px;height:864px;"></div>
<script type="application/json" data-for="htmlwidget-79f351a847cf4e646453">{"x":{"diagram":"\ndigraph course_connections {\n  graph [rankdir = LR, bgcolor = transparent, splines = curved, nodesep = 0.8, ranksep = 2.2]\n  node [shape = box, style = filled, fontsize = 42, width = 6.4, height = 2.0]\n\n  MVUE  [label = \"MVUE Theory\\n(Lessons 3, 6)\", fillcolor = \"#AED6F1\"]\n  CRLB  [label = \"CRLB / Fisher Info\\n(Lessons 3, 6)\", fillcolor = \"#F5B7B1\"]\n  MLE   [label = \"MLE\\n(Lesson 4)\", fillcolor = \"#FAD7A0\"]\n  Suff  [label = \"Sufficient Stats\\n(Lesson 5)\", fillcolor = \"#D7BDE2\"]\n  GM    [label = \"Gauss-Markov:\\nOLS is BLUE\", fillcolor = \"#ABEBC6\"]\n  Reg   [label = \"Applied Regression\", fillcolor = \"#D5D8DC\"]\n\n  MVUE -> GM  [label = \"BLUE = MVUE for\\nlinear models\", fontsize = 24]\n  CRLB -> GM  [label = \"OLS achieves CRLB\\nunder normality\", fontsize = 24]\n  MLE  -> GM  [label = \"OLS = MLE\\nunder normality\", fontsize = 24]\n  Suff -> GM  [label = \"(β̂₀, β̂₁, S²) sufficient\\nunder normality\", fontsize = 24]\n  GM   -> Reg [label = \"t-tests, F-tests,\\nprediction intervals\", fontsize = 24]\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<ul>
<li><strong>Applied Regression:</strong> Everything builds on today’s theory
<ul>
<li>Multiple regression extends to <span class="math inline">\(\hat{\boldsymbol\beta} = (\mathbf{X}^\top\mathbf{X})^{-1}\mathbf{X}^\top\mathbf{Y}\)</span>; the same BLUE result holds via matrix algebra</li>
<li>Generalized Linear Models (GLMs): when <span class="math inline">\(\varepsilon_i\)</span> are non-normal → MLE replaces OLS</li>
<li>Mixed models: when independence fails → GLS / REML</li>
</ul></li>
<li><strong>Weighted Least Squares:</strong> BLUE when heteroscedasticity is known (DBC §12.9)</li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Matrix Formulation Preview</strong></p>
</div>
<div class="callout-content">
<p>In multiple regression: <span class="math inline">\(\mathbf{Y} = \mathbf{X}\boldsymbol\beta + \boldsymbol\varepsilon\)</span></p>
<p>OLS estimate: <span class="math inline">\(\hat{\boldsymbol\beta} = (\mathbf{X}^\top\mathbf{X})^{-1}\mathbf{X}^\top\mathbf{Y}\)</span></p>
<p>This is still linear in <span class="math inline">\(\mathbf{Y}\)</span>, still unbiased under GM conditions, and still BLUE by the matrix version of the Gauss-Markov theorem.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questions" class="slide level2 center" data-background-color="#3498db">
<h2>Questions?</h2>
<p>Thank you!</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Lesson 22 - Gauss-Markov Theorem and OLS Theory</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1955,

        height: 1100,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>