{
  "hash": "8eb85924bf8b71c8c60b93f61f40a7e1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 7: Introduction to Confidence Intervals\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-01-21\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 7 - Introduction to CIs\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 7: From Point Estimates to Intervals {background-color=\"#2c3e50\"}\n\n## Review: What We've Learned About Estimation\n\n**Point Estimation (Lessons 1-6):**\n\n-   Estimators: statistics that estimate parameters\n-   Properties: bias, variance, MSE, efficiency\n-   Construction: Method of Moments, Maximum Likelihood\n-   Quality: MVUE, sufficient statistics, Cramér-Rao bound\n\n. . .\n\n**The Limitation of Point Estimates:**\n\nA single number ($\\hat{\\theta} = 0.75$) tells us nothing about **precision** or **uncertainty** of the estimate.\n\n## Today's Goals\n\n::: incremental\n1.  Understand why we need interval estimates\n2.  Learn the correct interpretation of confidence intervals\n3.  Derive confidence intervals using pivotal quantities\n4.  Construct and interpret z-intervals (known $\\sigma$)\n5.  Determine sample sizes for desired precision\n6.  Understand one-sided confidence bounds\n:::\n\n## Motivating Example: Clinical Trial\n\nA new antihypertensive drug is tested in $n = 36$ patients. The mean reduction in systolic blood pressure is $\\bar{x} = 12.3$ mmHg.\n\n. . .\n\n**Point estimate:** $\\hat{\\mu} = 12.3$ mmHg\n\n. . .\n\n**Questions we can't answer with just the point estimate:**\n\n-   How close is 12.3 to the true mean reduction?\n-   Is the true mean likely to be at least 10 mmHg?\n-   How much could $\\bar{X}$ vary in repeated trials?\n\n. . .\n\n::: callout-note\n## The Solution\nA **confidence interval** provides a range of plausible values for the parameter, along with a measure of confidence.\n:::\n\n# The Fundamental Idea {background-color=\"#27ae60\"}\n\n## From Point to Interval\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-revealjs/unnamed-chunk-1-1.png){width=1344}\n:::\n:::\n\n\n**Key insight:** The interval captures our uncertainty about the true parameter value.\n\n## What Is a Confidence Interval?\n\n::: callout-important\n## Definition: Confidence Interval\nA **confidence interval (CI)** for a parameter $\\theta$ is a random interval $(L, U)$ computed from sample data such that:\n$$P(L < \\theta < U) = 1 - \\alpha$$\nfor a specified confidence level $1 - \\alpha$.\n:::\n\n. . .\n\n**Important:**\n\n-   $L$ and $U$ are **random** (they depend on the sample)\n-   $\\theta$ is **fixed** (but unknown)\n-   The probability statement is about the **random event** that the lower and upper bound cover $\\theta$, not about any randomness in $\\theta$ itself.\n-   The probability statement only makes sense when thinking about defining the estimators $L$ and $U$ and their sampling distributions, it does not make sense when talking about one sample and the observed values for $L$ and $U$\n\n## Correct Interpretation of Confidence Intervals\n\n::: callout-warning\n## Common Misconception\n\"There is a 95% probability that $\\mu$ lies in the interval (7.4, 17.2).\"\n\n**This is WRONG!** After computing the interval, $\\mu$ either is or is not in the interval. There's no probability involved.\n:::\n\n. . .\n\n::: callout-tip\n## Correct Interpretation\n\"If we repeated this procedure many times, 95% of the resulting intervals would contain the true $\\mu$.\"\n\nOr more simply/loosely: \"We are 95% confident that the true mean lies between 7.4 and 17.2.\"\n:::\n\n## Common Mistakes to Avoid (Chihara Example 7.2)\n\nSuppose a 95% CI for mean gas mileage is (29.5, 33.4) mpg. Evaluate:\n\n. . .\n\n1. ❌ \"We are 95% confident that gas mileage for cars in this company is between 29.5 and 33.4 mpg.\"\n   - **Wrong:** CI is for population *mean*, not individual values.\n\n. . .\n\n2. ❌ \"95% of all samples will give an average mileage between 29.5 and 33.4 mpg.\"\n   - **Wrong:** Each sample gives a *different* CI; 95% of *intervals* contain $\\mu$.\n\n. . .\n\n3. ❌ \"There is a 95% chance that the true mean is between 29.5 and 33.4 mpg.\"\n   - **Wrong:** $\\mu$ is fixed, not random. It's either in the interval or not.\n\n## Visualizing Confidence Level: Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate 100 confidence intervals\nset.seed(551)\ntrue_mu <- 10; sigma <- 4; n <- 25\n\nci_data <- tibble(sample_id = 1:100) |>\n  rowwise() |>\n  mutate(\n    xbar = mean(rnorm(n, true_mu, sigma)),\n    lower = xbar - 1.96 * sigma / sqrt(n),\n    upper = xbar + 1.96 * sigma / sqrt(n),\n    contains_mu = lower < true_mu & upper > true_mu\n  )\n\n# Count how many contain the true mean\nsum(ci_data$contains_mu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 94\n```\n\n\n:::\n:::\n\n\n## Visualizing Confidence Level: The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## The R Code for CI Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate *5000* confidence intervals\nset.seed(551)\ntrue_mu <- 10; sigma <- 4; n <- 25\n\nci_data <- tibble(sample_id = 1:5000) |>\n  rowwise() |>\n  mutate(\n    xbar = mean(rnorm(n, true_mu, sigma)),\n    lower = xbar - 1.96 * sigma / sqrt(n),\n    upper = xbar + 1.96 * sigma / sqrt(n),\n    contains_mu = lower < true_mu & upper > true_mu\n  )\n\n# Proportion containing true mu (should be ~95%)\nmean(ci_data$contains_mu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9498\n```\n\n\n:::\n:::\n\n\nThis is how the confidence level works: about 95% of intervals capture $\\mu$.\n\n## Your Turn: CI Interpretation\n\n**Exercise:** A researcher reports a 95% CI for mean hospital stay after surgery as (3.2, 4.8) days. Which statements are correct?\n\nA. \"95% of patients stay between 3.2 and 4.8 days\"\n\nB. \"We are 95% confident the true mean stay is between 3.2 and 4.8 days\"\n\nC. \"There is a 95% probability the mean is in this interval\"\n\nD. \"If we repeated this study many times, about 95% of the CIs would contain the true mean\"\n\n. . .\n\n**Answer:** B and D are correct interpretations.\n\n# Pivotal Quantities {background-color=\"#e74c3c\"}\n\n## The Key to Constructing CIs\n\n::: callout-important\n## Definition: Pivotal Quantity\nA **pivotal quantity** is a function $h(X_1, \\ldots, X_n; \\theta)$ of the data and parameter such that:\n\n1.  It depends on both the sample and $\\theta$\n2.  Its **distribution does not depend on $\\theta$** (or any other unknown parameters)\n:::\n\n. . .\n\n**Why pivotal quantities matter:**\n\n-   We can find critical values that don't depend on unknowns\n-   We can \"solve for $\\theta$\" to get confidence limits\n\n## Example: The Standard Pivotal Quantity\n\nLet $X_1, \\ldots, X_n \\stackrel{iid}{\\sim} N(\\mu, \\sigma^2)$ with $\\sigma$ known.\n\n. . .\n\nConsider:\n$$Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$$\n\n. . .\n\n**Check the properties:**\n\n1.  $Z$ depends on $\\bar{X}$ (data) and $\\mu$ (parameter) ✓\n2.  $Z \\sim N(0, 1)$ — the distribution doesn't depend on $\\mu$ ✓\n\n. . .\n\n$Z$ is a **pivotal quantity**!\n\n## From Pivotal Quantity to CI\n\nSince $Z \\sim N(0, 1)$, we know:\n$$P(-z_{\\alpha/2} < Z < z_{\\alpha/2}) = 1 - \\alpha$$\n\n. . .\n\nSubstitute $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}}$:\n$$P\\left(-z_{\\alpha/2} < \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < z_{\\alpha/2}\\right) = 1 - \\alpha$$\n\n. . .\n\n**Solve for $\\mu$:**\n$$P\\left(\\bar{X} - z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{X} + z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\\right) = 1 - \\alpha$$\n\n. . .\n\nThis gives us the **confidence interval formula**!\n\n. . .\n\nWhat is $L$ and $U$ here?\n\n## The General Pivotal Quantity Method\n\n::: callout-tip\n## Recipe for Constructing CIs\n1. Find a pivotal quantity $h(X_1, \\ldots, X_n; \\theta)$\n2. Find constants $a$ and $b$ such that $P(a < h < b) = 1 - \\alpha$\n3. Solve the inequalities for $\\theta$ to get $(L, U)$\n:::\n\n. . .\n\n**Example (Devore 8.1):** For normal data with known $\\sigma$:\n\n- Pivotal: $Z = \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} \\sim N(0,1)$\n- Constants: $a = -z_{\\alpha/2}$, $b = z_{\\alpha/2}$\n- Solve: $\\bar{X} - z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{X} + z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$\n\n# CI for Mean: $\\sigma$ Known {background-color=\"#3498db\"}\n\n## The Z-Interval\n\n::: callout-important\n## Z Confidence Interval for Normal Mean ($\\sigma$ Known)\nIf $X_1, \\ldots, X_n \\sim N(\\mu, \\sigma^2)$ with $\\sigma$ known, a $100(1-\\alpha)\\%$ CI for $\\mu$ is:\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\nwhere $z_{\\alpha/2}$ is the critical value with $P(Z > z_{\\alpha/2}) = \\alpha/2$.\n:::\n\n. . .\n\n**Common critical values:**\n\n| Confidence Level | $\\alpha$ | $\\alpha/2$ | $z_{\\alpha/2}$ |\n|------------------|----------|------------|----------------|\n| 90% | 0.10 | 0.05 | 1.645 |\n| 95% | 0.05 | 0.025 | 1.960 |\n| 99% | 0.01 | 0.005 | 2.576 |\n\n## Example: Tensile Strength (Devore Example 8.1)\n\nSynthetic fibers are tested for tensile strength. From past data, $\\sigma = 55$ MPa is known. A sample of $n = 31$ fibers has $\\bar{x} = 1064$ MPa.\n\n. . .\n\n**95% Confidence Interval:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 1064\nsigma <- 55\nn <- 31\nalpha <- 0.05\n\nz_crit <- qnorm(1 - alpha/2)\nmargin <- z_crit * sigma / sqrt(n)\n\nc(xbar - margin, xbar + margin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1044.639 1083.361\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** We are 95% confident that the true mean tensile strength is between 1044.6 and 1083.4 MPa.\n\n## Medical Example: Blood Glucose Levels\n\nA hospital monitors fasting blood glucose in diabetic patients. Historical data shows $\\sigma = 18$ mg/dL. A sample of $n = 40$ patients has $\\bar{x} = 142$ mg/dL.\n\n**Construct a 99% CI for the population mean glucose level:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 142\nsigma <- 18\nn <- 40\nalpha <- 0.01\n\nz_crit <- qnorm(1 - alpha/2)\ncat(\"z critical value:\", round(z_crit, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz critical value: 2.576 \n```\n\n\n:::\n\n```{.r .cell-code}\nmargin <- z_crit * sigma / sqrt(n)\ncat(\"Margin of error:\", round(margin, 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargin of error: 7.33 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"99% CI: (\", round(xbar - margin, 1), \",\", round(xbar + margin, 1), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n99% CI: ( 134.7 , 149.3 )\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Clinical interpretation:** We can be 99% confident that the true mean fasting glucose for this patient population is between 134.7 and 149.3 mg/dL.\n\n## Anatomy of a Confidence Interval\n\n$$\\bar{x} \\pm z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n**Three factors affect the margin of error:**\n\n1. **Confidence level** ($z_{\\alpha/2}$): Higher confidence → wider interval → less precise\n2. **Population variability** ($\\sigma$): More variation → wider interval → less precise\n3. **Sample size** ($n$): Larger sample → narrower interval → more precise\n\n## Interactive: Effect of Confidence Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Same data, different confidence levels\nxbar <- 1064; sigma <- 55; n <- 31\n\nconfidence_levels <- c(0.90, 0.95, 0.99)\n\ntibble(conf_level = confidence_levels) |>\n  mutate(\n    z_crit = qnorm(1 - (1 - conf_level)/2),\n    margin = z_crit * sigma / sqrt(n),\n    lower = xbar - margin,\n    upper = xbar + margin,\n    width = upper - lower\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  conf_level z_crit margin lower upper width\n       <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl>\n1       0.9    1.64   16.2 1048. 1080.  32.5\n2       0.95   1.96   19.4 1045. 1083.  38.7\n3       0.99   2.58   25.4 1039. 1089.  50.9\n```\n\n\n:::\n:::\n\n\n**Takeaway:** Higher confidence requires wider intervals!\n\n## Visualizing the Trade-off\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](07_Confidence_Intervals_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Sample Size Determination\n\n**Question:** How large should $n$ be to achieve a desired precision?\n\n. . .\n\nIf we want the margin of error to be at most $b$:\n$$z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}} \\leq b$$\n\n. . .\n\n**Solving for $n$:**\n$$n \\geq \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{b}\\right)^2$$\n\n## Sample Size Example: Clinical Trial Design\n\nA pharmaceutical company wants to estimate mean drug clearance time. From pilot data, $\\sigma \\approx 25$ minutes. They want a 95% CI with margin of error ≤ 5 minutes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 25\nb <- 5  # desired margin of error\nalpha <- 0.05\nz_crit <- qnorm(1 - alpha/2)\n\nn_required <- (z_crit * sigma / b)^2\ncat(\"Minimum sample size:\", ceiling(n_required))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMinimum sample size: 97\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Note:** Always round **up** to ensure the desired precision!\n\n## Sample Size: Effect of Requirements\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How does required n change with margin of error and confidence?\nexpand_grid(\n  margin = c(3, 5, 10),\n  conf_level = c(0.90, 0.95, 0.99)\n) |>\n  mutate(\n    z = qnorm(1 - (1 - conf_level)/2),\n    n_required = ceiling((z * 25 / margin)^2)\n  ) |>\n  pivot_wider(names_from = margin, values_from = n_required, \n              names_prefix = \"margin_\") |>\n  select(-z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  conf_level margin_3 margin_5 margin_10\n       <dbl>    <dbl>    <dbl>     <dbl>\n1       0.9       188       68        17\n2       0.95      267       97        25\n3       0.99      461      166        42\n```\n\n\n:::\n:::\n\n\n**Key insight:** Halving the margin of error (from 10 to 5) quadruples the sample size!\n\n## One-Sided Confidence Bounds\n\nSometimes we only care about one direction:\n\n-   **Lower bound:** We want to know the minimum plausible value\n-   **Upper bound:** We want to know the maximum plausible value\n\n. . .\n\n::: callout-tip\n## One-Sided Bounds\n**Lower Confidence Bound:** $\\bar{x} - z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu$\n\n**Upper Confidence Bound:** $\\mu < \\bar{x} + z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n\nNote: Use $z_\\alpha$ (not $z_{\\alpha/2}$) for one-sided bounds at confidence level $1 - \\alpha$.\n:::\n\n. . .\n\n## Why $z_\\alpha$ instead of $z_{\\alpha/2}$?\n\nFor a **two-sided** CI, we split $\\alpha$ into two tails ($\\alpha/2$ each):\n$$P\\left(-z_{\\alpha/2} < \\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < z_{\\alpha/2}\\right) = 1 - \\alpha$$\n\n. . .\n\nFor a **one-sided lower bound**, all $\\alpha$ goes in one tail:\n$$P\\left(\\frac{\\bar{X} - \\mu}{\\sigma/\\sqrt{n}} < z_{\\alpha}\\right) = 1 - \\alpha$$\n\nRearranging for $\\mu$:\n$$P\\left(\\bar{X} - z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}} < \\mu\\right) = 1 - \\alpha$$\n\n. . .\n\nSo the lower bound is: $L = \\bar{X} - z_{\\alpha} \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n\n**Key insight:** One-sided bounds use $z_\\alpha$ because we put all the \"error probability\" $\\alpha$ on one side, not split between two sides.\n\n## Medical Example: Drug Half-Life\n\nA pharmacologist measures half-life of a new drug. With $n = 20$ subjects, $\\bar{x} = 4.2$ hours, and known $\\sigma = 0.8$ hours.\n\n**Find a 95% lower confidence bound:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 4.2\nsigma <- 0.8\nn <- 20\nalpha <- 0.05\n\nz_crit <- qnorm(1 - alpha)  # Note: z_alpha, not z_alpha/2\nlower_bound <- xbar - z_crit * sigma / sqrt(n)\n\ncat(\"95% lower confidence bound:\", round(lower_bound, 2), \"hours\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower confidence bound: 3.91 hours\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Interpretation: We are 95% confident that the true half-life\",\n    \"\\nis at least\", round(lower_bound, 2), \"hours\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterpretation: We are 95% confident that the true half-life \nis at least 3.91 hours\n```\n\n\n:::\n:::\n\n\n## Why Lower vs. Upper Bounds?\n\n**Use a LOWER bound when:**\n\n- Testing if a treatment effect is \"at least\" some value\n- Establishing minimum efficacy\n- Setting safety margins\n\n. . .\n\n**Use an UPPER bound when:**\n\n- Estimating maximum risk or adverse event rate  \n- Establishing worst-case scenarios\n- Quality control (maximum defect rate)\n\n## Example: Remission Time (Devore 8.7)\n\nA surgeon wants a lower bound for mean remission time after cancer surgery. From $n = 25$ patients, $\\bar{x} = 42$ months, $\\sigma = 12$ months (from historical data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 42\nsigma <- 12\nn <- 25\nalpha <- 0.05\n\n# 95% lower confidence bound\nz_alpha <- qnorm(1 - alpha)\nlower <- xbar - z_alpha * sigma / sqrt(n)\n\ncat(\"95% lower confidence bound:\", round(lower, 1), \"months\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% lower confidence bound: 38.1 months\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nWe are 95% confident that true mean remission time\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWe are 95% confident that true mean remission time\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"is at least\", round(lower, 1), \"months.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nis at least 38.1 months.\n```\n\n\n:::\n:::\n\n\n# Pivotal Quantities for Other Distributions {background-color=\"#9b59b6\"}\n\n## Example: Exponential Distribution (Devore 8.5)\n\nTime-to-breakdown of insulating fluid follows $\\text{Exp}(\\lambda)$ with mean $1/\\lambda$ and variance $1/\\lambda^2$. Given $n = 10$ observations with $\\sum x_i = 550.87$ min.\n\n. . .\n\n**The pivotal quantity:**\n$$h = 2\\lambda \\sum_{i=1}^n X_i \\sim \\chi^2_{2n}$$\n\n. . .\n\n**Why is this pivotal?**\n\n- Depends on data ($\\sum X_i$) and parameter ($\\lambda$)\n- Distribution ($\\chi^2_{2n}$) doesn't depend on $\\lambda$\n\n## Exponential CI Derivation\n\nLet $\\chi^2_{.025, 20}$ and $\\chi^2_{.975, 20}$ be the critical values. Then:\n\n$$P\\left(\\chi^2_{.975, 20} < 2\\lambda \\sum X_i < \\chi^2_{.025, 20}\\right) = 0.95$$\n\n. . .\n\n**Solving for $\\lambda$:**\n$$P\\left(\\frac{\\chi^2_{.975, 20}}{2\\sum X_i} < \\lambda < \\frac{\\chi^2_{.025, 20}}{2\\sum X_i}\\right) = 0.95$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_x <- 550.87\nlower <- qchisq(0.025, df = 20) / (2 * sum_x)\nupper <- qchisq(0.975, df = 20) / (2 * sum_x)\ncat(\"95% CI for λ: (\", round(lower, 4), \",\", round(upper, 4), \")\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for λ: ( 0.0087 , 0.031 )\n```\n\n\n:::\n:::\n\n\n## CI for Mean of Exponential\n\nSince the mean of $\\text{Exp}(\\lambda)$ is $\\mu = 1/\\lambda$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CI for mean breakdown time\nmean_lower <- 1/upper\nmean_upper <- 1/lower\n\ncat(\"95% CI for mean breakdown time:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mean breakdown time:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(\", round(mean_lower, 1), \",\", round(mean_upper, 1), \") minutes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n( 32.2 , 114.9 ) minutes\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Note:** The interval is quite wide — reflecting variability in the data and small sample size.\n\n# Summary and Looking Ahead {background-color=\"#2c3e50\"}\n\n## Lesson 7 Summary\n\n**Key Concepts:**\n\n1.  **Confidence Intervals** provide a range of plausible values with quantified uncertainty\n\n2.  **Correct Interpretation:** \"95% of intervals constructed this way contain $\\theta$\"\n\n3.  **Pivotal Quantities** allow CI construction without knowing unknown parameters\n\n4.  **Z-intervals** ($\\sigma$ known): $\\bar{x} \\pm z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$\n\n5.  **Sample Size:** $n \\geq \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{b}\\right)^2$\n\n6.  **One-sided bounds** use $z_\\alpha$ instead of $z_{\\alpha/2}$\n\n## Key Formulas for Z-Intervals\n\n| Quantity | Formula |\n|----------|---------|\n| Two-sided CI | $\\bar{x} \\pm z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$ |\n| Lower bound | $\\bar{x} - z_{\\alpha}\\frac{\\sigma}{\\sqrt{n}}$ |\n| Upper bound | $\\bar{x} + z_{\\alpha}\\frac{\\sigma}{\\sqrt{n}}$ |\n| Sample size | $n = \\left(\\frac{z_{\\alpha/2} \\cdot \\sigma}{b}\\right)^2$ |\n| Width | $w = 2 z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}$ |\n\n## Looking Ahead: Lesson 8\n\n**Next Lesson: One-Sample t-Intervals and Proportions**\n\n-   What if $\\sigma$ is unknown? (The t-interval)\n-   The Student's t distribution\n-   Confidence intervals for population proportions\n-   Wald vs. Score intervals\n-   Checking assumptions\n\n## References\n\n::: nonincremental\n-   Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Chapter 8.1\n-   Chihara and Hesterberg. *Mathematical Statistics with Resampling and R* (Wiley). Chapter 7.1-7.2\n:::\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n",
    "supporting": [
      "07_Confidence_Intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}