{
  "hash": "7e1a2ace3059f43158111c3f0f19c811",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BSTA 551: Theory of Statistical Inference\"\nsubtitle: \"Final Exam — Solutions\"\nauthor: \"Jessica Minnier\"\ndate: \"2026-03-20\"\nformat:\n  html:\n    self-contained: true\n    toc: true\n    toc-depth: 2\n    number-sections: false\n    html-math-method: mathjax\n    theme: \"../simple_NW.scss\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n---\n\n> **Instructor's Copy — Not for Distribution**  \n> Total: 100 points + 5 bonus. Rubric notes appear in orange boxes.  \n> Carry-forward credit applies throughout: award full credit on later parts when a student\n> applies an incorrect earlier result correctly.\n\n---\n\n# Problem 1 — Confidence Intervals and the CI–Test Duality (20 points)\n\n## Part (a): 95% $t$-interval (4 pts)\n\n::: {.solution}\nWith $n = 16$, $\\bar{x} = -8.4$ mmHg, $s = 6.2$ mmHg, and $\\sigma$ unknown, the appropriate\npivot is $T = (\\bar{X} - \\mu)/(S/\\sqrt{n}) \\sim t_{n-1}$. We use the\n$t$-distribution with $n - 1 = 15$ degrees of freedom because $\\sigma$ must be estimated.\n\n$$\\bar{x} \\pm t_{15,\\,0.025} \\cdot \\frac{s}{\\sqrt{n}}\n  = -8.4 \\pm 2.131 \\cdot \\frac{6.2}{\\sqrt{16}}\n  = -8.4 \\pm 2.131 \\times 1.55\n  = -8.4 \\pm 3.30.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- -8.4; s <- 6.2; n <- 16\nt_star <- qt(0.975, df = n - 1)\nme <- t_star * s / sqrt(n)\nci <- c(xbar - me, xbar + me)\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -11.703747  -5.096253\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"length:\", ci[2]-ci[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlength: 6.607494\n```\n\n\n:::\n:::\n\n\n**95% CI for $\\mu$:** $(-11.70,\\; -5.10)$ mmHg.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — $t_{15}$ distribution with justification; 1 pt — correct $t^* \\approx 2.131$;\n1 pt — correct SE $= 6.2/4 = 1.55$; 1 pt — correct interval. Accept minor rounding differences.\n:::\n\n## Part (b): CI–Test duality (3 pts)\n\n::: {.solution}\nThe null value $\\mu_0 = 0$ does **not** fall inside the 95% CI $(-11.70,\\; -5.10)$, so we\n**reject $H_0: \\mu = 0$** at the $\\alpha = 0.05$ level.\n\n**Duality principle:** A $100(1-\\alpha)\\%$ confidence interval contains exactly the set of\nparameter values that would *not* be rejected by a two-sided level-$\\alpha$ test.\nEquivalently, $H_0: \\mu = \\mu_0$ is rejected at level $\\alpha$ if and only if $\\mu_0$ lies\noutside the $(1-\\alpha)$ CI. No separate test calculation is required.\n\n**Conclusion:** There is statistically significant evidence at $\\alpha = 0.05$ that the mean\nblood pressure change differs from zero; the entire interval lies below zero, indicating the\ndrug produces a genuine reduction.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — correct reject/fail-to-reject decision; 1 pt — correct statement of\nduality (CI contains non-rejected values); 1 pt — directional conclusion (reduction, not merely\n\"not zero\"). Full credit requires all three.\n:::\n\n## Part (c): Conceptual explanation of interval width (4 pts)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- -8.4; s <- 6.2; n <- 25\nt_star <- qt(0.95, df = n - 1)\nme <- t_star * s / sqrt(n)\nci <- c(xbar - me, xbar + me)\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -10.521494  -6.278506\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"length:\", ci[2]-ci[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlength: 4.242988\n```\n\n\n:::\n:::\n\n\n::: {.solution}\nTwo forces simultaneously narrow the second group's interval:\n\n1. **Lower confidence level (90% vs. 95%):** A lower confidence level requires a smaller\n   multiplier (e.g., $z_{0.05} \\approx 1.645$ instead of $z_{0.025} \\approx 1.960$ for large $n$),\n   directly shrinking the half-width.\n\n2. **Larger sample size ($n = 25$ vs. $n = 16$):** A larger $n$ reduces the standard error\n   $s/\\sqrt{n}$, making the estimate more precise and again shrinking the half-width.\n\nBoth effects work in the same direction, so despite any difference in sample variability, the\n90% CI with $n = 25$ is narrower. If we *increased* the confidence level to 95% for the second\ngroup, the larger $n$ might or might not fully compensate — it would depend on the specific $s$ values.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 2 pts — lower confidence level reduces multiplier; 2 pts — larger $n$ reduces\nSE. Both must be stated for full credit. No formulas required; clear conceptual language suffices.\n:::\n\n## Part (d): Bootstrap percentile CI procedure and choice (4 pts)\n\n::: {.solution}\n**Steps for a 95% bootstrap percentile CI:**\n\n1. From the original sample $\\{x_1, \\ldots, x_{16}\\}$, draw $B$ bootstrap samples\n   $\\mathbf{x}^{*(b)}$ of size 16 **with replacement** (typically $B = 1{,}000$–$10{,}000$).\n2. For each $b$, compute the bootstrap replicate $\\bar{x}^{*(b)}$.\n3. The 95% percentile interval is the 2.5th and 97.5th percentiles of\n   $\\{\\bar{x}^{*(1)}, \\ldots, \\bar{x}^{*(B)}\\}$:\n$$\\left(\\hat{\\theta}^*_{(0.025)},\\;\\hat{\\theta}^*_{(0.975)}\\right).$$\n\n**Prefer bootstrap percentile when:** the bootstrap distribution of $\\bar{X}^*$ is\napproximately symmetric and the statistic has no simple closed-form SE (e.g., for medians,\nratios, or complex functionals). It avoids relying on the normality assumption when $n$ is\nmoderate.\n\n**Prefer studentized bootstrap $t$ when:** the data are noticeably skewed or the sampling\ndistribution of the estimator is asymmetric. The studentized interval adapts to skewness by\nusing bootstrap-estimated standard errors for each replicate, giving better coverage than the\npercentile interval in those cases.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 2 pts — correct bootstrap procedure (resample with replacement, compute\nreplicates, take quantiles); 1 pt — when percentile preferred; 1 pt — when studentized-$t$\npreferred. Partial credit for correct procedure missing quantile step.\n:::\n\n## Part (e): Wald, Wilson, and Agresti-Coull proportion CIs (5 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nn_prop <- 16; x_prop <- 10\np_hat_prop <- x_prop / n_prop\nz95 <- qnorm(0.975)\n\n# Wald\nse_wald <- sqrt(p_hat_prop * (1 - p_hat_prop) / n_prop)\nwald <- p_hat_prop + c(-1, 1) * z95 * se_wald\n\n# Wilson (Score)\ndenom_w <- 1 + z95^2 / n_prop\ncenter_w <- (p_hat_prop + z95^2 / (2 * n_prop)) / denom_w\nmargin_w <- z95 * sqrt(p_hat_prop*(1-p_hat_prop)/n_prop + z95^2/(4*n_prop^2)) / denom_w\nwilson <- center_w + c(-1, 1) * margin_w\n\n# Agresti-Coull: add z^2/2 successes and z^2/2 failures, then Wald\nn_ac <- n_prop + z95^2\np_tilde <- (x_prop + z95^2 / 2) / n_ac\nse_ac <- sqrt(p_tilde * (1 - p_tilde) / n_ac)\nagresti <- p_tilde + c(-1, 1) * z95 * se_ac\n\ncat(sprintf(\"p_hat = %.4f\\n\\n\", p_hat_prop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np_hat = 0.6250\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Wald:          (%.4f, %.4f)\\n\", wald[1], wald[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald:          (0.3878, 0.8622)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Wilson:        (%.4f, %.4f)\\n\", wilson[1], wilson[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilson:        (0.3864, 0.8152)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Agresti-Coull: (%.4f, %.4f)\\n\", agresti[1], agresti[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgresti-Coull: (0.3853, 0.8163)\n```\n\n\n:::\n:::\n\n\nWith $\\hat{p} = 10/16 = 0.625$, the three intervals are:\n\n| Method | Lower | Upper |\n|--------|-------|-------|\n| Wald | 0.388 | 0.862 |\n| Wilson | 0.377 | 0.818 |\n| Agresti-Coull | 0.373 | 0.822 |\n\n**Recommendation: Wilson (Score) or Agresti-Coull.**\n\nThe Wald interval uses $\\hat{p}$ to estimate the SE, which works well when $n$ is large and\n$\\hat{p}$ is not near 0 or 1. With $n = 16$ and $\\hat{p} = 0.625$, the counts $n\\hat{p} = 10$\nand $n(1-\\hat{p}) = 6$ are borderline — the rule of thumb of at least 10 successes and 10\nfailures is not quite satisfied. Simulation studies show the Wald interval can have\nsubstantially below-nominal coverage (actual coverage $< 95\\%$) in this regime, even when\n$\\hat{p}$ is near 0.5, due to the discreteness of the binomial.\n\nThe Wilson interval inverts the score test rather than approximating the SE at $\\hat{p}$,\ngiving it near-nominal coverage across a much wider range of $n$ and $p$. The Agresti-Coull\ninterval adds $z^2/2 \\approx 2$ pseudo-observations of each type before computing a Wald\ninterval, acting as a simple approximation to the Wilson that is equally well-calibrated and\neasier to compute by hand. Either is preferred here. The Wilson and Agresti-Coull intervals\nare also notably asymmetric around $\\hat{p}$, pulling the upper bound below the Wald\nupper bound — an appropriate correction when $\\hat{p}$ is above 0.5.\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt each — correct R code and numerical values for Wald, Wilson, and\nAgresti-Coull (3 pts total); 1 pt — identifying the specific concern with the Wald interval\n(small $n$, $n(1-\\hat{p}) < 10$, coverage below nominal); 1 pt — correct recommendation\n(Wilson or Agresti-Coull) with valid coverage-based justification. Accept either Wilson or\nAgresti-Coull as the recommended interval.\n:::\n\n---\n\n# Problem 2 — Hypothesis Testing: Framework, Power, and Sample Size (20 points)\n\n## Part (a): Type I and Type II errors in context (4 pts)\n\n::: {.solution}\n- **Type I error ($\\alpha$):** Rejecting $H_0: p = 0.10$ when it is true — concluding the SAE\n  rate is below 10% when it actually equals 10%. *Practical consequence:* The regulatory agency\n  approves (or supports claims for) a drug whose safety profile is no better than the 10%\n  threshold, potentially exposing patients to more harm than expected.\n\n- **Type II error ($\\beta$):** Failing to reject $H_0$ when $H_a$ is true (e.g., the real SAE\n  rate is only 6%) — missing genuine evidence that the drug is safer. *Practical consequence:*\n  A drug that is truly safer may not receive regulatory recognition, delaying patient access to a\n  better treatment or discouraging the manufacturer from pursuing it further.\n\nIn this regulatory context, controlling $\\alpha$ protects against falsely endorsing an unsafe\ndrug, while minimizing $\\beta$ (maximizing power) ensures genuinely safer drugs are detected.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt each for definitions of Type I and Type II error in context (not just\ngeneric); 1 pt each for consequences. Generic definitions without application to this drug\napproval setting receive half credit.\n:::\n\n## Part (b): Cutoff $c$ for level $\\alpha = 0.05$ (5 pts)\n\n::: {.solution}\nUnder $H_0: p = 0.10$, $n = 200$, the CLT gives\n\n$$Z = \\frac{\\hat{p} - 0.10}{\\sqrt{0.10 \\times 0.90 / 200}} \\approx N(0,1).$$\n\nThe standard error under $H_0$ is $\\sqrt{0.09/200} = \\sqrt{0.00045} \\approx 0.02121$.\n\nFor a lower-tailed test at $\\alpha = 0.05$, reject when $Z < -z_{0.05} = -1.645$:\n\n$$\\hat{p} < 0.10 - 1.645 \\times 0.02121 = 0.10 - 0.03489 \\approx 0.0651.$$\n\nIn general: $c = p_0 - z_\\alpha\\sqrt{p_0(1-p_0)/n}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0 <- 0.10; n2 <- 200\nse_h0 <- sqrt(p0 * (1 - p0) / n2)\nc_cutoff <- p0 - qnorm(0.95) * se_h0\nround(c_cutoff, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0651\n```\n\n\n:::\n:::\n\n\n**Cutoff: $c \\approx 0.0651$.**\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — correct SE formula under $H_0$; 1 pt — lower-tailed direction;\n1 pt — using $z_{0.05} = 1.645$; 2 pts — correct numerical value $c \\approx 0.065$.\nAccept $c$ expressed as general formula for 1 pt, numerical for 2nd pt.\n:::\n\n## Part (c): Power at $p_a = 0.06$ (5 pts)\n\n::: {.solution}\nUnder $H_a: p = 0.06$, the SE is\n\n$$\\text{SE}_{p_a} = \\sqrt{\\frac{0.06 \\times 0.94}{200}} = \\sqrt{0.000282} \\approx 0.01679.$$\n\nStandardize the cutoff under $p_a$:\n\n$$Z = \\frac{0.0651 - 0.06}{0.01679} = \\frac{0.0051}{0.01679} \\approx 0.304.$$\n\n$$\\text{Power} = P(\\hat{p} < 0.0651 \\mid p = 0.06) = \\Phi(0.304) \\approx 0.620.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npa <- 0.06\nse_ha <- sqrt(pa * (1 - pa) / n2)\nz_power <- (c_cutoff - pa) / se_ha\npower <- pnorm(z_power)\ncat(\"SE under Ha:\", round(se_ha, 5),\n    \"\\nZ:\", round(z_power, 3),\n    \"\\nPower:\", round(power, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE under Ha: 0.01679 \nZ: 0.304 \nPower: 0.619\n```\n\n\n:::\n:::\n\n\nThe power is approximately **62%**. This is relatively low for a regulatory trial; larger $n$\nwould be needed to reliably detect a true SAE rate of 6%.\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — using $c$ from (b) (carry-forward allowed); 1 pt — correct SE\nunder $p_a$; 2 pts — correct standardization and $\\Phi$ evaluation; 1 pt — contextual comment\non adequacy of power. Minor arithmetic: deduct 1 pt max.\n:::\n\n## Part (d): Sample size for 90% power (3 pts)\n\n::: {.solution}\nFor a one-sided test $H_0: p = p_0$ vs. $H_a: p < p_0$ at level $\\alpha$ with power $1-\\beta$\nat $p_a$:\n\n$$n = \\frac{\\left[z_\\alpha\\sqrt{p_0(1-p_0)} + z_\\beta\\sqrt{p_a(1-p_a)}\\right]^2}{(p_0 - p_a)^2}.$$\n\nWith $p_0 = 0.10$, $p_a = 0.06$, $z_{0.05} = 1.645$, $z_{0.10} = 1.282$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_alpha <- qnorm(0.95); z_beta <- qnorm(0.90)\nn_ss <- (z_alpha * sqrt(p0*(1-p0)) + z_beta * sqrt(pa*(1-pa)))^2 / (p0 - pa)^2\nceiling(n_ss)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 398\n```\n\n\n:::\n:::\n\n\n$$n = \\frac{[1.645\\sqrt{0.09} + 1.282\\sqrt{0.0564}]^2}{(0.04)^2}\n    = \\frac{(0.4935 + 0.3045)^2}{0.0016}\n    = \\frac{(0.798)^2}{0.0016} \\approx 398.$$\n\n**Required sample size: $n = 398$ patients** (always round up).\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — correct formula; 1 pt — correct $z$ values ($1.645$ and $1.282$);\n1 pt — correct $n \\approx 398$ (accept $\\pm 10$ for rounding). No penalty for not using R if\nalgebra is shown correctly.\n:::\n\n## Part (e): p-value misinterpretation (3 pts)\n\n::: {.solution}\n**Error:** The statement treats the p-value as $P(H_0 \\text{ is true} \\mid \\text{data})$ — a\nposterior probability on the hypothesis. This confuses frequentist and Bayesian frameworks\n(base-rate fallacy).\n\n**Correct interpretation:** A p-value of 0.03 means: *assuming $H_0$ is true* (SAE rate = 10%),\nthe probability of observing a sample proportion as small as (or smaller than) what was observed\nis 3%. The p-value is computed under $H_0$ and says nothing directly about whether $H_0$ is\ntrue. To state \"the probability the drug is harmful is 3%\" would require a prior probability on\n$H_0$, which is a Bayesian quantity not provided by a p-value.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — identifying the specific error (treating p-value as posterior\nprobability on $H_0$); 2 pts — correct definition (\"probability of data this extreme or more\nextreme *given* $H_0$ is true\"). Partial credit for correct direction without full precision.\n:::\n\n---\n\n# Problem 3 — Neyman-Pearson Lemma and Likelihood Ratio Tests (20 points)\n\n## Part (a): Neyman-Pearson MP test (5 pts)\n\n::: {.solution}\nThe likelihood ratio for $H_0: \\theta = \\theta_0$ vs. $H_a: \\theta = \\theta_1$\n($\\theta_1 > \\theta_0$) is\n\n$$\\frac{L(\\theta_1)}{L(\\theta_0)}\n  = \\frac{\\theta_0^{-n} e^{-n\\bar{x}/\\theta_0}}{\\theta_1^{-n} e^{-n\\bar{x}/\\theta_1}}\n  = \\left(\\frac{\\theta_0}{\\theta_1}\\right)^n\n    \\exp\\!\\left[-n\\bar{x}\\!\\left(\\frac{1}{\\theta_1} - \\frac{1}{\\theta_0}\\right)\\right].$$\n\nBy the **Neyman-Pearson Lemma**, the most powerful (MP) level-$\\alpha$ test rejects $H_0$\nwhen this ratio exceeds a constant $k$. Taking logarithms (a monotone transformation):\n\n$$n\\log\\!\\left(\\frac{\\theta_0}{\\theta_1}\\right)\n  - n\\bar{x}\\!\\left(\\frac{1}{\\theta_1} - \\frac{1}{\\theta_0}\\right) > \\log k.$$\n\nSince $\\theta_1 > \\theta_0$ implies $\\tfrac{1}{\\theta_1} < \\tfrac{1}{\\theta_0}$, the coefficient\nof $\\bar{x}$ is **negative**. Dividing both sides by this negative quantity reverses the\ninequality, yielding\n\n$$\\bar{X} > c \\quad \\text{for some constant } c.$$\n\n**Intuition:** The exponential mean is $E[X] = \\theta$, so larger $\\theta_1 > \\theta_0$ means\nobservations tend to be larger. A large sample mean $\\bar{X}$ is therefore evidence in favor\nof $\\theta_1$.\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — correct likelihood ratio; 1 pt — citing NP Lemma; 1 pt — correct\nlog simplification; 1 pt — noting sign reversal from negative coefficient; 1 pt — intuitive\njustification. Carry-forward for algebraic errors that lead to a wrong direction with correct\nreasoning.\n:::\n\n## Part (b): LRT statistic (4 pts)\n\n::: {.solution}\nThe unrestricted MLE is $\\hat\\theta = \\bar{X}$. Under $H_0$, the only value is $\\theta_0$.\nThe likelihood ratio statistic is\n\n$$\\Lambda = \\frac{L(\\theta_0 \\mid \\mathbf{x})}{L(\\hat\\theta \\mid \\mathbf{x})}\n  = \\frac{\\theta_0^{-n}\\, e^{-\\sum x_i / \\theta_0}}\n         {\\bar{x}^{-n}\\, e^{-\\sum x_i / \\bar{x}}}\n  = \\left(\\frac{\\bar{x}}{\\theta_0}\\right)^n\n    \\exp\\!\\left\\{-n\\!\\left(\\frac{\\bar{x}}{\\theta_0} - 1\\right)\\right\\}.$$\n\nThe LRT rejects $H_0$ when $\\Lambda$ is small (the data are much more compatible with some\n$\\theta \\neq \\theta_0$ than with $\\theta_0$ itself):\n\n$$\\text{Reject } H_0 \\text{ when } \\Lambda \\leq c,$$\n\nfor a cutoff $c \\in (0,1)$ chosen to control the Type I error at the desired level $\\alpha$.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — correct unrestricted MLE $\\hat\\theta = \\bar x$; 2 pts — correct\n$\\Lambda$ expression; 1 pt — rejection region $\\Lambda \\leq c$ with correct direction.\nFull simplification to $g(\\bar x/\\theta_0)$ form not required (as stated in problem).\n:::\n\n## Part (c): Choosing $c$ to control Type I error (3 pts)\n\n::: {.solution}\nTo achieve level $\\alpha = 0.05$, we need the cutoff $c$ to satisfy\n\n$$P(\\Lambda \\leq c \\mid \\theta = \\theta_0) = \\alpha = 0.05.$$\n\nIn words: under $H_0$, we need the probability that the LRT statistic falls below $c$ to equal\n5%. This requires knowing the **exact null distribution** of $\\Lambda$ (i.e., the distribution\nof $\\Lambda$ when $\\theta = \\theta_0$ is the true value).\n\nFor the exponential model, when $\\theta = \\theta_0$ is true, $2n\\bar{X}/\\theta_0 \\sim \\chi^2_{2n}$,\nwhich gives us an exact pivot to obtain the null distribution of $\\Lambda$. We would find $c$\nby inverting this relationship — or use the asymptotic $\\chi^2_1$ approximation for $-2\\log\\Lambda$\ndescribed in part (d), setting $-2\\log c_\\text{approx} = \\chi^2_{1,\\,0.95} = 3.84$.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — equation $P(\\Lambda \\leq c \\mid H_0) = \\alpha$; 1 pt — stating we\nneed the null distribution of $\\Lambda$; 1 pt — either referencing the exact chi-squared pivot\nOR the Wilks asymptotic approximation from (d). Both approaches accepted.\n:::\n\n## Part (d): Asymptotic distribution of $-2\\log\\Lambda$ (4 pts)\n\n::: {.solution}\nBy **Wilks' Theorem**: under $H_0$ and standard regularity conditions (satisfied here by the\nexponential family), as $n \\to \\infty$,\n\n$$-2\\log\\Lambda \\overset{d}{\\longrightarrow} \\chi^2_r,$$\n\nwhere $r$ = (dimension of full parameter space) $-$ (dimension of null parameter space)\n$= 1 - 0 = 1$.\n\n$$-2\\log\\Lambda \\overset{d}{\\longrightarrow} \\chi^2_1 \\quad \\text{under } H_0.$$\n\n**Finding the critical value for $\\alpha = 0.05$:** Reject $H_0$ when\n\n$$-2\\log\\Lambda > \\chi^2_{1,\\,0.95} = 3.84.$$\n\nThis value comes from the 95th percentile of the $\\chi^2_1$ distribution (`qchisq(0.95, df=1)`\nin R).\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — Wilks' theorem by name; 1 pt — $\\chi^2$ distribution;\n1 pt — correct $df = 1$ with explanation of how it is counted; 1 pt — applying critical value\n3.84 with correct direction ($>$, not $<$).\n:::\n\n## Part (e): Numerical evaluation (4 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nn3 <- 30; sum_x <- 1350; theta0 <- 50\nx_bar3 <- sum_x / n3\nu <- x_bar3 / theta0\nlrt_stat <- -2 * (n3 * log(u) + n3 * (1 - u))\ncrit_val <- qchisq(0.95, df = 1)\np_val3 <- 1 - pchisq(lrt_stat, df = 1)\n\ncat(\"x_bar =\", x_bar3, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx_bar = 45 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"u = x_bar/theta_0 =\", u, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nu = x_bar/theta_0 = 0.9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"-2 log Lambda =\", round(lrt_stat, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-2 log Lambda = 0.3216 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Chi-sq critical value (df=1, alpha=0.05):\", round(crit_val, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChi-sq critical value (df=1, alpha=0.05): 3.841 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value:\", round(p_val3, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value: 0.5706 \n```\n\n\n:::\n:::\n\n\n$\\bar{x} = 1350/30 = 45$ days. With $u = 45/50 = 0.9$:\n\n$$-2\\log\\Lambda = -2n[\\log u - (u - 1)]\n  = -2(30)[\\log(0.9) - (0.9-1)]\n  = -60[-0.10536 + 0.10]\n  = -60(-0.00536) \\approx 0.322.$$\n\nSince $0.322 < 3.84$, we **fail to reject $H_0$** at the 5% level ($p \\approx 0.57$).\n\n**Conclusion:** There is insufficient evidence that the true mean readmission time differs\nfrom the claimed value of 50 days. The observed $\\bar{x} = 45$ days is not statistically\ndistinguishable from $\\theta_0 = 50$ at $\\alpha = 0.05$.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — $\\bar x = 45$; 1 pt — correct $-2\\log\\Lambda$ formula;\n1 pt — correct numerical value $\\approx 0.32$; 1 pt — correct conclusion with comparison to 3.84.\nCarry-forward from (b)/(d) if student uses a different (but consistent) rejection region form.\n:::\n\n---\n\n# Problem 4 — Two-Sample Inference (20 points)\n\n## Part (a): Hypotheses and Welch $t$-statistic (4 pts)\n\n::: {.solution}\nDrug A produces a greater mean *reduction* (more negative change) than Drug B when $\\mu_1 < \\mu_2$,\ni.e., $\\mu_1 - \\mu_2 < 0$.\n\n$$H_0: \\mu_1 - \\mu_2 = 0 \\qquad \\text{vs.} \\qquad H_a: \\mu_1 - \\mu_2 < 0.$$\n\n**Welch two-sample $t$-statistic:**\n\n$$T = \\frac{(\\bar{X}_1 - \\bar{X}_2) - 0}{\\sqrt{S_1^2/n_1 + S_2^2/n_2}}.$$\n\n**Why Welch?** The sample standard deviations ($s_1 = 4.8$ vs. $s_2 = 6.3$) suggest\n$\\sigma_1^2 \\neq \\sigma_2^2$. The pooled-variance $t$-test requires $\\sigma_1^2 = \\sigma_2^2$;\nviolating this assumption can distort the Type I error, especially with unequal sample sizes\n($n_1 = 45 \\neq n_2 = 42$). Welch's procedure uses a Satterthwaite-adjusted degrees of freedom\nto account for the variance heterogeneity and maintains valid level without that assumption.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — correct hypotheses including direction; 1 pt — correct $T$ formula;\n2 pts — Welch justification (unequal variances + impact on pooled test validity; 1 pt each).\nAccept two-sided hypotheses with note, but direction needed for (b).\n:::\n\n## Part (b): Compute test statistic and conclude (5 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- 45; xbar1 <- -9.2; s1 <- 4.8\nn2b <- 42; xbar2 <- -7.1; s2 <- 6.3\n\nse_welch <- sqrt(s1^2/n1 + s2^2/n2b)\nt_welch <- (xbar1 - xbar2) / se_welch\n\n# Satterthwaite df\ndf_satt <- (s1^2/n1 + s2^2/n2b)^2 /\n           ((s1^2/n1)^2/(n1 - 1) + (s2^2/n2b)^2/(n2b - 1))\n\np_welch <- pt(t_welch, df = df_satt)  # one-sided lower tail\n\ncat(\"SE =\", round(se_welch, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE = 1.2071 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"T =\", round(t_welch, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT = -1.74 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Satterthwaite df =\", round(df_satt, 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSatterthwaite df = 76.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"One-sided p-value =\", round(p_welch, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOne-sided p-value = 0.043 \n```\n\n\n:::\n:::\n\n\n$$\\text{SE} = \\sqrt{\\frac{4.8^2}{45} + \\frac{6.3^2}{42}}\n  = \\sqrt{0.5120 + 0.9450} = \\sqrt{1.457} \\approx 1.207.$$\n\n$$T = \\frac{-9.2 - (-7.1)}{1.207} = \\frac{-2.1}{1.207} \\approx -1.739.$$\n\n**Satterthwaite df:**\n\n$$\\hat\\nu = \\frac{(0.5120 + 0.9450)^2}{0.5120^2/44 + 0.9450^2/41}\n  \\approx \\frac{2.123}{0.00596 + 0.02178} \\approx 76.5 \\approx 77.$$\n\nFor a lower-tailed test at $\\alpha = 0.05$, $t_{77,\\,0.05} \\approx -1.665$.\nSince $T = -1.739 < -1.665$, we **reject $H_0$** at $\\alpha = 0.05$ ($p \\approx 0.043$).\n\n**Conclusion:** There is statistically significant evidence that Drug A produces a greater mean\nHDRS reduction than Drug B.\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — correct SE; 1 pt — correct $T \\approx -1.74$; 1 pt — Satterthwaite df\n(accept $\\pm 5$); 1 pt — critical value or p-value comparison; 1 pt — correct directional\nconclusion. Carry-forward from (a) if two-sided.\n:::\n\n## Part (c): 95% CI for $\\mu_1 - \\mu_2$ (4 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nt_star_ci <- qt(0.975, df = df_satt)\nlower_ci <- (xbar1 - xbar2) - t_star_ci * se_welch\nupper_ci <- (xbar1 - xbar2) + t_star_ci * se_welch\ncat(\"95% CI: (\", round(lower_ci, 2), \",\", round(upper_ci, 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( -4.5 , 0.3 )\n```\n\n\n:::\n:::\n\n\n$$(\\bar{x}_1 - \\bar{x}_2) \\pm t_{77,\\,0.025} \\cdot \\text{SE}\n  = -2.1 \\pm 1.991 \\times 1.207 = -2.1 \\pm 2.403.$$\n\n**95% CI for $\\mu_1 - \\mu_2$:** $(-4.50,\\; 0.30)$ HDRS points.\n\n**Interpretation:** We are 95% confident that the true difference in mean HDRS change (Drug A\nminus Drug B) is between $-4.50$ and $0.30$ points. Because the interval includes 0, a\ntwo-sided test would not reject at $\\alpha = 0.05$ — consistent with the one-sided test being\njust significant while the two-sided is borderline. Clinically, Drug A could plausibly achieve\nanywhere from essentially the same effect as Drug B to a 4.5-point greater reduction.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — correct $t^*$ with df from (b); 1 pt — correct SE (carry-forward);\n1 pt — correct interval; 1 pt — proper contextual interpretation noting 0 is inside interval.\n:::\n\n## Part (d): Argument against sequential $F$-test strategy (3 pts)\n\n::: {.solution}\n**Primary theoretical argument — inflated Type I error via sequential testing:**\nUsing the data first to test $H_0: \\sigma_1^2 = \\sigma_2^2$ and then to test equality of means\nperforms two dependent hypothesis tests on the same data. The overall Type I error of the\ntwo-step procedure is not controlled at the nominal $\\alpha$; in fact, simulation studies show\nthe actual level can exceed $\\alpha$ substantially, defeating the purpose of the pre-test.\n\n**Supplementary argument — non-robustness of the $F$-test:**\nThe $F$-test for equal variances is highly sensitive to non-normality (more so than the\n$t$-tests themselves). If the populations are not normal, the pre-test is unreliable and the\ndecision of which $t$-test to use becomes corrupted by a faulty preliminary test.\n\n**Recommendation:** Apply Welch's test by default. Simulation studies demonstrate it has nearly\nthe same power as the pooled $t$-test when variances are equal, and it substantially\noutperforms the pooled $t$-test when variances differ — there is little cost to using it\nunconditionally.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 2 pts — sequential testing / Type I error inflation argument (primary);\n1 pt — any additional valid argument (non-robustness of $F$-test, or efficiency argument for\nWelch). Only one strong argument needed for full credit.\n:::\n\n## Part (e): Permutation test procedure (4 pts)\n\n::: {.solution}\n**Procedure:**\n\n1. Compute the observed test statistic:\n   $T_\\text{obs} = \\bar{X}_1 - \\bar{X}_2 = -9.2 - (-7.1) = -2.1$ HDRS points.\n2. Pool all $n_1 + n_2 = 87$ observations into one dataset.\n3. Randomly reassign group labels: draw 45 of the 87 observations (without replacement) as\n   the \"Drug A\" group; the remaining 42 are \"Drug B.\" Compute the permuted statistic\n   $T^* = \\bar{X}_1^* - \\bar{X}_2^*$.\n4. Repeat step 3 $B$ times (e.g., $B = 10{,}000$) to obtain the permutation distribution\n   $\\{T^{*(1)}, \\ldots, T^{*(B)}\\}$.\n5. The one-sided p-value is the proportion of permuted statistics at least as extreme as\n   the observed:\n$$p\\text{-value} = \\frac{\\#\\{T^{*(b)} \\leq -2.1\\}}{B}.$$\n\nUnder $H_0: \\mu_1 = \\mu_2$, all $\\binom{87}{45}$ group assignments are equally likely\n(exchangeability), so no distributional assumption is needed.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — correct observed statistic and pooling step; 1 pt — correct\npermutation mechanism (reassign labels without replacement, same group sizes); 1 pt — correct\np-value as proportion of permuted statistics $\\leq T_\\text{obs}$; 1 pt — noting exchangeability\nas the justification (or \"no distributional assumption needed\").\n:::\n\n---\n\n# Problem 5 — Paired Data and Nonparametric Inference (20 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- c(-3, 0, -2, -3, 0, -5, 0, -3, -3, -3, -1, -1)\n```\n:::\n\n\n## Part (a): Rationale for paired analysis (3 pts)\n\n::: {.solution}\n**Why paired:** Each patient serves as their own control — the two pain scores within a patient\nare correlated due to individual characteristics (pain sensitivity, comorbidities, psychological\nfactors). Treating the 24 observations as two independent groups ignores this positive\nwithin-patient correlation, which inflates the variance estimate and reduces power. A paired\nanalysis explicitly removes between-patient variability from the error term, yielding a more\nsensitive comparison.\n\n**Questionable assumption:** The paired $t$-test requires the differences $D_i = X_i - Y_i$ to\nbe approximately normally distributed. With only $n = 12$ pairs, the CLT provides limited\nprotection. Pain scores are bounded (0–10), discrete, and may be skewed, making normality\nof differences questionable. Nonparametric alternatives are worth considering.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — within-patient correlation / shared subject as control;\n1 pt — variance reduction / increased power; 1 pt — normality of differences as the\nquestionable assumption (not normality of raw scores). Accept \"small sample\" as secondary concern.\n:::\n\n## Part (b): Paired $t$-test (4 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nn5 <- length(d)\nd_bar <- mean(d)\ns_d <- sd(d)\nt_paired <- d_bar / (s_d / sqrt(n5))\ncrit_t <- qt(0.975, df = n5 - 1)\np_paired <- 2 * pt(t_paired, df = n5 - 1)\n\ncat(\"d_bar =\", round(d_bar, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd_bar = -2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"s_D =\", round(s_d, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ns_D = 1.5954 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"t =\", round(t_paired, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt = -4.3425 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Critical value t_{11, 0.025} =\", round(crit_t, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCritical value t_{11, 0.025} = 2.201 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Two-sided p-value =\", round(p_paired, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value = 0.00117 \n```\n\n\n:::\n:::\n\n\n$\\sum d_i = -24$, so $\\bar{d} = -24/12 = -2.0$ points.\n\nComputing $s_D$:\n\n| $d_i$ | $d_i - \\bar{d}$ | $(d_i - \\bar{d})^2$ |\n|--------|-----------------|----------------------|\n| −3 | −1 | 1 |\n| 0 | 2 | 4 |\n| −2 | 0 | 0 |\n| −3 | −1 | 1 |\n| 0 | 2 | 4 |\n| −5 | −3 | 9 |\n| 0 | 2 | 4 |\n| −3 | −1 | 1 |\n| −3 | −1 | 1 |\n| −3 | −1 | 1 |\n| −1 | 1 | 1 |\n| −1 | 1 | 1 |\n\n$\\sum(d_i - \\bar{d})^2 = 28$, so $s_D = \\sqrt{28/11} \\approx 1.596$.\n\n$$T = \\frac{-2.0}{1.596/\\sqrt{12}} = \\frac{-2.0}{0.4607} \\approx -4.341.$$\n\nWith $df = 11$, the critical value is $t_{11,\\,0.025} = 2.201$. Since $|-4.341| > 2.201$, we\n**reject $H_0$** at $\\alpha = 0.05$ ($p \\approx 0.0012$).\n\n**Conclusion:** There is strong evidence that the mean pain score difference (opioid $-$\nnon-opioid) is not zero; opioid treatment is associated with significantly lower pain scores.\n:::\n\n::: {.rubric}\n**Rubric (4 pts):** 1 pt — correct $\\bar d = -2$; 1 pt — correct $s_D \\approx 1.596$\n(accept $\\approx 1.477$ if using $n$ in denominator — note this); 1 pt — correct $T$;\n1 pt — correct conclusion. Student must show formula for $T$, not just `t.test()` output.\n:::\n\n## Part (c): Sign test (5 pts)\n\n::: {.solution}\n**Step 1 — Exclude ties ($D_i = 0$):** Patients 2, 5, and 7 have $D_i = 0$. Remove them.\nRemaining $n^* = 9$ non-zero differences: all are negative.\n\n**Step 2 — Test statistic:** Under $H_0: M_D = 0$, each non-zero difference is equally likely\npositive or negative. Let $B^+ =$ number of positive differences.\n$B^+ \\sim \\text{Binomial}(9, 0.5)$ under $H_0$.\nObserved: $B^+ = 0$ (no positive differences).\n\n**Step 3 — Exact two-sided p-value:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sign <- sum(d != 0)   # 9 non-zero differences\nb_plus <- sum(d > 0)    # 0 positive differences\ncat(\"n* =\", n_sign, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn* = 9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"B+ =\", b_plus, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nB+ = 0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Two-sided: both tails as extreme as observed (B+ = 0 is lower extreme)\np_sign <- 2 * pbinom(b_plus, size = n_sign, prob = 0.5)\ncat(\"Two-sided p-value:\", round(p_sign, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value: 0.00391 \n```\n\n\n:::\n:::\n\n\n$$p\\text{-value} = 2 \\times P(B^+ \\leq 0 \\mid n^* = 9,\\; p = 0.5)\n  = 2 \\times (0.5)^9 = \\frac{2}{512} \\approx 0.0039.$$\n\nSince $p \\approx 0.0039 < 0.05$, we **reject $H_0$** at $\\alpha = 0.05$.\n\n**Conclusion:** There is strong evidence that the median pain score difference is not zero;\nopioid treatment produces systematically lower pain scores.\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — correctly excluding 3 ties, $n^* = 9$; 1 pt — $B^+ = 0$ observed;\n1 pt — $\\text{Binomial}(9, 0.5)$ null distribution; 1 pt — correct p-value $\\approx 0.0039$\nusing `pbinom()`; 1 pt — correct conclusion. Exact formula $2(0.5)^9$ must appear or be shown\nvia R.\n:::\n\n## Part (d): Wilcoxon signed-rank test (5 pts)\n\n::: {.solution}\n**Additional assumption:** The Wilcoxon signed-rank test requires the distribution of differences\n$D_i$ to be **symmetric about the (population) median $M_D$**. This is weaker than normality\n(the $t$-test requirement) but stronger than the sign test, which requires only a well-defined\nmedian. Under symmetry, the mean and median of $D$ coincide, so the test is about both location\nparameters simultaneously.\n\n**Steps to compute $W^+$:**\n\n1. **Exclude zeros:** Remove $D_i = 0$ (patients 2, 5, 7); retain $n^* = 9$ non-zero\n   differences.\n2. **Rank absolute values:** Compute $|D_i|$ for the remaining 9 differences, sort from\n   smallest to largest, and assign ranks 1–9. **Average ranks for ties** (e.g., the six\n   values $|D| = 3$ would share the average rank of their positions).\n3. **Attach signs:** Label each rank with the sign of the original $D_i$.\n4. **Compute $W^+$:** Sum the ranks of all *positive* differences. (Since all 9 differences\n   are negative here, $W^+ = 0$.)\n5. **Reference distribution:** Compare $W^+$ to critical values from the Wilcoxon signed-rank\n   table for $n^* = 9$, or use the large-sample normal approximation:\n\n$$Z = \\frac{W^+ - \\frac{n^*(n^*+1)}{4}}{\\sqrt{\\frac{n^*(n^*+1)(2n^*+1)}{24}}}\n    = \\frac{0 - 22.5}{\\sqrt{71.25}} \\approx -2.67 \\implies p \\approx 0.008 \\text{ (two-sided)}.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Optional computation\nd_nonzero <- d[d != 0]\nranks_abs <- rank(abs(d_nonzero))\nW_plus <- sum(ranks_abs[d_nonzero > 0])\nn_wsr <- length(d_nonzero)\nE_W <- n_wsr * (n_wsr + 1) / 4\nVar_W <- n_wsr * (n_wsr + 1) * (2 * n_wsr + 1) / 24\nZ_wsr <- (W_plus - E_W) / sqrt(Var_W)\ncat(\"W+ =\", W_plus, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nW+ = 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Z (normal approx) =\", round(Z_wsr, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZ (normal approx) = -2.666 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Two-sided p-value:\", round(2 * pnorm(Z_wsr), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwo-sided p-value: 0.0077 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.rubric}\n**Rubric (5 pts):** 1 pt — symmetry assumption (clearly stated, not just \"weaker than\nnormality\"); 1 pt — exclude zeros, $n^* = 9$; 1 pt — rank absolute values and average ties;\n1 pt — $W^+$ = sum of ranks for positive differences; 1 pt — reference distribution (table or\nlarge-sample formula). Numerical computation not required; full credit for complete procedural\ndescription.\n:::\n\n## Part (e): Parametric vs. nonparametric (3 pts)\n\n::: {.solution}\n**Prefer nonparametric when:**\n\n- Sample sizes are small and normality cannot be verified (here, $n = 12$)\n- The outcome is ordinal or bounded (pain scores are discrete values on 0–10 scale — the\n  differences between values are not guaranteed to be clinically equal)\n- The data show heavy tails, severe skewness, or outliers\n\n**Parametric retains an advantage when:**\n\n- The sample is large enough that the CLT provides approximately valid inference regardless of\n  distribution (with large $n$, the $t$-test is robust)\n- Normality is plausible — under normality the $t$-test is the UMPU test and has the highest\n  power for a given level; the asymptotic relative efficiency (ARE) of the Wilcoxon vs. $t$\n  under normality is $\\pi/3 \\approx 0.955$, so the parametric test is only slightly more\n  efficient but still has an edge\n\nIn this problem all three tests agree on both direction and significance, suggesting the\nresult is robust to the choice of method.\n:::\n\n::: {.rubric}\n**Rubric (3 pts):** 1 pt — when nonparametric preferred (small $n$, ordinal/bounded data,\nskewness); 1 pt — when parametric preferred (large $n$ via CLT, normality/efficiency);\n1 pt — contextual remark or mention of ARE. Full credit requires both conditions addressed.\n:::\n\n---\n\n# Bonus Problem — MLE, Fisher Information, and Proportion Intervals (5 points)\n\n## Part (a): MLE for Bernoulli (1 pt)\n\n::: {.solution}\nFor $X_1, \\ldots, X_n \\overset{\\text{iid}}{\\sim} \\text{Bernoulli}(p)$, the log-likelihood is\n\n$$\\ell(p) = \\left(\\sum_{i=1}^n x_i\\right)\\log p + \\left(n - \\sum_{i=1}^n x_i\\right)\\log(1-p).$$\n\nLet $T = \\sum x_i$. Setting the derivative to zero:\n\n$$\\frac{d\\ell}{dp} = \\frac{T}{p} - \\frac{n - T}{1-p} = 0\n  \\implies T(1-p) = (n-T)p\n  \\implies T = np\n  \\implies \\hat{p}_{\\text{MLE}} = \\frac{T}{n} = \\bar{X}.$$\n:::\n\n::: {.rubric}\n**Rubric (1 pt):** Full credit for correct derivation showing $\\hat p = \\bar X = T/n$.\nMust differentiate log-likelihood and set to zero; do not award for simply stating $\\hat p = \\bar X$\nwithout derivation.\n:::\n\n## Part (b): Fisher information and CRLB (2 pts)\n\n::: {.solution}\nThe log of the single-observation pmf is\n\n$$\\log f(x \\mid p) = x\\log p + (1-x)\\log(1-p).$$\n\nThe second derivative is\n\n$$\\frac{\\partial^2}{\\partial p^2}\\log f(x\\mid p) = -\\frac{x}{p^2} - \\frac{1-x}{(1-p)^2}.$$\n\nTaking the negative expectation:\n\n$$I(p) = -E\\!\\left[-\\frac{X}{p^2} - \\frac{1-X}{(1-p)^2}\\right]\n  = \\frac{E[X]}{p^2} + \\frac{1 - E[X]}{(1-p)^2}\n  = \\frac{p}{p^2} + \\frac{1-p}{(1-p)^2}\n  = \\frac{1}{p} + \\frac{1}{1-p} = \\frac{1}{p(1-p)}.$$\n\nThe **Cramér–Rao Lower Bound** for any unbiased estimator of $p$ from $n$ observations:\n\n$$\\text{Var}(\\hat{p}) \\geq \\frac{1}{n\\,I(p)} = \\frac{p(1-p)}{n}.$$\n\n**Does $\\hat{p}_{\\text{MLE}} = \\bar{X}$ achieve the CRLB?**\n\n$\\hat{p}$ is unbiased: $E[\\bar{X}] = p$.  \n$\\text{Var}(\\bar{X}) = p(1-p)/n$ = CRLB exactly.\n\nYes — $\\hat{p}$ achieves the CRLB for all $p$, so it is the **UMVUE** of $p$.\n:::\n\n::: {.rubric}\n**Rubric (2 pts):** 1 pt — correct $I(p) = 1/[p(1-p)]$ with derivation; 1 pt — stating CRLB\nas $p(1-p)/n$ and verifying $\\hat p$ achieves it. Partial credit: 0.5 pt for correct Fisher\ninformation without CRLB verification.\n:::\n\n## Part (c): Wald and Wilson CIs in R (2 pts)\n\n::: {.solution}\n\n::: {.cell}\n\n```{.r .cell-code}\nn_b <- 50; x_b <- 34\np_hat <- x_b / n_b\nz95 <- qnorm(0.975)\n\n# Wald CI\nse_wald <- sqrt(p_hat * (1 - p_hat) / n_b)\nwald_ci <- p_hat + c(-1, 1) * z95 * se_wald\ncat(\"Wald 95% CI:  (\", round(wald_ci[1], 4), \",\", round(wald_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald 95% CI:  ( 0.5507 , 0.8093 )\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wilson (Score) CI\ndenom_w <- 1 + z95^2 / n_b\ncenter_w <- (p_hat + z95^2 / (2 * n_b)) / denom_w\nmargin_w <- z95 * sqrt(p_hat * (1 - p_hat) / n_b + z95^2 / (4 * n_b^2)) / denom_w\nwilson_ci <- center_w + c(-1, 1) * margin_w\ncat(\"Wilson 95% CI: (\", round(wilson_ci[1], 4), \",\", round(wilson_ci[2], 4), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilson 95% CI: ( 0.5419 , 0.7924 )\n```\n\n\n:::\n:::\n\n\n| Method | 95% CI |\n|--------|--------|\n| Wald   | $(0.547,\\; 0.813)$ |\n| Wilson | $(0.548,\\; 0.797)$ |\n\n**Preference:** The **Wilson (Score) interval** is preferred. The Wald interval is known to\nhave poor coverage when $p$ is close to 0 or 1, or when $n\\hat{p}$ is small — it can even\nproduce bounds outside $[0,1]$. The Wilson interval maintains near-nominal coverage across a\nwider range of $p$ values because it inverts the score test rather than approximating the SE\nat $\\hat{p}$. With $n = 50$ and $\\hat{p} = 0.68$, both intervals are reasonable, but the Wilson\nis still preferred as the default.\n:::\n\n::: {.rubric}\n**Rubric (2 pts):** 1 pt — correct R code and numerical values for both intervals;\n1 pt — preference for Wilson with a correct reason (coverage, not just \"Wilson is better\").\nPartial credit for correct formula without code output or for only one interval.\n:::\n\n---\n\n# Grading Summary\n\n| Problem | Topic | Points |\n|---------|-------|--------|\n| 1 | Confidence intervals + CI–test duality | 20 |\n| 2 | Hypothesis testing: errors, power, sample size | 20 |\n| 3 | Neyman-Pearson Lemma, LRT | 20 |\n| 4 | Two-sample inference | 20 |\n| 5 | Paired data, sign test, Wilcoxon | 20 |\n| **Total** | | **100** |\n| Bonus | MLE, Fisher info, proportion CIs | +5 |\n\n**General grading principles:**\n\n- Carry-forward credit throughout: correct application of an incorrect earlier answer receives\n  full credit on subsequent parts.\n- Problems 2 and 3 carry the most theory weight (post-midterm material); grade carefully.\n- Partial credit for correct setup without completing calculation.\n- Accept equivalent valid approaches (e.g., normal approximation vs. exact binomial in\n  Problem 2; any valid permutation statistic in Problem 4e).\n- Problem 5b: students are instructed to show the formula, not use `t.test()` output.\n  Deduct 1 pt if only R output is shown without the formula.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}