{
  "hash": "442c96013043e1ca2a24c2c9b31be9ff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 18: Two-Sample Confidence Intervals and Tests\"\nsubtitle: \"BSTA 551: Statistical Inference\"\nauthor: \"Jessica Minnier\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2026-03-02\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    scrollable: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 18 - Two-Sample Inference\n    html-math-method: mathjax\n    highlight-style: atom-one\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n# Lesson 18: Two-Sample Inference {background-color=\"#2c3e50\"}\n\n## Review: Where We Left Off\n\n**Lessons 15–17: Hypothesis Testing**\n\n- Neyman-Pearson Lemma: MP tests via likelihood ratio\n- Likelihood Ratio Tests (LRT) for composite hypotheses\n- Bootstrap hypothesis tests: shift data to $H_0$, approximate null distribution\n\n. . .\n\n**Today's Goals:**\n\n1. Extend one-sample inference to **two independent samples**\n2. Derive and apply the two-sample **z-test and CI** for means ($\\sigma$ known)\n3. Derive and apply the **Welch t-test** and **pooled t-test** ($\\sigma$ unknown)\n4. Extend to **binary outcomes**: CIs and tests for $p_1 - p_2$\n5. Derive the **F-distribution** and test for $\\sigma_1^2/\\sigma_2^2$\n6. Apply all methods to medical research examples\n\n## Roadmap\n\n| Parameter | Setting | Method | Reference |\n|-----------|---------|--------|-----------|\n| $\\mu_1 - \\mu_2$ | $\\sigma_1^2, \\sigma_2^2$ known | Two-sample $z$ | DBC 9.5 |\n| $\\mu_1 - \\mu_2$ | $\\sigma_1^2 \\neq \\sigma_2^2$ unknown | Welch $t$ | DBC 9.5 |\n| $\\mu_1 - \\mu_2$ | $\\sigma_1^2 = \\sigma_2^2$ unknown | Pooled $t$ | DBC 9.5 |\n| $p_1 - p_2$ | Large samples | $z$-test / Wald CI | DBC 9.6 |\n| $\\sigma_1^2 / \\sigma_2^2$ | Normal populations | $F$-test | DBC 9.6 |\n\n. . .\n\n::: callout-note\n## Motivating Context\nAll of these settings arise constantly in medical research: comparing treatment vs. control on a continuous biomarker, comparing adverse event rates between arms, comparing lab variability between sites.\n:::\n\n# Two-Sample Setup and Point Estimation {background-color=\"#3498db\"}\n\n## The Two-Sample Model\n\n**Setup:** Two independent random samples from possibly different populations:\n\n$$X_{11}, X_{12}, \\ldots, X_{1n_1} \\stackrel{iid}{\\sim} F_1 \\quad \\text{with mean } \\mu_1, \\text{ variance } \\sigma_1^2$$\n\n$$X_{21}, X_{22}, \\ldots, X_{2n_2} \\stackrel{iid}{\\sim} F_2 \\quad \\text{with mean } \\mu_2, \\text{ variance } \\sigma_2^2$$\n\nThe two samples are **independent of each other**.\n\n. . .\n\n**Parameter of interest:** $\\Delta = \\mu_1 - \\mu_2$\n\n**Point estimator:** $\\hat{\\Delta} = \\bar{X}_1 - \\bar{X}_2$\n\n. . .\n\n**Properties of $\\hat{\\Delta}$:**\n\n- $E[\\bar{X}_1 - \\bar{X}_2] = \\mu_1 - \\mu_2 \\Rightarrow$ **unbiased**\n- $\\text{Var}(\\bar{X}_1 - \\bar{X}_2) = \\dfrac{\\sigma_1^2}{n_1} + \\dfrac{\\sigma_2^2}{n_2}$ (by independence)\n- $\\text{SE}(\\bar{X}_1 - \\bar{X}_2) = \\sqrt{\\dfrac{\\sigma_1^2}{n_1} + \\dfrac{\\sigma_2^2}{n_2}}$\n\n## Why Is $\\bar{X}_1 - \\bar{X}_2$ Approximately Normal? {.smaller}\n\n**Case 1: Both populations are normal** — exact result for any $n_1, n_2$:\n\n$$\\bar{X}_1 \\sim N\\!\\left(\\mu_1, \\frac{\\sigma_1^2}{n_1}\\right), \\quad \\bar{X}_2 \\sim N\\!\\left(\\mu_2, \\frac{\\sigma_2^2}{n_2}\\right)$$\n\nA linear combination of independent normals is normal, so $\\bar{X}_1 - \\bar{X}_2 \\sim N\\!\\left(\\mu_1-\\mu_2,\\; \\sigma_1^2/n_1 + \\sigma_2^2/n_2\\right)$ exactly.\n\n. . .\n\n**Case 2: Non-normal populations, large $n_1$ and $n_2$** — CLT applies *separately* to each sample mean:\n\n$$\\bar{X}_1 = \\frac{1}{n_1}\\sum_{j=1}^{n_1} X_{1j} \\;\\dot{\\sim}\\; N\\!\\left(\\mu_1, \\frac{\\sigma_1^2}{n_1}\\right) \\quad \\text{(CLT, as } n_1 \\to \\infty\\text{)}$$\n\n$$\\bar{X}_2 = \\frac{1}{n_2}\\sum_{j=1}^{n_2} X_{2j} \\;\\dot{\\sim}\\; N\\!\\left(\\mu_2, \\frac{\\sigma_2^2}{n_2}\\right) \\quad \\text{(CLT, as } n_2 \\to \\infty\\text{)}$$\n\nBecause the two samples are **independent**, $\\bar{X}_1 - \\bar{X}_2$ is a sum of two asymptotically independent normal quantities:\n\n$$\\bar{X}_1 - \\bar{X}_2 \\;\\dot{\\sim}\\; N\\!\\left(\\mu_1 - \\mu_2,\\; \\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}\\right)$$\n\n. . .\n\n::: callout-note\nBoth $n_1$ and $n_2$ must be large — if one is small, the CLT approximation may be poor for that group, undermining the overall approximation. A common rule of thumb is $n_1 \\geq 30$ and $n_2 \\geq 30$.\n:::\n\n## The Pivot: Standardizing the Difference\n\nIn either case (exact or approximate), after standardizing:\n\n$$Z = \\frac{(\\bar{X}_1 - \\bar{X}_2) - (\\mu_1 - \\mu_2)}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}} \\;\\sim\\; N(0,1)$$\n\nThis is a **pivotal quantity** when $\\sigma_1^2$ and $\\sigma_2^2$ are known — its distribution does not depend on any unknown parameters.\n\n. . .\n\nWe can invert it to get a CI, just as in the one-sample case:\n\n$$P\\!\\left(-z_{\\alpha/2} \\leq \\frac{(\\bar{X}_1-\\bar{X}_2)-\\Delta}{\\sqrt{\\sigma_1^2/n_1+\\sigma_2^2/n_2}} \\leq z_{\\alpha/2}\\right) = 1-\\alpha$$\n\n$$\\Rightarrow \\quad (\\bar{X}_1 - \\bar{X}_2) \\pm z_{\\alpha/2}\\sqrt{\\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}}$$\n\n# Two-Sample z-Procedures ($\\sigma$ Known) {background-color=\"#e74c3c\"}\n\n## Two-Sample z-Test and CI (DBC 9.5)\n\n**Two-sample z-test** of $H_0: \\mu_1 - \\mu_2 = \\Delta_0$:\n\n$$Z = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}}$$\n\nReject $H_0$ at level $\\alpha$:\n\n| Alternative | Rejection Region |\n|-------------|-----------------|\n| $\\mu_1 - \\mu_2 > \\Delta_0$ | $Z > z_\\alpha$ |\n| $\\mu_1 - \\mu_2 < \\Delta_0$ | $Z < -z_\\alpha$ |\n| $\\mu_1 - \\mu_2 \\neq \\Delta_0$ | $|Z| > z_{\\alpha/2}$ |\n\n**Two-sample z-CI** (95%, two-sided):\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm z_{\\alpha/2} \\sqrt{\\frac{\\sigma_1^2}{n_1} + \\frac{\\sigma_2^2}{n_2}}$$\n\n## Medical Example: Two-Sample z-Test\n\n**Study:** A pilot study compares mean serum cortisol ($\\mu$g/dL) between ICU patients with sepsis ($n_1 = 30$, known $\\sigma_1 = 6$) and non-septic ICU controls ($n_2 = 35$, known $\\sigma_2 = 5$). Observed: $\\bar{x}_1 = 28.4$, $\\bar{x}_2 = 22.1$. Test $H_0: \\mu_1 = \\mu_2$ vs. $H_a: \\mu_1 > \\mu_2$ at $\\alpha = 0.05$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nxbar1 <- 28.4; xbar2 <- 22.1\nsigma1 <- 6;   sigma2 <- 5\nn1 <- 30;      n2 <- 35\n\nse_diff <- sqrt(sigma1^2/n1 + sigma2^2/n2)\nz_obs   <- (xbar1 - xbar2) / se_diff\np_value <- pnorm(z_obs, lower.tail = FALSE)  # one-sided\n\nz_crit <- qnorm(0.975)\nci_lo  <- (xbar1 - xbar2) - z_crit * se_diff\nci_hi  <- (xbar1 - xbar2) + z_crit * se_diff\n\ncat(\"SE:\", round(se_diff, 3), \"| Z:\", round(z_obs, 3),\n    \"| One-sided p:\", round(p_value, 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE: 1.384 | Z: 4.553 | One-sided p: 0 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"95% CI for mu1 - mu2: (\", round(ci_lo, 2), \",\", round(ci_hi, 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for mu1 - mu2: ( 3.59 , 9.01 )\n```\n\n\n:::\n:::\n\n\n**Conclusion:** $Z = 4.55$, $p < 0.001$. Strong evidence that septic ICU patients have higher mean cortisol.\n\n# Two-Sample t-Procedures ($\\sigma$ Unknown) {background-color=\"#27ae60\"}\n\n## The Behrens-Fisher Problem\n\nIn practice $\\sigma_1^2$ and $\\sigma_2^2$ are **rarely known**. Replacing them with sample variances $S_1^2$, $S_2^2$ gives the statistic:\n\n$$T = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{\\sqrt{S_1^2/n_1 + S_2^2/n_2}}$$\n\n**Problem:** $T$ does **not** follow an exact $t$ distribution when $\\sigma_1^2 \\neq \\sigma_2^2$ — the numerator and denominator are not independent in the way needed for an exact $t$ pivot. This is the **Behrens-Fisher problem**.\n\n. . .\n\n**Two solutions:**\n\n| Approach | Assumption | Null distribution |\n|----------|-----------|------------------|\n| Welch (Satterthwaite) | $\\sigma_1^2 \\neq \\sigma_2^2$ allowed | $T \\approx t_{\\hat\\nu}$ |\n| Pooled | $\\sigma_1^2 = \\sigma_2^2 = \\sigma^2$ required | $T_P \\sim t_{n_1+n_2-2}$ (exact) |\n\n## Welch's t-Test — Recommended Default (DBC 9.5)\n\n**Welch's t-statistic:**\n$$T_W = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{\\sqrt{S_1^2/n_1 + S_2^2/n_2}}$$\n\nUnder $H_0$, $T_W \\approx t_{\\hat\\nu}$ where the **Welch-Satterthwaite degrees of freedom** are:\n\n$$\\hat\\nu = \\frac{(S_1^2/n_1 + S_2^2/n_2)^2}{\\dfrac{(S_1^2/n_1)^2}{n_1-1} + \\dfrac{(S_2^2/n_2)^2}{n_2-1}}$$\n\nNote: $\\hat\\nu$ is always between $\\min(n_1, n_2)-1$ and $n_1+n_2-2$.\n\n. . .\n\n**Welch 95% CI for $\\mu_1 - \\mu_2$:**\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm t_{\\alpha/2,\\,\\hat\\nu}\\,\\sqrt{\\frac{S_1^2}{n_1} + \\frac{S_2^2}{n_2}}$$\n\n::: callout-important\n## Why Welch?\nThe Welch test is robust to unequal variances and performs well even when $\\sigma_1^2 = \\sigma_2^2$. It is the **default in R's `t.test()`** and recommended by most statisticians as the standard two-sample test.\n:::\n\n## The Pooled t-Test (DBC 9.5)\n\nWhen $\\sigma_1^2 = \\sigma_2^2 = \\sigma^2$ (equal variances assumed), we estimate the common variance by pooling:\n\n$$S_p^2 = \\frac{(n_1-1)S_1^2 + (n_2-1)S_2^2}{n_1 + n_2 - 2}$$\n\n$S_p^2$ is an unbiased estimator of $\\sigma^2$ and uses all $n_1 + n_2 - 2$ degrees of freedom.\n\n**Pooled t-statistic:**\n$$T_P = \\frac{(\\bar{X}_1 - \\bar{X}_2) - \\Delta_0}{S_p\\sqrt{1/n_1 + 1/n_2}} \\sim t_{n_1+n_2-2} \\quad \\text{(exact under normality + equal } \\sigma^2\\text{)}$$\n\n**Pooled 95% CI:**\n$$(\\bar{X}_1 - \\bar{X}_2) \\pm t_{\\alpha/2,\\,n_1+n_2-2}\\;S_p\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}$$\n\n::: callout-warning\n## When to Use Pooled t\nOnly use the pooled t when there is **strong prior subject-matter reason** to believe $\\sigma_1^2 = \\sigma_2^2$. Do **not** use an F-test on the same data to justify pooling — this inflates Type I error.\n:::\n\n## Why the Direction of Bias Matters\n\nWhen $\\sigma_1^2 \\neq \\sigma_2^2$, $S_p^2$ is a weighted average of two estimators targeting *different* quantities. The pooled SE can be either too big or too small:\n\n$$S_p^2 = \\frac{(n_1-1)S_1^2 + (n_2-1)S_2^2}{n_1+n_2-2} \\approx \\frac{(n_1-1)\\sigma_1^2 + (n_2-1)\\sigma_2^2}{n_1+n_2-2}$$\n\nThe **true** SE of $\\bar{X}_1 - \\bar{X}_2$ is $\\sqrt{\\sigma_1^2/n_1 + \\sigma_2^2/n_2}$. Whether the pooled SE over- or underestimates this depends on the $n$–$\\sigma$ relationship:\n\n| Configuration | Pooled SE vs. true SE | Pooled test |\n|---------------|-----------------------|-------------|\n| $n_1 = n_2$ (balanced) | Approximately correct regardless of $\\sigma_1 \\neq \\sigma_2$ | $\\approx$ 5% |\n| Larger group has **larger** $\\sigma$ (Scenario 3 below) | Pooled SE **too large** → $T$ deflated | **Conservative** (< 5%) |\n| Larger group has **smaller** $\\sigma$ (Scenario 4 below) | Pooled SE **too small** → $T$ inflated | **Anti-conservative** (> 5%) |\n\n. . .\n\n::: callout-note\nThe Welch test is robust to all of these scenarios because it uses $S_1^2/n_1 + S_2^2/n_2$ directly without pooling.\n:::\n\n## Welch vs. Pooled: Type I Error Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\nsim_ttest <- function(n1, n2, sigma1, sigma2, B = 3000) {\n  map_dfr(1:B, function(i) {\n    x1 <- rnorm(n1, mean = 0, sd = sigma1)\n    x2 <- rnorm(n2, mean = 0, sd = sigma2)\n    tibble(\n      p_welch  = t.test(x1, x2, var.equal = FALSE)$p.value,\n      p_pooled = t.test(x1, x2, var.equal = TRUE)$p.value\n    )\n  })\n}\n\n# Compute true SE and pooled-approx SE for annotation\ntrue_se   <- function(n1, n2, s1, s2) sqrt(s1^2/n1 + s2^2/n2)\npooled_se <- function(n1, n2, s1, s2) {\n  sp <- sqrt(((n1-1)*s1^2 + (n2-1)*s2^2) / (n1+n2-2))\n  sp * sqrt(1/n1 + 1/n2)\n}\n\nscenarios <- tibble(\n  n1     = c(20, 20, 10, 30),\n  n2     = c(20, 20, 30, 10),\n  sigma1 = c( 2,  1,  1,  1),\n  sigma2 = c( 2,  3,  3,  3),\n  label  = c(\n    \"Equal n, equal variances\\nn1=n2=20, s1=s2=2\",\n    \"Equal n, unequal variances\\nn1=n2=20, s1=1, s2=3\",\n    \"Larger group has larger variance\\nn1=10, n2=30, s1=1, s2=3\",\n    \"Larger group has smaller variance\\nn1=30, n2=10, s1=1, s2=3\"\n  )\n)\n\nresults <- pmap_dfr(scenarios, function(n1, n2, sigma1, sigma2, label) {\n  sim_ttest(n1, n2, sigma1, sigma2) |>\n    summarise(Welch  = mean(p_welch  < 0.05),\n              Pooled = mean(p_pooled < 0.05)) |>\n    mutate(\n      Scenario  = label,\n      true_se   = true_se(n1, n2, sigma1, sigma2),\n      pooled_se = pooled_se(n1, n2, sigma1, sigma2),\n      se_bias   = case_when(\n        abs(pooled_se - true_se) < 0.02 ~ \"Pooled SE ~ True SE\",\n        pooled_se > true_se             ~ \"Pooled SE too LARGE\\n(conservative)\",\n        TRUE                            ~ \"Pooled SE too SMALL\\n(anti-conservative)\"\n      )\n    )\n})\n\n# Annotation data: only label the pooled bar\npooled_annot <- results |>\n  select(Scenario, se_bias) |>\n  mutate(Test = \"Pooled\", x_pos = 1)\n\nplot_data <- results |>\n  pivot_longer(c(Welch, Pooled), names_to = \"Test\", values_to = \"TypeI\")\n\nggplot(plot_data, aes(x = Test, y = TypeI, fill = Test)) +\n  geom_col(width = 0.5) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", linewidth = 1.2) +\n  geom_text(\n    data = filter(plot_data, Test == \"Pooled\"),\n    aes(label = se_bias, y = TypeI + 0.008),\n    color = \"#c0392b\", size = 3.5, lineheight = 0.9\n  ) +\n  scale_fill_manual(values = c(\"Welch\" = \"#006a4e\", \"Pooled\" = \"#e74c3c\")) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.30),\n                     expand = expansion(mult = c(0, 0.05))) +\n  facet_wrap(~Scenario, nrow = 1) +\n  labs(\n    title    = \"Type I Error Rate: Welch vs. Pooled t-test  (nominal alpha = 5%)\",\n    subtitle = paste0(\n      \"Pooled test can be conservative OR anti-conservative depending on which group has the larger variance.\\n\",\n      \"Welch test stays near 5% in all scenarios.\"\n    ),\n    x = NULL, y = \"Type I Error Rate\", fill = \"Method\"\n  ) +\n  theme(legend.position = \"bottom\",\n        strip.text    = element_text(size = 10),\n        axis.text.x   = element_blank(),\n        axis.ticks.x  = element_blank())\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-2-1.png){width=1536}\n:::\n:::\n\n\n## Medical Example: Welch t-Test in R\n\n**RCT:** A randomized trial compares 12-week LDL cholesterol reduction (mg/dL) between a statin ($n_1 = 45$) and placebo ($n_2 = 43$).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(42)\nldl_drug    <- rnorm(45, mean = 32, sd = 18)\nldl_placebo <- rnorm(43, mean =  8, sd = 12)\n\n# Welch t-test (R default)\nresult_welch <- t.test(ldl_drug, ldl_placebo,\n                       alternative = \"two.sided\", conf.level = 0.95)\ntidy(result_welch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic    p.value parameter conf.low conf.high\n     <dbl>     <dbl>     <dbl>     <dbl>      <dbl>     <dbl>    <dbl>     <dbl>\n1     21.3      30.8      9.52      5.97    1.08e-7      65.6     14.1      28.4\n# ℹ 2 more variables: method <chr>, alternative <chr>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Store for use below\nci_result <- result_welch\ncat(\"Welch df:\", round(ci_result$parameter, 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWelch df: 65.6 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"Mean difference:\", round(diff(rev(ci_result$estimate)), 2), \"mg/dL\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean difference: 21.25 mg/dL\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"95% CI: (\", round(ci_result$conf.int[1], 2), \",\",\n                  round(ci_result$conf.int[2], 2), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: ( 14.14 , 28.37 )\n```\n\n\n:::\n:::\n\n\n## Visualizing the LDL Data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(\n  reduction = c(ldl_drug, ldl_placebo),\n  group     = rep(c(\"Statin\", \"Placebo\"), c(45, 43))\n) |>\n  ggplot(aes(x = group, y = reduction, fill = group)) +\n  geom_boxplot(alpha = 0.7, width = 0.4, outlier.shape = 1) +\n  geom_jitter(width = 0.12, alpha = 0.4, size = 1.8) +\n  stat_summary(fun = mean, geom = \"point\", shape = 18,\n               size = 5, color = \"black\") +\n  scale_fill_manual(values = c(\"Statin\" = \"#006a4e\", \"Placebo\" = \"#3498db\")) +\n  labs(title = \"LDL Cholesterol Reduction by Treatment Group\",\n       subtitle = \"Diamond = group mean. Welch two-sample t-test.\",\n       x = NULL, y = \"LDL Reduction (mg/dL)\", fill = NULL) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-5-1.png){width=1056}\n:::\n:::\n\n\n**Interpretation:** The statin reduces LDL by approximately 21.3 mg/dL more than placebo (95% CI: 14.1 to 28.4 mg/dL, $p < 0.001$, Welch t-test, df = 65.6).\n\n## Pooled t-Test: DBC Example\n\n**DBC 9.5:** Two care groups measured for systolic blood pressure (mmHg). Prior clinical knowledge supports equal variability.\n\n- Standard care: $n_1 = 12$, $\\bar{x}_1 = 140.2$, $s_1 = 14.3$\n- Intensive care: $n_2 = 10$, $\\bar{x}_2 = 128.7$, $s_2 = 13.8$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nn1 <- 12; xbar1 <- 140.2; s1 <- 14.3\nn2 <- 10; xbar2 <- 128.7; s2 <- 13.8\n\nsp2 <- ((n1-1)*s1^2 + (n2-1)*s2^2) / (n1 + n2 - 2)\nsp  <- sqrt(sp2)\n\nt_obs <- (xbar1 - xbar2) / (sp * sqrt(1/n1 + 1/n2))\ndf    <- n1 + n2 - 2\np_val <- 2 * pt(abs(t_obs), df = df, lower.tail = FALSE)\nt_crit <- qt(0.975, df = df)\nmargin <- t_crit * sp * sqrt(1/n1 + 1/n2)\n\ncat(sprintf(\"Sp = %.2f,  df = %d\\n\", sp, df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSp = 14.08,  df = 20\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"T_obs = %.3f,  p-value = %.4f\\n\", t_obs, p_val))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT_obs = 1.908,  p-value = 0.0709\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"95%% CI: (%.2f, %.2f)\\n\",\n            xbar1 - xbar2 - margin, xbar1 - xbar2 + margin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: (-1.07, 24.07)\n```\n\n\n:::\n:::\n\n\n**Conclusion:** $t = 1.908$, $df = 20$, $p = 0.0709$. Reject $H_0$ at $\\alpha = 0.05$; evidence of a difference in systolic BP between care groups.\n\n## When Do Welch and Pooled t-Distributions Differ?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Scenario A: similar n and similar s (Welch ~ Pooled)\nnA1 <- 45; nA2 <- 43; sA1 <- 18; sA2 <- 12\nnuA_welch  <- (sA1^2/nA1 + sA2^2/nA2)^2 /\n              ((sA1^2/nA1)^2/(nA1-1) + (sA2^2/nA2)^2/(nA2-1))\nnuA_pooled <- nA1 + nA2 - 2\n\n# Scenario B: very unequal n and s (Welch << Pooled)\nnB1 <- 8;  nB2 <- 40; sB1 <- 15; sB2 <- 3\nnuB_welch  <- (sB1^2/nB1 + sB2^2/nB2)^2 /\n              ((sB1^2/nB1)^2/(nB1-1) + (sB2^2/nB2)^2/(nB2-1))\nnuB_pooled <- nB1 + nB2 - 2\n\nt_grid <- seq(-5, 5, length.out = 600)\n\nmake_df <- function(nu_w, nu_p, label) {\n  bind_rows(\n    tibble(t = t_grid,\n           density = dt(t_grid, df = nu_w),\n           Method  = sprintf(\"Welch (df=%.1f)\", nu_w)),\n    tibble(t = t_grid,\n           density = dt(t_grid, df = nu_p),\n           Method  = sprintf(\"Pooled (df=%d)\", nu_p))\n  ) |> mutate(Scenario = label)\n}\n\ndf_both <- bind_rows(\n  make_df(nuA_welch, nuA_pooled,\n          sprintf(\"Scenario A: balanced, similar variances\\nn1=%d, n2=%d, s1=%.0f, s2=%.0f\",\n                  nA1, nA2, sA1, sA2)),\n  make_df(nuB_welch, nuB_pooled,\n          sprintf(\"Scenario B: small n1, very unequal variances\\nn1=%d, n2=%d, s1=%.0f, s2=%.0f\",\n                  nB1, nB2, sB1, sB2))\n)\n\n# Show T_obs = 2 in each panel (representative value in rejection region)\nt_ref <- 2.0\n\nggplot(df_both, aes(x = t, y = density, color = Method, linetype = Method)) +\n  geom_line(linewidth = 1.5) +\n  geom_vline(xintercept = c(-t_ref, t_ref), color = \"#e74c3c\",\n             linewidth = 1.1, linetype = \"dotted\") +\n  annotate(\"text\", x = t_ref + 0.15, y = 0.37,\n           label = paste0(\"T = \", t_ref),\n           color = \"#e74c3c\", size = 5, hjust = 0) +\n  facet_wrap(~Scenario) +\n  scale_color_manual(values    = c(\"#006a4e\", \"#e74c3c\",\n                                   \"#3498db\", \"#9b59b6\")) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\",\n                                   \"solid\", \"dashed\")) +\n  labs(\n    title    = \"Welch vs. Pooled t-Distributions: When Do They Differ?\",\n    subtitle = paste0(\"Scenario A: nearly identical distributions — pooled and Welch agree.\\n\",\n                      \"Scenario B: small n1 with large s1 → Welch df much smaller → heavier tails → larger p-values\"),\n    x = \"t\", y = \"Density\", color = NULL, linetype = NULL\n  ) +\n  theme(legend.position = \"bottom\",\n        strip.text = element_text(size = 12))\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-7-1.png){width=1536}\n:::\n:::\n\n\n## Sample Size for Two-Sample t-Test\n\nFor a two-sided test at level $\\alpha$, power $1-\\beta$, to detect $|\\mu_1 - \\mu_2| = \\delta$ (assuming $\\sigma_1 = \\sigma_2 = \\sigma$, $n_1 = n_2 = n$):\n\n$$n \\approx \\frac{2\\sigma^2(z_{\\alpha/2} + z_\\beta)^2}{\\delta^2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Detect 10 mmHg SBP difference; sigma = 15; 90% power; alpha = 0.05\nsigma <- 15; delta <- 10; alpha <- 0.05; power <- 0.90\n\nn_approx <- ceiling(2 * sigma^2 * (qnorm(1-alpha/2) + qnorm(power))^2 / delta^2)\ncat(\"Formula approximation, n per arm:\", n_approx, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFormula approximation, n per arm: 48 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\npower.t.test(delta = delta, sd = sigma, sig.level = alpha,\n             power = power, type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 48.26431\n          delta = 10\n             sd = 15\n      sig.level = 0.05\n          power = 0.9\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n## Summary: Which Two-Sample Test?\n\n| Condition | Method | Degrees of Freedom |\n|-----------|--------|-------------------|\n| $\\sigma_1^2, \\sigma_2^2$ known; large $n$ or normal | Two-sample $z$ | $\\infty$ (use $z_{\\alpha/2}$) |\n| $\\sigma_1^2 \\neq \\sigma_2^2$, unknown **(default)** | **Welch $t$** | $\\hat\\nu$ (Satterthwaite) |\n| $\\sigma_1^2 = \\sigma_2^2$, strong prior knowledge | Pooled $t$ | $n_1 + n_2 - 2$ |\n| Non-normal, small $n$ | Bootstrap or Wilcoxon rank-sum | — |\n\n. . .\n\n::: callout-important\n## Rules of Thumb\n- **Default:** Use Welch. It performs well whether or not variances are equal.\n- **Pooled:** Only when there is strong external (prior) subject-matter justification for equal variances — not based on testing the same data.\n- **Checking normality:** Plot the data (histogram, Q-Q plot). For $n_i \\geq 30$, the CLT provides protection; for small $n$, departures from normality matter more.\n:::\n\n# Two-Sample Inference for Proportions (DBC 9.6) {background-color=\"#e74c3c\"}\n\n## Setup: Two Independent Bernoulli Samples\n\n**Group 1:** $X_{11}, \\ldots, X_{1n_1} \\stackrel{iid}{\\sim} \\text{Bernoulli}(p_1)$; count $Y_1 \\sim \\text{Bin}(n_1, p_1)$\n\n**Group 2:** $X_{21}, \\ldots, X_{2n_2} \\stackrel{iid}{\\sim} \\text{Bernoulli}(p_2)$; count $Y_2 \\sim \\text{Bin}(n_2, p_2)$\n\n**Parameter of interest:** $\\Delta = p_1 - p_2$. **Estimator:** $\\hat\\Delta = \\hat{p}_1 - \\hat{p}_2 = Y_1/n_1 - Y_2/n_2$\n\n. . .\n\n**Why CLT applies:** Each $\\hat{p}_i = Y_i/n_i$ is a sample mean of iid $\\text{Bernoulli}(p_i)$ observations. By CLT:\n\n$$\\hat{p}_i = \\frac{1}{n_i}\\sum_{j=1}^{n_i} X_{ij} \\;\\dot{\\sim}\\; N\\!\\left(p_i,\\; \\frac{p_i(1-p_i)}{n_i}\\right) \\quad \\text{for large } n_i$$\n\nSince the groups are independent, the difference of two approximately normal quantities is approximately normal:\n\n$$\\hat{p}_1 - \\hat{p}_2 \\;\\dot{\\sim}\\; N\\!\\left(p_1 - p_2,\\; \\frac{p_1(1-p_1)}{n_1} + \\frac{p_2(1-p_2)}{n_2}\\right)$$\n\n. . .\n\n::: callout-note\n## Large-Sample Condition\nThe normal approximation is adequate when $n_i\\hat{p}_i \\geq 5$ and $n_i(1-\\hat{p}_i) \\geq 5$ for both $i = 1, 2$.\nFor rare events or small $n$, use **Fisher's exact test** or a **bootstrap CI**.\n:::\n\n## CI and Test for $p_1 - p_2$ (DBC 9.6)\n\n**Wald CI** (plug in $\\hat{p}_1, \\hat{p}_2$ for unknown $p_1, p_2$):\n$$(\\hat{p}_1 - \\hat{p}_2) \\pm z_{\\alpha/2} \\sqrt{\\frac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}}$$\n\n**Hypothesis test** of $H_0: p_1 = p_2$: Under $H_0$ both groups share a common $p$. Estimate it as $\\hat{p} = (Y_1 + Y_2)/(n_1 + n_2)$ — the **pooled proportion**.\n\n**Pooled z-statistic:**\n$$Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1-\\hat{p})\\left(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\right)}}$$\n\n. . .\n\n::: callout-important\n## Pooled vs. Unpooled SE\n- **Test:** Use **pooled** $\\hat{p}$ — $H_0$ says $p_1 = p_2$, so exploit that constraint.\n- **CI:** Use **unpooled** $\\hat{p}_1, \\hat{p}_2$ — the CI makes no assumption about $p_1 = p_2$.\n:::\n\n## Medical Example: Adverse Event Rates\n\n**Clinical Trial:** A drug trial compares 30-day SAE rates: treatment ($n_1 = 150$, $y_1 = 12$) vs. control ($n_2 = 148$, $y_2 = 24$). Test $H_0: p_1 = p_2$ and construct a 95% CI.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nn1 <- 150; y1 <- 12\nn2 <- 148; y2 <- 24\n\np1_hat <- y1/n1; p2_hat <- y2/n2\np_pool <- (y1 + y2) / (n1 + n2)\n\n# Test (pooled SE)\nse_pool <- sqrt(p_pool*(1-p_pool)*(1/n1 + 1/n2))\nz_stat  <- (p1_hat - p2_hat) / se_pool\np_val   <- 2 * pnorm(abs(z_stat), lower.tail = FALSE)\n\n# 95% CI (unpooled SE)\nse_ci <- sqrt(p1_hat*(1-p1_hat)/n1 + p2_hat*(1-p2_hat)/n2)\nci    <- (p1_hat - p2_hat) + c(-1, 1) * qnorm(0.975) * se_ci\n\ncat(sprintf(\"p1_hat = %.4f | p2_hat = %.4f | pooled p = %.4f\\n\",\n            p1_hat, p2_hat, p_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np1_hat = 0.0800 | p2_hat = 0.1622 | pooled p = 0.1208\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"Z = %.3f | p-value = %.4f\\n\", z_stat, p_val))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZ = -2.176 | p-value = 0.0296\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"95%% CI for p1-p2: (%.4f, %.4f)\\n\", ci[1], ci[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for p1-p2: (-0.1557, -0.0086)\n```\n\n\n:::\n:::\n\n\n## Compare with prop.test(), and Visualize\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nprop.test(c(y1, y2), c(n1, n2), correct = FALSE) |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 9\n  estimate1 estimate2 statistic p.value parameter conf.low conf.high method     \n      <dbl>     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      \n1      0.08     0.162      4.73  0.0296         1   -0.156  -0.00860 2-sample t…\n# ℹ 1 more variable: alternative <chr>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntribble(\n  ~Group,       ~rate,   ~n,\n  \"Treatment\",  p1_hat,  n1,\n  \"Control\",    p2_hat,  n2\n) |>\n  mutate(\n    se = sqrt(rate*(1-rate)/n),\n    lo = rate - qnorm(0.975)*se,\n    hi = rate + qnorm(0.975)*se\n  ) |>\n  ggplot(aes(x = Group, y = rate, color = Group)) +\n  geom_point(size = 6) +\n  geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.08, linewidth = 1.3) +\n  scale_color_manual(values = c(\"Treatment\" = \"#006a4e\", \"Control\" = \"#e74c3c\")) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.25)) +\n  labs(title = \"30-Day SAE Rate by Treatment Arm\",\n       subtitle = \"Points: estimated rates; bars: 95% Wald CIs\",\n       x = NULL, y = \"SAE Rate\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-11-1.png){width=864}\n:::\n:::\n\n\n## Relative Risk and Odds Ratio\n\nThe difference $p_1 - p_2$ (risk difference) is one effect measure. Medical research often reports:\n\n$$\\text{Relative Risk (RR)} = \\frac{p_1}{p_2}, \\qquad \\text{Odds Ratio (OR)} = \\frac{p_1/(1-p_1)}{p_2/(1-p_2)}$$\n\nCIs for RR and OR are constructed on the log scale (approximately normal), then back-transformed.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nRR <- p1_hat / p2_hat\nOR <- (p1_hat/(1-p1_hat)) / (p2_hat/(1-p2_hat))\n\n# Delta-method SE on log scale\nse_logRR <- sqrt(1/y1 - 1/n1 + 1/y2 - 1/n2)\nse_logOR <- sqrt(1/y1 + 1/(n1-y1) + 1/y2 + 1/(n2-y2))\n\ncat(sprintf(\"RR = %.3f  (95%% CI: %.3f, %.3f)\\n\",\n    RR, exp(log(RR) - 1.96*se_logRR), exp(log(RR) + 1.96*se_logRR)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRR = 0.493  (95% CI: 0.256, 0.949)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"OR = %.3f  (95%% CI: %.3f, %.3f)\\n\",\n    OR, exp(log(OR) - 1.96*se_logOR), exp(log(OR) + 1.96*se_logOR)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOR = 0.449  (95% CI: 0.216, 0.936)\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Interpretation:** The treatment arm had approximately half the SAE rate of control (RR ≈ 0.49). When $p$ is small, RR $\\approx$ OR; they diverge as event rates increase.\n\n# Inferences About Two Variances (DBC 9.6) {background-color=\"#9b59b6\"}\n\n## The F-Distribution\n\nWhen comparing variability between two groups, we need the **F-distribution**.\n\n**Key result:** If $U \\sim \\chi^2_m$ and $V \\sim \\chi^2_n$ are independent, then:\n$$F = \\frac{U/m}{V/n} \\sim F_{m,n}$$\n\nConnection to sample variances: Under normality, $(n_i-1)S_i^2/\\sigma_i^2 \\sim \\chi^2_{n_i-1}$ independently, so:\n\n$$F = \\frac{S_1^2/\\sigma_1^2}{S_2^2/\\sigma_2^2} \\sim F_{n_1-1,\\;n_2-1}$$\n\nUnder $H_0: \\sigma_1^2 = \\sigma_2^2$, the ratio simplifies to $F = S_1^2/S_2^2$.\n\n. . .\n\n**Properties of $F_{m,n}$:**\n\n- Support: $(0, \\infty)$; right-skewed for small $m, n$\n- $E[F] = n/(n-2)$ for $n > 2$\n- **Reciprocal:** if $F \\sim F_{m,n}$ then $1/F \\sim F_{n,m}$\n- Critical values in R: `qf(p, df1, df2)`\n\n## F-Distribution Shape\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nx_f <- seq(0.01, 6, length.out = 500)\n\nexpand_grid(\n  x   = x_f,\n  df1 = c(1, 5, 10, 20)\n) |>\n  mutate(\n    density = df(x, df1 = df1, df2 = df1),\n    label   = paste0(\"F(\", df1, \",\", df1, \")\")\n  ) |>\n  ggplot(aes(x = x, y = density, color = label)) +\n  geom_line(linewidth = 1.4) +\n  scale_color_brewer(palette = \"Dark2\") +\n  coord_cartesian(ylim = c(0, 1.2)) +\n  labs(\n    title    = \"F-Distribution for Various Degrees of Freedom  (df1 = df2)\",\n    subtitle = \"As degrees of freedom increase, the F-distribution concentrates near 1\",\n    x        = \"f\",\n    y        = \"Density\",\n    color    = \"Distribution\"\n  ) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-13-1.png){width=1248}\n:::\n:::\n\n\n## F-Test for $H_0: \\sigma_1^2 = \\sigma_2^2$ (DBC 9.6)\n\n**Test statistic:** $f = s_1^2/s_2^2$; under $H_0$, $F = S_1^2/S_2^2 \\sim F_{n_1-1,\\,n_2-1}$\n\n| Alternative | Rejection Region | p-value |\n|-------------|-----------------|---------|\n| $\\sigma_1^2 > \\sigma_2^2$ | $f > F_{\\alpha,\\,n_1-1,\\,n_2-1}$ | $P(F \\geq f)$ |\n| $\\sigma_1^2 < \\sigma_2^2$ | $f < F_{1-\\alpha,\\,n_1-1,\\,n_2-1}$ | $P(F \\leq f)$ |\n| $\\sigma_1^2 \\neq \\sigma_2^2$ | $f < F_{1-\\alpha/2}$ or $f > F_{\\alpha/2}$ | $2\\min(P(F \\leq f),\\,P(F \\geq f))$ |\n\n**CI for $\\sigma_1^2/\\sigma_2^2$:**\n\n$$\\left(\\frac{s_1^2/s_2^2}{F_{\\alpha/2,\\,n_1-1,\\,n_2-1}},\\;\\; \\frac{s_1^2/s_2^2}{F_{1-\\alpha/2,\\,n_1-1,\\,n_2-1}}\\right)$$\n\nNote: use the reciprocal property $F_{1-\\alpha/2,\\,m,n} = 1/F_{\\alpha/2,\\,n,m}$.\n\n## Medical Example: Comparing Lab Variability\n\n**Study:** Two clinical labs each measure serum potassium (mEq/L) on the same patient samples.\n\n- Lab 1: $n_1 = 16$, $s_1 = 0.38$ mEq/L\n- Lab 2: $n_2 = 21$, $s_2 = 0.22$ mEq/L\n\nTest $H_0: \\sigma_1^2 = \\sigma_2^2$ vs. $H_a: \\sigma_1^2 > \\sigma_2^2$ at $\\alpha = 0.05$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nn1 <- 16; s1 <- 0.38\nn2 <- 21; s2 <- 0.22\n\nf_stat <- s1^2 / s2^2\ndf1    <- n1 - 1; df2 <- n2 - 1\n\np_val  <- pf(f_stat, df1 = df1, df2 = df2, lower.tail = FALSE)\n\nf_lo  <- qf(0.025, df1 = df1, df2 = df2)\nf_hi  <- qf(0.975, df1 = df1, df2 = df2)\nci_lo <- f_stat / f_hi;   ci_hi <- f_stat / f_lo\n\ncat(sprintf(\"F = %.3f  (df: %d, %d)  |  one-sided p = %.4f\\n\",\n            f_stat, df1, df2, p_val))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF = 2.983  (df: 15, 20)  |  one-sided p = 0.0120\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"95%% CI for sigma1^2/sigma2^2: (%.3f, %.3f)\\n\", ci_lo, ci_hi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI for sigma1^2/sigma2^2: (1.159, 8.222)\n```\n\n\n:::\n:::\n\n\n**Conclusion:** $F = 2.983$, $p = 0.012$. Strong evidence Lab 1 has greater measurement variability. Verify with `var.test()`.\n\n## F-Test in R and Sensitivity Warning\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(551)\nlab1 <- rnorm(16, mean = 4.2, sd = 0.38)\nlab2 <- rnorm(21, mean = 4.2, sd = 0.22)\n\nvar.test(lab1, lab2, alternative = \"greater\") |> tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 9\n  estimate num.df den.df statistic p.value conf.low conf.high method alternative\n     <dbl>  <int>  <int>     <dbl>   <dbl>    <dbl>     <dbl> <chr>  <chr>      \n1     3.04     15     20      3.04  0.0109     1.38       Inf F tes… greater    \n```\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-warning\n## The F-test is Extremely Sensitive to Non-Normality\n\nThe F-test for equality of variances assumes **exact normality** of both populations — far more sensitive than the t-test for means. For non-normal data:\n\n- **Levene's test** (`car::leveneTest()`) — uses absolute deviations from group medians; robust to non-normality\n- **Bartlett's test** (`bartlett.test()`) — equivalent power to F-test but also assumes normality\n\nIn medical research, the F-test for variances is most appropriate when normality is well-established (e.g., duplicate laboratory measurements). In most other settings, Levene's test is preferred.\n:::\n\n## F-Test Sensitivity to Non-Normality: Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(551)\nB <- 3000\n\nsim_ftest <- function(dist_fn, n = 20) {\n  map_dbl(1:B, function(i) {\n    var.test(dist_fn(n), dist_fn(n))$p.value\n  })\n}\n\ntibble(\n  p_value = c(\n    sim_ftest(function(n) rnorm(n)),\n    sim_ftest(function(n) rt(n, df = 3)),\n    sim_ftest(function(n) rexp(n)),\n    sim_ftest(function(n) rchisq(n, df = 5))\n  ),\n  Distribution = rep(\n    c(\"Normal\", \"t(3) - heavy tails\",\n      \"Exponential - right skew\", \"chi-sq(5) - right skew\"),\n    each = B\n  )\n) |>\n  group_by(Distribution) |>\n  summarise(RejectionRate = mean(p_value < 0.05)) |>\n  ggplot(aes(x = reorder(Distribution, RejectionRate),\n             y = RejectionRate, fill = Distribution)) +\n  geom_col(width = 0.55) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", linewidth = 1.2) +\n  scale_fill_brewer(palette = \"Set2\") +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.32),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(\n    title    = \"F-Test Type I Error Under H0 (equal variances) by Distribution Shape\",\n    subtitle = \"F-test is severely inflated for heavy-tailed and skewed data. Nominal level = 5%.\",\n    x        = NULL,\n    y        = \"Rejection Rate (alpha = 0.05)\",\n    fill     = NULL\n  ) +\n  coord_flip() +\n  theme(legend.position = \"none\",\n        axis.text.y = element_text(size = 13))\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-16-1.png){width=1248}\n:::\n:::\n\n\n# Complete Clinical Trial Example {background-color=\"#2c3e50\"}\n\n## Anticoagulant Trial: Applying All Methods\n\n**RCT:** New anticoagulant vs. standard of care in atrial fibrillation patients. Outcomes at 6 months: INR (continuous) and major bleeding events (binary).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(42)\nn_treat <- 80; n_ctrl <- 78\n\ninr_treat   <- rnorm(n_treat, mean = 2.5, sd = 0.6)\ninr_ctrl    <- rnorm(n_ctrl,  mean = 2.1, sd = 0.9)\nbleed_treat <- rbinom(n_treat, 1, 0.06)\nbleed_ctrl  <- rbinom(n_ctrl,  1, 0.13)\n\nwelch_res <- t.test(inr_treat, inr_ctrl) |> tidy()\nftest_res <- var.test(inr_treat, inr_ctrl) |> tidy()\nprop_res  <- prop.test(c(sum(bleed_treat), sum(bleed_ctrl)),\n                        c(n_treat, n_ctrl), correct = FALSE) |> tidy()\n\np1 <- tibble(\n  INR   = c(inr_treat, inr_ctrl),\n  Group = rep(c(\"Treatment\", \"Control\"), c(n_treat, n_ctrl))\n) |>\n  ggplot(aes(x = Group, y = INR, fill = Group)) +\n  geom_violin(alpha = 0.5, trim = FALSE) +\n  geom_boxplot(width = 0.15, fill = \"white\", outlier.shape = 1) +\n  scale_fill_manual(values = c(\"Treatment\"=\"#006a4e\",\"Control\"=\"#e74c3c\")) +\n  labs(title = \"INR at 6 Months\", x = NULL, y = \"INR\") +\n  theme(legend.position = \"none\")\n\nbleed_summ <- tibble(\n  Group = c(\"Treatment\",\"Control\"),\n  rate  = c(mean(bleed_treat), mean(bleed_ctrl)),\n  n     = c(n_treat, n_ctrl)\n) |>\n  mutate(se = sqrt(rate*(1-rate)/n),\n         lo = pmax(0, rate - qnorm(0.975)*se),\n         hi = rate + qnorm(0.975)*se)\n\np2 <- bleed_summ |>\n  ggplot(aes(x = Group, y = rate, color = Group)) +\n  geom_point(size = 6) +\n  geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.08, linewidth = 1.3) +\n  scale_color_manual(values = c(\"Treatment\"=\"#006a4e\",\"Control\"=\"#e74c3c\")) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.25)) +\n  labs(title = \"Major Bleeding Rate\", x = NULL, y = \"Rate\") +\n  theme(legend.position = \"none\")\n\np1 + p2 +\n  plot_annotation(\n    title    = \"Anticoagulant RCT: Two-Sample Analyses\",\n    subtitle = \"Left: continuous outcome (Welch t-test + F-test)   |   Right: binary outcome (z-test for proportions)\"\n  )\n```\n\n::: {.cell-output-display}\n![](18_TwoSampleTests_files/figure-revealjs/unnamed-chunk-17-1.png){width=1440}\n:::\n:::\n\n\n## Reading All Results Together\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"=== INR: Welch t-test ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== INR: Welch t-test ===\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"Treatment mean: %.2f | Control mean: %.2f\\n\",\n            mean(inr_treat), mean(inr_ctrl)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment mean: 2.51 | Control mean: 1.99\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"Difference: %.2f  (95%% CI: %.2f, %.2f)  p = %.4f\\n\",\n            welch_res$estimate, welch_res$conf.low,\n            welch_res$conf.high, welch_res$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: 0.52  (95% CI: 0.28, 0.75)  p = 0.0000\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"\\n=== INR: F-test for equal variances ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== INR: F-test for equal variances ===\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"S_treat = %.2f | S_ctrl = %.2f | F = %.3f | p = %.4f\\n\",\n            sd(inr_treat), sd(inr_ctrl),\n            ftest_res$statistic, ftest_res$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nS_treat = 0.64 | S_ctrl = 0.82 | F = 0.612 | p = 0.0312\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"\\n=== Bleeding Rate: Two-sample z-test ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Bleeding Rate: Two-sample z-test ===\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"Treatment: %.1f%%  |  Control: %.1f%%\\n\",\n            100*mean(bleed_treat), 100*mean(bleed_ctrl)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment: 7.5%  |  Control: 12.8%\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"Difference: %.1f%%  (95%% CI: %.1f%%, %.1f%%)  p = %.4f\\n\",\n            100*(prop_res$estimate1 - prop_res$estimate2),\n            100*prop_res$conf.low, 100*prop_res$conf.high,\n            prop_res$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: -5.3%  (95% CI: -14.7%, 4.1%)  p = 0.2677\n```\n\n\n:::\n:::\n\n\n# Key Takeaways {background-color=\"#2c3e50\"}\n\n## Key Takeaways: Means (DBC 9.5)\n\n::: callout-important\n## Two-Sample Tests for Means\n\n1. **Point estimator** $\\bar{X}_1 - \\bar{X}_2$ is unbiased; approximately normal by CLT (both $n_i$ large) or exact normality of populations\n\n2. **Welch t-test** (default): $T_W \\approx t_{\\hat\\nu}$; Satterthwaite df accounts for unequal variances; valid whether or not $\\sigma_1^2 = \\sigma_2^2$\n\n3. **Pooled t-test**: exact under normality + $\\sigma_1^2 = \\sigma_2^2$; requires strong prior justification — anti-conservative when variances differ and $n$'s are unequal\n\n4. **CI-test duality**: the $100(1-\\alpha)\\%$ CI for $\\Delta$ contains exactly the $\\Delta_0$ values for which the two-sided test fails to reject at level $\\alpha$\n:::\n\n## Key Takeaways: Proportions and Variances (DBC 9.6)\n\n::: callout-important\n## Two-Sample Tests for Proportions and Variances\n\n1. **Proportions (CLT):** $\\hat{p}_i$ is a sample mean of Bernoulli observations; CLT gives $\\hat{p}_1 - \\hat{p}_2 \\dot\\sim N(p_1-p_2, \\text{SE}^2)$; requires $n_i\\hat{p}_i \\geq 5$ and $n_i(1-\\hat{p}_i) \\geq 5$\n\n2. **Pooled vs. unpooled SE:** Use **pooled** $\\hat{p}$ for the test (exploits $H_0: p_1 = p_2$); use **unpooled** for the CI (no such assumption)\n\n3. **F-test:** $S_1^2/S_2^2 \\sim F_{n_1-1,\\,n_2-1}$ under normality and $H_0: \\sigma_1^2 = \\sigma_2^2$; the CI for $\\sigma_1^2/\\sigma_2^2$ is asymmetric\n\n4. **Sensitivity:** The F-test for variances is *extremely* sensitive to non-normality — prefer Levene's test in practice for most biomedical data\n\n5. **Always report** point estimates + CIs; choose the effect measure (RD, RR, OR) that is most interpretable in context\n:::\n\n## Looking Ahead\n\n**Next class: Analysis of Paired Data (DBC 10.3)**\n\n- When to use a paired design (pre/post, crossover trials, matched pairs)\n- Reduction to one-sample problem: $D_i = X_{1i} - X_{2i}$\n- Paired t-test, Wilcoxon signed-rank test, sign test\n\n. . .\n\n**Lesson 20:** Bootstrap and permutation methods for two samples; course review\n\n## References\n\n::: nonincremental\n- Devore, Berk, and Carlton. *Modern Mathematical Statistics with Applications* (Springer). Sections 9.5–9.6.\n- Welch, B. L. (1947). The generalization of 'Student's' problem when several different population variances are involved. *Biometrika*, 34(1–2), 28–35.\n- Chihara, L. M. and Hesterberg, T. C. *Mathematical Statistics with Resampling and R* (Wiley). Chapter 3.\n:::\n\n## Questions? {.center background-color=\"#3498db\"}\n\nThank you!\n\n\n",
    "supporting": [
      "18_TwoSampleTests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}